### ISSUE TITLE
[Other] Migration tasks

### ISSUE THREAD

**Issue by tarioch** [paperless-ngx/paperless-ngx#1]
- [x] rename repository to paperless-ngx
- [x] docker registry (use github registry?)
- [x] readthedocs
- [x] translations (crowdin)
- [x] chat/gitter
- [x] update readme with locations and some infos about the fork
- [x] dependabot
- [x] Coveralls
- [ ] Codacity
- [ ] Dissemination of new project: see #98

**Comment by a17t** [comment]
I will update the readme tomorrow, add some initial info about the fork and links to matrix room and the issues in the original repository. 

I will also replace paperless-ng with paperless-ngx.

**Comment by qcasey** [comment]
Ping me with how that goes, I'm curious how well the branch protection works

**Comment by qcasey** [comment]
> How do we proceed with the issues of the original repository? Do we move them over as well?

We technically can, but some have mentioned it would be better to start with a clean slate as many of those issues are stale by now. Perhaps asking people to resubmit here if they're still encountering the same problems.

I'd be happy to put the issue to a vote/discussion.

**Comment by sbrunner** [comment]
The Docker registry point is not finish, see my comment here: https://github.com/paperless-ngx/paperless-ngx/issues/76

**Comment by qcasey** [comment]
Do we still want to implement Codacity? That seems to be the final task for this issue

**Comment by sbrunner** [comment]
I'm not a maintainer, but I prefer a tool like Prospector because we can run it locally and the configuration is in the repository (instead of stored on a website).

**Comment by qcasey** [comment]
I don't have experience in either, but I think introducing one or the other should be a new issue. Doesn't need to be included in the 1.6.0 release. 

That being said I'll close this. All other minor tasks have been completed and we're now awaiting/tracking the milestone.
