### ISSUE TITLE
[BUG] Documents not being consumend and being queued

### ISSUE THREAD

**Issue by cristiangauma** [paperless-ngx/paperless-ngx#1003]
### Description

Hello,

since a few days ago I've not been able to consume any PDF uploaded to the app. 

It all started when I tried to consume a corrupt PDF which I thought was a good one. After trying to upload it, paperless hasn't been able to consume any other PDF.

The only thing that I see in the logs is that the PDFs that I upload (using the drag&drop or the consume directory) are queued on the consume queue, but as the elements are not being consumed the only thing that I see on the logs are that the queue is growing (you'll see it in the logs `09:11:47 [Q] INFO Enqueued 8`)

I've tried to restart the container (I'm using the Linuxserver.io one) several times but didn't work, and it doesn't print any error messages no matter how much time has been working (it has been working for more than 24 hours but the documents are not being consumed).

Also, the CPU/Memory consumption are normal, so the consumer is actually iddle.

Is there a way to clear the consume queue or see the elements that are being consumed just to know what could be happening?

### Steps to reproduce

1. Uploaded a corrupt PDF (can't share, has personal information, sorry)
2. Consumer stopped to consume any other PDF that I try to upload.

### Webserver logs

```bash
09:09:05 [Q] INFO recycled worker Process-1:7
09:09:05 [Q] INFO Process-1:9 ready for work at 668
09:10:00 [Q] INFO Enqueued 1
09:10:00 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
09:10:00 [Q] INFO Process-1:8 processing [hotel-magazine-cola-ceiling]
09:10:05 [Q] INFO Process-1:8 stopped doing work
09:10:05 [Q] INFO Processed [hotel-magazine-cola-ceiling]
09:10:05 [Q] INFO recycled worker Process-1:8
09:10:05 [Q] INFO Process-1:10 ready for work at 670
09:11:00 [Q] INFO Enqueued 1
09:11:00 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
09:11:00 [Q] INFO Process-1:9 processing [steak-ack-beryllium-eleven]
09:11:05 [Q] INFO Process-1:9 stopped doing work
09:11:06 [Q] INFO Processed [steak-ack-beryllium-eleven]
09:11:06 [Q] INFO recycled worker Process-1:9
09:11:06 [Q] INFO Process-1:11 ready for work at 672
09:11:47 [Q] INFO Enqueued 8
09:12:01 [Q] INFO Enqueued 1
09:12:01 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
09:12:01 [Q] INFO Process-1:10 processing [oklahoma-venus-robin-cold]
09:12:06 [Q] INFO Process-1:10 stopped doing work
09:12:06 [Q] INFO Processed [oklahoma-venus-robin-cold]
09:12:06 [Q] INFO recycled worker Process-1:10
09:12:06 [Q] INFO Process-1:12 ready for work at 685
09:13:01 [Q] INFO Enqueued 1
09:13:01 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
09:13:01 [Q] INFO Process-1:11 processing [bulldog-texas-washington-lima]
09:13:06 [Q] INFO Process-1:11 stopped doing work
09:13:06 [Q] INFO Processed [bulldog-texas-washington-lima]
```

### Paperless-ngx version

1.7.1

### Host OS

RockyLinux

### Installation method

Docker

**Comment by shamoon** [comment]
Did you look under Tasks in the Admin (Django backend)? As you’re using lsio container I will just say it’s possible there’s an issue present there that isn’t here. I haven’t quite seen this issue reported before.

**Comment by cristiangauma** [comment]
Yes, I've already checked the Django Admin, and I haven't seen anything abnormal there.

I guess you are asking about the `[Failed tasks]`, but the last failed task that I have is from some weeks ago (while configuring the mail check). But there is nothing during the last days.

I've been thinking: does the queue processor use redis to manage the queues?. If so, I could access to the redis instance and just delete the keys there. Would it work or would I brake something internally?

**Comment by stumpylog** [comment]
I'd be curious to know what the management commands of django-q outputs: https://django-q.readthedocs.io/en/latest/monitor.html

**Comment by cristiangauma** [comment]
Here you have a screenshot (I've just deleted the SECRET_KEY from the picture. It is not that important as this is a private installation, but whatever :) ).

<img width="724" alt="screenshot" src="https://user-images.githubusercontent.com/1321112/169717455-f8a0ae61-39a5-4232-9af4-1157270feea3.png">

**Comment by stumpylog** [comment]
Well, 0 clusters and 0 workers, no wonder nothing is being processed.  At a guess, the cluster isn't starting for some reason.  Any messages on restart about the Q Cluster starting/read for work/running?

**Comment by Profex** [comment]
Not sure if this is connected, but as per screenshot Redis 7.0.0 is used in this case. Is this version compatible?
All compose example files you provide only include`image: redis:6.0`

**Comment by stumpylog** [comment]
Good spot.  I tried my own example with Redis 7 and it had no problem starting or consuming files.  I suspect django_q doesn't do anything fancy with the broker that would have changed in a version update.

**Comment by cristiangauma** [comment]
Nope, I've just restarted it and I don't see any information that could give a clue about what is happening.

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1051
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 70-aliases: executing...
[cont-init.d] 70-aliases: exited 1.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] 99-migrations: executing...
No changes detected
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
[cont-init.d] 99-migrations: exited 0.
[cont-init.d] done.
[services.d] starting services
Waiting for redis to become available...
Waiting for redis to become available...
Waiting for redis to become available...
412:C 23 May 2022 21:09:34.364 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
412:C 23 May 2022 21:09:34.364 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=412, just started
412:C 23 May 2022 21:09:34.364 # Configuration loaded
[services.d] done.
412:M 23 May 2022 21:09:34.367 * Running mode=standalone, port=6379.
412:M 23 May 2022 21:09:34.367 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
412:M 23 May 2022 21:09:34.367 # Server initialized
412:M 23 May 2022 21:09:34.367 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
412:M 23 May 2022 21:09:34.367 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
412:M 23 May 2022 21:09:34.368 * Ready to accept connections
[2022-05-23 19:09:45 +0000] [409] [INFO] Starting gunicorn 20.1.0
[2022-05-23 19:09:45 +0000] [409] [INFO] Listening at: http://0.0.0.0:8000 (409)
[2022-05-23 19:09:45 +0000] [409] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2022-05-23 19:09:45 +0000] [409] [INFO] Server is ready. Spawning workers
19:09:47 [Q] INFO Q Cluster glucose-nineteen-robert-mountain starting.
19:09:47 [Q] INFO Process-1 guarding cluster glucose-nineteen-robert-mountain
19:09:47 [Q] INFO Process-1:2 ready for work at 461
19:09:47 [Q] INFO Process-1:1 ready for work at 460
19:09:47 [Q] INFO Process-1:4 pushing tasks at 463
19:09:47 [Q] INFO Q Cluster glucose-nineteen-robert-mountain running.
19:09:47 [Q] INFO Process-1:3 monitoring at 462
[2022-05-23 19:09:47,541] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /data/consume
19:10:17 [Q] INFO Enqueued 1
19:10:17 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
19:10:17 [Q] INFO Process-1:2 processing [harry-low-xray-salami]
19:10:18 [Q] INFO Process-1:2 stopped doing work
19:10:18 [Q] INFO Processed [harry-low-xray-salami]
19:10:18 [Q] INFO recycled worker Process-1:2
19:10:18 [Q] INFO Process-1:5 ready for work at 475
```

Once it has started, doing a `python3 manage.py qinfo` shows the same (`Clusters` and `Workers` at 0)

**Comment by stumpylog** [comment]
Best guess is the Redis keys have changed or been corrupted somehow.  If you're curious, you could try dumping all the keys to confirm.

Otherwise, I would stop the stack/container and clear out all Redis data so it can be completely re-created.  Anything queued would be lost, but no other data should be.  Obviously, I still suggest making a backup

**Comment by cristiangauma** [comment]
I'm closing the issue, sorry I have bothered you with this.

The Linuxserver.io paperless-ngx mantainers have changed the Redis host environment variable, so I don't know how, but paperless was pushing the elements to my desired Redis, but the consumers were connected to the Redis located in the same container (which was not the good Redis). I still don't know how it could happen as it doesn't make much sense, but I've just deleted the Redis environment variable so it uses the Redis located in the same container, and I can upload PDFs again without any issue.

Thank you for your hint about it being Redis :).

**Comment by eomanis** [comment]
> I would stop the stack/container and clear out all Redis data so it can be completely re-created. Anything queued would be lost, but no other data should be. Obviously, I still suggest making a backup

I am currently affected by this bug, and unfortunately for me, purging the Redis databases did not solve the issue. Documents are being enqueued but not processed; this applies both to when they are uploaded via the web interface and when they are put into the "add" directory.

My instance is running bare-metal with a Python virtual environment, and Redis communication goes through a Unix socket.
Redis re-creates the purged database files and its socket just fine.

I even added `After=paperless-redis.service` to the application server, scheduler and consumer services so that Redis is up and running when they are started, to no avail.

Any more ideas?
Is there some debugging configuration that logs who says what to Redis?

#### paperless.conf

```
PAPERLESS_REDIS=unix:///srv/paperless/redis/redis.sock

PAPERLESS_CONSUMPTION_DIR=/srv/paperless/add
PAPERLESS_DATA_DIR=/srv/paperless/data
PAPERLESS_MEDIA_ROOT=/srv/paperless/media
PAPERLESS_STATICDIR=/srv/paperless/webroot/static

PAPERLESS_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXXXX"
PAPERLESS_URL=https://theserver:3333
PAPERLESS_STATIC_URL=/static/

PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_OCR_OUTPUT_TYPE=pdf
PAPERLESS_CONVERT_TMPDIR=/srv/paperless/tmp

PAPERLESS_SCRATCH_DIR=/srv/paperless/uploads

PAPERLESS_TASK_WORKERS=2
PAPERLESS_CONSUMER_POLLING=10
```

#### redis.conf

```
# Configuration for the paperless-ng dedicated Redis server

# Disable TCP socket listening completely, an UNIX socket is used instead
# If port 0 is specified Redis will not listen on a TCP socket
port                 0
protected-mode       yes

# Listen on UNIX socket
# Redis URL:  unix:///srv/paperless/redis/redis.sock
unixsocket           /srv/paperless/redis/redis.sock
unixsocketperm       660

# Server behavior
timeout              0
daemonize            no
supervised           systemd
pidfile              /srv/paperless/redis/redis.pid
loglevel             warning
logfile              ""
databases            1
always-show-logo     no
set-proc-title       yes
proc-title-template  "{title} paperless-dedicated instance"
# Working directory; database files go here
dir                  /srv/paperless/redis/
# Default database file
dbfilename           dump.rdb
# Persist the DB after 300 seconds (5 minutes) if at least 1 key has changed
save                 300 1
# Write an additional append-only database file for increased crash resilience
appendonly           yes
appendfilename       appendonly.aof
appendfsync          everysec
```

**Comment by rantwolf** [comment]
> 

Same for me... dumbass. Also missed the new service '...task-queue.service'.

Thx for your help.
