### ISSUE TITLE
[BUG] Consumption triples scan-image

### ISSUE THREAD

**Issue by tefracky** [paperless-ngx/paperless-ngx#1005]
### Description

I use `scanimage` to scan different documents. Using the `color` mode, everything works fine, the documents are consumed, OCR is running and the document saved.

When I use the `lineart` mode, the document is scanned correctly, however, during consumption/OCR recognition, the document is tripled and there is then 3 times the same document on one page.

Input: [Input.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8749311/2020-12-01.Uelzener.-.2022-05-22_13-26-25.pdf)
Output: [Output.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8749309/2020-12-01.Uelzener.-.2022-05-22_13-24-39.pdf)

### Steps to reproduce

1. Scan a document via `scanimage` using `lineart` color mode
2. Let Paperless consume the document

### Paperless-ngx version

1.7.1

### Host OS

Raspberry Pi arm64

### Installation method

Docker

**Comment by stumpylog** [comment]
Looks like an ocrmypdf issue.  Just a basic `ocrmypdf --skip-text "2020-12-01.Uelzener.-.2022-05-22_13-24-39.pdf" out.pdf` produces the tripled image output.  Very curious!

**Comment by stumpylog** [comment]
Hm, tossing both these files into 1.7.1, I get a matching looking output.  Have you made any configuration changes to the OCR settings?  For example setting the image DPI or custom arguments?

**Comment by tefracky** [comment]
Are you sure we are talking from the same files? The output does NOT look normal and like the input...

Attached as picture, maybe the PDF is shown in a different way.

![input](https://user-images.githubusercontent.com/4464088/169961109-c6cc3327-1714-4c34-ac28-aa6a6ee2c6bc.jpg)

![output](https://user-images.githubusercontent.com/4464088/169961112-d0bb8c9d-4b79-4d13-92df-86cf5c4338e1.jpg)

**Comment by stumpylog** [comment]
I've uploaded both the files and looked at them through the webui and just in a file browser.  I am running with amd64, as opposed to arm64, that might be relevant here.  I don't have a device to test with though.

**Comment by qcasey** [comment]
I also cannot replicate this on `aarch64` with either 1.7.1 or ocrmypdf directly

**Comment by tefracky** [comment]
Okay, that's very strange... Thanks a lot for testing! Maybe it is a problem like "occurs and go by itself".
