### ISSUE TITLE
[BUG] Renaming of tags or correspondent does not reflect in filesystem

### ISSUE THREAD

**Issue by fishi0x01** [paperless-ngx/paperless-ngx#1006]
### Description

Renaming of `PAPERLESS_FILENAME_FORMAT` components does not reflect in filesystem, unless re-applied manually.

I assume [update_filename_and_move_files](https://github.com/paperless-ngx/paperless-ngx/blob/8e9d1cdd18dcd6bf215231e64614704e7d8dc194/src/documents/signals/handlers.py#L312) should be called on all affected document keys when changes are saved to [DocumentType](https://github.com/paperless-ngx/paperless-ngx/blob/8e9d1cdd18dcd6bf215231e64614704e7d8dc194/src/documents/models.py#L82), [Correspondent](https://github.com/paperless-ngx/paperless-ngx/blob/8e9d1cdd18dcd6bf215231e64614704e7d8dc194/src/documents/models.py#L57) and [Tag](https://github.com/paperless-ngx/paperless-ngx/blob/8e9d1cdd18dcd6bf215231e64614704e7d8dc194/src/documents/models.py#L64)?

### Steps to reproduce

1. PAPERLESS_FILENAME_FORMAT={correspondent}/{document_type}/{created_year}/{title}
2. set correspondent `my-correspondent` on a document -> you should see `my-correspondent` as dir on fs
3. rename `my-correspondent` -> `my-other-correspondent`. The dir will not be renamed, unless you re-apply that correspondent in document in UI

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04

### Installation method

Docker

**Comment by shamoon** [comment]
I believe you need to run the [document_renamer](https://paperless-ngx.readthedocs.io/en/latest/administration.html#managing-filenames)

TBH Im not sure why Paperless doesnt run the rename after editing tags correspondents / doc types
