### ISSUE TITLE
[Other] Unforking paperless-ngx

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#101]
It's been discussed to "un-fork" this repo, detaching it in Github's UI from jonaswinkler's. 

This would have a number of benefits:

1. Show branches' commit status against our own (X commits ahead of YY).
2. Remove the "fetch upstream" button.
3. PRs would target our `dev` instead of Jonas' by default.
4. Github code search feature would function.

From @dblitt in chat:

> This process seems to be one way, so I won't push to do this immediately, but I will note the above benefits and the fact that jonaswinkler/paperless-ng isn't a GH fork itself. 

> I believe the only downside is that we won't be listed on the list of forks of paperless-ng and we won't have the badge saying "forked from jonaswinkler/paperless-ng"

The process seems simple enough here: https://ralphjsmit.com/unfork-github-repo/

I suggested this should be done once we're recognized as the successor project (i.e. #98). Are there any objections to that plan?

**Comment by gador** [comment]
No objections. I agree with the statement that we should unfork.

**Comment by skorvek** [comment]
Agree. We can make the lineage very clear in updated documentation.

**Comment by sytone** [comment]
Agreed, it will make it clearer for future collaboration and we just need to ensure documentation has this in it.

**Comment by amo13** [comment]
Does @jonaswinkler know about this fork and did he make any statement about his plans to further maintain or abandon his paperless-ng?

**Comment by qcasey** [comment]
> Does @jonaswinkler know about this fork and did he make any statement about his plans to further maintain or abandon his paperless-ng?

He hasn't responded, see https://github.com/jonaswinkler/paperless-ng/issues/1599. Of course if he does return, he'd be welcome back to this project.

**Comment by amo13** [comment]
Wow, I see, there has been a lot going on! That's why I love open source :)
So that's at least 23 participants supporting this fork and half a year of Jonas' absence on the ng repo without response.

**Comment by sbrunner** [comment]
This should be done throw a support ticket, see also: https://ralphjsmit.com/unfork-github-repo/

**Comment by qcasey** [comment]
This has been completed. 

This marks the [first milestone](https://github.com/paperless-ngx/paperless-ngx/milestone/1) completed. Thank you to everyone for a successful community migration, looking fwd to many more years of this.
