### ISSUE TITLE
[BUG] Language not switching after saving

### ISSUE THREAD

**Issue by tooomm** [paperless-ngx/paperless-ngx#1029]
### Description

When the user adjusts the language setting of Paperless and saves the changes in the settings, there is no live update of the languages as expected.

The minimum would be a notification or hint telling the user that they need to login again to make the changes take effect.

### Steps to reproduce

1. Go to settings
2. Change language
3. Save

### Webserver logs

*No response*

### Paperless-ngx version

1.7.1

### Host OS

demo.paperless-ngx.com

### Installation method

Docker

### Browser

Firefox

### Configuration changes

demo.paperless-ngx.com

**Comment by shamoon** [comment]
There is a hint for this right below the field. See below

![Settings - Paperless-ngx](https://user-images.githubusercontent.com/4887959/170320496-720521ac-ab56-4536-8bd8-42757e2de5d1.png)

**Comment by tooomm** [comment]
Indeed! I had to login again to spot that one. 😄 

It would be way more visible and obvious though, if it would show up not until after changing the selection (and in e.g. a highlight color)! Especially since the behavior differs from all other settings.

**Comment by shamoon** [comment]
Well I guess Im a sucker for a feature request 😅

**Comment by tooomm** [comment]
The reload button in your solution is a nice addition as well, cool.
