### ISSUE TITLE
[BUG] High consumption usage, bringing raspberry pi down

### ISSUE THREAD

**Issue by arnavpraneet** [paperless-ngx/paperless-ngx#1040]
### Description

Paperless has suddenly started grinding the Raspberry Pi to a halt and the tika server appears to be the cause

![image](https://user-images.githubusercontent.com/30770259/170707428-4204af07-f81b-4622-a09c-3937e8a0ea3d.png)
Paperless Tika Logs

![image](https://user-images.githubusercontent.com/30770259/170707525-c0767a5f-2fb7-4f7b-ab5a-5140e6620cf1.png)
Paperless Gotenberg Logs

![image](https://user-images.githubusercontent.com/30770259/170707629-32d1f760-f4f5-4bf1-a446-adf4e4c4e6d4.png)
Paperless Broker Logs (just 3 minutes before resource spike rendered Raspberry Pi inaccessible)

![image](https://user-images.githubusercontent.com/30770259/170707897-3f682a83-cd0d-4d30-a756-56fed49ccfce.png)
Paperless Webserver logs (same as above)

### Steps to reproduce

1. Run paperless-ngx in docker on Raspberry Pi (Dietpi, 3B+ ARM64)
2. Rendered inaccessible after a few minutes specifically due to Paperless (doesn't occur without it running)

### Webserver logs

```bash
self.start()
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 172, in start
    self.spawn_cluster()
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 248, in spawn_cluster
    self.pusher = self.spawn_pusher()
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 201, in spawn_pusher
    return self.spawn_process(pusher, self.task_queue, self.event_out, self.broker)
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 197, in spawn_process
    p.start()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.9/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 347, in pusher
    logger.error(e, traceback.format_exc())
Message: ConnectionError('Connection closed by server.')
Arguments: ('Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 345, in pusher\n    task_set = broker.dequeue()\n  File "/usr/local/lib/python3.9/site-packages/django_q/brokers/redis_broker.py", line 21, in dequeue\n    task = self.connection.blpop(self.list_key, 1)\n  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1900, in blpop\n    return self.execute_command(\'BLPOP\', *keys)\n  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command\n    return self.parse_response(conn, command_name, **options)\n  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response\n    response = connection.read_response()\n  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 739, in read_response\n    response = self._parser.read_response()\n  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 470, in read_response\n    self.read_from_socket()\n  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 429, in read_from_socket\n    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)\nredis.exceptions.ConnectionError: Connection closed by server.\n',)
18:46:36 [Q] ERROR Error -5 connecting to broker:6379. No address associated with hostname.
18:46:36 [Q] ERROR Error -5 connecting to broker:6379. No address associated with hostname.
18:46:37 [Q] ERROR Error -5 connecting to broker:6379. No address associated with hostname.
18:46:37 [Q] ERROR Error -5 connecting to broker:6379. No address associated with hostname.
18:46:38 [Q] ERROR Error -5 connecting to broker:6379. No address associated with hostname.
2022-05-27 13:16:38,226 WARN received SIGTERM indicating exit request
2022-05-27 13:16:38,347 INFO waiting for consumer, gunicorn, scheduler to die
2022-05-27 13:16:39,392 INFO reaped unknown pid 74 (terminated by SIGTERM)
2022-05-27 13:16:39,396 INFO reaped unknown pid 75 (terminated by SIGTERM)
2022-05-27 13:16:39,398 INFO reaped unknown pid 1572 (terminated by SIGTERM)
2022-05-27 13:16:39,399 INFO reaped unknown pid 1591 (terminated by SIGTERM)
2022-05-27 13:16:41,405 INFO waiting for consumer, gunicorn, scheduler to die
2022-05-27 13:16:44,413 INFO waiting for consumer, gunicorn, scheduler to die
2022-05-27 13:16:47,420 INFO waiting for consumer, gunicorn, scheduler to die
2022-05-27 13:16:47,536 INFO stopped: scheduler (exit status 0)
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis: redis://broker:6379
Connected to Redis broker: redis://broker:6379
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Executing /usr/local/bin/supervisord -c /etc/supervisord.conf
2022-05-27 13:20:54,569 INFO Set uid to user 0 succeeded
2022-05-27 13:20:54,592 INFO supervisord started with pid 1
2022-05-27 13:20:55,602 INFO spawned: 'consumer' with pid 35
2022-05-27 13:20:55,617 INFO spawned: 'gunicorn' with pid 36
2022-05-27 13:20:55,630 INFO spawned: 'scheduler' with pid 37
2022-05-27 13:20:56,635 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-27 13:20:56,636 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-27 13:20:56,637 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-05-27 18:50:59 +0530] [36] [INFO] Starting gunicorn 20.1.0
[2022-05-27 18:50:59 +0530] [36] [INFO] Listening at: http://0.0.0.0:8000 (36)
[2022-05-27 18:50:59 +0530] [36] [INFO] Using worker: paperless.workers.ConfigurableWorker
[2022-05-27 18:50:59 +0530] [36] [INFO] Server is ready. Spawning workers
18:51:07 [Q] INFO Q Cluster mirror-oscar-hot-lion starting.
18:51:07 [Q] INFO Process-1:1 ready for work at 71
18:51:07 [Q] INFO Process-1:2 ready for work at 72
18:51:07 [Q] INFO Process-1 guarding cluster mirror-oscar-hot-lion
18:51:07 [Q] INFO Q Cluster mirror-oscar-hot-lion running.
18:51:07 [Q] INFO Process-1:4 pushing tasks at 74
18:51:07 [Q] INFO Process-1:3 monitoring at 73
[2022-05-27 18:51:07,933] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf to the task queue.
18:51:07 [Q] INFO Enqueued 1
[2022-05-27 18:51:07,963] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/src/../consume
18:51:07 [Q] INFO Process-1:1 processing [mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf]
[2022-05-27 18:51:10,850] [ERROR] [paperless.consumer] Not consuming mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf: It is a duplicate.
18:51:10 [Q] INFO Process-1:1 stopped doing work
18:51:11 [Q] ERROR Failed [mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf] - mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf: Not consuming mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf: It is a duplicate. : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 298, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 213, in try_consume_file
    self.pre_check_duplicate()
  File "/usr/src/paperless/src/documents/consumer.py", line 110, in pre_check_duplicate
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 81, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf: Not consuming mahim_khan_8f6c56a1ad1d35c86351991a0f5f975f2907a1fb.pdf: It is a duplicate.
18:51:11 [Q] INFO recycled worker Process-1:1
18:51:11 [Q] INFO Process-1:5 ready for work at 89
18:51:37 [Q] INFO Enqueued 1
18:51:37 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
18:51:37 [Q] INFO Process-1:2 processing [low-two-magnesium-blue]
18:51:37 [Q] INFO Process-1:2 stopped doing work
18:51:37 [Q] INFO Processed [low-two-magnesium-blue]
18:51:37 [Q] INFO recycled worker Process-1:2
18:51:37 [Q] INFO Process-1:6 ready for work at 91
```

### Paperless-ngx version

1.7.1

### Host OS

DietPi ARM64

### Installation method

Docker

### Browser

Firefox

### Configuration changes

None

**Comment by qcasey** [comment]
Thanks for reporting. Could you post your `docker-compose.yml`?

**Comment by arnavpraneet** [comment]
`# docker-compose file for running paperless from the docker container registry.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware. The apache/tika image
# does not support arm or arm64, however.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# SQLite is used as the database. The SQLite file is stored in the data volume.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Apache Tika and Gotenberg servers are started with paperless and paperless
#   is configured to use these services. These provide support for consuming
#   Office documents (Word, Excel, Power Point and their LibreOffice counter-
#   parts.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/expansion/DocumentStore:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/expansion/Documents:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  redisdata:`


Here you go

**Comment by arnavpraneet** [comment]
`version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/expansion/DocumentStore:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/expansion/Documents:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: gotenberg/gotenberg:7
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  redisdata:`



Here you go:

**Comment by slankes** [comment]
Not sure if this is relevant but right now the upstream repo is fixing gotenberg to gotenberg/gotenberg:7.4 which is older than :7 
Also the tika images is not the current one - paperless now uses one that is hosted by paperless-ngx and is claimed to be "arm compatible". Maybe using that fixes the issue for you.

**Comment by arnavpraneet** [comment]
> Not sure if this is relevant but right now the upstream repo is fixing gotenberg to gotenberg/gotenberg:7.4 which is older than :7 Also the tika images is not the current one - paperless now uses one that is hosted by paperless-ngx and is claimed to be "arm compatible". Maybe using that fixes the issue for you.

Tried this out, changed the Docker-Compose with the new Gotenberg and Tika images and all, checked and ran, issue still persists. To note, issue is there running webserver and broker without Tika and Gotenberg too

**Comment by slankes** [comment]
Something is not right here: The error clearly starts with the "exec format error". So that seems to be related to the wrong image format for tika.

**Comment by slankes** [comment]
Maybe we need to come to the conclusion that 1 GB of Memory is just not enough to run the full stack ...

**Comment by eloo** [comment]
@slankes the error "exec format error" mostly indicates that the image/binary was build for the wrong architecture

so maybe in this case its build for a x86-64 system and not an arm system what the RPI actually is. 
so you need to use an arm image of tika if possible (not sure if there is one)

nevertheless i guess 1GB of ram is not enough for the whole stack. 

best regards

**Comment by arnavpraneet** [comment]
Even going without the tika and Gotenberg issues, I had this stack running for at least 1 month without any issues. The only high system load I got was the expected one when I stuffed a bunch of documents into the consume folder, which slowed the Pi down, but otherwise, the stack was running fine imo, so I am not sure what changed that suddenly rendered it unable to run the stack ;-;
I do have virtual machines I can run this on, but just preferred having the documents on my hard disk, that's why it's on the Pi.

**Comment by azN2** [comment]
what are the general system requirements?

**Comment by AlRo75** [comment]
Maybe that will help. My Raspi runs with it without any problems.

[https://github.com/paperless-ngx/paperless-ngx/discussions/729](url)
