### ISSUE TITLE
[BUG] Download filename only contains created date when title is empty, even though correspondent is set

### ISSUE THREAD

**Issue by nepomuc** [paperless-ngx/paperless-ngx#1052]
### Description

When a document has not title, but a correspondent: When downloading such a document, the filename only contains the create date followed by a space and then the extension. So the correspondent is missing in the filename, even though it's set. As soon as that document has a title which is not empty, the filename contains the create date, the correspondent and the title.
What should happen: Even when there's no title, the filename should still contain the create date and the correspondent if they are != "".

### Steps to reproduce

1. Upload a sample document
2. Fill out the create date and the correspondent but NOT the title.
3. Click the download button for this document.

### Webserver logs

Nothing gets logged when reproducing this issue.

### Paperless-ngx version

1.7.1

### Host OS

Debian 11

### Installation method

Docker

### Browser

Brave 1.39.111

**Comment by stumpylog** [comment]
Well, I wouldn't say this is a bug exactly.  This formatting has been mostly this way since the project was just paperless.  I imagine It's pretty unexpected to have a document with no title.

It is changeable though, if there is a desire from the community for it.

**Comment by shamoon** [comment]
I agree, what really is the use case for no title anyway?

**Comment by nepomuc** [comment]
@shamoon In my case for example I've got a lot of documents which are perfectly described by the created date, the correspondent and the document type. No further information like a title needed. This is the case for documents of recurring things like loan, subscriptions etc.

**Comment by stumpylog** [comment]
The space following the date is only there because the title is blank.  Normally, it would be the space followed by title.  Not really a bug, just an unexpected user use case.

The good new is, despite this coming from a pretty fundamental location, it doesn't appear to break anything to change this.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/2abe6eec842cb3f1e901eff6d5d7e0008e878bd4
