### ISSUE TITLE
[BUG] When time of created date is 00:00 the download filename contains the date of the day before.

### ISSUE THREAD

**Issue by nepomuc** [paperless-ngx/paperless-ngx#1054]
### Description

When a document has a created date where the time of day is 00:00 the download filename will contain the date of the day before. At first I thought about a timezone issue, but my docker-compose.env has the correct PAPERLESS_TIME_ZONE.

### Steps to reproduce

1. Upload a sample document
2. Go to the Administration section, open the document and set the time of the created date to 00:00.

I also tried to reproduce how documents can end up having a created date with the time part being exactly 00:00. I was not able to reproduce that, but still paperless-ngx should handle that properly, since e.g. 2022-05-31 00:00 is already 2022-05-31 and not 2022-05-30. :)

### Webserver logs

```bash
No logs for this issue.
```

### Paperless-ngx version

1.7.1

### Host OS

Debian 11

### Installation method

Docker

**Comment by tooomm** [comment]
https://github.com/paperless-ngx/paperless-ngx/pull/942 probably fixes this already.
