### ISSUE TITLE
[BUG] tesseract warning in log

### ISSUE THREAD

**Issue by bin101** [paperless-ngx/paperless-ngx#1093]
### Description

I think this is a low priority issue and most likely? upstream related.

Currently I get a few warning per day:

```
[2022-06-03 20:25:19,049] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.aiim.org/pdfa/ns/extension/}schemas: {'\n                  '}. Error: 'http://www.aiim.org/pdfa/ns/extension/'
```

If I follow the [link ](http://www.aiim.org/pdfa/ns/extension)it results in a 404

### Steps to reproduce

1. import some files
2. check the log

### Paperless-ngx version

1.7.1

### Host OS

debian bullseye

### Installation method

Bare metal

**Comment by stumpylog** [comment]
This is likely just a slight difference in whatever application is creating the PDFs vs what metadata is standardized.  It doesn't affect much, if anything at all.

See also: https://paperless-ngx.readthedocs.io/en/latest/troubleshooting.html#error-while-reading-metadata
