### ISSUE TITLE
[BUG] Wrong docs on creating superuser during setup

### ISSUE THREAD

**Issue by SystemZ** [paperless-ngx/paperless-ngx#1094]
### Description

Setup docs from https://paperless-ngx.readthedocs.io/en/latest/setup.html and comments in docker-compose examples  https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite.yml are suggesting: 

>To be able to login, you will need a super user. To create it, execute the following command:
>docker-compose run --rm webserver createsuperuser

But such file doesn't exist, also default docker image cmd isn't python3 manage.py to allow this shortcut

```
docker exec -it paperless createsuperuser

OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "createsuperuser": executable file not found in $PATH: unknown
```

Related: https://github.com/paperless-ngx/paperless-ngx/issues/884

### Steps to reproduce

1. `docker exec -it paperless createsuperuser`

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04

### Installation method

Docker

**Comment by shamoon** [comment]
Those two commands are not the same though and the docs are written for compose. `docker-compose run...` creates a new container using the config specified in you compose file e.g. "webserver" or whatever you call it. `docker exec...` runs in an existing container. Here's a more detailed explanation: https://stackoverflow.com/questions/65100572/docker-compose-difference-run-exec-and-what-happens-to-the-layers

If you'd like to  use exec, try `docker exec -it paperless bash` and then `python3 manage.py createsuperuser`
