### ISSUE TITLE
[Other] Use a named volume for broker

### ISSUE THREAD

**Issue by SvenFlock** [paperless-ngx/paperless-ngx#112]
Hi all,

I am a fan to keep the volumes well organized. Though there are already three Docker volumes defined there is a new volume with a hashkey popping up in a regular manner.

Is there a way to name the volume properly that the volumes are not messed up?

Thanks
<img width="1244" alt="Screenshot 2022-02-20 at 16 38 42" src="https://user-images.githubusercontent.com/84663902/154850843-f47f8eb6-a27f-4ed2-9727-cdfaceb1fa13.png">
<img width="1244" alt="Screenshot 2022-02-20 at 16 38 52" src="https://user-images.githubusercontent.com/84663902/154850850-dec05cc4-9e72-4547-9b31-ac7f68544265.png">

**Comment by qcasey** [comment]
Done in #132

**Comment by SvenFlock** [comment]
Thanks, that was quick :-). How is your release cycle? When will the dev branch merged into main? Thanks

**Comment by qcasey** [comment]
Welcome! :) 

There isn't a process in place yet, although in the last few days we've been talking more about a release. See the [1.6.0 milestone](https://github.com/paperless-ngx/paperless-ngx/milestone/1)

I'm guessing early March.
