### ISSUE TITLE
[Other] Remove support for Python 3.7 

### ISSUE THREAD

**Issue by isigmund** [paperless-ngx/paperless-ngx#114]
as discussed on https://app.element.io/#/room/#paperless:adnidor.de we agreed to drop support for python 3.7 in order to be able to merge depandabot PRs #92, #93, #94, #95, #96 , which currently fail the 3.7 pipeline tests.

Todo:

- [ ] Adapt CI workflow and remove tests on python 3.7
- [ ] Identify documentation references to Python 3.7 and correct those

**Comment by shamoon** [comment]
This should help address some of the [many] security warnings

**Comment by yschroeder** [comment]
Done via #142.
