### ISSUE TITLE
[BUG] Downloaded file date in filename is one day off

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1153]
### Description

Every file which is downloaded via the WebGUI has a wrong date (one day before the correct day) in the filename.

I know there is another bug which affects UTC and situations were it can overlap due to different timezones. But this is different as it seems it happens with all my documents.

In the archive and original folder, filename with dates are correct. They are also correct shown in the WebGUI field  "Date created".

### Steps to reproduce

1. Download any document via the WebGUI.
2. Look at the date in the filename.

### Paperless-ngx version

1.7.1

### Host OS

gentoo x86_64

### Installation method

Docker

**Comment by r2ixuz** [comment]
NVM it is already fixed in an upcoming (hopefully soon... ;-) ) release: https://github.com/paperless-ngx/paperless-ngx/issues/1036

Tested with Docker tags: "feature-frontend-task-queue" and "feature-prevent-text-dupe-api-calls". On both it works as expected.

**Comment by shamoon** [comment]
Glad to know the fix works thank you. Yes next release will likely need some thorough testing before release and a few team members are AFK at the moment but hopefully soon!
