### ISSUE TITLE
[BUG] Permission setting ignored

### ISSUE THREAD

**Issue by Torxgewinde** [paperless-ngx/paperless-ngx#1160]
### Description

I configured a user and just granted permission to view documents, tags etc. 
Even without giving any other permissions, this user can add/delete documents and details.

Removing ALL permissions and logging in as such a user still allows deleting/adding/editing documents and details.

Solely accessing the "Admin" area is blocked by not assigning "employee" status.

### Steps to reproduce

1. Create new user: SomeName, assign a password, proceed
2. Assign no permissions, just leave the defaults. The rightmost boxes remain empty. Do not check "admin" permission, do not tick "employee" checkbox
3. Save the user, logoff, login as this new user
4. Go to documents, delete or add a document --> it will delete or add the document regardless of the permission

### Paperless-ngx version

1.7.1

### Host OS

Running in a Debian Bullseye chroot

### Installation method

Bare metal

### Browser

Firefox

**Comment by shamoon** [comment]
Multi-user permissions are not yet implemented, see https://github.com/paperless-ngx/paperless-ngx/discussions/295

**Comment by Torxgewinde** [comment]
May I suggest to add a hint in the documentation, explaining that this is not implemented (yet)? Currently the permission-settings are visible, but not working as expected - which is confusing IMHO.

**Comment by askielboe** [comment]
I don't get it. The discussion linked seems to talk about permissions per tag, or something (it's not clear what they are talking about). This issue here is about the existing User permissions settings, which seem to not work. It this intended? Why are they part of the UI if they don't work?

**Comment by askielboe** [comment]
I asked for clarification on https://github.com/paperless-ngx/paperless-ngx/discussions/295 and that feature suggestion does not seem related to this issue at all. This issue seems to be about the problem that the existing user permissions feature is not working, while the "Multi user permission support" feature request (#295) is all about document-specific permissions which is something else entirely.

I have the same issue as @Torxgewinde above and would love some advice on how to troubleshoot. 🙏

**Comment by shamoon** [comment]
There is nothing to troubleshoot as there is no bug. Plainly, permissions for multiple users is not implemented in any meaningful way yet. Django comes with the ability to create users etc out of the box so I understand that could be misleading.

It’s a big job, I think most of us on the development team would like to tackle it some day. I am not aware of anyone actively working on it.

The linked feature request is for now probably the best place to watch / discuss.

**Comment by askielboe** [comment]
Thanks for your reply. This is still a bit confusing to me, not knowing Django, but I guess whet you're saying is that the permissions listed on the user settings in the admin panel are somehow auto generated by Django, including the UI to manage them etc, but the actual logic to implement the permissions into the app is not implemented?

Also, perhaps "multi user permissions" makes perfect sense to someone who know what that means, but as far as I can tell there are no user permissions at all, not for single users, nor for multiple users.

I fully understand you not wanting to prioritize this, and I don't think that's what anyone here is asking, I'm simply confused and ignorant about the nomenclature used and the fact that there are settings in the app which has no effect when applied. I hope it will be slightly more clear now for people finding this issue in the future.

Thank you for working on paperless-ngx! 🙏
