### ISSUE TITLE
[BUG] RTL Import is reversed

### ISSUE THREAD

**Issue by OmarWazzan** [paperless-ngx/paperless-ngx#1163]
### Description

When importing an RTL (arabic) document, the content is reversed. 

I.e, if it is the following:
 إعادة اصدار لوحة المركبة
Paperless imports it as:
ﺔﺒﻛﺮﻤﻟﺍ ﺔﺣﻮﻟ ﺭﺍﺪﺻﺍ ﺓﺩﺎﻋﺇ

I believe this could potentially be related to the following issue from the original paperless-ng repo: https://github.com/jonaswinkler/paperless-ng/pull/627

### Steps to reproduce

1. Import an RTL (Arabic in my case) document
2. Check the content within Paperless
3. Will be reversed

### Paperless-ngx version

1.7.1

### Host OS

Unraid 6.10.3

### Installation method

Docker

**Comment by shamoon** [comment]
Reviewing that linked issue it seems like not every doc is reversed, that it might be dependent on how the pdf was authored. Is that the case for you? That PR is just for tests but at the end it looks like there was some brainstorming about a possible solution. Not in my wheelhouse though

**Comment by OmarWazzan** [comment]
> Reviewing that linked issue it seems like not every doc is reversed, that it might be dependent on how the pdf was authored. Is that the case for you? That PR is just for tests but at the end it looks like there was some brainstorming about a possible solution. Not in my wheelhouse though

**Comment by OmarWazzan** [comment]
Sorry, misclicked the close button

**Comment by OmarWazzan** [comment]
> Is that the case for you?

Seems to be any digitally created RTL documents. Scanned ones work fine.

**Comment by stumpylog** [comment]
Do you have a sample document we could use for testing?  Or a way to generate one?  I'm not at all familiar with RTL, but I'm guessing it is something about the sidecar file which probably exists for generated vs scanned documents.

**Comment by OmarWazzan** [comment]
> Do you have a sample document we could use for testing? Or a way to generate one? I'm not at all familiar with RTL, but I'm guessing it is something about the sidecar file which probably exists for generated vs scanned documents.

I've attached a sample document. 

I have tested a bit, and the behavior is also duplicated if you create a word file with RTL content, and save that as PDF."

[test.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9131710/test.pdf)

**Comment by stumpylog** [comment]
Thank you.  It certainly looks reversed to me.  Interestingly, this document appears to be OCRd with tesseract.  We'll try to find a fix, though it could always be somewhere in a dependency.

**Comment by OmarWazzan** [comment]
Hello, any ETA on a fix?

**Comment by stumpylog** [comment]
Unfortunately, the best fix requires a library to update: pdfminer/pdfminer.six/issues/515

It doesn't appear to be being work sadly, so it may not happen for some time.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/a2b7687c3b88aadc55ec38a2249c299eaefd394d
