### ISSUE TITLE
paperless-ngx.com is down

### ISSUE THREAD

**Issue by bllngr** [paperless-ngx/paperless-ngx#1170]
### Description

https://downforeveryoneorjustme.com/paperless-ngx.com

![image](https://user-images.githubusercontent.com/303458/176855159-2c3f6598-6b67-46cb-809c-313cb5d83ec4.png)

I don't know when it happened, I just noticed it right now.

### Steps to reproduce

1. Go to https://paperless-ngx.com

### Paperless-ngx version

1.7.1

### Host OS

Windows 10

### Installation method

Other (please describe above)

### Browser

Firefox, Chrome, isup.me

**Comment by shamoon** [comment]
There is no content at the top level (though it normally forwards to GitHub which was paused), the demo at demo.paperless-ngx.com is alive and kicking 🙂
