### ISSUE TITLE
[BUG] Consume works only once when starting up - Docker, 1.7.1, macOS m1

### ISSUE THREAD

**Issue by editwentyone** [paperless-ngx/paperless-ngx#1207]
### Description

consume only works when there are files and I start up the docker images on my m1 MacBook, macOS. 

after consuming I try to copy more files into the folder but nothing happens, files are staying there and no reaction in the log. 
only when I turn of the docker image and restart the docker image, everything works fine again for one round.

### Steps to reproduce

1. stop container
2. copy files to consume
3. start container
4. consume starts 
5. after consume is done, copy more files into consume folder
6. nothing happens
7. restart container
8. consume resumes again for one round

### Paperless-ngx version

1.7.1

### Host OS

macOS 12.4 M1

### Installation method

Docker - official image

### Browser

safari

**Comment by shamoon** [comment]
Did you look at https://paperless-ngx.readthedocs.io/en/latest/troubleshooting.html ? Issues like that are sometimes a problem with inotify so you may want to try using polling instead https://paperless-ngx.readthedocs.io/en/latest/configuration.html#configuration-polling

**Comment by mariosemes** [comment]
Had the same issue and adding "PAPERLESS_CONSUMER_POLLING=<seconds>" as an environment did it for me and it works flawlessly now.

**Comment by editwentyone** [comment]
big thanks guys, that worked and fixed it flawlessly.
