### ISSUE TITLE
[BUG] not processing large PDFs

### ISSUE THREAD

**Issue by ccvh** [paperless-ngx/paperless-ngx#1232]
### Description

I have scanned some insurance files which led to pdfs of e.g. 35mb to 70mb. They get recognised in the consume folder and The process starts as usual, but just gives up after a long period of time. The PDF remains in the consume folder. 

Any chance to change settings or sth else to make it work?

### Steps to reproduce

Add large files to consume folder

### Paperless-ngx version

1.7.1

### Host OS

QNAP QTS

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Have you tried increasing the worker timeout?  See https://paperless-ngx.readthedocs.io/en/latest/configuration.html#software-tweaks `PAPERLESS_WORKER_TIMEOUT` setting

**Comment by ccvh** [comment]
God. Thank you so much.
