### ISSUE TITLE
[BUG] 1.8.0-rc1 Logging errors/spam when running with uvicorn

### ISSUE THREAD

**Issue by eomanis** [paperless-ngx/paperless-ngx#1280]
### Description

When running the `paperless-ngx` ASGI application server with `uvicorn`, the log is spammed with logging errors and stack traces when the user interacts with the web site. The error message is:

```
TypeError: cannot unpack non-iterable NoneType object
```

This does *not* affect the built-in development application server.

**Be aware that this with Python 3.10.5**, whereas in the [setup instructions](https://paperless-ngx.readthedocs.io/en/latest/setup.html#bare-metal-route) currently only Python 3.8 and 3.9 are listed as supported versions.
My unwarranted assumption was that maybe with `paperless-ngx` 1.8.0 Python 3.10 might be supported.

### Setup
Arch Linux, bare metal, in Python virtual environment. `uvicorn` hosts on a UNIX socket, and `nginx` provides the frontend and serves the static files directly.
The application server is run like this:

```
[paperless@server src]$ pwd
/srv/paperless/paperless-ngx/src
[paperless@server src]$ . ../.venv/bin/activate
(.venv) [paperless@server src]$ uvicorn 'paperless.asgi:application' --uds ../../socket/paperless.sock --proxy-headers
[2022-07-25 16:35:31,280] [INFO] [uvicorn.error] Started server process [1599748]
[2022-07-25 16:35:31,280] [INFO] [uvicorn.error] Waiting for application startup.
[2022-07-25 16:35:31,280] [INFO] [uvicorn.error] ASGI 'lifespan' protocol appears unsupported.
[2022-07-25 16:35:31,281] [INFO] [uvicorn.error] Application startup complete.
INFO:     Started server process [%d]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
[2022-07-25 16:35:31,281] [INFO] [uvicorn.error] Uvicorn running on unix socket ../../socket/paperless.sock (Press CTRL+C to quit)
INFO:     Uvicorn running on unix socket ../../socket/paperless.sock (Press CTRL+C to quit)
```
So far, so good.

### Logging problem
The application itself seems to work as expected. However, for example refreshing the login prompt on the `paperless-ngx` web frontend causes this to be printed on the console:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "/srv/paperless/paperless-ngx/.venv/lib/python3.10/site-packages/uvicorn/logging.py", line 104, in formatMessage
    (
TypeError: cannot unpack non-iterable NoneType object
Call stack:
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/paperless/paperless-ngx/.venv/lib/python3.10/site-packages/concurrent_log_handler/queue.py", line 49, in _monitor
    super()._monitor()
Message: ' - "GET /accounts/login/?next=/ HTTP/1.0" 200'
Arguments: None
```
For each user interaction with the web site at least one of these blocks is printed to the console, which is an awful lot of clutter.

This *might* be a `uvicorn` bug, however I do not observe this issue when running `etebase` with `uvicorn`.
A workaround is disabling `uvicorn` logging by adding the arguments `--log-level error --no-access-log`.

### paperless.conf
```
PAPERLESS_REDIS=unix:///srv/paperless/redis/redis.sock

PAPERLESS_CONSUMPTION_DIR=/srv/paperless/add
PAPERLESS_DATA_DIR=/srv/paperless/data
PAPERLESS_MEDIA_ROOT=/srv/paperless/media
PAPERLESS_STATICDIR=/srv/paperless/webroot/static

PAPERLESS_SECRET_KEY="XXXXXXXXXXXXXXXX"
PAPERLESS_URL=https://server:3333
PAPERLESS_STATIC_URL=/static/

PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_OCR_OUTPUT_TYPE=pdf
PAPERLESS_CONVERT_TMPDIR=/srv/paperless/tmp

PAPERLESS_SCRATCH_DIR=/srv/paperless/uploads

PAPERLESS_TASK_WORKERS=2
PAPERLESS_CONSUMER_POLLING=10
```

### Steps to reproduce

1. On Arch Linux, install the AUR package `paperless-ngx`. This is *only* to obtain any required dependencies; the application installed by the package is not used
2. Switch to your `paperless` user
3. Download and extract the archive of the actually used `paperless-ngx` to `/srv/paperless` following [the instructions for bare-metal installation](https://paperless-ngx.readthedocs.io/en/latest/setup.html#bare-metal-route), with a virtual environment in `/srv/paperless/paperless-ngx/.venv`
4. Activate the virtual environment and install the requirements with `pip` as described
5. In `/srv/paperless/paperless-ngx`, move `paperless.conf` to e.g. `paperless.conf.orig`, then create a symbolic link to your actual configuration file, e.g. `ln -s /etc/paperless.conf`
6. Enter directory: `/srv/paperless/paperless-ngx/src`
8. Launch `uvicorn`: `uvicorn 'paperless.asgi:application' --uds ../../socket/paperless.sock --proxy-headers`

### Webserver logs

```bash
The `nginx` web server does not log any warnings or errors when this happens.
```

### Paperless-ngx version

1.8.0-rc1

### Host OS

Arch Linux x86_64

### Installation method

Bare metal

### Browser

Firefox

### Configuration changes

See Description for paperless.conf

**Comment by stumpylog** [comment]
Although not mentioned in the docs, we do run our unit testing with Python 3.10, so I would consider it pretty well supported.

Otherwise, your setup is beyond my own knowledge of hosting, so hopefully someone with more knowledge will come along.

**Comment by qcasey** [comment]
Thanks for reporting. I can test this later this weekend. To confirm, is this is a bug new to the 1.8.0 beta and did not occur previously on 1.7.1?

**Comment by eomanis** [comment]
> To confirm, is this is a bug new to the 1.8.0 beta and did not occur previously on 1.7.1?

Before 1.8.0-rc1 I was using the packaged version, 1.7.1, from [the AUR package](https://aur.archlinux.org/packages/paperless-ngx), pure bare-metal, all dependencies system-widely installed with distribution packages.

I was running it with uWSGI's Python plugin:

```
ExecStart=/usr/bin/uwsgi \
	--plugin=/usr/lib/uwsgi/python_plugin.so \
	--socket=/srv/paperless/socket/paperless.sock \
	--chmod-socket=660 \
	--vacuum \
	--module=paperless.wsgi
```

This packaged version was often plagued with issues caused by poor backward compatiblity of the dependencies when they were updated. In my particular case, document consumption was currently broken. This is why I went the virtual-environment way with 1.8.0-rc1.

Also, `paperless-ngx` was switched from WSGI to ASGI with version 1.8.0, so I had to change the application server from uWSGI to an ASGI application server. I chose `uvicorn` because I already have `etebase` running with it.

**Comment by qcasey** [comment]
Interesting, thanks for the extra detail. I can replicate this issue as you described, except I used Caddy instead of nginx. Exact same verbose logs. I can't determine if it's a `uvicorn` bug or not

**Comment by shamoon** [comment]
Is folks can check if they’re still having this issue with 1.10.0 that would be helpful

**Comment by eomanis** [comment]
> Is folks can check if they’re still having this issue with 1.10.0 that would be helpful

Will test and report when I upgrade to 1.10.0.
Can confirm that the issue is present with 1.9.2.

**Comment by eomanis** [comment]
The issue is still present with 1.10.1.

I would paste an example, but my desktop's copy&paste is currently glitching.
Anyhow the error message is the same, and the stack dumps look identical right down to the line numbers.

**Comment by shamoon** [comment]
Thanks for checking. Another question, does this have any material effects other than spammy logs?

Im not clear if its truly an issue in paperless or something else in your deployment, but admittedly this side of things is outside my wheelhouse. In the end, its not going to be particularly easy for anyone to work on without being able to reproduce it easily

**Comment by eomanis** [comment]
> Thanks for checking. Another question, does this have any material effects other than spammy logs?

No, it does not impair application functionality, it mostly is a nuisance.

As far as I am able to tell there is an `AccessFormatter` class in `uvicorn`'s `logging.py` that attempts, and fails, to format something that should be logged. So it may very well be a shortcoming of `uvicorn`.

Anybody else use `uvicorn` as ASGI server? If not, which ASGI server do you use that does not act up like that?

**Comment by shamoon** [comment]
Ok thanks for clarifying. Im going to close this just as "wont fix" kinda thing. If its an upstream bug perhaps you can raise an issue at https://github.com/encode/uvicorn/issues . Of course we'd always be happy to entertain a fix here from whomever but again we'd rather focus our efforts on functional bugs, etc.

Appreciate your understanding

**Comment by eomanis** [comment]
Started a [discussion thread](https://github.com/encode/uvicorn/discussions/1796) over at [uvicorn](https://github.com/encode/uvicorn).

**Comment by shamoon** [comment]
Thanks for your persistence :)
Keep us posted

**Comment by eomanis** [comment]
The `uvicorn` people indicate that [it is not their bug](https://github.com/encode/uvicorn/discussions/1796#discussioncomment-4490032).

Root cause seems to be that `paperless-ngx` passes access log records whose `.args` are `None` to `uvicorn`'s logging.

Why that is the case, and whether having `None` `.args` is reasonable, is anyone's guess.
