### ISSUE TITLE
[BUG] CONSUME_SUBDIRS_AS_TAGS not working when using CONSUMER_ENABLE_BARCODES

### ISSUE THREAD

**Issue by tsia** [paperless-ngx/paperless-ngx#1294]
### Description

my scanner puts files into a specific subdirectory of the `CONSUMPTION_DIR`. However when `CONSUMER_ENABLE_BARCODES` is enabled and a barcode is detected the split documents don't have the expected tags.

It looks like this is caused by `save_to_dir()` in `src/documents/tasks.py` and the fact that it always stores the new documents into `CONSUMPTION_DIR`

### Steps to reproduce

1. enable CONSUMER_ENABLE_BARCODES and CONSUME_SUBDIRS_AS_TAGS 
2. put document with correct Barcode into <CONSUMPTION_DIR>/foo
3. wait for import
4. imported documents don't have the tag `foo`

### Paperless-ngx version

1.7.1

### Host OS

Debian

### Installation method

Bare metal

**Comment by stumpylog** [comment]
Thank you, that seems pretty clearly to be an unintended interaction.
