### ISSUE TITLE
[BUG] Input field too small

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1299]
### Description

With 1.8.0 (great work btw.!) the input field for "title & content" is way too small, see:

<img width="1039" alt="Bildschirmfoto 2022-07-29 um 12 06 36" src="https://user-images.githubusercontent.com/15087554/181737014-dc0f09cb-7136-412b-aab8-a406fa6c4055.png">

Or can I just hide the storage path button? I don't need this.

### Steps to reproduce

Upgrade from 1.7 to 1.8.

### Paperless-ngx version

1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by qcasey** [comment]
Thank you for reporting! This has been fixed in #1305
