### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by xEtarusx** [paperless-ngx/paperless-ngx#1300]
### Description

The translation string is missing for the **hover title** in the lower left corner when hovering over "Suggest an idea".

For e.g. when you switch to German it looks like this:
![Unbenannt](https://user-images.githubusercontent.com/4696990/181783653-74c324e6-0645-4f07-89f7-46f218038a08.png)

The title gets set in line 192 at the end `title="Suggest an idea"`
https://github.com/paperless-ngx/paperless-ngx/blob/main/src-ui/src/app/components/app-frame/app-frame.component.html#L192

Please add the possibility to translate this string too.
Thank you :)

### Steps to reproduce

Hover over the "Suggest an idea" button in the lower left corner on the paperless website

### Paperless-ngx version

1.8.0

### Host OS

Ubuntu

### Installation method

Docker - official image

### Browser

Chrome

**Comment by qcasey** [comment]
Thank you for reporting! This has been fixed in #1305
