### ISSUE TITLE
Original PDF is not untouched / Signature is broken

### ISSUE THREAD

**Issue by titro** [paperless-ngx/paperless-ngx#1304]
### Description

I have several digital signed documents which are properly signed with a qualified signature and the adobe reader shows the signature as verified.
![image](https://user-images.githubusercontent.com/4005090/181823803-8880d50d-638b-4d56-a1a3-c3d587d9db02.png)

after processing with paperless and downloading the original there is something broken, i assume with the signature dictionary which contains the signature

![image](https://user-images.githubusercontent.com/4005090/181823946-9156259c-5c1e-421b-b62a-bd9a91e04317.png)

So the original pdf is not really untouched but altered?

### Steps to reproduce

1. have a digital signed document
2. do processing with paperless
3. load the original PDF.
4. Signature is broken

### Paperless-ngx version

1.8.0

### Host OS

Raspberry Pi 32 bit / Docker

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
When I compare the checksums of an original file, the file in paperless and the downloaded original file, they are all matching, so it doesn't appear the original is changed.

Is it possible for you to provide a signed sample file?  Or the details for how one could produce a signed file?

The logs when uploading a signed file could be interesting as well.

**Comment by titro** [comment]
Please find attached:
signed-test.pdf --> QES signed PDF
original.pdf --> Document after paperless processing and original download
[original.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9229144/original.pdf)
[signed-test.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9229145/signed-test.pdf)

**Comment by titro** [comment]
ok my bad...

I have a (very quick and dirty) Pre Consume Script for Decryting which tries to decrypt with:

qpdf --decrypt --password=<password>--replace-input "${1}"

Of course this does not work with signed files...
