### ISSUE TITLE
[BUG] Typo new OCR button in german translation

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1308]
### Description

In the edit screen it is named PCR instead of OCR:

<img width="1007" alt="Bildschirmfoto 2022-07-30 um 10 45 56" src="https://user-images.githubusercontent.com/15087554/181903090-a0d67359-0bb3-4bdb-91d3-a6baca165043.png">

Side question: Should an OCR redo reset the timestamp of the archive PDF file? I did it once and it finished without errors but the timestamp in the PDF header and the Linux fs timestamp (archive folder) are still the same from importing the document for the first time. Linux command "stat" shows no change either. The OCR results seems to be unchanged which ofc could be true.

### Steps to reproduce

Edit a document.

### Paperless-ngx version

1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

**Comment by tooomm** [comment]
>In the edit screen it is named PCR instead of OCR:

Translations are managed via Crowdin and mostly community sourced, see https://github.com/paperless-ngx/paperless-ngx#translation.

I think this was already fixed to `OCR wiederholen` there.
But now I see, that in the recent Crowdin PR, the technical term "OCR" is not preserved, and a new translation version has implemented `Texterkennung erneut durchführen`, which is crazy long for a button...
You should be able to fix that by yourself at Crowdin to ensure it's correct in the next release. 👍 

Translators might not always be aware where the strings show up and what's attached to such "small" translation changes.

---

*Highlighting your second question again*

>Side question: Should an OCR redo reset the timestamp of the archive PDF file? I did it once and it finished without errors but the timestamp in the PDF header and the Linux fs timestamp (archive folder) are still the same from importing the document for the first time. Linux command "stat" shows no change either. The OCR results seems to be unchanged which ofc could be true.

**Comment by r2ixuz** [comment]
Thanks for the info with Crowdin. I don't know this so I tried to vote:

<img width="595" alt="Bildschirmfoto 2022-07-30 um 12 23 41" src="https://user-images.githubusercontent.com/15087554/181906210-43e97813-c7ae-4a8b-b06f-cea1d8034b56.png">

But this make not much sense to me, as there are certainly few users who use Crowdin. And yes, Texterkennung is way too long although it is easier to understand from a non-techy person perspective.

**Comment by stumpylog** [comment]
The redo of OCR only touches the content stored in the database, it doesn't modify any of the timestamps for a document and doesn't modify any files either.

**Comment by shamoon** [comment]
Will be closed by next Crowdin merge, confirmed at https://crowdin.com/translate/paperless-ngx/16/en-de#1520
