### ISSUE TITLE
[BUG] Text selection issue

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1309]
### Description

PDFs with OCR created by Paperless does not set the text selection box correctly:

<img width="163" alt="Bildschirmfoto 2022-07-30 um 10 45 23" src="https://user-images.githubusercontent.com/15087554/181903483-e9c7f44c-2a75-45a6-8353-3a58b9a1219c.png">

Even it seems to be not selected fully the text gets correctly copied to the clipboard. So in this example there would be the letter G NOT missing.

This issue was already present at 1.7.

### Steps to reproduce

Import a newly scanned document and let it getting OCRed.

Select text in the PDF manually or by double clicking a single word. The blue highlighting is missing the last letter.

### Paperless-ngx version

at least 1.7.1 and 1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
This is likely an issue with the pdf viewer we use but is not something we’ll really be able to fix. Have you tried switching to the native pdf viewer? (Under settings)

**Comment by r2ixuz** [comment]
No, you can download the PDF and open it with another PDF viewer. I tried it with macOS and Gnome 42 integrated PDF viewer apps. Both have the same issue.

**Comment by r2ixuz** [comment]
Adobe Reader got this also. So it is an issue with the PDF generated by Paperless.

Interesting thing is, that no matter what font type, size everytime only the last letter of a word is missing. Which software generates theses boxes? Is it pikepdf or tesseract?

You can open such a PDF in LibreOffice Draw and move the image layer a little bit down, so you can see the OCR text boxes. The are alle fine in terms of size and text which can selected. This is strange why than the PDF text boxes are too short.

If you work a lot with the Paperless generated PDF files it is a bit irritating and annoying if you need to copy text from them.

**Comment by r2ixuz** [comment]
OCRmyPDF seems to be the culprit: https://github.com/ocrmypdf/OCRmyPDF/issues/450

Unfortunately no real solution there...

**Comment by r2ixuz** [comment]
Well after deeper digging: This https://github.com/ocrmypdf/OCRmyPDF/issues/530 leads me to https://github.com/tesseract-ocr/tesseract/issues/2879 :-(

**Comment by shamoon** [comment]
As noted this issue lies with our dependencies, if / when they are updated we will be happy to incorporate any fixes. Generally speaking we keep things pretty up-to-date. Im closing this in our repo just to keep things tidy, thank you.
