### ISSUE TITLE
[BUG] Bare metal install of django-q fails

### ISSUE THREAD

**Issue by jwilczek** [paperless-ngx/paperless-ngx#1321]
### Description

I'm receiving an error when installing requirements for v1.8.0 in a bare metal installation specific to the line for django-q.

 -e git+https://github.com/paperless-ngx/django-q.git@bf20d57f859a7d872d5979cd8879fac9c9df981c#egg=django-q

```
Obtaining django-q from git+https://github.com/paperless-ngx/django-q.git@bf20d57f859a7d872d5979cd8879fac9c9df981c#egg=django-q
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/vcs/git.py", line 299, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 265, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 552, in prepare_editable_requirement
    req.update_editable(not self._download_should_save)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 654, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "/usr/lib/python3/dist-packages/pip/_internal/vcs/versioncontrol.py", line 532, in obtain
    existing_url = self.get_remote_url(dest)
  File "/usr/lib/python3/dist-packages/pip/_internal/vcs/git.py", line 301, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError
```

### Steps to reproduce

Pull v1.8.0
sudo -Hu paperless pip3 install -r requirements.txt

### Paperless-ngx version

1.8.0

### Host OS

Ubunt 20.04

### Installation method

Bare metal

### Browser

Chrome

**Comment by stumpylog** [comment]
I find the same issue in `pip`'s issues (pypa/pip/issues/6636), but with no resolution.  

You could try to upgrade pip, or remove the `-e` portion from requirements.txt, which I think would try to install differently and might work.

**Comment by jwilczek** [comment]
pip is upgraded to latest - I'll  try without the `-e` when I'm back at my desk.

**Comment by jwilczek** [comment]
@stumpylog are you baremetal? I'm a little confused by the upgrade instructions... they seem to hint at just overwriting the current path with the contents of the latest release, but some of the files there are config related (at least my paperless.conf lives there).

**Comment by stumpylog** [comment]
I use the Docker image and haven't tried the bare metal instructions ever.  

Do you use a virtual environment?  Or install to the system?

**Comment by stumpylog** [comment]
I definitly run into issues if the `-e` portion is included when following along with the directions.  There's also some conflict if `django_q==1.3.9` installed, then the version from Git is going to be installed.

The workaround for now:
- Remove `-e` from requirements.txt
- Uninstall the existing `django_q` (`sudo -Hu paperless pip3 uninstall django_q`)

**Comment by jwilczek** [comment]
These steps did work for me. Thank you!

**Comment by stumpylog** [comment]
Just to make sure, you had 1.7.1 requirements installed, then tried to install 1.8 over top?

I'm finding the `-e` is required, but if it's just a conflict, that's simple enough to warn about.

**Comment by SiM22** [comment]
Maybe take a look at the ansible role as that will set up a bare metal install - https://github.com/paperless-ngx/ansible

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/6f50285f47643560370f1f9734f57b5ab441bca1
