### ISSUE TITLE
Translation of Paperless-ngx

### ISSUE THREAD

**Issue by yschroeder** [paperless-ngx/paperless-ngx#134]
The following text is based on the translation issue from Paperless-ng: https://github.com/jonaswinkler/paperless-ng/issues/212.

In an effort to provide Paperless-ngx in multiple languages, there is a translation project at Crowdin, which is free for open source projects.

https://crowdin.com/project/paperless-ngx

If you want to see Paperless-ngx in your own language, please help out! The project page shows the status of the current languages. If you want a new language added to the project, mention @shamoon in this issue, he will add it to Crowdin.

### Some notes about translation

* There are two resources. `src-ui/messages.xlf` contains the translation strings for the front end. This is important. `django.po` contains strings for the administration section of paperless, which is nice to have translated but not critical.
* Keep in mind that most of these strings are used on buttons, menu items, etc. The translated string should therefore not be much longer than the English original.
* Translation units may contain placeholders. These usually mean that there's a name of a tag or document or something in the string. You can click on the placeholders to copy them.
* Translation units may contain plural expressions such as {PLURAL_VAR, plural, =1 {one result} =0 {no results} other {<placeholder> results}}. Copy these verbatim and translate only the content in the inner {} brackets. Example: {PLURAL_VAR, plural, =1 {Ein Ergebnis} =0 {Keine Ergebnisse} other {<placeholder> Ergebnisse}}
* Changes to translations at Crowdin will get pushed into the repository automatically.

**Comment by shamoon** [comment]
FYI, I added this kinda text to the readme (in dev) to avoid having to keep open an issue, imho...

https://github.com/paperless-ngx/paperless-ngx/tree/dev#translation

**Comment by yschroeder** [comment]
Oh, I didn't see that... I guess having that in the readme is enough then...

**Comment by FaintGhost** [comment]
I would like to ask why there is no simplified Chinese section on Crowdin？I am willing to take over the translation of the simplified Chinese part.

**Comment by yschroeder** [comment]
@shamoon can you add simplified Chinese?

**Comment by shamoon** [comment]
Hi @FaintGhost , thanks for your offer to help! I added it on Crowdin, please let me know when you've got most / all of it ready and I will add it to the app (thats another step).

**Comment by FaintGhost** [comment]
Hi @shamoon I have completed all parts of the translation, do we need another person to proofread my translation? Or can we just merge the translations into the project. I'd very happy to use paperless-ngx with my native language since paperless-ng does not have any update for six months. :)

**Comment by shamoon** [comment]
Thank you! We dont really have any rules about checking translations, and since Crowdin is open to anyone if there are any issues we can just rely on the community for that. Wonderful to hear, I will create a PR for this (will not be until the next release)

**Comment by yschroeder** [comment]
Reopening as there is quite some inrush of people wanting to help.

**Comment by Pheggas** [comment]
@shamoon Could you please add Slovak language so i can start translating?

**Comment by shamoon** [comment]
I added Slovak to crowdin.

I’m not a fan of the pinned mega-issue, we will all see comments in here if used or users are free to open a new issue / discussion for eg a new language.

**Comment by DarkoBG79** [comment]
@shamoon Could you please add Serbian language so i can start translating? Thank you.

**Comment by shamoon** [comment]
> @shamoon Could you please add Serbian language so i can start translating? Thank you.

All set, let us know when its complete so we can add to the app, and thank you!

**Comment by DarkoBG79** [comment]
Hi @shamoon I have completed all parts of the translation for Serbian (Srpski) language.
