### ISSUE TITLE
[BUG] CSRF issue, broken by favicon.ico

### ISSUE THREAD

**Issue by sbrunner** [paperless-ngx/paperless-ngx#1345]
### Description

Wrong CSRF check

### Steps to reproduce

1. Open http://100.88.77.85:8001/admin/paperless_mail/mailaccount/
2. Open an account
3. Edit the password
4. Save

=> 
```
Interdit (403)

La vérification CSRF a échoué. La requête a été interrompue.

Des informations plus détaillées sont affichées lorsque la variable DEBUG vaut True.
```

Do the same butt using AdBlock to block the favicon.ico => working

For me, the favicon.ico breaks the csrftoken cookie

### Webserver logs

```bash
[2022-08-02 12:10:37,244] [WARNING] [django.security.csrf] Forbidden (CSRF token from POST incorrect.): /admin/paperless_mail/mailaccount/1/change/
```

### Paperless-ngx version

1.8.0

### Host OS

Docker on Synology

### Installation method

Docker - official image

### Browser

Firefox

### Other

The result with the debug option:
```
Help

Reason given for failure:

    CSRF token from POST incorrect.
    

In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/4.0/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:

    Your browser is accepting cookies.
    The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
    In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
    If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
    The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.

You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.
```

Page query cookies:
![Capture d’écran du 2022-08-03 21-19-44](https://user-images.githubusercontent.com/353872/182691856-d239bb33-75ac-4ecf-ae12-92e9ec58b635.png)

favicon.ico cookies:
![Capture d’écran du 2022-08-03 21-19-00](https://user-images.githubusercontent.com/353872/182691888-b392b8cb-4c97-4d17-84f3-97a77c1d11ac.png)

Post query cookies:
![Capture d’écran du 2022-08-03 21-19-55](https://user-images.githubusercontent.com/353872/182691917-ab49e326-fedf-4c01-81ee-11eb7e85757a.png)

**Comment by shamoon** [comment]
Hmm, I cant reproduce this issue, Im able to edit my mail pw without issue, dont see that in the logs. I wonder if theres something else going on.

![Screen Shot 2022-08-02 at 2 25 19 PM](https://user-images.githubusercontent.com/4887959/182476487-78872907-6cfa-4e3d-bf34-8086b1dd2154.jpg)

**Comment by sbrunner** [comment]
The problem is not to get the favicon but when when when we get him, he changes the cookie value...
I didn't get additional information with DEGUG=true

**Comment by foto-andreas** [comment]
To enable debugging: Set `PAPERLESS_DEBUG: true` in docker-compose.yaml

There is a variable interpreted in code names `PAPERLESS_CORS_ALLOWED_HOSTS` which defaults to `http://localhost:8000`. I tried to add my external URL to it, but that does not work.

You must restart the docker containers with `docker-compose up` to see any effect of such changes.

**Comment by foto-andreas** [comment]
For me the issue seems to be solved by adding PAPERLESS_URL with the external URL to docker-compose.yml. I do not know, why this worked before. I migrated to ngx some days ago. Perhaps any token validation timeout jumped in last night.

**Comment by sbrunner** [comment]
I add the `PAPERLESS_DEBUG` then I effectively get more details, I put them in the issue description.

I also add the `PAPERLESS_URL` But without any more success.

I also add some screenshot with the cookies of the important queries in the issue description.

Notes that I have a workaround than if it doesn't affect anyone else we con close it...
