### ISSUE TITLE
[BUG] [WARNING] [paperless.parsing.tesseract] This file is encrypted, OCR is impossible. Using any text present in the original file.

### ISSUE THREAD

**Issue by MalteKiefer** [paperless-ngx/paperless-ngx#1361]
### Description

I try to upload some files in a new paperless environment.
Then I get the following log messages and the site looks like this:

![grafik](https://user-images.githubusercontent.com/59220985/182903267-41641356-af8e-4038-8a5d-32f231d85eeb.png)

File is still in the documents overview
![grafik](https://user-images.githubusercontent.com/59220985/182903677-6914e4de-ec55-49a7-98e2-dc118b343a47.png)

### Steps to reproduce

1. Upload file
2. Watch the logs

### Webserver logs

```bash
paperless-webserver-1  | 18:17:58 [Q] INFO Process-1:9 processing [Lohnabrechnung Malte Kiefer 2022-03.pdf]
paperless-webserver-1  | [2022-08-04 18:17:59,277] [INFO] [paperless.consumer] Consuming Lohnabrechnung Malte Kiefer 2022-03.pdf
paperless-webserver-1  | [2022-08-04 18:17:59,940] [WARNING] [paperless.parsing.tesseract] This file is encrypted, OCR is impossible. Using any text present in the original file.
paperless-webserver-1  | [2022-08-04 18:18:02,712] [INFO] [paperless.consumer] Document 2022-03-01 Lohnabrechnung Malte Kiefer 2022-03 consumption finished
paperless-webserver-1  | 18:18:02 [Q] INFO Process-1:9 stopped doing work
paperless-webserver-1  | 18:18:02 [Q] INFO Processed [Lohnabrechnung Malte Kiefer 2022-03.pdf]
paperless-webserver-1  | 18:18:04 [Q] INFO recycled worker Process-1:9
paperless-webserver-1  | 18:18:04 [Q] INFO Process-1:10 ready for work at 516
```

### Paperless-ngx version

1.8.0

### Host OS

Debian 11.4

### Installation method

Docker - official image

### Browser

Chromium

**Comment by stumpylog** [comment]
This is expected behavior for an encrypted PDF, the file cannot be processed further without being decrypted.  As the message says, any existing text will be used for the content displayed in the webui.

**Comment by MalteKiefer** [comment]
But the file is not encrypted

**Comment by stumpylog** [comment]
Ah, that wasn't clear.  It could be the file is encrypted, even if you didn't set it yourself.  Some banks, etc will encrypt statements.

In this case, OCRMyPDF thinks is it, which probably means pikepdf thinks it is, which probably means qpdf thinks it is.  Could you see what `qpdf --show-encryption` reports for this file?

**Comment by MalteKiefer** [comment]
```
R = 3
P = -12
User password =
Supplied password is user password
extract for accessibility: allowed
extract for any purpose: allowed
print low resolution: allowed
print high resolution: allowed
modify document assembly: allowed
modify forms: allowed
modify annotations: allowed
modify other: not allowed
modify anything: not allowed
```

**Comment by stumpylog** [comment]
I don't have a known encrypted file handy to check against, but that does look like the file is encrypted with revision 3, with the allowed permission only being for printing at low resolution.  (That's the R & P, see https://qpdf.readthedocs.io/en/stable/encryption.html)

I would suspect it could be removed by `qpdf`, maybe even a `qpdf infile.pdf outfile.pdf`.

**Comment by fdw** [comment]
As this prevents OCR, do you have an idea/hint to still get OCR for the archive without touching the original?
