### ISSUE TITLE
[BUG] Copy/Insert date from PDF fails

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1365]
### Description

Since 1.8.0 copy a date like 26.07.2022 fails when I try to insert it in the "Ausgestellt am" field (issued field in english!?). Instead of inserting, the field gets cleared. Tried under macOS with Chrome and Firefox.

### Steps to reproduce

See description.

### Paperless-ngx version

1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

**Comment by r2ixuz** [comment]
Additionally to this, sometimes inserting works, but instead the correct date like 06.08.2022 it gets automagically changed to 08.06.2022 event it is correct in the clipboard.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/a81dc00ccfc406f0eeea005e53f7eafb92519685
