### ISSUE TITLE
[other] manifest unknown when pulling "latest"

### ISSUE THREAD

**Issue by skorvek** [paperless-ngx/paperless-ngx#137]
When using the updated docker compose files referencing this repository

I get the following error: Pulling webserver (ghcr.io/paperless-ngx/paperless-ngx:latest)... manifest unknown.

**Comment by qcasey** [comment]
Hi, unfortunately we don't have a tested build pushed to latest yet.

If you'd like to run an untested version you can pull from the `dev` tag:

```
ghcr.io/paperless-ngx/paperless-ngx:dev
```

`latest` will be posted with version 1.6.0.

**Comment by skorvek** [comment]
Sure. Understood. Perhaps we can put a comment in the files for now until the tag is added to release or alternatively we could tag 1.5 since that is the last functional release. 

Is there going to be a tag for a release candidate as well for more beta testing than just following Dev?

**Comment by qcasey** [comment]
That's a good idea, I just tagged 1.5.0/latest off the current main branch.

We do expect to have a release candidate for testing 1.6.0.

**Comment by skorvek** [comment]
great- thanks. I’m working no setting up some template stacks for dev, test/rc, and prod/release built to use the docker compose scripts and sane defaults, and separate from my personal production version. If we also had a beta or release candidate tag then that infrastructure could be largely automated.

**Comment by qcasey** [comment]
Sure, it's undecided how that'll look exactly but there will be a testing phase before release 👍
