### ISSUE TITLE
[BUG] document view: action menu has wrong/missing translation (German)

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1385]
### Description

Both buttons are called "Originale herunterladen". I guess one of them should be just "Herunterladen" like in the edit view.

<img width="251" alt="Bildschirmfoto 2022-08-09 um 18 27 31" src="https://user-images.githubusercontent.com/15087554/183707617-7614f473-4b74-49d7-9345-1f4b8318471e.png">

### Steps to reproduce

Select at least one document in the document view. Open the actions drop down menu.

### Paperless-ngx version

1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by r2ixuz** [comment]
Hmm, tried it there but did not find it.

So both of your crowdin links/translations were already 6 month ago confirmed by the paperless project. Why was this not already merged then?

**Comment by shamoon** [comment]
Sorry wrong link! https://crowdin.com/translate/paperless-ngx/16/en-de#1516 (Updated 11d ago)

vs https://crowdin.com/translate/paperless-ngx/16/en-de#1518

**Comment by r2ixuz** [comment]
Thanks, that makes more sense now! I up voted  for #1516 at Crowdin. Hope that's the right one. :-)

But to be honest, I would never have found that on my own in Crowdin. What is the best way? Should I inspect the button with the build-in Chrome developer tools?

**Comment by shamoon** [comment]
There’s a search in crowdin inside the “editor”, did you see that? That’s how I found this particular one

**Comment by r2ixuz** [comment]
Yeah I found these also, but I was not sure, if this is really that button. Ok the path src/app/components/document-list/bulk-editor/bulk-editor.component.html is a hint but not that clear to me as a user who wants to help (without developing background). :-)

Anyways, I am eagerly looking forward to the next stable release. :-) I really like this awesome project and the teams efforts to make all working like a charm. Thank you very much!
