### ISSUE TITLE
[BUG] Pagination loses filters

### ISSUE THREAD

**Issue by smseidl** [paperless-ngx/paperless-ngx#1389]
### Description

Similar to discussion #1360.  When I am navigating a view that has multiple pages in it, it seems to lose the filters that are in place and all documents are retrieved.

Screenshot for page 1:
![image](https://user-images.githubusercontent.com/23556348/183810283-07336904-e67a-46c3-afb0-65224c999953.png)

Screenshot on page 2:
![image](https://user-images.githubusercontent.com/23556348/183810329-aed80788-d337-4696-b8ef-4edb4b626c36.png)

### Steps to reproduce

1. Open a view with many documents (i.e. Inbox with > 50 documents [assuming default items / page])
2. Navigate from the first page by clicking a specific page, or the next page button.
3. Filters are now gone, and all documents are present.

### Webserver logs

```bash
Nothing seen in docker-compose logs for webserver
```

### Paperless-ngx version

1.8.0

### Host OS

RPi 4

### Installation method

Docker - official image

### Browser

Edge

**Comment by smseidl** [comment]
Playing around a bit more - I don't think it **loses** the filter, but almost defaults to the filter present on the generic documents view.

General Documents Filtered for Correspondent & Created in last 7 days:
![image](https://user-images.githubusercontent.com/23556348/183815026-38007d38-a0cb-46cc-aa8f-fd7015cf0f0a.png)

Move to Large View - Page 1
![image](https://user-images.githubusercontent.com/23556348/183815271-f754cbd0-9bcb-496e-b788-9f34e50e2042.png)

Navigate to Page 2 - and filters now match the General Documents (image 1) and error
![image](https://user-images.githubusercontent.com/23556348/183815370-03dc245d-d060-438a-9fba-58cbbfa52528.png)

**Comment by smseidl** [comment]
Cleaning up my email - I just saw another issue that was closed with PR #1376 .  I'm guessing that same PR will fix this issue.... @shamoon  please close this if that is true.

**Comment by qcasey** [comment]
Thanks for the detailed report! As you mentioned, #1376 will correct this in the next release.
