### ISSUE TITLE
[BUG] Fresh install from ghcr.io doesn't build frontend

### ISSUE THREAD

**Issue by gabrielke** [paperless-ngx/paperless-ngx#139]
Just created a new docker-compose based install with postgres.
in the docker-compose.env file I set
PAPERLESS_OCR_LANGUAGES=hun
PAPERLESS_OCR_LANGUAGE=hun
Placed it to port 7777 because port 8000 is already used.
Created superuser as described in the documentation. This went fine.

The login screen appears just fine.
Login successfull but after that "nothing".
The page source says: "Paperless-ng is loading..."

**Comment by qcasey** [comment]
Hello, could you post the output of `docker-compose logs`? Also you you see any errors in the browser's console?

**Comment by yschroeder** [comment]
Without looking deeper into this: the login page is created by django. Afterwards the Angular ui takes over and if that fails to load you get that message.

Where did you change the port? Inside the container? Did you build from the dev or main branch?

**Comment by yschroeder** [comment]
I'm on mobile right now, but I have the feeling that angular did not manage to connect to the rest API served by django. It infers the location of the API from the browser address bar:

https://github.com/paperless-ngx/paperless-ngx/blob/ae94b90fe4656b8145d9cf14549d5488dd2438ae/src-ui/src/environments/environment.prod.ts

Maybe this fails under certain circumstances?

**Comment by gabrielke** [comment]
> Without looking deeper into this: the login page is created by django. Afterwards the Angular ui takes over and if that fails to load you get that message.
> 
> Where did you change the port? Inside the container? Did you build from the dev or main branch?

I changed the port in the docker-compose.yml only, like this:

    ports:
      - 7777:8000

**Comment by gabrielke** [comment]
Additional info, tried the setup on port 8000, there it started just fine.
So I guess that port 8000 is "burned" into the code somewhere where it shouldn't be.

**Comment by gador** [comment]
looking at the source, it seems the port `8000` is hardcoded in https://github.com/paperless-ngx/paperless-ngx/blob/140b179607e3166097b17344b6c5db2093b10f1a/src-ui/src/environments/environment.ts#L5-L11

This should get replaced with `fileReplacements` during build with https://github.com/paperless-ngx/paperless-ngx/blob/140b179607e3166097b17344b6c5db2093b10f1a/src-ui/src/environments/environment.prod.ts#L3-L9

Im not familiar with angular, but I havent found the reference to `baseURI` yet. Seems the problem originates there. 

Apart from that: You didn't change the port *inside* the container but how to access it from the outside. I have paperless running on port 8010 the same way, you did change the port and it works. The difference is, I have a reverse proxy. What does the webConsole say?

**Comment by gabrielke** [comment]
> Apart from that: You didn't change the port _inside_ the container but how to access it from the outside. I have paperless running on port 8010 the same way, you did change the port and it works. The difference is, I have a reverse proxy. What does the webConsole say?

Honestly I never had any problem with any application changing the port where (the docker proxy) listens on.
I guess the root cause is the generated javascript has the port 8000 fixed at build time and then it won't change - because it can't change.

There must be a pattern how the other zillion similar apps solve this so I hope this is not gonna be a big deal :)

**Comment by yschroeder** [comment]
There are two environment file. The one with the hard coded 8000 is for development. The Angular dev server runs on port 4200 thus inferring the API location from the browser address bar will fail. When building docker for production it should use the prod environment file.

I also have it running on a different port with no problem.

**Comment by yschroeder** [comment]
Maybe angular didn't know to build the production version?

**Comment by gador** [comment]
@gabrielke could you post your complete docker-compose? I'd especially would like to see which images you use.
Apart from that: What did the webConsole say?

**Comment by gabrielke** [comment]
Attached my docker-compose.env and docker-compose.yml

Now I started it on the default port 8000 and it doesn't start there either :)

[docker-compose.zip](https://github.com/paperless-ngx/paperless-ngx/files/8132297/docker-compose.zip)

**Comment by gador** [comment]
could you please attach the webConsole output

**Comment by gabrielke** [comment]
Yes it works with the old image. Both on port 8000 and 7777.

**Comment by gador** [comment]
ok, then it has something to do with our changes to the image.
I still think, the webConsole will offer some introspective.

**Comment by gabrielke** [comment]
The web console output: 

The resource from “http://localhost:8000/static/frontend/en-US/styles.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[localhost:8000](http://localhost:8000/)
The resource from “http://localhost:8000/static/frontend/en-US/main.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[localhost:8000](http://localhost:8000/)
Loading failed for the <script> with source “http://localhost:8000/static/frontend/en-US/main.js”. [localhost:8000:25:1](http://localhost:8000/)
The resource from “http://localhost:8000/static/frontend/en-US/runtime.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[localhost:8000](http://localhost:8000/)
Loading failed for the <script> with source “http://localhost:8000/static/frontend/en-US/runtime.js”. [localhost:8000:23:1](http://localhost:8000/)
The resource from “http://localhost:8000/static/frontend/en-US/polyfills.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[localhost:8000](http://localhost:8000/)
Loading failed for the <script> with source “http://localhost:8000/static/frontend/en-US/polyfills.js”.

**Comment by yschroeder** [comment]
Is that output with port 7777 or 8000 configured?

**Comment by gador** [comment]
I was able to reproduce with with current `dev` with port 8000. Could it be, that angular didn't build the static content in the current docker image?

**Comment by gabrielke** [comment]
> Is that output with port 7777 or 8000 configured?

port 8000

**Comment by gador** [comment]
> I was able to reproduce with with current `dev` with port 8000. Could it be, that angular didn't build the static content in the current docker image?

yep, I think thats the spot.
After running `npm install` and `ng build --prod` the (same) errors disappear and I can login.
The next problem (in the dev branch) is:
```
main.js:3 ERROR TypeError: tt(...) is not a function
    at template (main.js:3:861131)
    at sb (main.js:3:54236)
    at ed (main.js:3:52369)
    at KP (main.js:3:60450)
    at OP (main.js:3:52573)
    at ed (main.js:3:52584)
    at Cm.create (main.js:3:100338)
    at t.bootstrap (main.js:3:125826)
    at main.js:3:123897
    at Array.forEach (<anonymous>)
RN @ main.js:3
handleError @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
runOutsideAngular @ main.js:3
(anonymous) @ main.js:3
invoke @ polyfills.js:1
onInvoke @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonymous) @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:3
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
L @ polyfills.js:1
Promise.then (async)
d @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMicroTask @ polyfills.js:1
U @ polyfills.js:1
then @ polyfills.js:1
bootstrapModule @ main.js:3
913 @ main.js:3
f @ runtime.js:1
(anonymous) @ main.js:3
t @ runtime.js:1
(anonymous) @ main.js:3
main.js:3 TypeError: tt(...) is not a function
    at template (main.js:3:861131)
    at sb (main.js:3:54236)
    at ed (main.js:3:52369)
    at KP (main.js:3:60450)
    at OP (main.js:3:52573)
    at ed (main.js:3:52584)
    at Cm.create (main.js:3:100338)
    at t.bootstrap (main.js:3:125826)
    at main.js:3:123897
    at Array.forEach (<anonymous>)
```
but that is probably another problem.

**Comment by yschroeder** [comment]
The second one might be a node package not properly updated. Sometimes npm seems to mess up...

**Comment by gador** [comment]
@gabrielke The problem seems to be in the new image build, which doesn't include the static build files from angular
@yschroeder : Yes, maybe. I was able to run the master branch w/o problems and get the error above repeatably with the dev branch. Shall I open a new bug report?

**Comment by gabrielke** [comment]
@gador which one is the "master branch" image?

**Comment by gador** [comment]
ah I missed the change to`main` and used my local `master` branch :facepalm: 
The same happens with the `main` branch though:

`main`: builds and runs normally with `npm install && ng build --prod` before
`dev`: builds, but gives this error https://github.com/paperless-ngx/paperless-ngx/issues/139#issuecomment-1049862851 when I logged in.

**Comment by gador** [comment]
@yschroeder 
Our CI pipeline from github is supposed to build the frontend:
https://github.com/paperless-ngx/paperless-ngx/blob/140b179607e3166097b17344b6c5db2093b10f1a/.github/workflows/ci.yml#L147-L172

I'm not familiar with Githubs process to build the image at ghcr.io but shouldn't it run the pipeline? To that effect, shouldn't the pipeline run on `push`: 
https://github.com/paperless-ngx/paperless-ngx/blob/140b179607e3166097b17344b6c5db2093b10f1a/.github/workflows/ci.yml#L3-L5

Could it be, that we need to change that to `ngx` to have a working pipeline?

**Comment by qcasey** [comment]
1.5.0 was not built in CI, it needs to be rebuilt manually with the compiled frontend

**Comment by qcasey** [comment]
Alright, rebuilt and pushed a `latest` container. I'm able to log into the front end with this one.

@gabrielke could you `docker-compose pull && docker-compose up -d` and let us know if the updated image fixes this issue?

I guess this is another point for #19 :smiling_face_with_tear:

**Comment by gador** [comment]
> I guess this is another point for #19 :smiling_face_with_tear:

Oh, didn't see that issue. Sounds like a good plan :+1: 

> @gabrielke could you docker-compose pull && docker-compose up -d and let us know if the updated image fixes this issue?

At least for me, it fixed the issue

**Comment by gabrielke** [comment]
> @gabrielke could you `docker-compose pull && docker-compose up -d` and let us know if the updated image fixes this issue?

Issue fixed, thank you!

**Comment by gabrielke** [comment]
FWIW port 7777 works too :)

**Comment by qcasey** [comment]
Great! Thank you both :+1:

**Comment by gabrielke** [comment]
Issue fixed.
