### ISSUE TITLE
[BUG] Document not archived

### ISSUE THREAD

**Issue by dstampfer** [paperless-ngx/paperless-ngx#1437]
### Description

I use the media folder to access my documents on disc. This works nice except a few documents do not show up in archive/, but only show up in originals/. Here is what I find in the logs:

```
webserver_1  | [2022-08-18 20:49:08,799] [INFO] [paperless.consumer] Consuming document.pdf
webserver_1  | [2022-08-18 20:49:09,222] [WARNING] [paperless.parsing.tesseract] This file is encrypted, OCR is impossible. Using any text present in the original file.
webserver_1  | [2022-08-18 20:49:11,317] [INFO] [paperless.consumer] Document document consumption finished
webserver_1  | 20:49:11 [Q] INFO Process-1:4 stopped doing work
webserver_1  | 20:49:11 [Q] INFO Processed [document.pdf]
```

The document is PDF-1.4. I have no clue what "encrypted" means.

I have not set PAPERLESS_OCR_MODE, so I assume it defaults to skip. I expect the document to be stored in archive/ anyway.

It is, however, included when I run document_exporter

### Steps to reproduce

Unfortunately I cannot share the document to reproduce.

### Webserver logs

```bash
see above
```

### Paperless-ngx version

1.8.0

### Host OS

ubuntu 20.04, docker install

### Installation method

Docker - official image

### Browser

chrome

**Comment by stumpylog** [comment]
This is expected behavior for encrypted PDFs.  See #1361 for example.  Even if you didn't set a password, some documents are encrypted to prevent changes, such as making an archived version of it.

**Comment by thmo** [comment]
Could you further explain?

I also have some files which can be decrypted without password simply with `qpdf --decrypt infile outfile`. It should (at least technically) be possible for paperless to at least try this before further processing the document. See also https://github.com/jonaswinkler/paperless-ng/issues/1387#issuecomment-942727072 (but if it can be done with a `PRE_CONSUME_SCRIPT` it could also be done by paperless proper).

Or am I missing something?

**Comment by stumpylog** [comment]
I'm not sure that running `qpdf` against an input file is a good idea.  In this case, OCRMyPdf is saying the file is encrypted. In this case, it's probably an owner password, which is why the command runs without error.

You could ask the OCRmyPdf folks to try and detect owner vs user passwords and separate them for different processing, but there currently isn't a way to tell.

**Comment by thmo** [comment]
One could use [`--requires-password`](https://qpdf.readthedocs.io/en/stable/cli.html#option-requires-password) to check, having some logic like this
```shell
if qpdf --is-encrypted infile.pdf && ! qpdf --requires-password infile.pdf ; then
    qpdf --decrypt infile.pdf intermediatefile.pdf
fi
```
either _before_ passing it to OCRmyPDF or _as part of_ OCRmyPDF. Maybe the latter would indeed make more sense, going to ask them.

**Comment by dstampfer** [comment]
In case it helps: From my report before, the file is not encrypted, even though the logs say so. Here is qpdf --info:


PDF Version: 1.4
R = 3
P = -12
User password = 
extract for accessibility: allowed
extract for any purpose: allowed
print low resolution: allowed
print high resolution: allowed
modify document assembly: allowed
modify forms: allowed
modify annotations: allowed
modify other: not allowed
modify anything: not allowed
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
