### ISSUE TITLE
[BUG] PAPERLESS_OCR_MODE=skip_noarchive not adhered when storage path is set to automatic

### ISSUE THREAD

**Issue by mamema** [paperless-ngx/paperless-ngx#1438]
### Description

Paperless 1.8.0
Docker 20.10.17
Debian 11

Variable 
PAPERLESS_OCR_MODE=skip_noarchive is set and available in docker session
(tested with - echo $PAPERLESS_OCR_MODE

If storage path is set eg:
{correspondent}/{created_day}_{created_month}_{created_year}_{title}
Mode: Find Any word: "foo" "foo bar"

archive files are not created - GOOD! as variable skip_noarchive is set

If storage path is set eg:
{correspondent}/{created_day}_{created_month}_{created_year}_{title}
Mode: AUTO

archive files are created - BAD! as variable skip_noarchive is set

### Steps to reproduce

1. set variable PAPERLESS_OCR_MODE=skip_noarchive
2. check if available in docker
3. configure storage path with find any term condition
4. consume a pdf
5. archive file is not created
6. configure storage path with AUTO condition
7. consume a pdf
8. archive file will be created

### Paperless-ngx version

1.8.0

### Host OS

Debian 11

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
There's definitely something going on with `skip_noarchive` mode.  Not 100% sure it is related to storage paths as I can se archive files generated when none exist.

At a guess, it's when the file doesn't have existing text on some pages, so OCR is still preformed, and there's no check against creating an archive file at that point.

**Comment by qcasey** [comment]
Fixed in #1442
