### ISSUE TITLE
[BUG] Issue with tag colours on REST-API (GET/POST)

### ISSUE THREAD

**Issue by hrvylein** [paperless-ngx/paperless-ngx#1449]
### Description

I'm developing a small client which can migrate data from Sismics Teedy to paperless-ngx in golang.

When retrieving tags from the api (/api/tags/) colour hex codes aren't returned for me.
`{
            "id": 14,
            "slug": "Test",
            "name": "Test",
            "colour": 1,
            "match": "",
            "matching_algorithm": 1,
            "is_insensitive": false,
            "is_inbox_tag": false,
            "document_count": 0
}`

And when posting a new tag only empty values are allowed or working. Everything else returns error 400.
Example request:
`{"name":"mytag2fg","colour":"#000000","match":"","matching_algorithm":1,"is_insensitive":false,"is_inbox_tag":false}` is denied.

When inspecting network traffic from the web-interface I can see, that hex-values for colours can be saved and are returned from the server. Going directly to the tag api endpoint and using the django interface leads to the same problem. Right now, I cant wrap my head around the problem. Any advice?

### Steps to reproduce

1. Go to /api/tags
2. missing hex codes in colour field
3. unable to create a new tag with hex code when posting a new tag 

### Paperless-ngx version

1.8.0

### Host OS

Debian

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
As noted in the api doc you can specify different versions of the API https://github.com/paperless-ngx/paperless-ngx/blob/5fe435048bc6eb77f9473afc11588427846456ab/docs/api.rst#api-versioning , default is v1 which didnt include the hex colors. To change it, specify the version in the headers, e.g.:
`Accept: application/json; version=2`
