### ISSUE TITLE
[BUG] document_renamer -> ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by chris199512** [paperless-ngx/paperless-ngx#1452]
### Description

I want to rename my files with document_renamer but get this error. so i updatet django with 'sudo -Hu paperless pip3 install -r requirements.txt' but still the same error.

![image](https://user-images.githubusercontent.com/84684730/186348806-c3799153-8bec-480a-93ae-1f29b843e9cf.png)

### Steps to reproduce

cd /opt/paperless/src
python3 manage.py document_renamer

### Paperless-ngx version

1.8

### Host OS

Proxmox 7.2 with debian 11

### Installation method

Bare metal

**Comment by chris199512** [comment]
This is from pip3 list:
`Package                Version        Editable project location
---------------------- -------------- ---------------------------
aioredis               1.3.1
anyio                  3.6.1
arrow                  1.2.2
asgiref                3.5.2
async-timeout          4.0.2
attrs                  21.4.0
autobahn               22.6.1
Automat                20.2.0
blessed                1.19.1
certifi                2020.6.20
cffi                   1.15.1
channels               3.0.5
channels-redis         3.4.1
chardet                4.0.0
charset-normalizer     2.1.0
click                  8.1.3
coloredlogs            15.0.1
concurrent-log-handler 0.9.20
constantly             15.1.0
cryptography           3.3.2
daphne                 3.0.2
dateparser             1.1.1
Deprecated             1.2.13
deprecation            2.1.0
Django                 4.0.6
django-cors-headers    3.13.0
django-extensions      3.2.0
django-filter          22.1
django-picklefield     3.1
django-q               1.3.9          /opt/paperless/src/django-q
djangorestframework    3.13.1
dnspython              2.0.0
filelock               3.7.1
fuzzywuzzy             0.18.0
gpg                    1.14.0-unknown
gunicorn               20.1.0
h11                    0.13.0
hiredis                2.0.0
httplib2               0.18.1
httptools              0.4.0
humanfriendly          10.0
hyperlink              21.0.0
idna                   2.10
imap-tools             0.56.0
img2pdf                0.4.4
incremental            21.3.0
inotify-simple         1.3.5
inotifyrecursive       0.3.5
joblib                 1.1.0
langdetect             1.0.9
lxml                   4.9.1
Markdown               3.3.4
msgpack                1.0.4
numpy                  1.23.1
ocrmypdf               13.6.1
packaging              21.3
pathvalidate           2.5.0
pdf2image              1.16.0
pdfminer.six           20220524
pikepdf                5.4.0
Pillow                 9.2.0
pip                    20.3.4
pluggy                 1.0.0
portalocker            2.5.1
psycopg2               2.9.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.21
pycurl                 7.43.0.6
Pygments               2.7.1
pyOpenSSL              22.0.0
pyparsing              3.0.9
PySimpleSOAP           1.16.2
python-apt             2.2.1
python-dateutil        2.8.2
python-debian          0.1.39
python-debianbts       3.1.0
python-dotenv          0.20.0
python-gnupg           0.4.9
python-Levenshtein     0.12.2
python-magic           0.4.27
pytz                   2022.1
pytz-deprecation-shim  0.1.0.post0
PyYAML                 5.3.1
pyzbar                 0.1.9
redis                  4.3.4
regex                  2022.3.2
reportbug              7.10.3+deb11u1
reportlab              3.6.11
requests               2.25.1
requests-toolbelt      0.9.1
scikit-learn           1.1.1
scipy                  1.8.1
service-identity       21.1.0
setuptools             52.0.0
six                    1.16.0
sniffio                1.2.0
sqlparse               0.4.2
threadpoolctl          3.1.0
tika                   1.24
tqdm                   4.64.0
Twisted                22.4.0
txaio                  22.2.1
typing_extensions      4.3.0
tzdata                 2022.1
tzlocal                4.2
urllib3                1.26.5
uvicorn                0.18.2
uvloop                 0.16.0
watchdog               2.1.9
watchfiles             0.16.0
wcwidth                0.2.5
websockets             10.3
wheel                  0.34.2
whitenoise             6.2.0
Whoosh                 2.7.4
wrapt                  1.14.1
zope.interface         5.4.0`
and this is from the install:
`Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple, https://www.piwheels.org/simple
Ignoring backports.zoneinfo: markers 'python_version < "3.9"' don't match your environment
Obtaining django-q from git+https://github.com/paperless-ngx/django-q.git@bf20d57f859a7d872d5979cd8879fac9c9df981c#egg=django-q (from -r requirements.txt (line 32))
  Skipping because already up-to-date.
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Ignoring importlib-resources: markers 'python_version < "3.9"' don't match your environment
Ignoring zipp: markers 'python_version < "3.9"' don't match your environment
Requirement already satisfied: aioredis==1.3.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: anyio==3.6.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (3.6.1)
Requirement already satisfied: arrow==1.2.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (1.2.2)
Requirement already satisfied: asgiref==3.5.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (3.5.2)
Requirement already satisfied: async-timeout==4.0.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (4.0.2)
Requirement already satisfied: attrs==21.4.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (21.4.0)
Requirement already satisfied: autobahn==22.6.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (22.6.1)
Requirement already satisfied: automat==20.2.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (20.2.0)
Requirement already satisfied: blessed==1.19.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (1.19.1)
Requirement already satisfied: certifi==2022.6.15 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (2022.6.15)
Requirement already satisfied: cffi==1.15.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (1.15.1)
Requirement already satisfied: channels==3.0.5 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (3.0.5)
Requirement already satisfied: channels-redis==3.4.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 16)) (3.4.1)
Requirement already satisfied: charset-normalizer==2.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 17)) (2.1.0)
Requirement already satisfied: click==8.1.3 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 18)) (8.1.3)
Requirement already satisfied: coloredlogs==15.0.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 19)) (15.0.1)
Requirement already satisfied: concurrent-log-handler==0.9.20 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 20)) (0.9.20)
Requirement already satisfied: constantly==15.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 21)) (15.1.0)
Requirement already satisfied: cryptography==37.0.4 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 22)) (37.0.4)
Requirement already satisfied: daphne==3.0.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 23)) (3.0.2)
Requirement already satisfied: dateparser==1.1.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 24)) (1.1.1)
Requirement already satisfied: deprecated==1.2.13 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 25)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 26)) (2.1.0)
Requirement already satisfied: django==4.0.6 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 27)) (4.0.6)
Requirement already satisfied: django-cors-headers==3.13.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 28)) (3.13.0)
Requirement already satisfied: django-extensions==3.2.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 29)) (3.2.0)
Requirement already satisfied: django-filter==22.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 30)) (22.1)
Requirement already satisfied: django-picklefield==3.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 31)) (3.1)
Requirement already satisfied: djangorestframework==3.13.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 33)) (3.13.1)
Requirement already satisfied: filelock==3.7.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 34)) (3.7.1)
Requirement already satisfied: fuzzywuzzy[speedup]==0.18.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 35)) (0.18.0)
Requirement already satisfied: gunicorn==20.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 36)) (20.1.0)
Requirement already satisfied: h11==0.13.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 37)) (0.13.0)
Requirement already satisfied: hiredis==2.0.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 38)) (2.0.0)
Requirement already satisfied: httptools==0.4.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 39)) (0.4.0)
Requirement already satisfied: humanfriendly==10.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 40)) (10.0)
Requirement already satisfied: hyperlink==21.0.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 41)) (21.0.0)
Requirement already satisfied: idna==3.3 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 42)) (3.3)
Requirement already satisfied: imap-tools==0.56.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 43)) (0.56.0)
Requirement already satisfied: img2pdf==0.4.4 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 44)) (0.4.4)
Requirement already satisfied: incremental==21.3.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 46)) (21.3.0)
Requirement already satisfied: inotify-simple==1.3.5 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 47)) (1.3.5)
Requirement already satisfied: inotifyrecursive==0.3.5 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 48)) (0.3.5)
Requirement already satisfied: joblib==1.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 49)) (1.1.0)
Requirement already satisfied: langdetect==1.0.9 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 50)) (1.0.9)
Requirement already satisfied: lxml==4.9.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 51)) (4.9.1)
Requirement already satisfied: msgpack==1.0.4 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 52)) (1.0.4)
Requirement already satisfied: numpy==1.23.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 53)) (1.23.1)
Requirement already satisfied: ocrmypdf==13.6.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 54)) (13.6.1)
Requirement already satisfied: packaging==21.3 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 55)) (21.3)
Requirement already satisfied: pathvalidate==2.5.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 56)) (2.5.0)
Requirement already satisfied: pdf2image==1.16.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 57)) (1.16.0)
Requirement already satisfied: pdfminer.six==20220524 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 58)) (20220524)
Requirement already satisfied: pikepdf==5.4.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 59)) (5.4.0)
Requirement already satisfied: pillow==9.2.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 60)) (9.2.0)
Requirement already satisfied: pluggy==1.0.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 61)) (1.0.0)
Requirement already satisfied: portalocker==2.5.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 62)) (2.5.1)
Requirement already satisfied: psycopg2==2.9.3 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 63)) (2.9.3)
Requirement already satisfied: pyasn1==0.4.8 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 64)) (0.4.8)
Requirement already satisfied: pyasn1-modules==0.2.8 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 65)) (0.2.8)
Requirement already satisfied: pycparser==2.21 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 66)) (2.21)
Requirement already satisfied: pyopenssl==22.0.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 67)) (22.0.0)
Requirement already satisfied: pyparsing==3.0.9 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 68)) (3.0.9)
Requirement already satisfied: python-dateutil==2.8.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 69)) (2.8.2)
Requirement already satisfied: python-dotenv==0.20.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 70)) (0.20.0)
Requirement already satisfied: python-gnupg==0.4.9 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 71)) (0.4.9)
Requirement already satisfied: python-levenshtein==0.12.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 72)) (0.12.2)
Requirement already satisfied: python-magic==0.4.27 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 73)) (0.4.27)
Requirement already satisfied: pytz==2022.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 74)) (2022.1)
Requirement already satisfied: pytz-deprecation-shim==0.1.0.post0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 75)) (0.1.0.post0)
Requirement already satisfied: pyyaml==6.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 76)) (6.0)
Requirement already satisfied: pyzbar==0.1.9 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 77)) (0.1.9)
Requirement already satisfied: redis==4.3.4 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 78)) (4.3.4)
Requirement already satisfied: regex==2022.3.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 79)) (2022.3.2)
Requirement already satisfied: reportlab==3.6.11 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 80)) (3.6.11)
Requirement already satisfied: requests==2.28.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 81)) (2.28.1)
Requirement already satisfied: scikit-learn==1.1.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 82)) (1.1.1)
Requirement already satisfied: scipy==1.8.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 83)) (1.8.1)
Requirement already satisfied: service-identity==21.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 84)) (21.1.0)
Requirement already satisfied: setuptools==63.2.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 85)) (63.2.0)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 86)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 87)) (1.2.0)
Requirement already satisfied: sqlparse==0.4.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 88)) (0.4.2)
Requirement already satisfied: threadpoolctl==3.1.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 89)) (3.1.0)
Requirement already satisfied: tika==1.24 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 90)) (1.24)
Requirement already satisfied: tqdm==4.64.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 91)) (4.64.0)
Requirement already satisfied: twisted[tls]==22.4.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 92)) (22.4.0)
Requirement already satisfied: txaio==22.2.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 93)) (22.2.1)
Requirement already satisfied: typing-extensions==4.3.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 94)) (4.3.0)
Requirement already satisfied: tzdata==2022.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 95)) (2022.1)
Requirement already satisfied: tzlocal==4.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 96)) (4.2)
Requirement already satisfied: urllib3==1.26.10 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 97)) (1.26.10)
Requirement already satisfied: uvicorn[standard]==0.18.2 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 98)) (0.18.2)
Requirement already satisfied: uvloop==0.16.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 99)) (0.16.0)
Requirement already satisfied: watchdog==2.1.9 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 100)) (2.1.9)
Requirement already satisfied: watchfiles==0.16.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 101)) (0.16.0)
Requirement already satisfied: wcwidth==0.2.5 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 102)) (0.2.5)
Requirement already satisfied: websockets==10.3 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 103)) (10.3)
Requirement already satisfied: whitenoise==6.2.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 104)) (6.2.0)
Requirement already satisfied: whoosh==2.7.4 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 105)) (2.7.4)
Requirement already satisfied: wrapt==1.14.1 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 106)) (1.14.1)
Requirement already satisfied: zope.interface==5.4.0 in ./.local/lib/python3.9/site-packages (from -r requirements.txt (line 108)) (5.4.0)
Building wheels for collected packages: django-q
  Building editable for django-q (pyproject.toml) ... done
  Created wheel for django-q: filename=django_q-1.3.9-py3-none-any.whl size=5250 sha256=f5ea428c41acb3f5d3824b6d857c4db2accf56cc2257ee64b492ded820dce9db
  Stored in directory: /tmp/pip-ephem-wheel-cache-je3egzfw/wheels/54/68/ef/abeac6474cddb690f1d54361b7737a9a484eb35eb9fa14e667
Successfully built django-q
Installing collected packages: django-q
  Attempting uninstall: django-q
    Found existing installation: django-q 1.3.9
    Uninstalling django-q-1.3.9:
      Successfully uninstalled django-q-1.3.9
Successfully installed django-q-1.3.9`

**Comment by stumpylog** [comment]
I notice you're not running the managment command as the paperless user, which is who has the modules installed.  Try running `sudo -Hu paperless python3 manage.py ...`
