### ISSUE TITLE
[BUG] Internal server error @ fresh install

### ISSUE THREAD

**Issue by infracritical** [paperless-ngx/paperless-ngx#1481]
### Description

Get "Internal server error" with no description after a fresh install.  Have I missed a step, or is this a bug?

### Steps to reproduce

...

### Webserver logs

```bash
Nothing shows up using 'docker-compose logs -f'

webserver_1  | [2022-08-30 23:21:18 +0000] [44] [CRITICAL] WORKER TIMEOUT (pid:47)
webserver_1  | [2022-08-30 23:21:18 +0000] [44] [WARNING] Worker with pid 47 was terminated due to signal 6
```

### Paperless-ngx version

1.8.0

### Host OS

CentOS 7.9 -fully patched with latest patches

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

none

### Other

...

**Comment by Biepa** [comment]
I just installed for the first time. Had the same error in the logs. Took a while for paperless to show the website, but finally came up.

**Comment by shamoon** [comment]
Im not sure theres a true bug, no. Please see https://github.com/paperless-ngx/paperless-ngx/discussions/1417 (and many other discussions of this), in other cases the worker getting killed was a resource limitation e.g. OOM. Have you investigated that aspect? https://github.com/paperless-ngx/paperless-ngx/search?q=worker+timeout

**Comment by stumpylog** [comment]
I see this occasionally when first starting the container, even in an environment with a lot of resources.  However, it's never affected anything I can tell.  Is it affecting something for you?

The general solutions I've found suggest increasing the gunicorn timeout, but with it already set to 120, that doesn't seem like much of a solution.

**Comment by stumpylog** [comment]
```
[2022-09-01 17:53:19 -0700] [50] [INFO] Server is ready. Spawning workers
17:53:19 [Q] INFO Q Cluster rugby-four-sweet-apart starting.
2022-09-01 17:53:19,717 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-09-01 17:53:19,717 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-09-01 17:53:19,717 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-09-01 17:53:19,730] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /consume
17:53:19 [Q] INFO Process-1:1 ready for work at 67
17:53:19 [Q] INFO Process-1:2 ready for work at 69
17:53:19 [Q] INFO Process-1 guarding cluster rugby-four-sweet-apart
17:53:19 [Q] INFO Process-1:3 monitoring at 70
17:53:19 [Q] INFO Q Cluster rugby-four-sweet-apart running.
17:53:19 [Q] INFO Process-1:4 pushing tasks at 71
[2022-09-01 17:55:19 -0700] [50] [CRITICAL] WORKER TIMEOUT (pid:62)
[2022-09-01 17:55:19 -0700] [50] [WARNING] Worker with pid 62 was terminated due to signal 6
```

I can reproduce it, but only if `PAPERLESS_WEBSERVER_WORKERS` is set to 1.  It does appear to prevent the login from loading until the timeout is completed and the worker is respawned.

**Comment by stumpylog** [comment]
This will be fixed in the next release.
