### ISSUE TITLE
[BUG] PDFs not consumed via "consume" directory

### ISSUE THREAD

**Issue by Biepa** [paperless-ngx/paperless-ngx#1484]
### Description

I installed paperless locally and the consumption worked pretty quick. Then deleted everything and set it up with the webserver volumes being placed on a network share.
I can see the documents in the "consume" directory inside the docker container. But they don't seem to be consumed.

### Steps to reproduce

Setup all webserver volumes on a network share via CIFS.
It looks like a bit like https://github.com/paperless-ngx/paperless-ngx/issues/879

### Webserver logs

```bash
webserver_1  | Executing /usr/local/bin/paperless_cmd.sh
webserver_1  | 2022-08-31 13:15:37,928 INFO Set uid to user 0 succeeded
webserver_1  | 2022-08-31 13:15:37,934 INFO supervisord started with pid 132
webserver_1  | 2022-08-31 13:15:38,939 INFO spawned: 'consumer' with pid 133
webserver_1  | 2022-08-31 13:15:38,954 INFO spawned: 'gunicorn' with pid 134
webserver_1  | 2022-08-31 13:15:38,960 INFO spawned: 'scheduler' with pid 135
webserver_1  | 2022-08-31 13:15:39,966 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | 2022-08-31 13:15:39,969 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | 2022-08-31 13:15:39,972 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
webserver_1  | [2022-08-31 13:15:40 +0000] [134] [INFO] Starting gunicorn 20.1.0
webserver_1  | [2022-08-31 13:15:40 +0000] [134] [INFO] Listening at: http://[::]:8000 (134)
webserver_1  | [2022-08-31 13:15:40 +0000] [134] [INFO] Using worker: paperless.workers.ConfigurableWorker
webserver_1  | [2022-08-31 13:15:40 +0000] [134] [INFO] Server is ready. Spawning workers
webserver_1  | [2022-08-31 13:15:42,167] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
webserver_1  | 13:15:42 [Q] INFO Q Cluster failed-colorado-india-zebra starting.
webserver_1  | 13:15:42 [Q] INFO Process-1:1 ready for work at 152
webserver_1  | 13:15:42 [Q] INFO Process-1:2 monitoring at 153
webserver_1  | 13:15:42 [Q] INFO Process-1 guarding cluster failed-colorado-india-zebra
webserver_1  | 13:15:42 [Q] INFO Process-1:3 pushing tasks at 154
webserver_1  | 13:15:42 [Q] INFO Q Cluster failed-colorado-india-zebra running.
webserver_1  | 13:16:07 [Q] INFO Enqueued 1
webserver_1  | 13:16:07 [Q] INFO Process-1 created a task from schedule [Train the classifier]
webserver_1  | 13:16:07 [Q] INFO Process-1:1 processing [ten-apart-ohio-august]
webserver_1  | 13:16:07 [Q] INFO Enqueued 1
webserver_1  | 13:16:07 [Q] INFO Process-1 created a task from schedule [Optimize the index]
webserver_1  | 13:16:07 [Q] INFO Enqueued 1
webserver_1  | 13:16:07 [Q] INFO Process-1 created a task from schedule [Perform sanity check]
webserver_1  | 13:16:07 [Q] INFO Enqueued 1
webserver_1  | 13:16:07 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
webserver_1  | 13:16:08 [Q] INFO Process-1:1 stopped doing work
webserver_1  | 13:16:08 [Q] INFO Processed [ten-apart-ohio-august]
webserver_1  | 13:16:12 [Q] INFO recycled worker Process-1:1
webserver_1  | 13:16:12 [Q] INFO Process-1:4 ready for work at 165
webserver_1  | 13:16:12 [Q] INFO Process-1:4 processing [happy-winner-oklahoma-coffee]
webserver_1  | 13:16:13 [Q] INFO Process-1:4 stopped doing work
webserver_1  | 13:16:14 [Q] INFO Processed [happy-winner-oklahoma-coffee]
webserver_1  | 13:16:17 [Q] INFO recycled worker Process-1:4
webserver_1  | 13:16:17 [Q] INFO Process-1:5 ready for work at 168
webserver_1  | 13:16:17 [Q] INFO Process-1:5 processing [fifteen-stairway-tennis-nuts]
webserver_1  | [2022-08-31 13:16:18,398] [INFO] [paperless.sanity_checker] Sanity checker detected no issues.
webserver_1  | 13:16:18 [Q] INFO Process-1:5 stopped doing work
webserver_1  | 13:16:18 [Q] INFO Processed [fifteen-stairway-tennis-nuts]
webserver_1  | 13:16:22 [Q] INFO recycled worker Process-1:5
webserver_1  | 13:16:22 [Q] INFO Process-1:6 ready for work at 172
webserver_1  | 13:16:22 [Q] INFO Process-1:6 processing [monkey-mockingbird-uncle-ten]
webserver_1  | 13:16:22 [Q] INFO Process-1:6 stopped doing work
webserver_1  | 13:16:23 [Q] INFO Processed [monkey-mockingbird-uncle-ten]
webserver_1  | 13:16:27 [Q] INFO recycled worker Process-1:6
webserver_1  | 13:16:27 [Q] INFO Process-1:7 ready for work at 174
webserver_1  | [2022-08-31 13:17:40 +0000] [134] [CRITICAL] WORKER TIMEOUT (pid:137)
webserver_1  | [2022-08-31 13:17:41 +0000] [134] [WARNING] Worker with pid 137 was terminated due to signal 6
webserver_1  | 13:21:08 [Q] INFO Enqueued 1
webserver_1  | 13:21:08 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
webserver_1  | 13:21:08 [Q] INFO Process-1:7 processing [beryllium-mississippi-glucose-venus]
webserver_1  | 13:21:08 [Q] INFO Process-1:7 stopped doing work
webserver_1  | 13:21:08 [Q] INFO Processed [beryllium-mississippi-glucose-venus]
webserver_1  | 13:21:13 [Q] INFO recycled worker Process-1:7
webserver_1  | 13:21:13 [Q] INFO Process-1:8 ready for work at 315
webserver_1  | [2022-08-31 13:29:40,785] [WARNING] [django.request] Not Found: /api/logs/mail/
webserver_1  | 13:31:10 [Q] INFO Enqueued 1
webserver_1  | 13:31:10 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
webserver_1  | 13:31:10 [Q] INFO Process-1:8 processing [red-paris-edward-muppet]
webserver_1  | 13:31:10 [Q] INFO Process-1:8 stopped doing work
webserver_1  | 13:31:10 [Q] INFO Processed [red-paris-edward-muppet]
webserver_1  | 13:31:15 [Q] INFO recycled worker Process-1:8
webserver_1  | 13:31:15 [Q] INFO Process-1:9 ready for work at 613
```

### Paperless-ngx version

1.8.0

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Firefox

**Comment by Biepa** [comment]
Changed the loglevel to debug:

`Attaching to paperless_webserver_1, paperless_broker_1, paperless_db_1
broker_1     | 1:C 31 Aug 2022 13:52:12.395 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
broker_1     | 1:C 31 Aug 2022 13:52:12.396 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=1, just started
broker_1     | 1:C 31 Aug 2022 13:52:12.396 # Configuration loaded
broker_1     | 1:M 31 Aug 2022 13:52:12.399 * Running mode=standalone, port=6379.
broker_1     | 1:M 31 Aug 2022 13:52:12.399 # Server initialized
broker_1     | 1:M 31 Aug 2022 13:52:12.399 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
broker_1     | 1:M 31 Aug 2022 13:52:12.400 * Loading RDB produced by version 6.0.16
broker_1     | 1:M 31 Aug 2022 13:52:12.400 * RDB age 376 seconds
broker_1     | 1:M 31 Aug 2022 13:52:12.400 * RDB memory usage when created 0.77 Mb
broker_1     | 1:M 31 Aug 2022 13:52:12.401 * DB loaded from disk: 0.000 seconds
broker_1     | 1:M 31 Aug 2022 13:52:12.401 * Ready to accept connections
broker_1     | 1:M 31 Aug 2022 13:52:12.401 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:12.401 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:17.421 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:17.421 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:22.443 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:22.443 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:27.464 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:27.464 . 0 clients connected (0 replicas), 804280 bytes in use
db_1         | 
db_1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1         | 
db_1         | 2022-08-31 13:52:12.855 UTC [1] LOG:  starting PostgreSQL 13.8 (Debian 13.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1         | 2022-08-31 13:52:12.856 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1         | 2022-08-31 13:52:12.856 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1         | 2022-08-31 13:52:14.551 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1         | 2022-08-31 13:52:15.435 UTC [26] LOG:  database system was shut down at 2022-08-31 13:51:48 UTC
db_1         | 2022-08-31 13:52:16.419 UTC [1] LOG:  database system is ready to accept connections
webserver_1  | Paperless-ngx docker container starting...
webserver_1  | Mapping UID and GID for paperless:paperless to 0:0
broker_1     | 1:M 31 Aug 2022 13:52:32.484 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:32.484 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:37.504 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:37.504 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:42.524 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:42.524 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:47.544 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:47.544 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:52.564 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:52.564 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:52:57.586 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:52:57.586 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:53:02.608 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:53:02.608 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:53:07.631 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:53:07.631 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:53:12.652 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:53:12.652 . 0 clients connected (0 replicas), 804280 bytes in use
broker_1     | 1:M 31 Aug 2022 13:53:17.673 - DB 0: 1 keys (1 volatile) in 4 slots HT.
broker_1     | 1:M 31 Aug 2022 13:53:17.673 . 0 clients connected (0 replicas), 804280 bytes in use
`

**Comment by Biepa** [comment]
Restarted all containers and after 7 minutes the webserver came up. Is that the normal behaviour?

**Comment by Biepa** [comment]
Thank you for your reply. The mentioned option helped with my NAS share so the consumer is getting the documents.
The webserver startup runs in some type of timeout until it starts
```
[135] [CRITICAL] WORKER TIMEOUT (pid:138)
```
I only see timeout options for the worker for the OCR in the documentation.
Is that the one running on startup of the webserver?

**Comment by stumpylog** [comment]
That timeout is from gunicorn, which doesn't relate to the consumer. It's been fixed though
