### ISSUE TITLE
[Bug] Docker Build armv7 fails

### ISSUE THREAD

**Issue by schnuffle** [paperless-ngx/paperless-ngx#150]
The problems with the armv7 build exists because there's no wheel package for pikepdf on armv7.
That leads to the package being compiled
pikepdf depends on qpdf > 10.3 whereas debian bullseye only provides v10.1. That leads to a compile error due to missing headers files.

I've created a stripped down workflow tring to solve the problem yesterday and the last run just when i felt asleep has been successfull.
The major change has been to compile a recent qpdf version manually.

The workflow can be seen at: https://github.com/schnuffle/paperless-ngx/tree/ci-fix

If there's interest in integrating the changes i can extract them and create a PR. Though we'll need to build the armv7 image differently from the other plattforms

Regards

Schnuffle

**Comment by qcasey** [comment]
This [might still be failing](https://github.com/paperless-ngx/paperless-ngx/runs/5353930474?check_suite_focus=true)? 

You could name the branch something like `feature-docker-fix-ci` to get `build-docker-image` step to run/publish.

**Comment by bauerj** [comment]
Ugh, oh well.

I think I see what's wrong: I enabled qpdf compilation only for armv7. Now the other architectures don't have qpdf installed at all. It probably just needs a "apt-get -y install libqpdf-dev" and "apt-get remove libqpdf-dev" somewhere.

I hope I'll have time for that tomorrow. If anyone else wants to give it a shot, go for it.

**Comment by qcasey** [comment]
Getting close though!

I tried `apt-get -y install libqpdf-dev` but ran into [this error](https://github.com/paperless-ngx/paperless-ngx/runs/5362031783?check_suite_focus=true):

https://github.com/pikepdf/pikepdf/issues/292

Is there anything wrong with building qpdf on all platforms?

**Comment by bauerj** [comment]
Forget what I said, it was probably too early in the morning!

The binary wheels for pikepdf should already have qpdf included, so no need to have it installed on the OS-level there.

**Comment by qcasey** [comment]
That looks good, thanks! I think we're awaiting #174 but the [most recent build](https://github.com/paperless-ngx/paperless-ngx/runs/5363149667?check_suite_focus=true) passed the wheel stage

**Comment by bauerj** [comment]
Yes, it works! 😮

And it took only three people to fix it 😄

**Comment by qcasey** [comment]
This worked well, `dev` was successfully built on 3 archs. Thank you both!
