### ISSUE TITLE
[BUG] Assignment of rights does not work correctly

### ISSUE THREAD

**Issue by AlRo75** [paperless-ngx/paperless-ngx#1526]
### Description

I created a new user and assigned permissions to it. Unfortunately, this user can now delete documents, although he does not have this right.

![image](https://user-images.githubusercontent.com/103645905/188310911-1b8e179f-f75e-4cba-9182-d31dd0ca058e.png)

### Steps to reproduce

1. Create new user.
2. Assign Permissions.
3. Login with this user.
4. Now delete a document.

![image](https://user-images.githubusercontent.com/103645905/188311108-b9f7aaa4-0d7d-41ef-b6d6-d43070017a48.png)

### Paperless-ngx version

1.8.0

### Host OS

Raspberry PI arm64

### Installation method

Docker - official image

### Browser

Edge

**Comment by AlRo75** [comment]
It is also possible to delete views, correspondents, etc., although the respective deletion authorization has not been granted.

**Comment by shamoon** [comment]
Sorry this isn’t a big, multi user permissions aren’t supported yet. See #295
