### ISSUE TITLE
[BUG] v1.9.0 RC1 Bug - Comments appear to be on all documents

### ISSUE THREAD

**Issue by stumpylog** [paperless-ngx/paperless-ngx#1564]
### Description

I believe this is just a visual bug, but when a comment is added to a document, then you navigate to a new document using the arrows, the added comment remains in the comments tab.  It remains visible until a refresh of the page.

A similar issue happens if you start navigation from a document with no comment, then navigate to one with a comment.  It appears to have no comments until a refresh.

### Steps to reproduce

1. Add comment to document
2. Navigate to next document via arrow buttons
3. See the comment seemingly applied to the new document

### Paperless-ngx version

1.9.0 RC1

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Ah thanks, I’ll sort this out. Haven’t had a chance to poke around the beta yet.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/16882b8fa903eef16228185a12b91730ee4dfd42
