### ISSUE TITLE
Upgrade to Django 4.0

### ISSUE THREAD

**Issue by bauerj** [paperless-ngx/paperless-ngx#157]
Django 4.0 has been release. We are still using 3.2.

There is no need to update ASAP but we should keep this in mind.

We need to check if anything here is relevant to us: https://docs.djangoproject.com/en/4.0/releases/4.0/#backwards-incompatible-4-0

**Comment by qcasey** [comment]
#180

**Comment by stumpylog** [comment]
I looked into why the tests are failing under 4.0.  I fixed them in [`stumpylog:fix-django-4.0-tests`](https://github.com/stumpylog/paperless-ngx/tree/fix-django-4.0-tests).

With that said, there might be more updates/better ways to do things, given the large version bump.

**Comment by stumpylog** [comment]
We upgrade in #497 and nothing exploded yet, so I'm going to close this,

**Comment by gador** [comment]
Actually, a lot of Django-extensions test cases fail with django4, but I haven't noticed any regression in using paperless-ngx.
See https://github.com/django-extensions/django-extensions/issues/1695
