### ISSUE TITLE
[Roadblock] i can't seem ti install the --dev requirments

### ISSUE THREAD

**Issue by Puthus** [paperless-ngx/paperless-ngx#1575]
### Description

while following the setup process for developing i found myself stuck at this error
![image](https://user-images.githubusercontent.com/32844173/189880168-ce1ef841-640b-4270-b47e-125e89e9a40d.png)

### Steps to reproduce

1. go to src
2. pipenv install --dev

### Paperless-ngx version

latest

### Host OS

Ubuntu 20.04.5 LTS on Windows 10 x86_64

### Installation method

Bare metal

### Browser

Edge

**Comment by Puthus** [comment]
> sudo apt install python3-pip

![image](https://user-images.githubusercontent.com/32844173/189883828-4be12db6-7c21-42d2-aa8a-bed7676732c1.png)
Already installed them

**Comment by stumpylog** [comment]
What version of `pipenv`?  I know they had some recent issues around the virtualenv creation not including everything to bootstrap itself.

**Comment by Puthus** [comment]
> What version of `pipenv`? I know they had some recent issues around the virtualenv creation not including everything to bootstrap itself.

pipenv, version 11.9.0

**Comment by stumpylog** [comment]
Ah, I'm going to assume that is installed from your package manager.

I would suggest upgrading that: `pip install --user --upgrade pipenv`
