### ISSUE TITLE
[BUG] PDF could not add, HTTP 413

### ISSUE THREAD

**Issue by turian** [paperless-ngx/paperless-ngx#1581]
### Description

PDF uploads on the demo site are not working, but I really want to try paperless-ngx

<img width="330" alt="image" src="https://user-images.githubusercontent.com/65918/190022921-6dcdc63b-0358-4725-aac2-4d137b4feba1.png">

### Steps to reproduce

1) Go to [demo](https://demo.paperless-ngx.com/dashboard)
2) Try to upload [this PDF](https://cs.brown.edu/courses/csci2952d/readings/lecture1-firth.pdf)
3) Get the following error:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/65918/190022921-6dcdc63b-0358-4725-aac2-4d137b4feba1.png">

### Paperless-ngx version

demo.paperless-ngx.com

### Host OS

demo.paperless-ngx.com

### Installation method

Other (please describe above)

### Browser

Chrome

### Configuration changes

n/a

**Comment by stumpylog** [comment]
How large is the file?  That response means the payload is too large.

**Comment by shamoon** [comment]
Yes the demo site intentionally limits upload size to manage resources as it is not a particularly powerful server. Smaller files work fine, that one is rather large since it’s scans from a book. If you’re wedded to testing that one you can take off some pages
