### ISSUE TITLE
[BUG] DOUBLE Patch-T document seperator always leads to a failed task

### ISSUE THREAD

**Issue by Skram-de** [paperless-ngx/paperless-ngx#1590]
### Description

Using the "patch-T" document seperator always leads to a failed task. Documents are seperated and stored properly. The failed tasks drag attention even though it's not necessary.

Seperator is [Patch-T](https://www.alliancegroup.co.uk/downloads/patches-for-printing-on-a4-paper.pdf).

![image](https://user-images.githubusercontent.com/113503248/190173386-e8604473-484a-4ba4-b18a-6a9bbbbf000f.png)

### Steps to reproduce

Source document format is pdf , it has 5 pages, page 3 is "patch-t" seperator.

### Webserver logs

```bash
Unable to get page count.
Syntax Error: Invalid page count 0
Command Line Error: Wrong page range given: the first page (1) can not be after the last page (0).
 : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 479, in pdfinfo_from_path
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/docker/src/django-q/django_q/cluster.py", line 434, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 109, in consume_file
    separators = barcodes.scan_file_for_separating_barcodes(file_to_process)
  File "/usr/src/paperless/src/documents/barcodes.py", line 110, in scan_file_for_separating_barcodes
    pages_from_path = convert_from_path(filepath, output_folder=path)
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 488, in pdfinfo_from_path
    raise PDFPageCountError(
pdf2image.exceptions.PDFPageCountError: Unable to get page count.
Syntax Error: Invalid page count 0
Command Line Error: Wrong page range given: the first page (1) can not be after the last page (0).
```

### Paperless-ngx version

1.8

### Host OS

Linux 3.10.108 #42661 SMP (x86_64)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
Can you provide a sample file?  At a glance, it looks like a malformed document, where `pdfinfo` isn't able to get valid pages out from the document.

**Comment by Skram-de** [comment]
That's what the scanner generated:
[0166_220914170108_SEP.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9567661/0166_220914170108_SEP.pdf)

Paperless splits this into 3 files. 1 and 3 are consumed correctly. File 2 seems to be the "seperator file" which contains no pages and leads to the error. Attached here.
[0166_220914170108_SEP_document_1.pdf](https://github.com/paperless-ngx/paperless-ngx/files/9567697/0166_220914170108_SEP_document_1.pdf)

**Comment by stumpylog** [comment]
Ah, I see.  The back to back patch-t barcodes are probably what's tripping it up.  The assumption was probably a single patch-t seperator, not 2 end to end.

**Comment by Skram-de** [comment]
Same issue with single patch-t page

**Comment by stumpylog** [comment]
That's surprising, we have quite good coverage of the more normal cases.  Where is the patch code in this document?  Maybe the end or middle?

**Comment by gador** [comment]
The error seems to be in getting the page count of the PDF.

Can you provide a sample PDF where the error occurs?

What happens if you just use the seperator page? 

I suspect, the error lies in an unusual PDF format. 
We test with standard PDFs and as @stumpylog said, we have a good coverage.

**Comment by gador** [comment]
Ah I just took a look at your scan.

It could be the case, that two seperator pages right behind each other are the problem. It tries to get the document between the seperator pages and it obviously can't find it.

Please try with just a single seperator page

**Comment by Skram-de** [comment]
I was wrong, sorry! :/

The error only occurs having 2 or more seperator in a row. The PDF between the seperators has no content. That's clear.
As I always scan double sided pages, i created this double-sided seperator.
Otherwise the blank backside of the seperator will be added to the second document as first page. That's what I tried to avoid because of the blank thumbnail in this case....

**Comment by gador** [comment]
Oh boy, the mobile github app seemed to have swallowed the other answers. Sorry.

Could you upload the document where the error occurs with the single seperator page?

**Comment by Skram-de** [comment]
@gador , I was wrong. Look at my last [post](https://github.com/paperless-ngx/paperless-ngx/issues/1590#issuecomment-1247035126). So I can't provide a document with a single seperator that leads to an error because there is none. Sorry for that! 
I renamed this issue.

**Comment by gador** [comment]
Hi @Skram-de thanks for your feedback!

I'll look into it sometime later, when I have access to my laptop again 👍

**Comment by stumpylog** [comment]
The next release will fix this.
