### ISSUE TITLE
[BUG] Demo password doesn't work

### ISSUE THREAD

**Issue by thebarless** [paperless-ngx/paperless-ngx#1593]
### Description

Demo instructions say:
"A demo is available at [demo.paperless-ngx.com](https://demo.paperless-ngx.com/) using login demo / demo. Note: demo content is reset frequently and confidential information should not be uploaded."

![Screen Shot 2022-09-14 at 12 17 43](https://user-images.githubusercontent.com/20303110/190208293-22a4ee9d-6c4c-420f-bd89-52959f4d1ec7.png)

### Steps to reproduce

Go to demo.paperless-ngx.com
Type in username: demo
Type in password: demo
Submit
Cry

### Paperless-ngx version

Demo

### Host OS

Yours

### Installation method

Other (please describe above)

### Browser

Firefox

**Comment by mikehosmar** [comment]
I have also noticed this.

**Comment by shamoon** [comment]
The demo site gets rebuilt every X hours. Unfortunately sometimes people do things like change the password, should be sorted now, thanks.
