### ISSUE TITLE
[BUG] DOCKER container misses CRONITER to use CRON schedule type

### ISSUE THREAD

**Issue by Skram-de** [paperless-ngx/paperless-ngx#1598]
### Description

Container misses a dependend package if you want to schedule tasks by cron: CRONITER

![image](https://user-images.githubusercontent.com/113503248/190364929-378f8866-f4b3-4489-ab7c-4d7d9e2e790e.png)

### Steps to reproduce

UI -> admin -> Scheduled tasks -> add scheduled task -> use schedule type "cron"

### Webserver logs

```bash
[Q] ERROR Please install croniter to enable cron expressions
```

### Paperless-ngx version

1.8

### Host OS

Linux 3.10.108 #42661 SMP (x86_64)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Im not sure if this is really a bug in the sense that even though this is built into the Django admin its not really functionality relevant to Paperless, actual Paperless tasks run fine. Curious, what is your use case here anyway?

**Comment by Skram-de** [comment]
No big deal, i can install it manually.
Use case is to allow my HDDs to fall asleep at night. So i train the classifier only 9 to 5. Same with checking mail accounts.

**Comment by stumpylog** [comment]
It would be easy enough to add, but there's some discussion around dropping django-q anyway, as it isn't maintained by the original author anymore.  And the replacement supports cron without croniter.

**Comment by Skram-de** [comment]
Thanks for you feedback! It's no problem at all. Many roads lead to Rome.
I just thought: "If it's selectable (cron) i can use it....". :)
