### ISSUE TITLE
[BUG] permission error if no consume share is mapped

### ISSUE THREAD

**Issue by mtettke123** [paperless-ngx/paperless-ngx#1599]
### Description

starting with Paperless-ngx 1.8.0, Paperless on docker does not start when no consume share is mapped:

`
  SystemCheckError: System check identified some issues:
  ERRORS:
  ?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
  drwxr-xr-x /usr/src/paperless/consume
  to be writeable by the user running the Paperless services

`

I've some containers running without a mapped share, as I don't need a consumption folder. Was no issue in previous versions; I assume the permissions of the folder in the docker container has changed.

### Steps to reproduce

1. create docker-compose without mapped consumption folder
2. look at the error message

### Webserver logs

```bash
SystemCheckError: System check identified some issues:
ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
drwxr-xr-x /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
```

### Paperless-ngx version

1.8,0

### Host OS

docker

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
That's curious indeed.  If you get a shell inside the container, what does `ls -ahl /usr/src/paperless` output?

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/3b34aed64f63c2d76a54ed90986b7fca4639f459

**Comment by mtettke123** [comment]
Perfect :-)

**Comment by mrwee** [comment]
How can I fix this manually? Running the install-script gives me the same error. Don't know when 1.9 is due out.

**Comment by stumpylog** [comment]
There's a couple options.

1. The `beta` is pretty stable at this point.  After a backup, you could run it until 1.9 is released
2. Map the consumption folder, even if you won't be using it
