### ISSUE TITLE
[BView storage with directoy not error 

### ISSUE THREAD

**Issue by JBufe** [paperless-ngx/paperless-ngx#1606]
### Description

![image](https://user-images.githubusercontent.com/113714227/190691860-fa77e2f5-1c0e-4b09-b9d7-84d9e8472c03.png)
When trying to store a search only with storage directoy as value I receive an error without any code number. Alos log didn't show any additional information

### Steps to reproduce

Any time I try to store a search just with a directory filter. Anyother filter works fine.

### Webserver logs

```bash
no logs
```

### Paperless-ngx version

18.0

### Host OS

Ubuntu LXC with Docker 

### Installation method

Docker - official image

### Browser

Edge

### Configuration changes

no

**Comment by shamoon** [comment]
Thank you, this issue is already fixed and will be in our next release, see #1462
