### ISSUE TITLE
[BUG] Error in Example Configuration

### ISSUE THREAD

**Issue by alan-kniep** [paperless-ngx/paperless-ngx#1613]
### Description

While trying to configure the barcode-feature, I copied the lines 66 to 67 from the [example configuration](https://github.com/paperless-ngx/paperless-ngx/blob/b9e60e0145af9199f35a980d9cff16d7065372d3/paperless.conf.example#L66-L67):
```
#PAPERLESS_CONSUMER_ENABLE_BARCODES=false
#PAPERLESS_CONSUMER_ENABLE_BARCODES=PATCHT
```
I noticed that line 67 was (probably) copied from 66 and should be this:
```
#PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT
```
As it is in the [documentation](https://paperless-ngx.readthedocs.io/en/latest/configuration.html#software-tweaks).

### Steps to reproduce

1. Use the [paperless.conf.example](https://github.com/paperless-ngx/paperless-ngx/blob/main/paperless.conf.example) as a starting point for your own configuration.
2. Uncomment the lines related to the barcode-feature and enable it.
3. Notice that the barcode-feature is not enabled.

### Paperless-ngx version

1.8.0

### Host OS

Archlinux x86_64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Thanks, this is actually already fixed and should updated once v1.9.0 beta is released. See https://github.com/paperless-ngx/paperless-ngx/blob/beta/paperless.conf.example
