### ISSUE TITLE
[BUG] v1.9.0 RC1 Bug: missing exec in paperless_cmd.sh 

### ISSUE THREAD

**Issue by lemmi** [paperless-ngx/paperless-ngx#1616]
### Description

This should be called through `exec`:
https://github.com/paperless-ngx/paperless-ngx/blob/b9e60e0145af9199f35a980d9cff16d7065372d3/docker/paperless_cmd.sh#L15

### Steps to reproduce

With `podman stop`, the container will ignore the `TERM` signal and is only removed after the timeout has passed and is getting `KILL`ed

### Paperless-ngx version

ghcr.io/paperless-ngx/paperless-ngx:beta@sha256:ca34bd64209e3c3543ace5c31509ca05679586cbf70f867f55771ba127bc5abf

### Host OS

voidlinux

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Thank you for the report and the fix.  I always like that combination!  Now fixed in the `beta` branch.
