### ISSUE TITLE
[BUG] Cant save view when storage path is selected

### ISSUE THREAD

**Issue by ThomasMuenster** [paperless-ngx/paperless-ngx#1619]
### Description

If a view is selected with a storage path and you try to save it this message occurs:

![grafik](https://user-images.githubusercontent.com/114019195/191334571-0841ffd3-670c-414a-85d0-8a487757a518.png)

### Steps to reproduce

select a temporary view with storage path

try to "save as" view

### Webserver logs

```bash
[2022-09-20 20:17:44,010] [WARNING] [django.request] Bad Request: /api/saved_views/
```

### Paperless-ngx version

1.8.0

### Host OS

unraid

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
Thanks for the report, this one (and the other you reported) have already been fixed and are being tested in our current [beta](https://github.com/paperless-ngx/paperless-ngx/pull/1560). Gentle reminder to search before opening an issue, but thanks again.

See #1462 and #1606

**Comment by ThomasMuenster** [comment]
Thanks for the reminder, I'm new to this so I just checked the opened issues.

Thank you for your work!
