### ISSUE TITLE
[Other][Migration] Collaboration with ngx team and community

### ISSUE THREAD

**Issue by sytone** [paperless-ngx/paperless-ngx#164]
Taking to an issue to track the ngx team and community views. There are a few options, some which are in place now for communication with the team/community. 

We currently have:
- GitHub Discussions
- Matrix

A proposed way to communicate with the community in a simpler manner is also by having a paperless-ngx Discord server which allows for more real time interaction with community as well as allowing the community to interact with each other more. This is usually seen as a simpler way for general users to interact and provides more flexibility than the current Matrix or Github solutions.

Looking for feedback from the team on this.

**Comment by yschroeder** [comment]
I use discord mostly for audio chat with close friends and have it installed on all my platforms. I have also used discord for various open source projects (klipper, wled, home assistant, superslicer) which use discord to connect with the community. My experience is mediocre at best. I see multiple problems:

1. These servers have an insane amount of channels, so it is overwhelming to find the correct one to post your issue.
2. You need to be very lucky to find a person that can actually help you. It is real time communication and your chat partner needs to be awake (timezones). If he isn't, your message will age and you get no response.
3. A combination of 1 and 2 results in very few people watching a specific channel making it even less likely to get an answer.
4. Discord chats are messy when multiple topics are discussed at the same time. There are threads now but I haven't seen extensive use.
5. Discord chats are not indexed by search engines. People cannot find solutions to existing problems and have to ask the same questions over and over again.

Ask yourself this question: where do you find help without asking the question yourself? It is either github, reddit or stackoverflow. If we want to move away from github issues for community support, I would suggest to create a discourse forum.

I would be fine to use the github issues for now and the matrix room for the occasional informal chat with other contributors.

Using github issues also shows other people that this is an active and alive project. Even moving to discourse will hide this activity.

**Comment by shamoon** [comment]
I definitely think the core of discussion should be here for the reasons above and others. Not just Issues btw, Discussions are helpful too, they have some useful features (like voting).

I think chat has been discussed before and people seem happy with Matrix, I cant say I feel strongly but its been working fine so far. As @yschroeder said, mostly discussion here with informal stuff on Matrix

**Comment by sytone** [comment]
All makes sense, just wanted to make sure the group is clear with the decision and where we are going. I use a combination of them all for different open-source projects. 

The GitHub Discussions have a nice integration so you can go back and forth from them to issues as required and they are searchable which is a plus. 

So we Have:

- GitHub Discussions to talk about issues or new features or general platform questions. 
- Matrix for informal chats about contributions.
- Issues to track actual bugs or issues with the platform (may come from a chat in GitHub discussions or Matric) and also use issues to track new feature requests or implementations so they can be better tied to a PR. 

Sound good?
