### ISSUE TITLE
[BUG] 1.9 OCR output mode "skip_noarchive" is not valid

### ISSUE THREAD

**Issue by brightdroid** [paperless-ngx/paperless-ngx#1643]
### Description

With version 1.9 the following env trow errors:
```ini
PAPERLESS_OCR_MODE=skip_noarchive
```

### Steps to reproduce

1. set above docker env variable
2. start container

### Webserver logs

```bash
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 50014:50014
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
SystemCheckError: System check identified some issues:
ERRORS:
?: OCR output mode "skip_noarchive" is not valid
```

### Paperless-ngx version

1.9

### Host OS

Ubuntu 22.04 x86_64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Thanks for the report, I think https://github.com/paperless-ngx/paperless-ngx/pull/1551

**Comment by brightdroid** [comment]
So the option is removed or just a failure? The [documentation](https://paperless-ngx.readthedocs.io/en/latest/configuration.html?highlight=PAPERLESS_OCR_MODE#ocr-settings) still lists this value. Hope it's not removed, though.

**Comment by stumpylog** [comment]
No, it's still valid, I missed that setting as an option.
