### ISSUE TITLE
[BUG] Office365 Business IMAP basic auth broken

### ISSUE THREAD

**Issue by beber-msft** [paperless-ngx/paperless-ngx#1647]
### Description

Microsoft is disabling basic authentication for Exchange online and therefore O365 Business on October first. Therefore Imap auth for those accounts will be broken:

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-september-2021-update/ba-p/2772210

Currently basic auth is beeing used. On tenants that have basic auth already disabled, the following error appears in paperless-ngx:

imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'LOGIN failed.']

### Steps to reproduce

Use imap fetcher for Exchange online account with disabled basic auth.
get:
imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'LOGIN failed.']

### Paperless-ngx version

1.80

### Host OS

Ubuntu

### Installation method

Docker - official image

### Browser

Edge

**Comment by shamoon** [comment]
Im not sure this is the appropriate place to raise the issue, this change will break many many projects, I assume. Our IMAP library is https://github.com/ikvk/imap_tools and I dont see this mentioned there. But basically, without exchange support I dont see how this will be resolved and may just end up with these accounts no longer being supported...

Someone correct me if Im wrong, please.

**Comment by stumpylog** [comment]
Or is AUTH PLAIN still supported?  That's what the `login_ut8` uses under the hood, and I don't think changing everything to use just that would break anything (fingers crossed)

**Comment by Rondal** [comment]
As far as I'm aware there is no way to use what Microsoft calls Basic Auth in the future. It was disabled for all tenants beginning of this month. It is possible to reenable Basic Auth until end of December but starting January it will be gone.

See: 
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

and

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437

**Comment by shamoon** [comment]
Great idea, I made a PR for that.
