### ISSUE TITLE
[BUG] documents not read after upgrade 1.8 to 1.9

### ISSUE THREAD

**Issue by tomdh76** [paperless-ngx/paperless-ngx#1651]
### Description

After upgrading from 1.8 to 1.9 I see this error when going to documents:

Error while loading documents: 
```<!doctype html> <html lang="en"> <head> <title>Server Error (500)</title> </head> <body> <h1>Server Error (500)</h1><p></p> </body> </html>```

I cannot see any documents anymore. All documents are still in the media folders, and when I try to add a document in the dashboard it states that it is allready there. 

### Steps to reproduce

Rebooting or restarting paperless-webserver does not help

### Paperless-ngx version

1.9

### Host OS

LXC container proxmox

### Installation method

Bare metal

**Comment by stumpylog** [comment]
Please provide any webserver logs from when you try to view documents.

**Comment by tomdh76** [comment]
I cannot find the webserver log file but I see this when checking systemctl status paperless-webserver

Sep 26 19:30:51 paperless-ngx gunicorn[247]:     return executor(sql, params, many, context)
Sep 26 19:30:51 paperless-ngx gunicorn[247]:   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 89, in _execute
Sep 26 19:30:51 paperless-ngx gunicorn[247]:     return self.cursor.execute(sql, params)
Sep 26 19:30:51 paperless-ngx gunicorn[247]:   File "/usr/local/lib/python3.9/dist-packages/django/db/utils.py", line 91, in __exit__
Sep 26 19:30:51 paperless-ngx gunicorn[247]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Sep 26 19:30:51 paperless-ngx gunicorn[247]:   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 89, in _execute
Sep 26 19:30:51 paperless-ngx gunicorn[247]:     return self.cursor.execute(sql, params)
Sep 26 19:30:51 paperless-ngx gunicorn[247]:   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/sqlite3/base.py", line 477, in execute
Sep 26 19:30:51 paperless-ngx gunicorn[247]:     return Database.Cursor.execute(self, query, params)
Sep 26 19:30:51 paperless-ngx gunicorn[247]: django.db.utils.OperationalError: no such column: documents_document.original_filename

**Comment by stumpylog** [comment]
That looks like you have missed running the database migrations.  I would stop everything and run `python3 manage.py migrate` to make sure those are completed.

**Comment by tomdh76** [comment]
Thanks a lot! That was it!
