### ISSUE TITLE
[BUG] - solved - Changes in the document view failed

### ISSUE THREAD

**Issue by solluh** [paperless-ngx/paperless-ngx#1659]
### Description

If I make changes to documents via the document view, nothing changes after confirmation in the dialog box, but the changes are implemented.

![Bildschirmfoto 2022-09-27 um 13 19 17](https://user-images.githubusercontent.com/42142710/192514952-552ca368-38fc-4288-be4d-c216b0d9b583.png)

The dialog box does not close on its own.

Thanks!

### Steps to reproduce

1. select douments
2. tick some of them
3. make changes
4. click on "Bestätigen"

### Paperless-ngx version

1.9.0

### Host OS

docker image on Synology NAS

### Installation method

Docker - official image

### Browser

Firefox and Chrome

**Comment by shamoon** [comment]
I think theres something else going on here, perhaps an actual error or something. I cannot reproduce this (and our tests cover this btw). Here's a video of the demo site I just made. Please check your logs and see if you see anything.

https://user-images.githubusercontent.com/4887959/192547019-8158ccc7-a5fd-4c6a-8544-f927c0f6e968.mov

**Comment by shamoon** [comment]
You can try to enable debug to get more output there, the other place to check is the browser console when you try to make the edit, you should see a request to `api/documents/bulk_edit/` something like:
`{"documents":[xx],"method":"modify_tags","parameters":{"add_tags":[yy],"remove_tags":[]}}`
and a response like 
`{ "result": "OK" }`
_Or not_! =)

**Comment by solluh** [comment]
After I turned on the debug mode, it worked perfectly, even after deactivating everything is fine again!  Thanks so much!

**Comment by shamoon** [comment]
Great thanks for letting us know

**Comment by lippoliv** [comment]
I'm facing the same issue after upgrading from 1.8.0 to 1.9.2: No matter which bulk action I execute, the dialog doesn't close.

Since @solluh wrote, even after toggling off debug mode it worked again, I tried a simple restart of the app (I use docker containers). It worked o.O

**Comment by steffen-lorenz** [comment]
Faced the same issue. A restart was the solution as well.
Thanks!
