### ISSUE TITLE
[BUG] False "Unsupported mime type inode/x-empty" alarm

### ISSUE THREAD

**Issue by Crocmagnon** [paperless-ngx/paperless-ngx#166]
**Describe the bug**
I'm dropping files to the consume folder via webdav from the macOS Finder. It looks like the file is initially created empty then filled with its data, under the same name.
Paperless is too eager to do its job well and immediately detects the file and tries to load it, when it's still empty.
It then complains it can't load the file with the following error message in a failed task :

```
08:08:21 [Q] ERROR Failed [2021-09-28 facture.pdf] - 2021-09-28 facture.pdf: Unsupported mime type inode/x-empty : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 74, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 209, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 70, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}")
documents.consumer.ConsumerError: 2021-09-28 facture.pdf: Unsupported mime type inode/x-empty
```

The file is quickly loaded after its data are filled so paperless still ingests the correct file a short moment after.

**To Reproduce**
Drop a file to the consume folder via webdav.

**Expected behavior**
Don't try to ingest the file when it's still empty, give it some time. Don't generate a failed task for this.

**Screenshots**
<img width="309" alt="CleanShot 2022-02-27 at 08 33 14@2x" src="https://user-images.githubusercontent.com/3630554/155873063-cc152ddd-e813-44a4-91da-315e4deab9c8.png">

**Webserver logs**
See above.

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 20.04 for the host, paperless runs in Docker
 - Browser: any
 - Version: 1.5.0 as per the footer, I'm currently running the latest paperless-ngx docker image.
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: none relevant.

**Comment by Crocmagnon** [comment]
I wouldn't silence this issue since I guess it may be legitimate.

Maybe we can implement a retry mechanism? For example, we could allow 3 tries to consume a file with a 10 seconds delay between each try (both values configurable via env).
If after the 3rd try the file still can't be imported, then notify the task failure.

**Comment by Crocmagnon** [comment]
From what I can tell, this is only related to polling. In my case, polling is disabled and if I understood correctly, paperless is using `inotify` to determine when there's a new file to process.

```
❯ docker-compose exec webserver python manage.py shell
Python 3.9.6 (default, Aug 17 2021, 02:29:16)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> settings.CONSUMER_POLLING
0
>>> settings.CONSUMER_POLLING_DELAY
5
>>> settings.CONSUMER_POLLING_RETRY_COUNT
5
```

**Comment by yschroeder** [comment]
I have seen similar when saving a file with thunderbird on Windows on a smb share. Using inotify as well.

**Comment by mimek** [comment]
I'm seeing similar issues when using share on Synology NAS via AFP from MacBook (but it behave similarly also while accessing through SMB). The clue is that in Synology case @eaDir with metadata about files are being created (with same names as origin files).

**Comment by yschroeder** [comment]
FWIW, my smb share is also on a synology nas.

**Comment by a17t** [comment]
To fix that issue I'd suggest to just silently skip unsupported mimetypes in the consumption folder, logging that skip on debug level.

**Comment by mimek** [comment]
What helped in my case was defining @synoresource as ignored pattern on consumer directory:
`PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_Store/*", "._*", ".stfolder/*", "@synoresource"]`
