### ISSUE TITLE
[BUG] Wrong version number string within docker 1.9.1

### ISSUE THREAD

**Issue by vulndev** [paperless-ngx/paperless-ngx#1664]
### Description

After a successful pull and deploy via docker with https://ghcr.io/paperless-ngx/paperless-ngx:1.9.1 the version string on the paperless-ngx Web-UI is still 1.9.0.

![Bildschirmfoto 2022-09-27 um 16 33 06](https://user-images.githubusercontent.com/48019302/192555664-f7aca659-8180-4d50-b4b8-147b54ca8769.png)

### Steps to reproduce

1. Pull the new version via docker, docker-compose or portainer via https://ghcr.io/paperless-ngx/paperless-ngx and tag 1.9.1
2. Access the Web-UI.
3. Login
4. Find the version string on the lower left side.

### Paperless-ngx version

1.9.1

### Host OS

Alpine Linux x86-64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
Yeah, looks like I forgot to update those.  I'm not positive it's worth a .2 release, but I'll let others chime in.

**Comment by SB97** [comment]
> Yeah, looks like I forgot to update those. I'm not positive it's worth a .2 release, but I'll let others chime in.
I updated yesterday between the 1.9.0 release and the 1.9.1 release and got confused after updating two times and the message not going away. I decided just to wait what happens. 

A .2 would minimize confusion and possible support.
