### ISSUE TITLE
[BUG] 1.9.1 OCR output mode "none" is not valid

### ISSUE THREAD

**Issue by v8xemvoh** [paperless-ngx/paperless-ngx#1667]
### Description

Very similar to #1643 

Updating via portainer, and with the following ENV:

PAPERLESS_OCR_CLEAN=none

the startup of the web server goes into a loop (see logs below).

### Steps to reproduce

1. Set PAPERLESS_OCR_CLEAN=none (from 1.8.0 install)
2. Update docker via portainer to latest paperless-ngx
3. Start container

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
SystemCheckError: System check identified some issues:
ERRORS:
?: OCR clean mode "none" is not valid
```

### Paperless-ngx version

1.9.1

### Host OS

Raspberry Pi 4B

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
Thanks for reporting, we'll have a release soon to fix this.
