### ISSUE TITLE
[BUG] skip_noarchive behavior contradicts the documentation since 1.9

### ISSUE THREAD

**Issue by raisinbear** [paperless-ngx/paperless-ngx#1678]
### Description

Hi,  
first let me once more thank you all for maintaining this project and advancing it at such quick pace! :)

I updated from 1.7.1 to 1.9.1 (now .2). In 1.7, PAPERLESS_OCR_MODE=skip_noarchive would do exactly as the docs say:
If there is text in the document already, it would skip OCR and not generate an archive. On the other hand, if there is no text in the document, an archive (by definition with no text) and a new version with text overlay would be created.
In 1.9.2, however, the same setting leads to no version with text overlay. I understand this was introduced in [#1442](https://github.com/paperless-ngx/paperless-ngx/pull/1442), but I think the documentation is pretty clear on what should be happening, am I wrong? Right now it states "In addition to skip, paperless won’t create an archived version of your documents _when it finds any text in them_." [Emphasis added]

Of course I'm completely fine with that decision, even though I was relying on this setting and found it very useful.
But if it should be kept as is, I suppose the Docs should be updated to reflect that there will be no archive even for text-free documents.

Also I would like to know if there is now any setting that would result in what happened before:

Document has text -> no archived version, no OCR
Document has no text -> archived version, version with text overlay, OCR

### Steps to reproduce

Set PAPERLESS_OCR_MODE=skip_noarchive, import a document with no text.

### Paperless-ngx version

1.9.2

### Host OS

Raspbian Buster

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
I can see how this is confusing.  I think the docs need to be updated to note that `skip_noarchive` will never create an archive file.  To me, if it says `noarchive`, there shouldn't be an archive created ever.

**Comment by raisinbear** [comment]
I totally understand the point of not expecting an archive when the flag literally says 'no archive'. But as mentioned, I found the functionality itself quite useful.
It's really only nitpicking, but I don't like the idea too much that the backing folders of my library will now have somewhat inconsistent contents. Either it's `skip` from now on, meaning (as I understand the docs) that every new file in `/originals` will have a backup in `/archive` or file parity stays as is with `skip_noarchive` but new documents will have no text overlay.
Luckily it seems to be enough for now to invalidate the if check in line 280 of parsers.py, which I could figure out despite my limited experience 😅.
If at some point, you think it's a good idea to reintroduce the behavior under a more literal flag, all the better. But as stated, this is a highly specific objection and mostly owed to me being neurotic about the file level consistency. 😉

Thanks for the hard work and the quick reply! Please feel free to close this. (presumably with the docs update PR?)
