### ISSUE TITLE
[BUG] Incorrectly listing new documents as duplicates

### ISSUE THREAD

**Issue by janbro1** [paperless-ngx/paperless-ngx#1688]
### Description

I use dockerized version 1.9.2  (image: ghcr.io/paperless-ngx/paperless-ngx:latest)
and use usually use a consume folder for feeding paperless. I just recently updated to that version.
I have now several documents that are kept in that folder and are shown in the log as: "Not consuming" as "it is a duplicate". 

However that is not correct, there are no duplicates to be found. From the task view I have only the option to abort, but no option to overwrite and ignore. I also seem to have no option to delete the "false original".

### Steps to reproduce

add document into consume folder.
Receive error

### Webserver logs

```bash
[2022-09-30 10:29:23,621] [ERROR] [paperless.consumer] Not consuming 1802140_Stromabrechnung_2020.pdf: It is a duplicate.
```

### Paperless-ngx version

1.9.2

### Host OS

Synology Docker

### Installation method

Other (please describe above)

**Comment by shamoon** [comment]
Paperless checks for duplicates by comparing and md5 hash so I think its unlikely that its wrong, tbh see https://github.com/paperless-ngx/paperless-ngx/blob/5639659b6384fc675569fbec044bc2757a6696f5/src/documents/consumer.py#L111 and its not something thats been reported by others.

Have you looked through your existing docs to make absolutely certain that its incorrect?

**Comment by stumpylog** [comment]
This does present a nice enhancement. It should be very easy to get the title of the already stored duplicate. That's be a good qol

**Comment by shamoon** [comment]
Yea had the same thought!

**Comment by janbro1** [comment]
Yes, I can confirm that those documents did not exist. Simply as I had just recieved them and stored them in the consumption folder. Nevertheless did I try to find them with some keywords, but no luck, otherwise I wouldn't have raised the ticket.
I restarted the container now, didn't change the situation for those documents, but newer ones are now processed again.
To get those in question into paperless I re-printed them as PDFs and afterwards I was able to feed them.

**Comment by stumpylog** [comment]
With #1696 merged, you'll get a title and the id of the duplicate document, which simplifies confirming where a duplicate was found.

**Comment by dtmichel** [comment]
I do have the same problem after setting up Paperless-ngx (v1.9.2) for the first time and importing hundreds of files from the past 10 years. I can't find any duplicates on my disk and can't see any hint what the original/first file might be.

**Comment by makanimike** [comment]
I too have this issue. It is without doubt a different document.
Though, tbf, there is only a tiny difference. It is a product certificate (for extended warranty) for a photography lens. 
The certificate is the same. The only difference to the other document that was consumed first is that two fields in the form are different, the serial number and the product model.

**Comment by lgwapnitsky** [comment]
I'm having the same issue with docs that are coming in via e-mail. They're named the same, but have different dates and the MD5 hashes are different.
