### ISSUE TITLE
[Other] CI Question: should we include other `tesseract-ocr-*` for enabled langs?

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#171]
See here in the dockerfile:

https://github.com/paperless-ngx/paperless-ngx/blob/49e6e54e0b449da4a33808cc2c127decd14237ba/Dockerfile#L43-L48

With #83 and #84 we now have many languages enabled in the frontend that don't have their respective `tesseract-ocr-` packages installed (which [does exist](https://packages.debian.org/search?keywords=tesseract%2Docr%2Dda)). Does this matter, should they be added?

**Comment by schnuffle** [comment]
I would just install tesserart-ocr-all.

Haven't checked the impact on size but without having all available lang included, people choosing one of those will run into problems.
And i had to realize that many people are using compose setups without really having basic knowledge of it. 
So we should make it as easy as possible for them.

Regards

Schnuffle

**Comment by qcasey** [comment]
That's an interesting idea, I agree we should make things as straightforward as possible.

> Haven't checked the impact on size

The `tesserart-ocr-all` bundle is 708 MB in size, while the 6 individual ones we have now is 30.1 MB. That's a pretty big increase.

**Comment by tribut** [comment]
Didn't we have a proposal to remove the _LANGUAGES setting in favor of automatically installing whatever is needed from _LANGUAGE? That would be just as straightforward for the user without increasing image size.

**Comment by mweimerskirch** [comment]
There is an env variable, PAPERLESS_OCR_LANGUAGES where you can specify additional languages to install.
It's used here: https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/docker-entrypoint.sh#L79

I made handling this a bit simpler in this PR: https://github.com/paperless-ngx/paperless-ngx/pull/20

Theoretically, the base image could even use less languages or no languages at all and they would install automatically on the first run.

**Comment by qcasey** [comment]
Thank you, I didn't see that option/pr.
