### ISSUE TITLE
[BUG] permission issues

### ISSUE THREAD

**Issue by Nachtpfoetchen** [paperless-ngx/paperless-ngx#1730]
### Description

Install on my fedora machine failed. It is a new fedora installation.

### Steps to reproduce

Try to install it on my fresh fedora install

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
find: ‘/usr/src/paperless/export’: Permission denied
chown: changing ownership of '/usr/src/paperless/export': Permission denied
find: ‘/usr/src/paperless/consume’: Permission denied
chown: changing ownership of '/usr/src/paperless/consume': Permission denied
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
SystemCheckError: System check identified some issues:

ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
drwxr-xr-x root root /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
ERROR: 1
```

### Paperless-ngx version

1.9.2

### Host OS

Fedora 36

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Are you attempting to run with `user:` set in the `docker-compose.yml`?

**Comment by Nachtpfoetchen** [comment]
no i don't.
here is my docker compose file:
`➤ cat docker-compose.yml 
# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/andromeda/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
  redisdata:
`

**Comment by Nachtpfoetchen** [comment]
i checked the ownership. it looks right to me:
```
ls -l /usr/src/
total 0
drwxr-xr-x. 1 root root 42 12. Sep 18:25 annobin
drwxr-xr-x. 1 root root  0  9. Aug 15:57 debug
drwxr-xr-x. 1 root root  0  9. Aug 15:57 kernels
drwxr-xr-x. 1 root root  0  3. Okt 17:47 paperless

```
filesystem is btrfs:
```
df -Th | grep "^/dev"
/dev/dm-0      btrfs     488G   53G  435G  11% /
/dev/dm-0      btrfs     488G   53G  435G  11% /home
```
All volume mounts are the default of the install script and on my local harddrive in my system.

**Comment by stumpylog** [comment]
Are you able to manually change the ownership of `/home/andromeda/paperless-ngx/consume` to be 1000:1000?

**Comment by Nachtpfoetchen** [comment]
i changed ownership of the dirs:
```
➤ ls -l ./paperless-ngx/
total 8
drwxr-xr-x. 1 andromeda andromeda    0  3. Okt 17:19 consume/
-rw-r--r--. 1 andromeda andromeda  147  3. Okt 17:46 docker-compose.env
-rw-r--r--. 1 andromeda andromeda 2247  3. Okt 17:46 docker-compose.yml
drwxr-xr-x. 1 andromeda andromeda    0  3. Okt 17:19 export/
drwxr-xr-x. 1 andromeda andromeda    0  3. Okt 17:19 media/
```
and made sure that i am 1000
```
$ cat /etc/passwd |grep andromeda
andromeda:x:1000:1000:andromeda:/home/andromeda:/usr/bin/fish

```
still get permission errors when i try `docker-compose up`

```
webserver_1  | SystemCheckError: System check identified some issues:
webserver_1  | 
webserver_1  | ERRORS:
webserver_1  | ?: PAPERLESS_CONSUMPTION_DIR is not writeable
webserver_1  | 	HINT: Set the permissions of 
webserver_1  | drwxr-xr-x paperless paperless /usr/src/paperless/consume
webserver_1  |  to be writeable by the user running the Paperless services

```

**Comment by stumpylog** [comment]
And I assume if you create a file in `consume` and `export`, it is created no problem?  

The difference here seems to be volumes vs bind mounts, but to the image, all these folders are treated the same, and the permissions changing all runs as root.

**Comment by Nachtpfoetchen** [comment]
yes i can create a file with no problem in these dirs:
```
andromeda@unicorn-desktop:~/paperless-ngx
➤ touch ./consume/test
andromeda@unicorn-desktop:~/paperless-ngx
➤ touch ./export/test
andromeda@unicorn-desktop:~/paperless-ngx
➤ ls -l ./consume/
total 0
-rw-r--r--. 1 andromeda andromeda 0  4. Okt 01:04 test
```

**Comment by stumpylog** [comment]
The best I can tell, something is interfering with the image.  Docker has things like userspace re-mapping, etc, that could all do it.  All I can really know here is that the OS reports a PermissionError when trying to write to `consume` and likely would for `export` as well.

You could attempt to run with `privledged: true` which may work around whatever Docker is doing.

**Comment by Nachtpfoetchen** [comment]
I made some things:
1) making sure that my docker is setup like described here: https://developer.fedoraproject.org/tools/docker/docker-installation.html (before that i was using docker from the official fedora repos)
2) running the webserver privileged once.

the container came up successfully. after that i removed the privileged line.
the container also comes up successfully.
I am not understanding what was going on here. closing this issue, since it works for now fine on my system.

**Comment by cryptoluks** [comment]
Fedora uses SELinux by default. You need to append either `:Z` for (with other containers) non-shared volumes mounts or `:z` for shared ones. You probably want to use the latter one with `consume` and `export`.

And oh, you do not wan't to use privileged containers for paperless, trust me!

Strange permission issues almost always have something to do with SELinux or AppArmor. You can temporarily disable SELinux with `setenforce 0` to see if it's the case. Reenable again with `setenforce 1` or reboot the machine.

**Comment by lukmuk** [comment]
I ran into the same issues as @Nachtpfoetchen on my Fedora installation. I was able to resolve the issue thanks to the information by @cryptoluks:
> Fedora uses SELinux by default. You need to append either `:Z` for (with other containers) non-shared mounts or `:z` for shared ones. You probably want to use the latter one with `consume` and `export`. And if you use a bind mount for `media` too (and not a docker volume), you also have to use `:z` for `media` and not `:Z`, as exporting documents to the export folder will keep the source-directories SELinux labels. Then you will have issues permission when accessing files inside `export` through another container.
> 
> And oh, you do not wan't to use privileged containers for paperless, trust me!
> 
> Strange permission issues almost always have something to do with SELinux or AppArmor. You can temporarily disable SELinux with `setenforce 0` to see if it's the case. Reenable again with `setenforce 1` or reboot the machine.
> 
> And SELinux errors are logged to the journal, so watch out in either Fedora cockpit or use `journalctl -b -g selinux`.
> 
> See here: https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

I changed the volume entries in the ```docker-compose.yml``` file to

>     volumes:
>      - data:/usr/src/paperless/data:z
>      - media:/usr/src/paperless/media:z
>      - ./export:/usr/src/paperless/export:z
>      - ./consume:/usr/src/paperless/consume:z

during installation procedure describe [here](https://docs.paperless-ngx.com/setup/#docker_hub).

I tried ```:Z``` on media, but then the document_importer did not work. Using small ```:z``` on all volumes seems to lead to a fully functional installation. 
Maybe someone with SELinux experience could provide a note in the installation instructions (to https://docs.paperless-ngx.com/setup/#docker_hub) similar to the previous answer of @cryptoluks?

**Comment by cryptoluks** [comment]
Issues can occur if a document is created in a folder with private (Z) labels and afterwards copied to a folder with shared (z) labels. The copy implementation of Paperless does preserve those flags when copying files from a to b. So even in a directory with the z flag, the files do not automatically inherit the context of the parent folder. If you recreate the container, the shared flags will probably be applied again.

You can list the SELinux labels with `ls -laZ` to see what is happening.

**Comment by Alexander-Wilms** [comment]
I'm having the same issue:

<details>
<summary>output of docker-compose up</summary>

```
paperless-webserver-1  | Creating directory /tmp/paperless
paperless-webserver-1  | Adjusting permissions of paperless files. This may take a while.
paperless-webserver-1  | chown: changing ownership of '/usr/src/paperless/export': Operation not permitted
paperless-webserver-1  | chown: changing ownership of '/usr/src/paperless/consume': Operation not permitted
paperless-webserver-1  | Waiting for PostgreSQL to start...
paperless-webserver-1  | Waiting for Redis...
paperless-webserver-1  | Connected to Redis broker.
paperless-webserver-1  | Apply database migrations...
paperless-webserver-1  | Operations to perform:
paperless-webserver-1  |   Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions
paperless-webserver-1  | Running migrations:
paperless-webserver-1  |   No migrations to apply.
paperless-webserver-1  | Running Django checks
paperless-webserver-1  | SystemCheckError: System check identified some issues:
paperless-webserver-1  | 
paperless-webserver-1  | ERRORS:
paperless-webserver-1  | ?: PAPERLESS_CONSUMPTION_DIR is not writeable
paperless-webserver-1  |        HINT: Set the permissions of 
paperless-webserver-1  | drwxr-xr-x root root /usr/src/paperless/consume
paperless-webserver-1  |  to be writeable by the user running the Paperless services
paperless-webserver-1  | 
paperless-webserver-1  | System check identified 1 issue (0 silenced).
paperless-webserver-1 exited with code 1
```
</details>
<details>
<summary>docker-compose.yml</summary>

```
# docker-compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# All compose files of paperless configure paperless in the following way:
#
# - Paperless is (re)started on system boot, if it was running before shutdown.
# - Docker volumes for storing data are managed by Docker.
# - Folders for importing and exporting files are created in the same directory
#   as this file and mounted to the correct folders inside the container.
# - Paperless listens on port 8000.
#
# In addition to that, this docker-compose file adds the following optional
# configurations:
#
# - Instead of SQLite (default), PostgreSQL is used as the database server.
#
# To install and update paperless with this file, do the following:
#
# - Copy this file as 'docker-compose.yml' and the files 'docker-compose.env'
#   and '.env' into a folder.
# - Run 'docker-compose pull'.
# - Run 'docker-compose run --rm webserver createsuperuser' to create a user.
# - Run 'docker-compose up -d'.
#
# For more extensive installation and update instructions, refer to the
# documentation.

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    user: "1000"
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
      - ./import:/usr/src/paperless/import
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
  redisdata:

```
</details>

<details>
<summary>system information</summary>

Operating System: openSUSE Tumbleweed 20230205
KDE Plasma Version: 5.27.80
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.8-1-default (64-bit)
Graphics Platform: X11
</details>
