### ISSUE TITLE
[BUG] Can't connect to Mariadb

### ISSUE THREAD

**Issue by gmarlow** [paperless-ngx/paperless-ngx#1732]
### Description

I'm trying to configure Paperless to work with Mariadb.  However, the connection is failing and I'm getting errors from both Mariadb and Paperless.

I created an empty paperless database (via CloudBeaver).
I created an account (paperless@%) and verified it can login (via CloudBeaver).

When starting up the Paperless-ngx docker container I get the following errors:

Error from Paperless log:
      09:49:36 [Q] ERROR received invalid response to SSL negotiation: o

Error from MariaDB log:
      2022-10-03  9:49:36 2202 [Warning] Aborted connection 2202 to db: 'unconnected' user: 'unauthenticated' host: '172.19.0.1' (This connection closed normally without authentication)

My docker-compose DB related entries:
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: 192.168.102.6
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: "**redacted**"

I've tried the password with and without quotes.

### Steps to reproduce

Start paperless-ngx docker container

### Paperless-ngx version

1.9.2

### Host OS

Linux / Docker

### Installation method

Docker - linuxserver.io image

### Browser

Chrome

**Comment by stumpylog** [comment]
You say you're using the LSIO image, but it doesn't have a 1.9.2, as they have deprecated it.  The 1.9 series was the first to support MariaDB at all.

**Comment by gmarlow** [comment]
Looks like switching to ghcr.io/paperless-ngx/paperless-ngx:latest fixed my issue.  Thanks!
