### ISSUE TITLE
[BUG] some PDFs raise a NotImplementedError

### ISSUE THREAD

**Issue by kurti500** [paperless-ngx/paperless-ngx#1743]
### Description

Since 1.9.2 (I skipped 1.9 and 1.9.1) account statements of german dkb bank (also ones previously working fine) get stuck in processing.
There are some statements about barcode separation, maybe something broken there, as there is no barcode visible in the PDF.
Unfortunately also "reprinting" the PDF with a tool usually fixing issues for files which cannot be processed in papaerless is not working here.
Unfortunately I cannot share samples as its bank data....

Have barcode separation enabled:
PAPERLESS_CONSUMER_ENABLE_BARCODES=true
PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT

### Steps to reproduce

1. get the document consumed
2. process gets stuck in frontend
![image](https://user-images.githubusercontent.com/82444848/193867252-7cbf145f-ed99-4661-85de-4f1685c2a725.png)
3. shows up as queued for quite some time
![image](https://user-images.githubusercontent.com/82444848/193867603-6c67a193-04b5-40cc-bd0a-2581dbc98e21.png)
4. ends up as failed task

### Webserver logs

```bash
Kontoauszug_1023735317_Nr_2022_003_per_2022_08_01.pdf
HISTORY

Id:
79423d05e71d4a10b2457bf23f91cd60
Name:
Kontoauszug_1023735317_Nr_2022_003_per_2022_08_01.pdf
Func:
documents.tasks.consume_file
Hook:
-
Args:
/tmp/paperless/paperless-upload-0n2e8jty
Kwargs:
{'override_filename': 'Kontoauszug_1023735317_Nr_2022_003_per_2022_08_01.pdf', 'override_title': None, 'override_correspondent_id': None, 'override_document_type_id': None, 'override_tag_ids': None, 'task_id': 'dc8d5b5b-5eec-4395-b29a-22f4ee8df01a', 'override_created': None}
Result:
Not sure how to handle PDF image of this type : Traceback (most recent call last):
File "/usr/src/paperless/src/src/django-q/django_q/cluster.py", line 454, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 99, in consume_file
pdf_filepath, separators = barcodes.scan_file_for_separating_barcodes(path)
File "/usr/src/paperless/src/documents/barcodes.py", line 126, in scan_file_for_separating_barcodes
pillow_img = pdfimage.as_pil_image()
File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 742, in as_pil_image
im = self._extract_transcoded()
File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 606, in _extract_transcoded
if self.mode in {'DeviceN', 'Separation'}:
File "/usr/local/lib/python3.9/site-packages/pikepdf/models/image.py", line 301, in mode
raise NotImplementedError(
NotImplementedError: Not sure how to handle PDF image of this type
Group:
-
Started:
Oct. 4, 2022, 5:52 p.m.
Stopped:
Oct. 4, 2022, 5:56 p.m.
```

### Paperless-ngx version

1.9.2

### Host OS

Synology with Docker

### Installation method

Docker - ghcr.io image
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest

### Browser

Chrome

### Configuration changes

barcodes for page separation was enabled, problem is resolved after commenting it out in compose file:
#PAPERLESS_CONSUMER_ENABLE_BARCODES=true
#PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT

**Comment by shamoon** [comment]
Sometimes there are significant differences between the lsio image and ours. Unfortunately they are no longer supporting their image so you will need to switch to ours, helpful guide here: https://paperless-ngx.readthedocs.io/en/latest/setup.html#migrating-from-linuxserver-io-docker-image

If you can confirm this issue with our image then please let us know, of course.

**Comment by kurti500** [comment]
sorry, provided the wrong docker image reference. Issue is updated, I am using the ghcr.io one
webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest

Can the bug be reopened, pls?

**Comment by stumpylog** [comment]
Probably related: pikepdf/pikepdf/issues/237

It seems some PDF images are not convertible to PIL images for pyzbar.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/b13ced93ed0f9de2673b05ecefbfae11527dcff7
