### ISSUE TITLE
[BUG] paperless-webserver has to be restarted for consume to complete

### ISSUE THREAD

**Issue by tomdh76** [paperless-ngx/paperless-ngx#1751]
### Description

Scans are added to task queue but remain in the 'start task'
In the webserver log I see:

Oct 05 05:31:45 paperless-ngx gunicorn[131]: [2022-10-05 07:31:45 +0200] [131] [WARNING] Worker with pid 246 was terminated>
Oct 05 05:31:46 paperless-ngx gunicorn[438]: terminate called after throwing an instance of 'std::runtime_error'
what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance

I have to completely restart the LXC container for consuming to complete

### Steps to reproduce

Consuming works fine after restarting. But after being idle for a day new scans are not fully consumed. They are picked up by polling but do not complete

### Webserver logs

```bash
Oct 05 05:31:45 paperless-ngx gunicorn[131]: [2022-10-05 07:31:45 +0200] [131] [WARNING] Worker with pid 246 was terminated>
Oct 05 05:31:46 paperless-ngx gunicorn[438]: terminate called after throwing an instance of 'std::runtime_error'
what():  pybind11_object_dealloc(): Tried to deallocate unregistered instance
```

### Paperless-ngx version

1.9.2

### Host OS

LXC debian container on proxmox

### Installation method

Bare metal

**Comment by stumpylog** [comment]
gunicorn is a seperate process from the consumer and can't affect it.  Please try the trouble shooting steps for the consumer here: https://paperless-ngx.readthedocs.io/en/latest/troubleshooting.html

**Comment by tomdh76** [comment]
It turned out my memory stick was defect.. Now working correctedly..
