### ISSUE TITLE
[BUG] Dropdown for saved views without action

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#1791]
### Description

I stumbled upon the following behaviour, not sure whats supposed to happen in the attached screenshot.

![2022-10-13_20-10](https://user-images.githubusercontent.com/88422038/195673964-cc8ced89-a1b4-49c5-8008-2eb238db340d.png)

When selecting a saved view from the dropdown menu, i would assume that this view should be loaded but instead nothing happens.

### Steps to reproduce

1. go to "documents"
2. select the "view" button
3. choose one item
4. nothing happens

### Paperless-ngx version

1.9.2

### Host OS

Synology DSM 6.X

### Installation method

Docker - official image

### Browser

Chrome Version 106.0.5249.103

### Configuration changes

nothing of relevance for this issue

**Comment by shamoon** [comment]
Ah thanks, I will look into this when I have a moment

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/15bcb2491cdcf9c6d81f3630fb6819a6454f85b5
