### ISSUE TITLE
[BUG] Warning executing compile-frontend.sh

### ISSUE THREAD

**Issue by azapater** [paperless-ngx/paperless-ngx#181]
**Describe the bug**
To generate a production version of src-ui, while executing compile-frontend.sh it shows a warning related with the --prod deprecated flag. 

It basically needs to be replaced with "--configuration production"

**Comment by qcasey** [comment]
Thanks, `compile-frontend.sh` was removed in #161 but this will still apply to that line. I'll create a quick PR

**Comment by qcasey** [comment]
Fixed in #185
