### ISSUE TITLE
[BUG] document_retagger - how do I know it’s running, and why didn’t it applying my new Document Type?

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1813]
### Description

Hi, after spendings time importing lots of documents, as my confidence grew, I decided to do a bit of a tidy up and retrospectively apply some Document Type values.

Looking at all the energy company statements I’d imported, I thought I’d start there, by creating a rule, (see attached) , which leverage words I could see on a sample statement and it was in its OCR output too.

![E3A960EB-DB41-4F4C-B38A-D33A91560701](https://user-images.githubusercontent.com/4349292/196060270-cbaa892f-19bb-4d95-bfdc-e61530c24368.jpeg)

With that new rule in place, I then accessed Docker and ran the following retagger command, which just paused for a short while and then return me to the command prompt, no message nothing. Checking the log via the main ui that had no record of anything being kicked off either.  ..
````
docker-compose exec paperlessngx python3 manage.py document_retagger -t
````

### Steps to reproduce

Please see the screenshot above for what you would need to reproduce

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - linuxserver.io image

### Browser

Safari

**Comment by shamoon** [comment]
I dont think you want the quotes.
Also, if documents already have a doc type you need `-f`, see https://paperless-ngx.readthedocs.io/en/latest/administration.html#document-retagger

**Comment by stumpylog** [comment]
Also, if you enter a prompt in the container, you should be able to see the output of the command.

`docker exec -it paperlessngx /bin/bash` then run the command.  To exit, just `exit`.

**Comment by nodecentral** [comment]
Many thanks @stumpylog @shamoon , both for highlighting the quotes, as that was the issue and also the Docker command line so I can see the progress..

Quick follow on question - After the first run of this, which seems to have been applied correctly, should I update it for `string` to `Auto` , so it’s applied automatically to anything new going forward?

![93AF7596-1D48-4B7E-AAB5-D8C13630ADD6](https://user-images.githubusercontent.com/4349292/196530776-ada747fe-fc7f-4ecb-87cc-56bad65717b8.jpeg)

**Comment by shamoon** [comment]
I suspect both will work but feel free to try em out

**Comment by nodecentral** [comment]
Ok, just tired to rename that existing `statement` document type to `Financials which is set to Auto, and running the document retagger with the `-f` added, it showed the following in the log (see extract below)
````
[2022-10-18 21:11:12,042] [INFO] [paperless.handlers] Assigning document type None to 1997-06-06 C.V (Full)
[2022-10-18 21:11:12,070] [INFO] [paperless.handlers] Assigning document type None to 1997-06-06 BBC
[2022-10-18 21:11:12,086] [INFO] [paperless.handlers] Assigning document type None to 1997-06-06 BBC1
[2022-10-18 21:11:12,097] [INFO] [paperless.handlers] Assigning document type None to 1997-04-24 X-Files Wallpaper
[2022-10-18 21:11:12,108] [INFO] [paperless.handlers] Assigning document type None to 1997-04-24 s100X-Files Wallpaper
[2022-10-18 21:11:12,119] [INFO] [paperless.handlers] Assigning document type None to 1997-04-24 s800X-Files Wallpaper
[2022-10-18 21:11:12,131] [INFO] [paperless.handlers] Assigning document type None to 1997-04-24 defaultX-Files Wallpaper
[2022-10-18 21:11:12,141] [INFO] [paperless.handlers] Assigning document type None to 1997-04-04 comprice
```a

Strange thing is , while it suggests it’s tagged everything now, I can search or see them via the UI, only the Financial one is visible ?

**Comment by stumpylog** [comment]
I don't really understand the question, but remember for `auto` tags, the classifier needs to be up to date.  You can manually do so with `document_create_classifier`

**Comment by nodecentral** [comment]
Hi @stumpylog , apologies for not being clearer, my last question was about how the retagger response suggested it had updated every blank document type with a new document type? (Yet I can’t see that association via the UI?)

**Comment by stumpylog** [comment]
A type of `None` means it cleared the document type from those documents. So no match was found, depending on the matching setup of the possible document types.

**Comment by nodecentral** [comment]
Right I’m with you now, many thanks @stumpylog..

What confused me was that all those documents already didn’t have a document type assigned, so I couldn't understand why they were touched. I’m guessing now, that my earlier move to setting `Auto` on my Document Type, and then forcing an update, had something to do with that..  I’ll keep testing..
