### ISSUE TITLE
[BUG] Endless loading state after changing filter

### ISSUE THREAD

**Issue by sven-strothoff** [paperless-ngx/paperless-ngx#1819]
### Description

Changing the filter in the documents list shows a loading spinner that never finishes.
If the document list is multiple pages long and the pagination controls are used to select page N (N > 1) and the filter rules are adjusted, so that the results are less than N pages long, paperless tries to load the (non-existent) N-th page of the results and never finishes.

Changing the filter to get more results or using the pagination controls to select a smaller page number fixes this state.

I had first mistaken the issue as a failed backend call that got cancelled somehow and never responded, but it seems to be a bug in the frontend.

### Proposed solution
When the filter parameters are changed reset the current page to page 1.

### Possible fix
I had a look at the code and think that setting `this.activeListViewState.currentPage` to 0 (or is it 1?) here
https://github.com/paperless-ngx/paperless-ngx/blob/main/src-ui/src/app/services/document-list-view.service.ts#L272
should fix the problem, however I currently have no development setup of paperless to try it out.

Please let me know if I can provide any additional details.

### Steps to reproduce

1. Go to the Documents page.
2. Use the pagination controls to select a page > 1.
3. Adjust filter rules, for example filter by a tag. Filter results must be less pages long than page selected step 2.
4. Loading spinner is displayed indefinitely.

### Paperless-ngx version

1.9.2

### Host OS

Raspberry Pi 4, Raspbian GNU/Linux 11, arm7vl

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Thanks for reporting, this is a regression. I'll sort it out for our next release

**Comment by shamoon** [comment]
Actually, Im not able to reproduce this in 1.9.2 (or in `dev`). Im wondering if theres a more specific set of circumstances needed to reproduce it. And if you are able to, is anything shown in the browser logs?

https://user-images.githubusercontent.com/4887959/196466299-87214a07-8dc8-4b2c-8862-1462099ccf01.mov

**Comment by shamoon** [comment]
Also, https://github.com/paperless-ngx/paperless-ngx/blob/87472b31d27be1fff304377ec3260268f3ecc44d/src-ui/src/app/services/document-list-view.service.ts#L244 _should_ handle this

**Comment by sven-strothoff** [comment]
Thanks for the quick replies!
I can reliably reproduce this issue on my installation.

As far as I can see there is nothing relevant in the browser console.
However, the request for the (now non-existent) page never finishes.
As there is no 404 response, the line you mentioned is never triggered.

![image](https://user-images.githubusercontent.com/3276142/196471210-61a81235-5551-4fea-9ae6-f06bfc4f1b47.png)

I can try to check the backend logs for anything suspicious.

**Comment by sven-strothoff** [comment]
The content of `paperless.log` seem to contain more details (log level debug?), however, the last log entries are from the last document import.
Is there a way to log backend requests? I did a quick search of the documentation, but did not see anything so far.

**Comment by shamoon** [comment]
Can you tell me the api URL from that screenshot that never loads?

**Comment by sven-strothoff** [comment]
To rule out some browser-related problems like CORS I tried to make some requests with CURL.
If I request a page that is too high the request just _hangs_ forever.
It is not related to filtering at all. That is just a way to get the frontend to request a page that does not exist.

```
curl -v 'http://XXXXXXXX/api/documents/?page=10&page_size=50&ordering=created' \                                    
  -H 'Accept: application/json; version=2' \
  -H 'Accept-Language: de,en-GB;q=0.9,en-US;q=0.8,en;q=0.7' \ 
  -H 'Cache-Control: no-cache' \                                                                                                
  -H 'Connection: keep-alive' \
  -H 'Cookie: csrftoken=XXXXXXXX; sessionid=XXXXXXXX' \             
  -H 'Pragma: no-cache' \                                       
  -H 'Referer: http://XXXXXXXX/documents?sort=created&page=5' \                                                          
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari
/537.36' \                                                                                                                      
  -H 'X-CSRFToken: XXXXXXXX' \
  --compressed
```

(requesting page 10, 5 pages exist)


> Can you tell me the full api URL from that screenshot that never loads?

The unmodified API URL from the browser was
`http://XXXXXXXX/api/documents/?page=5&page_size=50&ordering=created&tags__id__all=5`

**Comment by shamoon** [comment]
Hmm, yea something is up. That query should return a 404, and does for me. Is it possible its something to do with a reverse proxy etc?

```
HTTP/1.1 404 Not Found
Content-Type: application/json
Vary: Accept, Accept-Language, Origin, Cookie
Allow: GET, HEAD, OPTIONS
X-Frame-Options: ANY
X-Api-Version: 2
X-Version: 1.9.2
Content-Length: 26
Content-Language: en-us
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
```
<img width="491" alt="Screen Shot 2022-10-18 at 8 53 15 AM" src="https://user-images.githubusercontent.com/4887959/196481127-58a832ab-8b50-4b2f-b5f2-aa9ebcfd86b6.png">

**Comment by sven-strothoff** [comment]
Just for completeness, I installed paperless using the install script in the Getting Started section of the README. I installed it on the 13th of October, so it should have been the version currently in main (87472b3).

The docker-compose file I ended up with is [docker-compose.sqlite.yml](https://github.com/paperless-ngx/paperless-ngx/blob/87472b31d27be1fff304377ec3260268f3ecc44d/docker/compose/docker-compose.sqlite.yml).
The only changes I made are the location of the `media`, `data` and `consume` folders:

```diff
diff --git a/docker-compose.sqlite.yml b/docker-compose.yml
index 5f5b906..5c90f0b 100644
--- a/docker-compose.sqlite.yml
+++ b/docker-compose.yml
@@ -44,16 +44,14 @@ services:
       timeout: 10s
       retries: 5
     volumes:
-      - data:/usr/src/paperless/data
-      - media:/usr/src/paperless/media
+      - /home/sven/paperless-ngx/data:/usr/src/paperless/data
+      - /home/sven/paperless-ngx/media:/usr/src/paperless/media
       - ./export:/usr/src/paperless/export
-      - ./consume:/usr/src/paperless/consume
+      - /home/sven/paperless-ngx/consume:/usr/src/paperless/consume
     env_file: docker-compose.env
     environment:
       PAPERLESS_REDIS: redis://broker:6379
 
 
 volumes:
-  data:
-  media:
   redisdata:
   ```

Contents of my `docker-compose.env`:

```
USERMAP_UID=1001
USERMAP_GID=1001
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY=XXXXXXXX
```

As far as I can tell there should be no surprises (like a reverse proxy you asked about) here. 🤷

**Comment by sven-strothoff** [comment]
Update: I did some more testing.

I did a clean install on macOS. Works as intended, requesting a non-existent page returns a 404.

Then I did another clean install on my Raspberry Pi and I get the same weird behaviour as before. Just requesting page 2 on a clean install with no documents results in the never-ending request (gets a timeout after about 22 minutes).

So, as far as I could narrow it down, it is somehow related to the environment paperless is running in. As to _why_ this is happening, I am at a loss…
I would never have guessed that this has anything to do with the OS/Hardware. Really strange…

I'm still curious, but I have more or less run out of ideas what I can do to track this down.
I don't know Django, but is there a way to enable really verbose logging on the server?
If you have any other ideas what I could try, please let me know.

**Comment by shamoon** [comment]
Oh yea, that is weird. 

You can enable the `DEBUG` setting, yea any more info would be great, I dont have an RPi I can easily test this with unless theres some other way to reproduce it (on other platforms). Also that API endpoint uses the Django Rest Framework mostly, so suppose could be a bug there.

Ideas to deal with this, assuming it is reproducible, would be to set a timeout for these, could be on the frontend side if needed though would necessitate keeping track of nRetries, etc. More ideal would be to track it down in the backend, of course.

**Comment by schnuffle** [comment]
I don't know if it's really related, but I already got many problem due to switching from docker volumes to folders. Often the owner/group creates problems that have sometimes weird effects.

Might be interesting to see if it works, when you use docker volumes.

**Comment by FunctionDJ** [comment]
Could this issue be re-opened and the frontend label removed?

**Comment by schnuffle** [comment]
Did you already tried to use docker volumes instead of paths?

I can reopen but as I'm not really involved for the moment, I'll leave that to others
