### ISSUE TITLE
[BUG] processing content in a hidden folder e.g .@__thumb/

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1828]
### Description

Not sure if this is actually a bug, but it was something I found strange initially as I couldn’t work out where all these low resolution versions of scanned images I’d just moved into the `Consume` folder had come from. After a bit of digging it seems they were all in an unknown hidden folder called `.@__thumb/`

Is there the ability to ignore or maybe prompt/highlight the user of hidden folders/files, should anything like that be moved into the `Consume` directory?

````
/share/TS-243Be/Full Backup 2/latest/Documents/My Employment/DT] # ls -la
total 47216
drwxrwxrwx 3 admin administrators    4096 2022-10-13 23:50 ./
drwxrwxrwx 3 admin administrators    4096 2022-02-03 10:03 ../
-rw-rw-rw- 1 admin administrators 2361927 2022-02-03 10:03 IMG_6637.jpg
-rw-rw-rw- 1 admin administrators 2153753 2022-02-03 10:03 IMG_6638.jpg
-rw-rw-rw- 1 admin administrators 1616196 2022-02-03 10:03 IMG_6639.jpg
-rw-rw-rw- 1 admin administrators 1617852 2022-02-03 10:03 IMG_6640.jpg
-rw-rw-rw- 1 admin administrators 2408256 2022-02-03 10:03 IMG_6641.JPG
-rw-rw-rw- 1 admin administrators 1415007 2022-02-03 10:03 IMG_6642.JPG
-rw-rw-rw- 1 admin administrators 1849161 2022-02-03 10:03 IMG_6643.jpg
-rw-rw-rw- 1 admin administrators 2333030 2022-02-03 10:40 IMG_6676.jpg
-rw-rw-rw- 1 admin administrators 2521306 2022-02-03 10:40 IMG_6677.jpg
-rw-rw-rw- 1 admin administrators 1838136 2022-02-03 10:40 IMG_6678.jpg
drwxrwxrwx 2 admin administrators    4096 2022-10-13 23:50 .@__thumb/
````
And then within the `.@__thumb` Directory, there was all of these..
````
[/share/TS-243Be/Full Backup 2/latest/Documents/My Employment/DT/.@__thumb] # ls
defaultIMG_6637.jpg  s100IMG_6678.jpg  defaultIMG_6638.jpg  s100IMG_6642.JPG  s800IMG_6637.jpg 
defaultIMG_6639.jpg. defaultIMG_6676.jpg  s100IMG_6643.jpg  s800IMG_6638.jpg  IMG_6640.jpg  
defaultIMG_6677.jpg  s800IMG_6639.jpg  s800IMG_6676.jpg  default IMG_6641.JPG  defaultIMG_6678.jpg
s800IMG_6640.jpg  s800IMG_6677.jpg  defaultIMG_6642.JPG  s100IMG_6637.jpg  s800IMG_6641.JPG  
s800IMG_6678.jpg  defaultIMG_6643.jpg  s100IMG_6638.jpg  s800IMG_6642.JPG  s100IMG_6639.jpg  
s100IMG_6676.jpg  s800IMG_6643.jpg  s100IMG_6640.jpg  s100IMG_6677.jpg  
````

### Steps to reproduce

Create/place images into a hidden folder e.g `.@__thumb/` and place that in the `Consume` directory 

### Other [_No response_]

**Comment by shamoon** [comment]
I wouldn't consider this a bug, no. We already have a list of folders that are ignored eg. standard OS dirs, etc. For others you can use [PAPERLESS_CONSUMER_IGNORE_PATTERNS](https://paperless-ngx.readthedocs.io/en/latest/configuration.html#software-tweaks)

**Comment by nodecentral** [comment]
Many thanks @shamoon 

So in this situation, do i build on the default ones that are shared, or just add my own incremental/additional ones ? 

Either…
````
PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", “.@__thumb/*]
````
or
````
PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".@__thumb/*]
````

?

**Comment by nodecentral** [comment]
Hi @shamoon - please can you help me exclude this folder, it does not like the format ?

````
PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", “.@__thumb/*]
````
When adding it into my docker compose it returns this ?

````
The Compose YAML is invalid
The Compose file './docker-compose.yml' is invalid because: services.webserver.environment.PAPERLESS_CONSUMER_IGNORE_PATTERNS contains [".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", ".@__thumb/*", "desktop.ini"], which is an invalid type, it should be a string, number, boolean, or a null
````

**Comment by nodecentral** [comment]
@shamoon , please advise ?

**Comment by shamoon** [comment]
I think `PAPERLESS_CONSUMER_IGNORE_PATTERNS: '[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", ".@__thumb/*"]'` should work fine?

**Comment by nodecentral** [comment]
Many Thanks ! Wrapping that in single quotes has allowed the Docker compose to pass the yml format checker..
