### ISSUE TITLE
[BUG] Duplicate files found in Consume folder are not (re)moved after processing ?

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1851]
### Description

Hi, 

I’m raising this as a bug, only as it feels like that should be handled differently ? 

After removing/deleting my original Docker instance to add new environment values, once recreated everything came back up fine, except the UI suddenly started to show it was importing 200 files, which I know I’d imported ages ago.

After a bit of digging, it looks like all those files were duplicates, and this was being confirmed in the logs too ? It looks like duplicates are not moved out of the Consume folder, which means if I don’t manually intervene this is going to occur again..

Suggestion : rather than leave duplicates there, could they be moved to a new/separate folder entirely?  If that’s not possible then maybe moved to the Media folder still, but into to a sub folder or, perhaps give them an appropriate duplicate identifying file name prefix/extension?  

The first option feels a better move, as that way they’re accounted for, but are not left in the `Consume` or `Media` folders to confuse matters etc.

I can understand why it’s good to keep any files that had errors in the consume folder, but duplicates feel like they should be cleared out..

### Steps to reproduce

Move loads of files already in your paperless instance into the consume folder

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - linuxserver.io image

### Browser

IOS Safari

### Configuration changes

environment:       PAPERLESS_REDIS: redis://redis:6379       PAPERLESS_DBHOST: db       USERMAP_UID: 1005       USERMAP_GID: 1000       PAPERLESS_TIME_ZONE: Europe/London       PAPERLESS_ADMIN_USER: XXXXXXX      PAPERLESS_ADMIN_PASSWORD: XXXXXXXX       PAPERLESS_CONSUMER_RECURSIVE: true       PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true       PAPERLESS_CONSUMER_POLLING: 5       PAPERLESS_OCR_LANGUAGE: eng       PAPERLESS_TIKA_ENABLED: 1       PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000       PAPERLESS_TIKA_ENDPOINT: http://tika:9998       #PAPERLESS_PRE_CONSUME_SCRIPT: /usr/src/paperless/scripts/pre_consume101.sh       PAPERLESS_POST_CONSUME_SCRIPT: /usr/src/paperless/scripts/post_consume101.sh       #PAPERLESS_FILENAME_FORMAT: {created_year}/{correspondent}/{title}

**Comment by stumpylog** [comment]
You can configure paperless to delete duplicates from the consume directory.  See `PAPERLESS_CONSUMER_DELETE_DUPLICATES` here: https://paperless-ngx.readthedocs.io/en/latest/configuration.html

**Comment by nodecentral** [comment]
Many thanks @stumpylog , so sorry that I missed that, (good to know) ..

I would like to preserve any duplicates Paperless finds, in a separate folder at least initially, so they can be investigated, is that something that a `pre_consumption` script could handle ? 

If so, by any chance do you know the bash code I could append to my existing script (which I found on the forum) below.. ?
````
#!/usr/bin/env bash

qpdf --show-encryption "${1}" | grep 'File is not encrypted' || qpdf --decrypt --replace-input "${1}"
````
