### ISSUE TITLE
[BUG] 256 Character limit on Matching Patterns for Document Types

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1864]
### Description

Hi,

Flagged as a bug as it has stopped me capture various different matching patterns to assign specific document types.

![EE622061-352F-4D84-80C8-1539CD044416](https://user-images.githubusercontent.com/4349292/197875687-8cf324ef-07b9-47c7-b0c9-4b33e8835d65.jpeg)

_There maybe another way to do this via a post consumption script but I’m not familiar with bash or the format to do that efficiently.._

### Steps to reproduce

Keep entering matching options until you hit the 256 charactor limit

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - linuxserver.io image

### Browser

iOS Safari

**Comment by shamoon** [comment]
How exactly is this a bug? Its a limit on the field length

**Comment by shamoon** [comment]
Also, in general, I think you ought to look at automatic matching, these highly explicit rules dont really benefit from any of the "learning" built in to paperless. For most people "teaching" Paperless what's what is similarly effective and less brittle, not to mention easier to setup.

**Comment by nodecentral** [comment]
Thanks @shamoon , as there wasn’t an option to flag something as a limitation :-),  recording it as a bug seemed like the only other viable option, but i know what you mean.. 

The value for me of these highly explicit rules is that i can be very focussed on exactly what attributes I want Paperless to apply, I can pick out very specific terms/references to really drill in with a high degree of accuracy; and then with document_retagger I can apply them instantly.

I guess an important question,  is do i even need to retain all the Matching Pattern in this configuration setting after its been applied, if I doubt it’ll need to be used as criteria again for a while?
