### ISSUE TITLE
[BUG] Applying a sort in a saved view resets the documents to the main document view

### ISSUE THREAD

**Issue by nalpo** [paperless-ngx/paperless-ngx#1866]
### Behaviour:
If I access a saved view from the sidebar, the view get's refreshed accordingly. But when I use the sort function, the viewable documents get changed back to whatever filters were chosen in the main document view, which is pretty confusing when working with saved views.

### Expected Behaviour:
In step 3 (see below), the sorting options should be applied to the current view and current filter conditions and not the "main view".

### Steps to reproduce

1. Main view: Some filters are set, leading to a set of 8 documents in the view.
![image](https://user-images.githubusercontent.com/46327482/197976530-76332d1f-c468-42b5-a139-49513b971361.png)

2. The saved view "Neue Dokumente" is picked, the view correctly changes to my 80 documents with tag "Neu"
![image](https://user-images.githubusercontent.com/46327482/197976889-46681590-e404-4b8c-bc75-771968c07036.png)

3. After a click on "Sortieren" in the top right corner, any option resets the view to the view from 1., with applied sorting:
![image](https://user-images.githubusercontent.com/46327482/197977330-ddcf8945-00f1-4040-a09f-751eb2af2705.png)

### Paperless-ngx version

1.9.2

### Host OS

Raspberry Pi OS Lite on Raspberry Pi 2 V1.1 B

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/d6b5c733f3264436dffec38c6c1510c9b4db2bcd
