### ISSUE TITLE
[BUG] Dropdowns in settings section not showing arrow icon

### ISSUE THREAD

**Issue by azapater** [paperless-ngx/paperless-ngx#188]
**Describe the bug**
Quite sure the origin is the migration to Angular 13. The dropdown menus in the "settings" section don't show the arrow icon, making them look like regular input boxes. 

Tests done in PR #174 

![image](https://user-images.githubusercontent.com/1220658/156065906-d7dcbf12-7e08-45e7-bee6-951db8554a86.png)

**Comment by shamoon** [comment]
I love frontend bugs (seriously)

I will take a look and should be able to fix tomorrow.
