### ISSUE TITLE
[BUG] Can’t select the ‘Any’ option from the Tags drop down menu on Documents UI

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1882]
### Description

Hi, 

Hopefully the subject of this post is clear but I wanted to apply a filter using a few tags to see which documents have it, assuming that the ANY feature works like a ‘OR’ command. 

Unfortunately I’m not able to select the ANY option, it’s unable to move off of ALL , so any filter can only work like an `AND` command

![4F2F1D9F-8129-45C6-8EB1-D7022424DE11](https://user-images.githubusercontent.com/4349292/198722208-5a90ddb3-7d3f-4927-9241-f0131abdf90f.jpeg)

### Steps to reproduce

Try clicking on the Any sub option under the Tags drop down filter see image above

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - official image

### Browser

IOS Safari

**Comment by stumpylog** [comment]
If you select two or more tags, the Any is clickable.  I'd wager this is the intended behavior, since an OR condition doesn't make sense until there's something to OR

**Comment by nodecentral** [comment]
Thanks @stumpylog 

That make sense, and with that in mind please can I suggest that the `Any` option is hidden/greyed out until two tags or more are select ?

In support of your point, if it’s not a valid option until two or more are selected, it shouldn’t be made available for (idiots) people like me who think i I have to choose that option first, as it comes before the tag list.. :-)

**Comment by shamoon** [comment]
Yes thats exactly what it does, the button is disabled until ≥ 2 items are selected.
<img width="182" alt="Screen Shot 2022-10-28 at 10 23 20 PM" src="https://user-images.githubusercontent.com/4887959/198815440-4d3f6954-e68c-44de-9f61-ca2cf30b3e10.png">
<img width="180" alt="Screen Shot 2022-10-28 at 10 23 17 PM" src="https://user-images.githubusercontent.com/4887959/198815441-e3339cb3-462a-4fd3-9c5f-4751edde4f2f.png">

**Comment by nodecentral** [comment]
Thanks @shamoon - any chance it can be made invisible too? Seems counterintuitive to have a search/filter option visible that's disabled. Only present the user with capabilities they can use, when they can use them..

**Comment by shamoon** [comment]
In general I think its better to show things and disable them rather than be sliding things in and out. Things moving unexpectedly in a UI is no good. If a lot of folks feel the same we can look at this, hasn't been an issue so far

**Comment by nodecentral** [comment]
Thanks 👍
