### ISSUE TITLE
[BUG] Text in filterable dropdown menus dissapearing after loosing focus

### ISSUE THREAD

**Issue by azapater** [paperless-ngx/paperless-ngx#189]
**Describe the bug**
Quite sure the origin is the migration to Angular 13. Opening any of the filterable dropdown menus in "Documents" section and without any item selected, getting the mouse out of the button makes the text dissapearing. 

Tests done in PR https://github.com/paperless-ngx/paperless-ngx/pull/174

https://user-images.githubusercontent.com/1220658/156069523-7ce8c2e9-3083-4466-85f4-c0b4bbe29993.mp4

**Comment by shamoon** [comment]
It took me a second, aha you mean the actual text of the button becomes invisible (wrong color). 

Another good one, thanks! (I will also take care of this)

**Comment by azapater** [comment]
> you mean the actual text of the button becomes invisible (wrong color).

yeah! exactly that. I assume it gets the same colour as the button, but it visually looks like it dissapears. Sorry, maybe I didn't explain myself correctly. 

> Another good one, thanks! (I will also take care of this)

you are welcome. Thanks for taking care of it. have fun! XD

**Comment by shamoon** [comment]
why no auto-close
