### ISSUE TITLE
[BUG] Straight quotes vs Curly quotes are handled differently

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1893]
### Description

Not sure if this constitutes a bug, or more an observation/sanity check, but depending on the keyboard I’m using, either a physical or virtual (screen) version, it can use different styles of quotes. Either curly ones “” from the physical keyboard, or straight ones "" when using the virtual keyboard.

Based on some tests, when you use ‘Any’ as your matching algorithm and you want to match on some specific phrases, if you use curly quotes, it looks like the framing is ignored. For example if i set up a Tag, with the Any criteria option, and ask it look for “Virgin Media Team” “Virgin Phone System” - it ends up looking for all the words individually, not the chain/sequence requested...

If I use straight quotes, it will do as requested, and only look for those specific chain/sequence of words.

### Steps to reproduce

Create two tags, one looking for a sequence of words wrapped in curly quotes, and another with straight quotes.

![E7C0AA66-7267-4BE2-8A55-6ED7D20A5280](https://user-images.githubusercontent.com/4349292/198899347-4bf7ebfd-601f-486d-b716-cdfda020999a.jpeg)

These two were applied against the same documents, only one document had the correct sequence and should have had the tag applied.. And that document was only found by the Tag set up using straight quotes

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - official image

### Browser

Safari iOS

**Comment by shamoon** [comment]
Curly quotes almost always cause problems, Im not aware that most keyboards use curly except in for example document editors. But anyway, isnt the solution here to just use straight quotes?

...

**Comment by nodecentral** [comment]
Hi @shamoon , i guess the issue is I didn't even realise i’d been using different styles of quotes, I just noticed certain things weren’t being assigned, and I assume it was an issue with Paperless. 

As for what to do, there are a few options, going from easiest to hardest :-)

1. Update the readme doc to make it clear that straight quotes should be used (it might not be easy for people to see)
2. Add a comment on the create pop up window, that makes it clear straight quotes must  be used when a sequence of words is being looked for 
3. Implement a backend process that checks for non straight quotes and replace them automatically

No 1’s obviously the quickest and easiest, and because it’s such an easy thing to miss, it would be good to publish  something on it, if only to address anyone thinking its just not working right.
