### ISSUE TITLE
[BUG] Completed file tasks is capped at 250

### ISSUE THREAD

**Issue by HFulcher** [paperless-ngx/paperless-ngx#1895]
### Description

When uploading +250 PDFs in one go the File Tasks window does not display the correct number of completed tasks once past 250.

![Uploading Screenshot 2022-10-31 at 13.52.59.png…]()

I uploaded ~750 PDFs and the total of failed, completed, started and queued does not match. Completed stays at 250 regardless of how many have now been completed.

### Steps to reproduce

1. Bulk upload +250 files
2. Once 250 files have been completed the counter will stay at that number

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu Server 22.04

### Installation method

Docker - official image

### Browser

Edge

**Comment by stumpylog** [comment]
I do see this, at a glance it's something with django-q not creating a Task.  The entire tasks has been reworked for the next release though and it doesn't happen in the `dev` build.

![image](https://user-images.githubusercontent.com/797416/199031717-f68d1b25-fd21-45fb-af5f-59f09254f8cf.png)

**Comment by HFulcher** [comment]
Cool, thanks for the swift response!
