### ISSUE TITLE
[BUG] Custom css - overrides.css is not loaded

### ISSUE THREAD

**Issue by leigsnering** [paperless-ngx/paperless-ngx#1921]
### Description

Hello,

My installation is done with Docker and works very well. I want to customize a little interface especially the primary color. I followed the documentation by creating a file overrides.css in the media folder, but it is not loaded.

Do I do some bad things?

Thks a lot !

### Steps to reproduce

overrides.css in the media folder

### Webserver logs

```bash
.
```

### Paperless-ngx version

Paperless-ngx 1.6.0

### Host OS

Docker Synology

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Where is that described in the documentation? I’m not even aware of this option

Also if you just want to change the color, please look in the settings

**Comment by shamoon** [comment]
Ah, I think [that](https://paperless-ngx.readthedocs.io/en/latest/changelog.html?highlight=Overrides.css#id28) is a reference from the old Paperless and is no longer the case
