### ISSUE TITLE
[BUG] large number of strange document names appearing in the log file

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1932]
### Description

Hi, 

I’m sure there’s an explanation for this, but I’m doing a large import from my mail box and there were a lot of strange file names appearing, as they all follow the same structure, all worth no file type extension, i assume it’s something Paperless-ngx is doing, but as it’s occuring against a huge amount of file, I’m naturally curious

To be clear, It does show the full and proper file name (along with its file type) for anything that seems to be more well known like, a jpeg, pdf, png. doc etc. as attachments.

![Uploading 25080977-759B-49A1-95BA-44E2386472A9.jpeg…]()

### Steps to reproduce

I have a mail rule for a gmail account thats running to import any/all attachments 

(I’ve had to enable it to `Process all files, including 'inline' attachments` due to another issue I’m seeing - which is reported separately  

### Webserver logs

```bash
Image provided earlier
```

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - official image

### Browser

Safari iOS

**Comment by shamoon** [comment]
Ok, please be more mindful of the issues youre opening, so far they have not yielded anything particularly helpful for the software for everyone. If you have questions or thoughts they belong in discussions. We all do this on a volunteer basis and each of these takes time.

Emails have all kinds of inline attachments and generally is a messy format. It doesnt seem like theres a bug here.

**Comment by nodecentral** [comment]
Thanks, and Yep, agreed. I was also conscious I was raising quite a few things lately , but if I couldn't find an answer elsewhere, all I could think to do was log it here, (if it was something that didn't seem right/normal), or in discussion section.

For this particular one, seeing a long list of random 3 part words appear out of the blue, with no file name or extension called out - plus as they are being processed Paperless seemed to refer to them with file name - so all in all, it just didn't add up, or seem normal.

As always I have huge admiration for what you all do with Paperless and I really appreciate it that you responded to this and explained it not unexpected.
