### ISSUE TITLE
[BUG] Need to restart container to digest

### ISSUE THREAD

**Issue by Gabgobie** [paperless-ngx/paperless-ngx#1975]
### Description

Paperless works flawlessly except for the fact that i have to docker-compose up -d --force-recreate for it to digest the files in the consume folder.

### Steps to reproduce

1. Set up paperless using the provided install script
2. install cifs-tools
3. mount a scan folder from your nas to the consume folder (make sure permissions are set correctly.. took me some time to figure that out)
4. put your documents into the consume/scan folder
5. docker-compose up -d --force-recreate
6. your files will be digested
7. put more documents into the folder
8. they won't be digested until you docker-compose up -d --force-recreate

### Webserver logs

```bash
there are no errors in the logs.. it states that inotify is listening to the folder which seems to not be the case or at least fail. there is just no error so it seems to believe that it's actually listening
```

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 22.04 x86_64

### Installation method

Docker - official image

**Comment by Gabgobie** [comment]
So after some digging i found out that smb shares can't be monitored. So there are two options remaining to me. Either try to access the files through another protocol (sftp) or make a cron job to try to digest whatever is available. I guess I'll try to go with sftp

**Comment by stumpylog** [comment]
You can also try with polling, instead of inotify

**Comment by Gabgobie** [comment]
Interesting.. how would i go about that?

**Comment by stumpylog** [comment]
https://paperless-ngx.readthedocs.io/en/latest/configuration.html#software-tweaks

PAPERLESS_CONSUMER_POLLING=x
