### ISSUE TITLE
[BUG] response missing when posting document.

### ISSUE THREAD

**Issue by jdckr** [paperless-ngx/paperless-ngx#1976]
### Description

When posting a document towards the rest api I don't get any response but the document is properly consumed.

I see this behavior since some weeks in the mobile apps I use to add new documents. Checked today and I am able to reproduce this with a simple post request. In the logs there is nothing suspicious. Any hints how to further debug this?

### Steps to reproduce

1. post document to /api/documents/post_document/
2. check response

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.9.2

### Host OS

Rasperry Pi

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
If the document is consumed, then the background task was created and queued properly.  The very next thing the code does is return a response.  If the response gets stuck, I feel it must be outside our code.

Can you test this against the beta?  It has numerous updates to our dependencies, like the RETS framework library and Django itself.

**Comment by shamoon** [comment]
Yea, there definitely is a response, I’d guess it’s somehow not being received rather than not sent

See https://github.com/paperless-ngx/paperless-ngx/blob/8feada6907a616c16956646810342dca11e18a02/src/documents/views.py#L628

**Comment by jdckr** [comment]
I tried 1.10.0-beta and there it works again. Thanks!
