### ISSUE TITLE
[BUG] v1.9.0 RC1 - Flower Documentation limited

### ISSUE THREAD

**Issue by smseidl** [paperless-ngx/paperless-ngx#1989]
### Description

Working on setting up 1.10 Beta and read the release notes about Flower/Prometheus and was looking forward to enabling.  I have never worked with flower before so I have no clue on what should go into the `flowerconfig.py` file.  It would be nice if the documentation or github had an example configuration and maybe details on connecting to Prometheus.

### Steps to reproduce

N/A - Documentation BUG

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

1.10 Beta

### Host OS

x86_64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
I don’t think the Prometheus PR made it into this. And as for flower, i think linking to that project is enough? I didn’t have to do anything to the config so if someone is going beyond that I think it’s reasonable that they go to the source. I’d say we don’t want too much cruft directly in our docs, imho…

**Comment by stumpylog** [comment]
Correct, the paperless specific metrics PR did not get into this release.

I agree that linking to flower's documentation is sufficient.  It isn't up to us to document how to configure and use another tool, beyond saying how to start it and providing the option for additional configuration.

I put the docs for enabling it in the advanced setup for that reason.  If you're wanting metrics like that, you're probably an advanced user already, who will go to the source and decide what, if any, extra configuration you'd like to do.
