### ISSUE TITLE
[BUG] Drag and Drop of pdf files yields lots of "HTTP error: 0 Unknown Error"

### ISSUE THREAD

**Issue by RobPattonDotCom** [paperless-ngx/paperless-ngx#1994]
### Description

New to this docker way of doing things, so be gentle..

While trying to import my library of pdf files, many will yield 

HTTP error: 0 Unknown Error

Is there some limit as to how many I can import.  I'll be honest, I dropped 15K files, but so far only about 10% have showed up after several attempts.

Is there a better way to ask this thing to ingest files?   

Is there some way for me to just copy the files over to the container to be processed?

I already have a system in place to scan and auto drop documents into a windows share, and I don't want to change that.  But Is there an easy way to have this watch an SMB share ?   

### Steps to reproduce

Select 15K pdf files, drop them on the "Drop Documents here"  wait for fail

### Webserver logs

```bash
Oddly the logs section is blank at this time, not sure what that means.
```

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 22 docker

### Installation method

Docker - official image

### Browser

Brave

### Other

10% works, eventually.

**Comment by stumpylog** [comment]
If I'm understanding this right, you dropped about 15k files into the WebUI?  I'm surprised anything works at all.

A better way to process such a large number of files (and files as they are scanned) is to use the [consume directory](https://paperless-ngx.readthedocs.io/en/latest/usage_overview.html#the-consumption-directory).  It's a directory which is watched for files, which are then processed as noticed.  By default, the path is `/usr/src/paperless/consume` inside the container, which can be mapped to anything you'd like outside the container (including a mounted network share, with some configuration).  Permissions will need to be correct for everything to function correctly,

Also, given the large number of initial files, you may want to:
- Use the `beta`. It had a lot of fixes related to task processing and large numbers of files.
- Batch them up so you can tag them, run the classifier, fix dates, find problematic files, etc

**Comment by shamoon** [comment]
Ha yes, that is an optimistic test of the webui! I’m curious if eg Google drive can handle 15k docs?!

Please let us know if you have issues with the above [thorough] alternative suggestions
