### ISSUE TITLE
[BUG] Documents API returns full content of document, which can lead to sluggish performance

### ISSUE THREAD

**Issue by falnos24865** [paperless-ngx/paperless-ngx#1996]
### Description

The `api/documents` call returns the full body of each document in the payload. While this is fine for small documents, with documents of any size this causes a payload of many MB, or even hundreds of MB in some of my cases. What makes this worse is the UI on the documents page does not display the full body of the document anywhere.

Recommendation: Trim the content of each result to a reasonable size, say around 2KB. This is plenty to be displayed by the UI and will fix issues with large documents.

### Steps to reproduce

1. Upload a series of large documents
2. Access the documents page
3. Notice slow response times and large payloads

### Webserver logs

```bash
None
```

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 20.22

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Im not sure this is a bug, but it is a valid concern, its already under discussion in #1854
