### ISSUE TITLE
[BUG] Cannot POST or PUT correspondent/document type/tags/documents from mobile app with autologin enabled

### ISSUE THREAD

**Issue by astubenbord** [paperless-ngx/paperless-ngx#2002]
### Description

When POSTing against the API (e.g. /correspondents/), I get a 403 Forbidden response with 
```json
{
"detail":"CSRF Failed: CSRF cookie not set."
}
```
in the body when posting from https://github.com/astubenbord/paperless-mobile. I tried a paperless instance both with and without a reverse proxy. 
When having autologin disabled, everything works as expected (with a bearer token sent to the server).

GET requests also work fine with autologin enabled, i.e. all document information can be retrieved and thumbnails/preview/download also loads as expected.

Is this a problem with my configuration or do the POST/PUT endpoints require a CSRF token OR a Bearer token to be sent? Because with autologin enabled, the app would neither send a Bearer nor a CSRF token. A CSRF Token should not be required anyway when not executing requests from within a browser. Is there a workaround for this?

### Steps to reproduce

1. set `PAPERLESS_AUTO_LOGIN_USERNAME=<username>` 
2. POST/PUT a new/existing correspondent/document_type/tag/storage_path/document from within app

### Webserver logs

```bash
[2022-11-20 00:30:54,050] [WARNING] [django.request] Forbidden: /api/correspondents/
[2022-11-20 00:31:38,215] [WARNING] [django.request] Forbidden: /api/document_types/
[2022-11-20 00:32:59,523] [WARNING] [django.request] Forbidden: /api/document_types/
[2022-11-20 00:33:03,714] [WARNING] [django.request] Forbidden: /api/document_types/
[2022-11-20 00:33:07,644] [WARNING] [django.request] Forbidden: /api/document_types/
[2022-11-20 00:33:33,461] [WARNING] [django.request] Forbidden: /api/correspondents/
```

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
The REST API still requires some form of authentication.  The auto login only applies to a browser request.  It could be changed, but at this moment I'm not sure of the implications.  Since a GET request works, I would assume the app is include a proper method of authorization in those.

The current behavior is consistent [with the docs](https://paperless-ngx.readthedocs.io/en/latest/api.html#authorization) which indicate authorization is required and don't provide any expectations of it being possible to disable.

**Comment by shamoon** [comment]
Yea Im not sure I see the issue, token auth works fine. Btw, curious why are you using `PAPERLESS_AUTO_LOGIN_USERNAME` at all? the docs state its not a good idea if your instance is exposed to the internet (which presumably it is if youre posting to the api from your app).

**Comment by astubenbord** [comment]
Thanks for the quick response. 
I don't need it personally, it was a request for the app to support this feature. But I also don't see many scenarios in which this is a good idea or needed. I'll close this issue, thanks again.
