### ISSUE TITLE
[BUG] Saved view: Filter rule "has tag" requires tag ID; should be tag name

### ISSUE THREAD

**Issue by torbengb** [paperless-ngx/paperless-ngx#2008]
### Description

- In the definition of "Saved views", when using the filter rule "has tag", if I enter the tag name itself, the view incorrectly shows all documents.
- the filter rule "has tag" requires me to enter the ID of the tag. 
- As a user, I do not know the internal ID values of the tags I have created.
- Found while trying to solve the user issue #2005.

### Steps to reproduce

1. Go to Paperless > Tags
2. pick a tag that has documents assigned to it. I use the tag "Inbox"; I can see that 2 documents use this tag.
![image](https://user-images.githubusercontent.com/810590/202921499-b087ea7e-3320-41e9-ac20-6981ebe787f5.png)
3. Go to Admin > Add new saved view
4. name "test-inbox", show in sidebar, ruletype = "has tag", value = "Inbox", Save.
5. Go to "View site" > in the sidebar, select the saved view "test-inbox".
6. ❌ observe: Paperless shows _ALL_ documents, even though they do not meet the criteria "has tag"="Inbox". 
![image](https://user-images.githubusercontent.com/810590/202922027-4124f79b-4460-4cac-8b91-72a3809791c8.png)
7. Go to Admin > edit saved view "test-inbox".
4. In the ruletype = "has tag", change the value to "1". (This is the ID of the tag "Inbox".) Save.
5. Go to "View site" > in the sidebar, select the saved view "test-inbox".
6. ✅ observe: Paperless shows the expected 2 documents that are tagged "Inbox".
![image](https://user-images.githubusercontent.com/810590/202922093-045484cf-4f53-4f4b-a68d-d4726f1b7fad.png)

### Webserver logs

```bash
Not sure? Apologies!
```

### Paperless-ngx version

1.9.2

### Host OS

Synology running Docker container "ghcr.io/paperless-ngx/paperless-ngx", from here: https://mariushosting.com/how-to-install-paperless-ngx-on-your-synology-nas/

### Installation method

Other (please describe above)

### Browser

Newest Firefox on Windows 10.

### Configuration changes

None.

**Comment by shamoon** [comment]
This doesn’t seem like a bug, the UI works, entering in the wrong value for that parameter in the backend doesn’t.

I agree most people don’t know the ID of their tags, that’s what the frontend is for…

**Comment by torbengb** [comment]
Hello! Just making sure I understand you correct: 

- Are you saying that this is not a bug because it is intentional that the user must specify the **ID** of the tag?
- Are you saying that the purpose of the front end is that users don't need to know the ID's? 

Those two statements seem contradictory. 

But anyway, if this not a bug then it would qualify as a feature request that I would submit if you confirm the above — given that the users aren't supposed to care about back-end ID's, it follows that the filter rules UI should be able to show a list of existing tags. We already see this in the UI for the mail rules metadata. 
![image](https://user-images.githubusercontent.com/810590/203018841-4d2acc0c-edb3-4198-a8fd-92f40efbde02.png)

**Comment by shamoon** [comment]
Yes a feature request if you like. We dont build this software around the "admin" which is Django's **auto-generated** admin, our focus is the angular frontend UI and of course the backend mechanisms e.g. OCR, scheduling etc. You keep talking about the admin "UI" but again, thats not the UI we actually work on
