### ISSUE TITLE
Document how to upgrade from Paperless-ng to -ngx

### ISSUE THREAD

**Issue by bauerj** [paperless-ngx/paperless-ngx#204]
The switch is rather simple (I assume?) but it should be documented either in the README or in the docs.

**Comment by jschpp** [comment]
As far as I can tell it should be enough to do the following in the docker-compose.yml

```diff
@@ -47,7 +47,7 @@
       POSTGRES_PASSWORD: paperless
 
   webserver:
-    image: ghcr.io/paperless-ngx/paperless-ngx:latest
+    image: jonaswinkler/paperless-ng:latest
     restart: unless-stopped
     depends_on:
       - db
```
after that `docker-compose pull && docker-compose up -d`

**Comment by qcasey** [comment]
That's, plus a link to the backup docs to cover our butts.

**Comment by shamoon** [comment]
Probably should just add to https://paperless-ngx.readthedocs.io/en/latest/setup.html#migration-to-paperless-ngx

I think its overkill to put in the readme (since literally theres nothing to do besides use -ngx =) What do others think?

I can take a swing at it.

**Comment by shamoon** [comment]
Welcome your input in #206

**Comment by shamoon** [comment]
Closed by commit merged in `dev`
