### ISSUE TITLE
Proton Mail Bridge Hostname

### ISSUE THREAD

**Issue by damianarnold1993** [paperless-ngx/paperless-ngx#2047]
### Description

I use ProtonMail with 10 Email Accounts with my own Domain. ProtonMail needs a local MailBridge for secure e-Mails. 
Paperless run on a VM with Debian an Docker. ProtonMailBridge is also installaed on this VM. I don't have a link like imap.hotmail.com

My Mailbox Hostname is 127.0.0.1 on Port 1143
![image](https://user-images.githubusercontent.com/76855878/204156640-ebf898b1-ca54-44de-8db2-8958f2a1cf5c.png)

In my logs i cecieved [paperless_mail] Error while retrieving mailbox Paperless: [Errno 111] Connection refused

### Steps to reproduce

1. Settings
2. e-Mail Account

### Webserver logs

```bash
[2022-11-27 20:44:30,419] [DEBUG] [paperless_mail] Processing mail account Paperless

[2022-11-27 20:44:30,432] [ERROR] [paperless_mail] Error while retrieving mailbox Paperless: [Errno 111] Connection refused
```

### Paperless-ngx version

1.9.2

### Host OS

Debian 11

### Installation method

Docker - official image

**Comment by shamoon** [comment]
I have no idea if the imap library will work with protonmail (if not, let’s call it a feature request) but the error log says connection refused, so this certainly seems like a networking / configu issue at the moment, doesn’t it?

**Comment by damianarnold1993** [comment]
ProtonMail runs locally on the Debian machine. A network problem can (99%) be ruled out. ProtonMail would be a cool feature in the future :)

**Comment by shamoon** [comment]
Sure but you’re trying to connect to it from a docker container. You can verify by pinging the mail server from inside the docker container eg `docker exec ping` (of course that would only check IP resolution not necessarily the port), depending on your docker networking 127.0.0.1 won’t resolve to your host from inside a container

**Comment by damianarnold1993** [comment]
sorry, i'm not de big IT crack... :) but i will give my best!
Seems not working 
![image](https://user-images.githubusercontent.com/76855878/204158982-fe6b9cd0-213c-4fe4-8e35-3b1f99cd58e6.png)

**Comment by shamoon** [comment]
Yea ping isn’t installed by default (you would `apt-get update && apt-get install iputils-ping`) but now that I think about it 127.0.0.1 will just resolve locally and won’t illustrate what I think is the issue

try `apt-get update && apt-get install netcat` then `netcat -vz 127.0.0.1 1143`

on my phone, pardon typos

**Comment by damianarnold1993** [comment]
![image](https://user-images.githubusercontent.com/76855878/204159997-74083149-7fa2-41f1-b9b6-64341651451d.png)

**Comment by shamoon** [comment]
Ha, touché

I have no idea about how protonmail works if that’s the issue

**Comment by shamoon** [comment]
So the mail bridge acts like a local imap server? Maybe a TLS issue since I’d guess the bridge is using self-signed certs?

**Comment by damianarnold1993** [comment]
The Bridge make a local IMAP Server. (They sad) its very secure an on high Level security :)

https://proton.me/mail/bridge
 "Proton Mail Bridge is a desktop application that runs in the background, encrypting and decrypting messages as they enter and leave your computer. It lets you add your Proton Mail account to your favorite email client via IMAP/SMTP by creating a local email server on your computer."

**Comment by shamoon** [comment]
Well not certain its the issue but does look like certificate may be an issue: https://proton.me/support/bridge-ssl-connection-issue

That suggests to disable SSL entirely, have you tried that? Theres also a troubleshooting section there.

At this point I dont think this is something we'll be addressing at the paperless level, either theres a workaround (e.g. above) or worst case I think it'd have to be dealt with by the tool we use to connect to IMAP servers, e.g. https://pypi.org/project/imap-tools/

Please do update the thread if you figure it out, others may find it useful

**Comment by stumpylog** [comment]
Unless you've configured networking differently, services in a container can't access a service running on the host.  In this case, 127.0.01 inside the container means the container, not the host, and the container doesn't have the bridge running to connect to.

Based on some research, you can do something like this: https://stackoverflow.com/questions/71936577/how-to-access-mysql-host-port-from-docker-container to access a port on the host from inside a container.  The bridge is also provided via a .deb, so you could create your own image and container and connect it to the same network as the paperless container.

**Comment by shamoon** [comment]
I was wondering if he had `network_mode: host`, youre more the expert than I

Another thought: if you are connecting to the proton server perhaps the proton logs will show something
