### ISSUE TITLE
[BUG] Update from 1.9.2 to 1.10.0 (latest) ends in bootloop

### ISSUE THREAD

**Issue by Limerick-gh** [paperless-ngx/paperless-ngx#2061]
### Description

Hi there
I just updated to latest release 1.10.0 from running 1.9.2 with sqlite db and tika setup on Raspberry Pi 4 using docker.
But the paperless-ngx-webserver container is not starting properly and loops on start. See log below. Did not had any issues on previous updates.
Any help is welcome.

### Steps to reproduce

As described, update from 1.9.2 to 1.10.0 ends with failure on start.

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
[nltk_data] Error loading snowball_data: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>
Error installing package. Retry? [n/y/e]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/nltk/downloader.py", line 2540, in <module>
    rv = downloader.download(
  File "/usr/local/lib/python3.9/site-packages/nltk/downloader.py", line 788, in download
    choice = input().strip()
EOFError: EOF when reading a line
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
[nltk_data] Error loading snowball_data: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>
Error installing package. Retry? [n/y/e]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/nltk/downloader.py", line 2540, in <module>
    rv = downloader.download(
  File "/usr/local/lib/python3.9/site-packages/nltk/downloader.py", line 788, in download
    choice = input().strip()
EOFError: EOF when reading a line
Paperless-ngx docker container starting...
```

### Paperless-ngx version

1.10.0

### Host OS

Raspberry Pi 4

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
`Temporary failure in name resolution` - you have some sort of DNS issue

**Comment by kuppingercole** [comment]
I have the same problem.
And yes, it looks like a DNS issue, but why don't other 20 containers running on my server have any?

```
Paperless-ngx docker container starting...
Installing languages...
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Package tesseract-ocr-rus not found! :(
Creating directory /tmp/paperless
[nltk_data] Error loading snowball_data: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>
Error installing package. Retry? [n/y/e]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/nltk/downloader.py", line 2540, in <module>
    rv = downloader.download(
  File "/usr/local/lib/python3.9/site-packages/nltk/downloader.py", line 788, in download
    choice = input().strip()
EOFError: EOF when reading a line
Paperless-ngx docker container starting...
Installing languages...
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'

```

**Comment by Limerick-gh** [comment]
@stumpylog: I have seen that name resolution entry in the log files, but I was guessing it's not coming from my setup since it worked the last months without issues. Thanks to your post, I investigated a little and figured out that I was proven wrong. So thanks for pushing me to the right root cause. Probably earlier releases did not require DNS?

Anyhow, the reason for my issue was pihole that I am running in another container on the same host. It looks like that with default config, other containers on the same host cannot reach it.  I found the answer here (https://stackoverflow.com/a/69994721). After I added the host ip address to the pihole port mapping, e.g.:
```
    ports:
      - 192.168.1.30:53:53/udp
      - 192.168.1.30:53:53/tcp
```
and recreating containers, the version 1.10.0 was starting as expected. :-)
Maybe this post helps other's having similar setup.

**Comment by KBischof** [comment]
```
[nltk_data] Error loading snowball_data: <urlopen error [Errno -3]
[nltk_data] Temporary failure in name resolution>
```
I had this error too while upgrading to Paperless-ngx v.1.10.0 and this is how I resolved it, this might be of help to others searching this same issue. A bit on my environment, I'm running Paperless-ngx on a Synology server, using Portainer via Docker (https://mariushosting.com/synology-install-paperless-ngx-with-office-files-support/). I am running Pi-hole on my network. 

Reading the comments above, I too thought I might have a DNS issue emanating from Pi-hole . However, after doing some debugging, I realized my issue was coming from the firewall on Synology.  I already have firewall rules to allow Paperless-ngx (port 8777) on all machines on my network subnet. I tried a few firewall tweaks, but nothing worked. So I temporarily disabled the Synology firewall and Paperless-ngx immediately finished upgrading and all is working well. I then re-enabled Synology firewall.  

**So temporarily disabling my Synology firewall, fixed the errors I encountered updating Paperless-ngx.**

**Comment by grimsi** [comment]
I had the same problem and adding the IP in front of the port did not work for me.
My setup also includes a PiHole running on the same host as Paperless-ngx, so that is definitely the reason.

I was able to solve my problem by setting the DNS for the "web" container in the compose file manually like this:
```
dns:
  - <IP of your DNS server>
```

**Comment by Limerick-gh** [comment]
@grimsi: Thanks for sharing. Wasn't aware that specifying it directly in the compose is possible. Good to know. 👍

**Comment by drivingmx** [comment]
For me, none of the above worked.
I also run paperless on a synology with pihole on the exact same host.
My docker- network is also bridged, so that the Synology sees another DNS address than my router. I tried all possible combinations, nothing worked.

I just set
```
dns:
  - 8.8.8.8
```

and it worked.

**Comment by morremeyer** [comment]
Hey everyone, would it be possible to re-open this? The reasons for this would be:

* versions prior to 1.10.0 did not try to install an additional package when starting, which is an antipattern. OCI images should be immutable.
* this change makes it impossible to run paperless in an environment without an internet connection (which applies to my environment: my paperless instance does not need to connect to the internet, so it does not have internet access)

**Comment by morremeyer** [comment]
Setting `PAPERLESS_ENABLE_NLTK` to `false` worked perfectly.

Thanks for the quick reply and thanks in advance for documenting this!
