### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by myxor** [paperless-ngx/paperless-ngx#2070]
### Description

Demo on https://demo.paperless-ngx.com/ is not working:

![grafik](https://user-images.githubusercontent.com/1397377/204763197-c0f2eb3b-94bb-4bbf-9a70-b3fcffedffe8.png)

### Steps to reproduce

1. Go to https://demo.paperless-ngx.com/
2. See cloudflare message

### Webserver logs

```bash
-
```

### Paperless-ngx version

-

### Host OS

-

### Installation method

Other (please describe above)

**Comment by shamoon** [comment]
Yea, welcome to "free tier" (it sucks)

Its been freaking out for a couple days, tbh Im not sure whats up but it usually smooths out eventually
