### ISSUE TITLE
[BUG] Unable to get API token if PAPERLESS_AUTO_LOGIN_USERNAME is set

### ISSUE THREAD

**Issue by JigSawFr** [paperless-ngx/paperless-ngx#2075]
### Description

Currently if you set the ENV var PAPERLESS_AUTO_LOGIN_USERNAME to something (ie your username).
You will not be able to grab a token via /api/token endpoint. (and so unable to use mobile apps)

### Steps to reproduce

1. Set PAPERLESS_AUTO_LOGIN_USERNAME with your username as value
2. Try with any paperless app (iOS/Android) or with Postman (POST on /api/token endpoint)

### Webserver logs

```bash
[2022-12-01 18:31:26,379] [WARNING] [django.request] Forbidden: /api/token/
```

### Paperless-ngx version

1.10.0

### Host OS

Ubuntu 22.10

### Installation method

Docker - official image

### Browser

Edge (Chrome)

### Configuration changes

n/a

### Other

Remove the env var and apps/api token works again.

**Comment by shamoon** [comment]
There is a warning for that setting that you shouldn't be using it on the internet, if youre using a mobile app I assume you are. I'm not sure it makes sense to fix this as its not really an intended use case...

**Comment by JigSawFr** [comment]
@shamoon it depends, but on my case everything is protected by authelia, but I've switched to remote-user header instead, which works fine. But use case can be internet and/or lan.

**Comment by shamoon** [comment]
remote-user is designed for this. so if you dont need it i think we can wait and see if others are having a problem with this before investing time in working on it =)
