### ISSUE TITLE
[BUG] Update documentation links in readme

### ISSUE THREAD

**Issue by natrius** [paperless-ngx/paperless-ngx#2093]
### Description

https://github.com/paperless-ngx/paperless-ngx is basically referencing https://paperless-ngx.readthedocs.io/en/latest/?badge=latest everytime insted of https://docs.paperless-ngx.com/

I mean, due to the redirect its not that bad, but it should be changed. I did not update it because i don't know about the badges in the first line.

**Comment by shamoon** [comment]
Good point I’ll fix thanks!

**Comment by OddSquirrel** [comment]
@shamoon Did something possible go sideways?

(I don't mean to nag, just noticed that all I get is a 404 when trying to pull up the docs.)

**Comment by natrius** [comment]
Nah, its not merged yet. But still, the redirect does not work today :D It worked yesterday though.

**Comment by OddSquirrel** [comment]
Well, it's weekend, right? If I were a doc server, I wouldn't have the energy to work, either. 😋

**Comment by nakal** [comment]
Yeah, it's weekend and a nice time to migrate from Paperless-NG. But no docs... no migration. ;)

**Comment by shamoon** [comment]
Fixed, sorry about that!
