### ISSUE TITLE
[BUG] Migration 1012_fix_archive_files fails with MariaDB using utf8mb4

### ISSUE THREAD

**Issue by homberger** [paperless-ngx/paperless-ngx#2094]
### Description

The initial execution of the migrations fails:

```
Applying documents.1012_fix_archive_files...Traceback (most recent call last):
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/paperless/.local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/opt/paperless/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/paperless/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/paperless/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')
```

In migration `documents.1012_fix_archive_files` the new unique keys of the columns `filename` and `archive_filename` exceed the max key length of 3072 if the character set is utf8mb4 as these columns have a length of 1024 characters and utf8mb4 needs up to four bytes per character.

My workaround was to decrease the length of both fields from 1024 to 768. As I never used or installed paperless-ngx before, I do not know if this is a good workaround.

### Steps to reproduce

1. use MariaDB with character set utf8mb4
2. execute the migrations: `sudo -Hu paperless python3 manage.py migrate`

### Webserver logs

```bash
No logs
```

### Paperless-ngx version

1.10.1

### Host OS

Ubuntu 18.04

### Installation method

Bare metal

**Comment by stumpylog** [comment]
MariaDB seems like it's been nothing but issues.  The best I can see doing is documenting this as a potential issue in using it.

**Comment by shamoon** [comment]
Yea so much for db abstraction saving us from all this. Agree, updating docs is a good solution here

**Comment by stumpylog** [comment]
From what I gather, those fields should be declared as `VARCHAR` which support something like [21k characters](https://mariadb.com/kb/en/varchar/) with a utf8 character set.  Even if that's 3 bytes per char, at 4 bytes it still seems like enough at around 16k characters.  That also matches my own testing, I can create a DB with MariaDB and all migrations are applied without issue.

![image](https://user-images.githubusercontent.com/797416/205452973-b666396b-7387-4c0c-8cf7-1d5a03a42cb4.png)


I'd make sure you don't have a setting or configuration on the DB limiting the length of columns further.

**Comment by homberger** [comment]
@stumpylog:

> MariaDB seems like it's been nothing but issues. The best I can see doing is documenting this as a potential issue in using it.
This is not an issue of MariaDB/MySQL, this is an issue of indexes and their limits which is exactly the same for other RDBMS like Postgres.

> From what I gather, those fields should be declared as VARCHAR which support something like [21k characters](https://mariadb.com/kb/en/varchar/) with a utf8 character set

That is not the problem and I should have explained it more.

The problem is that key/indexes like UNIQUE have a limit in size. We are not talking about the limit of a VARCHAR field.

The max **key size** is limited to 3072 bytes in MySQL/MariaDB.

Such a limit exists for PostgreSQL too:
> The maximum length for a value in a B-tree index, which includes primary keys, is one third of the size of a buffer page, by default floor(8192/3) = 2730 bytes.

> That also matches my own testing, I can create a DB with MariaDB and all migrations are applied without issue.

Your screenshot is lacking informations about the character set. If your migrations got applied without issues, your character set is surely not utf8mb4 (4 * 1024 = 4048) but utf8 (3 * 1024 = 3072).

**Comment by homberger** [comment]
To recommend a good solution I need more informations about the columns `filename` and `archive_filename`.
What is stored in these columns? A full path or only the name of the file? Do we really need utf8mb4 (which is recommended) for these columns or is utf8 enough?
Why is their length 1000?
Why do they have a unique index?

**Comment by stumpylog** [comment]
![image](https://user-images.githubusercontent.com/797416/205501788-818af85a-dca4-4d47-a970-8eeca18301f3.png)

![image](https://user-images.githubusercontent.com/797416/205501802-724af4ff-c6dc-4de7-9c13-9342630ad5ac.png)

looks like utf8mb4 to me.

The index is using HASH not BTREE for both.

**Comment by homberger** [comment]
I am just trying to help. 

@stumpylog 
> looks like utf8mb4 to me.

The default character set of your database is utf8mb4 but this does not tell anything about the tables and column which can have different character sets.

Please share the output of the following statement to settle this, please:
```
SHOW CREATE TABLE documents_document;
```

@stumpylog:
> The index is using HASH not BTREE for both.

AFAIK InnoDB doesn't support HASH for indexes, but only BTREE: https://mariadb.com/kb/en/storage-engine-index-types/
Even if you create an index with `USING HASH` it will still be an index of type BTREE. 
If a newer version of MariaDB is supporting indexes of type HASH (not talking about addaptive hash indexes which are built on top of a BTREE), I am not aware of it. I would be very happy if they'd be supported by InnoDB. They would be a great solution to this issue.

**Comment by stumpylog** [comment]
Everything there seems to checkout as utf8mb4 as well:
![image](https://user-images.githubusercontent.com/797416/205524178-f7e9c626-80d3-4f77-817f-8db806361131.png)

This is whatever version `image: mariadb:10` is pulling in for me

**Comment by homberger** [comment]
That's odd.

If I  try to create the table with this statement:
```
CREATE TABLE `documents_document` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(128) NOT NULL,
  `content` longtext NOT NULL,
  `created` datetime(6) NOT NULL,
  `modified` datetime(6) NOT NULL,
  `correspondent_id` int(11) DEFAULT NULL,
  `checksum` varchar(32) NOT NULL,
  `added` datetime(6) NOT NULL,
  `storage_type` varchar(11) NOT NULL,
  `filename` varchar(1024) DEFAULT NULL,
  `archive_serial_number` int(11) DEFAULT NULL,
  `document_type_id` int(11) DEFAULT NULL,
  `mime_type` varchar(256) NOT NULL,
  `archive_checksum` varchar(32) DEFAULT NULL,
  `archive_filename` varchar(1024) DEFAULT NULL,
  `storage_path_id` int(11) DEFAULT NULL,
  `original_filename` varchar(1024) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `documents_document_checksum_75209391_uniq` (`checksum`),
  UNIQUE KEY `archive_serial_number` (`archive_serial_number`),
  UNIQUE KEY `documents_document_filename_3ee5ad97_uniq` (`filename`),
  UNIQUE KEY `archive_filename` (`archive_filename`) USING HASH,
  UNIQUE KEY `filename` (`archive_filename`) USING HASH,
  KEY `documents_document_title_6b08e02a` (`title`),
  KEY `documents_document_correspondent_id_6164eb0c_fk_documents` (`correspondent_id`),
  KEY `documents_document_created_bedd0818` (`created`),
  KEY `documents_document_modified_2eae15bc` (`modified`),
  KEY `documents_document_added_28cfa360` (`added`),
  KEY `documents_document_document_type_id_1f88b50c_fk_documents` (`document_type_id`),
  KEY `documents_document_storage_path_id_07d27bdb_fk_documents` (`storage_path_id`),
  CONSTRAINT `documents_document_correspondent_id_6164eb0c_fk_documents` FOREIGN KEY (`correspondent_id`) REFERENCES `documents_correspondent` (`id`),
  CONSTRAINT `documents_document_document_type_id_1f88b50c_fk_documents` FOREIGN KEY (`document_type_id`) REFERENCES `documents_documenttype` (`id`),
  CONSTRAINT `documents_document_storage_path_id_07d27bdb_fk_documents` FOREIGN KEY (`storage_path_id`) REFERENCES `documents_storagepath` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

I get this error:
```
#1071 - Specified key was too long; max key length is 3072 bytes
```

Maybe my version of MariaDB really is too old? I can't find any informations about InnoDB now supporting index type HASH.

Server-Version: 10.3.37-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04

**Comment by homberger** [comment]
Or maybe: in newer versions of MariaDB you are allowed to create indexes of type HASH (no errors), but it the index can/will not be used.

Google pointed me to a comment that is indicating something like this:
https://jira.mariadb.org/browse/MDEV-20918?focusedCommentId=136648&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-136648

> InnoDB doesn't support hash indexes for simple tables, but:
> Seems like 10.0 and 10.4 work differently with ` INDEX `name` (`col`) USING HASH` statement.
> 
> Maria10.0.17 will ignore this option and create BTREE index.
> INFORMATION_SCHEMA.STATISTICS -> INDEX_TYPE will be BTREE.
> only in SHOW CREATE TABLE we can see `by hash` option
> 
> Maria10.4.7 will try to create HASH index.
> INFORMATION_SCHEMA.STATISTICS -> INDEX_TYPE will be HASH and CARDINALITY will be NULL.
> in SHOW CREATE TABLE will be `by hash` option.
> We will receive no errors after creating this index, but he will block any alter algorithms exept `COPY`. And this index will never be used by maria for optimization your queries
> 
> Its not really bug, but it can cause problems after migration from 10.0 to 10.4

**Comment by stumpylog** [comment]
That's really weird.  I can drop back to that version (10.3.37) with the magic of Docker and while the migration is applied without issue, it doesn't use utf8mb4 but latin1

**Comment by stumpylog** [comment]
I'm not sure.
```
MariaDB [paperless]> EXPLAIN SELECT archive_filename FROM documents_document WHERE archive_filename = '0000001.pdf';
+------+-------------+--------------------+-------+------------------+------------------+---------+-------+------+-------------+
| id   | select_type | table              | type  | possible_keys    | key              | key_len | ref   | rows | Extra       |
+------+-------------+--------------------+-------+------------------+------------------+---------+-------+------+-------------+
|    1 | SIMPLE      | documents_document | const | archive_filename | archive_filename | 1027    | const |    1 | Using index |
+------+-------------+--------------------+-------+------------------+------------------+---------+-------+------+-------------+
1 row in set (0.001 sec)

MariaDB [paperless]> ANALYZE SELECT archive_filename FROM documents_document WHERE archive_filename = '0000001.pdf';
+------+-------------+--------------------+-------+------------------+------------------+---------+-------+------+--------+----------+------------+-------------+
| id   | select_type | table              | type  | possible_keys    | key              | key_len | ref   | rows | r_rows | filtered | r_filtered | Extra       |
+------+-------------+--------------------+-------+------------------+------------------+---------+-------+------+--------+----------+------------+-------------+
|    1 | SIMPLE      | documents_document | const | archive_filename | archive_filename | 1027    | const |    1 |   NULL |   100.00 |       NULL | Using index |
+------+-------------+--------------------+-------+------------------+------------------+---------+-------+------+--------+----------+------------+-------------+
1 row in set (0.001 sec)
```

**Comment by Pakbon** [comment]
Just read through this thread, as I was referred to it by an issue I made. 
My database was created with character set utf8mb4, in which case the migration script fails as mentioned before. 
However it **does** work if set to utf8 (mb3)

So I think it's a good idea to mention in the documents to `CREATE DATABASE paperless CHARACTER SET utf8mb3`
