### ISSUE TITLE
re-OCR doesnt work

### ISSUE THREAD

**Issue by Gurkenmus** [paperless-ngx/paperless-ngx#2099]
### Description

I have Documents in Paperless, where i want to have a new OCR. But the task doesnt do anything new on OCR. Would be nice if this clears the Document and scans for new OCR

If i scan the document again without OCR, then it does the OCR correct. But not, if the Document has already OCR.

### Steps to reproduce

1. go to document
2. "OCR wiederholen"

### Webserver logs

```bash
?
```

### Paperless-ngx version

1.10.0

### Host OS

Synology

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
Without any logs, this isn't something actionable. 

 It almost sounds like you're looking for the ocr mode setting to replace any existing ocr, which is a separate setting to configure.

**Comment by shamoon** [comment]
Yea I’m not aware of any issue here so if there truly is we need more info. After you initiate the redo you should see logs something like

```
[2022-12-03 08:02:19,480] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/media/documents/originals/…
[2022-12-03 08:02:19,560] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args
…
```

**Comment by Gurkenmus** [comment]
> Without any logs, this isn't something actionable.
> 
> It almost sounds like you're looking for the ocr mode setting to replace any existing ocr, which is a separate setting to configure.

But isnt this setting then for ALL new documents? I only want to do ne ocr by starting the task for one document. Not for all new documents.

**Comment by Gurkenmus** [comment]
> Yea I’m not aware of any issue here so if there truly is we need more info. After you initiate the redo you should see logs something like
> 
> ```
> [2022-12-03 08:02:19,480] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/media/documents/originals/…
> [2022-12-03 08:02:19,560] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args
> …
> ```

Where can i find this logs? I try to get them, when i am back home.

**Comment by shamoon** [comment]
There’s a link in the sidebar, or the docker logs

**Comment by stumpylog** [comment]
There is no option to change the OCR mode for a single document.  It will use the global setting.

**Comment by Gurkenmus** [comment]
> There is no option to change the OCR mode for a single document. It will use the global setting.

But for what is the following action if not to generate a full new ocr? Thats why i thought its a bug.
![Screenshot_2022-12-03-19-36-35-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/64144734/205456551-36553f3e-6675-4450-a654-e48e63e98c93.jpg)

As a user i would think this deletes the actual ocr and generating a new one.
