### ISSUE TITLE
[BUG] table documents_paperlesstask has no column named task_file_name

### ISSUE THREAD

**Issue by m8522s** [paperless-ngx/paperless-ngx#2107]
### Description

After an update from 1.9.2 to 1.10.0 I frequently see log messages, which relate to a missing column in the database:
```
Dec 03 20:42:46 paperless gunicorn[68630]: django.db.utils.OperationalError: no such column: documents_paperlesstask.task_file_name
[2022-12-03 20:40:53,288] [ERROR] [paperless.handlers] Creating PaperlessTask failed: table documents_paperlesstask has no column named task_file_name
```
My installation uses SQLite. Is there an SQLite update script, that I might have missed?

### Steps to reproduce

Import a new PDF file or restart the `paperless-consumer` service.

### Webserver logs

```bash
The issue happens even when not accessing the web UI.
```

### Paperless-ngx version

1.10.0

### Host OS

Debian 11.5

### Installation method

Bare metal

### Browser

Firefox 107.0.1

**Comment by shamoon** [comment]
`python3 manage.py migrate` https://docs.paperless-ngx.com/administration/#bare-metal-route step 3
