### ISSUE TITLE
[BUG] service definition for taskqueue and scheduler / bare metal documentation

### ISSUE THREAD

**Issue by bmml1** [paperless-ngx/paperless-ngx#2113]
### Description

Hello,

I think the service files for the taskqueue and scheduler need to be pointed to something like:

`ExecStart=/opt/paperless/.local/bin/celery --app paperless worker --loglevel INFO
`
instead of 
`ExecStart=celery --app paperless worker --loglevel INFO`

like in the webserver service file. 

Also it would be nice to have a similiar hint in the documentation same as for the gunicorn bin 

![image](https://user-images.githubusercontent.com/32018487/205509481-a68220c6-629f-4eb6-8398-d0c9f350c506.png)

BR

### Steps to reproduce

1. install via bare metal instruction
2. try to start schedule and task-queue service via example files in /scripts/

### Webserver logs

```bash
not webserver related
```

### Paperless-ngx version

latest

### Host OS

ubuntu 20.04

### Installation method

Bare metal

**Comment by stumpylog** [comment]
If `celery` is installed for the user `paperless` I would expect to see it on the path for that user.  is it not?

**Comment by bmml1** [comment]
Yes I tried again and it worked.
