### ISSUE TITLE
Unable to open paperless-ngx from LAN IP.

### ISSUE THREAD

**Issue by apoorv569** [paperless-ngx/paperless-ngx#2127]
### Description

I am not able to access `paperless-ngx` from the `LAN` `IP` of the `paperless-ngx` server, I keep getting error mentioned below under `"Webserver logs"`.

`docs.homeserver.lan` is a local domain I set in `pi-hole`, it only works on my LAN.

I have tried changing and adding my IP and local domain using these variables,
```
- PAPERLESS_URL
- PAPERLESS_CSRF_TRUSTED_ORIGINS
- PAPERLESS_ALLOWED_HOSTS
- PAPERLESS_CORS_ALLOWED_HOSTS
```

but none of these helps solve the issue. I can only access the service via my external domain which I purchased recently.

### Steps to reproduce

1. Change various variables mentioned above
2. Try to access `paperless-ngx` via local IP

### Webserver logs

```bash
[2022-12-05 23:46:09,575] [ERROR] [django.security.DisallowedHost] Invalid HTTP_HOST header: 'docs.homeserver.lan'. You may need to add 'docs.homeserver.lan' to ALLOWED_HOSTS.
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
webserver_1  |     response = get_response(request)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
webserver_1  |     response = self.process_request(request)
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
webserver_1  |     host = request.get_host()
webserver_1  |   File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
webserver_1  |     raise DisallowedHost(msg)
webserver_1  | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'docs.homeserver.lan'. You may need to add 'docs.homeserver.lan' to ALLOWED_HOSTS.
webserver_1  | [2022-12-05 23:46:09,591] [WARNING] [django.request] Bad Request: /
```
```


### Browser logs

_No response_

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 22.04 LTS

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_

**Comment by shamoon** [comment]
Are you recreating the container after setting those? And you didnt really specify how. These settings essentially come from Django so it sure seems like theyre not set correctly, since the error says that hostname isnt there.

Btw, you say accessing by IP but looks like youre using a hostname (which is fine, just unclear)

**Comment by apoorv569** [comment]
> Are you recreating the container after setting those? And you didnt really specify how. These settings essentially come from Django so it sure seems like theyre not set correctly, since the error says that hostname isnt there.
> 
> Btw, you say accessing by IP but looks like youre using a hostname (which is fine, just unclear)

I have setup everything before creating the container.

Yes, they are local domains not really hostname, pi-hole has a section to create those, but anyways, I also tried with IP which also doesn't work.

**Comment by shamoon** [comment]
Again, might be helpful to see what you've tried but the error certainly suggests you havent actually passed in `docs.homeserver.lan`. There is more than one way to achieve this because `PAPERLESS_URL` is like an 'alias' for the others but if you want it to be accessible with multiple hostnames you'll need to specify them all.

**Comment by shamoon** [comment]
That’s why I was asking. You’re supplying URLs but `PAPERLESS_ALLOWED_HOSTS` takes a list of FQDN eg `docs.homeserver.lan` or you can use wildcards see https://docs.paperless-ngx.com/configuration/#hosting-and-security https://docs.djangoproject.com/en/4.1/ref/settings/

**Comment by apoorv569** [comment]
> That’s why I was asking. You’re supplying URLs but `PAPERLESS_ALLOWED_HOSTS` takes a list of FQDN eg `docs.homeserver.lan` or you can use wildcards see https://docs.paperless-ngx.com/configuration/#hosting-and-security https://docs.djangoproject.com/en/4.1/ref/settings/

So remove `http` and `https` you mean?
