### ISSUE TITLE
[BUG] service definition for taskqueue and scheduler / bare metal

### ISSUE THREAD

**Issue by Bloodpack** [paperless-ngx/paperless-ngx#2133]
### Description

i have the same probleme as here https://github.com/paperless-ngx/paperless-ngx/issues/2113#issue-1475085224

the service files as defined for task-queue and scheduler don´t work for me

`ExecStart=celery --app paperless worker --loglevel INFO`

if i change the files to this it works

```
[Unit]
Description=Paperless Celery Workers
Requires=redis.service

[Service]
User=paperless
Group=paperless
WorkingDirectory=/opt/paperless-ngx/src
ExecStart=/opt/paperless-ngx/.local/bin/celery --app paperless worker --loglevel INFO


[Install]
WantedBy=multi-user.target
```

### Steps to reproduce

1. install via bare metal instruction
2. try to start schedule and task-queue service via example files in /scripts/

### Webserver logs

```bash
root@paperless:/etc/systemd/system# systemctl status paperless-scheduler.service
× paperless-scheduler.service - Paperless Celery Beat
     Loaded: loaded (/etc/systemd/system/paperless-scheduler.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-12-06 13:04:21 CET; 35s ago
    Process: 55212 ExecStart=celery --app paperless beat --loglevel INFO (code=exited, status=203/EXEC)
   Main PID: 55212 (code=exited, status=203/EXEC)
        CPU: 3ms

Dez 06 13:04:21 paperless systemd[1]: Started Paperless Celery Beat.
Dez 06 13:04:21 paperless systemd[55212]: paperless-scheduler.service: Failed to locate executable celery: No such file or directory
Dez 06 13:04:21 paperless systemd[55212]: paperless-scheduler.service: Failed at step EXEC spawning celery: No such file or directory
Dez 06 13:04:21 paperless systemd[1]: paperless-scheduler.service: Main process exited, code=exited, status=203/EXEC
Dez 06 13:04:21 paperless systemd[1]: paperless-scheduler.service: Failed with result 'exit-code'.


and


root@paperless:/etc/systemd/system# systemctl status paperless-task-queue.service
× paperless-task-queue.service - Paperless Celery Workers
     Loaded: loaded (/etc/systemd/system/paperless-task-queue.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-12-06 13:04:35 CET; 1min 1s ago
    Process: 55353 ExecStart=celery --app paperless worker --loglevel INFO (code=exited, status=203/EXEC)
   Main PID: 55353 (code=exited, status=203/EXEC)
        CPU: 3ms

Dez 06 13:04:35 paperless systemd[1]: Started Paperless Celery Workers.
Dez 06 13:04:35 paperless systemd[55353]: paperless-task-queue.service: Failed to locate executable celery: No such file or directory
Dez 06 13:04:35 paperless systemd[55353]: paperless-task-queue.service: Failed at step EXEC spawning celery: No such file or directory
Dez 06 13:04:35 paperless systemd[1]: paperless-task-queue.service: Main process exited, code=exited, status=203/EXEC
Dez 06 13:04:35 paperless systemd[1]: paperless-task-queue.service: Failed with result 'exit-code'.
```

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

### Configuration changes

my install is located in: 

/opt/paperless-ngx

**Comment by shamoon** [comment]
The first comment in that other issue still applies here:

> If `celery` is installed for the user `paperless` I would expect to see it on the path for that user. is it not?

**Comment by Bloodpack** [comment]
I installed paperless ngx exactly from the manual version 1.9.2 and it worked till the update to 1.10.2

In the update process i installed the requirements from the requirements.txt with this command.

`sudo -Hu paperless pip3 install -r requirements.txt`

So from my understanding it should be installed under the paperless user.

Maybe i am wrong ( linux noob here)

If you need specific logs or something i am happy to provide but i am not home at the moment.

**Comment by amo13** [comment]
This looks a lot like an issue with your setup and not with the suggested systemd service file.

You could try `sudo -u paperless which celery` and compare the path to your celery executable with the paths included in your $PATH env variable (`echo $PATH`).

Keep in mind that bare metal installation instructions should vary a bit depending on your actual system/distro/setup.

**Comment by shamoon** [comment]
Yes, in the .9 to .10 we transitioned to the new task manager `celery`, as above notes its likely just an issue with the `$PATH`
