### ISSUE TITLE
[BUG] mail importer processes all mails everytime - not obeying tag

### ISSUE THREAD

**Issue by hokascha** [paperless-ngx/paperless-ngx#2145]
### Description

The mail import logs shows all mails in the imap account are being processed at every run. The email rule is configured to tag emails and process untagged.

### Steps to reproduce

1. configure email rule to tag emails and process untagged
2. watch the protocol

### Webserver logs

```bash
[2022-12-07 20:52:43,491] [DEBUG] [paperless_mail] Rule xxx.xxx: Processed 1162 matching mail(s)
[2022-12-07 21:02:01,599] [DEBUG] [paperless_mail] Rule xxx.xxx: Processed 1162 matching mail(s)
```

### Paperless-ngx version

1.10.0

### Host OS

Raspberry Pi 4, docker

### Installation method

Docker - official image

### Other

IMAP server is dovecot.

**Comment by shamoon** [comment]
I think you need to provide us more information e.g. about your rule setup, what email service etc.

**Comment by stumpylog** [comment]
Also the debug log lines directly below this would show what action is being taken and against how many messages.

This area hasn't changed in a release recently, so it's surprising if something has broken.

**Comment by stumpylog** [comment]
Yes, that's how it's always been and hasn't changed from paperless-ng.  It's also how the documentation describes the process [here](https://docs.paperless-ngx.com/usage/#usage-email).  

I can't say for certain, but it's probably that way to support multiple rules running against the same account.  So if rule 1 cares about the `From:`, but rule 2 checks the subject, rule 1 shouldn't take an action to flag/delete/move an email it doesn't "own", so to speak, as that may prevent rule 2 from seeing it.

**Comment by hokascha** [comment]
Thinking about this, a simple "mail was processed but no rules matched" flag should do the trick...
