### ISSUE TITLE
[BUG] 1.6.0 Beta Bug

### ISSUE THREAD

**Issue by azapater** [paperless-ngx/paperless-ngx#215]
**Describe the bug**
Editing a document, removing a tag using the delete icon next to it doesn't activate the save button

**To Reproduce**
1. From the main "documents" section, enter editing any document with tags assigned
2. Remove a tag using the specific delete icon to the left of the tag
3. None of the bottom action buttons activate (discard, save & next, save)

**Screenshots**
![image](https://user-images.githubusercontent.com/1220658/156881261-f611020a-e561-40bf-9a99-6c5cbb1b61ef.png)

**Relevant information**
 - I've noticed that if you enter to edit a document and refresh the page, the "save & next" button is not present anymore. After refreshing the page, deleting a tag activates the action buttons and every works as expected.

**Comment by shamoon** [comment]
This one is odd. Any rxjs masters out there, your input is appreciated. Will take a look when I have more time...

**Comment by shamoon** [comment]
Closed in branch
