### ISSUE TITLE
[BUG] Docs markdown issue

### ISSUE THREAD

**Issue by SB97** [paperless-ngx/paperless-ngx#2155]
### Description

https://docs.paperless-ngx.com/administration/#updating

![grafik](https://user-images.githubusercontent.com/20126520/206721118-534a477c-99cd-4502-9736-c2f3cecdeb79.png)

The page isn´t showing the code block correctly

### Steps to reproduce

docs...

### Webserver logs

```bash
docs...
```

### Paperless-ngx version

docs...

### Host OS

docs...

### Installation method

Other (please describe above)

**Comment by shamoon** [comment]
Sorted thanks :)
