### ISSUE TITLE
[BUG] Update dockerImage:1.9.2 -> dockerImage:1.10.0 or dockerImage:1.10.2 runs into "could not create unique index"

### ISSUE THREAD

**Issue by naishweb** [paperless-ngx/paperless-ngx#2158]
### Description

After i upgrade the dockerImage tag, the webserver is not able to start correctly.
I encounter the issue "psycopg2.errors.UniqueViolation: could not create unique index"
I thought it would be possible, that the script fails to use the default values for the database access, so i added them as env vars.
Thinking and trying stuff for days now, hope somebody see my fault faster than me.

Paperless is running on a Synology 1621+, as a stack in portainer.
my compose file is grown from the one from github:

`
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless_redis
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless-ngx/redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless-ngx/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:1.10.0
    container_name: paperless_paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperless-ngx/data:/usr/src/paperless/data
      - /volume1/docker/paperless-ngx/media:/usr/src/paperless/media
      - /volume1/docker/paperless-ngx/transfer/export:/usr/src/paperless/export
      - /volume1/docker/paperless-ngx/transfer/consume:/usr/src/paperless/consume
      - /volume1/Dokumente:/usr/src/paperless/media/documents/originals
    environment:
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: true
      PAPERLESS_TASK_WORKERS: 1
      USERMAP_UID: 1030
      USERMAP_GID: 100
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: initialPasswort
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBENGINE: postgresql
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_FILENAME_FORMAT: "Unbearbeitet/{created_year}{created_month}{created_day} - {title}"
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: True
      PAPERLESS_CONSUMER_RECURSIVE: false
      PAPERLESS_CONSUMER_ENABLE_BARCODES: False
      PAPERLESS_SECRET_KEY: "123456"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    container_name: paperless_gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperless_tika
    restart: unless-stopped
`

### Steps to reproduce

1. Portainer Paperless Stack runs perfectly with paperlessngx/paperless-ngx:1.9.2
2. Change Version in compose file to paperlessngx/paperless-ngx:1.10.0 or paperlessngx/paperless-ngx:1.10.2
3. Deploy Stack
4. View container-log of webservice

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
[nltk_data] Downloading package snowball_data to
[nltk_data]     /usr/src/paperless/data/nltk...
[nltk_data]   Package snowball_data is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /usr/src/paperless/data/nltk...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /usr/src/paperless/data/nltk...
[nltk_data]   Package punkt is already up-to-date!
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: could not create unique index "documents_paperlesstask_task_id_24b393f9_uniq"
DETAIL:  Key (task_id)=(0199ac53fc38443fb20e3801f1669ae0) is duplicated.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    self._alter_field(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 246, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 1045, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field]))
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: could not create unique index "documents_paperlesstask_task_id_24b393f9_uniq"
DETAIL:  Key (task_id)=(0199ac53fc38443fb20e3801f1669ae0) is duplicated.
  Applying documents.1027_remove_paperlesstask_attempted_task_and_more...
```

### Paperless-ngx version

1.9.2, 1.10.0

### Host OS

Linux data 4.4.180+ #42962 SMP Tue Oct 18 15:02:09 CST 2022 x86_64 GNU/Linux synology_v1000_1621+

### Installation method

Docker - official image

### Configuration changes

swappen Tag from 1.9.2 to any 1.10.x

### Other

Also tried to upgrade webservice & gotenberg in one step.

**Comment by shamoon** [comment]
Oddly it looks like you have a duplicate in your db. Try deleting the `paperlesstask` with `task_id` 0199ac53fc38443fb20e3801f1669ae0 or frankly you can safely remove them all

**Comment by stumpylog** [comment]
It appears you've gotten a UUID from django_q which wasn't actually unique, but the migration is enforcing now uniqueness.

Unfortunately, you'll need to manually fix this for the moment.  It will only remove a task, but we always suggest backups.

1. Access your database container `docker exec -it <yourdbname> /bin/bash`)
2. Access your database: `psql --user paperless`
3. `DELETE FROM documents_paperlesstask WHERE task_id = '0199ac53fc38443fb20e3801f1669ae0';`

That should return `DELETE 2` or more than 2.  Just not 1.

**Comment by shamoon** [comment]
Could they remove from the Django admin too no? (I dont remember if those showed up there)

**Comment by stumpylog** [comment]
No, we didn't create anything in the admin pages for the PaperlessTask

**Comment by naishweb** [comment]
After I executed the psql stement he promted that he deleted 2 entries.
started the webservice again, same issue different task_id, repeated delete statement.
deleted 25 task_ids meanwhile. seems that there is no end.

**Comment by shamoon** [comment]
As I mentioned before you can safely delete them all

**Comment by naishweb** [comment]
OK, did Truncate the whole table (TRUNCATE documents_paperlesstask;)
Problem is solved.
