### ISSUE TITLE
[BUG] Changing the Document Title works not properly 

### ISSUE THREAD

**Issue by wiphi** [paperless-ngx/paperless-ngx#216]
At first thank you for this awesome community-project. I will contribute by testing new releases. 

**Describe the bug**
When I edit the title of a document, some letters disapers while typing and the cursor jumps very often to the right by navigating with the arrow keys on the keyboard.

**To Reproduce**
* Edit a Document and change the title. Change more than 4 or 5 letters.
* Some new title letters disapers while editing the title.
* Reproduced in latest Firefox and MS Edge

**Expected behavior**
The title can be edit without missing letters.

**Screenshots**
I can make a quick video from this, but the bug is very obvious.

**Webserver logs**
```
It's a frontend bug.
```

**Relevant information**
 - Host OS of the machine running paperless: [e.g. Debian, OVM5]
 - Browser Firefox, Edge
 - Version 1.6.0-beta
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: Official beta Image.

**Comment by shamoon** [comment]
I think I have a fix for this already

**Comment by shamoon** [comment]
Closed in branch
