### ISSUE TITLE
[BUG] Not Found Exception despite document being present

### ISSUE THREAD

**Issue by Tooa** [paperless-ngx/paperless-ngx#2161]
### Description

The document sanity checker reports some documents missing despite them being available on disk. Debugging the issue shows that the document name in the database matches the one on the disk. I suspect the umlaut character in the document name to cause issues, but have no proof ATM. Find additional debug information below.

### Steps to reproduce

1. Login to paperless-ngx
2. Visit document URL https://paperless.home.arpa/documents/435

### Webserver logs

```bash
[2022-12-10 15:45:38,714] [INFO] [paperless.sanity_checker] Detected following issue(s) with document #435, titled bankdatenänderung-2022-03-09t00_00_00.000z
[2022-12-10 15:45:38,716] [ERROR] [paperless.sanity_checker] Original of document does not exist.
[2022-12-10 15:45:38,717] [ERROR] [paperless.sanity_checker] Archived version of document does not exist.

[...]
[2022-12-10 16:01:21,210] [WARNING] [django.request] Not Found: /api/documents/435/preview/
```

### Browser logs

```bash
GET https://paperless.home.arpa/api/documents/435/preview/ [HTTP/2 404 Not Found 14ms]
```

### Paperless-ngx version

1.10.2

### Host OS

Unraid (Slackware 15)

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes
```ini
PAPERLESS_FILENAME_FORMAT={created}-{correspondent}-{title}
PAPERLESS_URL=https://paperless.home.arpa
```

### Other

I can find the document on disk:

```bash
root@server:/mnt/user/paperless-ng/media/documents/originals# ls | grep "2022-03-09"
2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf
```

The UI shows the following attributes for the document:

* Title: bankdatenänderung-2022-03-09t00_00_00.000z
* Date Created: 09.03.2022
* Correspondent: gasag

The database entry for the document is as follows:

```csv
id,title,content,created,modified,correspondent_id,checksum,added,storage_type,filename,archive_serial_number,document_type_id,mime_type,archive_checksum,archive_filename,storage_path_id,original_filename
435,bankdatenänderung-2022-03-09t00_00_00.000z,"<content-redacted>",2022-03-08 23:00:00,2022-03-12 06:37:18.937456,14,80361e31e1269a638d38423e5e709d41,2022-03-12 06:37:18.768407,unencrypted,2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf,,,application/pdf,311b10cb2baba343fd567052a96550aa,2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf,,
```

**Comment by stumpylog** [comment]
The umlaut looks present everywhere it should be, namely the database and the error message, so it doesn't appear to be lost, which is good.

If you enter the container and check for the file, is the umlaut present there?

**Comment by Tooa** [comment]
> If you enter the container and check for the file, is the umlaut present there?

Looks fine:

```bash
root@1ac280d20b40:/usr/src/paperless/media/documents/originals# ls | grep "2022-03-09"
2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf
````

**Comment by stumpylog** [comment]
I've changed a title to include an umlaut (named from your actually) and it appears to be in the correct location and the sanity checker doesn't complain about it missing either.  I could see how including the expected path in the message would be helpful.  The only way to check now is by examining the database for pk 435.

Combined with the 404 error, I think the document isn't where it should be or the OS is saying it isn't a file.

**Comment by Tooa** [comment]
> I could see how including the expected path in the message would be helpful. The only way to check now is by examining the database for pk 435
 
Yes that sounds like a good idea

> Combined with the 404 error, I think the document isn't where it should be or the OS is saying it isn't a file.

Unfortunately, I can open the file `2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf` fine in Firefox's build-in PDF viewer (without password!). I also checked the Linux `file` command output and initially it looked suspicious to me:

```bash
# Command 'file' from inside the container
root@1ac280d20b40:/usr/src/paperless/media/documents/originals# file 2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf
2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf: PDF document, version 1.4 (password protected)

# Command 'file' from the hosts filesystem
file /mnt/user/paperless-ng/media/documents/originals/2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf
/mnt/user/paperless-ng/media/documents/originals/2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf: PDF document, version 1.4, 4 pages (zip deflate encoded)
```

However, I couldn't make a similar observation for other documents in my paperless-ngx instance that are reported missing too:

```bash
# Yields Not Found
https://paperless.home.arpa/documents/436

root@1ac280d20b40:/usr/src/paperless/media/documents/originals# file 2021-12-31-finanzamt-Erträgnisaufstellung_20220308.pdf
2021-12-31-finanzamt-Erträgnisaufstellung_20220308.pdf: PDF document, version 1.2

root@server:~ file /mnt/user/paperless-ng/media/documents/originals/2021-12-31-finanzamt-Erträgnisaufstellung_20220308.pdf         
/mnt/user/paperless-ng/media/documents/originals/2021-12-31-finanzamt-Erträgnisaufstellung_20220308.pdf: PDF document, version 1.2, 7 pages

# Database entry
id,title,content,created,modified,correspondent_id,checksum,added,storage_type,filename,archive_serial_number,document_type_id,mime_type,archive_checksum,archive_filename,storage_path_id,original_filename
436,Erträgnisaufstellung_20220308,"<redacted>",2021-12-30 23:00:00,2022-03-12 06:37:25.312070,20,3a3c66bdc3d12ab6140d5a7f7f7278ac,2022-03-12 06:37:25.139814,unencrypted,2021-12-31-finanzamt-Erträgnisaufstellung_20220308.pdf,,,application/pdf,1deb54cde87b1af63cbd1ae71dda088c,2021-12-31-finanzamt-Erträgnisaufstellung_20220308.pdf,,
```

**Comment by stumpylog** [comment]
If I copy what you put from the DB for 435, and the filepath you opened, although they look the same, the umlaut character is reported as different in Beyond Compare.  This is SQLite?

**Comment by Tooa** [comment]
>  This is SQLite

Yes.

**Comment by stumpylog** [comment]
Thanks, I was using Postgres in my default debugging environment.  I'll try with SQLite next.  Not sure we get a lot of control over things like how it stores characters, but maybe.

**Comment by Tooa** [comment]
So, in conclusion the problem may occur when a document uses a homoglyph ([confusables.txt](https://www.unicode.org/Public/security/8.0.0/confusables.txt), [confusablesSummary.txt](https://www.unicode.org/Public/security/8.0.0/confusablesSummary.txt)) in its title and paperless-ngx utilizes SQLite as storage backend. From your answer I conclude that the problem does not occur with PostgreSQL. 

As you suggest, we can look into solving the problem with SQLite build-in features. From experience, I am not optimistic about that. On the other hand, I kind of dislike maintaining a SQLite-only code quirk to make this work. 

We may also look into normalizing confusable characters (Punycode, IDNA, ...) or warn about them when being detected in filenames. But again, this falls into creating a quirk for SQLite instances.

I come to realize why a lot of self-hosted applications drop SQLite support in the long term.

**Comment by Tooa** [comment]
> If you re-save one of these documents, to rebuild the filename, does the sanity checker work then?

The sanity checker still reports the document, after changing the title in the UI via "https://paperless.home.arpa/documents/435" to use `U+00E4`. 

This is the updated database row:
```
id,title,content,created,modified,correspondent_id,checksum,added,storage_type,filename,archive_serial_number,document_type_id,mime_type,archive_checksum,archive_filename,storage_path_id,original_filename
435,bankdatenänderung-2022-03-09t00_00_00.000z,"<redacted>",2022-03-08 23:00:00,2022-12-11 16:34:13.473946,14,80361e31e1269a638d38423e5e709d41,2022-03-12 06:37:18.768407,unencrypted,2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf,,,application/pdf,311b10cb2baba343fd567052a96550aa,2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf,,
```

- The title field now uses `U+00E4`. Before the update it used `U+0061 U+0308`
- The filename still uses `U+0061 U+0308`

The sanity checker uses `U+00E4` as well:
```bash
root@dd84bf33f814:/usr/src/paperless/src# document_sanity_checker
100%|██████████████████████████████████████████████████████████████████████████████████████████| 507/507 [00:01<00:00, 322.13it/s]
[2022-12-11 17:39:34,190] [INFO] [paperless.sanity_checker] Detected following issue(s) with document #435, titled bankdatenänderung-2022-03-09t00_00_00.000z
[2022-12-11 17:55:38,041] [ERROR] [paperless.sanity_checker] Original of document does not exist.
[2022-12-11 17:55:38,041] [ERROR] [paperless.sanity_checker] Archived version of document does not exist.
[...]
```

The document on disk from within the container uses `U+00E4` as well:

```bash
root@dd84bf33f814:/usr/src/paperless/media/documents/originals# ls | grep "bankdatenänderung"
2022-03-09-gasag-bankdatenänderung-2022-03-09t00_00_00.000z.pdf
```

Did you want me to delete the existing document and re-import it?
