### ISSUE TITLE
[Other] Changelog not updated.

### ISSUE THREAD

**Issue by sUyMur** [paperless-ngx/paperless-ngx#218]
The [changelog-link](https://paperless-ngx.readthedocs.io/en/latest/changelog.html) is working but only shows version 1.5.0 under latest. 1.6.0 is not an option to choose from.

**Comment by isigmund** [comment]
I believe it will show up in the docs aster 1.6.0 is released ( currently it's in beta). In the meantime you can find the changeless in #216

**Comment by sUyMur** [comment]
Fair point, I guess the notification isn't 100% correct:

> [Paperless-ngx 1.6.0-rc1](https://github.com/paperless-ngx/paperless-ngx/releases/tag/ngx-1.6.0-rc1)
> Repository: [paperless-ngx/paperless-ngx](https://github.com/paperless-ngx/paperless-ngx) · Tag: [ngx-1.6.0-rc1](https://github.com/paperless-ngx/paperless-ngx/tree/ngx-1.6.0-rc1) · Commit: [77cc7ce](https://github.com/paperless-ngx/paperless-ngx/commit/77cc7cebf9c3f7c5a4325e812bf4b4cf745264d0) · Released by: [github-actions[bot]](https://github.com/apps/github-actions)
> For a **complete list of changes, see the changelog at https://paperless-ngx.readthedocs.io/en/latest/changelog.html.**

Sure, it's tagged as RC1, but I was very happy to get a notification that a new release 1.6.0 of paperless-ngx was ready! :-)

**Comment by qcasey** [comment]
Ah yes that's true, thanks for pointing that out.

I manually updated the changelog URL for this prerelease, it should be set correctly as of https://github.com/paperless-ngx/paperless-ngx/commit/1d67c323515ae3b8c9d6d86e50c0bfc780013ba1
