### ISSUE TITLE
[BUG] Loading saved views throws error in browser

### ISSUE THREAD

**Issue by astubenbord** [paperless-ngx/paperless-ngx#2196]
### Description

When trying to select a saved view from the documents view, (i.e. click "View" in the top right and select a view), I get the following error in the console:
```
ERROR TypeError: R(...).loadViewConfig is not a function
```

### Steps to reproduce

1. Go to documents page
2. Select "View" dropdown in top right corner
3. Select an arbitrary view

### Webserver logs

```bash
No unexpected messages
```

### Browser logs

```bash
ERROR TypeError: R(...).loadViewConfig is not a function
    at main.js:3:839373
    at NS (main.js:3:78552)
    at r (main.js:3:78690)
    at HTMLButtonElement.<anonymous> (main.js:3:184529)
    at v.invokeTask (polyfills.js:1:7195)
    at Object.onInvokeTask (main.js:3:117302)
    at v.invokeTask (polyfills.js:1:7116)
    at M.runTask (polyfills.js:1:2590)
    at m.invokeTask [as invoke] (polyfills.js:1:8246)
    at Z (polyfills.js:1:20861)
```

### Paperless-ngx version

1.9.2

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Im not aware of any issues like this in v1.9.2, please update to the latest one or theres something wrong with this saved view. Did you create it from the frontend?

**Comment by astubenbord** [comment]
Yes I did. I will update to 1.10 and see if this fixes the issue.

**Comment by astubenbord** [comment]
Resolved with updating, will close. 

Thanks!
