### ISSUE TITLE
[BUG] Upload progress on startpage will be not updated

### ISSUE THREAD

**Issue by wiphi** [paperless-ngx/paperless-ngx#220]
**Describe the bug**
After a upload via webinterface the document upload progress will be updated. The document is uploaded sucessfully. Only the frontend upload progress is not updated.

**To Reproduce**
1. Upload an document, for example a pdf file, via the webinterface on the startpage
2. The document will be uploaded successfull, but the progess is not updated.

**Expected behavior**
The upload screen will be updated.

**Screenshots**
<img width="188" alt="2022-03-06 11_12_29-Startseite - Paperless-ngx – Microsoft​ Edge" src="https://user-images.githubusercontent.com/25878910/156918912-3ec58178-a3ab-4b04-87c6-51078c51e2cc.png">

**Webserver logs**
```
If available, post any logs from the web server related to your issue.
```

**Relevant information**
 - Host OS of the machine running paperless: Debian on Docker / OVM5
 - Browser Edge
 - Version 1.6.0-beta
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

**Comment by shamoon** [comment]
Did you check your browser logs? Most often I have seen this be an issue when running behind a reverse proxy. I dont have edge to test, but dont think this is actually broken (video

https://user-images.githubusercontent.com/4887959/156928727-34624727-0b47-417e-b591-7b595d5257ef.mov

)

**Comment by Mr-N1ce** [comment]
Hi,

I have the exact same issue as wiphi if I access paperless-ng through a reverse proxy.
If I access it with IP:PORT it is working as expected.

shamoon, did you test it with a reverse proxy?

- Host OS of the machine running paperless: Debian
- Browser Firefox and Vivaldi
- Version Paperless-ng 1.5.0
- Installation method: docker

**Comment by wiphi** [comment]
Interesting.
I use Traefik. In version 1.5.0 I don't had any problems. 
My server is today not running. I can do more investigation in the course of this week.

**Comment by shamoon** [comment]
I also use traefik, no issues on 1.5.0 or 1.6.0

**Comment by wiphi** [comment]
> I also use traefik, no issues on 1.5.0 or 1.6.0

Do you use a folder-url like `myserver/paperless`?

**Comment by shamoon** [comment]
No I dont, I use subdomain. I see a lot of issues with subdirectories (not in paperless I mean in other traefik deployments with other software etc), might be related to that

**Comment by wiphi** [comment]
Hmm it seems like a websocket problem:
```
main.js:3 
        
       WebSocket connection to 'ws://nas-home/paperless/ws/status/' failed: Error during WebSocket handshake: Unexpected response code: 500
connect @ main.js:3
ngOnInit @ main.js:3
fO @ main.js:3
R0 @ main.js:3
Wf @ main.js:3
vu @ main.js:3
IP @ main.js:3
z_ @ main.js:3
bb @ main.js:3
detectChanges @ main.js:3
tick @ main.js:3
_loadComponent @ main.js:3
bootstrap @ main.js:3
(anonym) @ main.js:3
_moduleDoBootstrap @ main.js:3
(anonym) @ main.js:3
invoke @ polyfills.js:1
onInvoke @ main.js:3
invoke @ polyfills.js:1
run @ polyfills.js:1
(anonym) @ polyfills.js:1
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:3
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
_ @ polyfills.js:1

```
Maybe I have to configure something in my reverse proxy? The URI in the log is correct: My paperless instance on a sub-url.

**Comment by wiphi** [comment]
I found the point in the documentation:
https://paperless-ngx.readthedocs.io/en/latest/setup.html?highlight=reverse#using-nginx-as-a-reverse-proxy

P.S.: I thinked I used traefik but I switched a long time ago to nginx-proxy-manager and added now the configuration to my location. Now we will see if this works. Thanks for your support. I will close this issue now, because it's not a bug.

**Comment by shamoon** [comment]
I didnt explicitly need to set anything with traefik, if youre accessing the app via https you need the ws to be the wss, e.g. mine connects to `wss://paperless.domain.com/ws/status/`

Feel free to continue discussing but I'm closing this as Im confident its a configuration issue

**Comment by cupracer** [comment]
> P.S.: I thinked I used traefik but **I switched** a long time ago **to nginx-proxy-manager** and added now the configuration to my location. Now we will see if this works. Thanks for your support. I will close this issue now, because it's not a bug.

To whoever encountered this issue about the not working upload progress bar when using the **Nginx Proxy Manager** and arrived on this page to find a solution (like me): 

It does not seem to be necessary to configure any `proxy_set_header` options manually. 
Just tick the **Websockets Support** checkbox:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/7422872/172135308-6cb87a16-7c7f-4953-96f6-a78da9dbd9a7.png">

This setting was sufficient for my setup. HTH
