### ISSUE TITLE
[BUG] OCR slightly tilting scanned Document

### ISSUE THREAD

**Issue by MaximusdaVII** [paperless-ngx/paperless-ngx#2201]
### Description

I noticed that some of my scanned Documents are tilted slightly. They are not scanned  wrong, I compared the originals in the paperless folder and when compared most of them are slightly off axis some barely noticeable, but some are really distracting.
I tried some examples off the internet and they aren’t that bad.
I tried one in English too and it had the same problem. 
And deleting and resubmitting the same Original over the WebUI does not change how much it is tilted.

Original:
![472C6717-5546-4815-A071-7D5802C42F51](https://user-images.githubusercontent.com/109476705/208204675-b3759183-ae15-4e1f-bec4-3d89c1e58f1b.jpeg)
OCR:
![431A15C2-D6FF-4BD7-9ECF-4F8943D7AD0E](https://user-images.githubusercontent.com/109476705/208204669-153a5ca9-bf5b-4e09-b864-0842e35a11a2.jpeg)

### Steps to reproduce

Not sure some are worse some don’t have it.
1. Scan Document to PDF into consume Folder
2. Paperless shows it tilted already 
3. Compare the original with the OCR version

### Webserver logs

```bash
/
```

### Paperless-ngx version

1.10.2

### Host OS

Unraid, uname -m: x86_64

### Installation method

Docker - official image

### Browser

No difference how the pdfs are opened

**Comment by stumpylog** [comment]
You can configure the threshold for rotation with `PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=<num>`.  You may also be interested in`PAPERLESS_OCR_DESKEW=<bool>`.

See details here: https://docs.paperless-ngx.com/configuration/
