### ISSUE TITLE
[BUG] Filtering is inconsistent: tag exclusion does not apply with search term

### ISSUE THREAD

**Issue by elagil** [paperless-ngx/paperless-ngx#2204]
### Description

Filtering documents is not working as expected in some cases.

When filtering for tags, it is possible to include/exclude or exactly match tags. That functionality is lost when using a search term at the same time. I assume that this is not intended behaviour.

### Steps to reproduce

1. Go to `Documents`
2. Enter a search term for filtering documents by that search term. This works fine.
3. Exclude a tag from the search results. The tag is not excluded, when a search term was entered.

### Webserver logs

```bash
Does not apply
```

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Firefox

**Comment by elagil** [comment]
I noticed that this only occurs in the extended search, which does include serching for tags (it seems). Maybe this could be added to the documentation. I can create a PR, if that makes sense.

**Comment by shamoon** [comment]
Interesting and a bit surprising. The frontend just hits the API here, of course and Im surprised that exlclusion (`tags__id__none`) doesnt work even though inclusion (`tags__id__all`) does, need to see if we can track down why

**Comment by shamoon** [comment]
Will be fixed in #2205 =)

**Comment by elagil** [comment]
Great, thanks for fixing it!

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/5435dc2499c5f1c17bbc5c053ee291e7309cee19
