### ISSUE TITLE
PAPERLESS_ENABLE_HTTP_REMOTE_USER works perfectly but prevents access to admin part

### ISSUE THREAD

**Issue by Cartache** [paperless-ngx/paperless-ngx#2228]
### Description

My configuration:
docker-compose installation
Latest version of paperless

From a new install, directly enabling the PAPERLESS_ENABLE_HTTP_REMOTE_USER option prevents accessing to the protected pages with the superuser account. No error message is displayed but the login page requesting admin right loops.

Deactivating PAPERLESS_ENABLE_HTTP_REMOTE_USER enables access the pages with the same credentials.

A workaround exists:
- Enabling first PAPERLESS_ENABLE_HTTP_REMOTE_USER to activate the automatic local user creation
- Disable PAPERLESS_ENABLE_HTTP_REMOTE_USER and logging in with the superuser credentials
- Add the newly created user to the superuser membres
- Re-enbable PAPERLESS_ENABLE_HTTP_REMOTE_USER

### Steps to reproduce

Install from scratch with docker-compose
Activate the Http header authentication
Login with the authenticated user
Try to access the admin pages
Fill-in the requested admin credentials
Dead Loop on the credentials page

### Webserver logs

```bash
No warning neither error messages in the docker logs
```

### Paperless-ngx version

1.10.2

### Host OS

Debian 11

### Installation method

Docker - official image

### Browser

Microsoft Edge

**Comment by shamoon** [comment]
I’m not sure if there’s a reverse proxy issue or what exactly but I don’t think there’s an issue here, logged in as a super user with the remote header option I can access admin just fine.

**Comment by Cartache** [comment]
Dear,

I understand your point but I really think there is an issue somewhere.
Starting from a clean situation, using my docker-compose which uses secret files and HTTP_REMOTE_USER, I manage to install everything but am not able to use the superuser credentials that should be created thanks to both variables (PAPERLESS_ADMIN_USER & PAPERLESS_ADMIN_PASSWORD). 
Disabling the HTTP_REMOTE_USER variable and logging on with the superuser credentials permits me to configure my standard user as superuser.
Re-enabling the HTTP_REMOTE_USER variable, works perfectly and enables me to administer paperless.

For me, it is ok to proceed as explained just above but I really think there is an issue.

Regards.

Denis

**Comment by Pizmovc** [comment]
I've also encountered this issue.

I've also tried setting the `PAPERLESS_ADMIN_USER` to my username, but that did not grant me access to the admin pages either.

I can also confirm that the workaround by @Cartache works (disable remote-user login, login as admin, add rights to your user, enable remote-user login).
