### ISSUE TITLE
Bug? Getting "password authentication failed for user paperless" when running "document_retagger -t"

### ISSUE THREAD

**Issue by Cartache** [paperless-ngx/paperless-ngx#2248]
### Description

Hi,
Again, I am not sure it is a bug or the way I configurer the docker containers.
I try to simply re-execute the routine to change the document type by running "document_retagger -t".
I directly get the exception with the error underneath.

The strange thing is the fact that the error mentions a paperless user which is not used.

### Steps to reproduce

Open a shell session inside the paperless container.
Run the command document_retagger -t

### Webserver logs

```bash
document_retagger -t
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "paperless"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_retagger.py", line 81, in handle
    for document in tqdm.tqdm(documents, disable=options["no_progress_bar"]):
  File "/usr/local/lib/python3.9/site-packages/tqdm/std.py", line 989, in __init__
    total = len(iterable)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 323, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 299, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "paperless"

Exception ignored in: <function tqdm.__del__ at 0x7f72a9ab8f70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tqdm/std.py", line 1162, in __del__
  File "/usr/local/lib/python3.9/site-packages/tqdm/std.py", line 1281, in close
AttributeError: 'tqdm' object has no attribute 'disable'
```

### Paperless-ngx version

1.10.2

### Host OS

Linux Debian 11

### Installation method

Docker - official image

### Browser

Microsoft Edge

### Configuration changes

Everything in an env file and a docker-compose.file

### Other

DB: Postgres SQL, docker-compose using secrets files

**Comment by stumpylog** [comment]
You've doubled checked `PAPERLESS_DBPASS, `PAPERLESS_DBUSER` and the corresponding value in the DB container's configuration?

Our default configuration value for both those (and the DB name) is just `paperless`

**Comment by Cartache** [comment]
Hi,
Thank you for answering to my request. If I understand well your question, I don’t use the paperless config file, neither the env file for the DB user and DB password. Every field that could use the docker secrets was enabled. So the answer is yes the DB user and password are not paperless and are stored in a secure location mounted at run time. Does this mean that to run the command line scripts the DB credentials need to be located in the config file?

**Comment by stumpylog** [comment]
So you've set the environment variables `PAPERLESS_DBUSER_FILE` and `PAPERLESS_DBPASS_FILE` to a docker secret (usually `/run/secrets/`)?

And in the DB container `POSTGRES_USER` and `POSTGRES_PASSWORD` have been set to the same value as the secrets?

**Comment by Cartache** [comment]
Yes this is correct.

**Comment by Cartache** [comment]
But to be honest, I already created a another issue for another credentials/rights issue which seems completely unrelated but could reveal that my configuration is maybe not completely correct.

**Comment by stumpylog** [comment]
With a configuration like the below, everything works as I expect.  The password and username are picked up from the file and the database is connected to, migrated and files are consumed.  This should also work fine using Docker secrets, as they are just mounted as files.

```yaml
version: "3.7"
networks:
   paperless-ngx-net:
    name: paperless-ngx-net

services:
  paperless-ngx-dev-db:
   image: docker.io/postgres:15
...
   environment:
     POSTGRES_DB: paperless
     POSTGRES_USER: thisisausername
     POSTGRES_PASSWORD: thisisapassword

  paperless-ngx-dev-webserver:
...
    volumes:
...
      - ./username.txt:/secrets/username.txt:ro
      - ./password.txt:/secrets/password.txt:ro
    environment:
...
      PAPERLESS_DBHOST: paperless-ngx-dev-db
      PAPERLESS_DBUSER_FILE: "/secrets/username.txt"
      PAPERLESS_DBPASS_FILE: "/secrets/password.txt"
      PAPERLESS_DBPORT: 5432
```

**Comment by stumpylog** [comment]
I forgot this started with the retagger, which indeed, does not work as I expect.

**Comment by Cartache** [comment]
`
version: "3.9"
# Global Common Keys
#>>>>>>> Network
x-net-be: &net-be
  networks:
    - backend_net
x-net-fe: &net-fe
  networks:
    - frontend_net
x-net-socket: &net-socket
  networks:
    - socket_proxy_net
x-net-fe-be: &net-fe-be
  networks:
    - frontend_net
    - backend_net
x-net-be-socket: &net-be-socket
  networks:
    - backend_net
    - socket_proxy_net    
x-net-fe-socket: &net-fe-socket
  networks:
    - frontend_net
    - socket_proxy_net    
x-net-fe-be-socket: &net-fe-be-socket
  networks:
    - frontend_net
    - backend_net
    - socket_proxy_net   
#>>>>>>> Logging
...
x-logging-json: &logging-json
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"
...
#>>>>>>> Default
x-std-keys: &std-keys
  <<: *logging-json
  restart: unless-stopped
  environment:
    - TZ=$TZ
    - PUID=$PUID
    - PGID=$PGID
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro 
  labels:
    - com.centurylinklabs.watchtower.enable=true
#>>>>>>> Logging Security
...
x-std-keys-sec: &std-keys-sec
  <<: *std-keys
  security_opt:
    - no-new-privileges:true
...
# Secured
...

x-std-keys-sec-be: &std-keys-sec-be
  <<: *std-keys-sec
  <<: *net-be

...

########################### SERVICES ###########################
services:

paperless:
    <<: *std-keys-sec-be
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    depends_on:
      - paperless_db
      - paperless_redis
      - paperless_gotenberg
      - paperless_tika
    ports:
      - 8111:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - $DOCKER_DIR/paperless/data:/usr/src/paperless/data
      - $DOCKER_DIR/media:/usr/src/paperless/media
      - $DOWNLOAD_DIR/paperless:/usr/src/paperless/export
      - /mnt/inbox/paperless:/usr/src/paperless/consume
      - $LOG_DIR/paperless:/logs
    secrets:
      - paperless_db_user
      - paperless_db_password
      - paperless_secret_key
      - paperless_admin_user
      - paperless_admin_password
      - paperless_admin_email
    environment:
      - PAPERLESS_IGNORE_DATES="dd/mm/yyyy"
      - PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}/{title}
      - PAPERLESS_TASK_WORKERS=2
      - PAPERLESS_THREADS_PER_WORKER=2
      - PAPERLESS_WORKER_TIMEOUT=10000
      - PAPERLESS_OCR_MAX_IMAGE_PIXELS=3000000000
      - PAPERLESS_LOGGING_DIR=/logs
      - PAPERLESS_LOGROTATE_MAX_SIZE=10000
      - PAPERLESS_LOGROTATE_MAX_BACKUPS=10
      - PAPERLESS_REDIS=redis://paperless_redis:6379
      - PAPERLESS_DBHOST=paperless_db
      - PAPERLESS_DBUSER_FILE=/run/secrets/paperless_db_user
      - PAPERLESS_DBPASS_FILE=/run/secrets/paperless_db_password
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless_gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://paperless_tika:9998
      - PAPERLESS_OCR_LANGUAGES=fra nld
      - PAPERLESS_OCR_LANGUAGE=fra+nld
      - PAPERLESS_OCR_MODE=redo
      - PAPERLESS_OCR_CLEAN=clean
      - PAPERLESS_OCR_DESKEW=true
      - PAPERLESS_OCR_ROTATE_PAGES=true
      - PAPERLESS_OCR_OUTPUT_TYPE=pdfa
      - PAPERLESS_TIME_ZONE=Europe/Paris
      - PAPERLESS_CONSUMER_DELETE_DUPLICATES=false
      - PAPERLESS_CONSUMER_RECURSIVE=true
      - PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini"]
      - PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
      - PAPERLESS_CONSUMER_ENABLE_BARCODES=true
      #- PAPERLESS_CONSUMER_TMPDIR=$TEMP_DIR_TIER1
      - PAPERLESS_FILENAME_DATE_ORDER=YMD
      - PAPERLESS_ENABLE_UPDATE_CHECK=true
      - PAPERLESS_LOGROTATE_MAX_SIZE=2
      - PAPERLESS_LOGROTATE_MAX_BACKUPS=30
      - PAPERLESS_SECRET_KEY_FILE=/run/secrets/paperless_secret_key
      - PAPERLESS_URL=https://paperless.my.domain
      - PAPERLESS_ENABLE_HTTP_REMOTE_USER=$PAPERLESS_ENABLE_HTTP_REMOTE_USER
      - PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME=HTTP_REMOTE_USER
      - PAPERLESS_LOGOUT_REDIRECT_URL=https://auth.my.domain/logout 
      - PAPERLESS_ADMIN_USER_FILE=/run/secrets/paperless_admin_user
      - PAPERLESS_ADMIN_PASSWORD_FILE=/run/secrets/paperless_admin_password
      - PAPERLESS_ADMIN_MAIL_FILE=/run/secrets/paperless_admin_email
      - USERMAP_UID=$PUID
      - USERMAP_GID=$PGID
  paperless_redis:
    <<: *std-keys-sec-be
    image: docker.io/library/redis:7
    container_name: paperless_redis
    volumes:
      - $DOCKER_DIR/paperless/redis:/data
  paperless_db:
    <<: *std-keys-sec-be
    container_name: paperless_db
    image: docker.io/library/postgres:13
    volumes:
      - $DOCKER_DIR/paperless/db:/var/lib/postgresql/data
    secrets:
      - paperless_db_user
      - paperless_db_password
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER_FILE: /run/secrets/paperless_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/paperless_db_password
  paperless_gotenberg:
    <<: *std-keys-sec-be
    container_name: paperless_gotenberg
    image: docker.io/gotenberg/gotenberg:7.4
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
  paperless_tika:
    <<: *std-keys-sec-be
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperless_tika`

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/c76460bd962edf5188cafbc23fcd0af30dce53eb
