### ISSUE TITLE
Filtering for correspondents / tags / doc types only works on page 1

### ISSUE THREAD

**Issue by bauerj** [paperless-ngx/paperless-ngx#225]
## Steps to reproduce

1. Open "Correspondents page"
2. Go to page 2
3. Enter name of correspondent in filter field
4. Press return

## Expected behaviour:
Correspondent is shown

## Actual behaviour:
Nothing happens

## More information
The frontend requests `/api/correspondents/?page=2&name__icontains=something` to which the backend responds with "Invalid page". Indeed, when filtering for "something" only a single correspondent matches, so there is no page 2.

The frontend should probably drop the page from the query when filtering there.

This happens in 1.6.0-beta / #213

**Comment by shamoon** [comment]
Aha, I see this. I imagine this bug has been around for a while. It actually applies to all 3 management sections correspondents / tags / doctype, assuming you have enough of them.

I will look into this, imagine a fix wont be too bad. Thanks for reporting!

**Comment by shamoon** [comment]
Closed in branch
