### ISSUE TITLE
[BUG] Docs for "Bare Metal Route" - setup are not up to date

### ISSUE THREAD

**Issue by nicro87** [paperless-ngx/paperless-ngx#2250]
### Description

Hello,
I wanted to upgrade from paperless-ng to ngx, but the docs for the bare metal route are incomplete or wrong in some places.
For example:
- There is no `requirements.txt` you have to use pipenv
- The frontend is not delivered in the release and you have to build it yourself

Could you either change the docs or put  the frontend and requirements back into the releases?

Thank you very much.

### Steps to reproduce

Following the docs is not possible

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.10.2

### Host OS

ubuntu22.04/arm64

### Installation method

Bare metal

**Comment by shamoon** [comment]
The documentation states to pull a release archive, which do contain these.

**Comment by shamoon** [comment]
https://gist.github.com/shamoon/3a8daadc469bec7e79c75d0d2087a443 --> https://gist.github.com/shamoon/3a8daadc469bec7e79c75d0d2087a443#file-gistfile1-txt-L5 , https://gist.github.com/shamoon/3a8daadc469bec7e79c75d0d2087a443#file-gistfile1-txt-L63
