### ISSUE TITLE
[BUG] GUI not refreshing when adding / updating tags, correspondents etc. (on docker and demo instance)

### ISSUE THREAD

**Issue by tlwt** [paperless-ngx/paperless-ngx#2267]
### Description

When adding new entries to correspondents, tags, document types the entries are not available for immediate selection. I need to reload the page until they become available.

I tested this behavior on the demo.paperless-ngx.com and on a local install on Paperless-ngx 1.11.0

### Steps to reproduce

1. Go to https://demo.paperless-ngx.com/correspondents
2. click on "create"
3. enter a name for the new tag
4. click on "save"

The new entry does not show up unless the page is refreshed. Same behavior for document types, correspondents...

### Webserver logs

```bash
please see demo instance demo.paperless-ngx.com
```

### Browser logs

Observing with Firefox Developer tools an error is thrown when the "create" button is clicked:

```
ERROR TypeError: e.componentInstance.success is undefined 
[main.js:3:53626](https://demo.paperless-ngx.com/static/frontend/en-US/main.js)
```

### Paperless-ngx version

1.11.0

### Host OS

DS1817+

### Installation method

Docker - official image

### Browser

Firefox 108.0.1 (64-Bit), Version 16.1 (18614.2.9.1.12), Version 108.0.5359.124 (Offizieller Build) (arm64)

### Other

both on demo instance as well as local docker instance

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/58532eeb69ea876d40fe4f7cb0026fa117799de9
