### ISSUE TITLE
[BUG] 1.6.0-rc1 Filter indicator on Correspondent and Document types not showing a number

### ISSUE THREAD

**Issue by 42CrMo4** [paperless-ngx/paperless-ngx#227]
**Describe the bug**
The indicator on the filter Buttons is not showing a number on the Correspondent and Document types after slecting something. For the Tags it displays the selected number of Tags. 
<img width="421" alt="Bildschirmfoto 2022-03-07 um 21 28 04" src="https://user-images.githubusercontent.com/44754810/157112820-10b7e6ee-9564-473f-a273-7a5593450e0d.png">  

**To Reproduce**
1. Go to Documents
2. Click on Correspondent or Document types
3. Select one item
4. Number indicator on filter button will not show a number

**Expected behavior**
The Indicator circle should have the number in it. In 1.4.5 it was working this way.
<img width="414" alt="Bildschirmfoto 2022-03-07 um 21 32 37" src="https://user-images.githubusercontent.com/44754810/157113347-94628b42-685e-42ad-8f7d-d1da333ef50d.png">

**Webserver logs**
no, not that i know.

**Relevant information**
 - Host OS: Raspbian 10
 - Browser: Firefox
 - Version: 1.6.0-rc1 
 - Installation method: docker
 - Any configuration changes: no, same as 1.4.5

**Comment by shamoon** [comment]
This is intentional. Currently correspondents and doc types can only have 1 item selected. If changed in the future that can be altered =)
