### ISSUE TITLE
[BUG] Hebrew not treated as RTL when there is a text in the PDF

### ISSUE THREAD

**Issue by stepanov1975** [paperless-ngx/paperless-ngx#2301]
### Description

When PDF containing Hebrew text is OCRed the text in "Content" window is right-to-left. (Although aligned to left. Would be nice if this will be fixed and text will be aligned to right)  
When PDF already contains text and this text is taken as-is, the text is not treated as RTL, i.e. all characters in words are reversed.  
This causes major problems as the search will not find properly typed words. To use search I need to reverse the order of characters :(  
Attaching PDF in Hebrew as example
[mapa.pdf](https://github.com/paperless-ngx/paperless-ngx/files/10328954/mapa.pdf)

### Steps to reproduce

1. Upload a PDF containing text in Hebrew
2. Go to "Content" tab
3. Characters order reversed

### Webserver logs

```bash
Not relevant
```

### Paperless-ngx version

1.11.2

### Host OS

Fedora 35 x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Ah.

Well one immediate problem here is that the UI currently has no knowledge of the fact that the document is RTL. I suppose we will need to update the /documents API endpoint with a field for this, which I was about to do but actually, the document itself doesnt even retain this info. We could `langdetect` the content but this seems costly, I presume it would be better to retain the info during the consumption process, but Im not sure of the best approach to that, anyone else have thoughts?

If the API can return something like 'is_rtl' (or the language of course) fixing the frontend part is trivial.

**Comment by shamoon** [comment]
On second thought there might be a more obvious solution here...

@stepanov1975 can you tell me what settings you have to correctly parse this doc? `PAPERLESS_OCR_LANGUAGE=eng+heb`

**Comment by stepanov1975** [comment]
> On second thought there might be a more obvious solution here...
> 
> @stepanov1975 can you tell me what settings you have to correctly parse this doc? `PAPERLESS_OCR_LANGUAGE=eng+heb`?

@shamoon 
PAPERLESS_OCR_LANGUAGES=eng heb  
APERLESS_OCR_LANGUAGE=heb+eng

**Comment by stepanov1975** [comment]
@shamoon Why langdetect is costly? I understand you need only a small portion of the text for it. And this could be an optional feature as well (turned on only by users who know they have documents in RTL language).  
Anyway. I would guess the simplest solution is to add in the configuration (env or GUI) option to specify that the default text is RTL. Then in the document editing GUI add an option to overwrite this.  
But I would prefer an automatic solution very much.

**Comment by shamoon** [comment]
Hmm, I keep getting vietnamese 🫤 I gotta figure that out.

```
[2023-01-01 16:09:37,289] [DEBUG] [paperless.consumer] Parsing mapa.pdf...
[2023-01-01 16:09:38,792] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /private/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-upload-dnq5mg8m
[2023-01-01 16:09:39,502] [DEBUG] [paperless.parsing.tesseract] Detected language he
[2023-01-01 16:09:39,503] [WARNING] [paperless.parsing.tesseract] Detected RTL language he
[2023-01-01 16:09:39,735] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/private/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-upload-dnq5mg8m'), 'output_file': '/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-gmpxmfba/archive.pdf', 'use_threads': True, 'jobs': 8, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-gmpxmfba/sidecar.txt'}
[2023-01-01 16:09:41,364] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2023-01-01 16:09:42,808] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-gmpxmfba/archive.pdf
[2023-01-01 16:09:42,837] [DEBUG] [paperless.parsing.tesseract] Detected language vi
...
```

**Comment by stepanov1975** [comment]
> [2023-01-01 16:09:38,792] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /private/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-upload-dnq5mg8m
> [2023-01-01 16:09:39,502] [DEBUG] [paperless.parsing.tesseract] Detected language he

[2023-01-01 16:09:38,792] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /private/var/folders/50/p_n18fw96lj8y3jnd69gy2w40000gn/T/paperless/paperless-upload-dnq5mg8m  
[2023-01-01 16:09:39,502] [DEBUG] [paperless.parsing.tesseract] Detected language he  
It detects language from text properly

**Comment by stepanov1975** [comment]
@shamoon So tesseract already analyzes text in PDF and detects language properly.  It seems like you only need to save this information to the database and then use it in GUI?

**Comment by shamoon** [comment]
Yes, and I've come back around to that being the only viable solution here, see my [comment above](https://github.com/paperless-ngx/paperless-ngx/issues/2301#issuecomment-1368473087)

Will wait to see if folks who work more on the backend have thoughts about how best to achieve this.

**Comment by shamoon** [comment]
Well after all that I think theres a reasonable solution =) but we'll see if any issues. A docker container for this is being built if you'd like to test once done: https://github.com/paperless-ngx/paperless-ngx/actions/runs/3817828371

**Comment by stumpylog** [comment]
I've pushed an update which I think helps, alongside the other updates already made.  

I'm not 100% sure how an RTL should be displayed though, sf possible, could you (and perhaps @OmarWazzan as well) test with different types of documents?  Digital born PDFs as well as images with RTL would be awesome.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/985f298c46c5bedb421074061c7d746933868469

**Comment by OmarWazzan** [comment]
> I've pushed an update which I think helps, alongside the other updates already made.
> 
> I'm not 100% sure how an RTL should be displayed though, sf possible, could you (and perhaps @OmarWazzan as well) test with different types of documents? Digital born PDFs as well as images with RTL would be awesome.

Hi,
Apologies for the late response.

Will test this weekend and report back!

**Comment by OmarWazzan** [comment]
Happy to confirm issue appears fixed @shamoon @stumpylog

I uploaded a decent mix of scanned + digital documents and they were all spot on - will continue to test further over the next few days and let you know if anything pops up.

Greatly appreciated!
