### ISSUE TITLE
[BUG] [DOCS] PAPERLESS_URL should only be a domain name, don't set full URL

### ISSUE THREAD

**Issue by philbradley** [paperless-ngx/paperless-ngx#2314]
### Description

I encountered a problem when migrating from paperless-ng to ngx. 
Background: my -ng install runs from a subpath: https://example.com/scan/ , behind a reverse proxy.

Problem (1): https://docs.paperless-ngx.com/setup/#migrating-from-paperless-ng doesn't tell you to set the new envvar, "PAPERLESS_URL".  So although I could login and view docs just fine after taking the steps documented in https://docs.paperless-ngx.com/setup/#migrating-from-paperless-ng , some operations were failing because of a security check.

Problem (2): I set the URL to https://example.com/scan , but loading the web interface just returns a completely blank page - no error message, nothing.  Thankfully, shell output told me that "(corsheaders.E014) Origin 'https://example.com/scan' in CORS_ALLOWED_ORIGINS should not have path" 
The fix was to change "PAPERLESS_URL" so it's just a domain (https:///example.com), with no further path elements (i.e. it's not the actual install URL)

I therefore suggest at least updating the documentation to specify that not only should a trailing slash be omitted, but in fact *only* the domain should be included, not any other path element.  Or the code could strip it, when it's going to be a problem.

Perhaps "PAPERLESS_DOMAIN" would make for a better variable name, but that's probably going to be a breaking change for not much gain.

### Steps to reproduce

Set PAPERLESS_URL to https://example.com/scan , but loading the web interface just returns a completely blank page - no error message, nothing.

### Webserver logs

```bash
"(corsheaders.E014) Origin 'https://example.com/scan' in CORS_ALLOWED_ORIGINS should not have path"
```

### Paperless-ngx version

1.11.3

### Host OS

Ubuntu

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

Set PAPERLESS_URL to https://example.com/scan

**Comment by shamoon** [comment]
Thing is, it’s not just a domain (that would imply just “example.com”) so URL is more accurate.

I’m not positive if the path is truly an issue here or it has to do with your RP setup. If so, yes we  will update the docs.

**Comment by shamoon** [comment]
Thanks for taking the time to report, we'll add a note about this
