### ISSUE TITLE
[BUG] Multi-page TIFFs are truncated on import if they contain an alpha channel

### ISSUE THREAD

**Issue by githubuserx** [paperless-ngx/paperless-ngx#2320]
### Description

Currently Paperless only imports the first page of a multi-page TIFF file if it contains an alpha channel.

This seems to be the culprit as only the first page is saved here after processing:
https://github.com/paperless-ngx/paperless-ngx/blob/main/src/paperless_tesseract/parsers.py#L227-L237

I would've submitted a PR, but unfortunately don't have the time in the forseeable future to do it properly. Therefore I worked around the issue by manually removing the alpha channel before import:
```bash
convert -alpha off withalpha.tiff withoutalpha.tiff
```
```bash
find . -name "*.tiff" -exec convert "{}" -alpha off "{}" \;
```

Although, a potential fix could be as simple as the following (not properly tested):
```python
    with Image.open(input_file) as im:
        im_frames = ImageSequence.all_frames(im, lambda f: f.convert("RGB"))
        im_frames[0].save(input_file, save_all=True, append_images=im_frames[1:])
```
Also see

- https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#using-the-imagesequence-iterator-class
- https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#reading-multi-frame-tiff-images

### Steps to reproduce

1. Import new file `multipage.tiff`
2. Check page count of successfully imported file
3. Import new file `multipage-noalpha.tiff`
4. Check page count of successfully imported file

Demo files: [multipage-files.zip](https://github.com/paperless-ngx/paperless-ngx/files/10333025/multipage-files.zip)

### Webserver logs

```bash
Not relevant as no error is logged related to this issue.
```

### Paperless-ngx version

1.11.2

### Host OS

Ubuntu Server 22.10

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Thank you for the sample files, that always makes it easier to reproduce.  I've tested a fix to use `convert` to handle the removal, instead of trying to invent the wheel again.

If possible, could you make a smaller, simpler multi page tiff with alpha and some distinct text on each page?  I'd like to capture a sample file into a unit test

**Comment by githubuserx** [comment]
[multi-page-images.zip](https://github.com/paperless-ngx/paperless-ngx/files/10336855/multi-page-images.zip)
I created TIFF variants from the existing `multi-page-images.pdf` test sample file using
```bash
convert -compress Zip -density 300 -depth 8 -colorspace sRGB -type truecoloralpha multi-page-images.pdf multi-page-images-alpha-rgb.tiff
convert -compress Zip -density 300 -depth 8 -alpha off multi-page-images.pdf multi-page-images.tiff
convert -compress Zip -density 300 -depth 8 multi-page-images.pdf multi-page-images-alpha.tiff
```
The source file seems to be in grayscale so the new files are too, except I had to add an RGB version for the one that contains an alpha channel to be able to import it. Culprit seems to be the same piece of code as mentioned above. Hope that helps.

**Comment by stumpylog** [comment]
Thanks for the test files again.  This is now fixed in develop by the linked PR
