### ISSUE TITLE
[BUG] --prod argument when building frontend isn't recognized

### ISSUE THREAD

**Issue by Infouzi** [paperless-ngx/paperless-ngx#2333]
### Description

Currently, i am trying to build the frontend in a separate container than the "webserver" container.
In the process, when i follow the documentation and use `ng build --prod` i have the following error message:
`Error: Unknown argument: prod`

However, when i use `./node_modules/.bin/ng build --configuration production`, it works. So i was wondering if it is the same or not ?

In addition, when i try to execute the latter command inside the container, it displays that it is working, but the `dist/` folder isn't generated and that confuses me a bit; especially when it works locally.

Here is the Dockerfile i am using for building the frontend container:

```yaml
#stage 1
FROM node:latest as node

RUN mkdir -p /app
WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install -g @angular/cli
RUN npm install
COPY . /app # to copy the content of src-ui/ folder inside the container "app" folder
RUN ng build --configuration production # this command should create the "dist" folder, but it doesn't

ENTRYPOINT ["tail", "-f", "/dev/null"] # I have added it to make the container run indefinitely for debugging purpose

#stage 2
# FROM nginx:alpine
# COPY --from=node /app/dist/paperless-ui /usr/share/nginx/html #will copy the content of dist folder to an nginx container to serve the files
```

Some help would be appreciated. Thanks in advance !

### Steps to reproduce

```
1. Go to paperless-ngx/src-ui/ folder
2. run npm install
3. run ng build --prod

### Webserver logs

```bash
Not a webserver log, but a console output: `Error: Unknown argument: prod`
```

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Brave

**Comment by shamoon** [comment]
Thanks, youre right the --prod flag was deprecated a while back, the docs need to be updated

**Comment by Infouzi** [comment]
Thank you for your work 🙏
For my other request, do i open a new issue for it is not really an issue per say with paperless itself ?

**Comment by shamoon** [comment]
Sorry what’s the other piece exactly? The command works inside and outside the container, that’s how the frontend is built in the actual dockerfile of course:

https://github.com/paperless-ngx/paperless-ngx/blob/main/Dockerfile#L31

**Comment by Infouzi** [comment]
Thank you for the quick feedback.
Yah, i'm sure of it working inside and outside.. netherless, this should be something not-related to paperless, so i'm going to try more on my side to figure out why it isn't.

Again, thank you and all the best with this great project ❤
