### ISSUE TITLE
[BUG] PDF-Preview not visible on mobile / small screens

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#2344]
### Description

the mobile-view does not show the PDF-Preview. See following Screenshots for further description.

![2023-01-04_13-28](https://user-images.githubusercontent.com/88422038/210558560-cfcaace8-0027-469f-9f7a-f37dacaa9823.png)

![2023-01-04_14-05](https://user-images.githubusercontent.com/88422038/210561390-5899ac96-922a-4866-8012-769b44cfb851.png)

If the mobile-view is exited, it is shown (though not useable). Would assume, some JS / CSS rendering problems here. Would be nice if this could be fixed.

### Steps to reproduce

1. Visit app on mobile / small screens
2. navigate to document edit
3. view preview tab
4. no preview is shown

### Webserver logs

```bash
not relevant
```

### Browser logs

```bash
no logs occur
```

### Paperless-ngx version

1.11.3

### Host OS

Synology DSM 6.2.X

### Installation method

Docker - official image

### Browser

Chrome Version 108.0.5359.94

**Comment by Limerick-gh** [comment]
I can confirm. Thought it was my mobile not working correctly. :-) Rotating mobile device in landscape, preview shows up.

**Comment by sukisoft** [comment]
> I can confirm. Thought it was my mobile not working correctly. :-) Rotating mobile device in landscape, preview shows up.

rotating in deed shows the preview, but on my mobile, the desktop view is toggled, so that the mobile view is exited. 

I first recognized this on mobile, but as the screenshots indicate, this can be reproduced by minimzing the size of the browser when on desktop.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/8e83f909528f1a76836437514a26ba5b8b867fda
