### ISSUE TITLE
[BUG] env-from-file.sh breaks usage of COMPOSE_FILE

### ISSUE THREAD

**Issue by le-jou** [paperless-ngx/paperless-ngx#2367]
### Description

The paperless webserver is not starting up when the docker compose specific variable COMPOSE_FILE is used.
My Paperless compose file is named 'paperless.yml'. As I don't want to specify this explicitly every time when I run docker compose commands, I have set COMPOSE_FILE=paperless.yml in my .env file.

env-from-file.sh introduced with 06c6f33 breaks this and the webserver won't start because it can't find 'paperless.yml'.

I think this happens, because before this change, only certain environment variables were checked and now **all** variables are checked.

### Steps to reproduce

1. Name compose file something other than 'docker-compose.yml'
2. Specify environment variable 'COMPOSE_FILE' to use the right compose file
3. Start compose file and see webserver logs

### Webserver logs

```bash
Paperless-ngx docker container starting...
Installing languages...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
File paperless.yml doesn't exist
Paperless-ngx docker container starting...
Installing languages...
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
File paperless.yml doesn't exist
```

### Paperless-ngx version

1.11.3

### Host OS

Debian 10

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Thanks for the report, it's been fixed via the linked pull request.
