### ISSUE TITLE
[BUG] Thumbnail migration does not recover if it fails 

### ISSUE THREAD

**Issue by msettlemeyer** [paperless-ngx/paperless-ngx#2375]
### Description

Reading the notes of the thumbnail commit. It seems like there is a process that runs once to migrate PNG to WebP. It must have failed in my move from paperless-ng. Now only newly uploaded documents show thumbnails.

### Steps to reproduce

Force failure during migration from Paperless-ng

### Webserver logs

```bash
No mention of error in paperless logs
```

### Browser logs

```bash
404 for get request for thumbnails on existing documents
```

### Paperless-ngx version

1.11.3

### Host OS

Ubuntu Server 22.04 VM

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Any errors would have been logged if you're curious why the convert failed.  

The management command `document_thumbnails` can regenerate thumbnails for particular documents or all documents, depending on how many there are, which will restore thumbnails in the expected format and location.
