### ISSUE TITLE
[BUG] Issues in the bare metal setup guide

### ISSUE THREAD

**Issue by teythoon** [paperless-ngx/paperless-ngx#2405]
### Description

If you follow the bare metal setup guide, you end up with an installation that is not working.  I have identified the following issues:

- Missing `manage.py collectstatic` to collect the static files.
- `paperless-scheduler.service` and `paperless-task-queue.service` don't use an absolute path to `celery`, hence the service fails to start.
- `paperless-webserver.socket` is missing from the release tarballs:
```
% tar tf paperless-ngx-v1.11.3.tar.xz | grep paperless-ngx/scripts
paperless-ngx/scripts/
paperless-ngx/scripts/start_services.sh
paperless-ngx/scripts/paperless-consumer.service
paperless-ngx/scripts/paperless-scheduler.service
paperless-ngx/scripts/paperless-task-queue.service
paperless-ngx/scripts/post-consumption-example.sh
paperless-ngx/scripts/paperless-webserver.service
```
- The static files are not served.  The symptoms are the same as in #2384 which makes sense: unless in debug mode or explicitly configured to serve the static files, Django doesn't serve static files.
- The nginx configuration template also doesn't serve the static files.

### Steps to reproduce

1. Follow the bare metal setup guide.
2. Paperless doesn't work.

### Webserver logs

```bash
There aren't any.
```

### Paperless-ngx version

1.11.3

### Host OS

Debian GNU/Linux, armv7l

### Installation method

Bare metal

**Comment by stumpylog** [comment]
- The release archive already has the static files collected, so that doesn't seem necessary to do a second time?
- There's a note in the documentation that an absolute path may be required
- That does look to be missing, thank you
- Are you saying that gunicorn isn't working for you?
- I don't believe the nginx config is for serving the site, but instead for being the reverse proxy, leaving gunicorn serving the static files

**Comment by teythoon** [comment]
> - The release archive already has the static files collected, so that doesn't seem necessary to do a second time?

Indeed, that should suffice, I missed that.

> - There's a note in the documentation that an absolute path may be required

Well, celery is installed as a side-effect of installing paperless (unless it was previously installed system-wide I guess).  Therefore, wouldn't it be nicer to use the absolute path in the service files, making the note obsolete?

> - Are you saying that gunicorn isn't working for you?

My installation is working fine.  However, guincorn is not serving the static files.  gunicorn is a WSGI application server, it doesn't serve static files.  One could make Django serve static files, but that is not what is happening, otherwise #2384 wouldn't be an issue.

> - I don't believe the nginx config is for serving the site, but instead for being the reverse proxy, leaving gunicorn serving the static files

It is very common to let nginx serve the static files, and pass through the rest of the requests to a dynamic web application.  In fact, this is what the gunicorn deployment documentation suggests: https://docs.gunicorn.org/en/latest/deploy.html

**Comment by korncola** [comment]
my "bare-metal installaton" which as actually a vm installation also does only work in debug-mode, otherwise i get at login "you are still here, something went wrong" or just a 504 from nginx.
In debug mode also no uploads possible, i get a 504.
Whats best: no logs whatsoever indicate an error.

**Comment by stumpylog** [comment]
- I think in many cases, installing the Python dependencies will add celery to the path for the user paperless, but if you'd like to update to include a full path like the webserver .service does, it's should be fine as well, as that's already done for the webserver systemd unit

- As for web servers, that's not at all my area of expertise.  I assumed gunicorn since `paperless-webserver.service` is the only systemd unit that is related to web things.  I believe [whitenoise](https://whitenoise.evans.io/en/stable/) is also supposed to be related to static files and WSGI, so maybe there's some configuration missing in the steps for that?

**Comment by teythoon** [comment]
Interesting, I haven't heard of whitenoise before.  It did get installed on my system, and it seems to be enabled, but it didn't serve static files when I tried the dev server (#2384) and it didn't serve static files when using gunicorn.  FTR, this is what I see:

```
$ pip list | grep whitenoise
whitenoise             6.2.0
$ grep -iR whitenoise src
src/documents/tests/test_views.py:        # Provide a dummy static dir to silence whitenoise warnings
src/paperless/settings.py:    "whitenoise.runserver_nostatic",
src/paperless/settings.py:    "whitenoise.middleware.WhiteNoiseMiddleware",
src/paperless/settings.py:WHITENOISE_STATIC_PREFIX = "/static/"
$ grep PAPERLESS_STATICDIR paperless.conf
PAPERLESS_STATICDIR=/opt/paperless/state/static
```

**Comment by stumpylog** [comment]
gunicorn + whitenoise is all the Docker image uses as well, there's no nginix, apache, etc installed.

Is /opt/paperless/__state__/static the correct directory for your static files?  Based on the docs, I would expect /opt/paperless/static instead.  I just ran through the setup for the webserver and running `gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application` was enough to reach the login page

**Comment by teythoon** [comment]
> gunicorn + whitenoise is all the Docker image uses as well, there's no nginix, apache, etc installed.

Interesting.

> Is /opt/paperless/state/static the correct directory for your static files? Based on the docs, I would expect /opt/paperless/static instead.

Yes it is:

```
$ ls /opt/paperless/state/static
admin  bootstrap.min.css  django_extensions  frontend  paperless  rest_framework  signin.css
```

> I just ran through the setup for the webserver and running gunicorn -c /opt/paperless/gunicorn.conf.py paperless.asgi:application was enough to reach the login page

Yes, that was my experience as well.  But as soon as I authenticated, no static files are served.  It behaves exactly as I described in #2384.

**Comment by stumpylog** [comment]
I've moved the files to `/opt/paperless/state/static/` and everything is good, including after login.  

```shell
$ grep STATIC paperless.conf
PAPERLESS_STATICDIR=/opt/paperless/state/static
#PAPERLESS_STATIC_URL=/static/
```

Any other changes in the conf file?

**Comment by stumpylog** [comment]
Hm, certainly nothing that should affect anything.  If you link/copy the files to `/opt/paperless/static` does it work?  It shouldn't be looking there, but ??

**Comment by teythoon** [comment]
I re-checked with gunicorn and the django development server and indeed whitenoise is serving the static files now.  My best bet is that when I followed the setup guide, I had changed `PAPERLESS_STATICDIR` but not yet run collectstatic.

I think there are two reasons that contributed to my confusion.  First, the setup guide's odd claim that running the development server would collect static files.  And second, that the missing static files did not result in 404s, but because of the broad routing rules the applications static html page got served for every request.

@korncola can you please check that your `PAPERLESS_STATICDIR` points to the static files?

**Comment by shamoon** [comment]
> First, the setup guide's odd claim that running the development server would collect static files.

I don’t think it says that?

**Comment by shamoon** [comment]
Oh it does, sorry. Yea that’s a mistake!

**Comment by teythoon** [comment]
You are very quick to close issues.
