### ISSUE TITLE
[BUG] Export fails OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by stepanov1975** [paperless-ngx/paperless-ngx#2412]
### Description

When running export, it fails with the error:
```
OSError: [Errno 36] File name too long: '../export/pension/2021/12/check date,from mail,inbox,pension,phoenix pension_שם - סטפנוב אלכס -ת.ז  314442872 מעסיק- 4740(0) סיסקו סיסטמס ישראל בע-מ ח.פ- 512396144 -1-314442872-סטפנוב-אלכס-43-אישור חסר לה.pdf-thumbnail.webp'
```
And BTW, this is exactly the situation I asked about [here](https://github.com/paperless-ngx/paperless-ngx/discussions/2251), and I was assured there is a check that will prevent fails like this.

### Steps to reproduce

1. Have a document with a long Title and many tags
2. Run export ```/usr/local/bin/docker-compose exec -T webserver document_exporter -c -f ../export > export.log 2>&1```
3. Export fails

### Webserver logs

```bash
99%|█████████▉| 1032/1040 [00:05<00:00, 194.11it/s]
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 134, in handle
    self.dump(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 284, in dump
    self.check_and_copy(document.thumbnail_path, None, thumbnail_target)
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 342, in check_and_copy
    shutil.copy2(source, target)
  File "/usr/local/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.9/shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 36] File name too long: '../export/pension/2021/12/check date,from mail,inbox,pension,phoenix pension_שם - סטפנוב אלכס -ת.ז  314442872 מעסיק- 4740(0) סיסקו סיסטמס ישראל בע-מ ח.פ- 512396144 -1-314442872-סטפנוב-אלכס-43-אישור חסר לה.pdf-thumbnail.webp'
```

### Paperless-ngx version

1.11.3

### Host OS

Fedora 35 x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

PAPERLESS_FILENAME_FORMAT={document_type}/{created_year}/{created_month}/{tag_list}_{title}

**Comment by shamoon** [comment]
That other thread was wrt consumption, this is export.

Also, this is FOSS, assurances around here = volunteer time and effort. Steady.

**Comment by stepanov1975** [comment]
> That other thread was wrt consumption, this is export.
> 
> Also, this is FOSS, assurances around here = volunteer time and effort. Steady.
I am not trying to blame anyone or request guarantees :) I understand it is FOSS. I also love the app very much, and thank you for all the effort. I just think we all want the app to be stable first and feature second, as the loss of documents may be very painful. BTW I don't see any way to donate to support development.

**Comment by stumpylog** [comment]
I don't see this as an issue with paperless.  OSes have limits to file name lengths.  On most, if not all, Linux systems, the maximum is 255 bytes.  The filename above is 283 bytes.  There's no way for an application to raise the limit.

This is just a risk when using `{tag_list}` formatting.  I suppose a warning could be added to the docs, but that's the extent of a solution.

**Comment by stepanov1975** [comment]
> I don't see this as an issue with paperless. OSes have limits to file name lengths. On most, if not all, Linux systems, the maximum is 255 bytes. The filename above is 283 bytes. There's no way for an application to raise the limit.
> 
> This is just a risk when using `{tag_list}` formatting. I suppose a warning could be added to the docs, but that's the extent of a solution.

I think better solution will be to truncate file name to 255 characters

**Comment by stumpylog** [comment]
I disagree.  An truncation to a certain number of bytes (not necessarily equal to characters) is not what a user would expect.  Raising an error ensures the user knows there's a problem and the file isn't placed in an arbitrary location.

I'd added a warning in 2 places for the potential problem.
