### ISSUE TITLE
[BUG] Archive is missing folders/documents

### ISSUE THREAD

**Issue by ciddi89** [paperless-ngx/paperless-ngx#2418]
### Description

The archive folder has not the same folder structure like the originals folder. Some documents and folders are missing. In the originals folder are alle documents and folders as excepted. Is there a way to force rebuild the archive folder?

### Steps to reproduce

Add documents in inbox and changing data like path etc. 

### Webserver logs

```bash
No logs related to this issue yet
```

### Paperless-ngx version

v 1.11.3

### Host OS

Synology NAS x86_64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
There's not a lot of information to go on here, but here's some ideas and information which may help.

- You mention "changing data like path".  If you move where the media folder is, files won't be moved automatically, unless you run `document_renamer`.
- Similarlly, changes to the global filename format will not be applied without running the renamer
- Likewise, manually moving files around in the media folder should not be done
- You didn't mention your OCR mode, but if set to `skip_noarchive`, archive files won't always be created, only if needed, such as if an image is consumed

If you would like to recreate archives, please refer to the documentation: https://docs.paperless-ngx.com/administration/#archiver

**Comment by ciddi89** [comment]
Okay sorry I found already the problem. I read the log and it seems that some of the documents are encrypted. But it's curious. It's all the same type, Income tax certificate and Payroll but some of them seems encrypted and some other not. Hmm okay, thanks anyway.
