### ISSUE TITLE
[BUG] Some non-scanned pdfs can not be consumed 'Unsupported mime type inode/x-empty'

### ISSUE THREAD

**Issue by j0lt** [paperless-ngx/paperless-ngx#2419]
### Description

Hey everyone,
thanks for the great piece of software that paperless-ngx is!
I took the docker route to install running version 1.11.3 of paperless-ngx.

I've moved a lot of pdfs into the consume folder coming from/created by an online service. Meaning these files are not scanned documents but where 'digitally' created.

Some files went throgh flawlessly and like expceted. However, some of these files are not getting consumed and the UI states  'name_of_the_file.pdf: Unsupported mime type inode/x-empty'

Is this maybe related to this Bug report and caused by pikepdf?

### Steps to reproduce

1. Place those pdf files into the consume directory
2. wait till paperless-ngx tries to consume them
3. see error logs / task

### Webserver logs

```bash
[2023-01-13 13:50:26,392] [INFO] [paperless.consumer] Consuming 2020-07-28_XYZ 28.07.2020_ABC123456789.pdf

[2023-01-13 13:50:26,393] [DEBUG] [paperless.consumer] Detected mime type: inode/x-empty

[2023-01-13 13:50:26,396] [ERROR] [paperless.consumer] Unsupported mime type inode/x-empty
```

### Paperless-ngx version

1.11.3

### Host OS

Ubuntu 22.10

### Installation method

Docker - official image

### Other

used this tutorial to install paperless-ngx https://www.schreiners-it.de/proxmox/paperless-ngx-im-lxc-container-installieren/

**Comment by shamoon** [comment]
What does `file --mime-type` show? In general these are malformed PDFs so you can regenerate, but if thats the mime-type detected there isnt much we can do since we dont actually want to consume files that are `inode/x-empty`

**Comment by j0lt** [comment]
just like expected it's `inode/x-empty`. I will try to "fix" those files. Thanks for the support

**Comment by AIndoria** [comment]
>but if thats the mime-type detected there isnt much we can do since we dont actually want to consume files that are inode/x-empty

Is there a way to force this? This still happens on files saved by Acrobat, Edge, Firefox, Chrome etc by default.
