### ISSUE TITLE
Removal of @shamoon from project after defense of nazi

### ISSUE THREAD

**Issue by bowvtasm** [paperless-ngx/paperless-ngx#2425]
### Description

My pull request has been rejected again! 

After private discussion with @shamoon he expressed sympathy and admiration for Roberto Rosario Mayan's main developer.

Roberto is a very problematic figure in the Django and Python communities for his Nazi views.

I took me and my friends a long time but we managed to infiltrate Mayan and to do what nobody had the balls to do, take it down from the inside.

This is a BIG opportunity for your project to get all users away from Mayan.

We did all the work, the least we expect is a thank you and a quick approval of the tool to move everybody away from Mayan to Paperless!

Mayan has finally imploded and it is time for everyone to take their private information from a program made by a self avowed neo Nazi homophobe. 

Spitting image of Kyle Rittenhouse right down to the same murder weapon.

https://ibb.co/BrfshyV

This is the person you are helping by rejecting my patch.

### Steps to reproduce

None

### Webserver logs

```bash
None
```

### Paperless-ngx version

All

### Host OS

Any

### Installation method

Docker - official image

**Comment by bowvtasm** [comment]
![image](https://user-images.githubusercontent.com/122652676/212443910-5ea6fb42-148b-4469-b130-1bb47fd14d77.png)

**Comment by shamoon** [comment]
Im going to report this as abuse, please dont post here.
