### ISSUE TITLE
[BUG] Folder locations are not loaded from configuration when creating superuser (or using migrate option)

### ISSUE THREAD

**Issue by SpiderD555** [paperless-ngx/paperless-ngx#2433]
### Description

When I try to create superuser for the first time, then a SystemCheckError appears:
 ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is set but doesn't exist.
	HINT: Create a directory at /opt/paperless/paperless-1.11.3/paperless-ngx/consume
?: PAPERLESS_MEDIA_ROOT is set but doesn't exist.
	HINT: Create a directory at /opt/paperless/paperless-1.11.3/paperless-ngx/media

It seems superuser creation SystemCheck is not loading relevant folder locations from configuration, instead it wrongly assumes  relative paths.

### Steps to reproduce

1. Download & Unpack paperless into /opt/paperless/paperless-{{ version }} folder
2. Configure for bare metal installation as per the instruction (along with postgresql installation)
3. Set configuration in following way:
```
PAPERLESS_CONSUMPTION_DIR=/opt/paperless/paperless-1.11.3/consume
PAPERLESS_DATA_DIR=/opt/paperless/paperless-1.11.3/data
PAPERLESS_TRASH_DIR=/opt/paperless/paperless-1.11.3/trash
PAPERLESS_MEDIA_ROOT=/opt/paperless/paperless-1.11.3/media
```
4. Try to create superuser (or use migrate option) with following command:
`/opt/paperless/paperless-1.11.3/venv/bin/python3 /opt/paperless/paperless-1.11.3/paperless-ngx/src/manage.py manage_superuser`

### Webserver logs

```bash
No logs yet
```

### Paperless-ngx version

1.11.3

### Host OS

Debian 11

### Installation method

Bare metal

### Configuration changes

PAPERLESS_CONSUMPTION_DIR=/opt/paperless/paperless-1.11.3/consume PAPERLESS_DATA_DIR=/opt/paperless/paperless-1.11.3/data PAPERLESS_TRASH_DIR=/opt/paperless/paperless-1.11.3/trash PAPERLESS_MEDIA_ROOT=/opt/paperless/paperless-1.11.3/media

**Comment by shamoon** [comment]
This doesn’t make sense, it is loading the path as the logs note, it’s saying it doesn’t exist. Does it?

**Comment by SpiderD555** [comment]
Please take note the path is different in configuration and error message:
/opt/paperless/paperless-1.11.3/consume (for PAPERLESS_CONSUMPTION_DIR in configuration)
/opt/paperless/paperless-1.11.3/**paperless-ngx**/consume (in error message)

It is true that the consume folder in /opt/paperless/paperless-1.11.3/**paperless-ngx**/ does not exist (but why should it exist there in the fist place if I created it in a different place and defined that different place in configuration file)

**Comment by shamoon** [comment]
Ah thanks. It’s not obvious to me why this would happen yet, need to look into it

**Comment by shamoon** [comment]
Yea I still cant reproduce this problem either for `migrate` or `manage_superuser` (btw you might want `createsuperuser` but depends what youre trying to do)

**Comment by SpiderD555** [comment]
I did some additional tests and digging, and I found the issue.
Apparently the problem was with how the manage.py script got called. I used the very same task that the official Ansible paperless-ngx uses, but it failed on me (here it is how it looks):
```
- name: Migrate database schema
  become: true
  become_user: "{{ paperless_service_user }}"
  ansible.builtin.command: "{{ paperless_installdir }}/venv/bin/python3 {{ paperless_installdir }}/paperless-ngx/src/manage.py migrate"
  register: database_schema
  changed_when: '"No migrations to apply." not in database_schema.stdout'
```
Whereas calling this task helped me go through farther:
```
- name: Create paperless db schema
  become: true
  become_user: "{{ paperless_service_user }}"
  ansible.builtin.command: "{{ paperless_installdir }}/venv/bin/python3 manage.py migrate --no-input"
  args:
    chdir: "{{ paperless_installdir }}/paperless-ngx/src/"
  register: database_schema
  changed_when: '"No migrations to apply." not in database_schema.stdout'
  tags: migrate_db```
See how I had to change the folder to **/paperless-ngx/src/**
Once that was done it all went fine. This brings me to a conclusion that somehow manage.py depends on the current system path - it is somehow not a problem for official paperless-ngx ansible playbook (maybe it is somehow executed already inside /paperless-ngx/src/ folder ??) , but for me that was different. Once I used chdir argument it all went fine.
I guess this is a minor problem, but may potentially hit the installation process at some future release. You decide if this worth your time digging into it.
By the way I have my own Ansible role just for that, so I am able to reproduce it 100% of the time.

**Comment by shamoon** [comment]
Im not sure TBH, I dont use ansible (which btw is maintained in a separate repo but sounds like there isnt an issue there per se). I dont think it does happen when executing the commands manually though, at least not that I'm able to recreate.

Thanks for digging into it and reporting back, perhaps someone will find this helpful down the road so always valuable to have a resolution described.
