### ISSUE TITLE
[BUG] Sorting tags by color does not work

### ISSUE THREAD

**Issue by riker09** [paperless-ngx/paperless-ngx#2452]
### Description

When click on the header field for the "Color" column the order of the tags never changes.

### Steps to reproduce

1. Go to "Tag Management"
2. Click on "Color" table header
3. Little arrow besides header name indicates sorting but no changes in sort order occur

### Webserver logs

```bash
Does not apply. (I think?)
```

### Paperless-ngx version

vaultwarden/server:1.26.0-alpine

### Host OS

OpenMediaVault 6.x (Debian)

### Installation method

Docker - official image

### Browser

Browser Firefox 106.0.3 (64-Bit)

### Other

I have pretty much a standard installation, afaik. Sorting other columns like tag name does work and the little arrow appears and changes direction after repeated clicks, so my guess would be the data type for the column is wrong or undefined?

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/1bf6d9165f3d3539640baf882c8295a2935f7bc1

**Comment by shamoon** [comment]
Thanks for reporting, seems not many people have wanted this since I dont think its worked for a long time, maybe ever! =)
The fix will be in our next release.
