### ISSUE TITLE
[BUG] unable to change mail rule order in new frontend

### ISSUE THREAD

**Issue by tsia** [paperless-ngx/paperless-ngx#2455]
### Description

i was setting up mail rules and wasn't able to get them to work properly until i realized that in the django admin i was able to set a order for those rules. in the new frontend the order was already displayed how i actually wanted them to be but in the django admin i was able to see they were in the wrong order

### Steps to reproduce

1. go to django admin
2. change mail order rule
3. go to new mail rule frontend
4. mail rule order doesn't match the django admin order
5. (also there is no way to change the order in the new frontend)

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

1.11.4

### Host OS

Debian 11

### Installation method

Bare metal

### Browser

Firefox 108

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/284e0d3f60f6c8cb789bef3ff415cc36a569e637

**Comment by shamoon** [comment]
Thanks for pointing this out, I can understand why someone might want it. The PR was merged into `dev` and the change will be in our next release
