### ISSUE TITLE
[BUG] Documentation: misleading command for using management utilities on bare metal installation

### ISSUE THREAD

**Issue by ph1248** [paperless-ngx/paperless-ngx#2463]
### Description

In the documentation at 
https://docs.paperless-ngx.com/administration/#management-commands
there is the following description of how to invoke management.py on a bare metal installation: 

```
$ cd /path/to/paperless/src
$ python3 manage.py <command> <arguments>
```

However, this should be invoked as the paperless user which was set up during installation.:

```
$ cd /path/to/paperless/src
$ sudo -Hu <paperless_user> python3 manage.py <command> <arguments>
```
Thanks a lot for the great work, by the way!

### Steps to reproduce

Read the docs :-)

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

N/A

### Host OS

debian

### Installation method

Bare metal

**Comment by amannsbart** [comment]
possibly related to https://github.com/paperless-ngx/paperless-ngx/discussions/668#discussioncomment-4699294

**Comment by shamoon** [comment]
The thing about bare metal, of course, is that the setup and commands like this are often a little different between installs. I don’t think every install will need this but presumably some will, happy to add it as optional to the docs, thanks
