### ISSUE TITLE
[BUG] Filter doesnt apply if i am on page 2+

### ISSUE THREAD

**Issue by oladarula** [paperless-ngx/paperless-ngx#2487]
### Description

if i am in the unfiltered view on page 2 (i assume 2+ but havent tested):

![image](https://user-images.githubusercontent.com/15786629/213921288-7c46f714-c1bb-4603-a5aa-4b14b26eee12.png)

and i select a correspondent filter:
![image](https://user-images.githubusercontent.com/15786629/213921330-1c8fee8a-70bd-4244-8b40-21749851af1c.png)

status indicator keeps circling...
![image](https://user-images.githubusercontent.com/15786629/213921404-e3323e6e-b27b-4abb-81ba-b5a2dc9df2c6.png)

if i click on page1 selector, it refreshes normally and applies the filter.

![image](https://user-images.githubusercontent.com/15786629/213921459-4683a794-cf76-4a16-bba8-ca69279ad296.png)

### Steps to reproduce

see above

### Webserver logs

```bash
nothing in the webserver logs.
```

### Browser logs

```bash
no obvious browser problem.
```

### Paperless-ngx version

1.11.3

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Edge

**Comment by stumpylog** [comment]
It appears you are on page 2, but the filter only has a single page worth of docs.  I don't know if there's a way to force the page to back up

**Comment by shamoon** [comment]
Well theres https://github.com/paperless-ngx/paperless-ngx/issues/1819 but Im sure someone more recently asked about this. I cant reproduce it, I have to think theres another issue or perhaps a more specific set of circumstances to recreate it. If You can enable `DEBUG` but if the call to the API is failing there should be e.g. 5xx errors from Django at least.

**Comment by shamoon** [comment]
It does reset the page number if there are e.g. < 2 pages

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/blob/d94ca2962ebe2758b80d9deae01a20953f0edc46/src-ui/src/app/services/document-list-view.service.ts#L245-L248

**Comment by ChristophCaina** [comment]
Hi @shamoon - I think you refering to my issue with this: "but Im sure someone more recently asked about this." (Issue #2391 -> Discussion 2392)

Since my last reply in the discussion, I haven't really faced this case anymore.
Still I am not quite sure, what exactly has caused it, since nothing has changed on the network side...
