### ISSUE TITLE
[BUG] Date range view no longer works

### ISSUE THREAD

**Issue by patii132** [paperless-ngx/paperless-ngx#2508]
### Description

I recently installed the latest release 1.12.0. Since this upgrade, the view for a date period no longer works correctly. An error message always appears. The error occurs with my saved view as well as when manually selecting the filter for a date period. The other filters, such as for a document type, work. With the previous version 1.11.3 everything still worked.

![Bildschirmfoto 2023-01-25 um 16 43 22](https://user-images.githubusercontent.com/70706251/214608485-3bbfee34-5007-47ce-a284-41bf2014933d.png)

**Browser Request:**
![Bildschirmfoto 2023-01-25 um 16 53 48](https://user-images.githubusercontent.com/70706251/214611137-e9408321-44ac-495a-b273-c874eebd496e.png)

![Bildschirmfoto 2023-01-25 um 16 53 39](https://user-images.githubusercontent.com/70706251/214611177-2b625e8c-234d-4ae7-b95d-35609fa7aab3.png)

### Steps to reproduce

1. Go to Documents
2. select filter "selected on" or "created on"
3. A period is selected

### Webserver logs

```bash
I cannot see any error in the logs
```

### Browser logs

```bash
refer to screenshot in the description
```

### Paperless-ngx version

1.12.0

### Host OS

Raspberry Pi 'arm64'

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

docker-compose.yml

**Comment by shamoon** [comment]
This is related to https://github.com/paperless-ngx/paperless-ngx/pull/2351 , already working on a fix

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/1871ef1a72f995346e9a19cf2795c4d8846a2756

**Comment by shamoon** [comment]
Thanks for reporting, we should be able to get out a small patch release with this in the near future

**Comment by Vortex-TH** [comment]
This is still broken for me in 1.13.0

There's no error message, but when I apply a filter with the date picker, there are 0 results (when there definitely should be some). Selecting 'Last 3 months', 'Last year' etc. does work though.

**Comment by shamoon** [comment]
This bug is definitely not still present nor can I reproduce any issues, if you have a new / separate concern feel free to create a separate thread.

<img width="1664" alt="Screenshot 2023-04-13 at 2 04 09 PM" src="https://user-images.githubusercontent.com/4887959/231882655-c7d5685f-a54b-4fd3-b767-a8079ccdf25d.png">
