### ISSUE TITLE
[BUG] Extended search in comments doesn’t work

### ISSUE THREAD

**Issue by thegodfatherrelish** [paperless-ngx/paperless-ngx#2511]
### Description

The search in the comments of the documents introduced with version 1.12.0 does not work for me.

### Steps to reproduce

Save any word under comments for any document and then search for it.

### Webserver logs

```bash
No entries
```

### Browser logs

```bash
No entries
```

### Paperless-ngx version

1.12.0

### Host OS

Synology DSM

### Installation method

Docker - official image

### Browser

Safari, Chrome

### Configuration changes

None

**Comment by stumpylog** [comment]
Can you [rebuild the index](https://docs.paperless-ngx.com/administration/#index)?  Then make a comment and check

**Comment by thegodfatherrelish** [comment]
I have rebuilt the index. After that, it finds all the comments entered so far. But when you enter a new comment, it is not found - presumably only after a new indexing.

**Comment by shamoon** [comment]
That error isnt related (and can likely be ignored, btw), we'll release the fix for this pretty soon in v1.12.1

Thanks for reporting
