### ISSUE TITLE
[BUG] ASN barcodes not detected

### ISSUE THREAD

**Issue by muued** [paperless-ngx/paperless-ngx#2516]
### Description

Currently paperless uses pikepdf to convert pdf pages to PIL images, which internally [may produce tif or jpg images](https://github.com/pikepdf/pikepdf/blob/3f37e806b68724aac5af96930e21986536f19bd3/src/pikepdf/models/image.py#L503-L519).
Barcode detection however works best on rasterised images.
Currently, the pages are [only rasterised when pikepdf raises an exception](https://github.com/paperless-ngx/paperless-ngx/blob/main/src/documents/barcodes.py#L230-L241). I don't understanding the details of when pikepdf would do that.
For my documents, pikepdf doesn't seem to raise an exception.
My ASN barcodes are not detected.

For my barcode stickers, it would be beneficial (that is, make it a usable feature for me) for the ASN barcode detection feature to always use rasterisation or at least always rasterise them when that feature is enabled.
I also would love to see the dpi of the rasterisation set to 300 ([default is 150](https://linux.die.net/man/1/pdftoppm)) to improve the chances of detecting the barcode and also [match the dpi value used in the convert call](https://github.com/paperless-ngx/paperless-ngx/blob/454264a87f59a354546f487eba258cb01a364b55/src/documents/parsers.py#L190) - or make that a configuration option. This would mean calling [convert_from_path](https://github.com/paperless-ngx/paperless-ngx/blob/92fb390f7baf5e88290062f31cba0804e4dd5d8e/src/documents/barcodes.py#L202) with an additional parameter `dpi=300`.

### Steps to reproduce

Set PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE to True.
Consume a document with an ASN barcode.
Look at the log to see that there are no lines mentioning detected barcodes.

### Webserver logs

```bash
[2023-01-25 20:28:38,689] [INFO] [paperless.management.consumer] Adding /opt/paperless-ng/consumption/20230125_Scan_002072.pdf to the task queue.

[2023-01-25 20:28:38,978] [DEBUG] [paperless.barcodes] Detected mime type: application/pdf

[2023-01-25 20:28:39,756] [INFO] [paperless.consumer] Consuming 20230125_Scan_002072.pdf

[2023-01-25 20:28:39,758] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-01-25 20:28:39,768] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-01-25 20:28:39,780] [DEBUG] [paperless.consumer] Parsing 20230125_Scan_002072.pdf...

[2023-01-25 20:28:40,111] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/opt/paperless-ng/consumption/20230125_Scan_002072.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-zu4zp_z0/archive.pdf'), 'use_threads': True, 'jobs': 6, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-zu4zp_z0/sidecar.txt'), 'optimize': 1}

[2023-01-25 20:29:28,550] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2023-01-25 20:29:28,552] [DEBUG] [paperless.consumer] Generating thumbnail for 20230125_Scan_002072.pdf...

[2023-01-25 20:29:28,579] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-zu4zp_z0/archive.pdf[0] /tmp/paperless/paperless-zu4zp_z0/convert.webp

[2023-01-25 20:29:34,005] [DEBUG] [paperless.consumer] Saving record to database

[2023-01-25 20:29:34,006] [DEBUG] [paperless.consumer] Creation date from parse_date: 2022-07-22 00:00:00+01:00
```

### Paperless-ngx version

1.12.0

### Host OS

Armbian 22.11.4 aarch64

### Installation method

Bare metal

### Other

PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true

**Comment by stumpylog** [comment]
Do you have some documenation or manual that rasterised images work better?  Or that a DPI of 300 is also better?

The `pikepdf` method is used since it's faster and less memory intensive than converting every page to an image, but if per page actually is better, it could be used only instead.

(Also the default for pdf2image is a [DPI of 200](https://github.com/Belval/pdf2image/blob/d415156659f76f898ff2d5c9e2884212ee7fac76/pdf2image/pdf2image.py#L39), so getting closer.

**Comment by muued** [comment]
> Do you have some documentation or manual that rasterised images work better?

When I built my pre-/post-consumption scripts, that was what I read, but I can't find any hard evidence for that claim right now.
Here are some pointers however:
- [Accelerated Shape Detection in Images (W3C)](https://wicg.github.io/shape-detection-api/#image-sources-for-detection) expects a bitmap as input
- [StackOverflow post about jpg vs raster image formats](https://stackoverflow.com/q/1013729) answered in favor of raster image
- [Scanprep](https://github.com/baltpeter/scanprep/blob/4144a729734b45e74a009b20287b179f8b0daf3c/scanprep/scanprep.py#L45) prepares the images as bitmaps before detecting barcodes
- [ZXing](https://github.com/zxing/zxing/blob/dfb06fa33b17a9e68321be151c22846c7b78048f/javase/src/main/java/com/google/zxing/client/j2se/DecodeWorker.java#L136) converts the input to a bitmap before trying to detect barcodes

> Or that a DPI of 300 is also better?

For me, 300 DPI is a good compromise between file size and pdf quality (and scanner speed). So all my scanned inputs use 300 DPI. When playing around with the options when setting up my pre-/post-consumption scripts, setting conversion to 300 DPI helped zbar in recognising my barcodes a lot. I also manually inspected the conversion results (of pdftoppm) and could see a notable improvement for a human eye.

> Having a sample page would be useful too, maybe the ASN isn't getting placed in a image.

I attached a sample page. Note that my prefix is 'O' instead of 'ASN'.
[Test_missed_barcode.pdf](https://github.com/paperless-ngx/paperless-ngx/files/10512793/Test_missed_barcode.pdf)

> The `pikepdf` method is used since it's faster and less memory intensive than converting every page to an image, but if per page actually is better, it could be used only instead.

I see the performance benefit and it may be sufficient for stop pages and potentially larger barcodes. For smaller barcodes (or at least for my case) it doesn't to the trick.

> (Also the default for pdf2image is a [DPI of 200](https://github.com/Belval/pdf2image/blob/d415156659f76f898ff2d5c9e2884212ee7fac76/pdf2image/pdf2image.py#L39), so getting closer.

You are right.

**Comment by stumpylog** [comment]
Thank you, I'll have to do some reading.  The SO about JPEG smoothing is interesting indeed.

**Comment by plankobostjan** [comment]
I've been having issues with barcode detection as well. Sometimes barcodes are detected, sometimes not. So I did some testing.

I've found out that the size of the barcode matters. If it is too small, there's a chance that paperless won't detect it.

At the same time, I have found out that even small flaws in the barcode can lead to paperless not picking it up.

For example, this one was not detected (it's a bit bent and the resolution isn't that good):
![image](https://user-images.githubusercontent.com/17665959/215026572-21b254e8-5734-47f9-a291-494819e66307.png)

But this one (it's exactly the same, just straightened up) was detected just fine:
![image](https://user-images.githubusercontent.com/17665959/215026677-b2ca3c8f-99bc-4405-88cc-8886c15049cc.png)

All in all, assigning ASN using barcodes is a bit unreliable, at least for me. Whether or not this is a problem within paperless, I'm not sure.

**Comment by ritschido** [comment]
Same situation here as well. Left is not detected and right is detected. 
![Greenshot 2023-01-27 13 37 47](https://user-images.githubusercontent.com/110458099/215089350-e37cf515-ba9c-46b5-957f-464829b7ea82.png)

**Comment by stumpylog** [comment]
Do keep in mind we're not writing the actual detection code.  It's dependent on libzbar for that, which hasn't seen many updates recently.  

If to you would like to test more directly, so zbarimg uses the same library against images from the command line.  It it doesn't find the barcode, paperless won't either.

**Comment by stumpylog** [comment]
Yes, I noticed the same result this morning.  I believe zbar is highly sensitive to size of the barcode, actually doing better if the barcode is smaller or perhaps smaller within a large page.  It's frustrating to be sure.

**Comment by stumpylog** [comment]
I've made some updates that hopefully help in at least some cases.  It will still not detect the barcode in the sample file.  

After debugging more, I believe that comes down to the version of `poppler-utils` and libzbar present in Debian Bullseye.  When tested with Ubuntu 22.04, with somewhat more recent versions, it is detected.  Certainly frustrating, but not much we can do about it right now.

The good news, Bookworm has begun freezing for release, and we'll certainly upgrade the base image when possible.
