### ISSUE TITLE
[BUG] Sort arrows point in the wrong direction

### ISSUE THREAD

**Issue by love-will-tear-us-apart** [paperless-ngx/paperless-ngx#2528]
### Description

The sort arrows are pointing in the wrong direction across the web application.

Example: The sort arrow should point downwards when the table is sorted by 'created most recently'.

![Screenshot 26 01 2023 um 15 13 23 PM](https://user-images.githubusercontent.com/123647181/214858351-88736a05-dd46-44d4-ab39-56c302049186.png)

(Sort arrow in screenshot highlighted in red colour.)

### Steps to reproduce

1. Access web application
2. Click on field in table header to change sorting direction
3. See behaviour of sort arrow

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

1.12.1

### Host OS

Debian

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Uh, I have no idea if theres a true convention for this, but they are consistent throughout the app, arrow up means highest at the top?

**Comment by love-will-tear-us-apart** [comment]
Thank you for your response, @shamoon. Shall I file this as a feature request instead?

I think the convention is, that descending order is symbolized by a sort arrow pointing downwards.

It is like that in MacOS for example.

See [https://ux.stackexchange.com/questions/37564/use-up-or-down-arrow-to-represent-sort-ascending-at-table-header](url)

**Comment by shamoon** [comment]
Yea, not sure if stack exchange is definitive source, honestly Im not sure but one thing is that the icons we use which come from Bootstrap are consistent with how it is currently. It would be pretty confusing to have these opposite I think

<img width="195" alt="Screen Shot 2023-01-26 at 8 01 07 AM" src="https://user-images.githubusercontent.com/4887959/214885670-180965f5-458b-4e5e-b2ab-c3990c394b0a.png">

**Comment by love-will-tear-us-apart** [comment]
OK, it's no biggie anyway.. cheers
