### ISSUE TITLE
[BUG] Error when searching documents add the last 7 days

### ISSUE THREAD

**Issue by MehrCurry** [paperless-ngx/paperless-ngx#2533]
### Description

I have save filter which searches for all documents added in the last 7 days. Since upgrade to 1.12.x it does not work anymore. An error is displayed: Fehler beim Laden des Dokuments: Document matching query does not exist.

### Steps to reproduce

1. Go to 'documents'
2. select "last 7 days" as filter for date added
3. error message is shown

Note: filtering with a manual entered date works as expected

### Webserver logs

```bash
error does not show up in the logs
```

### Browser logs

```bash
ERROR 
Object { headers: {…}, status: 400, statusText: "Bad Request", url: "http://diskstation:8000/api/documents/?page=1&page_size=10&ordering=-added&query=added:%5B-1%20week%20to%20now%5D", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://diskstation:8000/api/documents/?page=1&page_size=10&ordering=-added&query=added:%5B-1%20week%20to%20now%5D: 400 Bad Request", error: "Document matching query does not exist." }
​
error: "Document matching query does not exist."
​
headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit() }
​
message: "Http failure response for http://diskstation:8000/api/documents/?page=1&page_size=10&ordering=-added&query=added:%5B-1%20week%20to%20now%5D: 400 Bad Request"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 400
​
statusText: "Bad Request"
​
url: "http://diskstation:8000/api/documents/?page=1&page_size=10&ordering=-added&query=added:%5B-1%20week%20to%20now%5D"
​
<prototype>: Object { … }
main.js:3:52331
```

### Paperless-ngx version

1.12.1

### Host OS

docker compose on synology nas

### Installation method

Docker - official image

### Browser

Firefox

**Comment by natrius** [comment]
Same here, i updated because of https://github.com/paperless-ngx/paperless-ngx/issues/2204 that error and am having the same problem now. If I remember correctly, the last-7-days worked before.

**Comment by MehrCurry** [comment]
I am sure that it worked in 1.11. I had this filter on the start page.

**Comment by shamoon** [comment]
Hmm, There was a similar error #2508, but that was closed and fixed in 1.12.1, I’m not aware of any current issues with this. You don’t indicate precisely what version you’re using but then again the error message you’re seeing is slightly different than that one. Either way I can’t reproduce this

Can folks perhaps try reindexing the search index? See https://docs.paperless-ngx.com/administration/#index

**Comment by MehrCurry** [comment]
It occurs with 1.12.1 and also with 1.12.1-dev.

**Comment by MehrCurry** [comment]
reindexing fixed it

**Comment by shamoon** [comment]
Thanks. The next release will trigger a reindex for docker installs, others may have to do this manually
