### ISSUE TITLE
[BUG] Head requests fails for "ghcr.io/paperless-ngx/paperless-ngx:latest" in watchtower

### ISSUE THREAD

**Issue by Profex** [paperless-ngx/paperless-ngx#2545]
### Description

I am using watchtower for automatic update of "ghcr.io/paperless-ngx/paperless-ngx:latest" docker image

Since a few days watchtower reports the following when checking for updated images for "ghcr.io/paperless-ngx/paperless-ngx:latest"

> Could not do a head request for "ghcr.io/paperless-ngx/paperless-ngx:latest", falling back to regular pull.
> Reason: registry responded to head request with "404 Not Found", auth: "not present"

For all other images which are checked by watchtower in my case (11 others) the error is not showing up

If there is a new paperless-ngx image it will be still downloaded, but error is showing up nevertheless

Based on my investigation this seems to be an issue not only affecting paperles-ngx, but also many other images
And it is caused by an issue connected to "buildx"

References and workarounds:
https://forums.docker.com/t/registry-responded-to-head-request-with-404-not-found/134177/6
https://github.com/containrrr/watchtower/discussions/1529#discussioncomment-4748053
https://github.com/docker/buildx/issues/1509#issuecomment-1378538197

### Steps to reproduce

Let watchtower check for updated "ghcr.io/paperless-ngx/paperless-ngx:latest" image

Watchtower log if no new image is present:

> time="2023-01-26T17:40:49+01:00" level=warning msg="Could not do a head request for \"ghcr.io/paperless-ngx/paperless-ngx:latest\", falling back to regular pull." container=/paperless-ngx-webserver-1 image="ghcr.io/paperless-ngx/paperless-ngx:latest"
> time="2023-01-26T17:40:49+01:00" level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/paperless-ngx-webserver-1 image="ghcr.io/paperless-ngx/paperless-ngx:latest"
> time="2023-01-26T17:41:02+01:00" level=info msg="Session done" Failed=0 Scanned=12 Updated=0 notify=no

Watchtower log if new image is present:

> time="2023-01-26T05:40:49+01:00" level=warning msg="Could not do a head request for \"ghcr.io/paperless-ngx/paperless-ngx:latest\", falling back to regular pull." container=/paperless-ngx-webserver-1 image="ghcr.io/paperless-ngx/paperless-ngx:latest"
> time="2023-01-26T05:40:49+01:00" level=warning msg="Reason: registry responded to head request with \"404 Not Found\", auth: \"not present\"" container=/paperless-ngx-webserver-1 image="ghcr.io/paperless-ngx/paperless-ngx:latest"
> time="2023-01-26T05:42:02+01:00" level=info msg="Found new ghcr.io/paperless-ngx/paperless-ngx:latest image (42a963428916)"
> time="2023-01-26T05:42:11+01:00" level=info msg="Stopping /paperless-ngx-webserver-1 (3476ab9da515) with SIGTERM"
> time="2023-01-26T05:42:26+01:00" level=info msg="Creating /paperless-ngx-webserver-1"
> time="2023-01-26T05:42:35+01:00" level=info msg="Removing image 7820990767c5"
> time="2023-01-26T05:42:43+01:00" level=info msg="Session done" Failed=0 Scanned=12 Updated=1 notify=no

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

1.12.1

### Host OS

Synology DSM

### Installation method

Docker - official image

**Comment by gordon848** [comment]
I can confirm this bug. My watchtower log shows exactly the same since some days.

**Comment by carsten-re** [comment]
Same for me, I can confirm this bug.

**Comment by stumpylog** [comment]
This is something wrong with Watchtower: https://github.com/containrrr/watchtower/issues/1540

**Comment by Profex** [comment]
@stumpylog The link you have added points to the same thing I found before, and based on that it's not a bug of watchtower, but an upstream issue with buildx

https://github.com/containrrr/watchtower/discussions/1529
> This is due to a new format of the manifest that is produced with the new version of docker buildx. The only consequence is that the docker API rate limiting will be applied to every check for an image update, so as long as you don't use a really short interval for watchtower it should be fine. In that case you can set the WATCHTOWER_WARN_ON_HEAD_FAILURE=never environment variable for watchtower, or add the equivalent argument --warn-on-head-failure never (see https://containrrr.dev/watchtower/arguments/#head_failure_warnings).
> 
> If you are responsible for creating said image, you can look at the upstream bug for ways to opt-out of the unsupported manifest until it's supported: https://github.com/docker/buildx/issues/1509#issuecomment-1378538197

**Comment by Profex** [comment]
Issue should be now fixed in latest watchtower release 1.5.2, so it was at the end indeed an issue on their side
https://github.com/containrrr/watchtower/pull/1533
