### ISSUE TITLE
Added Last x Days not including documents added today

### ISSUE THREAD

**Issue by padenj** [paperless-ngx/paperless-ngx#2564]
### Description

The "Added" filter is not including documents added today when using any of the "Last x" filter options.  I have a "Recently Added" view which does not include the most recent documents that were just processed.  If I change the filter to a specific date, for example, `After: 1/1/2023`, then the documents are included in the view.  If I change to "Last 7 days", "Last Month", "Last 3 Months" or "Last Year", then the most recent document in the view is one I scanned 3 days ago.  

### Steps to reproduce

1) Add a new document to Paperless and let it complete processing
2) Open a document view
3) Set the sort to "Added" and descending (z-a)
4) Set the Added filter to "Last 7 days"
  - The document added does not show in the view
 5) Set the Added filter to "After: 1/1/2023"
  - The document added shows in the view

### Webserver logs

```bash
No server messages logged pertaining to the issue
```

### Browser logs

```bash
No browser messages logged pertaining to the issue
```

### Paperless-ngx version

1.12.2

### Host OS

Debian 11 x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

PAPERLESS_TIME_ZONE set to "America/Denver", Date order set to "MDY"

**Comment by stumpylog** [comment]
Strange, no recent changes there that I can see, but it does look to be not returning the correct date range.

**Comment by stumpylog** [comment]
It looks to be a timezone issue.  The query to the index is in local time, but the database and index are using UTC.  Why on earth this is cropping up, I can't say.

**Comment by shamoon** [comment]
Yea that's odd. I guess you're looking at this stumpy?
https://whoosh.readthedocs.io/en/latest/dates.html#about-time-zones-and-basetime

**Comment by stumpylog** [comment]
Thanks, this will be fixed in the next release.  For the time being, using the date based filters will still return correct documents.
