### ISSUE TITLE
[BUG] Debian 11 32bit: document_exporter fails when document creation date <=1901-12-13  or >= 2038-01-20

### ISSUE THREAD

**Issue by ph1248** [paperless-ngx/paperless-ngx#2572]
### Description

I invoked the document exporter with

     sudo -Hu paperless python3 manage.py document_exporter /target/directory --delete --use-filename-format --no-thumbnail --use-folder-prefix --split-manifest

I got the following error message: 
```

 27%|███████████████████████████████▉                                                                                       | 40/149 [00:02<00:07, 14.99it/s]
Traceback (most recent call last):
  File "/opt/paperless/paperless-ngx/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/paperless/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/paperless/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/paperless/.local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/paperless/.local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/paperless/paperless-ngx/src/documents/management/commands/document_exporter.py", line 181, in handle
    self.dump(options["no_progress_bar"])
  File "/opt/paperless/paperless-ngx/src/documents/management/commands/document_exporter.py", line 314, in dump
    t = int(time.mktime(document.created.timetuple()))
OverflowError: mktime argument out of range
```

After some research I found out that the reason is the following: I had some old historic documents without a creation date. I decided to set it to 01.01.1900 to mark them as just "old". Apparently this confused the script. When I set the date to 01.01.1970 and restarted the exporter, everything worked fine.

### Steps to reproduce

1. Set the creation date of a document to 01.01.1900
2. Invoke the document_exporter

### Webserver logs

```bash
none
```

### Paperless-ngx version

1.12.2

### Host OS

Debian 11

### Installation method

Bare metal

### Configuration changes

PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}{created_month}{created_day} {correspondent} {title} PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=true

**Comment by stumpylog** [comment]
It must be another date besides 1.1.1900.  I'm able to export that just fine, as well as call the same code from the command line.

**Comment by ph1248** [comment]
Strange, I just tested it again and was able to recreate it with another document. Are there any logs I could provide? 

One idea, though: I installed it on an old thin client which is 32bit. Could this make a difference?

**Comment by stumpylog** [comment]
It also happens with Windows, not that we support Windows.  A weird little thing for sure.  I do think it can be worked around it in this case, as it is only applicate to encrypted files (which no one should be using anyway)

**Comment by stumpylog** [comment]
Alright, this will be fixed in the next release.  Or at least it will require a 32 bit system utilizing encrypted storage, which has been deprecated as of paperless-ng 0.9.0, so that should be a miniscule segment of users, if any.
