### ISSUE TITLE
[BUG] Search times out

### ISSUE THREAD

**Issue by FunctionDJ** [paperless-ngx/paperless-ngx#2584]
### Description

When using search with either "Title" or "Title & Content", the request is sent but the server doesn't reply (times out reverse proxy after a minute or so).

### Steps to reproduce

Searching using "Title" or "Title & Content" (error doesn't occur when it's empty and therefore omitted from query params of the API call)

### Webserver logs

```bash
[Nothing gets logged into data/log/paperless.log when this issue occurs]
```

### Browser logs

```bash
No error until my reverse proxy responds with a 504 timeout after a minute, which gets logged into browser console.
```

### Paperless-ngx version

1.12.2

### Host OS

Linux Mint x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

docker-compose environment: PAPERLESS_TIME_ZONE: Europe/Berlin       PAPERLESS_OCR_LANGUAGE: [...]    PAPERLESS_AUTO_LOGIN_USERNAME: [...]       PAPERLESS_FILENAME_FORMAT: "{correspondent}/{document_type}/{created_year}/{title}_{created}_{asn}"       PAPERLESS_URL: [...]       PAPERLESS_ENABLE_UPDATE_CHECK: true

### Other

This issue started after i did some thorough digging through my documents, browsing many pages. It didn't occur during a version update.

**Comment by FunctionDJ** [comment]
Addendum: When i navigate to page 0 it's working again, but when i jump to page 24 (my last page), i have that issue again 😳
This seems to be consistent for me.

**Comment by shamoon** [comment]
This sounds a little like #2487

In that case, and others some things:

- It seems to go away often and then people can't reproduce it
- I have suspicions that it is somehow specific to deployment, either OS or network setup, or else
- It does seem like the backend never correctly throws a 404 (or similar) error. Im hesitant to add some kind of timeout to the frontend for this. Would love if there was a more robust backend solution to "catch" this but its not even clear where / why it happens
- Regardless, I still cannot reproduce this

**Comment by FunctionDJ** [comment]
That other ticket was also an official docker image deployment. I'd love to get behind this, but while i'm a working software dev, i don't have any Python skills.
I'll keep this issue updated if i learn anything new.

**Comment by FunctionDJ** [comment]
After reading that other issue i came across #1819. This issue here is clearly a duplicate of that one, so i'll close this one and add any new information there.
