### ISSUE TITLE
[BUG] Checkbox in Documents section does not work properly in Edge browser

### ISSUE THREAD

**Issue by mptr8956** [paperless-ngx/paperless-ngx#259]
**Describe the bug**
If you use Edge browser and try to click a checkbox in front of a document, that works. If I try to uncheck it, its not working. If you click some pixels left or right from the checkbox, unchecking works. 

**To Reproduce**
1. Go to 'Documents section'
2. Click on Checkbox'
3. Try to uncheck the same checkbox

**Expected behavior**
Checking and unchecking should work when clicking the checkbox

**Relevant information**
 - Host OS of the machine running paperless: Win 11 Pro 22000.493
 - Browser Edge
 - Version 98.0.1108.56 (64-Bit)
 - Installation method: Docker on synology

**Comment by shamoon** [comment]
Sorry I cant confirm this. See attached video in Edge (working fine). What browser version are you using? And any more specifics on how to recreate the problem?

https://user-images.githubusercontent.com/4887959/157956943-ac862588-ccb3-40b0-834d-2c9af4fb2cfc.mov

**Comment by 90er** [comment]
I have an issue using Brave (Version 1.36.112) in combination with the documents list view.

In the documents list view i can't use the checkbox by exactly clicking on it with the cursor. When i click close to it (or on the item line) it's working:

https://user-images.githubusercontent.com/17730136/158058127-cb51a54c-1c21-48be-9235-b72367fa4fd2.mov

**Comment by shamoon** [comment]
Separate browser, separate issue. I will test Brave.
