### ISSUE TITLE
[BUG] All assets under /static are not loaded when proxied with Nginx.

### ISSUE THREAD

**Issue by virtadpt** [paperless-ngx/paperless-ngx#2595]
### Description

I have Paperless-ngx installed and working as expected when I interact with Gunicorn directly (http://leandra:8000).  I've been trying to configure proxying through Nginx to make it available under a sub-directory (http://leandra/paperless) but haven't been able to get it to work.  If I go to that URL I get the usual login page but when I authenticate successfully all I get is the "Still here?!" page:

![screenshot-paperless-ngx_login_problem](https://user-images.githubusercontent.com/639730/216680257-da7f1089-65d4-4347-a9c0-31c742ae9a69.png)

I've been tinkering with this for a few weeks but haven't been able to get it to work as expected.  I've gotten a little help from some other folks and made a few configuration changes, but so far no soap.  What I know for sure is that the `PAPERLESS_FORCE_SCRIPT_NAME` and `PAPERLESS_STATIC_URL` configuration directives are being ignored.  I've gone through the _src/paperless/settings.py_ file to see if there were any configuration options that I missed or that weren't in the documentation but haven't found anything helpful.  I've attached the stuff from my server's access.log and error.log files in the appropriate field.

For completeness' sake, here is my paperless.conf file (sans most comments and blank lines) as of my tinkering right now:

```
PAPERLESS_DEBUG=False
PAPERLESS_REDIS=redis://localhost:6379
PAPERLESS_DBHOST=localhost
PAPERLESS_DBPORT=3306
PAPERLESS_DBENGINE=mariadb
PAPERLESS_DBNAME=paperless
PAPERLESS_DBUSER=paperless
PAPERLESS_DBPASS=Icantthinkofacuteredactionthisearly
PAPERLESS_DBSSLMODE=disable
PAPERLESS_CONSUMPTION_DIR=../incoming
PAPERLESS_DATA_DIR=../data
PAPERLESS_TRASH_DIR=../trash
PAPERLESS_MEDIA_ROOT=../media
PAPERLESS_STATICDIR=../static
PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{title}
PAPERLESS_SECRET_KEY=icanhazcheezburger
PAPERLESS_URL=http://leandra
PAPERLESS_LOGROTATE_MAX_SIZE=10485760
PAPERLESS_LOGROTATE_MAX_BACKUPS=10
PAPERLESS_FORCE_SCRIPT_NAME=/paperless

# I've also tried /static/ for PAPERLESS_STATIC_URL and that didn't work.
PAPERLESS_STATIC_URL=/paperless/static/

# I've also tried /static/ for WHITENOISE_STATIC_PREFIX and that didn't work.
# It also doesn't work if I leave WHITENOISE_STATIC_PREFIX commented out.
WHITENOISE_STATIC_PREFIX=/paperless/static/
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_TASK_WORKERS=4
PAPERLESS_THREADS_PER_WORKER=3
PAPERLESS_TIME_ZONE=PST8PDT
PAPERLESS_NLTK_DIR=/home/drwho/nltk_data
PAPERLESS_ENABLE_NLTK=true
```

..and here is the relevant bit from my nginx.conf file:

```
    location /paperless {
        # I've also tried http://127.0.0.1:8000/ - that also doesn't work.  Same thing.
        proxy_pass http://127.0.0.1:8000/paperless;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;

        # It also doesn't work when this is commented out.  Same thing.
        add_header P3P 'CP=""';
        }
```

### Steps to reproduce

1. Follow the instructions for doing a bare metal installation of Paperless-ngx.
2. Follow the instructions for configuring Nginx to proxy Paperless-ngx such that it's accessible from a sub-directory.
3. Restart all Paperless-ngx processes.  Restart Nginx (`sudo systemctl restart nginx`).
4. Go to http://leandra/paperless or http://leandra/paperless/
5. Get stuck at the "Still here?!" page.

### Webserver logs

```bash
access.log:
192.168.0.114 - - [03/Feb/2023:10:38:11 -0800] "GET /paperless/ HTTP/1.1" 200 84
00 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.0.114 - - [03/Feb/2023:10:38:11 -0800] "GET /static/frontend/en-US/style
s.css HTTP/1.1" 404 153 "http://leandra/paperless/" "Mozilla/5.0 (X11; Linux x86
_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.0.114 - - [03/Feb/2023:10:38:11 -0800] "GET /static/frontend/en-US/runti
me.js HTTP/1.1" 404 153 "http://leandra/paperless/" "Mozilla/5.0 (X11; Linux x86
_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.0.114 - - [03/Feb/2023:10:38:11 -0800] "GET /static/frontend/en-US/main.
js HTTP/1.1" 404 153 "http://leandra/paperless/" "Mozilla/5.0 (X11; Linux x86_64
; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.0.114 - - [03/Feb/2023:10:38:11 -0800] "GET /static/frontend/en-US/polyf
ills.js HTTP/1.1" 404 153 "http://leandra/paperless/" "Mozilla/5.0 (X11; Linux x
86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.0.114 - - [03/Feb/2023:10:38:11 -0800] "GET /static/frontend/en-US/apple
-touch-icon.png HTTP/1.1" 404 153 "http://leandra/paperless/" "Mozilla/5.0 (X11;
 Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
192.168.0.114 - - [03/Feb/2023:10:38:12 -0800] "GET /paperless/favicon.ico HTTP/
1.1" 200 111014 "http://leandra/paperless/" "Mozilla/5.0 (X11; Linux x86_64; rv:
108.0) Gecko/20100101 Firefox/108.0"

error.log:
2023/02/03 10:38:33 [error] 1554101#1554101: *113 open() "/srv/http/frontpage/st
atic/frontend/en-US/styles.css" failed (2: No such file or directory), client: 1
92.168.0.114, server: leandra, request: "GET /static/frontend/en-US/styles.css H
TTP/1.1", host: "leandra", referrer: "http://leandra/paperless/"
2023/02/03 10:38:33 [error] 1554101#1554101: *113 open() "/srv/http/frontpage/st
atic/frontend/en-US/main.js" failed (2: No such file or directory), client: 192.
168.0.114, server: leandra, request: "GET /static/frontend/en-US/main.js HTTP/1.
1", host: "leandra", referrer: "http://leandra/paperless/"
2023/02/03 10:38:33 [error] 1554101#1554101: *113 open() "/srv/http/frontpage/st
atic/frontend/en-US/runtime.js" failed (2: No such file or directory), client: 1
92.168.0.114, server: leandra, request: "GET /static/frontend/en-US/runtime.js H
TTP/1.1", host: "leandra", referrer: "http://leandra/paperless/"
2023/02/03 10:38:33 [error] 1554103#1554103: *114 open() "/srv/http/frontpage/st
atic/frontend/en-US/polyfills.js" failed (2: No such file or directory), client:
 192.168.0.114, server: leandra, request: "GET /static/frontend/en-US/polyfills.
js HTTP/1.1", host: "leandra", referrer: "http://leandra/paperless/"
2023/02/03 10:38:33 [error] 1554101#1554101: *113 open() "/srv/http/frontpage/st
atic/frontend/en-US/apple-touch-icon.png" failed (2: No such file or directory),
 client: 192.168.0.114, server: leandra, request: "GET /static/frontend/en-US/ap
ple-touch-icon.png HTTP/1.1", host: "leandra", referrer: "http://leandra/paperle
ss/"
```

### Paperless-ngx version

1.11.3

### Host OS

Archlinux, x86_64

### Installation method

Bare metal

### Browser

Chrome, Firefox, Lynx

### Other

The other webapps I have proxied through Nginx that are exposed through subdirectories are working normally and have been for the life of the server.

**Comment by stumpylog** [comment]
I can say with certainty `PAPERLESS_STATIC_URL` and `PAPERLESS_FORCE_SCRIPT_NAME` aren't being ignored.  They're used to set the relevant Django settings, [FORCE_SCRIPT_NAME](https://docs.djangoproject.com/en/4.1/ref/settings/#force-script-name) and [STATIC_URL](https://docs.djangoproject.com/en/4.1/ref/settings/#static-url)

Have you tried with `http://127.0.0.1:8000`?  Without the trailing slash.

**Comment by shamoon** [comment]
As you can see in https://github.com/paperless-ngx/paperless-ngx/issues/2252 we have a bunch of users who use subpaths without an issue so not sure there's a real bug here. If this works without your RP then you'll need to troubleshoot the nginx config but again, that's not a bug in this codebase.
