### ISSUE TITLE
[BUG] Login does not work after migrating from -ng linuxserver.io docker image

### ISSUE THREAD

**Issue by mptr8956** [paperless-ngx/paperless-ngx#260]
**Describe the bug**
Upgraded vom Paperless-ng to ngx:latest. Login stays and works. After logging out and logging in, Server Error 500 occurs

**To Reproduce**
1. Migrate from latest NG to latest NGX
2. Log out your session
3. Try to login
4. See Server error 500

**Expected behavior**
Login should work without error

**Relevant information**
- Host OS of the machine running paperless: Win 11 Pro 22000.493
- Browser Edge
- Version 98.0.1108.56 (64-Bit)
- Installation method: Docker on synology

**Comment by qcasey** [comment]
Thank you for your report. Is this still occuring after a few minutes running paperless? Sometimes this happens on startup when the backend hasn't fully started.

Could you post the logs of the webserver container?

``docker-compose logs```

**Comment by RaveWithGrin** [comment]
Same issue here after migrating. Attached are the webserver container logs.
[_paperless_webserver_logs.txt](https://github.com/paperless-ngx/paperless-ngx/files/8234817/_paperless_webserver_logs.txt)

**Comment by qcasey** [comment]
Are you also on synology? I know I asked for just the webserver container, but it may be helpful to see the entire stack's logs:

`docker-compose logs`

if you don't mind of course.

**Comment by byrleyar** [comment]
Same issue for me.  Logs attached
[paperlesslogs.txt](https://github.com/paperless-ngx/paperless-ngx/files/8235408/paperlesslogs.txt)

**Comment by qcasey** [comment]
@byrleyar are you also on synology?

**Comment by yschroeder** [comment]
Did you migrate from the official ng image or from the Linuxserver.io one?

**Comment by byrleyar** [comment]
I'm on Linux 20.04 running on a proxmox vm

**Comment by byrleyar** [comment]
Now that you mention it, i migrated from Linuxserver.io

**Comment by yschroeder** [comment]
The two environment variables which set gid and uid are a specialty of the linuxserver.io image are are ignored in the official image. It boils down to a permission problem when accessing the mounted folders in the container.

I would suggest to migrate to the upcoming ngx image by linuxserver.io: https://github.com/linuxserver/docker-paperless-ngx

**Comment by RaveWithGrin** [comment]
I migrated from the official one, running Ubuntu 20.04 as well.
Strangely, after fully tearing down the containers and bringing the stack back up, I'm now able to log in again.

**Comment by mptr8956** [comment]
thanks, yes, I migrated from linuxserver ios as well. I will close that here, as the problem should not occur when migrating with linuxserver ios in the future! :) Thanks anyways!
