### ISSUE TITLE
[BUG]  python3 manage.py migrate MySQLdb.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

### ISSUE THREAD

**Issue by Pakbon** [paperless-ngx/paperless-ngx#2603]
### Description

Mysql/mariadb doesn't work correctly when following the tutorial. Apparently there's a key that's way too long for mysql/mariadb to handle

### Steps to reproduce

1. follow the setup for baremetal: https://docs.paperless-ngx.com/setup/#bare_metal
2. step 9 is creating the database tables until " Applying documents.1012_fix_archive_files" when it errors out because of a key being used that's too long

### Webserver logs

```bash
Applying documents.1012_fix_archive_files...Traceback (most recent call last):
  File "/opt/paperless/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/paperless/.venv/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/opt/paperless/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/paperless/.venv/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/paperless/.venv/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')
```

### Paperless-ngx version

12.2

### Host OS

Debian 10

### Installation method

Bare metal

**Comment by shamoon** [comment]
This is #2094 so closing as a duplicate but please have a look through that one (which eventually was just closed as stale as we never got a reply) and let us know if you have more to add or anything there helps solve it. Looking at it again for a moment I wonder if changing the encoding will solve this

If there’s something we can narrow down on our end to fix we’d be happy to of course but from the other thread it wasn’t apparent if that’s the case or not
