### ISSUE TITLE
[BUG] High CPU Usage after migration from NG to NGX / Problem with rights?

### ISSUE THREAD

**Issue by mptr8956** [paperless-ngx/paperless-ngx#261]
**Describe the bug**
CPU usage is extremely high after migration (constantly between 20 and 60%). Migrated from NG to NGX in Docker on Synology NAS. 

Probably a problem with correct rights? I just did what like the documentation recommends "how to migrate" (change docker image link and restart docker container). Did not change anything, old docker image with paperless-ng still works like a charm.

**Expected behavior**
Low cpu usage during idle sessions, no errors after migration / see Screenshot of LOG file attached. 

**Screenshots**
![image](https://user-images.githubusercontent.com/73469840/157823871-23bae793-5c0f-41f7-aeba-e862a1434e3c.png)

Relevant information

- Host OS of the machine running paperless: Win 11 Pro 22000.493
- Browser Edge
- Version 98.0.1108.56 (64-Bit)
- Installation method: Docker on synology

**Comment by yschroeder** [comment]
This is related to #260.

It cannot start up the worker, so it tries over and over again.

**Comment by mptr8956** [comment]
yes, that was the problem. thanks!
