### ISSUE TITLE
[BUG] Heavy correspondents set leads to slow application loading

### ISSUE THREAD

**Issue by Kaaybi** [paperless-ngx/paperless-ngx#2616]
### Description

At launch, with more than 100k correspondents, Paperless-ngx takes a fair amount of time to be 'ready to use'.

Here are my findings, until all correspondents are loaded we can't:
- In documents list, use correspondent filter
- In documents list, see any correspondents be bound to documents
- In document edit view, assign a correspondent
- In document edit view, save document

On my instance with approximatively 120k correspondents, it takes up to 16.60s to load:
![image](https://user-images.githubusercontent.com/13943086/216928896-d54e422c-155e-444f-9410-5d3f8f8cc391.png)

### Steps to reproduce

1. Create an instance of Paperless
2. Import more than 100k correspondents
3. Import at least one document
4. Launch Paperless-ngx from private navigation

### Webserver logs

_Not necessary_

### Paperless-ngx version

1.12.2

### Host OS

Debian amd64

### Installation method

Docker - official image

### Browser

Firefox

**Comment by stumpylog** [comment]
I'm actually working on adding compression middleware, which would help reduce the size at least.

**Comment by stumpylog** [comment]
Forgot to revisit this, with #2621, the response will be compressed by default, which should improve response times.  I'd be curious to see how much of a savings it ends up being.
