### ISSUE TITLE
[BUG] Too long correspondent name moves document preview

### ISSUE THREAD

**Issue by solarssk** [paperless-ngx/paperless-ngx#2637]
### Description

When we enter the name of the correspondent, which does not fit into the assumed field to be completed, the field expands. As a result, the preview of the document moves to the bottom.

It would be possible to use row wrapping to keep the size and UX without moving the document preview.

<img width="1436" alt="Screenshot 2023-02-09 at 19 19 16" src="https://user-images.githubusercontent.com/83293863/217905804-515033c8-40c3-4f2e-b2e8-c5169b17f329.png">

### Steps to reproduce

1. Add file
2. Fill in the name of the correspondent so that it is long
3. Done

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

1.12.2

### Host OS

Synology NAS (Docker), x86_64

### Installation method

Docker - official image

### Browser

Safari

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/bc91b830ed3651d9235fe87fe207fba2a3c6e9ca
