### ISSUE TITLE
[BUG] Storage path does not accept year/month variants despite the doc says so

### ISSUE THREAD

**Issue by hojason117** [paperless-ngx/paperless-ngx#2650]
### Description

Using the year/month placeholder variants to create storage paths fails with 400 Bad Request.

These year/month variants were introduced in #1906 but only seem to work as the global `PAPERLESS_FILENAME_FORMAT` setting, but not as part of a storage path.

![Screenshot 2023-02-11 at 9 45 10 PM](https://user-images.githubusercontent.com/24447831/218295883-3fca4f59-cb1e-4571-8433-91b995fd3ecc.png)

Not sure if this should be tagged as `bug` or `enhancement`,  but the doc saying

> Each storage path is a `PAPERLESS_FILENAME_FORMAT`

throws me off a bit when I realized that some placeholders don't actually work with storage paths.

### Steps to reproduce

1. Create a storage path
2. Set the path using `created_year_short`/`created_month_name_short`
3. Click save
4. See `Invalid variable detected.` error message

### Webserver logs

```bash
[2023-02-11 21:56:31,746] [WARNING] [django.request] Bad Request: /api/storage_paths/13/
```

### Paperless-ngx version

1.12.2

### Host OS

Ubuntu

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/1d5eb983ea089cacdd7da337f72c8f541df5433c

**Comment by shamoon** [comment]
Thanks for reporting, this will be fixed in our next release
