### ISSUE TITLE
[BUG] Installation script gets stuck on tr

### ISSUE THREAD

**Issue by TryAndErr0r** [paperless-ngx/paperless-ngx#2655]
### Description

Installing paperless-ngx on my raspberry pi via install script. Script get stuck on 
`tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 64 | head -n 1`
I have a feeling that this command behaves diffrently on diffrent distros. On the ubuntu image atleast the command prints out the string and does not return the prompt. Therefore the script does not continue.

Fixed it by replacing 
`SECRET_KEY=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 64 | head -n 1)`
with 
`SECRET_KEY='<the string the command prints to shell when executed manually>`

hope this is usefull - thanks for the great work!

### Steps to reproduce

Execute 
`bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`

### Webserver logs

```bash
-- Error when using installation script
```

### Paperless-ngx version

1.12.2

### Host OS

Raspberry pi arm64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Can you try the change from the linked pull request?  The fix worked for me on Ubuntu, so it should also work on the Debian based pi

**Comment by stumpylog** [comment]
Fixed in the linked merge request.
