### ISSUE TITLE
[BUG] Reduce the number of pages displayed

### ISSUE THREAD

**Issue by solarssk** [paperless-ngx/paperless-ngx#2666]
### Description

When we get to the number of pages, e.g., in Correspondents more than fits on one line, it seems to me that the panel with the page selection will move to the second line - which does not look very nice.

![image](https://user-images.githubusercontent.com/83293863/218532329-a8a44979-34da-4c35-9678-be5fb65aed5f.png)

When narrowing the page in width, the bar moves to the second line, and in case of inability to display all page numbers - the width of the page remains as much as it shows pages.

![image](https://user-images.githubusercontent.com/83293863/218532632-f8f09a76-c55b-464e-85b9-5756e50c7261.png)

![image](https://user-images.githubusercontent.com/83293863/218532706-c2b74480-750a-4318-9d12-0afa696e7646.png)

You can replace this with the example suggestions from the screens - it takes up less space, and looks nice (in my opinion).

![image](https://user-images.githubusercontent.com/83293863/218533426-a67a1bfa-dc21-4e00-bc73-49b031de6a83.png)

![image](https://user-images.githubusercontent.com/83293863/218533468-eae3e396-a1c6-4b2a-b14f-d4fdf755b98b.png)

### Steps to reproduce

Narrow the page width in your browser and see how it behaves.

### Webserver logs

```bash
n/a
```

### Browser logs

```bash
n/a
```

### Paperless-ngx version

1.12.2

### Host OS

Synology NAS (Docker), x86_64

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

n/a

### Other

n/a

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/405c0922f8041939fc4865f640fef4e1b2641813

**Comment by shamoon** [comment]
This was already completed in #2618 

Funny enough I was wondering if anyone really had that many correspondents, I guess we have our answer. Amazing how much variation there is in how people use the software!
