### ISSUE TITLE
[BUG] iOS shortcut errors when the API submission is successful

### ISSUE THREAD

**Issue by qbunt** [paperless-ngx/paperless-ngx#2667]
### Description

When invoking the iOS shortcut with a known working token, the submission to send a PDF into Paperless fires correctly, however displays an erroneous error message. This notification contains zero content, but makes the user think that the submission failed.

There is a success message if statement that either has changed, or is not looking for the right content. I've learned the hard way that 'Get contents of url' _does not_ look for the http status code, but rather the actual body of the page that's returned. In the current version of paperless-ngx, a successful submission returns a UUID string, not "OK" as indicated in the docs. The "OK" the author is likely talking about is the HTTP status code 200 (for OK), not the textual body content of the page.

This was confirmed by running the same test in a REST testing tool.

<img width="637" alt="image" src="https://user-images.githubusercontent.com/187095/218561089-3482bf41-928f-4366-825e-9ab14604b8b5.png">

The last 'if' statement is looking for the response body content 'OK' when it is in fact `"[uuid_of_document]"`. Looking into iOS shortcuts further, I don't think it's possible to grab the status code off the response from the server, so that's why we're seeing the error.

![image](https://user-images.githubusercontent.com/187095/218560528-192c52b7-a33b-4070-842e-8ba18763abe9.png)

### Steps to reproduce

1. set up the iOS shortcut with the auth token & URL as shown
2. find a PDF and trigger the shortcut for `upload to paperless`
3. see the submission fire, and `An error occurred` with no content in it
4. log into paperless-ngx and see the document ingested just fine

### Webserver logs

```bash
No logs are relevant here
```

### Paperless-ngx version

1.12.2

### Host OS

Docker on Debian, x86_64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
I don't think we provide anything for iOS shortcuts.  I find nothing in our docs or files about an iOS shortcut being provided or how to set one up.

If there's one someone created, this is better suited as something to bring up to the creator.

**Comment by qbunt** [comment]
@stumpylog found it in the [wiki here](https://github.com/paperless-ngx/paperless-ngx/wiki/Scanner-&-Software-Recommendations#mobile-phone-software). That said, I have no idea who owns it, it looks like it's coming straight from iCloud. Reason I posted it here is there are other closed tickets that looked relevant

**Comment by stumpylog** [comment]
Ah, the wiki.  It was likely original from in #878 by @dabenzel, who perhaps can update it to check the HTTP code instead of response data.  I have no idea how it's created or can be updated.

**Comment by tooomm** [comment]
#878

It used to be in the docs, but now in the wiki: https://github.com/paperless-ngx/paperless-ngx/wiki/Scanner-&-Software-Recommendations#mobile-phone-software

**Comment by qbunt** [comment]
I'm a new paperless-ngx user, did the API response structure change? I don't know how this worked for anyone in the past

**Comment by stumpylog** [comment]
It has always returned Http 200 on success.  The data returned changed a bit ago

**Comment by shamoon** [comment]
I could have sworn I already updated the shortcut link when we made that API change but I guess not. This one should work: https://www.icloud.com/shortcuts/dab4224978ff48ad8bacf1e224529324

**Comment by qbunt** [comment]
Killer, thanks!!
