### ISSUE TITLE
[BUG] document_exporter document dates are off by one day

### ISSUE THREAD

**Issue by derjoerg** [paperless-ngx/paperless-ngx#267]
**Describe the bug**
When running the document_exporter script with the "-f" flag, all documents (and thumbnails) are off by one day.

**To Reproduce**
1. Running paperless-ngx on a raspi4 within a docker-container (The OS is set to the timezone "Europe/Berlin" and also within docker-compose PAPERLESS_TIME_ZONE is also set to Europe/Berlin). PAPERLESS_FILENAME_FORMAT is set to `{correspondent}/{document_type}/{created_year}/{created_year}{created_month}{created_day}_{title}_{tag_list}`
2. Consume a document as set the date to e.g. 11.03.2022
3. Check that the document is correctly stored with 20220311_xxx.pdf as filename
4. Run the document_exporter script the document (and the thumbnail) is saved as 20220310_xxx.pdf

**Expected behavior**
After running the document_exporter script the document is correctly saved as 20220311_xxx.pdf

**Relevant information**
 - RaspberryPiOS 64bit
 - Chrome
 - 1.6.0 (but was already with 1.5.0
 - docker

**Comment by qcasey** [comment]
Thanks for reporting. Possibly related: #224

**Comment by lippoliv** [comment]
I ran into that yesterday as well. Its a Synology NAS, `TZ` is set to `Europe/Berlin` (if important). One hint regarding #224: It is unrelated to whether the date was auto-detected or not. I can simply set a date myself, the Filename will always be off by one day.

**Comment by Vedeneb** [comment]
The same problem is also present in the `document_renamer`. I used the default filename format previously (e.g. 000000123.pdf) and changed it to something else. After that I ran the document_renamer script and it populated all placeholders correctly, except for the {created_day} being off one day on all my ~800 documents.

**Comment by Vedeneb** [comment]
Just updated to 1.7.0, didn't fix it. So it seems to be a different issue as #224 which was fixed in this release.
When editing the document using the web ui, the filename has the correct date, however after running the `document_renamer` it's off by one day again.
