### ISSUE TITLE
[BUG] PAPERLESS_CONSUMER_RECURSIVE together with PAPERLESS_CONSUMER_IGNORE_PATTERNS not ignoring recursively

### ISSUE THREAD

**Issue by rsaffi** [paperless-ngx/paperless-ngx#2670]
### Description

I am running paperless-ngx on a docker container and my consume folder is mapped as a volume with source from `/mnt/nas/scans`. That consumer folder lives inside a Synology NAS where my scanner saves files directly into various folders. This is the content of `/mnt/nas/scans`:
```bash
Tue Feb 14 10:40:17 ricardo@viserion [0] ~
$ ls -1 /mnt/nas/scans/
banks/
documents/
'@eaDir'/
government/
images/
invoices/
kita/
mail/
medical/
misc/
```

As can be seen above, there exists a folder called `@eaDir`, which is something created by DSM (Synology's NAS OS) to store metadata and some control files, mostly related to indexed content.
Among various other settings, my `docker-compose.env` contains:

- `PAPERLESS_CONSUMER_RECURSIVE=true`
- `PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", "@eaDir/*"]`

The problem is that adding `"@eaDir/*"` to the ignore patterns array doesn't work, since inside `@eaDir` there are multiple subfolders, which will then have the files inside be picked up (see attached file [eaDir_content.txt](https://github.com/paperless-ngx/paperless-ngx/files/10731055/eaDir_content.txt)). Given some of the files are actually thumbnails (so, images), they end up being processed by paperless-ngx and show up in my documents, which is undesired behavior since they not only are very low resolution, but also just a thumbnail of another file that was already correctly processed.

The only way I could have paperless-ngx bypass this limitation was by adding all the various extensions and filename patterns I could find inside the `@eaDir` hierarchy, like so:

`PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", "@eaDir/*", "*.log", "*@SynoEAStream", "*@SynoResource", "*.delete", "*.tmp", "SYNOFILE*", "*THUMB*", "*.cfs", "*.del", "*.fnm", "*.fdt", "*.fdx", "segments*", "*.tis", "*.tii", "*.frq", "*.prx", "*.nrm", "*.tvx", "*.tvd", "*.tvf", "*.lock", "*.gen", ".DS_Store", "@drive*"]`

My problem with this is that it not only is tedious, but especially error prone and doesn't really scale.

Ideally the pattern matching logic should completely ignore everything from within the folder hierarchy after `@eaDir`, which is what I intended by adding `"@eaDir/*"` to the ignore patterns.

Is this behavior by design or something that could be improved on?

Relevant files:
- [docker-compose.env.gz](https://github.com/paperless-ngx/paperless-ngx/files/10731175/docker-compose.env.gz)
- [docker-compose.yml.gz](https://github.com/paperless-ngx/paperless-ngx/files/10731186/docker-compose.yml.gz)

### Steps to reproduce

1. Use a consume folder that has folders with multiple subfolders
2. Configure `PAPERLESS_CONSUMER_RECURSIVE=true`
3. Add one top level folder to PAPERLESS_CONSUMER_IGNORE_PATTERNS (e.g.: `"folder_to_exclude/*"`)
4. Check docker logs and see files inside subfolders of `folder_to_exclude` being picked up for processing

### Webserver logs

```bash
paperless-webserver-1  | [2023-02-14 10:57:56,378] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.fnm: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,379] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.fdt: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,380] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.fdx: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,381] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.tis: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,382] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.tii: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,383] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.frq: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,383] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.prx: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,385] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.nrm: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,386] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.tvx: Unknown file extension.                                                                                
paperless-webserver-1  | [2023-02-14 10:57:56,387] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/SYNO@.fileindexdb/_1jk.tvd: Unknown file extension.                                                                                
(...)
paperless-webserver-1  | [2023-02-14 10:57:56,517] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/documents/@eaDir/document_0005.jpg/SYNOFILE_THUMB_M.jpg to the task queue.                                                                               
paperless-webserver-1  | [2023-02-14 10:57:56,644] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/documents/@eaDir/document_0004.jpg/SYNOFILE_THUMB_S.jpg to the task queue.                                                                               
paperless-webserver-1  | [2023-02-14 10:57:56,658] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/documents/@eaDir/document_0004.jpg/SYNOFILE_THUMB_M.jpg to the task queue.                                                                               
paperless-webserver-1  | [2023-02-14 10:57:56,693] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_.jpg/SYNOFILE_THUMB_M.jpg to the task queue.                                                                                           
paperless-webserver-1  | [2023-02-14 10:57:56,716] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_.jpg/SYNOFILE_THUMB_S.jpg to the task queue.                                                                                           
paperless-webserver-1  | [2023-02-14 10:57:56,741] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_0003.jpg/SYNOFILE_THUMB_M.jpg to the task queue.                                                                                       
paperless-webserver-1  | [2023-02-14 10:57:56,759] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_0001.jpg/SYNOFILE_THUMB_S.jpg to the task queue.                                                                                       
paperless-webserver-1  | [2023-02-14 10:57:56,782] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_0009.jpg/SYNOFILE_THUMB_S.jpg to the task queue.                                                                                       
paperless-webserver-1  | [2023-02-14 10:57:56,801] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_0010.jpg/SYNOFILE_THUMB_S.jpg to the task queue.                                                                                       
paperless-webserver-1  | [2023-02-14 10:57:56,819] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/images/@eaDir/img_0017.jpg/SYNOFILE_THUMB_S.jpg to the task queue.
```

### Paperless-ngx version

1.12.2

### Host OS

Debian GNU/Linux 11 (bullseye) x86_64

### Installation method

Docker - official image

### Configuration changes

See file attached to description.

**Comment by stumpylog** [comment]
Certainly not ideal.  I'll have a look.

**Comment by stumpylog** [comment]
Pathlib's match isn't behaving how I expect in this case.  Despite claiming `match` is glob style matching, it's not really.
```python
>>> Path('@eaDir/tmp/test').match("@eaDir/**")
False
>>> Path('@eaDir/tmp').match("@eaDir/*")
True
>>> Path('@eaDir/tmp/').match("@eaDir/*")
True
>>> Path('@eaDir/tmp/test').match("@eaDir/*")
False
```

There's an open cpython issue about why these don't work.  Something to work around.

**Comment by stumpylog** [comment]
Fixed in the linked PR
