### ISSUE TITLE
[DOCS] Remove PAPERLESS_WORKER_RETRY from docs

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/paperless-ngx#2693]
### Description

In the docs there has been left behind a parameter that is not supported anymore: PAPERLESS_WORKER_RETRY

### Steps to reproduce

.

### Webserver logs

```bash
.
```

### Paperless-ngx version

1.13.0

### Host OS

.

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Thanks for taking the time to report
