### ISSUE TITLE
[BUG] Filesystem path not updating after changing storage path

### ISSUE THREAD

**Issue by leonfilser** [paperless-ngx/paperless-ngx#2695]
### Description

I created a storage path named "Bezügemitteilungen" and assigned it to some of my documents. 
After a little while i decided to rename the path to "bezuegemitteilungen/{title}" and noticed that the renaming is not applied to the host filesystem. I tried to delete the storage path from one of the documents and reassign it. Paperless than created the correct filesystem path and stored the document in it. Problem is that the old path still exists and all the other documents are still stored inside the old path.

### Steps to reproduce

1. Create a new storage path and assign it to some documents
2. Edit the path of the storage path
3. Check if the path on the filesystem was renamed

### Webserver logs

```bash
/
```

### Browser logs

```bash
/
```

### Paperless-ngx version

1.12.2

### Host OS

Ubuntu x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
As a quick fix, you can simply run the renamer and they will be moved.

**Comment by shamoon** [comment]
Yes it may seem counter-intuitive (and a reasonable thing to make a FR to change) but this is expected behavior. It’s already noted in the docs: https://docs.paperless-ngx.com/advanced_usage/#storage-paths and in fact there is a warning in the UI to this effect

![Storage Paths - Paperless-ngx](https://user-images.githubusercontent.com/4887959/219714364-90633dd1-e74c-4e8f-8a69-ecd396da23e1.png)

**Comment by stumpylog** [comment]
I don't recall the reasoning why that's the case.  It seems simple enough to implement with a Django signal

**Comment by leonfilser** [comment]
@shamoon Thanks i just did that and it worked like a charm but i still think its kind of unexpected behavior

**Comment by shamoon** [comment]
I agree, hence the warning in the docs and the UI.

Again, agree with it as a FR but not a bug exactly.

**Comment by shamoon** [comment]
Ps. Was discussed buried in the majillion comments on the original PR :)

https://github.com/paperless-ngx/paperless-ngx/pull/916#issuecomment-1132087824
