### ISSUE TITLE
[BUG] Management list "Filter Documents" shortcuts don't work after loading a saved view

### ISSUE THREAD

**Issue by lotrfan** [paperless-ngx/paperless-ngx#2702]
### Description

The "Filter Documents" actions in the various management views (Correspondents/Tags/etc.) sometimes don't work - looking at the network activity, a request is made to get the list of documents, but the UI doesn't switch to the "Documents" view to actually show them. Afterwards, manually navigating to the main Documents view (via the sidebar) does use the relevant filter.

I think this only happens after a Saved View has been opened at some point during the session; after reloading, the links work as expected (until a saved view is opened).

### Steps to reproduce

1. Open a saved view
2. Navigate to one of the management screens (e.g., Correspondents)
3. Click on "Filter Documents" for one of the rows

### Webserver logs

```bash
n/a, I think - pretty sure this is frontend-only. I've reproduced this on the demo site as well.
```

### Browser logs

```bash
No errors (or any logs) reported. Adding a breakpoint here: https://github.com/paperless-ngx/paperless-ngx/blob/e8a52d48cfa85fbad02be61594c1abd7616efbf0/src-ui/src/app/services/document-list-view.service.ts#L225 [*] shows that `_activeSavedViewId` is non-`null` when this happens; not sure if that's significant.

[*] I haven't tried getting a dev environment set up, so this is using the production build (so the actual breakpoint is a slightly different - however, it's still in `DocumentListViewService.reload`)
```

### Paperless-ngx version

1.13.0

### Host OS

TrueNAS SCALE (running paperless-ngx via helm/k8s)

### Installation method

Docker - official image

### Browser

Chrome, Firefox

**Comment by shamoon** [comment]
Thanks, should be fixed in our next release

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/b15eda94669f302a95abf577472629fd88a5a6c1
