### ISSUE TITLE
[BUG] Documents Stuck in Queue while Mail rule is processing

### ISSUE THREAD

**Issue by widestorm** [paperless-ngx/paperless-ngx#2736]
### Description

Same behaviour as in issue #2649. Manually uploaded files don't process while the mail rule is processing my mail account which is taking abnormally long. I set a limit to 10 days which seems to have lowered the amount of time it takes from around 3-6 hours to around 1.

Although it seems to be persistently causing uploads to not process during the mail scans. Clearing the redis container as mentioned in the linked issue doesn't seem like a great solution since it will stop processing again after a while.

Clearing and uploading again won't help and documents uploaded at 4:54PM are only uploaded an hour later.

mail.log output (busy scanning mails):
![image](https://user-images.githubusercontent.com/78905404/220962031-510413b2-d50b-4691-9212-9e6a32cf1190.png)

paperless.log doesn't show any consumptions while mails are being scanned:
![image](https://user-images.githubusercontent.com/78905404/220962752-7c2bcede-42db-4b0d-8016-0f872888a24f.png)
Note the arrow is around where I uploaded additional documents through the web-ui.

mail.log when mail job is finishing:
![image](https://user-images.githubusercontent.com/78905404/220972462-0a3a10eb-c2a4-4d91-b0b5-6b9d0e9bb1ad.png)

Documents start consuming again right after the job is done:

paperless.log :
![image](https://user-images.githubusercontent.com/78905404/220971943-a15a76ce-b209-4da0-9106-46d2a0679432.png)

### Steps to reproduce

1. Install paperless ngx on Synology DiskStation inspired by this manual: [https://mariushosting.com/synology-install-paperless-ngx-with-office-files-support/](https://mariushosting.com/synology-install-paperless-ngx-with-office-files-support/)
2. I created each container manually and linked them instead of using a portainer stack but the behaviour should be identical.
3. Enable mail-appendix-automation (with a Gmail account)
4. Check if you can add new documents manually. Mine are uploaded, but then get stuck in the queued-section in the file tasks-tab until the mail rule has finished processing.

### Webserver logs

```bash
see images above
```

### Paperless-ngx version

1.13.0

### Host OS

Synology DSM 7.1.1-42962 Update 4

### Installation method

Docker - official image

### Configuration changes

PAPERLESS_CONSUMER_POLLING=30

Edits: Clarity

**Comment by shamoon** [comment]
If you're saying that email processing is finding a bunch of files and your other documents are getting queued behind them that doesn't seem like a bug does it? Presumably your email rules are finding tons of emails / files to process, otherwise they should definitely not be taking that long. You didn't provide details of the rule.

If that's not the case please let us know.

Ps. This isn't the same issue as the one you linked to.

**Comment by widestorm** [comment]
Within 10 days there's perhaps 200 mails so it doesn't seem like it should take 1-2 hours. So a simultaneous processing of mail and uploaded documents should maybe be considered. Although if that's how it should work for now I guess that's definitely no bug then.

Rule here:
![image](https://user-images.githubusercontent.com/78905404/221006314-02e77c8b-a6e7-43dc-afa6-f285ab15304e.png)

**Comment by shamoon** [comment]
200 emails total or 200 with attachments? If the latter then that amount of time isn't so crazy depending on e.g. their contents. But unless you're getting 200 pdfs per day I would expect your email rule to process much more quickly after the initial run(s) if its not picking up any new files.

**Comment by widestorm** [comment]
I'd say 200 total with around 5-10% with pdf attachments. So nothing too crazy. Might have been the initial maximum age setting that was maybe a little too high. I'll keep an eye on it. Thank you very much :)
