### ISSUE TITLE
[BUG] paperless.conf missing from v1.13.0 release archive

### ISSUE THREAD

**Issue by SpiderD555** [paperless-ngx/paperless-ngx#2737]
### Description

When I try to install fresh paperless installation, then there is no configuration file in [release archive](https://github.com/paperless-ngx/paperless-ngx/releases/download/v1.13.0/paperless-ngx-v1.13.0.tar.xz). Ansible can't cope with that.
It existed in release v1.12.2 archive

### Steps to reproduce

1. Use Ansible installation
2. Installation fails when setting up configuration file
Example log message - "paperless.conf does not exist"

### Webserver logs

```bash
Not related
```

### Paperless-ngx version

v1.13.0

### Host OS

Debian 11

### Installation method

Other (please describe above)

**Comment by shamoon** [comment]
That's odd. Perhaps related to https://github.com/paperless-ngx/paperless-ngx/pull/2561

**Comment by stumpylog** [comment]
Probably so.  Weird though, there's a [line](https://github.com/paperless-ngx/paperless-ngx/blob/main/.github/workflows/ci.yml#L454) there that should create it.  I'll have to spelunk a little

**Comment by stumpylog** [comment]
Ah, silly mistake.  Fixed via afcefe3d
