### ISSUE TITLE
[BUG] Opening saved view then search and change tags on documents give message to save view

### ISSUE THREAD

**Issue by ronbruins** [paperless-ngx/paperless-ngx#2756]
### Description

When opening a view, searching and retagging documents then select a different view makes paperless to want to save the view. But it should not, as the view itself is irrelevant as I want to (re)organise documents that ended up in this view (e.g. by tag) See below steps with more details in the 'to reproduce'

### Steps to reproduce

1. **Opening view '2do' which in my case is a view based on a tag** 
![Screenshot 2023-02-26 at 09 21 15](https://user-images.githubusercontent.com/43776917/221395596-a840c11f-8c17-4217-ad1a-0c923cb32cad.png)

2. **enter search text**
![Screenshot 2023-02-26 at 09 22 36](https://user-images.githubusercontent.com/43776917/221395637-78b7cf2e-9f57-4894-a273-bcf71bac42ba.png)

3. **Change some tags and apply**
![Screenshot 2023-02-26 at 09 24 26](https://user-images.githubusercontent.com/43776917/221395693-1bf32524-17ff-4def-9142-513e997c00e1.png)

4.**now when selecting other view paperless asks if it should save current view**
![Screenshot 2023-02-26 at 09 25 28](https://user-images.githubusercontent.com/43776917/221395728-b51b278e-9182-4abe-a8b0-f40b19b12b8e.png)

### Webserver logs

```bash
no logs applicable as it is GUI issue and no error reported
```

### Paperless-ngx version

1.13.0

### Host OS

Ubuntu

### Installation method

Docker - official image

**Comment by shamoon** [comment]
When you searched for text you modified the view, which is why it asked to save. See the * next to the view title
