### ISSUE TITLE
[BUG] Initial Splash Welcome and "Start the Tour" message box never goes away.

### ISSUE THREAD

**Issue by northrup** [paperless-ngx/paperless-ngx#2763]
### Description

I am running version 1.13.0 via a docker image pulled from the official docker hub repo. Paperless-ngx has full permissions to the underlying mounted file structures and otherwise runs correctly, however I cannot for the life of me get it to dismiss the GIANT box in the middle of the dashboard window to start the tour. I've done the tour several times now, clicking all he way through, even clicking on "end". Nothing dismisses this nor the "Start Tour" button at the tome of the Settings UI.

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/11050/221477874-2902035b-3cba-459c-af9f-f076a4d080df.png">

### Steps to reproduce

1. Install stock 1.13.0 Paperless-ngx from docker
2. Take tour
3. Tour message will never disappear

### Webserver logs

```bash
n/a there appear to be no errors in the logs to indicate anything.
```

### Paperless-ngx version

1.13.0

### Host OS

Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

none

**Comment by shamoon** [comment]
I can see how it’s not obvious but that panel doesn’t go away until you add a saved view to the dashboard

**Comment by shamoon** [comment]
But yea, a thought to make it go away after taking the tour. The old panel also used to explicitly say something like “add a saved view to hide this”
