### ISSUE TITLE
[BUG] Sanity check finds a lot of orphaned files after upgrade from 1.11.1 to 1.13.0

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/paperless-ngx#2807]
### Description

Hi,

I did an upgrade from 1.11.1 to 1.13.0. Before the upgrade the sanity checker returned no warnings/errors. After the upgrade for every document I have the sanity checker reports orphaned original, thumbnail and archive files. Besides some files that are reported missing. For the missing: The files are definitely there (hosted on a nas). For the orphaned ones: The saved values in the database did not change. Like archive_filename. So the path to the files pngx is looking for should be the same, shouldn't it? Reverting back to 1.11.1 makes the sanity checker report no issues again. I really need a tip to trace down the root cause here. I couldn't find something in the sanity checker files or the models.py file that has changed and could have had an impact here. And as I said: The entries in the database did not change as far as I can tell. I made a comparison between the two versions. Hm :(

### Steps to reproduce

upgrade from 1.11.1 to 1.13.0

### Webserver logs

```bash
none
```

### Paperless-ngx version

1.13.0

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

**Comment by stumpylog** [comment]
Providing some logs, such as from the sanity checker and the upgrade would be helpful.

**Comment by stumpylog** [comment]
I tested a 1.11 to 1.13 upgrade and couldn't reproduce this.

**Comment by jonaswinkler** [comment]
Unable to reproduce.

**Comment by stevenengland** [comment]
Hi at all, I gather them and then share them with you. I think I will need some time to do so. Maybe in parallel to help me help ;) : When the sanitize checker says 
`[2023-03-03 15:54:04,269] [WARNING] [paperless.sanity_checker] Orphaned file in media dir: /mnt/paperless_ngx/media/data/documents/originals/2021/21_08_07_alternate_Rechnung_220000002.pdf` then it is because he thinks that none of all the docs gathered via

```
# sanity_checker.py
Document.objects.all()
```

will reach this code here that would filter it out, right?
```
# sanity_checker.py
...
        # Check sanity of the original file
        # TODO: extract method
        source_path: Final[Path] = Path(doc.source_path).resolve()
        if not source_path.exists() or not source_path.is_file():
            messages.error(doc.pk, "Original of document does not exist.")
        else:
            if source_path in present_files:
                present_files.remove(source_path) # <-- here the file mentioned should be filtered as it is an original
```

When in the database the filename attribute points to `2021/21_08_07_alternate_Rechnung_220000002.pdf` it should get found, shouldn't it?

**Comment by stevenengland** [comment]
OH NOOOO... Long story short: Error 40, layer 8 problem. Of course...

The root cause was as obvious as it could be... I tackled the issue with different tooling and that made me see what's wrong. Instead of reading my ansible playbook and paperless.conf files for differences again and again I played around with the command

`manage.py diffsettings`

That made me see what I overlooked the whole time... #routine-blinded

```
- MEDIA_ROOT = '/mnt/paperless_ngx/media'
+ MEDIA_ROOT = '/mnt/paperless_ngx/media/data'
```
