### ISSUE TITLE
[BUG] Changing of owner is inconsistent between document details and bulk edit

### ISSUE THREAD

**Issue by jonaswinkler** [paperless-ngx/paperless-ngx#2809]
Issue:

* I've observed that my second user (who is not a super user but has all global permissions), can select other owners in the document details, but then cannot save the document. The save button is greyed out.
* If a user is not allowed to change the owner (this is what I assume is happening here), then the owner field should be read only.
* However, I am able to clear the owner field, and save the document.

However:

* Changing the owner as this second non-super user is possible via bulk edit.

Notes:

* I'm not sure what the expected behavior is.
* I'd assume that changing ownership should be reserved for super users. Normal users should not have this option?

**Comment by shamoon** [comment]
The intent currently is that if you own a doc you can 'give it away' by changing the owner, so the first part is a bug i.e. that user should be able to change the owner and save that.

Unless we disagree with that design?

**Comment by shamoon** [comment]
First part above is already solved in https://github.com/paperless-ngx/paperless-ngx/commit/9ffebd31cfa11bc0434c8a887a2e514b7f89a559 , just need to troubleshoot something else

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/62e756a11ec6d2bc4282d10320bb2924a0cd9c40
