### ISSUE TITLE
[BUG] Suggestions allow editing on read only documents

### ISSUE THREAD

**Issue by jonaswinkler** [paperless-ngx/paperless-ngx#2811]
Issue:

1. Create a document and assign permissions so that a different user is able to view it, but not edit it.
2. The document edit form should have suggestions, such as dates or correspondent.
3. Open the document as the other user.
4. Click on suggestion.

Actual behavior:

* The edit form fields update.

Expected behavior:

* Nothing should happen. At best, the suggestions aren't displayed at all.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/f0fa726e718c93c626b3cb2401fb077f10d74e16
