### ISSUE TITLE
[BUG] Unable to edit permissions as super user on documents owned by other users

### ISSUE THREAD

**Issue by jonaswinkler** [paperless-ngx/paperless-ngx#2812]
Issue:

1. Create a super user
2. Create another user
3. Add docs while logged in as the super user (owner=super user)
4. Using bulk edit (or i assume just editing details works too), set owner to the other user.

Observed Behavior:

Currently logged in super user is no longer able to edit the document (and reset owner for example)

Expected behavior:

Super user should be able to edit all permissions (?)

Notes:

This is what I'd expect. My closest comparison is the super user on unix, who is also allowed to do almost anything, pretty much.

**Comment by shamoon** [comment]
Yea this is intentional at the moment, we can change it if we think superusers should be able to do this, I guess your vote would be yes, Im OK with that

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/2d3cf43bc5b0f1bae7dd58784247af8354aa0d0a
