### ISSUE TITLE
[BUG] Front end unable to handle changing the password of the currently logged in user

### ISSUE THREAD

**Issue by jonaswinkler** [paperless-ngx/paperless-ngx#2814]
Issue:

* Try changing the password of your own currently logged in user account. The Django session is invalidated, but the front end doesn't seem to be able to properly handle that. now some login form of my browser is displayed instead.

![Image](https://user-images.githubusercontent.com/17569239/222854298-37e14136-6e60-414b-af94-a3f1bcffb74a.png)

Expected behavior:

* Log out the current user, and display the real login form again (or somehow tell django to keep the session alive)

**Comment by shamoon** [comment]
Ah yea that’s not handled, at first changing password wasn’t enabled at all. Curious what you think the best solution is here, force logout?

**Comment by JigSawFr** [comment]
I've a similar issue for something different on my side,
I'm using "PAPERLESS_ENABLE_HTTP_REMOTE_USER" env var which was working great,
But now, even if i'm logged to the proxy, paperless show me a Basic Auth.
Seems to request "/api/ui_settings/" and give answer: "www-authenticate: Basic realm="api""

**Comment by shamoon** [comment]
@JigSawFr are you using the `dev` branch i.e. with permissions? In general I don't think its the same issue so please make a separate discussion.

**Comment by JigSawFr** [comment]
> @JigSawFr are you using the `dev` branch i.e. with permissions? In general I don't think its the same issue so please make a separate discussion.

No sorry, I'm on main branch

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/70ac696f178fb5d5687ba5057c0d554da79caec1
