### ISSUE TITLE
[BUG] Bulk edit permissions buttons not disabled during operation

### ISSUE THREAD

**Issue by jonaswinkler** [paperless-ngx/paperless-ngx#2815]
Issue:

* Updating permissions on many documents using bulk edit takes a long time.
* After clicking "Confirm" in the permissions bulk edit dialog, the button stays enabled and can be clicked multiple times.

Expected behavior:

* Buttons should be disabled during operation, both to indicate that something is happening as well as to prevent double clicks.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/19b9fd05783416bd3389bf6cce1191a6e7fd27b2
