### ISSUE TITLE
The selected ocr language XXX is not installed.

### ISSUE THREAD

**Issue by flemmingss** [paperless-ngx/paperless-ngx#2824]
### Description

I tried to use the official container to install this on UnRAID. and with this settings it did not work, the container just stop and terminate the log/console.
```
PAPERLESS_OCR_LANGUAGE: nob+eng+fas
PAPERLESS_OCR_LANGUAGES: nob+eng+fas
```
![image](https://user-images.githubusercontent.com/25674067/222914583-8ad295c7-e27a-495c-bf9a-ec1decfa760e.png)
Then I tried removing nob:
![image](https://user-images.githubusercontent.com/25674067/222914619-c9b548fe-abb7-4568-a5b9-78c574f2452d.png)
When I have just eng it looks like it works.

Are these languages not supported or why does they not work?

### Steps to reproduce

docker config:
PAPERLESS_OCR_LANGUAGE: nob+eng+fas
PAPERLESS_OCR_LANGUAGES: nob+eng+fas

### Webserver logs

```bash
ref pictures
```

### Paperless-ngx version

Paperless-ngx 1.13.0

### Host OS

UnRAID 6.11.5 2022-11-20 (Linux 5.19.17-Unraid x86_64)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
`PAPERLESS_OCR_LANGUAGES` is space separated.

**Comment by flemmingss** [comment]
I tested with nob only, same result

**Comment by stumpylog** [comment]
Tesseract calls Norwegian nor: https://packages.debian.org/bullseye/tesseract-ocr-nor

**Comment by flemmingss** [comment]
> Tesseract calls Norwegian nor: https://packages.debian.org/bullseye/tesseract-ocr-nor

That did not help
![image](https://user-images.githubusercontent.com/25674067/222954179-7008f885-61c1-4b5e-932c-d878ee9c23b2.png)

**Comment by stumpylog** [comment]
High up in the log is where install happens. What does that say?

**Comment by tooomm** [comment]
When looking into the [docs](https://docs.paperless-ngx.com/configuration/#ocr), it tells me you should set it up like this in your case I guess:
>`PAPERLESS_OCR_LANGUAGES=nob fas`
>`PAPERLESS_OCR_LANGUAGE=nob+eng+fas`

**Comment by stumpylog** [comment]
It's trying to install nor+eng above, which isn't a valid package and fails.  So you still have a + in the setting, at least in the above screenshot.

**Comment by flemmingss** [comment]
> tooomm

That's true. Idk why it tried that because I changed to nor only .. Anyway, when trying now with just nor it worked.
Also, Tried the configuration [tooomm](https://github.com/tooomm) pointed out with spaces on `PAPERLESS_OCR_LANGUAGES`, and that worked also. "far" does not work, however that is not a impotent language to have in my setup.
![image](https://user-images.githubusercontent.com/25674067/222976383-20a97cff-dee8-4588-914c-d89fc3688b1c.png)

**Comment by tooomm** [comment]
Have a look here: https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html

`far` is also not a supported language code, in case you are looking for Persian it needs to be `fas`.

This will update in the docs soon as well and provide better help, just today I created a PR for it.

**Comment by tooomm** [comment]
> Not sure though when to use `:` and when `=`. Also, `=` should not be followed by spaces?

@stumpylog can you help me here, please?

**Comment by stumpylog** [comment]
That comes down to how one has configured things and how one likes their YAML to look.

In a .env or .conf file:
```
PAPERLESS_DBHOST=localhost
```
or in the `docker-compose.yml`
```yaml
environment:
  PAPERLESS_DBHOST: localhost
```
or
```yaml
environment:
  - PAPERLESS_DBHOST=localhost
```

are all equivalent.
