### ISSUE TITLE
[BUG] Gmail 'tag' rule removes current label on email

### ISSUE THREAD

**Issue by damomato** [paperless-ngx/paperless-ngx#2856]
### Description

Some of my emails in Gmail are labeled when received and Gmail supports emails having multiple labels. When paperless imports the email attachment the current label is removed and replaced by the 'Paperless' (my action parameter) label.

Is there any way for the 'Paperless' label to be added as an additional label without removing current labels?

### Steps to reproduce

1. In Gmail labels an email
2. Paperless consumed email with attachment
3. Email now has original label removed and action parameter label added

### Webserver logs

```bash
.
```

### Paperless-ngx version

1.13.0

### Host OS

Synology

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Thanks, fixed in the linked pull request.  The label will be appended to any existing labels.

**Comment by damomato** [comment]
Wow so fast, thanks!
