### ISSUE TITLE
[BUG] Can't view/load certain documents in Chrome (,') - ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

### ISSUE THREAD

**Issue by freezingDaniel** [paperless-ngx/paperless-ngx#2887]
### Description

I found a bug in viewing Documents that include , AND ' in the file path in Chromium based browsers. (Also happens on freshly installed paperless with default settings)

Editing window opens up but doesn't show document preview.
Attempting to download or preview causes Chromium (Brave in my case) to throw ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION.

This might help solving the issue:
https://www.ryadel.com/en/err_response_headers_multiple_content_disposition-error-google-chrome-fix/

### Steps to reproduce

1. Rename Document "Let's meet every monday, tuesday and friday"
2. Save
3. Reopen document or try to preview/download

or

1. Rename Correspondent "Tony's"
2. Rename Document to "Pizza, Pasta and more"
3. Save
4. Reopen document or try to preview/download

### Webserver logs

```bash
--
```

### Browser logs

```bash
--
```

### Paperless-ngx version

1.13.0

### Host OS

Manjaro Linux x86_64

### Installation method

Docker - official image

### Browser

Chromium Version 111.0.5563.64 (Official Build) Arch Linux (64-bit)

### Configuration changes

docker-compose.env: PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{created}-{title}

**Comment by stumpylog** [comment]
The proposed fix from the article is already done is both places we directly control the content setting:
https://github.com/paperless-ngx/paperless-ngx/blob/851b23fb09150981b01f1b5fd4b03ef028f88510/src/documents/views.py#L318

https://github.com/paperless-ngx/paperless-ngx/blob/851b23fb09150981b01f1b5fd4b03ef028f88510/src/documents/views.py#L845

I guess replacing commas with something else, like underscores

**Comment by freezingDaniel** [comment]
~~Removing the comma or replacing it with underscores also seems to be the generally recommended fix.~~ If it is the comma, but...

Because I found it a bit odd that the resources I found talk only about the comma.
I tested again with ng (because I didn't recall having the issue there) and could not reproduce the issue. So after seeing that ng still generated the Content-Disposition header differently and the bug only occurs when the comma is paired with an apostrophe I had to dig deeper.

I believe that the problem stems from the filename encoding to ascii which converts the string into a byte literal:
- `filename="its"` -> `filename="b'its'"`
- `filename="it's"` -> `filename="b"it's""`

Firefox AND Chrome seem to be able to handle the `"b"it's""` example, but both fail as soon as there's an additional `,`.
While Firefox just assumes the file name is b and appends the filetype itself => `b.pdf`, chrome fails a bit more roughly, throwing the `ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION`-error.

I assume a solution could be to _(1)_ not encode the string to keep as is (but if I understand correctly from the comment that breaks firefox), _(2)_ to decode the string right after to remove the b-notation and non-ascii-characters or _(3)_ since the decode alters the original name anyways, just remove commas altogether. ¯\_(ツ)_/¯

Headers as received by browsers:
| content-disposition | Broken in Chrome '+, | Works ,| Works ' |
|---------------------|----------------------|--------|---------|
| NGX | **`inline; filename="b"2023-03-14 Let's meet every monday, tuesday and friday.pdf""; `<br />`filename*=utf-8''2023-03-14%20Let%27s%20meet%20every%20monday%2C%20tuesday%20and%20friday.pdf`** | `inline; filename="b'2023-03-14 Lets meet every monday, tuesday and friday.pdf'"; `<br />`filename*=utf-8''2023-03-14%20Lets%20meet%20every%20monday%2C%20tuesday%20and%20friday.pdf` | `inline; filename="b"2023-03-14 Let's meet every monday tuesday and friday.pdf""; `<br />`filename*=utf-8''2023-03-14%20Let%27s%20meet%20every%20monday%20tuesday%20and%20friday.pdf` |
| NG  | `inline; filename="2023-03-14 Let's meet every monday, tuesday and friday.pdf"` | `inline; filename="2023-03-14 Lets meet every monday, tuesday and friday.pdf"` | `inline; filename="2023-03-14 Let's meet every monday tuesday and friday.pdf"` |

**Comment by stumpylog** [comment]
Fixed via #2892
