### ISSUE TITLE
[BUG] Tag filtering counts are off

### ISSUE THREAD

**Issue by stumpylog** [paperless-ngx/paperless-ngx#2921]
### Description

When dropping down the box to filter via tag (may apply to other filters) the count is showing as 0 until the tag is clicked on:
![image](https://user-images.githubusercontent.com/797416/226382851-5ce5729c-e0ae-4e4c-82b6-6f5ac0396e3d.png)

![image](https://user-images.githubusercontent.com/797416/226382963-017e72da-5a24-4383-960a-1d01c7d70dcb.png)

Probably related to #2893

### Steps to reproduce

Create tags (ie many of them from subdirectories), then look at resulting filter counts

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

dev

### Host OS

x

### Installation method

Docker - official image

**Comment by shamoon** [comment]
That's odd indeed, I can't reproduce (screenshot). Anything more specifically about this case that might help track it down?
<img width="1521" alt="Screenshot 2023-03-20 at 8 28 19 AM" src="https://user-images.githubusercontent.com/4887959/226388649-0c1fdddf-157d-4b3c-b200-a3ec6b27acc0.png">
