### ISSUE TITLE
[BUG] Email rule with correspondent assignment from sender doesn't work

### ISSUE THREAD

**Issue by wellmeyer** [paperless-ngx/paperless-ngx#293]
Docker on Synology NAS, migrated from linuxserver/paperless-ng

All is working so far (after adjusting environment variables) except mail rule:
- Create mail rule with "Korrespondent zuweisen von:" (probably "Assign correspondent from") as third option "Absendername benutzen (oder E-Mail-Adressen, wenn nicht verfügbar)" (probably "Use sender name (or mail addresses if not available)")
- After running rule check mail log:
___
`[2022-03-12 16:55:58,489] [ERROR] [paperless_mail] Rule xx.xxx@gmail.com.Gmail 30d PDF only: Error while processing mail 40169: argument of type 'EmailAddress' is not iterable

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule

    processed_files = self.handle_message(message, rule)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 266, in handle_message

    correspondent = self.get_correspondent(message, rule)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 138, in get_correspondent

    and "name" in message.from_values

TypeError: argument of type 'EmailAddress' is not iterable`
___
After changing this setting to "Keinen Korrespondenten zuweisen" (perhaps "Don't assign correspondent") the rule works and produces content.

Best,
Norbert

**Comment by 90er** [comment]
I have the same issue running the Stack on my Synology NAS in Docker.

```
[2022-03-13 11:45:18,265] [ERROR] [paperless_mail] Rule <xx>.<xx>: Error while processing mail 1: argument of type '
EmailAddress' is not iterable                                                                                                                   
Traceback (most recent call last):                                                                                                              
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule                                                           
    processed_files = self.handle_message(message, rule)                                                                                        
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 266, in handle_message                                                             
    correspondent = self.get_correspondent(message, rule)                                                                                       
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 138, in get_correspondent                                                          
    and "name" in message.from_values                                                                                                           
TypeError: argument of type 'EmailAddress' is not iterable
```

I used this setting (which leads to the error above):
Assign correspondent from:
-> Use correspondent selected below
-> Assign this correspondent: (My user)

It's working with:
-> Do not assign a correspondent

**Comment by 90er** [comment]
Attached you can see the Docker Images i use if this helps. I run the Stack without docker-compose.

<img width="250" alt="Screenshot 2022-03-13 at 17 23 27" src="https://user-images.githubusercontent.com/17730136/158069139-60cec69e-bfc1-4447-869f-2c0799c17e60.png">

**Comment by Tooa** [comment]
I had no luck reproducing this yet. See below my steps:

```bash
$ docker-compose -f docker-compose.sqlite.yml up -d
$ docker-compose -f docker-compose.sqlite.yml run --rm webserver createsuperuser
[...]
```

Login and create mail account, correspondent and mail rule as follows:

![image](https://user-images.githubusercontent.com/5375334/158256011-d498c20d-b3df-43dd-a617-aedecc7c1556.png)
![image](https://user-images.githubusercontent.com/5375334/158255270-483a5884-ac9e-4654-a7bc-37a60792d50f.png)

I created an unread mail in my inbox with a PDF `bug.pdf` attached containing the word `bug`. I then triggered the mail consumer:

```bash
$ docker exec -it 218 mail_fetcher
[2022-03-14 20:21:23,246] [INFO] [paperless_mail] Rule Test Mail.bug_rule: Consuming attachment bug.pdf from mail bug from mail@XXXXX
20:21:23 [Q] INFO Enqueued 1
```

Log looks fine:

```bash
webserver_1  | [2022-03-14 20:21:23,411] [INFO] [paperless.consumer] Consuming bug.pdf
webserver_1  | [2022-03-14 20:21:26,814] [INFO] [paperless.consumer] Document 2022-03-14 Mail user bug consumption finished
webserver_1  | 20:21:26 [Q] INFO Process-1:1 stopped doing work
webserver_1  | 20:21:26 [Q] INFO Processed [bug.pdf]
webserver_1  | 20:21:27 [Q] INFO recycled worker Process-1:1
webserver_1  | 20:21:27 [Q] INFO Process-1:5 ready for work at 131
```

Did I get something wrong in my test setup? Please assist. Willing to fix the issue once I can reproduce it.

**Comment by shamoon** [comment]
Closed in branch
