### ISSUE TITLE
[BUG] The `Date created` cannot be correctly extracted from arXiv manuscripts

### ISSUE THREAD

**Issue by hzxie** [paperless-ngx/paperless-ngx#2933]
### Description

Paperless-ngx cannot recognize the correct date from arXiv PDFs.

### Steps to reproduce

1. Upload an [arXiv manuscript](https://arxiv.org/pdf/1901.11153.pdf)
2. The `Date created` field should be 29/07/2019. But Paperless was recognized as 01/07/2019.

### Webserver logs

```bash
No logs are related to this issue.
```

### Paperless-ngx version

1.13.0

### Host OS

CentOS Stream release 9

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
Setting an initial created date is just a guessing game, based on things which look date like.  There's nothing special about a particular PDF, just the content and date like things which come first.

**Comment by stumpylog** [comment]
Looking at the document content the string `Jul 2019` is picked up first and utilized, ending up with July 1, 2019.  There's a reason the field is editable, it's just not possible to accurately locate every date in every format.

As such, this isn't a bug, but expected.

**Comment by hzxie** [comment]
Many research scientists use paperless-ngx to read papers. And arXiv is the largest website to publish preprint papers.
Do you have any plans to support the arXiv date format?
I can help to create a pull request if you can tell me **where** to add the code.
