### ISSUE TITLE
[BUG] Preview Button downloads PDF

### ISSUE THREAD

**Issue by newhinton** [paperless-ngx/paperless-ngx#2934]
### Description

When i use the preview button:

![image](https://user-images.githubusercontent.com/25279821/227187549-ef297d7e-9d3c-48ec-9670-e09c21a41ad4.png)

Paperless downloads the pdf. I would expect it to open the pdf either in the current, or a new tab.

### Steps to reproduce

1. Go to any document list
2. Click "eye"-button 
3. Download Starts

### Webserver logs

```bash
No logs
```

### Browser logs

```bash
PDF f4754a895794a9e****77260822b [1.7 pikepdf 6.2.8.post1 / ocrmypdf 14.0.2 / Tesseract OCR-PDF 4.1.1] (PDF.js: 3.4.62 [9cea76483]) viewer.js:1470:13
```

### Paperless-ngx version

1.12.1

### Host OS

Raspberry Pi

### Installation method

Docker - official image

### Browser

Firefox 111

### Other

Kubuntu as Client Host

**Comment by stumpylog** [comment]
I've not able to reproduce this with either Chrome or Firefox.  In both, it opens the document in a new tab.

**Comment by shamoon** [comment]
Yes this is going to be deployment-specific, either your reverse proxy, perhaps something in the browser. The link is in the end a plain anchor and does not have the download attribute set

**Comment by newhinton** [comment]
The issue is firefox: it is set to automatically download pdf's. This overrides the `content-disposition: inline;` header the api-endpoint has set, and downloads the file. If i unset this, or use chromium, it works as intended.

So now the question is: is this something paperless wants to "fix"? I personally would preferr paperless to open a popup similar to the hover-action. 

Is there anything i can do to make this work without changing firefox' behaviour which i like the way it is?

**Comment by shamoon** [comment]
I don’t understand exactly your suggestion. You have a setting in your browser that it sounds like is doing exactly what it should. Our current implementation provides good behavior for all other users (for example using keyboard keys to make the button download, open a new tab, etc) so I don’t think we would change things on our end.

**Comment by shamoon** [comment]
The fact that it is a “plain” anchor to a pdf file is a plus to me, it makes it more compatible. I suppose you could open a FR for this but without significant community interest I would not push for this personally.

Out of curiosity, it sounds like that FF setting sort of inverts the behavior of clicking links like this. For me (and I think most browsers), option-click downloads the file directly (again a useful part of the current implementation), I wonder if option-click does the opposite in your case?

**Comment by newhinton** [comment]
> Out of curiosity, it sounds like that FF setting sort of inverts the behavior of clicking links like this. For me (and I think most browsers), option-click downloads the file directly (again a useful part of the current implementation), I wonder if option-click does the opposite in your case?

Sadly no. But i cant reprouce it either with the ff-setting set to open.
My observed behaviour:

|Firefox-PDF-Setting | Click-Combination | Result |
|---|---|---|
|Download | Left-Click | Downloads PDF |
|Download | Left-Click + Ctrl | Downloads PDF |
|Download | Left-Click | Downloads PDF |
|Directly Open | Left-Click | Opens pdf in new tab, switches to tab |
|Directly Open | Left-Click + Alt| Toggles preview Popup |
|Directly Open | Left-Click + Ctrl| Opens pdf in new tab, does not switch |
|Directly Open | Scrollwheel-Click| Opens pdf in new tab, does not switch |

I use Firefox 111 on Kubuntu, maybe that makes a difference.
