### ISSUE TITLE
[BUG] Installation fails - ApplyLayer exit status 1 stout: stderr

### ISSUE THREAD

**Issue by bub4** [paperless-ngx/paperless-ngx#3001]
### Description

i tried to install the project by following the setup script:
https://docs.paperless-ngx.com/setup/#docker_script

There I get following error:
failed to register layer: ApplyLayer exit status 1 stout: stderr: unlinkat /us/local/lib/python3.9/site-packages/pkg_resources/tests/data/my-test-package-source: invalid argument

I also tried to install it by following a youtube guide with portainer and stacks.
https://www.youtube.com/watch?v=ycLwmM0UZ4Q
https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.portainer.yml

It fails to deploy as well.
I seems not to pull all images correctly (not sure).

I tried the ubuntu standard docker engine: version 20.10.21, build 20.10.21-0ubuntu1~22.04.2,
as well as the latest version 23 

### Steps to reproduce

https://docs.paperless-ngx.com/setup/#docker_script

### Webserver logs

```bash
no running server
```

### Paperless-ngx version

latest

### Host OS

Ubuntu 22.04 LXC (proxmox)

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
This very much seems like an issue with your setup, either Proxmox or the Docker version.  A quick search turns up several threads with the same general message.  Perhaps there's a solution in one of those?

**Comment by stumpylog** [comment]
A relevant looking thread: https://forum.proxmox.com/threads/docker-failed-to-register-layer-applylayer-exit-status-1-stdout-stderr-unlinkat-var-log-apt-invalid-argument.119954/

**Comment by bub4** [comment]
Oh F*** - you are totally right! I was just wondering as the yt guy made it working with the same setup 2 months ago. 

Thanks for making this clear and sorry to bother you!!
