### ISSUE TITLE
[BUG] Background for plain text document in dark mode results in illegible text

### ISSUE THREAD

**Issue by jat255** [paperless-ngx/paperless-ngx#3004]
### Description

When previewing a text document on the edit page while dark mode is enabled, the document is illegible because it is black text on a black background:

![image](https://user-images.githubusercontent.com/1278301/229411670-26a550a2-6e9f-4d7e-9e55-12cfc26f91dc.png)

Highlighting the text shows it's present, but it can't be seen due to the colors:

![image](https://user-images.githubusercontent.com/1278301/229411786-6908ed4e-6003-490f-a211-5ed5738860df.png)

[This PR](https://github.com/paperless-ngx/paperless-ngx/pull/9) was meant to fix the original issue I had reported on paperless-ng [here](https://github.com/jonaswinkler/paperless-ng/issues/1228) . That style is getting applied via the `bg-white` class, but according to my devtools, the background color is getting overridden via the `--pngx-bg-darker` SCSS variable somewhere:

![image](https://user-images.githubusercontent.com/1278301/229412305-900a29f3-cf00-454a-812b-a08de30fe1d9.png)

```CSS
body.color-scheme-dark .preview-sticky.bg-white {
    background-color: var(--pngx-bg-darker)!important
}
``` 

> As an aside, I was a small contributor to the original Paperless back in the day, and I just wanted to commend you guys on getting NGX organized and running. That's not a small effort by any stretch, and it's great to see this great tool live on. Great job!

### Steps to reproduce

1. Create a text only document (.txt format)
2. Enable dark mode
3. Go to Edit page for that document to observe invisible text

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

Paperless-ngx 1.14.0-beta.rc1

### Host OS

Debian Bullseye (Docker built locally)

### Installation method

Other (please describe above)

### Browser

Chrome

**Comment by shamoon** [comment]
Ah, interesting. Am I correct in thinking that you have Paperless in dark mode but your OS (or maybe browser) in regular? For me (macOS) I have my OS in dark mode so the text is white so a white background actually causes illegible text for me, opposite of what youre describing, see screenshot.

<img width="1840" alt="Screenshot 2023-04-03 at 3 56 48 AM" src="https://user-images.githubusercontent.com/4887959/229496940-cab664d9-d212-4acc-90f4-13b219acf6ba.png">

The tricky thing is these docs are rendered in an `<object>` tag, so we can't actually control the text color in there i.e. just force it with css.

If you can confirm (or not) the above Im thinking of a potential workaround...

**Comment by jat255** [comment]
Yes, that's a correct assumption:

![image](https://user-images.githubusercontent.com/1278301/229544270-96001490-e988-4456-9bd1-be2192e34bac.png)

I'm using KDE on Linux with the "Breeze Dark" theme, but for whatever reason, the system "dark/light" theme does not get detected by Paperless, so I need to force it to dark. My Chrome theme is dark, too using the default "GTK" theme which is supposed to match your desktop environment. 

If I tell Paperless to use the system theme, it changes to light:

![image](https://user-images.githubusercontent.com/1278301/229545560-f2d9d114-bf87-4bdd-9a4c-0249a103b79d.png)

**Comment by shamoon** [comment]
Thanks for reporting, Im happy with the (new) PR solution here

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/1e19ec6b9a3a72272b8242a759aff6cf4fbc6a6f
