### ISSUE TITLE
[BUG] v1.14.0 RC1 Tour cannot be completed if account has insufficient permissions

### ISSUE THREAD

**Issue by bllngr** [paperless-ngx/paperless-ngx#3052]
### Description

When a user account has missing permissions for the steps of the tour, the tour cannot be completed and fails with an error message.

### Steps to reproduce

1. Create a user account with these permissions:
![2023-04-09 17_12_39-Settings - Paperless-ngx — Mozilla Firefox](https://user-images.githubusercontent.com/303458/230781455-cbcbfb74-bd07-4ef8-be04-c8d41c070d39.png)
2. Log in with the created account and start the tour
3. Observe an error message being shown on step 7:
![paperless-ngx-error](https://user-images.githubusercontent.com/303458/230781635-dee6aa77-dcd5-4297-b3ed-5fe937e11d94.png)

### Webserver logs

```bash
[2023-04-09 17:04:32,327] [WARNING] [django.request] Forbidden: /api/storage_paths/
```

### Paperless-ngx version

v1.14.0 RC1

### Host OS

Synology DSM x86_64 Docker

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/b4d97d4a2bce12e65bc7a44ef78115c00b472215

Thanks for reporting
