### ISSUE TITLE
[BUG] v1.14.0 RC1 User cannot set itself as owner of a document when account has no "View User" permission

### ISSUE THREAD

**Issue by bllngr** [paperless-ngx/paperless-ngx#3053]
### Description

When an account has no "View User" permission, the dropdown to set an owner only shows "No items found", and does not allow selecting the used account.

### Steps to reproduce

1. Create a user account with no "User" permissions
2. Login with the newly created user account
3. Upload a document and try to set your account as the owner
4. Observe that the dropdown only shows "No items found", and does not allow selecting the used account
![signal-2023-04-09-171125_002](https://user-images.githubusercontent.com/303458/230782610-17303a89-51e9-4792-b324-ddd688928159.png)

### Webserver logs

```bash
[2023-04-09 17:09:35,281] [WARNING] [django.request] Forbidden: /api/users/
[2023-04-09 17:10:29,945] [WARNING] [django.request] Forbidden: /api/groups/
```

### Paperless-ngx version

 v1.14.0 RC1

### Host OS

Synology DSM x86_64 Docker

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/8f90fe79c875f00dd793f082ac195a6b734c6bcd

Thanks for reporting
