### ISSUE TITLE
[BUG] Handling OCR Languages with Underscores

### ISSUE THREAD

**Issue by eightfiftytwo** [paperless-ngx/paperless-ngx#3065]
### Description

Paperless fails to handle OCR languages with underscores in them.

When I do what the [documentation](https://docs.paperless-ngx.com/configuration/#ocr) suggests:
```
  -e PAPERLESS_OCR_LANGUAGES="chi_tra eng" \
  -e PAPERLESS_OCR_LANGUAGE=chi_tra \
```
I get:
```
Package tesseract-ocr-chi_tra not found! :(
Package tesseract-ocr-eng already installed!
...
ERRORS:
?: The selected ocr language chi_tra is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
```

If I use:
```
  -e PAPERLESS_OCR_LANGUAGES="chi-tra eng" \
  -e PAPERLESS_OCR_LANGUAGE=chi-tra \
```
I get:
```
ERRORS:
?: The selected ocr language chi-tra is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
```

This is the only config that works:
```
  -e PAPERLESS_OCR_LANGUAGES="chi-tra eng" \
  -e PAPERLESS_OCR_LANGUAGE=chi_tra \
```

I'm guessing that paperless finds the required language packs by simply appending `PAPERLESS_OCR_LANGUAGES` to the package names, but the Debian package is called `tesseract-ocr-chi-tra` and not `tesseract-ocr-chi_tra`.
If this is the intended behaviour, perhaps the documentation could mention it?

### Steps to reproduce

Run the official Docker image with:
```
  -e PAPERLESS_OCR_LANGUAGES="chi_tra eng" \
  -e PAPERLESS_OCR_LANGUAGE=chi_tra \
```
I am using rootless podman 4.4.4.

### Webserver logs

```bash
Package tesseract-ocr-chi_tra not found! :(
Package tesseract-ocr-eng already installed!
...
ERRORS:
?: The selected ocr language chi_tra is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
```
```


### Browser logs

_No response_

### Paperless-ngx version

1.13

### Host OS

Armbian 23.02.2

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

**Comment by shamoon** [comment]
Yea it's not particularly obvious, see https://github.com/tesseract-ocr/tesseract/issues/1873 / https://packages.debian.org/bullseye/graphics/

The documentation doesn't say to use underscore for `PAPERLESS_OCR_LANGUAGES` but only for `PAPERLESS_OCR_LANGUAGE` which, admittedly confusingly, is not the same thing.

I'll add the above link to the docs
