### ISSUE TITLE
[BUG] TLD e-mail adress check

### ISSUE THREAD

**Issue by JPlanche** [paperless-ngx/paperless-ngx#3091]
### Description

Hello.

I am discovering this very interesting tool.
I have an e-mail address with TLD .name (example: `jeannot@lapin.name`)
The createsuperuser function thinks my e-mail address is invalid, but is is valid.
I searched in the code but I didn't find where this check is.

### Steps to reproduce

1. Use the createsuperuser function (`docker-compose run --rm webserver createsuperuser`)
2. Enter your username
3. Enter the e-mail address `jeannot@lapin.name`

You have the error "Enter a valid email address".

### Webserver logs

```bash
Not copied, sorry
```

### Paperless-ngx version

1.13.0

### Host OS

Fedora

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Uh, I cant reproduce this...

```
root@e7ee3af1696e:/usr/src/paperless/src# python3 manage.py createsuperuser
Username (leave blank to use 'root'): testing123
Email address: me@example.name
Password: 
Password (again): 
Superuser created successfully.
```

**Comment by shamoon** [comment]
<img width="556" alt="Screenshot 2023-04-13 at 1 27 00 PM" src="https://user-images.githubusercontent.com/4887959/231875417-bf81a3ac-c3a1-47f7-95c8-e4f05eebbf7d.png">

**Comment by JPlanche** [comment]
Well, indeed, truly sorry, I had to have a non printable character in the terminal or something like that. :-(
