### ISSUE TITLE
[BUG] No ability to return to the main documents View when viewing a single document fully via (iOS) webview

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#3100]
### Description

When using paperless on my ipad, and saving it via a bookmark on the Home Screen, when returning to acces it, if I double click on the eye icon to open a file fully, there is no obvious way to close that view and return to the previous screen.  I have to force close and access paperless again.

This area seems to be specific to when you are accessing paperlesss via a home screen book mark - recommended fix would be to add a back button option as an overlay in the top left corner of the document viewer that is used..

### Steps to reproduce

Access paperless-ngx and save it as a bookmark to your iOS device Home Screen 
Access the new home screen link (bookmark) and find a document to open from the main paperless page 
Click on the eye icon to open the document fully
Once here, you do not have the standard browser toolbar options so can’t close/click back etc.

### Webserver logs

```bash
No logs
```

### Browser logs

```bash
No logs
```

### Paperless-ngx version

1.13.0

### Host OS

Linux QNAP

### Installation method

Docker - official image

### Browser

Safari iOS (iPad)

**Comment by shamoon** [comment]
Well, the back button?

Clicking that link is opening up the file directly, not something we have any control over.

**Comment by nodecentral** [comment]
> Well, the back button?

But that’s the thing, on the iPad when saving paperless as a link/book mark on your homescreen - you don’t get the back button hence it becomes a dead end and you have to close. (sorry if that was not clear in the explanation above).

Not sure if you have access to an iOS device to experience this *(s it’s very annoying or I’m missing something obvious), but you should be able to easily reproduce this, and if you confirm it, perhaps add guidance in the documentation not to use Paperless-ngx that way, which is unfortunate as I do that for the majority of my self hosted apps..

**Comment by shamoon** [comment]
Swipe from the left of the screen.
