### ISSUE TITLE
Unable to click checkbox in documents list view

### ISSUE THREAD

**Issue by shamoon** [paperless-ngx/paperless-ngx#311]
_Originally posted by @90er in https://github.com/paperless-ngx/paperless-ngx/issues/259#issuecomment-1066085008_

I have an issue using Brave (Version 1.36.112) in combination with the documents list view.

In the documents list view i can't use the checkbox by exactly clicking on it with the cursor. When i click close to it (or on the item line) it's working:

https://user-images.githubusercontent.com/17730136/158058127-cb51a54c-1c21-48be-9235-b72367fa4fd2.mov

_Originally posted by @90er in https://github.com/paperless-ngx/paperless-ngx/issues/259#issuecomment-1066085008_

**Comment by shamoon** [comment]
Confirmed, I'll sort this out.

**Comment by lippoliv** [comment]
@shamoon this can be closed now, right?

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/5794faef6c79e848157ba642daf6c578707d357a
