### ISSUE TITLE
[BUG] 1.14.0-beta.rc1 - apostrophe in filename affects download file name

### ISSUE THREAD

**Issue by DarkPhyber-hg** [paperless-ngx/paperless-ngx#3114]
### Description

If i have a document with an apostrophe in the title.  Such as "Steve's document", and then click on "download" the file name will download as "b.pdf" instead of "Steve's Document.pdf", An Apostrophe should not be an illegal character for a file name, but if it was an illegal character stripping it would be more acceptable.

### Steps to reproduce

put an apostrophe in the "Title" Field, and click download.

### Webserver logs

```bash
i don't have any.
```

### Paperless-ngx version

1.14.0-beta.rc1

### Host OS

ubuntu 22.04.2

### Installation method

Docker - official image

### Browser

firefox

**Comment by shamoon** [comment]
I cant reproduce this. I confirmed in the beta and 1.13.

. If theres a real issue perhaps there are more specific circumstances needed, please let us know if thats the case and we can re-address.

<img width="1588" alt="Screenshot 2023-04-16 at 2 46 30 PM" src="https://user-images.githubusercontent.com/4887959/232344359-59984386-172e-4316-962c-3c9a7c47f6bd.png">
