### ISSUE TITLE
[BUG] Page numbers are not visible in documents view - Visual BUG

### ISSUE THREAD

**Issue by miku323** [paperless-ngx/paperless-ngx#312]
There is a visual bug with numbers in Documents view. Pictures below:
Light mode:
![image](https://user-images.githubusercontent.com/5058121/158066553-332ffa2e-634e-4ef2-a554-fdedb9d4b273.png)
Dark mode:
![image](https://user-images.githubusercontent.com/5058121/158066567-2188e22e-cd8b-438a-8179-179675a2b21d.png)

Same problem if I change color scheme of paperless:
![image](https://user-images.githubusercontent.com/5058121/158066595-78fad7d5-1ab0-4721-96cc-bba6dd745150.png)

**Relevant information**
 - Host OS of the machine running paperless: Linux/Unraid
 - Browser Chrome 99.0.4844.51, Opera
 - Version 1.6.0
 - Installation method: Docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: No.

**Comment by miku323** [comment]
Picture from version 1.5.0 for relevance:
![image](https://user-images.githubusercontent.com/5058121/158066723-ad5707fe-db09-439e-b328-39f6229635a8.png)

**Comment by shamoon** [comment]
That is not version 1.6.0, that has to be the `dev` branch. Still, thanks for reporting, I will fix.

**Comment by miku323** [comment]
That is true., I'm so sorry. For some reason, I forgot I have put it in `dev`. Once I put it on `latest` and it works as intended.

**Comment by Profex** [comment]
Page numbers currently just show up on top of a documents view. Would it be also possible to add them in addition at the bottom of each documents view? If just browsing though a large list of documents you currently have to scroll back to the top of the page in order to select the next document overview page for viewing.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/f93783052b402f85975b2dc1052459c97ef2d5df
