### ISSUE TITLE
[BUG] Rest API responds with wrong URI prefix for next pagination

### ISSUE THREAD

**Issue by abbbi** [paperless-ngx/paperless-ngx#3130]
### Description

It seems the API replies with a fixed (or wrong) URI to http within the json response. 

### Steps to reproduce

Attempting to get a list of correspondents via rest API using CURL as such:

`curl -vvv --header 'authorization: Token MY_TOKEN' https://host:443/api//correspondents/`

will respond with the following JSON:

`{"count":28,"next":"http://host/api/correspondents/?page=2","previous": [..]`

for some reason, the URI provided in the "next" key defaults to http and strips the port.
This means any api sdk such as pypaperless will fail to get paginated results, if the paperless instance 
is not exposed via http, too.

In my case im accessing the instance via NGINX Reverse Proxy, which might play into this issue 
It think the json response should contain the correct host.

### Webserver logs

```bash
No logs.
```

### Paperless-ngx version

1.13.0

### Host OS

Debian 11

### Installation method

Bare metal

**Comment by stumpylog** [comment]
The pagination is a lightly customized [PageNumberPagination](https://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination).  So nothing in here I can find directly sets the next field.

If you try directly, without the proxy, is the response correct?

**Comment by stumpylog** [comment]
I just tried with an instance which sits behind Traefik and a local instance.  (and I used tags, but the pagination is the same).

Local instance kept the port, as expected.  Proxy instance kept the host as well.  

It did replace the HTTPS with HTTP, which seems counter to the example in their documentation.  I'd suggest going to the source: https://github.com/encode/django-rest-framework/issues.  I don't find any issue there currently that seems to fit.

**Comment by stumpylog** [comment]
I don't have the time this evening to investigate all the settings, but this looks relevant: https://stackoverflow.com/questions/42818940/django-rest-framework-pagination-links-do-not-use-https

**Comment by stumpylog** [comment]
Alright, it looks like setting [SECURE_PROXY_SSL_HEADER](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-SECURE_PROXY_SSL_HEADER) will return HTTPS in the next.  It does come with some large warning boxes, but we can provide the option to set it for users who understand those warnings and want it.

**Comment by stumpylog** [comment]
The branch `feature-fix-3130` is building, but should fix this.  Users can now control the `USE_X_FORWARDED_` values and set `SECURE_PROXY_SSL_HEADER` if desired.  All settings default to Django defaults, ie, disabled.

Can you test the resulting image with these settings?

**Comment by abbbi** [comment]
> Can you test the resulting image with these settings?

thanks, ill try my best but im quite busy atm, not sure if i have time to test in the next few days.

**Comment by stumpylog** [comment]
I've merged it.  Users can set the three most relevant seeming options from Django.
