### ISSUE TITLE
listing of documents in views takes longer in 1.14

### ISSUE THREAD

**Issue by titro** [paperless-ngx/paperless-ngx#3164]
### Description

After updating from 1.13 to 1.14 the listing of documents in the different views (doesn't matter what view) takes much longer

![image](https://user-images.githubusercontent.com/4005090/234216956-2ea06ff0-41d9-4474-a82f-193b30856dca.png)
Loading of the view takes approx. 2-3 secs. Views with more/all documents takes much longer but even a view with a tag filter with 22 documents takes a second.

![image](https://user-images.githubusercontent.com/4005090/234220447-4161fc0a-966a-48ac-be92-843643583b8c.png)

### Steps to reproduce

1. Use a "saved view" view
2. Wait until loading spinner is disabled and count of documents is showed up.

### Webserver logs

```bash
no logs are written during this action
```

### Paperless-ngx version

1.14

### Host OS

RPI4 armv7, Docker 20.10.22

### Installation method

Docker - official image

### Browser

Chrome 112.0.5615.138

**Comment by stumpylog** [comment]
"It takes longer" isn't something that's going to be very actionable.  It's going to be dependent on hardware (a Pi for example) and configuration (using a proxy? compression? caching?).  To me, loading the documents view or a saved view appears to be roughly the same as before.  It's highly subjective.

If you can gather browser logs and show actual timing, that would be more useful.
