### ISSUE TITLE
[BUG] Redis connection fails with 1.14 with: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'

### ISSUE THREAD

**Issue by ThxAndBye** [paperless-ngx/paperless-ngx#3173]
### Description

Upgrading from Paperles-NGX 1.13 to 1.14 causes the Redis connection via a UNIX-Socket to fail with the following error message:  
`Error: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'.`  

I'm running Paperless-NGX via the official Docker image: `ghcr.io/paperless-ngx/paperless-ngx`

### Steps to reproduce

1. Setup Paperless-NGX with the Docker image `ghcr.io/paperless-ngx/paperless-ngx:1.13`
2. Configure Redis via a UNIX socket with the `PAPERLESS_REDIS` environment variable (e.g. `unix:///run/redis/redis.sock`)
3. Upgrade to the 1.14 image

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for Redis...
Redis ping #0 failed.
Error: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'.
Waiting 5s
Redis ping #1 failed.
Error: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'.
Waiting 5s
Redis ping #2 failed.
Error: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'.
Waiting 5s
Redis ping #3 failed.
Error: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'.
Waiting 5s
Redis ping #4 failed.
Error: 'UnixDomainSocketConnection' object has no attribute 'socket_timeout'.
Waiting 5s
Failed to connect to redis using environment variable PAPERLESS_REDIS.
```

### Paperless-ngx version

1.14

### Host OS

UnRAID 6.11.5

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Looks like redis/redis-py/issues/2581 which was fixed in 4.5.4 (we're using 4.5.3).  I'll see about updating soon

**Comment by ThxAndBye** [comment]
> Looks like [redis/redis-py/issues/2581](https://github.com/redis/redis-py/issues/2581) which was fixed in 4.5.4 (we're using 4.5.3). I'll see about updating soon

Whoa, that was a swift reply if I've ever seen one.  

Keep in mind, that mentioned issue has the missing attribute `'_command_packer'` while for me it fails with `'socket_timeout'`.  
I'm happy to test new images though.

**Comment by stumpylog** [comment]
Oh, looks like redis/redis-py/issues/2629 then.  Very similar

**Comment by stumpylog** [comment]
Oh, it closes it now.  Neat.  We'll probably have a new point release out soon with the upgraded library
