### ISSUE TITLE
Group "Privat"?

### ISSUE THREAD

**Issue by titro** [paperless-ngx/paperless-ngx#3178]
### Description

I sometimes see the Group "Privat" 

![image](https://user-images.githubusercontent.com/4005090/234352315-f333251a-7861-4f25-992f-0b99eecfbbba.png)
If i reload the page, the group is gone. Group is also not in the database. I recently updated to 1.14 and did not do anything with users or groups so far.

### Steps to reproduce

1. Go to Settings and User & Groups
2. Click on "Add User"
3. Click on "cancel"
4. The group is there
5. refresh. The group is gone.

### Webserver logs

```bash
nothing there
```

### Paperless-ngx version

1.14

### Host OS

RPI4 armv7, Docker 20.10.22

### Installation method

Docker - official image

### Browser

Chrome 112.0.5615.138

**Comment by titro** [comment]
This happens for each and every "add user, cancel" action:

![image](https://user-images.githubusercontent.com/4005090/234353780-2f53d846-ec98-4404-b2f3-139906ba061e.png)

**Comment by stumpylog** [comment]
Not sure where it lies, but I do reproduce it

**Comment by Strohhut1** [comment]
These groups are gone once you log in and out, sometimes even after a reload of the site.

**Comment by titro** [comment]
Maybe some interfere with the input select component? This is the only file where i found the Private....

**Comment by shamoon** [comment]
Hmm, I actually cant reproduce this, presumably there is a way to, just haven't been able to no matter how many times I reload/logout etc. Thats on my 'production' install, a 'dev' install and local dev environment.

Do people seeing this have any groups or only happens with 0? And if folks can confirm the output of `/api/groups/?page=1&page_size=100000` looks like
```
{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```

**Comment by stumpylog** [comment]
I see it with a fresh instance.  No groups, single super user created at container start.

I don't see any network requests in the developer tools when I do an add, then cancel.  I didn't need to enter any values for the user either.

If I did multiple add then cancel, I think it was adding one private per cancel

**Comment by shamoon** [comment]
Oh wonderful, I missed the "add" part—got it! I'll sort it
