### ISSUE TITLE
[BUG] "Storage Paths" are visible to all users after setting permissions

### ISSUE THREAD

**Issue by Strohhut1** [paperless-ngx/paperless-ngx#3179]
### Description

The storage paths are visible to all users after setting "Owner" to only one specific user.
This is also the case when adding that one user selected as "Owner" to "View" and/or "Edit".

The permissions for Tags, Document-Type and Correspondent work perfectly with the same settings.

### Steps to reproduce

1. Login as Admin
2. Create a new Storage Path
3. Add one user as the Owner under Permissions
4. Log out and log in as a user not set as the Owner
5. See the storage paths even tho having no permission to do so

(All users are allowed to view, edit, delete and create Storage Pahts in the User&Group settings)

### Webserver logs

```bash
-
```

### Browser logs

```bash
-
```

### Paperless-ngx version

1.14.0

### Host OS

Synology DSM 7.1.1-42962 Update 5

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

-

### Other

-

**Comment by stumpylog** [comment]
I can't reproduce this.  The other user doesn't even see the storage path link in the toolbar:
![image](https://user-images.githubusercontent.com/797416/234359635-eeb01b09-f8ee-44c1-aa5a-570c563f02b1.png)

**Comment by Strohhut1** [comment]
Did you allow the users to see Storage Paths beforehand?:
![image](https://user-images.githubusercontent.com/46486021/234360010-0ee4cdf2-51cf-4948-bc23-be8fa1cb7e4f.png)

**Comment by stumpylog** [comment]
If the user has permissions to view StoragePath(s), they can view them, regardless of the owner.

**Comment by Strohhut1** [comment]
Is it different to e.g. Tags?
Because all my users are allowed to edit, view, create and delete tags but are only able to see the Tags they have permissions for.

**Comment by stumpylog** [comment]
Ah, I think I see it now

**Comment by Strohhut1** [comment]
Wow, that was fast thanks for the great work!
I sure hope to find the time to contribute to this great project too :)
