### ISSUE TITLE
[BUG] Autocompletion suggests terms included in documents a user has no access to

### ISSUE THREAD

**Issue by astubenbord** [paperless-ngx/paperless-ngx#3187]
### Description

When using the autocomplete feature from `/api/search/autocomplete/?term=...`, the API suggests terms included in documents which the user has no access to (in 1.14.0).

This has one "unfortunate" side effect and another more severe effect:

1. A user without access to the document the suggestion string originated from will be suggested the string but will not get any results. 
2. The more severe case: Imagine someone uploads a very sensitive document, e.g. containing your social security number. In some countries, these numbers follow a certain format, e.g. start with a constant expression (like DE123). Now, if a user without access to this document wants to know the social security number of another user (assuming a corresponding document with this number exists), he can just search for "DE123" and be suggested the whole social security number. For instance, in germany, the payroll you receive at the end of each month contains your tax id. Not sure I want to share this with other users.

So one could essentially do "text mining" of documents one should not have access to.

I'm not sure how the search is currently implemented, but I assume it is a global index which is built from the content of _all_ documents. If this is the case, this would be a lot of effort to fix since we would have to
1. Create this index for each user independently based on the documents this user has access to, and
2. Update the index every time the permissions for this user change or someone shares/removes a document from a user.

### Steps to reproduce

1. Create PDF file containing only one unique String (like 123456789)
2. Upload PDF to paperless as admin (or any other user with add document permission)
3. Assign the uploader (here: admin) as the owner and add per document permissions to admin (i.e. no other user is allowed to view the document)
4. Logout
5. Login as user B and ensure this user has the **document.view** permission
6. Ensure that user B does not see the new document (no access!)
7.  Search for the unique string in the top
8. Observe that it is auto completed

### Webserver logs

```bash
No related logs.
```

### Browser logs

```bash
No related logs
```

### Paperless-ngx version

1.14.0

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Autocomplete uses https://whoosh.readthedocs.io/en/latest/api/reading.html#whoosh.reading.IndexReader.most_distinctive_terms , I don't see an obvious solution here

**Comment by astubenbord** [comment]
I see. After reading the docs, I think the only solution would be to maintain several indices which whould also have to be updated on permission change, so that each index is only built based only on the documents a user also has access to. 
Should be fairly complex to implement as far as I can tell.

**Comment by leschbenedikt** [comment]
Would it help to add the permission relevant field to the index, like owner etc.
And then check all the entries after searching for permission?

**Comment by shamoon** [comment]
It already is there. The issue is the method used to generate these, noted above, doesn't include any kind of filtering of documents.

**Comment by leschbenedikt** [comment]
Sorry I'm not familiar with the code right now.

But couldn't we just copy the method to the paperless code and add filtering or write a custom query?

**Comment by shamoon** [comment]
> Sorry I'm not familiar with the code right now.
> 
> But couldn't we just copy the method to the paperless code and add filtering or write a custom query?

If you look into the code a bit I think you will see it's not quite so simple. Would welcome a PR, of course.

**Comment by leschbenedikt** [comment]
That's what I came up with in the short time.
Because I'm no python dev I not really able to submit a PR.  That's why I did it in a test case

But at least this seams to work in the same way as the original method.
Return values and score are the same.

Still needs the permission filtering in the query and sure some python improvements.

```python
   def test_auto_complete_custom(self):
        doc1 = Document.objects.create(
            title="doc1",
            checksum="A",
            content="test test2 test3",
        )
        doc2 = Document.objects.create(title="doc2", checksum="B", content="test test2")
        doc3 = Document.objects.create(title="doc3", checksum="C", content="test2")

        index.add_or_update_document(doc1)
        index.add_or_update_document(doc2)
        index.add_or_update_document(doc3)

        ix = index.open_index()

        results = self.autocomplete(ix)

        self.assertListEqual(
            results,
            [b"test3", b"test", b"test2"],
        )

    def autocomplete(self, ix):
        with ix.searcher(weighting=scoring.TF_IDF()) as s:
            qp = QueryParser("content", schema=ix.schema)
            q = qp.parse("tes*")

            results = s.search(q, terms=True)

            termCount = dict()
            if results.has_matched_terms():
                for hit in results:
                    for term in hit.matched_terms():
                        if term[1] in termCount:
                            termCount[term[1]] = termCount[term[1]] + 1
                        else:
                            termCount[term[1]] = 1


            scoreMap = OrderedDict()
            N = float(ix.reader().doc_count())
            for key in termCount:
                scoreMap[key] = (termCount[key] * log(N / termCount[key]))

            return list(scoreMap.keys())
```

**Comment by shamoon** [comment]
> That's what I came up with in the short time. Because I'm no python dev I not really able to submit a PR. That's why I did it in a test case
> 
> But at least this seams to work in the same way as the original method. Return values and score are the same.

Thanks for the snippet :) It’s not really the logic that concerns me it’s the performance of eg this vs how autocomplete is “natively” implemented, but to be honest I haven’t tried yet so you’re inspiring me to at least see how it goes! Either way, thanks for the input. I’ll report back once I have some time to tinker
