### ISSUE TITLE
[BUG] Tags user has no permissions for show as "Private" after file upload

### ISSUE THREAD

**Issue by Strohhut1** [paperless-ngx/paperless-ngx#3196]
### Description

When a user uploads a file that triggers Tag-Rules of other users the "detected" Tags show up as Private as the uploading user does not have the permissions to view these Tags.

(The image is german so Privat = Private)
![s8u2Hd0b07ZqJ5n5](https://user-images.githubusercontent.com/46486021/234629541-7e37e389-c3b6-4ac6-bb4a-f201ecd6f2af.png)

I don't know if that is a feature or not ... for me its confusing.

("Neu" is the Inbox-Tag ... the only one that should show here)

### Steps to reproduce

1. Login as User A
2. Create Tag "Test" with rule to add when "Test" is detected as a Word in the Document
3. Set Permission of this Tag to User A only
4. Login as User B
5. Upload a file with the word "Test" in it
6. See a Private-Tag added by paperless

### Webserver logs

```bash
-
```

### Browser logs

```bash
-
```

### Paperless-ngx version

1.14.0

### Host OS

Synology DSM 7.1.1-42962 Update 5

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

-

### Other

-

**Comment by shamoon** [comment]
Hmm, this should actually be handled, what permissions does user B have for the Tag?

https://github.com/paperless-ngx/paperless-ngx/blob/c385355c2b76c83e7b5d85936d2e2db007f91011/src/documents/matching.py#L60

**Comment by shamoon** [comment]
Yes, and assuming you uploaded the doc via the UI i.e. the doc was uploaded with an owner?

**Comment by Strohhut1** [comment]
Correct I uploaded via User B (Test 2) ... so the owner with no permissions over Tag "Test" that's why the Tag is displayed as "Private" I suppose.

**Comment by shamoon** [comment]
I see the issue, will get it sorted thanks
