### ISSUE TITLE
[BUG] Selecting date ranges breaks searches

### ISSUE THREAD

**Issue by Skram-de** [paperless-ngx/paperless-ngx#3206]
### Description

Searching documents using TWO filters will not work, if one parameter is "last month" or "last year" in the "added" or "created" field. I tried to be more precise than #3203 

Example: 

Selected document type is "Anleitung" -> everything works as expected:
![image](https://user-images.githubusercontent.com/113503248/234883356-1975b4b6-713c-4d93-bb52-459638fa2ed4.png)

Now a second filter "last year" is applied. Year is as expected but selected document type is ignored:
![image](https://user-images.githubusercontent.com/113503248/234883815-39dcd974-a010-46ac-9897-cb326cf036cc.png)

### Steps to reproduce

1. login as a superuser
2. go to web-ui -> documents
3. reset filters (all documents displayed now)
4. select document type.
5. select "created" oder "added" date range "last year"
-> all document types ara displayed.

### Webserver logs

```bash
none
```

### Browser logs

```bash
none
```

### Paperless-ngx version

1.14.0

### Host OS

Linux 3.10.108 #42661 SMP (x86_64)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Thanks, yep got it
