### ISSUE TITLE
[BUG] Filter dates with german localization does not work (for example: "12.04.2023")

### ISSUE THREAD

**Issue by simowNgithub** [paperless-ngx/paperless-ngx#3236]
### Description

in my example there are documents in the last 7 days, but the filter doesn't work after upgrading to version 1.14.2
[
![D3DEB0A1-8E10-4724-B7E8-B0C228027A94](https://user-images.githubusercontent.com/117570480/235231910-213d4458-87ee-4144-b712-9ba9716429bb.jpeg)
](url)

### Steps to reproduce

1. Install paperless-ngx with german localization
2. Upgrade paperless-ngx to 1.14.2
3. Click for all documents
4. filter for the last 7 days

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.14.2

### Host OS

Debian 11

### Installation method

Docker - official image

**Comment by Skram-de** [comment]
Sounds a little bit like #3222 . Are you logged in as a superuser?

**Comment by simowNgithub** [comment]
Yes I'm superuser, but I'm not sure if this is the same issue... Sounds same on some points but bit different.

**Comment by stumpylog** [comment]
Two things, can you double check your index in up to date?  Running `document_index reindex` will ensure that.

Could use developer tools to get the request the frontend is sending?

It will be a request to `api/documents/` with a `&query=` in it.  Filters like "Last 7 days" don't actually calculate the date, it's given to the searcher (known as whoosh) almost directly.

**Comment by stumpylog** [comment]
To me, it looks like only "Last 7 days" isn't working as I expect.  Which is odd, since those are all treated the same that I can see.

**Comment by nillebor** [comment]
I have no problem here. Filter works fine:
paperless-ngx in german
upgrading to version 1.14.2 with watchtower
installed on a synology diskstation

the other time periods also work!

**Comment by shamoon** [comment]
I do think #3222 would explain this, but it's hard to say without knowing the exact specifics. But effectively that issue makes docs 'disappear'. Does the doc youre expecting have an owner, is it "Simon" like in your screenshot?

In general, I dont think theres an issue here, I cant reproduce one anyway (besides the one noted). Yes, the date queries are passed to the backend like `query=added:%5B-1%20week%20to%20now%5D`, which can easily be changed around e.g. `query=added:%5B-3%20week%20to%20now%5D`

Reindexing is a good thing to try, you can also try the `dev` image (at the moment thats pretty safe but always good to have a backup).

Almost certainly has nothing to do with German locale.

**Comment by simowNgithub** [comment]
found same here https://github.com/paperless-ngx/paperless-ngx/issues/2533 trying this steps.

**Comment by simowNgithub** [comment]
`python3 /opt/paperless/src/manage.py document_index reindex` resolved the issue.
