### ISSUE TITLE
[BUG] "document_exporter --delete" doesn't work after "document_renamer"

### ISSUE THREAD

**Issue by yonchko** [paperless-ngx/paperless-ngx#3255]
### Description

Files and folders are not deleted from last export if document-renamer was run.

### Steps to reproduce

docker-compose exec -T webserver document_exporter ../export -c -d -f -p
change the PAPERLESS_FILENAME_FORMAT in docker.compose.env
sudo docker-compose exec webserver document_renamer
docker-compose exec -T webserver document_exporter ../export -c -d -f -p

### Webserver logs

```bash
na
```

### Paperless-ngx version

1.14.2

### Host OS

Synology 220plus

### Installation method

Docker - official image

**Comment by shamoon** [comment]
I cant reproduce this

`python3 manage.py document_exporter ../export -c -d -f -p`

```
ls ../media/documents/originals
0000001.pdf
0000002.pdf
0000003.pdf
0000004.pdf
...
```

```
ls ../export/originals
0000001.pdf
0000002.pdf
0000003.pdf
...
```

`PAPERLESS_FILENAME_FORMAT={created_year}/{title}`

```
python3 manage.py document_renamer
100%|███████████████████████████████████| 62/62 [00:00<00:00, 441.80it/s]
```

`python3 manage.py document_exporter ../export -c -d -f -p`

```
ls ../export/originals            
1972
1985
1989
1990
1995
2000
...
```

**Comment by shamoon** [comment]
Please reopen if needed

**Comment by yonchko** [comment]
I just found out that the issue simply comes from the synology drive client that is not deleting properly. paperless-ngx did it just alright. Sorry about that and many thanks for checking nevertheless.
