### ISSUE TITLE
[BUG] Cookies not sent when requesting ui_settings

### ISSUE THREAD

**Issue by odelseth** [paperless-ngx/paperless-ngx#3299]
### Description

When I open the frontend locally and I'm logged in the backend as an admin, I get an error 403.

![Screenshot from 2023-05-03 17-12-11](https://user-images.githubusercontent.com/4722139/235963316-a21b05a0-8630-415e-b2a1-acafaba47264.png)

Opening the same url in another tab correctly displays the JSON, because the sessionid cookies exists:

![Screenshot from 2023-05-03 17-13-31](https://user-images.githubusercontent.com/4722139/235963926-9c7d08f5-70ba-44c2-a69a-8ceb7bf726c6.png)

It appears the cookies are not sent in the headers when the request is sent from the frontend, so the user is not authenticated:

![Screenshot from 2023-05-03 16-57-20](https://user-images.githubusercontent.com/4722139/235963151-d6be1e43-63fd-407b-ac13-a50eb6b0ecb5.png)

### Steps to reproduce

1. cd src-ui
2. ng serve
1. Browse to http://localhost:4200/
3. Inspect -> network
4. Click on http://localhost:8000/api/ui_settings/
5. Check request headers

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

1.14.2

### Host OS

Linux 5.19.0-38-generic 22.04.1-Ubuntu x86_64

### Installation method

Other (please describe above)

### Browser

Chrome 111.0.5563.146

**Comment by odelseth** [comment]
Updating Chrome to the latest Version 112.0.5615.121 doesn't change anything

**Comment by shamoon** [comment]
`ng serve` is the development server, which you should not be using for production, it doesn't use the webserver etc.

**Comment by odelseth** [comment]
@shamoon Sorry, I realize I shouldn't have opened a bug but a support discussion...

I was testing the project on localhost on my machine, and accidentally removed the `AngularApiAuthenticationOverride` authentication class, thus the auto login with a staff user was not working.

I'd like to test the multi-user feature with a user that is not staff member. I guess the best practice is to use `PAPERLESS_AUTO_LOGIN_USERNAME` to do that in dev mode. 

Thanks
