### ISSUE TITLE
[BUG] Email tag rule inverted for non Gmail labels

### ISSUE THREAD

**Issue by WackEarl** [paperless-ngx/paperless-ngx#3302]
### Description

Caused by https://github.com/paperless-ngx/paperless-ngx/pull/3240 which removed the X-GM-LABELS when the server doesn't support it, but (seemingly) kept the “NOT“ before it.

### Steps to reproduce

1. Create a rule with tag for non-GM
2. Should fetch untagged
3. Only fetches already tagged, ignoring other mails

Manually adding a tag to a mail caused it to be imported.

### Webserver logs

```bash
Searching folder with criteria (NOT (UNKEYWORD paperless) SINCE xxxxx
```

### Paperless-ngx version

1.14.3

### Host OS

Debian

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Yes, looks like a not not keyword instead of just not keyword.

**Comment by WackEarl** [comment]
Awesome, thanks for the quick fix 😄
I really appreciate the work you're doing here 👍
