### ISSUE TITLE
[BUG] Tag/Correspondent/Document type counts are off

### ISSUE THREAD

**Issue by jacroe** [paperless-ngx/paperless-ngx#3306]
### Description

This is a duplicate/re-open of #2921. I believe I have a few more observed notes that may explain why it was difficult to reproduce.

When dropping down to filter by tag, corespondent, or document type, the counts alongside each listing are only for the items currently listed on that page.

For example, let's say I have 177 documents that are tagged with "banking" across three different correspondents: Simple, BBVA, and PNC. Depending on which page of the result set I view, the counters update based on what's on that page.

![Screenshot from 2023-05-03 20-47-27](https://user-images.githubusercontent.com/1142635/236082074-34682ea6-ef0a-4af9-9d05-55bafd60510c.png)
![Screenshot from 2023-05-03 20-47-43](https://user-images.githubusercontent.com/1142635/236082093-983aac37-9cdb-48a7-a34f-a0e1d5d9407e.png)
![Screenshot from 2023-05-03 20-48-05](https://user-images.githubusercontent.com/1142635/236082143-06bb816d-1ee8-4571-a56e-852a5fe5e237.png)

The reason, I believe, that shamoon[^1] was unable to reproduce it was because their documents (filtered or not) were shown all on one page.

[^1]: Deliberately un-mentioned because that seems rude to me for some reason? But they're who interacted in #2921.

### Steps to reproduce

1. Have more than one page size of documents tagged across a number of correspondents/tags/document types.
2. Load the first page without any filters selected.
3. The counts in the three dropdowns represent only the items currently on page one. Items on page two+ are not counted.

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

1.14.3

### Host OS

Raspberry Pi aarch64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by jacroe** [comment]
Oh man, I have happily, gleefully used "that's intended behavior" in my own 9-5p job, but this is the first time I've had to face it myself. :laughing: I gotta respect it.

I'm gonna have to re-evaluate now that I know it's intended. The filtering panes were where I got most of my document counts, but those are also provided via the links under the left-hand pane's "Manage" section. That being said, I do think filtering, for example, by the "banking" tag and seeing a zero next to PNC is more confusing, but I recognize it may only be "more confusing" because I'm used to a not-specific-to-the-page number being there.

I'll noodle on this for a bit and if I can come up with a good argument, i'll open a FR. But, again, thank you, @shamoon, for confirming that it's not a bug. And fast, too. Wish all my questions could get service that quickly :blue_heart:

**Comment by shamoon** [comment]
Yea if there's clear consensus this is confusing as-is I would be happy to take a crack at implementing a change

**Comment by shamoon** [comment]
I actually think I see a simple way to implement this, just would love some clarity from users before deciding whether to implement

**Comment by jacroe** [comment]
That's lovely to hear. Give me a few days and I'l try to come up with an argument plus some acceptance criteria for it. And hopefully that will get a consensus

**Comment by shamoon** [comment]
See #3329
