### ISSUE TITLE
[BUG] Mails consumed although not fitting consumption rule

### ISSUE THREAD

**Issue by clemensrieder** [paperless-ngx/paperless-ngx#3332]
### Description

After upgrading to the newest version a couple of days ago I experienced that emails are processed although there is no file attached to the mail fitting my mail rule. The rule has been the same for months and working well. The attachments would be .png-files.

**Email inbox:**
<img width="490" alt="Bildschirmfoto 2023-05-06 um 15 12 21" src="https://user-images.githubusercontent.com/68914047/236627379-52268090-d3ad-480f-bc30-dac993de4cba.png">

**Email contents:**
<img width="603" alt="Bildschirmfoto 2023-05-06 um 15 12 25" src="https://user-images.githubusercontent.com/68914047/236627392-a90cc08a-bb8e-4db1-bc66-11ad225efc4b.png">

**Email attachments:**
<img width="328" alt="Bildschirmfoto 2023-05-06 um 15 31 16" src="https://user-images.githubusercontent.com/68914047/236627405-c5af22c4-270a-4168-885c-72b298320fc1.png">

**Server log:**
<img width="1441" alt="Bildschirmfoto 2023-05-06 um 15 18 48" src="https://user-images.githubusercontent.com/68914047/236627417-0b8dc6ad-ee9a-4082-933d-64610961edb6.png">

**Email rule:**
<img width="1016" alt="Bildschirmfoto 2023-05-06 um 15 25 09" src="https://user-images.githubusercontent.com/68914047/236627503-d270fb50-ab4c-4aa8-b784-27fea5feb2bf.png">

Is anyone else experiencing something similar?
Thank you for your lasting efforts in making such a wonderful piece of software!

### Steps to reproduce

Nothing the user has to do to reproduce.

### Webserver logs

```bash
see screenshots
```

### Paperless-ngx version

1.14.4

### Host OS

Debian 11

### Installation method

Docker - official image

### Configuration changes

No new changes introduces

**Comment by shamoon** [comment]
Indeed I think this is not intended, mails should be processed but if no files are consumed then the action shouldnt be performed. I've submitted a PR to fix this, whenever others on the team have some time to review
