### ISSUE TITLE
[BUG] Bulk editing not working in 1.14.1-1.14.4

### ISSUE THREAD

**Issue by lagset** [paperless-ngx/paperless-ngx#3341]
### Description

I have a paperless-ngx instance (1.14.4) with one super user which is only user for administrative tasks and two normal users with a wide range of permissions (every permission expect admin row and expect adding, updating and deleting groups/users) which are used by myself and my partner for adding and managing documents.

Here the permission matrix of the both users:
![image](https://user-images.githubusercontent.com/15156011/236683771-86545db5-2478-4671-841b-29df98ef0815.png)

I now have observed the following behaviour: When adding a new document to paperless I set the owner respectively to the user this documents belongs using my normal user account. When adding documents of my partner and changing the owner to her user and setting the permissions so my partner and I have viewing and editing rights this seems to work: I am still able to view, edit tags, correspondent, etc. of the document in the document detail view. However this is not true, when trying to edit the same document in the overview using the bulk editing feature.

### Steps to reproduce

1. Create two non-super users _foo_ and _bar_ with wide editing permissions.
2. Add or edit a document with the following permission settings:
 - Owner: bar
 - View: Users: foo, bar
 - Edit: Users: foo, bar
3. Result: The document is editable by _foo_ when opened in the detail view. The document cannot be edited by _foo_ using bulk editing in the document overview.

Expectation: The document can be edited by _foo_ using bulk editing as well, since the user has the permission to edit the document.

### Webserver logs

```bash
none
```

### Browser logs

```bash
none
```

### Paperless-ngx version

1.14.4

### Host OS

Synology DSM 7.1.1

### Installation method

Docker - official image

### Browser

Reproduced in_Firefox_, _Edge_

**Comment by shamoon** [comment]
Thanks, should be a simple fix
