### ISSUE TITLE
[BUG] document_sanity_checker uses wrong path

### ISSUE THREAD

**Issue by ciB89** [paperless-ngx/paperless-ngx#3355]
### Description

I tried running `document_sanity_checker` within my Home Assistant addon, but receive the following error:

```
?: PAPERLESS_CONSUMPTION_DIR is not writeable
        HINT: Set the permissions of
drwxr-xr-x root root /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
?: PAPERLESS_MEDIA_ROOT is not writeable
        HINT: Set the permissions of
drwxr-xr-x root root /usr/src/paperless/media
 to be writeable by the user running the Paperless services
```

It's true that those are not owned by the correct owner, because these are not the root/consume folders I set up in the environment variables, my paths are /mnt/...
The correct permissions are set for those folders, but it seems that the settings are not passed correctly to sanity_checker.

### Steps to reproduce

1. Set up custom paths for PAPERLESS_CONSUMPTION_DIR and PAPERLESS_MEDIA_ROOT
2. Run `document_sanity_checker` within the container

### Webserver logs

```bash
?: PAPERLESS_CONSUMPTION_DIR is not writeable
        HINT: Set the permissions of
drwxr-xr-x root root /usr/src/paperless/consume
 to be writeable by the user running the Paperless services
?: PAPERLESS_MEDIA_ROOT is not writeable
        HINT: Set the permissions of
drwxr-xr-x root root /usr/src/paperless/media
 to be writeable by the user running the Paperless services
```

### Paperless-ngx version

1.14.4

### Host OS

Raspberrypi4, RaspberrypiOS

### Installation method

Other (please describe above)

**Comment by stumpylog** [comment]
It's highly likely with a path like `/mnt/...` you're referring to a location on the **host** rather than inside the **container**.  The path inside is what paperless will use.

**Comment by ciB89** [comment]
Unfortunately I cannot provide the compose file, since it's the home assistant addon. I can only provide the logs of the addon, which include the environment variables / the mounting process. The folder definitely exists within the folder and files added to that folder are definitely consumed, also all my media (thumbnails etc.) are stored on the network share.

```
Starting...
/etc/cont-init.d/00-banner.sh: executing
-----------------------------------------------------------
 Add-on: Paperless NGX
 scan, index and archive all your physical documents
-----------------------------------------------------------
 Add-on version: 1.14.4
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 11 (bullseye)  (armv7 / raspberrypi4)
 Home Assistant Core: 2023.5.1
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums
-----------------------------------------------------------
 Provided by: https://github.com/alexbelgium/hassio-addons 
-----------------------------------------------------------
 Defining permissions for main user : 
User UID: 1000
User GID : 1000
-----------------------------------------------------------
/etc/cont-init.d/00-local_mounts.sh: executing
Local Disks mounting...
[20:24:28] INFO: Mounting G-Drive of type 
[20:24:29] INFO: Success! G-Drive mounted to /mnt/G-Drive
/etc/cont-init.d/00-smb_mounts.sh: executing
Mounting smb share(s)...
Using PUID 1000 and PGID 1000
[20:24:31] INFO: ... //192.168.0.177/ciB paperless files successfully mounted to /mnt/ciB paperless files with options ,uid=1000,gid=1000,iocharset=utf8
/etc/cont-init.d/01-custom_script.sh: executing
[20:24:32] INFO: Execute /config/addons_autoscripts/paperless-ng.sh if existing
[20:24:32] INFO: ... no script found
/etc/cont-init.d/20-folders.sh: executing
/etc/cont-init.d/31-nginx.sh: executing
/etc/cont-init.d/90-config_yaml.sh: executing
Using config file found in /config/addons_config/paperless_ng/config.yaml
Config file is a valid yaml
[20:24:34] INFO: Starting the app with the variables in /config/addons_config/paperless_ng/config.yaml
PAPERLESS_CSRF_TRUSTED_ORIGINS=\'redacted\'
PAPERLESS_OCR_PAGES=\'1\'
PAPERLESS_TASK_WORKERS=\'2\'
PAPERLESS_THREADS_PER_WORKER=\'1\'
PAPERLESS_OCR_CLEAN=\'none\'
PAPERLESS_WEBSERVER_WORKERS=\'1\'
PAPERLESS_CONSUMER_POLLING=\'600\'
PAPERLESS_CONSUMER_RECURSIVE=\'true\'
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=\'true\'
PAPERLESS_PRE_CONSUME_SCRIPT=\'/config/addons_config/paperless_ng/scripts/pre_consume.sh\'
PAPERLESS_CONSUMPTION_DIR=\'/mnt/ciB paperless files/media/consumer\'
PAPERLESS_MEDIA_ROOT=\'/mnt/ciB paperless files/media\'
/etc/cont-init.d/99-run.sh: executing
[20:24:37] INFO: Defining variables
[20:24:40] INFO: Defining database
...
```

**Comment by stumpylog** [comment]
Then it appears the environment is not being correctly set by the add on.  If addons allow shell access, you can check with `printenv` or similar.

The message printed is from a check run at every startup (at least in our own container) and for any command run, such as the sanity checker and the consumer.  The values are read from the environment, as Python sees it.  It's highly unlikely it is being set but Python somehow doesn't see it.

**Comment by ciB89** [comment]
```
S6_SERVICES_GRACETIME=0
PUID=0
HOSTNAME=db21ed7f-paperless-ng
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
PYTHON_VERSION=3.9.16
PACKAGES=redis-server yamllint pip libxml2-dev libxslt-dev python-dev libjpeg-dev zlib1g-dev python3-dev b
PWD=/usr/src/paperless/src
PYTHON_SETUPTOOLS_VERSION=58.1.0
TZ=Europe/Berlin
PAPERLESS_ADMIN_PASSWORD=redacted
HOME=/root
LANG=C.UTF-8
PGID=0
GPG_KEY=redacted
HASSIO_TOKEN=redacted
PAPERLESS_ADMIN_USER=redacted
TERM=xterm
SUPERVISOR_TOKEN=redacted
SHLVL=1
PYTHON_PIP_VERSION=22.0.4
PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
S6_CMD_WAIT_FOR_SERVICES=1
_=/usr/bin/printenv

```

You are right, there is no env set. But as far as I know it's using the config.cfg file within the container for the settings, at least I have configured a custom config path within the addon's setting (which should be PAPERLESS_CONFIGURATION_PATH), and the file contains all the settings. And as I mentioned, it works, except for the sanity_checker.

**Comment by stumpylog** [comment]
I assume you're running the sanity checker manually in this case?  As opposed to the scheduled task?

**Comment by ciB89** [comment]
I just realised that that does not make sense, because if the PAPERLESS_CONFIGURATION_PATH were set then it would show in printenv.  

At the same time: `[2023-05-08 19:31:26,036] [INFO] [paperless.management.consumer] Polling directory for changes: /mnt/ciB paperless files/media/consumer`
I don't get that it works and does not work at the same time 

> I assume you're running the sanity checker manually in this case? As opposed to the scheduled task?

Yes, that is correct. I believe the env are not correctly set (since of a delay connecting to the network share?) as mentioned here:  https://github.com/alexbelgium/hassio-addons/issues/674#issuecomment-1417846322 but different from what I experience it defaults to the defaults set up in the run script, which should be /config/addons_config/paperless_ng/... .

I am going to open an issue with @alexbelgium.

**Comment by stumpylog** [comment]
It's the way the addon start up happens.  [Here](https://github.com/alexbelgium/hassio-addons/blob/a63458b3337e8022508f0d469613e27895165e26/paperless_ngx/rootfs/etc/cont-init.d/99-run.sh#L29) it exports the configured values.  But that only makes it available in this shell or subshells, such as [here](https://github.com/alexbelgium/hassio-addons/blob/a63458b3337e8022508f0d469613e27895165e26/paperless_ngx/rootfs/etc/cont-init.d/99-run.sh#L96).  That's why the normal running is fine, it's environment is correctly setup.

So when you enter a shell in the addon, the environment is not present for that shell.  You'd see the same messages if trying to do an export or generally run any command.

As this isn't an issue in paperless, I'm going to close this out now.
