### ISSUE TITLE
[BUG] Issue with parsing a text file

### ISSUE THREAD

**Issue by hxck** [paperless-ngx/paperless-ngx#3433]
### Description

When trying to upload a text file containing key information for a Wordpress plugin, Paperless fails to open resource. Paperless is currently running in a Docker container set up through CasaOS on Debian 11 with nginx Reverse Proxy Manager.

File in question: 42359150-slider-revolution-responsive-wordpress-plugin-license.txt
Error: cannot open resource : Traceback (most recent call last):

![vivaldi_Yyl8JSyjCa](https://github.com/paperless-ngx/paperless-ngx/assets/1754583/6ea63266-db87-45c1-bfda-75f46e571bb5)

Content of the file:
--------------------------------------
Licensor's Author Username:
themepunch

Licensee:
MyName

Item Title:
Slider Revolution Responsive WordPress Plugin

Item URL:
https://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380

Item ID:
2751380

Item Purchase Code (alphanumeric):
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Purchase Date:
2017-11-05 01:17:06 UTC
--------------------------------------

### Steps to reproduce

1. Go to my Paperless instance address (docs.web.site)
2. Drag and drop generated txt file onto the page to initiate upload
3. Check File Tasks page (/tasks)

### Webserver logs

```bash
[2023-05-21 01:03:51,398] [INFO] [paperless.consumer] Consuming 42359150-slider-revolution-responsive-wordpress-plugin-license.txt

[2023-05-21 01:03:51,403] [DEBUG] [paperless.consumer] Detected mime type: text/plain

[2023-05-21 01:03:51,407] [DEBUG] [paperless.consumer] Parser: TextDocumentParser

[2023-05-21 01:03:51,410] [DEBUG] [paperless.consumer] Parsing 42359150-slider-revolution-responsive-wordpress-plugin-license.txt...

[2023-05-21 01:03:51,410] [DEBUG] [paperless.consumer] Generating thumbnail for 42359150-slider-revolution-responsive-wordpress-plugin-license.txt...
```

### Browser logs

```bash
cannot open resource : Traceback (most recent call last):
  File "/src/django-q/django_q/cluster.py", line 434, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/app/paperless/src/documents/tasks.py", line 162, in consume_file
    document = Consumer().try_consume_file(
  File "/app/paperless/src/documents/consumer.py", line 315, in try_consume_file
    thumbnail = document_parser.get_thumbnail(
  File "/app/paperless/src/paperless_text/parsers.py", line 26, in get_thumbnail
    font = ImageFont.truetype(
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 959, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

### Paperless-ngx version

1.8.0

### Host OS

Debian Linux Bullseye

### Installation method

Docker - official image

### Browser

Vivaldi 6.0.2979.22 (Stable channel) (64-bit)

**Comment by stumpylog** [comment]
Instead of the file content, could you attach it?

**Comment by shamoon** [comment]
Yea Im also able to consume a current version of a file like this

Please update -ngx and let us know if you can still re-create and if so provide a file

<img width="1339" alt="Screenshot 2023-05-21 at 9 19 18 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/c590321a-1c66-4f8a-9a93-3187947e6007">

[1234-woocommerce-partial-orders-license.txt](https://github.com/paperless-ngx/paperless-ngx/files/11525019/1234-woocommerce-partial-orders-license.txt)

**Comment by warrior-rockk** [comment]
I have the same exact issue with the same version (1.8.0 I don't know the internal version) and I tried with the txt file posted by @shamoon

**Comment by shamoon** [comment]
1.8.0 is many versions old, sounds like you'll need to upgrade.

**Comment by warrior-rockk** [comment]
> 1.8.0 is many versions old, sounds like you'll need to upgrade.

Ah, perfect! I was thinking that i was using the lastest version. 
I'm using a docker image from lscr.io/linuxserver/paperless-ngx. Is not the correct repository?
Thanks and regards!

**Comment by shamoon** [comment]
They gave up on supporting that image 8 months ago. You’d have to migrate your setup to our official image

https://github.com/linuxserver/docker-paperless-ngx

**Comment by stumpylog** [comment]
We have a guide for migrating in what is hopefully the easiest way: https://docs.paperless-ngx.com/setup/#migrating-from-linuxserverio-docker-image

**Comment by warrior-rockk** [comment]
I have done the migration (to 1.14.5) and now I can consume text files without problems. Thanks!

**Comment by stumpylog** [comment]
@hxck Have you upgrade and resolved your issue?  We'd like to close this issue out.

**Comment by stumpylog** [comment]
Given this can't be reproduced with our image on the latest version, updating to that version is documented and at least one other person was able to resolve their error, I'm going to close this out.

Do let us know if you have further issues.

**Comment by hxck** [comment]
Sorry for disappearing there, folks, but yes, I had the same issue as @warrior-rockk and was using the LSIO image. I appreciate the nod toward the migration docks. Thanks 👍
