### ISSUE TITLE
[BUG] File tasks page does not paginate output leading to loss of responsiveness with large file numbers

### ISSUE THREAD

**Issue by dcava** [paperless-ngx/paperless-ngx#3438]
### Description

When importing large numbers of files (thousands) at a time, the File Tasks tabs (Failed, Complete, Started, Queued) don't paginate output. This can lead to thousands of lines of output and loss of responsiveness of the page.

As there is loss of responsiveness, you then cannot "Dismiss" the lines or interact with the frontend. Restarting fixes.

Depending on the file number, eventually the page will become responsive again, but with large enough lists I get a blank page and have to manually reload.

### Steps to reproduce

1. Import/Add more than around 3000 files
2. Go to File Tasks page - select "Queued" tab
3. try to scroll file list leads to unresponsive page
4. Similar occurs when (for e.g) the Failed tab fills with multiple errors.

### Webserver logs

```bash
No logs from the webserver - doesn't actually crash. Developer console on Chrome shows very long running tasks and a large Cumulative Layout shift score.
```

### Paperless-ngx version

1.14.5

### Host OS

Docker Compose on M1 pro Mac Studio

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
Thousands at a time is a big more than imagined. Should be simple enough though to apply the standard pagination

**Comment by dcava** [comment]
Yeah, I realise I'm probably pushing things!! (total ingest so far is nearly 200000 files) Thanks for looking into it.

**Comment by shamoon** [comment]
I’m not really sure what the solution will be here. Is this a real use case or just pushing it for the sake of it? Is your server under load (eg consuming docs) or you mean just when trying to load the UI with thousands of tasks in the queue?

**Comment by shamoon** [comment]
I just tested this with 3k tasks and tbh, it did OK for me, UI stuttered but then responsive without a reload.

The problem with just paginating the tasks is that they are just all returned and the UI 'categorizes' them by status. To change this I think we'd have to change the API to paginate each status group, in addition to total counts.

Again, I just wonder if this is a 'real' problem worth working on...

<img width="582" alt="Screenshot 2023-05-22 at 12 39 07 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/34122eac-0891-4427-9628-1477dd3ebe4f">

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/9507e7a6-4986-468b-8df4-c2e1782109a2

**Comment by shamoon** [comment]
Ps. I tried dropping 2k files into Google Drive and it becomes completely unresponsive and crashes...

**Comment by dcava** [comment]
Server is not under particular load - it's just the UI is struggling with the tasks in the queue. At the moment, I'm ingesting by dropping files into the consume directory directly, not dropping them into the UI.

This is a real use case - I have a large number of medical records in PDF/txt/doc format that are not really accessible at the moment and I'm progressively adding them to ngx. My plan is to ingest all and have available as a searchable resource for research. All the files are small, but there are a lot of them - I would estimate 220,000 in total. I'm ingesting in batches of a few thousand at once, and sometimes there are a large number of failed tasks (mainly duplicates and of "NoneType" errors). The tab numbers like the video you show do update in real time - it just becomes an issue because the Failed tab is rendered as soon as you click on the File tasks page and if the number is high, it becomes unresponsive.

I guess I wasn't really aware what limitations there might be in terms of overall size of the document repo with ngx when I started, and now that I'm most of the way through, I'm keen to persist.

Pagination may not be the best way, agreed, especially if the whole array is returned and processed in UI. I haven't looked at the current code, but is it currently progressively rendered or is that an option?

It's not a critical problem - and I'm guessing my file numbers are an edge case. Is there an alternative option for me in terms of an "offline" ingestion method to process a large number of documents?

**Comment by shamoon** [comment]
For me, after the batch is done, even with 2k failed tasks it loads fine and I can dismiss all.

but I’m thinking stumpylog meant paginating in the UI not the api. I’m not sure if that will make a difference but yea thatd be simpler to try, I can look at that tomorrow

**Comment by stumpylog** [comment]
I was thinking the backend should paginate as well, since it looks like all the tasks are sent in each response

**Comment by stumpylog** [comment]
Until the next release is out, you can manually ackownledge or delete tasks from inside the Docker container.

Something like:
```python
python3 manage.py shell
>>> from documents.models import PaperlessTask
>>> PaperlessTask.objects.filter(acknowledged=False).update(acknowledged=True)
or
>>> PaperlessTask.objects.all().delete()
```

**Comment by dcava** [comment]
Updated container to include this PR - UI paginates well and very responsive even with 90000 docs in the queue (don't judge me).

Thanks
