### ISSUE TITLE
[BUG] Upgraded to 1.14.5 UI is mostly blank. 

### ISSUE THREAD

**Issue by WBWBW** [paperless-ngx/paperless-ngx#3439]
### Description

I updated to 1.14.5 today. Running in Docker on Unraid. 

After the update, the UI is mostly blank. The dashboard is missing all my tags and inbox documents. I was also prompted by the “Paperless Tour” window. 

On the right side, there is still a count of docs. If I click that, I get a “you do not have permission to do that”. See screenshot.

![Image 5-21-23 at 7 11 PM](https://github.com/paperless-ngx/paperless-ngx/assets/42853455/1e2ff007-8535-4e6e-8d1f-4884f392e8d6)

I tried to revert to 1.13.0 but I got the same result. 

### Steps to reproduce

N/A

### Webserver logs

```bash
I do not see anything out of place besides this: 
[WARNING] [django.request] Forbidden: /api/documents/
```

### Paperless-ngx version

1.14.5

### Host OS

Unraid

### Installation method

Docker - official image

### Browser

Safari, Chrome

**Comment by mkobler** [comment]
@WBWBW  I am also seeing this after upgrading to 1.15.0 from 1.13.0. 

How were you able to resolve this issue?  I looked over the release notes and didn't find any information related to updating to these newer versions.

**Comment by WBWBW** [comment]
> @WBWBW I am also seeing this after upgrading to 1.15.0 from 1.13.0.
> 
> How were you able to resolve this issue? I looked over the release notes and didn't find any information related to updating to these newer versions.

I had multiple non admin users. I had to login with the main admin account and update the new permissions for the other users.

**Comment by shamoon** [comment]
Assuming you have the same issue as OP, lmost certainly the user you are logged in as does not have sufficient permissions. That’s what the error says after all. The documentation recommends using a ‘super user’ to avoid this kind of issue, from there you can tweak things if you’d like.

you can change your user rights in the Django backend `/admin/` or create a new superuser

**Comment by mkobler** [comment]
I'd forgotten about the admin account from when I set things up as I'd only saved the user account information for some reason.  I was able to log into it and now see all the ways I can configure the user permissions.

Thanks for the pointers!
