### ISSUE TITLE
[BUG] Dump SQLite (Unable to serialize database: no such column: documents_correspondent.owner_id)

### ISSUE THREAD

**Issue by StiviiK** [paperless-ngx/paperless-ngx#3442]
### Description

I am currently trying to move from Linuxserver.io Paperless NG to Paperless NGX, but unfornately the dump database command (from SQLite) seems not to be working.

https://docs.paperless-ngx.com/setup/#migrating-from-linuxserverio-docker-image

### Steps to reproduce

1. Follow steps to migrate from Linuxserver.io Paperless NG to Paperless NGX
2. Try to move the SQLite to MySQL

### Webserver logs

```bash
python3 manage.py dumpdata --database=sqlite --exclude=contenttypes --exclude=auth.Permission > data.json
CommandError: Unable to serialize database: no such column: documents_correspondent.owner_id
```

### Paperless-ngx version

1.14.5

### Host OS

Debian 11

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
I would suggest using the export and import features instead of manually trying to save the database

**Comment by stumpylog** [comment]
Based on the error, I'm guessing after you adjusted the parameters needed to transition LSIO to the official image, you didn't allow it to start and preform migrations.  That would be the explanation for a missing column.  

The first warning for changing databases is to be fully migrated.  The image does this on startup.

**Comment by StiviiK** [comment]
>I would suggest using the export and import features instead of manually trying to save the database.

Which import export features are you talking about?

>Based on the error, I'm guessing after you adjusted the parameters needed to transition LSIO to the official image, you didn't allow it to start and preform migrations. That would be the explanation for a missing column.
> The first warning for changing databases is to be fully migrated. The image does this on startup.

I did let the Image boot fully up and complete all its migrations (on the new MySQL database). The previous data/config files where taking from a fully working and long previously running instance of LSIO image.

**Comment by stumpylog** [comment]
The SQLite database you are migrating from needs to be fully migrated, not just the destination database.  If they're not on the same migration, you'll get errors like the above.  That would mean doing the transition from LSIO first, starting that container, letting it migrate the SQLite DB, then following the steps to change database types.

**Comment by stumpylog** [comment]
I'm assuming after the migration of both databases this transition worked correctly?

**Comment by StiviiK** [comment]
I am closing the issue. I migrated the data manually without trying to migrate the database.
