### ISSUE TITLE
[BUG] The main container won't stop when asked

### ISSUE THREAD

**Issue by asitemade4u** [paperless-ngx/paperless-ngx#346]
**Describe the bug**
- I am deploying the `ghcr.io/paperless-ngx/paperless-ngx:latest` image of Paperless-ngx along with Redis, Apache Tika, and Gotenberg. I am using Portainer Business Edition to manage the stack.
- When asked, all containers stop except the main Paperless-ngx container.
- I am therefore unable to delete the stack.
- It does the same when executing `docker stop` from the CLI

**To Reproduce**
1. In Portainer Business Edition > Select environment > Stacks > Paperless-ngx
3. Click on **Stop this stack** > nothing happens
4. Select Redis, Apache Tika, and Gotenberg in the list of containers below then click on **Stop** > they stop
6. Select paperless-ngx container then **Stop** > the container does not stop and a time out error is reported
7. Yet the container is not really active any longer: I can't access its log from the console

**Expected behavior**
The Paperless-ngx container should stop in order for the whoe stack to stop.

**Relevant information**
 - Ubuntu Server 20.04
 - Browser Firefox
 - Version last as I am using WatchTower

**Comment by asitemade4u** [comment]
### Update
I also tried from the CLI:

- `docker kill`
- `docker stop`
- `docker rm --force`

And none worked.

**Comment by shamoon** [comment]
This is an odd one. I dont use business edition but I am able to stop via portioner without issue. Does the container have any errors? I guess I'm just questioning whether this is to do with the container itself or something specific to your setup. Have you tried recreating the container completely?

<img width="325" alt="Screen Shot 2022-03-14 at 8 53 26 PM" src="https://user-images.githubusercontent.com/4887959/158302925-1cf3a07d-d397-4398-938b-672eb21b01fe.png">

**Comment by shamoon** [comment]
Please re-open if needed
