### ISSUE TITLE
[BUG] setting PAPERLESS_DB_TIMEOUT causes stackdump (psycopg2.ProgrammingError: invalid dsn: invalid connection option "timeout")

### ISSUE THREAD

**Issue by r-pufky** [paperless-ngx/paperless-ngx#3569]
### Description

This configuration parameter is **not** specified in any of the default samples/templates; though it does appear in https://docs.paperless-ngx.com/configuration/#database

Paperless runs fine without specifying this.

Specifying any value for this parameter results in the following stackdump:

```
Traceback (most recent call last):
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
    self.connect()
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 121, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/var/lib/paperless-ngx-v1.15.1/.venv/lib/python3.9/site-packages/psycopg2/extensions.py", line 167, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "timeout"
```

It should be noted that the [psycopg2](https://github.com/psycopg/psycopg2/issues/1241) python module points out that this is consumer use problem, not a library issue.

### Steps to reproduce

1. Setup paperless with postgresql (bare metal in this case, but any deployment should work).
2. Explicitly specify a database timeout option `PAPERLESS_DB_TIMEOUT=5.0`
3. Run paperless, or any `manage.py` commands, such as `createsuperuser`

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

1.15.1

### Host OS

Debian bullseye, x64

### Installation method

Bare metal

### Browser

N/A

### Configuration changes

PAPERLESS_DB_TIMEOUT=5.0

### Other

Configuration works without specifying this setting.

**Comment by stumpylog** [comment]
The quick solution is to note that is only for SQLite and shouldn't be set for other database types.

**Comment by r-pufky** [comment]
I interpret the current documentation as it applying to postgres as well; if it really only applies to SQLite then it should be explicitly stated, as the other DB_ options:

```
Amount of time for a database connection to wait for the database to unlock. Mostly applicable for an sqlite based installation, consider changing to postgresql if you need to increase this.

Defaults to unset, keeping the Django defaults.
```

specifically, the _need to increase this_ I intrepret as applying to the postgres connection timeout limit.

**Comment by stumpylog** [comment]
It's trying to say that if you're setting this value, you're probably running into SQLite's concurrency limitations and should consider upgrading to a database that actually supports multiple writers.

That said, it'll probably get fixed for the other supported DB types, if they support it.  Though I'm not sure in what kind of cases it  would be needed to set.

**Comment by r-pufky** [comment]
I appreciate the quick responses and patches. Thanks everyone!
