### ISSUE TITLE
[BUG] Warning when migrating database MariaDB 1.14.5 -> 1.15.1

### ISSUE THREAD

**Issue by encspot** [paperless-ngx/paperless-ngx#3577]
### Description

When migrating the MariaDB Database after updating from 1.14.5 to 1.15.1:

Tried again to make sure, dependencies are fullfilled - warning remained.

<details>
  <summary>pip log</summary>
root@encspot-paperless:/opt/paperless# sudo -Hu paperless pip3 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple, https://www.piwheels.org/simple
Ignoring backports.zoneinfo: markers 'python_version < "3.9"' don't match your environment
Ignoring importlib-resources: markers 'python_version < "3.9"' don't match your environment
Ignoring typing-extensions: markers 'python_version < "3.10"' don't match your environment
Ignoring zipp: markers 'python_version < "3.10"' don't match your environment
Requirement already satisfied: amqp==5.1.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (5.1.1)
Requirement already satisfied: anyio==3.7.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (3.7.0)
Requirement already satisfied: asgiref==3.7.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (3.7.2)
Requirement already satisfied: async-timeout==4.0.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (4.0.2)
Requirement already satisfied: billiard==3.6.4.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (3.6.4.0)
Requirement already satisfied: bleach==6.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (6.0.0)
Requirement already satisfied: brotli==1.0.9 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (1.0.9)
Requirement already satisfied: celery[redis]==5.2.7 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (5.2.7)
Requirement already satisfied: certifi==2023.5.7 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2023.5.7)
Requirement already satisfied: cffi==1.15.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.15.1)
Requirement already satisfied: channels==4.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (4.0.0)
Requirement already satisfied: channels-redis==4.1.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (4.1.0)
Requirement already satisfied: charset-normalizer==3.1.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (3.1.0)
Requirement already satisfied: click==8.1.3 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (8.1.3)
Requirement already satisfied: click-didyoumean==0.3.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (0.3.0)
Requirement already satisfied: click-plugins==1.1.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (1.1.1)
Requirement already satisfied: click-repl==0.2.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (0.2.0)
Requirement already satisfied: coloredlogs==15.0.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (15.0.1)
Requirement already satisfied: concurrent-log-handler==0.9.24 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 22)) (0.9.24)
Requirement already satisfied: cryptography==40.0.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 23)) (40.0.1)
Requirement already satisfied: dateparser==1.1.8 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 24)) (1.1.8)
Requirement already satisfied: deprecation==2.1.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 25)) (2.1.0)
Requirement already satisfied: django==4.1.9 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 26)) (4.1.9)
Requirement already satisfied: django-celery-results==2.5.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 27)) (2.5.1)
Requirement already satisfied: django-compression-middleware==0.5.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 28)) (0.5.0)
Requirement already satisfied: django-cors-headers==4.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 29)) (4.0.0)
Requirement already satisfied: django-extensions==3.2.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 30)) (3.2.1)
Requirement already satisfied: django-filter==22.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 31)) (22.1)
Requirement already satisfied: django-guardian==2.4.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 32)) (2.4.0)
Requirement already satisfied: djangorestframework==3.14.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 33)) (3.14.0)
Requirement already satisfied: djangorestframework-guardian==0.3.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 34)) (0.3.0)
Requirement already satisfied: exceptiongroup==1.1.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 35)) (1.1.1)
Requirement already satisfied: filelock==3.12.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 36)) (3.12.0)
Requirement already satisfied: flower==1.2.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 37)) (1.2.0)
Requirement already satisfied: gunicorn==20.1.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 38)) (20.1.0)
Requirement already satisfied: h11==0.14.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 39)) (0.14.0)
Requirement already satisfied: hiredis==2.2.3 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 40)) (2.2.3)
Requirement already satisfied: httptools==0.5.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 41)) (0.5.0)
Requirement already satisfied: humanfriendly==10.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 42)) (10.0)
Requirement already satisfied: humanize==4.6.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 43)) (4.6.0)
Requirement already satisfied: idna==3.4 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 44)) (3.4)
Requirement already satisfied: imap-tools==1.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 45)) (1.0.0)
Requirement already satisfied: img2pdf==0.4.4 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 46)) (0.4.4)
Requirement already satisfied: inotify-simple==1.3.5 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 48)) (1.3.5)
Requirement already satisfied: inotifyrecursive==0.3.5 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 49)) (0.3.5)
Requirement already satisfied: joblib==1.2.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 50)) (1.2.0)
Requirement already satisfied: kombu==5.2.4 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 51)) (5.2.4)
Requirement already satisfied: langdetect==1.0.9 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 52)) (1.0.9)
Requirement already satisfied: lxml==4.9.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 53)) (4.9.2)
Requirement already satisfied: msgpack==1.0.5 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 54)) (1.0.5)
Requirement already satisfied: mysqlclient==2.1.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 55)) (2.1.1)
Requirement already satisfied: nltk==3.8.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 56)) (3.8.1)
Requirement already satisfied: numpy==1.24.3 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 57)) (1.24.3)
Requirement already satisfied: ocrmypdf==14.2.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 58)) (14.2.1)
Requirement already satisfied: packaging==23.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 59)) (23.1)
Requirement already satisfied: pathvalidate==3.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 60)) (3.0.0)
Requirement already satisfied: pdf2image==1.16.3 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 61)) (1.16.3)
Requirement already satisfied: pdfminer.six==20221105 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 62)) (20221105)
Requirement already satisfied: pikepdf==7.2.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 63)) (7.2.0)
Requirement already satisfied: pillow==9.5.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 64)) (9.5.0)
Requirement already satisfied: pluggy==1.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 65)) (1.0.0)
Requirement already satisfied: portalocker==2.7.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 66)) (2.7.0)
Requirement already satisfied: prometheus-client==0.17.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 67)) (0.17.0)
Requirement already satisfied: prompt-toolkit==3.0.38 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 68)) (3.0.38)
Requirement already satisfied: psycopg2==2.9.6 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 69)) (2.9.6)
Requirement already satisfied: pycparser==2.21 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 70)) (2.21)
Requirement already satisfied: python-dateutil==2.8.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 71)) (2.8.2)
Requirement already satisfied: python-dotenv==1.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 72)) (1.0.0)
Requirement already satisfied: python-gnupg==0.5.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 73)) (0.5.0)
Requirement already satisfied: python-ipware==0.9.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 74)) (0.9.0)
Requirement already satisfied: python-magic==0.4.27 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 75)) (0.4.27)
Requirement already satisfied: pytz==2023.3 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 76)) (2023.3)
Requirement already satisfied: pyyaml==6.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 77)) (6.0)
Requirement already satisfied: pyzbar==0.1.9 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 78)) (0.1.9)
Requirement already satisfied: rapidfuzz==3.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 79)) (3.0.0)
Requirement already satisfied: redis[hiredis]==4.5.5 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 80)) (4.5.5)
Requirement already satisfied: regex==2023.5.5 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 81)) (2023.5.5)
Requirement already satisfied: reportlab==3.6.12 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 82)) (3.6.12)
Requirement already satisfied: requests==2.31.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 83)) (2.31.0)
Requirement already satisfied: scikit-learn==1.2.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 84)) (1.2.2)
Requirement already satisfied: scipy==1.8.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 85)) (1.8.1)
Requirement already satisfied: setproctitle==1.3.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 86)) (1.3.2)
Requirement already satisfied: setuptools==67.8.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 87)) (67.8.0)
Requirement already satisfied: six==1.16.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 88)) (1.16.0)
Requirement already satisfied: sniffio==1.3.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 89)) (1.3.0)
Requirement already satisfied: sqlparse==0.4.4 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 90)) (0.4.4)
Requirement already satisfied: threadpoolctl==3.1.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 91)) (3.1.0)
Requirement already satisfied: tika==2.6.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 92)) (2.6.0)
Requirement already satisfied: tornado==6.3.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 93)) (6.3.2)
Requirement already satisfied: tqdm==4.65.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 94)) (4.65.0)
Requirement already satisfied: tzlocal==5.0.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 96)) (5.0.1)
Requirement already satisfied: urllib3==2.0.2 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 97)) (2.0.2)
Requirement already satisfied: uvicorn[standard]==0.22.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 98)) (0.22.0)
Requirement already satisfied: uvloop==0.17.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 99)) (0.17.0)
Requirement already satisfied: vine==5.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 100)) (5.0.0)
Requirement already satisfied: watchdog==2.3.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 101)) (2.3.1)
Requirement already satisfied: watchfiles==0.19.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 102)) (0.19.0)
Requirement already satisfied: wcwidth==0.2.6 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 103)) (0.2.6)
Requirement already satisfied: webencodings==0.5.1 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 104)) (0.5.1)
Requirement already satisfied: websockets==11.0.3 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 105)) (11.0.3)
Requirement already satisfied: whitenoise==6.4.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 106)) (6.4.0)
Requirement already satisfied: whoosh==2.7.4 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 107)) (2.7.4)
Requirement already satisfied: zstandard==0.21.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 109)) (0.21.0)
Requirement already satisfied: zxing-cpp==2.0.0 in ./.local/lib/python3.10/site-packages (from -r requirements.txt (line 110)) (2.0.0)
Requirement already satisfied: typing-extensions>=4 in ./.local/lib/python3.10/site-packages (from asgiref==3.7.2->-r requirements.txt (line 5)) (4.5.0)
</details>

root@encspot-paperless:/opt/paperless# 
root@encspot-paperless:/opt/paperless# cd src/
root@encspot-paperless:/opt/paperless/src# sudo -Hu paperless python3 manage.py migrate
System check identified some issues:

WARNINGS:
**documents.Correspondent: (models.W036) MariaDB does not support unique constraints with conditions.
        HINT: A constraint won't be created. Silence this warning if you don't care about it.
documents.DocumentType: (models.W036) MariaDB does not support unique constraints with conditions.
        HINT: A constraint won't be created. Silence this warning if you don't care about it.
documents.StoragePath: (models.W036) MariaDB does not support unique constraints with conditions.
        HINT: A constraint won't be created. Silence this warning if you don't care about it.
documents.Tag: (models.W036) MariaDB does not support unique constraints with conditions.
        HINT: A constraint won't be created. Silence this warning if you don't care about it.**
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless_mail, sessions
Running migrations:
  No migrations to apply.

### Steps to reproduce

1. Update files to 1.15.1,
2. Update dependencies
3. run migration

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.15.1

### Host OS

Ubuntu 22.04 /  5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Bare metal

**Comment by encspot** [comment]
I also tried MariaDB 10.11 (Ubuntu 23.04) - same issue.
I did revert back to paperless-ngx 1.14.5. Excecuting the migration also shows the warning, so it apperently is not related to this specific version. Is there a possibility to see what the migration tries to do (SQL statements etc.)? It seems to be a specific issue with my configuration. :(

Since it is "only" a warning I don't know if I should ignore it, since I did not have any isses while using 1.14.5 ...

**Comment by stumpylog** [comment]
Neither Django nor mysqlclient updated between those versions, which would be my only real candidates for introducing a new warning.

I also see no migrations created between the versions of paperless you listed.

The warning points to all the models which have some sort of matching, which were updated in #2827 to allow users to have tags of the same name, unique based on the tag owner.  So any effect I can image would be minimal at most

**Comment by encspot** [comment]
I knew about the caveats and never realized the warnings before. I now switched to postgresql, since it isn't very complicated to do ( dumpdata, migrate the new DB and loaddata).
Even if the warnings probably wouldn't interfere with my usage concerning tags I feel more save with switching the DMBS.

Thanks for your support and for you taking time to explan :)
