### ISSUE TITLE
[Suggested Fix] Bugs #817, #712 (from pull/674). 

### ISSUE THREAD

**Issue by r-pufky** [paperless-ngx/paperless-ngx#3588]
### Description

Both issues are closed to all but collaborators, creating a bug to comment on both of them.

1) The reverse proxy instructions should include the **Referrer-Policy** header. Certain referrer policies will cause paperless to throw the 403, including `no-referrer`, which is recommended all over as a way to secure your NGINX instance - my guess a large number of folks have set this globally and don't remember. I recommend explicitly setting this as follows for the paperless proxy:

``` nginx
add_header Referrer-Policy 'strict-origin-when-cross-origin';
```

2) `X-Forwarded` headers are specified in the proxy configuration, but no mention in these bug / proxy configurations to look at the Django `X_FORWARD_{HOST|PORT}` settings. I suggest that for proxy configuration, reasonable defaults for these and other critical variables should be explicitly mentioned, include the updated proxy configuration:

``` bash
PAPERLESS_URL=https://paperless.example.com
USE_X_FORWARD_HOST=true
USE_X_FORWARD_PORT=true
```

2) I believe the **P3P** reverse proxy fix is a red-herring. The only browsers that [support it are IE and Edge](https://en.wikipedia.org/wiki/P3P). People who run into this issue likely have blindly set reverse proxy options without considering everything that is going on. I would suggest this be removed, or kept in a footnote of wild things to try if people just can't get a reverse proxy to work.

### Steps to reproduce

1. Set Referrer-Policy to `no-referrer`.
2. reload NGINX.
3. 403 after login.

1. Have working NGINX reverse proxy w/ login and redirect to main page.
1. Disable X_FORWARD_HOST, X_FORWARD_PORT.
2. Restart/reload paperless webserver.
3. Attempt to login via reverse proxy again. 403 after login.

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

1.15.1

### Host OS

Debianx x64

### Installation method

Bare metal

### Browser

Chrome (latest), Firefox (latest)

### Configuration changes

X_FORWARD_HOST, X_FORWARD_PORT (paperless.conf), Referrer-Policy (NGINX) -- see above.

**Comment by shamoon** [comment]
Thanks for the info. Reverse proxy info is maintained in the wiki, you can edit it there https://github.com/paperless-ngx/paperless-ngx/wiki/Using-a-Reverse-Proxy-with-Paperless-ngx

**Comment by r-pufky** [comment]
Great - didn't know if the original bug contributors wanted to chim in before I submitted a change.

**Comment by r-pufky** [comment]
Wiki updated.
