### ISSUE TITLE
[BUG] Make tika work on Raspberry Pi

### ISSUE THREAD

**Issue by s-martin** [paperless-ngx/paperless-ngx#362]
**Describe the bug**
Office file formats (i.e. tika) does not work when installing on a Raspberry Pi (4).

see also https://github.com/jonaswinkler/paperless-ng/issues/1499

Fix seems to be to use ARM tika image in docker-compose.yml `image: abhilesh7/apache-tika-arm`
See https://github.com/jonaswinkler/paperless-ng/issues/1499#issuecomment-1037527276

**To Reproduce**
1. Use installer script on a Raspberry Pi for docker with tika option 
2. Put office document in consume directory 
3. See error `Could not parse /tmp/paperless/paperless-upload-4__50jys with tika server at http://tika:9998: HTTPConnectionPool(host='tika', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x71b69178>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

**Expected behavior**
Office document should be parsed correctly.

**Relevant information**
 - Host OS of the machine running paperless: Raspian Buster
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 1.0.0] 1.6
 - Installation method: [docker]
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`. Using tika option

**Comment by s-martin** [comment]
Ok, I have just seen there’s already a PR #27

**Comment by shamoon** [comment]
Closed via https://github.com/paperless-ngx/paperless-ngx/commit/5065f2cb80fbfc84f5e9a5219c8cafc716573e89
