### ISSUE TITLE
[BUG] Ambiguous description of `PAPERLESS_OCR_LANGUAGES` in configuration docs

### ISSUE THREAD

**Issue by DrMurx** [paperless-ngx/paperless-ngx#3624]
### Description

The documentation lists `PAPERLESS_OCR_LANGUAGES` twice with different meanings.

In the [OCR Settings](https://github.com/paperless-ngx/paperless-ngx/blob/05188aed6db2b0fe9a9f886939ff164478ec0c08/docs/configuration.md?plain=1#L505) it claims to hint the correct languages for tesseract, allowing a single value which might be a composite of multiple languages (`deu+eng`).

In the [Docker specific settings](https://github.com/paperless-ngx/paperless-ngx/blob/05188aed6db2b0fe9a9f886939ff164478ec0c08/docs/configuration.md?plain=1#L1183) it's being used to install additional language support for the OCR beyond English, German, Italian, Spanish and French. It allows multiple values and doesn't mention the composite with `+`.

It's therefore very unclear what the expected value or set of values should look like.

### Steps to reproduce

1. Read the configuration docs ;-)

### Webserver logs

```bash
---
```

### Paperless-ngx version

1.16.1

### Host OS

Linux

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
One has an S, one does not.  They are two different settings with two different purposes and two different formats. That's not a bug

**Comment by DrMurx** [comment]
@stumpylog Darn, you are right 🤦‍♂️  But then I would argue that it's easy to overlook and easy to confuse. 

`PAPERLESS_OCR_LANGUAGES` should rather be `PAPERLESS_INSTALL_ADDITIONAL_OCR_LANGUAGES` or something like this to make it more distinct.

**Comment by Atemu** [comment]
The naming confused me too. Especially that the purpose of LANGUAGE**S** is the *installation* of further languages which IMO is classically far outside of Paperless' domain as it's not a package manager.
