### ISSUE TITLE
[BUG] postgres ssl only connection is not working with paperless-ngx 1.16

### ISSUE THREAD

**Issue by RogerSik** [paperless-ngx/paperless-ngx#3633]
### Description

With 

```
PAPERLESS_DBSSLMODE=prefer
```
it will fallback to not ssl connection.

With 
```
PAPERLESS_DBSSLMODE=require
```
there will be following error on site after login: 
![20_09-32-43](https://github.com/paperless-ngx/paperless-ngx/assets/165814/e2852e7c-2eb6-4492-a9b4-57cbabcff4d6)

and in the docker logs 
```
django.db.utils.OperationalError: connection to server at "postgres.int.sikorski.cloud" (192.168.0.231), port 5432 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
```
this file doesn't exist. 

The previous version is working fine (1.15.x) with this setup.

### Steps to reproduce

- Setup papperless-ngx 1.16 with postgres ssl enforced
- Login 

### Webserver logs

```bash
django.db.utils.OperationalError: connection to server at "postgres.int.sikorski.cloud" (192.168.0.231), port 5432 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied
````
```


### Browser logs

_No response_

### Paperless-ngx version

1.16.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

_No response_

### Configuration changes

_No response_

### Other

_No response_

**Comment by SuperMasterPhoenix** [comment]
Had the same issue. If you are using docker/docker-compose you can add the following environment variable as a workaround to fix the issue:
PGSSLCERT=/tmp/postgresql.crt
With this variable my container came up again.

**Comment by stumpylog** [comment]
That file doensn't exist in 1.15 either.  Wouldn't you need to set these lines for SSL anyway?

https://github.com/paperless-ngx/paperless-ngx/blob/0fb553675bd0fa7710a448aa4fc75b563edef345/src/paperless/settings.py#L524-L526

**Comment by SuperMasterPhoenix** [comment]
That file doesn't exist, correct, but the error isn't about file not found but permission denied. So I guess the driver is trying to write whatever certificate at this location.
To be honest I didn't have the time to further look into this, I was just happy it worked again.
I found the workaround here: https://github.com/nginx/unit/issues/834#issuecomment-1410297997

**Comment by SuperMasterPhoenix** [comment]
I just tested docker tag :feature-fix-3633 in my environment (of course without the above mentioned env var...) and for me the issue is fixed. Great work, thanks!

**Comment by stumpylog** [comment]
Hopefully that last fix can get in and then a new release.  But for the moment, that branch is basically identical to what will be released.
