### ISSUE TITLE
[BUG] Missing German Translation in filtering Tags

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#365]
Migrated to NGX yesterday, great work you guys are putting on. Some minor bug came across my eye in the new tag-filtering. 

**Describe the bug**
The toggle-button for choosing "all" or "any" doesnt have german translations and the text is not visible.

using chrome Version 99.0.4844.51

![2022-03-15_06-25](https://user-images.githubusercontent.com/88422038/158313320-7910b67e-2248-44aa-9239-2de0ef43ec8b.png)

**To Reproduce**
Select two or more Tags and choose "any" or "all".

**Comment by shamoon** [comment]
Thanks for reporting. That visual bug is actually already fixed in the dev branch (so will be in next release). And I will fix the translation issue, thanks!

**Comment by sukisoft** [comment]
Alright, great. Sadly i dont really have the time to contribute myself. Maybe in the future.

**Comment by shamoon** [comment]
Yes, inevitably we will all have times of more or less availability, would love to have your help when you can.

**Comment by shamoon** [comment]
Closed by [02dc395](https://github.com/paperless-ngx/paperless-ngx/commit/02dc395880d2199e0560e7da6fdfaf5d27f84136)
