### ISSUE TITLE
pdf does not show an image

### ISSUE THREAD

**Issue by muecke6** [paperless-ngx/paperless-ngx#3664]
### Description

when i upload the attached file via ui it is displayed correctly in version 1.15.1. Not in version 1.16.0 and later
pdf file corrupt?
![1 15 1](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/1ac03500-5860-4967-bea7-3cc538f4dcaa)
![1 16 3](https://github.com/paperless-ngx/paperless-ngx/assets/123741690/5601970f-7503-495a-835d-89849bbc1792)
[00025513.pdf](https://github.com/paperless-ngx/paperless-ngx/files/11837621/00025513.pdf)

### Steps to reproduce

goto attached file
upload via UI

### Webserver logs

```bash
no error
```

### Paperless-ngx version

1.15.1  1.16.3

### Host OS

NAS Synology

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

no

**Comment by stumpylog** [comment]
Our software doesn't create the archive PDF, that's handled by OCRMyPdf.  Issues with the generation are better raised up with them.  It does seem like the current Ghostscript may not be compatible (yet) with OCRMyPdf and some PDFs.

**Comment by stumpylog** [comment]
When I upload the sample file, the log tells me this:
```log
[2023-06-22 11:45:22,981] [ERROR] [ocrmypdf._exec.ghostscript] GPL Ghostscript 10.0.0 (2022-09-21)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 2.
Page 1
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
Page 2
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
paperless-ngx-dev-webserver  |
The following warnings were encountered at least once while processing this file:
 recoverable image error
paperless-ngx-dev-webserver  |
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  This file had errors that were repaired or ignored.
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  The file was produced by:
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  >>>> Docentric Toolkit (6.1.37) <<<<
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  Please notify the author of the software that produced this
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  file that it does not conform to Adobe's published PDF
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  specification.
```

The message seems pretty clear, it's a PDF with errors, which the newer Ghostscript doesn't or can't handle.  We'll get newer versions as the base OS releases updates, but it's not something paperless or OCRMyPdf are likely to handle.

**Comment by muecke6** [comment]
Many thanks for the clarification and support. already thought that the file does not correspond to the standard


mit freundlichen Grüssen

Gabriel Wehle
________________________________
Von: Trenton H ***@***.***>
Gesendet: Donnerstag, 22. Juni 2023 20:48
An: paperless-ngx/paperless-ngx
Cc: muecke6; Author
Betreff: Re: [paperless-ngx/paperless-ngx] pdf does not show an image (Issue #3664) 

When I upload the sample file, the log tells me this:

[2023-06-22 11:45:22,981] [ERROR] [ocrmypdf._exec.ghostscript] GPL Ghostscript 10.0.0 (2022-09-21)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 2.
Page 1
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
Page 2
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
GPL Ghostscript 10.00.0: PDFA doesn't allow images with Interpolate true.
paperless-ngx-dev-webserver  |
The following warnings were encountered at least once while processing this file:
 recoverable image error
paperless-ngx-dev-webserver  |
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  This file had errors that were repaired or ignored.
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  The file was produced by:
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  >>>> Docentric Toolkit (6.1.37) <<<<
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  Please notify the author of the software that produced this
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  file that it does not conform to Adobe's published PDF
paperless-ngx-dev-webserver  |
[2023-06-22 11:45:22,982] [ERROR] [ocrmypdf._exec.ghostscript]  specification.

The message seems pretty clear, it's a PDF with errors, which the newer Ghostscript doesn't or can't handle. We'll get newer versions as the base OS releases updates, but it's not something paperless or OCRMyPdf are likely to handle.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/paperless-ngx/paperless-ngx/issues/3664#issuecomment-1603150389", "url": "https://github.com/paperless-ngx/paperless-ngx/issues/3664#issuecomment-1603150389", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
