### ISSUE TITLE
[BUG] sidebar buttons wrap when using tab sidebar with vertical scrollbar in MS Edge

### ISSUE THREAD

**Issue by tooomm** [paperless-ngx/paperless-ngx#3679]
### Description

Spotted this on the official demo.
I'm running full hd resolution on a small laptop screen on Windows 11 with recommended 1,5x scaling.

With Tab-Sidebar visible in Edge:
<img width="960" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/d25df1a8-ab20-4c05-a108-38f6a1af5c32">

With Tab-Sidebar collapsed:
<img width="960" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/fe636a68-2240-42c2-9380-ae4b2b5cd23f">

What sticks out, especially when looking at the second screenshot, `Documentation` and `Correspondents` are like the same size but in the first screen the later is not shown in one line with its icon.

### Steps to reproduce

1. Use Edge, enable Tab Sidebar
2. Go to https://demo.paperless-ngx.com/
3. Login
4. Pin/Collapse Sidebar

### Webserver logs

```bash
Official Demo
```

### Paperless-ngx version

1.16.3

### Host OS

Official Demo

### Installation method

Other (please describe above)

### Browser

Edge

### Configuration changes

Official Demo

**Comment by shamoon** [comment]
Can't reproduce this, using latest Edge. Maybe update yours. It doesn't really make sense anyway, toggling the edge sidebar should just render paperless in a more narrow window, which it seems to do just fine.

<img width="1303" alt="Screenshot 2023-06-24 at 5 52 08 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/78985545-f1a6-475e-8ade-7918b40c7e62">
<img width="1125" alt="Screenshot 2023-06-24 at 5 51 33 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/8c36ea56-692a-479e-a33e-90523c2f81fe">
<img width="1294" alt="Screenshot 2023-06-24 at 5 50 48 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/0e3ae006-f38b-49d6-b65e-0d5ea0451460">
<img width="1105" alt="Screenshot 2023-06-24 at 5 50 35 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/f6b630fc-5fe3-4f19-894a-ced203f6e45b">

**Comment by tooomm** [comment]
I'm running the newest Edge already
<img width="232" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/1b746638-d8ed-4a0f-b4e5-31c3641283ac">

When I checked today again, `Documentation` is now also no longer in the same line as the icon:
<img width="960" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/e20ddc5d-2981-4851-8dad-28c2cd1b3060">

Another observation:
When just shrinking the window, it works correctly and I can reduce the window width even further without seeing this issue:
<img width="960" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/8e2b0930-88c1-4771-bbcd-43b23d35e9ec">

Even with the tab sidebar pinned:
<img width="960" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/723fc236-abbd-4fcd-aeae-5a37beb3701e">

Switching the window to full screen will immediately result in the first picture again. Going back resolves it.
