### ISSUE TITLE
[BUG] Slim Sidebar Toggle and Dashboard/Documents menu buttons not working

### ISSUE THREAD

**Issue by tooomm** [paperless-ngx/paperless-ngx#3680]
### Description

Spotted this on the official demo.

The mentioned buttons can not be clicked, all other menu options do work.
Only way to see the big sidebar was for me to go to the settings.

Very strange is, that when I change the setting from slime to normal sidebar (or back), the buttons do work once. But only once.

### Steps to reproduce

1. Go to https://demo.paperless-ngx.com/
2. Login
3. Try to click one of the three mentioned buttons

### Webserver logs

```bash
Official Demo
```

### Paperless-ngx version

1.16.3

### Host OS

Official Demo

### Installation method

Other (please describe above)

### Browser

Edge

### Configuration changes

Official Demo

**Comment by shamoon** [comment]
This was just the demo, the alert message wasn't getting removed from the dom.
