### ISSUE TITLE
[BUG] Web interface hangs after changing between documents

### ISSUE THREAD

**Issue by kkrell2016** [paperless-ngx/paperless-ngx#3715]
### Description

When switching to the next document in the document view, first the icons of the buttons disappear and then the entire interface hangs.
In the background, all queries are pending. After a refresh it works again for 4-5 documents. 
It should not be the web service itself, because simultaneously working API queries work per script.

After a quick review, it seems that the suggestions keeping the CPU very busy. Is there a way to disable it?

### Steps to reproduce

Open the document view
open a document with the image on right side
Click the next button 3-4 times
Interface stops loading, gets very slow

### Webserver logs

```bash
No log here
```

### Paperless-ngx version

1.16.4

### Host OS

Synology OS

### Installation method

Docker - official image

**Comment by kkrell2016** [comment]
Okey got it.

Setting PAPERLESS_NUMBER_OF_SUGGESTED_DATES to 0 solves the problem. 
But i don't really know what I'm missing now.

**Comment by kkrell2016** [comment]
Okey got it.

Setting PAPERLESS_NUMBER_OF_SUGGESTED_DATES to 0 solves the problem.
But i don't really know what I'm missing now.

**Comment by DoinStuff35** [comment]
Same here.

**Paperless-ngx version**
1.16.5
**Host OS**
Pi OS Lite
**Installation method**
portainer/Docker - official image
**Browser**
Microsoft Edge
Version 114.0.1823.82

**Comment by shamoon** [comment]
The next release should handle this better, canceling the queries e.g. if navigating to another doc
