### ISSUE TITLE
[BUG] paperless_mail.tasks.process_mail_accounts always results in REVOKED state

### ISSUE THREAD

**Issue by pedropombeiro** [paperless-ngx/paperless-ngx#3739]
### Description

The periodic mail task executes. It always results in REVOKED task state, not sure why.

<img width="1088" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/138074/f37ba426-8ad7-4be2-a4d8-f7d61383d8a3">

<img width="1074" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/138074/b0b88786-c37d-4c22-96be-e81c1876f89a">

### Steps to reproduce

1. Set up a mail account with no encryption (I'm using protonmail-bridge):

    <img width="1134" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/138074/c45c5057-ba22-4bd1-a277-a5147d2e924c">

1. Set up a mail rule.

### Webserver logs

```bash
[2023-07-04 06:40:00,193] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[2810a24c-6b39-448e-bf64-63c0586be18f] received
[2023-07-04 06:40:00,194] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[2810a24c-6b39-448e-bf64-63c0586be18f]
```

Latest `mail.log` entry is from June 16 :thinking:
```


### Browser logs

_No response_

### Paperless-ngx version

1.16.5

### Host OS

QNAP 5.1

### Installation method

Docker - official image

### Browser

Edge

### Configuration changes

_No response_

### Other

_No response_

**Comment by shamoon** [comment]
Never seen this before, revoked seems to be celery equivalent for cancelling a task, which our code doesnt explicitly do anywhere.

The error says they're expired. Is the redis container running ok? Perhaps tasks are getting queued but never done so they just expire. You can try removing the redis data and celerybeat file in your data directory and let the containers re-create them on startup.

**Comment by pedropombeiro** [comment]
> The error says they're expired. Is the redis container running ok? Perhaps tasks are getting queued but never done so they just expire.

Thanks for the quick reply. Redis seems to be running OK. The tasks seem to be immediately expired though, there doesn't seem to be a wait period happening, as you can see below:

<img width="1370" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/138074/017d27f5-a9e9-49c3-8a45-43dabb05f04d">

>  You can try removing the redis data and celerybeat file in your data directory and let the containers re-create them on startup.

I did remove the redis data, by running `docker-compose down --volumes --remove-orphans`, since the redis container is not mapping any volume to the host.

I'm not sure what is the celerybeat file you're referring to. I only see a `celerybeat-schedule.db` file:

<img width="1037" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/138074/e60e278d-2798-4f4d-acb9-5e56781d7f17">

**Comment by shamoon** [comment]
Yea that one

**Comment by pedropombeiro** [comment]
Hmm, didn't seem to make a difference:

<img width="1466" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/138074/3dc08e0f-34e0-4f98-8d00-d69a5c56d4d4">

**Comment by pedropombeiro** [comment]
Interestingly, I downgraded to 1.15.1 and stopped seeing the revoking of tasks. The 1.16.0 release date seems to match the date where I stopped seeing new mails being processed (June 16th).

**Comment by pedropombeiro** [comment]
I also thought time zones might play a part in it, but my containers are all on the correct timezone (`Europe/Zurich`). Unless celery isn't using the time zone correctly.

**Comment by HomeBro** [comment]
I am experiencing the same problem.

After updating to version 1.16.5 the mail consumer doesn't work.

**Comment by stumpylog** [comment]
You can set the `TZ` environment variable as well, some containers will take it into account.  

You can also try bind mounting `/etc/localtime` to the same inside the container, ie `/etc/localtime:/etc/localtime:ro`

**Comment by pedropombeiro** [comment]
I already do that on all my containers, so I don’t understand why I’m coming across this.

**Comment by BiasF** [comment]
Same here, Mail Import stoped working since updating to latest Paperless NGX version. 
I already set TZ and PAPERLESS_TIME_ZONE: Europe/Berlin in my docker compose file but nothing helped.

But the task state is not REVOKED, there are just no log entries since update.

**Comment by psyciknz** [comment]
Ay update to this issue?    I think I'm suffering from it as well.  The only way I can get emails ingested is manually run the email_fetcher

**Comment by stumpylog** [comment]
You can look through celery issues and see if it's something already reported there: https://github.com/celery/celery/issues

**Comment by psyciknz** [comment]
> You can look through celery issues and see if it's something already reported there: https://github.com/celery/celery/issues

That doesn't give a lot to go on.   What is reported?  A revoked task? wouldn't I need the context of the type of task paperless it trying to create?  Or some pointers in getting celery logging to show more than:
```
[2023-07-28 08:10:00,101] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[9cd15263-7970-4c07-9710-779161ba3ae4] received
[2023-07-28 08:10:00,102] [INFO] [celery.worker.request] Discarding revoked task: paperless_mail.tasks.process_mail_accounts[9cd15263-7970-4c07-9710-779161ba3ae4]
[2023-07-28 08:15:00,199] [DEBUG] [celery.beat] beat: Synchronizing schedule...
[2023-07-28 08:15:00,208] [DEBUG] [celery.beat] beat: Waking up in 5.00 minutes.
```

**Comment by Marco98** [comment]
I also have the exact same issue, that no task will run and will be revoked with the reason "expired"
Imho i think it might be a localtime to utc conversion issue.
The task created UTC DateTime 4:30 pm / 16:30 is being displayed in django when in fact the real UTC time is 12:30 and my local time 14:30. So somehow the time difference has been inverted and doubled?

The last working containerimage ships with celery 5.2.X. With 5.3.X it seems to stop working. I'm not familiar with celery but it seems they changed their timezone library with 5.3. 

The timezone in the container as well as the host is set correctly. I also did reset `celerybeat-schedule.db` and the redis state.
```shell
root@host:~# ls -la /etc/localtime
lrwxrwxrwx 1 root root 33 Mai  8 09:52 /etc/localtime -> /usr/share/zoneinfo/Europe/Berlin

root@host:~# podman exec paperless-app ls -l /etc/localtime
lrwxrwxrwx 1 root root 33 Aug  5 15:31 /etc/localtime -> /usr/share/zoneinfo/Europe/Berlin

root@host:~# podman exec paperless-app env | grep -i europe
TZ=Europe/Berlin
PAPERLESS_TIME_ZONE=Europe/Berlin
```

Sadly after a long troubleshooting session i did not found the root cause nor a workaround.

**Comment by shamoon** [comment]
That is indeed suspicious, but again, I would try asking the question at the celery repo, there isn't much to suggest a fix would be in paperless

**Comment by psyciknz** [comment]
> That is indeed suspicious, but again, I would try asking the question at the celery repo, there isn't much to suggest a fix would be in paperless

The problem I have which this statement, is celery is not something I have deployed.  It has been bundled as part of paperless.  So we do not (as general users) have any idea how it is used and configured.

**Comment by pedropombeiro** [comment]
> That is indeed suspicious, but again, I would try asking the question at the celery repo, there isn't much to suggest a fix would be in paperless

Is downgrading celery an option?

**Comment by ridiekel** [comment]
I'm having the same issue. Downgrading to 1.15 seems to "work". So I would guess the problem got introduced with 1.16 and above.
I'm happy to help debugging, though I don't know where I should start

**Comment by pedropombeiro** [comment]
I just decided to stop using the mail processor, if no support is going to be given, or testing performed, when dependencies are brought in.

**Comment by shamoon** [comment]
> if no support is going to be given, or testing performed, when dependencies are brought in.

Please reality check yourself. Every single comment in every single issue and discussion in this repository and the chat is "support". Every one of the 793 python and 623 frontend tests are all "testing performed". All of this is done by volunteers with families and jobs and things.

Of the thousands of Paperless-ngx users only a few are experiencing this and no one else can reproduce it, so it does not seem to be widespread. I opened a discussion at the celery repo, it has precisely 0 replies to date.

**Comment by pedropombeiro** [comment]
@shamoon I'm totally aware and understanding of the fact that this project is maintained by people with families and jobs. That is why instead of complaining, I decided to stop using it. It just wasn't that important to my workflow.

That wasn't made out of spite, although I understand that it may have come across that way. It was just a realization that if we're going to keep the upgraded dependency despite the fact that it broke part of the workflow, then I have to come to the realization that the workflow is not as common as I thought, and therefore I have to re-evaluate how important it is to me.

**Comment by psyciknz** [comment]
> @shamoon I'm totally aware and understanding of the fact that this project is maintained by people with families and jobs. That is why instead of complaining, I decided to stop using it. It just wasn't that important to my workflow.
> 
> That wasn't made out of spite, although I understand that it may have come across that way. It was just a realization that if we're going to keep the upgraded dependency despite the fact that it broke part of the workflow, then I have to come to the realization that the workflow is not as common as I thought, and therefore I have to re-evaluate how important it is to me.

Simple solution is to run a cron on mail_fetcher...
docker exec paperless mail_fetcher

Does mean the internal stuff is still quite noisy and making tasks that are instantly revoked.  But this keeps your workflow going.

**Comment by shamoon** [comment]
I appreciate the reply, and yes I realize context can be lost online so perhaps I took your comment differently than intended.

In sum: we do our best to make the software as reliable and useful as possible, within the constraints of free open-source work. We will always accept PRs for issues and we do regularly merge upstream changes so hopefully, with time, this issue can be elucidated / resolved.

**Comment by pedropombeiro** [comment]
By the way, I definitely am grateful for you guys picking up where paperless-ng left off, and very much enjoy where you've taken it so far 💪

**Comment by ridiekel** [comment]
@psyciknz Thanks for providing that workaround. I have created a helper docker container with cron that now executes that docker command. Seems to work.
Happy that my workflow is running again on the latest version.

The offer still stands, if I can help debug by adding or enabling extra logging, always happy to do that.

**Comment by mmathau** [comment]
I had the same thing happening but for both the mail task and the document classifier training.
The issue was using a bind mount `/etc/localtime:/etc/localtime:ro` for the paperless container since the container did not respect the actual timezone and defaulted back to UTC.
```
root@paperless:/usr/src/paperless/src# ls -la /etc/localtime 
lrwxrwxrwx 1 root root 27 Aug 14 02:00 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
```

After removing the bindmount and recreating the containers the mail task and the document classifier started reporting a `SUCCESS` state again instead of `REVOKED`.

**Comment by psyciknz** [comment]
Oh good find.  So you did this on the paperless and redis broker containers?

**Comment by psyciknz** [comment]
```
[2023-09-19 07:11:15,146] [INFO] [celery.apps.worker] celery@ded8b5055668 ready.
[2023-09-19 07:11:15,149] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[d77a6504-a14a-4f1c-bf97-cdd8aa902c86] received
[2023-09-19 07:11:15,151] [INFO] [celery.worker.strategy] Task documents.tasks.train_classifier[20cb06dd-034b-452c-9501-3090a3506076] received
[2023-09-19 07:11:15,153] [INFO] [celery.worker.strategy] Task documents.tasks.index_optimize[fa530003-a99b-479e-b544-43b470a3c4bb] received
[2023-09-19 07:11:22,356] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[d77a6504-a14a-4f1c-bf97-cdd8aa902c86] succeeded in 7.189076526963618s: 'No new documents were added.'
```

Instantly starts processing.   I think this note should go in the docs potentially?

**Comment by ridiekel** [comment]
@mmathau Nice find, after removing the bind mount, everything started working again, without needing a seperate cron job to run the mail updater.

Thanks for the provided fix!

**Comment by mmathau** [comment]
Im still trying to figure out why this is happening.
@psyciknz I only removed the bindmount from the paperless container, not from the broker (redis) or the database container. 

Without looking at how the dockerimage is getting built I assume paperless overwrites the bindmounted localtime if the env var `PAPERLESS_TIME_ZONE` is set

**Comment by andreas-0001** [comment]
> I had the same thing happening but for both the mail task and the document classifier training. The issue was using a bind mount `/etc/localtime:/etc/localtime:ro` for the paperless container since the container did not respect the actual timezone and defaulted back to UTC.
> 
> ```
> mmath@dockerhost:~$ ls -la /etc/localtime
> lrwxrwxrwx 1 root root 33 May  2 13:48 /etc/localtime -> /usr/share/zoneinfo/Europe/Vienna
> 
> root@paperless:/usr/src/paperless/src# ls -la /etc/localtime 
> lrwxrwxrwx 1 root root 27 Aug 14 02:00 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
> ```
> 
> After removing the bindmount and recreating the containers the mail task and the document classifier started reporting a `SUCCESS` state again instead of `REVOKED`.

I had the same issue too (immediately revoked email processing). 
By removing the bind mounts in the portainer stack config for the webserver (image: ghcr.io/paperless-ngx/paperless-ngx:latest) the email processing restarted to work again.
 `   # - /etc/localtime:/etc/localtime:ro `
 `   # - /etc/timezone:/etc/timezone:ro `
To map the time zone, I use now the environment variable `TZ: Europe/Berlin`
All other containers from the paperless docker stack are still using bind mounts to map the time zone.
 Thanks for this find !

**Comment by G0bi83** [comment]
i have maybe the same problem, but I don´t know how to solve it. My paperless-ngx ist installed on bare-metal (proxmox lxc container) and the mail-fetcher stopped working. Any idea?

**Comment by HomeBro** [comment]
@G0bi83 I have the same setup as you have. Have you tried to stop all paperless services and delete the file **celerybeat-schedule.db.db** - reboot afterwards - just in case.

**Comment by G0bi83** [comment]
> @G0bi83 I have the same setup as you have. Have you tried to stop all paperless services and delete the file **celerybeat-schedule.db.db** - reboot afterwards - just in case.

Thanks for the tip, I already deleted the celerybeat-schedule.db.db everal times. But I found a solution. Barcode recognizing was acitvated for page separation. One doc had to much barcodes and the barcode enginge consumed to much ram and exited the celerybeat with an error. After disabling of barcode recognizion everything went fine.
