### ISSUE TITLE
[BUG] Z-index problems with Firefox

### ISSUE THREAD

**Issue by alexrtou** [paperless-ngx/paperless-ngx#3754]
### Description

Hello,
I am a new user of your great software. It will be my alternative to papermerge !
But I have a problem with Firefox 114.0.1 (64 bits) on linux.
Sometime le content comes over the header... I can't see this issue on Chromium.
for example :

![Capture d’écran du 2023-07-06 09-18-56](https://github.com/paperless-ngx/paperless-ngx/assets/11272280/568fe934-bed8-4593-bded-7acf390bb21a)

### Steps to reproduce

- use FF
- browse documents
- switch list view to thumbnails (for example)
- scroll the content

### Webserver logs

```bash
not needed
```

### Paperless-ngx version

1.16.5

### Host OS

manjaro

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
I cant reproduce this with FF macOS 114 or Windows 114 or linux 115

<img width="1728" alt="Screenshot 2023-07-06 at 6 24 01 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/835fc574-daa9-4c32-a304-b6af39bbf88e">
<img width="1628" alt="Screenshot 2023-07-06 at 6 29 43 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/10237aca-a083-45b0-bbed-7632f57d3a69">
<img width="1520" alt="Screenshot 2023-07-06 at 6 32 03 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/be981a2d-57ff-48dd-8bb6-43116a2fd754">
