### ISSUE TITLE
[BUG] GPG errors when running docker image on ARM

### ISSUE THREAD

**Issue by denilsonsa** [paperless-ngx/paperless-ngx#3856]
### Description

The latest version runs fine on my x86 machine, but it fails to start when I try running it on my Raspberry Pi 4, complaining about GPG keys while downloading Debian packages.

### Steps to reproduce

1. Find an ARM machine, and an intel-x86-64 machine. The same steps fail on the arm machine, but work on the x86.
2. Go to https://github.com/paperless-ngx/paperless-ngx/tree/dev/docker/compose
3. Download [docker-compose.env](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.env) and [docker-compose.sqlite.yml](https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.sqlite.yml).
4. Update the `.env` file:
    * Set `USERMAP_UID` and `USERMAP_GID` as needed.
    * Set `PAPERLESS_OCR_LANGUAGES` to something that would force downloading more languages (e.g. `eng nld`).
5. Run `docker-compose up`.
6. After a while, the x86 machine manages to run paperless-ngx just fine. However, the arm machine fails, the `webserver` keeps restarting with the following error:

### Webserver logs

```
webserver_1  | Paperless-ngx docker container starting...
webserver_1  | Installing languages...
webserver_1  | Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
webserver_1  | Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
webserver_1  | Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
webserver_1  | Err:1 http://deb.debian.org/debian bookworm InRelease
webserver_1  |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
webserver_1  | Err:2 http://deb.debian.org/debian bookworm-updates InRelease
webserver_1  |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
webserver_1  | Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
webserver_1  |   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
webserver_1  | Reading package lists...
webserver_1  | W: GPG error: http://deb.debian.org/debian bookworm InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131 NO_PUBKEY F8D2585B8783D481
webserver_1  | E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
webserver_1  | W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
webserver_1  | E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
webserver_1  | W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 54404762BBB6E853 NO_PUBKEY BDE6D2B9216EC7A8
webserver_1  | E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
```

### Paperless-ngx version

1.16.5

### Host OS

Raspberry Pi 4 (aarch64)

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
See https://github.com/docker-library/python/issues/837

**Comment by shamoon** [comment]
Please see above, there's no reason to track here

**Comment by denilsonsa** [comment]
This sounds like the cause of the issue: https://github.com/docker-library/python/issues/837#issuecomment-1599640563

Thanks for pointing to that other bug report.
