### ISSUE TITLE
[BUG] Timezone seems not to be correct in database, but everywhere else

### ISSUE THREAD

**Issue by FayeDE** [paperless-ngx/paperless-ngx#3897]
### Description

It seems like the timezone is not reflected in the database. The correct time is being used in the frontend, and in django admin in task results. This might be intended behavior, but I wanted to make this issue to be sure.

Europe/Berlin is set and correctly used by the docker container. (echo $TZ, echo $PAPERLESS_TIME_ZONE)

Screenshots (Reality: 10:35 import, 10:52 now check)
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/11154004/bbea42b4-22a1-41d0-8df9-da21882c86f7)
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/11154004/50d93bce-8ef1-4ffe-814a-656ec744d003)

### Steps to reproduce

No known steps to reproduce

### Webserver logs

```bash
No relatable logs
```

### Paperless-ngx version

1.16.5

### Host OS

Unraid, Docker

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
The database always stores datetime fields in UTC, which is converted to local time as needed.  Europe/Berlin is UTC+2, so the values make sense.
