### ISSUE TITLE
[BUG] I killed the demo?

### ISSUE THREAD

**Issue by yaomtc** [paperless-ngx/paperless-ngx#3901]
### Description

I got an error 524 every time I tried to upload an image, which then showed up as `Error -3 connecting to broker:6379. -3.`

Then the demo stopped loading entirely.

### Steps to reproduce

1. Go to demo
2. Upload image
3. Try again
4. Reload page after a while

### Webserver logs

```bash
Logs page was blank.
```

### Paperless-ngx version

Whatever version you're running for the demo

### Host OS

Unknown

### Installation method

Other (please describe above)

### Browser

Firefox

**Comment by stumpylog** [comment]
It will reset after some time and smooth out.  It's only a free tier, so not much power behind it.

**Comment by yaomtc** [comment]
Glad I didn't kill it. Seems it's working better now, uploads aren't failing at the moment. Thanks! Just want to get a feel for the tool as I don't have my own web server to test on atm
