### ISSUE TITLE
[BUG] Deprecation warning for task_allow_error_cb_on_chord_header=False

### ISSUE THREAD

**Issue by remmahad** [paperless-ngx/paperless-ngx#3919]
### Description

There is currently a deprecation warning raised after consuming an attachment via the mail functionionality:
`[WARNING] [py.warnings] /usr/local/lib/python3.9/site-packages/celery/canvas.py:2286: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.`

I'm not sure if this error is actually about paperless-ngx or the celery integration.

### Steps to reproduce

Import an attachment via a mail rule

### Webserver logs

```bash
webserver_1  | [2023-08-02 15:10:02,409] [INFO] [paperless_mail] Rule Paperless Account.CatchALL_SCAN: Consuming attachment FILENAME.pdf from mail SUBJECT from MAILADRESS
webserver_1  | [2023-08-02 15:10:02,414] [WARNING] [py.warnings] /usr/local/lib/python3.9/site-packages/celery/canvas.py:2286: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.
webserver_1  | Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final decision regarding how errbacks should behave when used with chords.
webserver_1  |   warnings.warn(
```

### Paperless-ngx version

1.16.5

### Host OS

Raspebrry Pi 4 aarch64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
We never actually set that, and it appears to be under discussion still anyway: celery/celery/discussions/8318

**Comment by shamoon** [comment]
Yea, also its a warning
