### ISSUE TITLE
[BUG] Choosing wrong OCR language code errors out and skips user creation

### ISSUE THREAD

**Issue by Znuff** [paperless-ngx/paperless-ngx#3920]
### Description

While using the auto-install script, I mistakenly entered the wrong OCR language code, instead of `ron` I used `rom`. 

This caused the following error:

```
Running Django checks
SystemCheckError: System check identified some issues:

ERRORS:
?: The selected ocr language rom is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

System check identified 1 issue (0 silenced).
```

Unfortunately, this also seems to skip the user creation (understandably)

With my familiarity of Docker, I just edited the `.env` file and I swapped to the correct language code. After that, I proceeded to restart the containers.

Once attempting to log on, I was met with a wrong user/pass message.

Entering the docker container and running `manage.py shell`, I have checked to see if the user exists:

```
>>> from django.contrib.auth.models import User
>>> User.objects.all()
<QuerySet [<User: consumer>, <User: AnonymousUser>]>
```

This has revealed that the user was not created during the initial setup, likely to the Django check failing.

Testing to see if my intuition was correct, I have cleared everything and re-run the setup, while making sure the language code is correct.

It seems the superuser only gets created *ONLY IF* all checks have passed:

```
Running Django checks
System check identified no issues (0 silenced).
Search index out of date. Updating...
Executing management command createsuperuser --noinput --username paper --email paper@localhost
Superuser created successfully.
```

This is obviously an user error on my part, but can be confusing to some people.

### Steps to reproduce

1. Run the auto-setup script
2. Enter the wrong language code for the OCR section
3. Edit the generated `.env` file manually, fix the language code
4. Attempt to log on with the user you have selected during the setup process
5. Fail.

### Webserver logs

```bash
Running Django checks
SystemCheckError: System check identified some issues:

ERRORS:
?: The selected ocr language rom is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.

System check identified 1 issue (0 silenced).
```

### Paperless-ngx version

1.16.5

### Host OS

Ubuntu 22.04, x86_64

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Yea, Im not sure what the 'bug' is here and theres not really a way to warn the user they did this before it happens

**Comment by Znuff** [comment]
I mean, it does... but it also starts the containers.

I think the UX would be better if:

- either _attempt_ to create the superuser, allowing the user to fix their mistake (in this case)
- **critically fail** and do not attempt to continue/start the containers

Starting the containers, in spite of the Errors, implies that they (the error(s)) can be ignored or fixed after.

**Comment by stumpylog** [comment]
We can't control the other containers starting up, only the webserver's initialization.  Which exits with a clear indication of error and exactly what environment needs to be fixed.  The other containers are start by `docker compose` because they are `depends_on` of the webserver.  There's no control over that, and they are required for the webserver.

**Comment by Znuff** [comment]
I mean this would literally be a case of `if ( $critical_error ) { exit the script }`.
