### ISSUE TITLE
[BUG] manage correspondents page errors with very old dates

### ISSUE THREAD

**Issue by pop-ch** [paperless-ngx/paperless-ngx#3944]
### Description

Calling the correspondent editor from the first page of the correspondents list works perfectly. Calling the same editor from the second page opens an empty form which does not appear to work at all.

As I don't have more correspondents at the moment, I don't know if the problem is bound to all pages but the first, or the last of several pages.

You can use the Django admin panel for a workaround.

### Steps to reproduce

This is page two of my correspondents list. Note the empty lines at the end of the list.

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/68431606/63827295-2062-4517-9e67-efff85651110)

Clicking on any of the 'Bearbeiten' links ('edit') produces this dialog box:

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/68431606/1b34d14d-3e7f-4c15-812e-3f23c7657169)

Doing the same on the first page of the list works fine.

### Webserver logs

```bash
none
```

### Paperless-ngx version

Paperless-ngx 1.17.0

### Host OS

Ubuntu 22.04.2 LTS

### Installation method

Docker - official image

### Browser

Firefox Browser 116.0.1 (64-Bit)

### Other

Another instance of paperless-ngx with far more correspondents does not show this behaviour. However, the other instance was migrated from paperless-ng. This instance is newly created using the instructions on the -ngx website.

**Comment by shamoon** [comment]
I cannot reproduce this and things here haven't changed lately. Based on the screenshot I'd bet there is in fact browser console output that might be helpful, please provide it.

<img width="1488" alt="Screenshot 2023-08-07 at 6 51 31 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/ec43432a-151b-4167-a15a-029d71d1901c">

**Comment by pop-ch** [comment]
This is what the console shows on entering the correspondents list:

18:00:57.503
Object { https: false, httpsAutoUpgrade: false, privacyScore: 2, entitiesBlocked: {}, entitiesNotBlocked: {}, scores: null }
[background.js:27693:25](moz-extension://a7144d3e-b01b-41e9-a836-dc72906189ea/public/js/background.js)
18:00:57.568 HTTPS: Service cache - host is not upgradable minix [background.js:27834:21](moz-extension://a7144d3e-b01b-41e9-a836-dc72906189ea/public/js/background.js)

Changing to the second page of the list shows this once:
18:05:49.730 HTTPS: Service cache - host is not upgradable minix [background.js:27834:21](moz-extension://a7144d3e-b01b-41e9-a836-dc72906189ea/public/js/background.js)

followed by what appears to be several identical copies of this:

18:05:51.239 ERROR Error: NG02100
    nt http://minix:8000/static/frontend/de-DE/main.js:3
    os http://minix:8000/static/frontend/de-DE/main.js:3
    transform http://minix:8000/static/frontend/de-DE/main.js:3
    transform http://minix:8000/static/frontend/de-DE/main.js:3
    valueFn http://minix:8000/static/frontend/de-DE/main.js:3
    Yle http://minix:8000/static/frontend/de-DE/main.js:3
    runInContext http://minix:8000/static/frontend/de-DE/main.js:3
    lM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    MM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    MM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    MM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    Z3 http://minix:8000/static/frontend/de-DE/main.js:3
    yM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    MM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    Z3 http://minix:8000/static/frontend/de-DE/main.js:3
    yM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    MM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    MM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    Z3 http://minix:8000/static/frontend/de-DE/main.js:3
    yM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    NM http://minix:8000/static/frontend/de-DE/main.js:3
    Z3 http://minix:8000/static/frontend/de-DE/main.js:3
    yM http://minix:8000/static/frontend/de-DE/main.js:3
    bM http://minix:8000/static/frontend/de-DE/main.js:3
    Ph http://minix:8000/static/frontend/de-DE/main.js:3
    detectChanges http://minix:8000/static/frontend/de-DE/main.js:3
    tick http://minix:8000/static/frontend/de-DE/main.js:3
    next http://minix:8000/static/frontend/de-DE/main.js:3
    invoke http://minix:8000/static/frontend/de-DE/polyfills.js:1
    onInvoke http://minix:8000/static/frontend/de-DE/main.js:3
    invoke http://minix:8000/static/frontend/de-DE/polyfills.js:1
    run http://minix:8000/static/frontend/de-DE/polyfills.js:1
    run http://minix:8000/static/frontend/de-DE/main.js:3
    next http://minix:8000/static/frontend/de-DE/main.js:3
    next http://minix:8000/static/frontend/de-DE/main.js:3
    _next http://minix:8000/static/frontend/de-DE/main.js:3
    next http://minix:8000/static/frontend/de-DE/main.js:3
    next http://minix:8000/static/frontend/de-DE/main.js:3
    V http://minix:8000/static/frontend/de-DE/main.js:3
    next http://minix:8000/static/frontend/de-DE/main.js:3
    emit http://minix:8000/static/frontend/de-DE/main.js:3
    xS http://minix:8000/static/frontend/de-DE/main.js:3
    rO http://minix:8000/static/frontend/de-DE/main.js:3
    onInvokeTask http://minix:8000/static/frontend/de-DE/main.js:3
    invokeTask http://minix:8000/static/frontend/de-DE/polyfills.js:1
    runTask http://minix:8000/static/frontend/de-DE/polyfills.js:1
    invokeTask http://minix:8000/static/frontend/de-DE/polyfills.js:1
    Z http://minix:8000/static/frontend/de-DE/polyfills.js:1
    N http://minix:8000/static/frontend/de-DE/polyfills.js:1
    F http://minix:8000/static/frontend/de-DE/polyfills.js:1

**Comment by pop-ch** [comment]
The issue occurs on two different clients, set to two different languages (German and English), in three different browsers: Firefox, Opera, Web (Gnome browser). However, as I said before, it occurs on one instance of paperless-ngx only. The other instance on another host does not show this issue.

**Comment by shamoon** [comment]
If you look in the network tab, can you copy and paste the results of the /api/correspondents/ endpoint? (You can redact any names or anything you don't want to share)

I suspect one of your correspondents is messed up but not sure how

**Comment by pop-ch** [comment]
I'm sorry, I don't understand. Which is the network tab and where do I find it? I'm just a plain user and quite new to paperless.

**Comment by pop-ch** [comment]
Anyway, I pointed to browser at: http://minix:8000/api/correspondents/

and received this. The data is not particularly sensitive as this is going to be a public archive, anyway, and most people mentioned here have been dead for some time:



HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 43,
    "next": "http://minix:8000/api/correspondents/?page=2",
    "previous": null,
    "all": [
        46,
        12,
        32,
        9,
        36,
        20,
        26,
        22,
        4,
        17,
        10,
        11,
        21,
        29,
        33,
        41,
        14,
        16,
        43,
        37,
        44,
        28,
        25,
        7,
        13,
        42,
        19,
        31,
        30,
        38,
        6,
        45,
        24,
        15,
        35,
        27,
        23,
        40,
        34,
        39,
        8,
        5,
        18
    ],
    "results": [
        {
            "id": 46,
            "slug": "agm",
            "name": "AGM",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 2,
            "last_correspondence": "2023-08-01T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 12,
            "slug": "bandli-hans",
            "name": "Bandli, Hans",
            "match": "\"Hans Bandli\" \"H. Bandli\"",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 113,
            "last_correspondence": "2023-08-03T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 32,
            "slug": "benz-samuel",
            "name": "Benz, Samuel",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1990-01-12T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 9,
            "slug": "bischoff-karl",
            "name": "Bischoff, Karl",
            "match": "bi \"Karl Bischoff\"",
            "matching_algorithm": 1,
            "is_insensitive": false,
            "document_count": 256,
            "last_correspondence": "2023-08-04T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 36,
            "slug": "blumer-ramstein-myrtha",
            "name": "Blumer-Ramstein, Myrtha",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "2023-07-22T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 20,
            "slug": "bruckner-daniel",
            "name": "Bruckner, Daniel",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 2,
            "last_correspondence": "1981-07-28T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 26,
            "slug": "bruckner-wilhelm",
            "name": "Bruckner, Wilhelm",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1950-01-01T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 22,
            "slug": "degen-wilhelm",
            "name": "Degen, Wilhelm",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1945-02-11T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 4,
            "slug": "eglinjakob",
            "name": "Eglin,Jakob",
            "match": "\"J. Eglin\" \"Jakob Eglin\"",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 143,
            "last_correspondence": "2023-08-04T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 17,
            "slug": "faes-armin",
            "name": "Faes, Armin",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1983-01-22T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 10,
            "slug": "fischli-albert",
            "name": "Fischli, Albert",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 8,
            "last_correspondence": "2023-07-21T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 11,
            "slug": "fischli-ernst",
            "name": "Fischli, Ernst",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1982-11-05T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 21,
            "slug": "frey-martin",
            "name": "Frey, Martin",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1975-03-25T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 29,
            "slug": "gantner-hildegard",
            "name": "Gantner, Hildegard",
            "match": "Hildegard Gantner",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 56,
            "last_correspondence": "2023-07-22T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 33,
            "slug": "gysin-paul",
            "name": "Gysin, Paul",
            "match": "\"-y-\" \"Paul Gysin\" \"- y -\"",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 22,
            "last_correspondence": "2023-08-04T00:00:00+02:00",
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 41,
            "slug": "hamel-hanspeter",
            "name": "Hamel, Hanspeter",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 14,
            "last_correspondence": "2021-06-10T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 14,
            "slug": "haring-hans",
            "name": "Häring, Hans",
            "match": "\"Hans Häring\"",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 43,
            "last_correspondence": "2023-07-22T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 16,
            "slug": "hausammann-georg",
            "name": "Hausammann, Georg",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "2023-07-21T00:00:00+02:00",
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 43,
            "slug": "herzog-philipp",
            "name": "Herzog, Philipp",
            "match": "\"Philipp Herzog\"",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 0,
            "last_correspondence": null,
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 37,
            "slug": "hug-werner",
            "name": "Hug, Werner",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1996-02-01T00:00:00+01:00",
            "owner": 3,
            "user_can_change": true
        },
        {
            "id": 44,
            "slug": "iselin-johannes",
            "name": "Iselin, Johannes",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1903-12-01T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 28,
            "slug": "jourdan-max",
            "name": "Jourdan, Max",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "2003-10-01T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 25,
            "slug": "kam",
            "name": "kam.",
            "match": "kam.",
            "matching_algorithm": 1,
            "is_insensitive": true,
            "document_count": 2,
            "last_correspondence": "1954-07-01T00:00:00+01:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 7,
            "slug": "kist-hermann",
            "name": "Kist, Hermann",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "2018-09-02T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        },
        {
            "id": 13,
            "slug": "leuenberger-martin",
            "name": "Leuenberger, Martin",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "document_count": 7,
            "last_correspondence": "2023-07-22T00:00:00+02:00",
            "owner": null,
            "user_can_change": true
        }
    ]
}

**Comment by pop-ch** [comment]
Got it. It's this entry:
```
{
            "id": 27,
            "slug": "schneider-j-j",
            "name": "Schneider, J. J.",
            "match": "",
            "matching_algorithm": 0,
            "is_insensitive": true,
            "document_count": 1,
            "last_correspondence": "1833-01-01T00:00:00+00:34:08",
            "owner": null,
            "user_can_change": true
        },
```

Changing the document date to 1933 resolves the issue. Changing the date back to 1833 makes the issue appear again.

Thanks so much for the hint. 

Should the title of the issue be changed to reflect the diagnostic? And what would be the earliest date acceptable to paperless?

**Comment by pop-ch** [comment]
I am now running paperless-ngx 1.17.1 and the issue persists.
To reproduce:
create a document with a correspondent who has only this document.
set the document creation date to 31-05-1833 (eighteen thirty-three) or before and the issue will show.
set the document creation date to 01-06-1833 or later and the issue will not show.
The issue will be shown as:
correspondents list stops with the offending correspondent. Lines following are shown but empty. Editing the correspondent will show an empty dialog popup.

How do I re-open an issue?

**Comment by shamoon** [comment]
<img width="1422" alt="Screenshot 2023-08-17 at 1 59 47 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/3be1e491-d6c7-4a17-bf55-5a5685092519">

**Comment by pop-ch** [comment]
Thanks for looking into this again. Still, I just tested this with some more user agents. I can reproduce it even in Windows 10 with both Opera and Edge. Now that I know how to provoke the error, I can provoke it in both paperless instances I currently run.
It's just conceivable that it's a localization thing, but not so probable. What locale is your client set to?

**Comment by shamoon** [comment]
Hmm, I wouldn't imagine that matters since the date itself is being passed as an iso8601 date. But Im using en-US.

Again, browser error console?
