### ISSUE TITLE
Bare Metal install impossible

### ISSUE THREAD

**Issue by MortRainey** [paperless-ngx/paperless-ngx#3950]
### Description

If you try to install bare matel it fails. Docker Image is updated to bockworm. But bockworm uses Python 3.11, the docker Image 3.9. 

The instructions in the dockerfile are using pipenv. The Dokumentation for bare Metal install not. 

On debian 11 pip3 dosen‘t find mysqlclient 2.2.0. i dont know why. Its 2.1.* so installing dependencies of requirements.txt fails. 

### Steps to reproduce

Folow the dokumentation for bare Mantel install. 

### Webserver logs

```bash
No webserver Logs because it does Not come to use it.
```

### Paperless-ngx version

1.17.0

### Host OS

Debian 11 and 12

### Installation method

Bare metal

**Comment by stumpylog** [comment]
This sounds like a problem with your system.  But without any sort of log, it's impossible to even begin assisting.

**Comment by stumpylog** [comment]
Also Python 3.11 is not (yet) supported.  If you want to utilize that with a bare metal install, and not use something like `pyenv`, you will need to do some work.

**Comment by MortRainey** [comment]
Are you kidding me? 

1. The documentation for bare metal install isn't up to date. 
2. If you try to install on bockworm you can't use python 3.9 like on a rocker image. 
What about that is a problem with my system?

**Comment by MortRainey** [comment]
> mysqlclient most certainly provides a 2.2.0: https://pypi.org/project/mysqlclient/#history

That's a good point. I don't know why pip doesn't find this version.

**Comment by LifeLifeLP** [comment]
As a workaround: After the it fails at mysqlclient you can remove it from requirements.txt and execute the command again. The install will finish and can be used with mysql-db.

**Comment by stumpylog** [comment]
Again, without a log from pip, there's little to do.  I don't believe the documentation says Python 3.11 is supported anywhere. If it does, that's not correct.

**Comment by MortRainey** [comment]
Debian 11 

`root@paperless ~ # pip3 install mysqlclient
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.9/dist-packages (2.1.1)
DEPRECATION: gpg 1.14.0-unknown has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of gpg or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

**Comment by stumpylog** [comment]
You missing `--upgrade`

**Comment by MortRainey** [comment]
> You are missing `--upgrade`

I tryed "pip3 install mysqlclient==2.2.0 and it couldn't find it. Upgrade did it. 

Do you know why pip3 install -r requirements.txt did not install it probably? 

After upgrading mysqlclient manually it run without fails. It's a miracle to me.

**Comment by web-sto** [comment]
I've got the same issue, but the suggested solution did not help.
I had to issue 'sudo apt install pkg-config' before running 'sudo pip3 install --upgrade mysqlclient==2.2.0'

Afterwards updating requirements ran as usually.
