### ISSUE TITLE
[Vote] Repo Name Change to "paperless-ngx"

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#4]
It's been suggested to change this repo's name to **paperless-ngx** (same as the organization) to prevent confusion with Jonas' upstream if/when people come to migrate.

### Please vote :+1: if you like this idea, :-1: if you do not.

I'm open to any relevant suggestions or comments. I'll leave this open for a day or two before starting #3

**Comment by kpj** [comment]
Do we only plan to rename the GitHub repository or also the actual project (i.e., name in the readme, `conf.py`, GitHub Actions workflows, etc)?

**Comment by qcasey** [comment]
For now just the repo, unless there is a good reason to change anything else.

**Comment by yschroeder** [comment]
I would go through the places where the project name is mentioned and add the x to it. Only actually code (variable names) could remain unchanged for backwards compatibility.

**Comment by gador** [comment]
> I would go through the places where the project name is mentioned and add the x to it. Only actually code (variable names) could remain unchanged for backwards compatibility. 

I agree. Otherwise people will get confused..
