### ISSUE TITLE
[BUG] ADMIN_{USER_PASSWORD} set but ... doesn't work

### ISSUE THREAD

**Issue by colemickens** [paperless-ngx/paperless-ngx#4010]
### Description

I'm pulling my hair out just trying to get paperless even started, figure out what port its on, and login.

### Steps to reproduce

```
PAPERLESS_AUTO_LOGIN_USERNAME="admin"
PAPERLESS_ADMIN_USER="admin";
PAPERLESS_ADMIN_PASSWORD="admin";
```

```
sudo rm -rf /var/lib/paperless
sudo reboot
```

Try to login, nothing.

### Webserver logs

```bash
Aug 17 09:13:56 xeep gunicorn[1914]: [2023-08-17 09:13:56,047] [INFO] [paperless.auth] Login failed for user `admin` from private IP `192.168.1.49`.
```

### Paperless-ngx version

1.17.0

### Host OS

NixOS

### Installation method

Other (please describe above)

**Comment by stumpylog** [comment]
PAPERLESS_ADMIN_USER/PAPERLESS_ADMIN_PASSWORD are only used if there is no user by that name and no existing superuser.  So it's only going to make a change, if any, once.  You should look at the existing users and see if those conditions are met.

**Comment by colemickens** [comment]
As noted in the op, I was `sudo rm /var/lib/paperless` before restarting paperless. It was set to use sqlite and I can see the sqlite file inside `/var/lib/paperless` so I don't expect there to be an existing user.

Maybe it's an issue with using `admin`? I don't know.

**Comment by stumpylog** [comment]
You would need to run the management command `manage_superuser` or nothing happens.  I assume your installation is essentially a bare metal install.

**Comment by colemickens** [comment]
Context, I'm using the NixOS module and assumed that paperless itself would auto create the superuser if those vars were set.

Instead, I see that the NixOS module will ensure the super user is there, but only if I use the secure option of specifying a path to the admin password file. (https://github.com/NixOS/nixpkgs/blob/2c5cd54460ec4460a31c4ce125f355142e6b3f7c/nixos/modules/services/misc/paperless.nix#L267-L277)

Anyway, clearly not a Paperless issue, at least, not a bug anyway.

Thanks for the help, sorry for the distraction.
