### ISSUE TITLE
[BUG] Poor contrast on some UI elements when on dark theme and dark theme color

### ISSUE THREAD

**Issue by dblitt** [paperless-ngx/paperless-ngx#4022]
### Description

This is definitely somewhat of an edge case, but could be resolved by computing a lighter version of the theme color to use when we know the background will also be dark. For example, I chose a very dark purple so a lighter purple could be used to increase contrast.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/11153164/a901e1f6-a238-4fc4-904c-a7f402b396be)

![image](https://github.com/paperless-ngx/paperless-ngx/assets/11153164/c2815d2e-889e-42d6-bb3b-dce209bab838)

![image](https://github.com/paperless-ngx/paperless-ngx/assets/11153164/e520860b-ed9c-4163-9019-0416239605dd)

### Steps to reproduce

1. Turn on dark mode and set theme color to `#08000a` or another dark color
2. Upload document, observe UI

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

1.17.1

### Host OS

amd64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
This is not something I would plan to fix. The color is an accent color, if youre using black (almost) with dark mode it's going to have poor contrast.

We certainly already do a lot of color luminance / brightness guestimating, when relevant, see https://github.com/paperless-ngx/paperless-ngx/blob/main/src-ui/src/app/utils/color.ts
