### ISSUE TITLE
[BUG] Adding a new tag does not clear the text typed in the Tags field

### ISSUE THREAD

**Issue by brandy007** [paperless-ngx/paperless-ngx#4036]
### Description

while editing a document, adding a new tag by typing the tags name in the Tags field and confirming the add new tag dialog adds the new tag to the document but leaves the typed text in the Tags field.
Clicking the "Save" button in the "Create new Tag" dialog correctly clears the typed text in the Tags field.

### Steps to reproduce

1. edit a document
2. start typing in the Tags field - type a non existing tag
3. hit "Enter"
4. the "Create new Tag" dialog appears
5. hit "Enter" 
6. the dialog closes
7. the tag is added to the Tags field, but the typed text rmains as text

### Webserver logs

```bash
no entries in the log
```

### Paperless-ngx version

1.17.1

### Host OS

docker / synology DSM7.2

### Installation method

Docker - official image

### Browser

Chrome / win11

**Comment by shamoon** [comment]
I cannot reproduce this, and the functionality mostly comes from one of our [dependencies](https://github.com/ng-select/ng-select#inputs) which has been pretty stable for some time. Perhaps there was an actual error of some kind somewhere.

See video.


https://github.com/paperless-ngx/paperless-ngx/assets/4887959/5a198ea5-3d12-4248-b626-f7414d21981c

**Comment by shamoon** [comment]
Odd, I can re-create this with enough tries. Hmm, I'll investigate some more
