### ISSUE TITLE
[BUG] Mail integration with Proton-bridge stopped working

### ISSUE THREAD

**Issue by wormi4ok** [paperless-ngx/paperless-ngx#4043]
### Description

After the upgrade from `1.16.5` to `1.17.1` I see connection errors in the mail.log (added a sample in the Webserver logs section)

I configured `paperless-ngx` to consume documents from the Proton Mail account - a privacy-focused email service. The only way to connect to the Proton mail account using IMAP is via the [Proton Mail Bridge](https://github.com/ProtonMail/proton-bridge), which encrypts traffic end to end using my own PGP keys and communicates with the mail server using TLS with certificate pinning. And while offering all these security features, it presents a self-signed certificate for the local connection.

```shell
$ openssl s_client -servername protonmail-bridge -connect 127.0.0.1:143 -starttls imap
CONNECTED(00000003)
depth=0 C = CH, O = Proton AG, OU = Proton Mail, CN = 127.0.0.1
verify error:num=18:self signed certificate
verify return:1
depth=0 C = CH, O = Proton AG, OU = Proton Mail, CN = 127.0.0.1
verify return:1
---
Certificate chain
 0 s:C = CH, O = Proton AG, OU = Proton Mail, CN = 127.0.0.1
   i:C = CH, O = Proton AG, OU = Proton Mail, CN = 127.0.0.1
   ....
```

I believe the reason for the error I get is this PR - https://github.com/paperless-ngx/paperless-ngx/pull/3886. And while I understand that verifying the certificate chain is important and agree with @stumpylog that it should be enabled by default - I feel like I'm exactly that edge case for whom this turns out to be a breaking change.

Would it be possible to add "Verify certificates" checkbox on the mail account settings page, which is enabled by default?
Or is there a way to make `paperless-ngx` trust that specific certificate?
I appreciate your thoughts on the best way to tackle this regression.

### Steps to reproduce

1. Configure `paperless-ngx` to use `protonmail-bridge` as an IMAP email server
2. Upgrade `paperless-ngx` from 1.16.5 to 1.17.0

### Webserver logs

```bash
[2023-08-21 20:10:00,864] [DEBUG] [paperless_mail] Processing mail account <my_email_account>

[2023-08-21 20:10:01,037] [ERROR] [paperless_mail] Error while retrieving mailbox <my_email_account>: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1129)
```

### Paperless-ngx version

1.17.1

### Host OS

Debian - x86_64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
#4040

**Comment by shamoon** [comment]
Yea thing is this isn’t really a bug. It was a change that was added to close a critical security vulnerability see #3886 . Unfortunately it seems breaking for some users. 

I think we can discuss in the above thread and will come up with something flexible enough for different use cases
