### ISSUE TITLE
document_importer: line 15: 477 Killed gosu paperless python3 manage.py document_importer "$@"

### ISSUE THREAD

**Issue by 24cx** [paperless-ngx/paperless-ngx#4091]
### Description

While importing the documents from my old paperless-ngx 1.7.1 version with "docker exec paperless-ngx-webserver-1 document_importer /usr/src/paperless/export/" 
 
I am receiving the information: 

**/usr/local/bin/document_importer: line 15:   477 Killed                  gosu paperless python3 manage.py document_importer "$@"**

What should that mean? 

### Steps to reproduce

I installed paperless-ngx 1.7.1 (before also the newest version) to a new system and copied my 76.000 files of the Export folder.

I did the import and got the information "477 Killed gosu paperless python3 manage.py document_importer "$@""

### Webserver logs

```bash
Where do I get those?
```

### Paperless-ngx version

1.7.1.

### Host OS

Raspberry Pi

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
76000 files is probably running out of memory.  During loading the database would be my guess or the manifest.  Both are JSON files which have to be loaded into memory to be used.

You can look in `dmesg`, something like `dmesg  | grep -i 'killed process'`

**Comment by 24cx** [comment]
[158445.808348] Out of memory: Killed process 25471 (python3) total-vm:348892kB, anon-rss:223708kB, file-rss:8kB, shmem-rss:4kB, UID:1000 pgtables:258kB oom_score_adj:0

Yep. So shall I better export the database on the old system and import in the new, aswell as copy all the files?

**Comment by stumpylog** [comment]
Yes, if you still have the old DB, exporting it to a SQL file (or just moving it if SQLite) as well as the files is roughly the same as the export/import
