### ISSUE TITLE
[BUG] .pdf: Error while consuming document .pdf: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa0d235ddb0>

### ISSUE THREAD

**Issue by fwiessner** [paperless-ngx/paperless-ngx#4096]
### Description

Uploading a PDF fails with: invoice.pdf: Error while consuming document invoice.pdf: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa0d235ddb0>

### Steps to reproduce

Try to upload this PDF: https://owncloud.smart-kvm.com/owncloud/index.php/s/AAm7HE588klSqUw

invoice.pdf: Error while consuming document invoice.pdf: UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa0d235ddb0>

Please request PW for file

### Webserver logs

```bash
there are none
```

### Paperless-ngx version

1.16.5

### Host OS

Deban 11, running from docker

### Installation method

Docker - official image

### Browser

firefox

**Comment by stumpylog** [comment]
Without actual logs, no one can begin to investigate.  Please provide the logs, we ask for them for a reason.

**Comment by stumpylog** [comment]
Ghostscript, through OCRMyPDF is producing an invalid image file, or at least something unrecognizable to PIL.  Nothing we can do about that from this end.  You can try the usual, printing to PDF, cleaning with `qpdf`

**Comment by shamoon** [comment]
You can also open an issue at https://github.com/ocrmypdf/OCRmyPDF/issues but as suspected, this is probably an issue with the pdf itself. Either way, it’s not a paperless bug per se so we’ll close this out. Thanks

**Comment by fwiessner** [comment]
OK, Printing it again as PDF resolved the issue. wouldn't it be cool if paperless did this itself in case of such errors in the first place and only bailing out if that does not fix it?
