### ISSUE TITLE
[BUG] Email attachments don't get storage path like email

### ISSUE THREAD

**Issue by madduck** [paperless-ngx/paperless-ngx#4127]
### Description

Emails are nicely being pulled in with IMAP, and much to my surprise (cf. https://github.com/paperless-ngx/paperless-ngx/discussions/4099), the attachments become documents of their own. This is cool.

I have a document type and a storage path both matching "any word", and that works. Both get correctly assigned to the email, but attachments only get the document type, not the storage path. Is this by design?

### Steps to reproduce

1. Create storage path, set match to "any word: foobar"
2. Create document type, set match to "any word: foobar"
3. Set up IMAP
4. Send an email matching "foobar" in the body, and with a PDF attachment containing "foobar"
5. Observe that the attachment gets into Paperless, and has a document type, but does not get the storage path assigned.

### Webserver logs

```bash
Not relevant.
```

### Paperless-ngx version

1.17.4

### Host OS

Debian

### Installation method

Bare metal

### Browser

Firefox

### Configuration changes

Enabled Tika…

**Comment by stumpylog** [comment]
All documents, email, attachments, PDFs, JPEG, go through the same task for consumption, so if it didn't match, it seems to me there must not have been a match for it.  

Perhaps the attachment didn't actually contain the word, or the content wasn't extracted fully?  If there are multiple possible matches, that also prevents setting a match

**Comment by madduck** [comment]
Thank you @stumpylog for your time!

I only have one document type and one storage path in this test installation, so multiple matches not possible.

There was a match for the document type but not for the storage path, despite both being configured the same. So the attachment should contain the word, but I am actually not sure. Is there another way by which a new document gets a document type assigned? Do all documents have to have a type, and thus if there's only one type, it gets assigned to all documents anyway?

**Comment by stumpylog** [comment]
> Do all documents have to have a type?
No.
> So the attachment should contain the word, but I am actually not sure
You can look at the document content and see what was extracted.  Match any types are pretty basic, merely looking for the work to exist in the content, case insensitive if configured.

**Comment by madduck** [comment]
I understand. What throws me off is that it's the same match for both:

"any word: Rechnung" to match document types:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/195073/af53aef0-aac1-40f6-a14d-05b78962413e)

"any word: Rechnung" to match storage paths:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/195073/26f5df49-1982-4567-97d0-cc2836ac3cb2)

And yet — the word matches in the title and also in the OCR'd text, but there is no storage path assigned:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/195073/2c85ae3b-2bd3-4b0f-b501-4320b82e3a91)

**Comment by stumpylog** [comment]
That appears to be inside a word, which isn't going to be a match.  It's a word based matching, not a search inside words as well.  "Rechnung" doesn't match "Handwerkrrechnung" but matches "Rechnung" (and "rechnung" if made case insensitive)

**Comment by madduck** [comment]
Okay, fair enough, but then why/how did the document type get assigned?

**Comment by stumpylog** [comment]
Presumably the word exists inside the email content as just a word, but not inside the attachment.  You can find the reason logged in the log file.

**Comment by madduck** [comment]
@stumpylog The email got both the type and path. This is not relevant.

The attachment only got the type, not the path, even though they both use the exact same match. That is the problem...

**Comment by madduck** [comment]
On the road now, will check log file...

**Comment by madduck** [comment]
Here is the log file for the email:

```
Sep 05 09:02:52 paperless celery[2509]: [2023-09-05 09:02:52,393] [INFO] [paperless.consumer] Consuming Rechnung-Nr. 1301682.eml
Sep 05 09:02:52 paperless celery[2509]: [2023-09-05 09:02:52,548] [INFO] [paperless.parsing.mail] Sending content to Tika server
Sep 05 09:02:52 paperless celery[2509]: [2023-09-05 09:02:52,606] [INFO] [paperless.parsing.mail] Converting mail to PDF
Sep 05 09:02:55 paperless celery[2509]: [2023-09-05 09:02:55,151] [INFO] [paperless.parsing.mail] Converting html to PDF
Sep 05 09:02:58 paperless celery[2509]: [2023-09-05 09:02:58,661] [INFO] [paperless.handlers] Assigning storage path Rechnungen to 2023-09-05 Rechnung Schneider Heizung und Sanitär GmbH Rechnung-Nr. 1301682
Sep 05 09:02:58 paperless celery[2509]: [2023-09-05 09:02:58,730] [INFO] [paperless.consumer] Document 2023-09-05 Rechnung Schneider Heizung und Sanitär GmbH Rechnung-Nr. 1301682 consumption finished
Sep 05 09:02:58 paperless celery[2509]: [2023-09-05 09:02:58,753] [INFO] [celery.app.trace] Task documents.tasks.consume_file[b86bf946-a93a-4ed1-9876-127572c92dc0] succeeded in 6.442857795000009s: 'Success. New document id 53 created'
```

and here is the log file for the attachment:

```
Sep 05 09:03:02 paperless celery[2773]: [2023-09-05 09:03:02,216] [INFO] [paperless.consumer] Consuming Rechnung-Nr. 1301682.pdf
Sep 05 09:03:02 paperless celery[2773]: [2023-09-05 09:03:02,575] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
Sep 05 09:03:02 paperless celery[2773]: [2023-09-05 09:03:02,595] [INFO] [ocrmypdf._sync] Postprocessing...
Sep 05 09:03:02 paperless celery[2773]: [2023-09-05 09:03:02,816] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
Sep 05 09:03:03 paperless celery[2773]: [2023-09-05 09:03:03,354] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.94 savings: 48.5%
Sep 05 09:03:03 paperless celery[2773]: [2023-09-05 09:03:03,354] [INFO] [ocrmypdf._pipeline] Total file size ratio: 2.67 savings: 62.5%
Sep 05 09:03:03 paperless celery[2773]: [2023-09-05 09:03:03,357] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
Sep 05 09:03:06 paperless celery[2773]: [2023-09-05 09:03:06,616] [INFO] [paperless.consumer] Document 2023-09-05 Rechnung Schneider Heizung und Sanitär GmbH Rechnung-Nr. 1301682 consumption finished
Sep 05 09:03:06 paperless celery[2773]: [2023-09-05 09:03:06,637] [INFO] [celery.app.trace] Task documents.tasks.consume_file[17dacdb4-1364-46f4-9d21-d51c0d11d4cf] succeeded in 4.505432184s: 'Success. New document id 55 created'
```

Notably, there is no `paperless.handlers` lines about storage paths assignment in the second.

**Comment by stumpylog** [comment]
Not really?  How does one log a negative?  The word isn't found, the storage path isn't applied.

**Comment by madduck** [comment]
If the word isn't found, then why is the document type set for the attachment? It has the same matching spec as is used for the storage path (see [screenshots here](https://github.com/paperless-ngx/paperless-ngx/issues/4127#issuecomment-1706881016)).

**Comment by stumpylog** [comment]
I tested again, with an email and PDF attachment.  With the ANY match set to "World", case sensitive, document type and storage path were assigned as expected, matching to that word, to both email document and attachment document.

Mail rules can also set the document type.  Perhaps you set it there

**Comment by madduck** [comment]
Yeah, I set it there, so that's probably what's happening. Will test.

What's the reason that document type and storage path are separate? Shouldn't at least be possible for the latter to be derived from the former?

Why can't the storage path be set in the mail rules, only the document type?
