### ISSUE TITLE
[BUG] (Mac OS) Outlook exported mails to PDF raise import failure

### ISSUE THREAD

**Issue by JarlMorgennebel** [paperless-ngx/paperless-ngx#4135]
### Description

I use Mac OS 11.7.4 Big Sur with Outlook 16.76.2 (23082700) from a Microsoft 365 subscription.

When I export a mail to PDF in Outlook (Menu Outlook >> Print >> PDF button on the bottom) and save to file for an import to paperless-ngx, the import process will fail:

````
MAINGAU Monierung 20230906.pdf: Error while consuming document MAINGAU Monierung 20230906.pdf: ValueError: overflow/underflow converting -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer
`````

I can reproduce this with different exported PDF from different mails, the errors look similiar.

It would be wonderful to support PDFs from Mac OS / Microsoft exports.

### Steps to reproduce

1. Start Outlook
2. Menu Outlook >> Print
3. Click PDF on the dialog (bottom)
4. Save file
5. Import file to paperless-ngx

### Webserver logs

```bash
MAINGAU Widerspruch 20230828.pdf: Error while consuming document MAINGAU Widerspruch 20230828.pdf: ValueError: overflow/underflow converting -67413490548258257961605456244286751932488567828666626215942277363556312796335701245807746045257510352439446031604288022271066970891889922072678664582536019864975141417378607199211846361157709784043353113990147575952011060054909426185709877131030446268188856225724459951776232684500341238408566850233269485568 to 64-bit integer
```

### Paperless-ngx version

1.17.1

### Host OS

Devuan Linux 5.0

### Installation method

Docker - official image

### Browser

Vivaldi

**Comment by JarlMorgennebel** [comment]
Bug verified with v1.17.4 - same issue

**Comment by stumpylog** [comment]
The PDF is not valid.  You can try printing it to a PDF instead or cleaning with qpdf.  See also #2356
