### ISSUE TITLE
[BUG] missing "-" character and {document_type} in downloaded PDF

### ISSUE THREAD

**Issue by flemmingss** [paperless-ngx/paperless-ngx#4148]
### Description

All my storage path's is ending with:
`/{created_year}-{created_month}-{created_day} - {correspondent} - {document_type} - {title}`
The "-" separator is included in the filenames of the paperless-ngx media\documents\archive\ folder, but if I download the file from the web, these charactersis missing. However, it looks like the character is included if it is part of a [placeholder]
The values of {document_type}  is also missing in the downloaded file.

(https://docs.paperless-ngx.com/advanced_usage/#file-name-handling).

![image](https://github.com/paperless-ngx/paperless-ngx/assets/25674067/9de0c453-ea52-4e45-b049-7c8c7ad67db7)

Example:
**In Paperless-ngx file structure:**
`2023-09-07 - WaterCircles - Forsikringsbevis - Travel Insurance (Expiry date- 15.10.2024).pdf`
**If downloaded:**
`2023-09-07 WaterCircles Travel Insurance (Expiry date- 15.10.2024).pdf`

### Steps to reproduce the "-" missing issue

1. create storage patch with "-" in filename (between two [placeholders](https://docs.paperless-ngx.com/advanced_usage/#file-name-handling)?)
2. Add storage patch to document
3. Download document

### Steps to reproduce the " {document_type} " missing issue

1. create storage patch with " {document_type} " [placeholders](https://docs.paperless-ngx.com/advanced_usage/#file-name-handling) in filename
2. Add storage patch to document
3. Download document

### Webserver logs

```bash
No related logs found
```

### Paperless-ngx version

 1.17.4

### Host OS

UnRAID

### Installation method

Docker - official image

### Browser

Google Chrome

**Comment by stumpylog** [comment]
The downloaded file name isn't supposed to match the storage path.  It's a simplified and sanitized filename, not a path.

**Comment by stumpylog** [comment]
Yeah, matches exactly to what I expect, just happens to be similar to your storage path: https://github.com/paperless-ngx/paperless-ngx/blob/d462464af97d1bc9ed9b44b6098de6bc2103ff84/src/documents/models.py#L279-L289

It's not a bug.
