### ISSUE TITLE
[BUG] Paperless no longer working on Safari (TypeError: Zt.split("+").at is not a function)

### ISSUE THREAD

**Issue by saschaludwig** [paperless-ngx/paperless-ngx#4159]
### Description

After successful login, the JS console shows a TypeError and the startpage never loads due to that error.

![Bildschirmfoto 2023-09-10 um 20 39 46](https://github.com/paperless-ngx/paperless-ngx/assets/12997980/0390d085-ebe3-4b29-9032-97ee61997a1f)

I used to use paperless on an older Mac, and it worked like a charm since the latest update.
On a newer Version of Safari, paperless still works.

### Steps to reproduce

1. Open Paperless URL in Safari 15.2 or Safari 15.3
2. Login
3. UI is dead, doesn't load startpage

### Webserver logs

```bash
none
```

### Browser logs

```bash
TypeError: Zt.split("+").at is not a function. (In 'Zt.split("+").at(-1)', 'Zt.split("+").at' is undefined)
```

### Paperless-ngx version

1.17.4

### Host OS

Docker Container on Debian Bullseye x86_64

### Installation method

Docker - official image

### Browser

Safari 15.2 + Safari 15.3

**Comment by shamoon** [comment]
The underlying Angular framework doesnt support all old versions of browsers, you're welcome to stay on an older version of -ngx
https://angular.io/guide/browser-support

**Comment by saschaludwig** [comment]
On your linked page is says: "Safari: 2 most recent major versions"

Latest two are 15 + 16
I'm using 15.

**Comment by shamoon** [comment]
Here's running on 15.6, I cant even test 15.2:
<img width="2362" alt="Screenshot 2023-09-10 at 12 40 45 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/a51d4cc9-dfb4-48bf-97fc-e33ac078b8bb">

In general Im not aware we're doing anything that would directly affect this, at best its an Angular issue (not something we can change), otherwise perhaps theres a deployment issue.

FWIW, no one else out there has reported this, I'd hazard to guess there are others on 15.x though dont know for sure

**Comment by saschaludwig** [comment]
If I redeploy 1.17.2 the problem is gone.
If I deploy 1.17.3 or 1.17.4 the problem is there.
Tested on 2 machines with freshly created macos users. So it shouldn't be a browser-cache issue.
What else can I test to find the cause?

**Comment by shamoon** [comment]
We upgraded to angular 16 around then, could be that. Perhaps running from source would shed more light. You can always look at angular issues

I’d be surprised if there’s something between 15.3 and 15.6 that breaks this but suppose it’s possible. What version of macOS are you on that can’t upgrade beyond 15.3?

**Comment by zivillian** [comment]
After looking a bit deeper it seems, that somehow a polyfill got lost. The function in question was [never supported in safari 15.3](https://caniuse.com/mdn-javascript_builtins_array_at). The usage was introduced in the origin library roughly [a year ago](https://github.com/mozilla/pdf.js/blame/221ee6ca373f452bbdaa7b7a3f0264408d751243/src/display/editor/tools.js#L383), but it seems to related to the [ng2-pdf-viewer upgrade](https://github.com/VadimDez/ng2-pdf-viewer/releases/tag/10.0.0).

**Comment by saschaludwig** [comment]
After upgrading Safari to Version 15.6.1 (which is currently the latest available), paperless works again.

**Comment by shamoon** [comment]
Thanks for the research

Sounds like something that should be reported at [ng2-pdf-viewer](https://github.com/VadimDez/ng2-pdf-viewer) though as noted any users on Safari 15.x (macOS Monterey) should have an upgrade path to 15.6 so may not affect many folks
