### ISSUE TITLE
[Documentation suggestion] Fuzzy tag matching says "I don't know"

### ISSUE THREAD

**Issue by germanmedinasl** [paperless-ngx/paperless-ngx#4206]
### Description

In the url https://docs.paperless-ngx.com/advanced_usage/ when describing the available algorithms for tag matching, at 'fuzzy match' entry, it says: "I don't know", which goes fully against what a documentation should be, as the user already is checking because he doesn't know the program functionality. 

After checking with ChatGPT after giving the following related code: 
`match = re.sub(r"[^\w\s]", "", matching_model.match)`
probably the fuzzy match is just avoiding special characters to find letters and numbers

It is suggested to document properly the 'fuzzy' option in behalf of user understanding.

Fuzzy match: I don't know. Look at [the source](https://github.com/paperless-ngx/paperless-ngx/blob/main/src/documents/matching.py).

### Steps to reproduce

Go to https://docs.paperless-ngx.com/advanced_usage/
Find algorithm for tag matching. 
Read the line "fuzzy match".

### Webserver logs

```bash
-none-
```

### Paperless-ngx version

1.17.4

### Host OS

Windows

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment]
This is actually hilarious.

**Comment by stumpylog** [comment]
Closed in #4207
