### ISSUE TITLE
[BUG] created and added custom date filters not working

### ISSUE THREAD

**Issue by Coniface** [paperless-ngx/paperless-ngx#4235]
### Description

If I filter the documents view by custom dates (whether it's created date or added date) I get a result of 0 documents, whichever dates I try it with. Predefined dates work well (last 7 days, last month...)

-----

All documents added before tomorrow (should be literally all documents):
![image](https://github.com/paperless-ngx/paperless-ngx/assets/7414846/b0b64eea-ff58-4282-9bfa-c40a4d6c32af)

All documents created before tomorrow (should also be all documents):
![image](https://github.com/paperless-ngx/paperless-ngx/assets/7414846/b7232bea-674c-4710-959a-3d95383b3be5)

All documents created in 2020 (should have dozens):
![image](https://github.com/paperless-ngx/paperless-ngx/assets/7414846/985b30e7-f09e-41e0-bc20-3c87f27490d7)

I do have documents saved successfully in the system and they appear flawlessly when no date filter is set:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/7414846/f7825e5c-cc6c-4fa1-a165-22d54990fa89)

And here is the creation date of one document 31/05/2020
![image](https://github.com/paperless-ngx/paperless-ngx/assets/7414846/a9d50d40-7b15-4df4-a80f-8e7d47274158)
which should then appear in the search for documents created between January 1st 2020 and December 31st 2020.

### Steps to reproduce

1. Create a document on paperless and set its creation date
2. Try to filter the documents view with a custom date using the date input
3. "0 documents (filtered)"

### Webserver logs

```bash
No DEBUG logs appear when I make researches.
```

### Browser logs

```bash
No browser logs appear when I make researches.
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 12 bookworm x86_64

### Installation method

Docker - official image

### Other

I don't know if it might be related but some PDF files are password protected. I manually defined a creation date for each and every document though. Also, the added filter should still work.

**Comment by stumpylog** [comment]
Only other thing I can think of is removing the index folder entirely and rebuilding again.  Or looking at the logs.  Date searching works totally fine for me and hasn't changed in quite a while

**Comment by shamoon** [comment]
Can you report the URL in the browser when you chose a date as well as the API url (look under the network tab). And if you open that api URL directly in your browser there are no errors?

Yea, i don’t think this is broken in general and hasn’t changed recently.

**Comment by shamoon** [comment]
Ps. this type of searching doesnt use the document index, its e.g. `created__date__gt=2020-05-31` which hits Django itself (making it even less likely things are broken, tbh)

**Comment by shamoon** [comment]
I wonder if its something like https://stackoverflow.com/questions/60810946/django-truncdate-gives-null/60844090#60844090 or similar.

But again, this functionality comes straight from Django, you'll note we dont implement it in our code (unless youre searching at the same time), and no one else has reported this anytime recently and it cant be reproduced.
