### ISSUE TITLE
[BUG] Weird string formatting for translation

### ISSUE THREAD

**Issue by DimitriDR** [paperless-ngx/paperless-ngx#4259]
### Description

Hi,

I noticed there's translation that doesn't match because of the string is formatted (word by word and not a full sentence).

For example:

![Screenshot 2023-09-25 at 11-13-01 Tâches sur les fichiers - Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx/assets/56969769/4bb9df33-8056-4323-947e-0d4c35209351)

On the bottom, we see "2 total terminé tâches", the equivalent in English would be translated to "2 total tasks finished", it's not correct. The correct sentence would be in English "2 total finished tasks". I presume It's because the UI used several words instead of one sentence like: `{{count}} {{i18n:total}} {{i18n:finished}} {{i18n:tasks}}` instead of `{{count}} {{i18n:finished_tasks}}` - I'm not an expert in TS so I just give the general idea.

Same thing for the Dismiss All modal box.

![Screenshot 2023-09-25 at 11-12-31 Tâches sur les fichiers - Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx/assets/56969769/159fd3ca-3a86-4ec2-8923-4d0dd25a1017)

The body text should be a complete sentence to translate.

I'm ready to translate it on Crowdin 😄 

### Steps to reproduce

1. Switch the UI to French
2. Navigate to the Tasks page

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

17.17.4

### Host OS

N/A

### Installation method

Docker - official image

**Comment by shamoon** [comment]
The string is a complete sentence, `{tasks.length, plural, =1 {One {{this.activeTabLocalized}} task} other {{{tasks.length || 0}} total {{this.activeTabLocalized}} tasks}}`, it just looks partially translated in crowdin https://crowdin.com/translate/paperless-ngx/16/en-fr#17609

The other I can change

**Comment by DimitriDR** [comment]
Oh yeah, the formatting of this translation was a bit uncommon, thus the weird result haha
Thanks!
