### ISSUE TITLE
[BUG] Install script fails on macOS because of empty `PAPERLESS_SECRET_KEY`

### ISSUE THREAD

**Issue by shamoon** [paperless-ngx/paperless-ngx#4272]
### Description

I think https://github.com/paperless-ngx/paperless-ngx/discussions/4267 is the same as https://github.com/paperless-ngx/paperless-ngx/discussions/2560 and #4267 (sorry for converting what was correctly a bug report) and the issue is the secret key generation in the install script. 

There's a change in https://github.com/paperless-ngx/paperless-ngx/discussions/3821 but it doesnt fix it for me.

1. Running `LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head --bytes 64` just gives some weird ouput e.g.:
`��Jz�0���Bc�i�RZ�Y�vl�B��1�r����l4n�B�8e�B��X���TY78�W��6��bs��D%` and I think that leaves PAPERLESS_SECRET_KEY empty ( https://github.com/paperless-ngx/paperless-ngx/discussions/2560#discussioncomment-4821925 https://github.com/paperless-ngx/paperless-ngx/discussions/4267#discussioncomment-7108885 ).
2. Then there's the fact that when the webserver starts with an empty key python does seem to throw `django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.` but nothing is shown in the logs, so its really not obvious.

I tried a hack-y little thing that just falls back if the key is empty:
```
SECRET_KEY = os.getenv(
    "PAPERLESS_SECRET_KEY" if os.getenv("PAPERLESS_SECRET_KEY") is not None else "PAPERLESS_SECRET_KEY_IS_EMPTY",
    "e11fl1oa-*ytql8p)(06fbj4ukrlo+n7k&q5+$1md7i+mge=ee",
)
```
which works but perhaps a better solution exists. Im happy to help test (have an intel Mac I can test with too) but this stuff not in my wheelhouse, or I can PR that little change above.

### Steps to reproduce

1. Run install script on macOS

### Webserver logs

```bash
Look normal, which is confusing
```

### Browser logs

```bash
generic Internal Server Error, which is confusing =)
```

### Paperless-ngx version

1.17.4

### Host OS

macOS (seems to affect at least Apple Silicon 13.5.2 & Intel 12.6.2)

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Does it require setting `LC_CTYPE=C` to get the weird output?  There's no effect I can see in ubuntu setting that vs not.  Or setting it to other values.

One simpler option is to check if the string is empty in the script and prompt for it from the user.  But I'm not sure how the weird string would look.  It may not be actually empty.

Or if macs have openssl available, that's easy as `openssl rand -hex 32`

**Comment by shamoon** [comment]
running without LC_CTYPE literally yields
`M%                           `

You’re right that `tr --delete --complement 'a-zA-Z0-9' < /dev/urandom 2>/dev/null | head --bytes 64` outputs nothing at all

But, OpenSSL seems to work like a charm (on both my machines)!
```
openssl rand -hex 32f25bd795b2ef1ed3a0b945873c382cb4441a0e588719f04498f93e43046990ae
```

Had a feeling you’d be the right person for the job :)

**Comment by stumpylog** [comment]
How about using `openssl` if the command is available, prompting for a string otherwise?  Seems like the simple solution to me?

**Comment by shamoon** [comment]
Sounds like a great solution 💪
