### ISSUE TITLE
[BUG] Drag&Drop Attachment from Thunderbird

### ISSUE THREAD

**Issue by webman2030** [paperless-ngx/paperless-ngx#428]
Hi guys

I wanted to note that it is not possible (for me anyway) to upload an attachment directly from Thunderbird to paperless via drag & drop (without saving it first, via the "save as ..." dialog).

Greetings from Munich
Flo

**Comment by qcasey** [comment]
Does this normally work with other web services, like Google Drive / Nextcloud / Dropbox or even GitHub?

**Comment by webman2030** [comment]
yes have tested it with Google Drive Nextclound and Wetransfer

**Comment by FrankStrieter** [comment]
I can check this.

**Comment by FrankStrieter** [comment]
@webman2030 I tried to upload a thunderbird attachment to google drive. This does not work on my machine. Can you provide some information about your environment?

I've tried it with:
```
OS: macOS (12.2.1)
Browser: Chrome (99.0.4844.51)
email client: Thunderbird (91.7.0)
No Plugins installed on Thunderbird or Chrome
```

**Comment by webman2030** [comment]
@FrankStrieter 
```
simple windows 10
chrome version 99.0.4844.51
thunderbird 91.4.1
```

i work like this for years ... the first time that it does not work like this

**Comment by FrankStrieter** [comment]
I can get a windows system tho check this at the weekend. Please stay tuned.

**Comment by shamoon** [comment]
I actually have the same exact issue with a totally different application on my Mac. My guess is something to do with the file format, e.g. on the mac it isnt a .eml until its been dragged to finder. By the way, when you do "save as..." what format are you saving to before uploading to paperless?

**Comment by shamoon** [comment]
Oh sorry I misunderstood, youre talking about PDF attachments to the email?

**Comment by FrankStrieter** [comment]
So I run into the same issue as this guy about 12 years ago: https://stackoverflow.com/questions/988469/drag-drop-handling-from-thunderbird

I've looked at the source code of dropzone.js as well and they are not handling such filetypes differently. And currently, I have no access to a machine operating windows.

**Comment by shamoon** [comment]
So I think he means PDF attachments, I found this: https://support.mozilla.org/en-US/questions/1153010

This issue doesnt seem to occur with other email clients but i installed Thunderbird Mac and can confirm but this is a bit esoteric. Its also worth noting we leave much of drag-drop logic to a dependency which doesnt seem to support this. I have conceived of a workaround (listen for drop on container element and deal with it there), but when dragging from Thunderbird all I get is an imap URI as `text/uri-list` like
imap://example%40gmail%2Ecom@imap.gmail.com:993/fetch%3EUID%3E/INBOX%3E1234?part=1.1&filename=example.pdf but no idea how to pull actual data. Anyone?

**Comment by webman2030** [comment]
yes i mean PDF attachments which i drag&drop to paperless

**Comment by webman2030** [comment]
how can i help with this "feature"?
i don't know about all the licenses, but isn't it possible to just integrate dropzone?

**Comment by shamoon** [comment]
Actually i just tested https://www.dropzone.dev/js/ with a pdf attachment from Thunderbird and it didnt work. Granted, that is on macOS.

**Comment by shamoon** [comment]
Ps. You cant put dropzone in Angular =)

**Comment by webman2030** [comment]
i find it strange that such a function/feature does not work on the mac.

is it perhaps the thunderbirnd for macos?

can someone test if it works from another macos mail client.

is a normal drag&drop of the attachment into the file manager/desktop working?

**Comment by shamoon** [comment]
Yes, doesnt work in Thunderbird on macOS, I dont have a real PC to test, (we use browserstack). macOS mail works fine, as does normal drag-n-drop

**Comment by FrankStrieter** [comment]
@paperless-ngx/test has anyone of you the possibility to test this behavior?

**Comment by JanneW3** [comment]
Drag&Drop functionality ist something... I tried to merge or convert jpg and other documents directly. I doesn't work. For my this work around works: Open a mail client window, a explorer window and a programm. Drag files now from window to window. I works on paperless, Acrobat etc.

**Comment by nedy13** [comment]
I tested Drag&Drop from Windows 10. Works without any problem.
Thunderbird --> Firefox --> Paperless

OS: Win 10
Thunderbird Portable: 91.8.1 (64-Bit)
Firefox: 99.0.1 (64-bit)

Processing took a while. Paperless-ngx 1.7.0 is running on a RaspPi4.

https://user-images.githubusercontent.com/4283170/167025131-0c68f0f3-9cd4-465c-9565-1af27712693f.mp4

Get the same message in Browser's Console, but seems to have no impact on that.

![image](https://user-images.githubusercontent.com/4283170/167025679-a6f015d2-3172-46ba-badc-164bc545820e.png)

**Comment by shamoon** [comment]
> I tested Drag&Drop from Windows 10. Works without any problem. Thunderbird --> Firefox --> Paperless

Appreciate the help & video, I think we can close this!
