### ISSUE TITLE
[Bug] Long notes overflow visually

### ISSUE THREAD

**Issue by PaulEins** [paperless-ngx/paperless-ngx#4286]
### Description

Many Notes dont work. Layout broken. Please help.

![SCR-20230928-ijk](https://github.com/paperless-ngx/paperless-ngx/assets/89552633/f306205a-b2c9-405a-a0b6-1de4ce9d0c97)

### Steps to reproduce

no, uss this tex: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
![SCR-20230928-ijk](https://github.com/paperless-ngx/paperless-ngx/assets/89552633/a6f0e43a-259d-4a74-8779-3284bbb83e63)

### Webserver logs

```bash
no Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

### Browser logs

```bash
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

### Paperless-ngx version

1.17.4

### Host OS

Synology Docker 

### Installation method

Docker - official image

### Browser

Chrome and Safari dont work

**Comment by shamoon** [comment]
Cant reproduce this
<img width="760" alt="Screenshot 2023-09-28 at 7 03 30 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/5931aa68-d0fe-40cf-acba-9efbf37b27ed">

Are there errors in your browser? Any custom css with Greasemonkey or something like that?

**Comment by stumpylog** [comment]
I think the idea is creating a really long note will overflow:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/0621de1b-e131-4f52-84f4-c0cdc2e013d8)

**Comment by shamoon** [comment]
Ah thanks, ok no worries
