### ISSUE TITLE
[BUG] Emails with text/html containing Windows-1252 charset rendered wrong.

### ISSUE THREAD

**Issue by weetmuts** [paperless-ngx/paperless-ngx#4297]
### Description

Many thanks for a very very useful program!

Emails with html with UTF8 characters are rendered wrong in my docker setup.

The text: "för måndagens digitala" found inside the text/plain part of an eml attachement to an imported email looks fine. The same content but as text/html however is rendered mostly correctly except the UTF8 characters: "fÃ¶r mÃ¥ndagens digitala"

When  I run the locale command in the paperless_webserver_1 docker container, it is LANG=C.UTF-8
For the postgresql it is LANG=en_US.utf8

But when I run the locale command in the tika and the gotenberg containers, then LANG is empty.
(LANG is empty in the redis container as well, but this is probably not relevant.)

Could it be that the tika/gotenberg docker containers should have LANG=C.UTF-8 locale set to fix this?

### Steps to reproduce

Use the standard docker setup, configure  an email import rule. 
Consumption scope import as eml and attachments separately.

Import an email with a text/plain part and a text/html part which contains UTF8 characters.
The text/plain is rendered correctly in the generated pdf. The text/html contains broken UTF8. 

### Webserver logs

```bash
.
```

### Paperless-ngx version

1.17.4

### Host OS

ubuntu 22

### Installation method

Docker - official image

### Browser

Firefox

**Comment by stumpylog** [comment]
Try setting the lang environment for those containers?

**Comment by weetmuts** [comment]
Tank you @stumpylog  I added:
    environment:
      LANG: C.UTF-8

to gotenberg and tika in the docker-compose.yml Not sure if this affected anything because
I tested with gmail and there it works fine with åäö in both plain and html.

After inspecting the raw eml, gmail uses:
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: base64
and
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

However after inspecting the problematic eml it seems they are sent a microsoft tool/platform
and uses the charset Windows-1252.

The working part starts like this:-----------------------------------------

Content-Type: text/plain; charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable

... f=F6r m=E5ndagens digitala styrelsem=F6te med =
 
The non working part starts like this:-----------------------------------

Content-Type: text/html; charset="Windows-1252"
Content-Transfer-Encoding: quoted-printable

<html>...<p><font size=3D"3">Jag bifogar dagordning f=F6r m=E5ndagens digitala styre=

----------------------------------------------------------------------------------------

Is the text/html going through gotenberg and can gotenberg handle Windows-1252?

**Comment by stumpylog** [comment]
Questions about gotenberg are better directed to it's developers.  I don't know anything about it's support.  If you can provide a sample file, I can try to look intonit from this side q little bit.

**Comment by weetmuts** [comment]
Thank you very much! I have attach an example eml file (renamed to txt since github)

[Testing åäö in emails from MS.txt](https://github.com/paperless-ngx/paperless-ngx/files/12816937/Testing.aao.in.emails.from.MS.txt)

Rename it to eml. Mail it to your paperless as an attachment.

**Comment by weetmuts** [comment]
The attached eml(txt) reproduces the problem, the first part of the archived document looks good:
åäö does it work?
The second part (through gutenberg) looks like:
Ã¥Ã¤Ã¶ does it work?

**Comment by stumpylog** [comment]
Looking at this a little more, the HTML isn't actually technically valid.  It doesn't include a DOCTYPE to indicate what version of HTML it is.  Considering HTML5 was released in 2014, it's probably trying to be that.  But including a [non-UTF8 `charset` isn't valid](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset).

So really whatever is making this should fix itself.  iso-8859-1 was the default charset for HTML 4.01 (released in 1999). Basically, whatever made this email is a mess of confusion.

**Comment by weetmuts** [comment]
> Basically, whatever made this email is a mess of confusion.

Completely unsurprising, the cause of this mess is Microsoft Office 365. :-) I am guessing that when windows-1252 is used when the email is sent from an Outlook windows program.

**Comment by stumpylog** [comment]
Our dependency has kindly made some updates which I think will resolve this.  I'll be able to test it further in the next day or so.

**Comment by shamoon** [comment]
Nice stumpy thanks for facilitating the fix

**Comment by weetmuts** [comment]
Many thanks @stumpylog for the quick work on this!

**Comment by weetmuts** [comment]
When will this be part of the docker distribution of paperless-ngx?

**Comment by stumpylog** [comment]
Soon(tm).  If you can't wait, you could use [container initialization](https://docs.paperless-ngx.com/advanced_usage/#custom-container-initialization) to run `pip3 install --upgrade imap_tools`
