### ISSUE TITLE
[Other] Workflow, Setup Issue, Possible Feature Request?

### ISSUE THREAD

**Issue by hav0ck** [paperless-ngx/paperless-ngx#431]
So very quick background on my setup.

I have MFP that scans and FTP's the pdf document to a directory on a Ubuntu server.
The Ubuntu Server has that directory setup as a NFS share.
A second server (both virtual on ESXi) mounts the NFS share and runs Paperless-ngx in docker.
Since inotify doesn't work with NFS I have polling set for every 60 seconds.

I had some issues with polling not working but I got that sorted, did some testing and everything seemed fine. So I scanned a document and Paperless-ngx reported an input file error. I scanned a second document with the same error.
I checked the pdf files and they opened fine in a pdf reader. It was late so I grabbed some sleep.

I did another test this morning and the printer needed to warm-up before starting the actual scan. During the warmup I opened the NFS scan in Windows Explorer and noticed a new pdf file, I tried to open the file but got an error. I went to the paperless-ngx tab in my browser and it had tried to import this new file and it errored out with the input file error again. Then the MFP started scanning the document. I went back to the Windows Explorer window, refreshed and I was able to open the new file I wasn't able to open just moments earlier. I quickly did another scan which paperless-ngx was able to import just fine.

So with the background out of the way.
My MFP creates the PDF file at the start of the scanning process.
I have polling set to 60 secs.
Only 1 attempt is ever made to import a file.

So it seems that if Paperless-ngx polls the share and the pdf is still being written it doesn't wait until the file is complete it errors out (pdf readers do the same).

Is there a way to have Paperless-ngx attempt an import of a pdf that experienced an error?
What is the best, simplest way to fix this issue? Increasing the polling time won't eliminate this but it might lessen the frequency?
Is there a way to setup a share that inotify will work? That seems like the ideal solution.

I was thinking a 'Rescan Consume Dir' option might be nice, is that Feature Request worthy?

**Comment by stumpylog** [comment]
I assume this was the same kind of issue we made attempts to resolve in #483 .  There are now additional checks before the consumption begins to prevent this sort of erroring out.  We won't (as of yet) be able to retry an import
