### ISSUE TITLE
[BUG] Some documents fail to be consumed due to "Device or resource busy"

### ISSUE THREAD

**Issue by Bond246** [paperless-ngx/paperless-ngx#432]
Hello,

i'm a really fresh user to paperless and installed it just some days ago via docker-compose. 
I would like to reference an issue from the before repository from jonas because i think i have the same problem:
https://github.com/jonaswinkler/paperless-ng/issues/1406

My scanner is an HP OfficeJet Pro 9022e with smb-scan function. And mostly files that are still not finished written gets queued from paperless but the job run into a `[Errno 16] Device or resource busy: `failure. 
This happens for example with files where i add pages manually by scanning and so the files are still handled by the scanner.

In Logs it looks like this:
```
[2022-03-18 14:00:43,759] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/scan_20220318_20220318135855.pdf to the task queue.
14:00:43 [Q] INFO Enqueued 1
14:00:43 [Q] INFO Process-1:174 processing [scan_20220318_20220318135855.pdf]
14:00:43 [Q] INFO Process-1:174 stopped doing work
14:00:43 [Q] ERROR Failed [scan_20220318_20220318135855.pdf] - [Errno 16] Device or resource busy: '/usr/src/paperless/src/../consume/scan_20220318_20220318135855.pdf' : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 70, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 199, in try_consume_file
    self.pre_check_duplicate()
  File "/usr/src/paperless/src/documents/consumer.py", line 90, in pre_check_duplicate
    with open(self.path, "rb") as f:
OSError: [Errno 16] Device or resource busy: '/usr/src/paperless/src/../consume/scan_20220318_20220318135855.pdf'

14:00:44 [Q] INFO recycled worker Process-1:174
14:00:44 [Q] INFO Process-1:176 ready for work at 24155
```

What i've done already was to define `PAPERLESS_CONSUMER_POLLING: 60` via docker-compose which canceled some warnings in paperless-log that i had before but didn't solved the main problem.

To solve the problem in specific case is to go to admin-page and restart the failed jobs 
or the more brutal way: to restart the paperless-container.

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 20.04 LTS
 - Browser not necessary
 - Version: 1.6.0
 - Installation method: docker-compose
```
version: "3.4"
services:
  paperless-redis:
    image: redis:alpine
    container_name: paperless-redis
    restart: unless-stopped
    networks:
      - my-bridge
    volumes:
      - paperless-redis_data:/data

  paperless-db:
    image: postgres:13-alpine
    container_name: paperless-db
    restart: unless-stopped
    networks:
      - my-bridge
    volumes:
      - paperless-db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: ...
      POSTGRES_PASSWORD: ...

  paperless-app:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-app
    restart: unless-stopped
    depends_on:
      - paperless-redis
      - paperless-db
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my-bridge
    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - paperless_export:/usr/src/paperless/export
      - paperless_incoming:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-db
      USERMAP_UID: 1000
      USERMAP_GID: 100
      #PAPERLESS_OCR_LANGUAGES: tur ces
      PAPERLESS_SECRET_KEY: ...
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{created}_{title}"
      PAPERLESS_CONSUMER_POLLING: 60

volumes:
  paperless_data:
    external: true
  paperless_media:
    external: true
  paperless_incoming:
    external: true
  paperless_export:
    external: true
  paperless-db_data:
    external: true
  paperless-redis_data:
    external: true

networks:
  my-bridge:
    external: true
```

**Comment by shamoon** [comment]
This came up a lot in -ng, I think. Is the issue that the scanner isnt "done" creating documents or are these docs that have already been completely scanned and saved?

**Comment by Bond246** [comment]
I think the issue is that the scanner isn't ready with the complete scan process when the files appears in the smb-share.
I also think that the scanner completely does the job inside the share instead doing everthing localy and copying the finished file to the share.

So thats why inotify also does not work.

I think it is not a problem at all that paperless can't process the uncompleted file but paperless should start a new try after a while or pause the cue for some seconds and restart then. Or it should start a defined number of retrys until it stops to import the specific file at all. At least in case of Error 16...

Does that help?
If needed i could do some tests in any verbose mode if you tell me how or what to do.

Thank!

**Comment by stumpylog** [comment]
I wonder if adding some sort of check either of mtime vs crime or maybe st_size stops changing would alleviate this?

Basically some way to wait until a file is "done" before really turning the consumer loose on it.  Or maybe the inotify flags could be used. I'll have to look at it.

**Comment by FrankStrieter** [comment]
We can also look at the error message. If the file is busy (Error 16 from the python file handler), reschedule the file in 1 Minute or so. I think there will be other use cases for this too. For Example, somebody creates an office document and saves it into the customer folder but leaves the application running. This will create a busy file too.

**Comment by a17t** [comment]
If the file is still busy being written, paperless should anyway receive another inotify event when the next write occurs or it's closed.

So maybe it would be enough to ignore the file as long as it is reporting as busy.


Btw. Had the same issue with the original paperless and an hp scanner...

**Comment by Bond246** [comment]
i made an inotify-log today to show you what the scanner is doing:
```
19:12:07 scan_20220320_20220320191034.pdf CREATE
19:12:07 scan_20220320_20220320191034.pdf OPEN
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:08 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:12:35 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:12 scan_20220320_20220320191034.pdf MODIFY
19:13:13 scan_20220320_20220320191034.pdf MODIFY
19:13:13 scan_20220320_20220320191034.pdf MODIFY
19:13:28 scan_20220320_20220320191034.pdf MODIFY
19:13:28 scan_20220320_20220320191034.pdf CLOSE_WRITE,CLOSE
19:13:28 scan_20220320_20220320191034.pdf ATTRIB
```
In this case is scanned 3 pages manually. Be aware of the times.
Maybe that helps to improve the process. 

The problem is that i think it is not possible for me to use paperless with inotify. I tryied to do the log on the paperless-driving ubuntu-machine that maps the comsume-folder by smb-cifs and nothing was logged. So i made this log above on the NAS where the share is hosted.

**Comment by FrankStrieter** [comment]
@paperless-ngx/backend does somebody of you have an idea, of how to solve this issue with all its edge cases? From my Point of view, the idea with the rescheduling if it fails with error code 16 can be tested.

**Comment by stumpylog** [comment]
For those who are seeing this issue, could you confirm it is happen when `PAPERLESS_CONSUMER_POLLING` is either set to 0 or is unset?  ie that is happens with the default configuration to use inotify

**Comment by Bond246** [comment]
> For those who are seeing this issue, could you confirm it is happen when `PAPERLESS_CONSUMER_POLLING` is either set to 0 or is unset? ie that is happens with the default configuration to use inotify

i can't answer that, in my case inotify is not working with my cifs-share.

**Comment by schnuffle** [comment]
Have any of you checked, if there's a handle on the file as long as it's not done?

Like lsof /path/file

**Comment by stumpylog** [comment]
Would that work in Docker?  I'm wondering if the handle to the file is out in the host, not the container, it might say the file is ready?  I'm not an expert on containers though, so maybe they share something like that

**Comment by stumpylog** [comment]
With 1.7.0, there is now some additional checking and waiting around file consumption for both inotify and polling based setups.  These changes should resolve the issue.

**Comment by Bond246** [comment]
Hello,

i had this problem again today:
```
[2022-05-13 13:49:33,358] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/scan_20220513.pdf to remain unmodified

[2022-05-13 13:49:38,993] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/src/../consume/scan_20220513.pdf: OS reports file as busy still

[2022-05-13 13:50:33,364] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/scan_20220513_20220513135110.pdf to remain unmodified

[2022-05-13 13:50:33,366] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/scan_20220513_20220513135048.pdf to remain unmodified

[2022-05-13 13:50:38,381] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/scan_20220513_20220513135048.pdf to the task queue.

[2022-05-13 13:50:38,593] [INFO] [paperless.consumer] Consuming scan_20220513_20220513135048.pdf

[2022-05-13 13:50:38,609] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2022-05-13 13:50:38,611] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2022-05-13 13:50:38,614] [DEBUG] [paperless.consumer] Parsing scan_20220513_20220513135048.pdf...

[2022-05-13 13:50:38,659] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/src/../consume/scan_20220513_20220513135048.pdf

[2022-05-13 13:50:38,765] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/scan_20220513_20220513135048.pdf', 'output_file': '/tmp/paperless/paperless-yfukhcne/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-yfukhcne/sidecar.txt'}

[2022-05-13 13:50:38,957] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/src/../consume/scan_20220513_20220513135110.pdf: OS reports file as busy still

[2022-05-13 13:50:55,181] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2022-05-13 13:50:55,182] [DEBUG] [paperless.consumer] Generating thumbnail for scan_20220513_20220513135048.pdf...

[2022-05-13 13:50:55,185] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-yfukhcne/archive.pdf[0] /tmp/paperless/paperless-yfukhcne/convert.png

[2022-05-13 13:50:56,801] [DEBUG] [paperless.parsing.tesseract] Execute: optipng -silent -o5 /tmp/paperless/paperless-yfukhcne/convert.png -out /tmp/paperless/paperless-yfukhcne/thumb_optipng.png

[2022-05-13 13:51:05,720] [DEBUG] [paperless.consumer] Saving record to database
```

Both file scan_20220513.pdf and scan_20220513_20220513135048.pdf where busy and didn't queued. In 1.6.0 i was able to restart the missed jobs with admin console. Now i can't do this anymore.

**Comment by stumpylog** [comment]
For my perspective, paperless is doing the correct thing here.  `scan_20220513.pdf` was still busy, even after waiting quite a while, so it wasn't consumed.  Consuming would have failed anyway.  The same issue with `scan_20220513_20220513135110.pdf`.  This means both documents were still is use by something.  I'm assuming a scanner is placing documents into the consume folder?  It seems like every single one has a different quirk about writing files.

Meanwhile, `scan_20220513_20220513135048.pdf` is consumed normally after it isn't busy.

**Comment by seidls** [comment]
@stumpylog I had this happen today on 1.7.1.   In the end the file was 8 MB in size coming from the scanner, and was going to be split by the PATCHT logic.  It hit this error and then this file did not retry to consume (even with my 90 second polling)
`[2022-05-15 21:35:44,348] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/U64875C1X114340_05152022_213330_000285.pdf to remain unmodified
...
[2022-05-15 21:36:09,371] [ERROR] [paperless.management.consumer] Timeout while waiting on file /usr/src/paperless/src/../consume/U64875C1X114340_05152022_213330_000285.pdf to remain unmodified.`

Once I restarted the container, it picked up just fine and processed.

Is there a setting that we can configure how long it waits for a file to remain unmodified?   Why wouldn't a subsequent polling have picked up and tried again?  If the "task" for this fail, why wasn't it in the failed task Q that I could have restarted it?

**Comment by stumpylog** [comment]
Ok, few things to unpack here.

> Is there a setting that we can configure how long it waits for a file to remain unmodified? 

Paperless will check for a file to unmodified PAPERLESS_CONSUMER_POLLING_RETRY_COUNT times (default 5) with PAPERLESS_CONSUMER_POLLING_DELAY (default 5) seconds between each check.  It sounds like you've already configured PAPERLESS_CONSUMER_POLLING_DELAY to be 90, so this file was still changing after 7.5 minutes of checking.  That's quite a long time, but I don't think indicative of a problem with paperless.

> Why wouldn't a subsequent polling have picked up and tried again? 

I'd have to examine to code of the library we use, but presumably it works on the basis of snapshotting directories and comparing subsequent snapshots.  Once a file has been snapshot, the event would be raised and then won't change in following snapshots.

> If the "task" for this fail, why wasn't it in the failed task Q that I could have restarted it?

In this case, no task would have been created anyway.  Otherwise, the only was for a task to fail is for it to crash.  There has been a lot of work put in to not allow unhandled exceptions, so I don't expect this to change.

**Comment by seidls** [comment]
> I assumed from your comment "(even with my 90 second polling)" that the polling delay was configured to 90 already. But maybe that was CONSUMER_POLLING instead. The names are a little confusing.

Ah - got it.  Yes, I have `PAPERLESS_CONSUMER_POLLING` set to 90.... not the polling delay.  Thanks for the info.

**Comment by Bond246** [comment]
so as conclusion (even for me) we have to define additional ENVs to deal with that?
Actually i only use `PAPERLESS_CONSUMER_POLLING: 60`. Anything else to use?

Maybe more retrys?
Higher delay?

**Comment by stumpylog** [comment]
Yes, you'll want to play around with tuning PAPERLESS_CONSUMER_POLLING_RETRY_COUNT and PAPERLESS_CONSUMER_POLLING_DELAY for your setup if you're running into issues consuming either due to documents still being busy or documents timing out while waiting to be unmodified.
