### ISSUE TITLE
[BUG] Wrong ASN on "+1" Button with multiuser

### ISSUE THREAD

**Issue by Schrolli91** [paperless-ngx/paperless-ngx#4325]
### Description

If another user will add a document and set an ASN on it, the "+1" Button near the ASN fild wont work for the other users, because the numbering is wrong.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/6043382/ef8dec2a-4a67-46f7-8fa4-f5ba3bc7fb21)

If the document with the first given ASN is shared to me, the "+1" Button will add the correct number (2 in this case).
If i cant see the other document (not shared) the "+1" Button will add a one and then i can't save the document because the ASN is still used.

### Steps to reproduce

**User1:**

- One user add adds a document
- Set a ASN on this document with "+1" button (1 is added)
- Save the document

**User2:**

- Other user adds a document
- Set a ASN on this document with "+1" button (1 is added)
- Try to save the document (error: ASN still in use)

User1 will share the document with User2.
Retry the steps from User2 - now a push on "+1" will add the correct ASN (2)

### Webserver logs

```bash
no logs needed
```

### Paperless-ngx version

1.17.4

### Host OS

Debian on Proxmox (Intel NUC)

### Installation method

Docker - official image

### Browser

Chrome

### Other

**Solution:**
A global counter for the ASN should be respected, also if documents are not shared. ASNs should uniqe over the whole paperless instance, not only by the user.

or

Prefixed ASNs to make it uniqe for each user.

**Comment by N1c093** [comment]
The ASN-feature doesn't seems to have a multiuser functionality at the moment. 
See also discussion: #4169 and #1841
