### ISSUE TITLE
[BUG] can't run the docker image with UID 33 (www-data)

### ISSUE THREAD

**Issue by ovoix** [paperless-ngx/paperless-ngx#433]
**Describe the bug**
I would like to run paperless-ngx docker with UID and GID 33 (www-data). 
This will throw the error usermod: UID '33' already exists.

**To Reproduce**
1. Use ghcr.io/paperless-ngx/paperless-ngx:latest
2. set the USERMAP_UID and USERMAP_GID to 33
3. docker-compose up
4. This will throw the error usermod: UID '33' already exists.

**Expected behavior**
no error

**Screenshots**
NA

**Webserver logs**
```
usermod: UID '33' already exists.
```

**Relevant information**
 - Ubuntu 21.10 arm64
 - Version [e.g. 1.6.0]
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
docker-compose.env:
USERMAP_UID=33
USERMAP_GID=33

**Comment by tribut** [comment]
Duplicate of #374

If this is a problem people encounter often, we should probably consider reusing an existing user if it already exists.

**Comment by shamoon** [comment]
Closing as duplicate
