### ISSUE TITLE
[BUG] Downloaded PDFs don't retain the url links present in the original PDF

### ISSUE THREAD

**Issue by owldown** [paperless-ngx/paperless-ngx#4337]
### Description

I've possibly missed something, but when I upload/consume a PDF with hyperlinked text, the pdf shown in Paperless doesn't retain functional hyperlinks when I download the document. If I instead download the original PDF again, the links do indeed work as intended. Something in the process of archiving the PDF is removing the hyperlinks, and if this can be changed by the user, I've not been able to find how. 

For my use, those hyperlinks are critical to the document, and I'd like to preserve them if possible. 

### Steps to reproduce

1. Upload PDF with hyperlinks
2. Download PDF
3. Click link and watch as nothing happens

### Webserver logs

```bash
I don't know if this is applicable
```

### Paperless-ngx version

1.17.4

### Host OS

x86_64 Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Safari

**Comment by shamoon** [comment]
Id presume this is caused by archiving as PDF/A which is the paperless default. But ultimately this is actually not performed by paperless but rather a tool we use called ocrmypdf. You can see in the logs the command paperless uses to generate the archive version to test it yourself, if you feel there's a bug in what its doing you can always raise an issue in their project: https://github.com/ocrmypdf/OCRmyPDF

**Comment by owldown** [comment]
Thanks! I do find that adding
```
PAPERLESS_OCR_OUTPUT_TYPE=pdf
```
to my docker-compose.env and testing the same document does result in the behavior I desire - preserving the hyperlinks in the archived version of the pdf. I hope that someone else finds this helpful.

Looking closely at the docs for OCRMyPDF, I see that they in turn use Ghostscript to produce PDF/A files, and they include this admonition "Ghostscript’s PDF/A conversion seems to remove or deactivate hyperlinks and other active content." From what I can tell, when a regular PDF is requested as the output type, they are using Tesseract's functionality to write the OCRed text into the output PDF. 

I do wonder if there should be something in the docs for paperless-ngx that includes not only *how* to set the OCR_OUTPUT_TYPE to pdf, but *why* one might want to do that (to preserve hyperlinks, for example).
