### ISSUE TITLE
[BUG] ASN (+1) provide a already used number

### ISSUE THREAD

**Issue by easyboxy** [paperless-ngx/paperless-ngx#4338]
### Description

If I request the next number by the (+1) button the function provide the next number of the user. It should provide the next number based on the last number over all ASN number. Otherwise an error occouses 'Number already in use'.

### Steps to reproduce

1. Enter a document with the next ASN
2. Enter a document with a user without access to the user in step 1
3. Click ASN (+1) 
4. An error occourses

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.17.4

### Host OS

Archlinux

### Installation method

Docker - official image

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/issues/4325
