### ISSUE TITLE
[BUG] Sort by date does not seem to be working

### ISSUE THREAD

**Issue by plu** [paperless-ngx/paperless-ngx#4351]
### Description

When I use the sorting function for the `Created` date, filling in `After: 2023-10-01`, I expect a document with creation date `2023-10-05` to be found. Unfortunately this does not seem to work, see 2nd screenshot. You can see in the 1st screenshot that using the `Last 7 days` sorting functionality does work.

# 👍 `Last 7 days`
<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/32e199d0-f0e8-43e0-9642-4dcce841ced4" width=600>

# 👎 `After 2023-10-01`
<img src="https://github.com/paperless-ngx/paperless-ngx/assets/31597/5f1a1536-8f23-43cc-a344-25ef68326e0c" width=600>

### Steps to reproduce

1. Look up some document's creation date
2. Change sort filter for creation date, fill in the `After:` date with a value older than the documents creation date

### Webserver logs

```bash
Don't have any.
```

### Paperless-ngx version

1.17.4

### Host OS

Debian GNU/Linux 12

### Installation method

Docker - official image

### Browser

Safari

**Comment by plu** [comment]
Forgot to mention that the same bug happens for the `Added` date.

**Comment by shamoon** [comment]
I wonder if this is #4235 but in general no known issues with this and it’s basic functionality that hasn’t changed in a long time.

**Comment by plu** [comment]
Magic! Thank you - that was it! Apologies I have not managed to dig out the older issue.

![Screenshot 2023-10-10 at 15 39 49](https://github.com/paperless-ngx/paperless-ngx/assets/31597/bfdb7cd1-91c0-4c39-af65-9cf23676b8ac)
