### ISSUE TITLE
[BUG] No found message after successful import

### ISSUE THREAD

**Issue by ferllings** [paperless-ngx/paperless-ngx#4357]
### Description

For most documents I put in the consume folder, it imports successfully...
<img width="1254" alt="Screenshot 2023-10-11 at 17 05 32" src="https://github.com/paperless-ngx/paperless-ngx/assets/2118130/0a54f27f-8190-4570-97f0-726d418a5b0d">

... but I also receive a message that the document can't be found.
<img width="1254" alt="Screenshot 2023-10-11 at 17 04 39" src="https://github.com/paperless-ngx/paperless-ngx/assets/2118130/0cdadc4e-10b0-439f-806d-3e895fe71ca7">

### Steps to reproduce

1. Put a document in the consume folder
2. Wait until it finished processing
3. See error message

### Webserver logs

```bash
2023/10/11 17:00:59	stderr	documents.consumer.ConsumerError: 2003 - Marlène - Impots Revenus.pdf: Cannot consume /usr/src/paperless/consume/2003 - Marlène - Impots Revenus.pdf: File not found.
2023/10/11 17:00:59	stderr	    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
2023/10/11 17:00:59	stderr	  File "/usr/src/paperless/src/documents/consumer.py", line 109, in _fail
2023/10/11 17:00:59	stderr	    self._fail(
2023/10/11 17:00:59	stderr	  File "/usr/src/paperless/src/documents/consumer.py", line 131, in pre_check_file_exists
2023/10/11 17:00:59	stderr	    self.pre_check_file_exists()
2023/10/11 17:00:59	stderr	  File "/usr/src/paperless/src/documents/consumer.py", line 350, in try_consume_file
2023/10/11 17:00:59	stderr	    document = Consumer().try_consume_file(
2023/10/11 17:00:59	stderr	  File "/usr/src/paperless/src/documents/tasks.py", line 156, in consume_file
2023/10/11 17:00:59	stderr	    return self.run(*args, **kwargs)
2023/10/11 17:00:59	stderr	  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
2023/10/11 17:00:59	stderr	    R = retval = fun(*args, **kwargs)
2023/10/11 17:00:59	stderr	  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
2023/10/11 17:00:59	stderr	Traceback (most recent call last):
2023/10/11 17:00:59	stderr	[2023-10-11 15:00:59,392] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[a49eeedf-4682-4543-a951-070b0ba451a3] raised unexpected: ConsumerError('2003 - Marlène - Impots Revenus.pdf: Cannot consume /usr/src/paperless/consume/2003 - Marlène - Impots Revenus.pdf: File not found.')
2023/10/11 17:00:59	stderr	[2023-10-11 15:00:59,361] [ERROR] [paperless.consumer] Cannot consume /usr/src/paperless/consume/2003 - Marlène - Impots Revenus.pdf: File not found.
```

### Paperless-ngx version

1.17.4

### Host OS

Synology

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
There are a number of timing tweaks documented which can help resolve this: https://docs.paperless-ngx.com/configuration/#consume_config

Please adjust those, depending on your use of inotify (default) or polling.

**Comment by stumpylog** [comment]
See also: https://docs.paperless-ngx.com/troubleshooting/#consumer-fails-with-a-filenotfounderror

**Comment by ferllings** [comment]
Thanks for the help.
This is a very powerful app, and barely scratched the basic configuration.
