### ISSUE TITLE
[BUG] api/tags endpoint ignores set_permissions?

### ISSUE THREAD

**Issue by ndw** [paperless-ngx/paperless-ngx#4363]
### Description

The `set_permissions` field doesn't seem to be supported when creating tags with the REST API.

### Steps to reproduce

I created a two users, my id is 3, the other id is 4. I then attempt to create a tag by posting this payload to `/api/tags` using token authorization.

```json
{
    "name": "tagme2",
    "match": "",
    "matching_algorithm": null,
    "is_insensitive": false,
    "is_inbox_tag": false,
    "owner": 3,
    "set_permissions": {
       "view": {
         "users": [4],
         "groups": []
       },
       "change": {
         "users": [4],
         "groups": []
       }
    }
}
```

I get a 201 response:

```
{"id":10,"slug":"tagme2","name":"tagme2","colour":1,"match":"","matching_algorithm":1,
"is_insensitive":false,"is_inbox_tag":false,"owner":3,"user_can_change":true}
```

The documentation suggests that `owner` should be a property inside `set_permissions`, but that doesn't have any effect. (I still get a 201 and I still don't get any permissions).

The resulting tag has no permissions for userid 4. The `full_perms=true` response uses `permissions`, not `set_permissions` as the property name, but that doesn't work either.

### Webserver logs

```bash
There don't appear to be any relevant logs.
```

### Browser logs

```bash
N/A
```

### Paperless-ngx version

1.17.4

### Host OS

Debian/12

### Installation method

Docker - official image

### Browser

N/A

### Configuration changes

None

**Comment by shamoon** [comment]
Well, you are correct that the docs are wrong, I can fix that, but the API endpoint definitely works, thats how the frontend does this:
<img width="512" alt="Screenshot 2023-10-13 at 8 07 07 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/a283606e-e471-4fcb-a7a1-50b2103638d8">
<img width="648" alt="Screenshot 2023-10-13 at 8 08 09 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/e721361b-dfca-40e8-b6db-70fb91d0a8d9">
<img width="279" alt="Screenshot 2023-10-13 at 8 15 46 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/76a051d5-d161-4dc3-b1cb-30184db9e477">

Again:
<img width="807" alt="Screenshot 2023-10-13 at 8 29 13 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/75f9266e-4421-408d-a33f-2e691211c90e">
<img width="382" alt="Screenshot 2023-10-13 at 8 29 37 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/5e6de061-b37d-4020-b30b-d1e54852e05c">

After creating the object you do need to retrieve it with ?full_perms=true to see the full permissions.

There are quite a few tests to corroborate this as well.

**Comment by ndw** [comment]
Well, I'll try again. I don't see how my payload is incorrect and the UI definitely didn't show that the permissions had been applied.

**Comment by ndw** [comment]
User error. The payload wasn't `application/json`. *blush*
