### ISSUE TITLE
[BUG] When browser loses focus, "Drop files to begin upload" overlay is shown

### ISSUE THREAD

**Issue by matty-r** [paperless-ngx/paperless-ngx#4368]
### Description

When in any view other than the Dashboard, clicking out of the browser window (Firefox), the "Drop files to begin upload" overlay is shown. Sometimes it won't show until you click back into the window.

As per below screenshot, all I did was click out of the window.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/9965448/ccc63abd-c4c4-4404-99d7-b61a62d4ca83)

### Steps to reproduce

1. Login
2. Go to Documents view
3. Click outside the window

### Webserver logs

```bash
No relevant logs
```

### Paperless-ngx version

1.17.4

### Host OS

Arch Linux

### Installation method

Docker - official image

### Browser

Firefox 118.0.2

### Other

Client OS is also Arch Linux

**Comment by shamoon** [comment]
Cant reproduce, 1.17.4 has been out for over a month and no one has reported this. I also couldn't reproduce with the demo. 


https://github.com/paperless-ngx/paperless-ngx/assets/4887959/1f666866-a97c-4279-8333-187e360e2efe


https://github.com/paperless-ngx/paperless-ngx/assets/4887959/4bc9b983-12f7-497a-bb4e-0d5193c6b3c2



The only thing that should bring up the overlay is dragging a file over
https://github.com/paperless-ngx/paperless-ngx/blob/e4054d684c1b635f3ba2235410acb3aec9a16d24/src-ui/src/app/app.component.html#L4
https://github.com/paperless-ngx/paperless-ngx/blob/e4054d684c1b635f3ba2235410acb3aec9a16d24/src-ui/src/app/app.component.ts#L248

**Comment by matty-r** [comment]
Looks like it's an issue with Wayland - I can't reproduce the issue on X11.
