### ISSUE TITLE
[BUG] Adding a note doesn't update the "modified" parameter of a document

### ISSUE THREAD

**Issue by LeoKlaus** [paperless-ngx/paperless-ngx#4370]
### Description

I'm working on an app that relies on the "modified" attribute of a document to determine whether it was changed recently.

This works well unless the only change made to a document was the addition of a note, which case "modified" isn't updated.

### Steps to reproduce

1. Go to any document and add a note
2. Head to /api/documents/{id_of_document}/ and see "modified" unchanged

### Webserver logs

```bash
Not applicable
```

### Paperless-ngx version

1.17.4

### Host OS

Ubuntu Server

### Installation method

Docker - official image

**Comment by shamoon** [comment]
The document isn’t being modified, notes are stored in paperless

**Comment by LeoKlaus** [comment]
> The document isn’t being modified, notes are stored in paperless

Does the API feature any other endpoint to get new notes then?

**Comment by shamoon** [comment]
On second thought, modified is the paperless modified time. Let me look at this.

**Comment by shamoon** [comment]
Sorry for my initial misunderstanding, I think it is more consistent that adding / removing notes should affect the modified time, see #4374

**Comment by LeoKlaus** [comment]
Thanks for the update and quick fix!
