### ISSUE TITLE
[BUG] Layout jumps when suggestions appear on document edit

### ISSUE THREAD

**Issue by jabdoa2** [paperless-ngx/paperless-ngx#4406]
### Description

When editing a document paperless ngx will provide helpful suggestions for date or correspondent. Unfortunately, those appear after rendering the form and move the layout down. If you are changing tags this often makes you miss the correct form field.

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/557540/fa3c6527-7c0e-42f8-84d4-b68e8ee6cbfa)

### Steps to reproduce

1. Open a document which contains suggestions
2. Try to remove a tag quickly
3. You will likely miss the (x) of the tag because the layout moves the tag edit field

### Webserver logs

```bash
Frontend only
```

### Browser logs

```bash
Looks like `suggestions` is a separate http request.
```

### Paperless-ngx version

1.17.4

### Host OS

Ubuntu 22.04 x86

### Installation method

Docker - official image

### Browser

Firefox (probably not related)

### Configuration changes

Installation via Helm chart

**Comment by shamoon** [comment]
Suggestions are loaded on demand, after you open a doc, so yes, the layout moves down.

Putting a negative margin on the suggestions could help, but isnt really a durable solution e.g. on mobile if they run over two lines.

Im not really inclined to do anything about this.

**Comment by jabdoa2** [comment]
I agree to the mobile view (for people not using the app). Can we have an alternative layout for people with large screens (i.e. computer screens)? Some min height should make this much nicer. For me unexpected layout changes are really annoying. I can create a PR if that would help.
