### ISSUE TITLE
[BUG] Mails imported multiple times

### ISSUE THREAD

**Issue by tsia** [paperless-ngx/paperless-ngx#4471]
### Description

not sure if i'm holding it wrong but i think the behaviour was differently before.
i have 2 mail import rules targeting the same mailbox. the first one is only for processing messages with attachments and the second one is for importing mails as .eml. i set both rules to "Mark as read, don't process read mails". the first rule is correctly importing the attachments (if any) but my expectation was that the second rule shouldn't match because the first rule already processed the message. however it seems like every mail is also imported as .eml by the second rule

![image](https://github.com/paperless-ngx/paperless-ngx/assets/1386595/419ee8ed-a5e8-422c-b4f7-e2935c91704d)

![image](https://github.com/paperless-ngx/paperless-ngx/assets/1386595/3c2da74d-ab8b-466d-8b45-6c65702387fa)

it seems like this is because both jobs are added to the queue immediately and the message is only marked as read after the message has been processed

### Steps to reproduce

1. create 2 rules matching the same mailbox
2. set them so that they both would match the same message
3. see import of attachment *and* .eml

### Webserver logs

```bash
Sep 02 20:00:00 paperless celery[50132]: [2023-09-02 20:00:00,471] [INFO] [paperless_mail] Rule wurstsalat.attachments: Consuming attachment Kassenbon_2023-09-02_07.56.pdf from mail EDEKA - Vielen Dank für Ihr>
Sep 02 20:00:00 paperless celery[50132]: [2023-09-02 20:00:00,473] [WARNING] [py.warnings] /opt/paperless/venv/lib/python3.11/site-packages/celery/canvas.py:2286: CPendingDeprecationWarning: task_allow_error_c>
Sep 02 20:00:00 paperless celery[50132]: Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final d>
Sep 02 20:00:00 paperless celery[50132]:   warnings.warn(
Sep 02 20:00:00 paperless celery[76]: [2023-09-02 20:00:00,484] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[b8becced-c96c-4334-ab1e-ee490fdae7f4] received
Sep 02 20:00:00 paperless celery[50132]: [2023-09-02 20:00:00,605] [INFO] [paperless_mail] Rule wurstsalat.no attachments: Consuming eml from mail EDEKA - Vielen Dank für Ihren Einkauf from noreply@app.edeka.de
Sep 02 20:00:00 paperless celery[50132]: [2023-09-02 20:00:00,617] [WARNING] [py.warnings] /opt/paperless/venv/lib/python3.11/site-packages/celery/canvas.py:2286: CPendingDeprecationWarning: task_allow_error_c>
Sep 02 20:00:00 paperless celery[50132]: Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final d>
Sep 02 20:00:00 paperless celery[50132]:   warnings.warn(
Sep 02 20:00:00 paperless celery[76]: [2023-09-02 20:00:00,622] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[30a86a2a-ebbe-48ab-85c0-995e5b423890] received
```

### Paperless-ngx version

1.17.3

### Host OS

Debian 12

### Installation method

Bare metal

**Comment by stumpylog** [comment]
Mail rules only take their action following the successful import of an item (be that an attachment or the email itself).  So with two rules targeting the same folder, without filters in place, this could happen.  But that's expected, so this isn't a bug.

**Comment by tsia** [comment]
okay i understand that behaviour. is there a way to target only messages without attachments?

**Comment by stumpylog** [comment]
A scope of email only will process emails only, with embedded attachments included.

**Comment by tsia** [comment]
if by "email only" you mean "Process message as .eml" then i have it already set up like that (see second screenshot). and there are lots of emails that are processed that actually have attachments

**Comment by stumpylog** [comment]
That would likely be from the first rule, which is targeting the same folder, but processing attachments and inline attachments.
