### ISSUE TITLE
[BUG] very slow while open PDF file generated by ios in web

### ISSUE THREAD

**Issue by danfate** [paperless-ngx/paperless-ngx#4473]
### Description

It may take about 30 seconds to open this pdf online:
[2023-11-01 Paperless.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13226713/2023-11-01.Paperless.pdf)

<img width="1497" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/8059612/6b3e6ddc-ee00-4cbe-b4a7-5aae66320b70">

You can generate this kind of PDF file follow the steps instucted by [Apple](https://support.apple.com/en-gb/guide/iphone/iphc872c0115/ios#:~:text=Take%20a%20full%2Dpage%20screenshot&text=Do%20one%20of%20the%20following,button%20at%20the%20same%20time.)

There's also some error message is in docker log:
<img width="1173" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/8059612/dd34d762-34af-4255-ad3e-29aed5359352">

### Steps to reproduce

1.upload the pdf file as attached
2.open the pdf in web ui

### Webserver logs

```bash
please see description
```

### Paperless-ngx version

1.17.4

### Host OS

Linux Tower 6.1.36-Unraid x86

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
It loads in 82ms and renders less than a second after that.  Both qpdf and ghostscript report issues with the original, so the produced file is at least partially corrupt.  Either way, I can't reproduce this and PDFs with issues aren't something we can fix.

**Comment by danfate** [comment]
> It loads in 82ms and renders less than a second after that. Both qpdf and ghostscript report issues with the original, so the produced file is at least partially corrupt. Either way, I can't reproduce this and PDFs with issues aren't something we can fix.

Weird.
In my environment, it wills show blank and after about 30s showing the real content:
<img width="1479" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/8059612/653de4eb-c6f0-4ae0-ac87-4d909ecabe6b">

**Comment by stumpylog** [comment]
You can try with the brower's built-in PDF viewer as well.  It might be quicker to render

**Comment by shamoon** [comment]
You can try switching to the native pdf viewer in settings

**Comment by danfate** [comment]
Thanks, switching to the native pdf viewer in settings fix the problem.
Before switch to the native pdf viewer, i did some more test:
Macos with safari & firefox is ok
Windows with chrome is ok,
Macos with chrome & chrome Incognito without any plugin is not ok
