### ISSUE TITLE
[BUG] Webserver not starting on Raspberry 64-Bit

### ISSUE THREAD

**Issue by vFabse91** [paperless-ngx/paperless-ngx#4491]
### Description

Hi,

i've tried many different images but always have to problem to get paperless starting on an arm64 Raspberry PI Debian Installation. DB (postgres) and Redis is running, but webserver container is not starting.
Only have on raspberry but also with fresh installed it was not working.

### Steps to reproduce

Run 'bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"' on Raspberry 4 installed with Debian 12 (Bookwarm) 64-bit

### Webserver logs

```bash
docker logs paperless-webserver-1
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
exec /sbin/docker-entrypoint.sh: exec format error
```

### Paperless-ngx version

1.17 / latest

### Host OS

Debian 12 (Bookworm), Raspberry PI 4, 8GB, aarch64

### Installation method

Docker - official image

### Configuration changes

Nothing

**Comment by stumpylog** [comment]
I would suggest prune all images and making sure your Docker installation is up to date.  The pulling of the image is not up to us at all, that's all on Docker to get the correct image.

**Comment by stumpylog** [comment]
I've pulled `:latest`. `:1.17` and `:dev` on my Pi3 without issue.

**Comment by vFabse91** [comment]
@stumpylog sorry was my fault :-( after second reinstall and new Compose File everything is fine. Seems like i had a problem between 32 and 64 bit.
Thanks for help
