### ISSUE TITLE
[BUG] PDF preview missing some lines.

### ISSUE THREAD

**Issue by LarsK1** [paperless-ngx/paperless-ngx#4495]
### Description

The PDF preview is not complete. When opening the pdf in a regular pdf viewer
Paperless-NGX Preview
![image](https://github.com/paperless-ngx/paperless-ngx/assets/28981528/eee2adb2-ac80-4230-9d94-56c1b6c58863)
Original:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/28981528/0f32b072-e696-47b4-a0b4-ba6cbfadd86c)

### Steps to reproduce

Upload a pdf file
Open the edting mode.
View the preivew

### Webserver logs

```bash
-
```

### Browser logs

```bash
-
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Microsoft Edge, Chrome, Firefox

### Configuration changes

-

### Other

-

**Comment by LarsK1** [comment]
This is the document I used
[2023-11-01 Reventix GmbH SR0049178709_geschwärzt.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13248087/2023-11-01.Reventix.GmbH.SR0049178709_geschwarzt.pdf)

**Comment by shamoon** [comment]
From the issue template:

> Also, note that Paperless-ngx does not perform OCR itself, that is handled by other tools. Problems with OCR of specific files should likely be raised 'upstream', see https://github.com/ocrmypdf/OCRmyPDF/issues or https://github.com/tesseract-ocr/tesseract/issues

This might be a display issue though, you can try switching to the browser PDF viewer under settings.
