### ISSUE TITLE
[BUG] Cannot use accented character in mail rules filters

### ISSUE THREAD

**Issue by gbwebdev** [paperless-ngx/paperless-ngx#4526]
### Description

If I set up a mail rule that have accentuated characters in filters like on the following snapshot :
![image](https://github.com/paperless-ngx/paperless-ngx/assets/11390313/98a9469d-b055-4a70-ae8f-ef70281a8941)

Then I get errors during mail processing, and it fails.

### Steps to reproduce

1. Go to "Settings" > "Mail" and click the "Add Rule" button.
2. Set up a simple rule. Use a filter (for instance, the "Filter subject") with an accentuated character (for instance "touché !").
3. Run the `mail_fetcher` command. It will fail (even if there is no mail matching the rule).

### Webserver logs

```bash
# mail_fetcher
[2023-11-07 22:59:23,729] [ERROR] [paperless_mail] Rule XXXX.Avis d'échéance: Error while processing rule: UID command error: BAD [b'Could not parse command']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 501, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 568, in _handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 160, in fetch
    uids = tuple((reversed if reverse else iter)(self.uids(criteria, charset)))[limit_range]
  File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 119, in uids
    uid_result = self.client.uid('SEARCH', 'CHARSET', charset, encoded_criteria)
  File "/usr/local/lib/python3.9/imaplib.py", line 890, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/local/lib/python3.9/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.9/imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b'Could not parse command']
```

### Paperless-ngx version

1.17

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Ha, look what I found: https://github.com/ikvk/imap_tools/issues/88#issuecomment-766697329

**Comment by stumpylog** [comment]
Make sure your account has properly selected the character set to support accents and for your server's configuration.

Otherwise, I will point you to ikvk/imap_tools/issues/88.  Some servers simply can't handle searches with UTF8 characters.  I just tested it out with the account we use for some live email testing, and it searched without issue when criteria included accented characters.

**Comment by shamoon** [comment]
Indeed, this fails with Gmail but works fine with another account I have

Guessing OP is using Gmail

**Comment by gbwebdev** [comment]
I am indeed using Gmail.
So, for what I understand from [ikvk/imap_tools/issues/88](https://github.com/ikvk/imap_tools/issues/88), we just have to live with it 🤷‍♂️

**Comment by shamoon** [comment]
> I am indeed using Gmail. So, for what I understand from [ikvk/imap_tools/issues/88](https://github.com/ikvk/imap_tools/issues/88), we just have to live with it 🤷‍♂️

Unfortunately, it seems so. And as you can see any improvements to the situation would likely be handled upstream, not here.

**Comment by gbwebdev** [comment]
Thanks a lot anyway 🙂

**Comment by stumpylog** [comment]
It being GMail, I'd assume they don't want to fix it, so you have to log in from a browser and get tracked in all the different ways
