### ISSUE TITLE
[BUG] Long notes overflow out of its element

### ISSUE THREAD

**Issue by TotalLag** [paperless-ngx/paperless-ngx#4527]
### Description

It seems to be a minor issue of the element not having an `overflow: auto` styling. Only other fix is that bottom div (with the trash can) scrolls with it :) 

![image](https://github.com/paperless-ngx/paperless-ngx/assets/1744428/eb447823-c828-4b2b-a4ae-8e3db53fe65e)

### Steps to reproduce

1. Go into any document Notes section
2. Add a long note with several lines or paragraph
3. Watch it flow out with no scrollbars.

### Webserver logs

```bash
N/A. Front-end issue
```

### Paperless-ngx version

1.17.4

### Host OS

Linux

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Please remember to search first. See [#4286](https://github.com/paperless-ngx/paperless-ngx/issues/4286)

the fix will be in our next release

**Comment by TotalLag** [comment]
Thanks. Did not think to search for _closed_ issues.
