### ISSUE TITLE
[BUG] UI Notes field text overrun with large notes text. 

### ISSUE THREAD

**Issue by pkoerner81929** [paperless-ngx/paperless-ngx#4529]
### Description

When adding large amount of notes text to a document, text runs over the whole screen. 

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/17785334/478765b3-ebf9-4036-b06b-68011b5e7c29)

### Steps to reproduce

1. Goto edit mode on any doc.
2. Add text to Notes field with copy&paste
3. Save note
4. Leaving edit mode and re-enter still shows notes messed up.

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

1.17.4

### Host OS

Raspberry Pi aarch64

### Installation method

Docker - official image

### Browser

Firefox, Chrome

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/issues/4527#issuecomment-1802313006
