### ISSUE TITLE
[BUG] Rootless does not work due to permissions error

### ISSUE THREAD

**Issue by Royal2000H** [paperless-ngx/paperless-ngx#4531]
### Description

There have been many issues on the topic, all seem to have been closed for some reason despite no fix. I'm happy to link to those issues if helpful.

If following the [official guide](https://docs.paperless-ngx.com/setup/#docker_hub) to run rootless, I set `user: "1041"` in the compose.yaml.
I also have in the env file:
```
USERMAP_UID=1041
USERMAP_GID=65536
```

The docker container log is as follows (and these lines repeat until the container quits):

> Paperless-ngx docker container starting...
> Mapping UID and GID for paperless:paperless to 1041:65536
> usermod: Permission denied.
> usermod: cannot lock /etc/passwd; try again later.

If I remove the `user: "1041"` line from the compose.yaml, it runs just fine.

So it appears I can run paperless-ngx just fine, but not rootless. Seems others had the same issue without a fix. However, for security preferences, it would be preferable not to run on root.

### Steps to reproduce

See above

### Webserver logs

```bash
Paperless-ngx docker container starting...
Mapping UID and GID for paperless:paperless to 1041:65536
sermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
```

### Paperless-ngx version

1.17.4

### Host OS

Synology DSM 7.2 x86_64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
You need to set user id and group id to match in your user: portion.  You've only set the user id.

**Comment by Royal2000H** [comment]
Hi @stumpylog

According to @theEndBeta, you only need to set user, noted here (https://github.com/paperless-ngx/paperless-ngx/pull/1212#issuecomment-1209452399)

That said I tried both `user: 1041:65536` as well as `user: "1041:65536"` and neither works. Same exact error.

This is consistent with other discussions/issues about this that were also not solved here (below). You've closed the issue and marked it as "not a bug" but what you said does not work. Could you reopen the issue and undo the tag please? I have yet to see any comment of anyone who has been able to run this rootless by following the instructions in the guide. Perhaps if there is no fix and you still consider it "not a bug", then removing the rootless instructions from the instructions guide because it's inaccurate?

Some other related discussions and issues without resolution:
https://github.com/paperless-ngx/paperless-ngx/discussions/2460
https://github.com/paperless-ngx/paperless-ngx/discussions/4019
https://github.com/paperless-ngx/paperless-ngx/issues/4242
https://github.com/paperless-ngx/paperless-ngx/issues/4018
https://github.com/paperless-ngx/paperless-ngx/issues/1229
https://github.com/paperless-ngx/paperless-ngx/issues/4191

**Comment by Opisek** [comment]
Bug still present with no solution to be found. @stumpylog

**Comment by soerenschneider** [comment]
I'm also facing the same problem.
