### ISSUE TITLE
[BUG] Raspberry Pi 4 "no Python frame"

### ISSUE THREAD

**Issue by Yoanndp** [paperless-ngx/paperless-ngx#4539]
### Description

I cant setup Paperless on my RPI4 :
![image](https://github.com/paperless-ngx/paperless-ngx/assets/13591243/a47fbbdf-6dd1-4d70-9885-dd1c4fd94524)

### Steps to reproduce

1. Run `bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`
2. The process ends up with <no Python frame> error

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

latest

### Host OS

RPI4 arm64

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
That is an extremely low level error, not a paperless error.  The usual solutions are ensuring Docker is using the latest version, your system is up to date and you have a recent version of libseccomp2.

See [here](https://github.com/jonaswinkler/paperless-ng/discussions/1467) for one solution or [here](https://github.com/linuxserver/docker-papermerge/issues/4), etc.
