### ISSUE TITLE
[BUG] {doc_pk} doesn't work in file names

### ISSUE THREAD

**Issue by julichan** [paperless-ngx/paperless-ngx#4546]
### Description

I tried to use the variable {doc_pk} in document path variables as stated in documentation on https://docs.paperless-ngx.com/advanced_usage/#file-name-handling but it ends with "Invalid variable detected" error.

### Steps to reproduce

1. Go to 'Storage Path'
2. Create new storage path
3. Use {doc_pk} in path
4. Save

### Webserver logs

```bash
none
```

### Paperless-ngx version

1.17.4

### Host OS

DSM 7.2

### Installation method

Docker - official image

### Browser

Edge

**Comment by stumpylog** [comment]
This is basically not possible.  The area of code has not seen any changes for a very long while.  `doc_pk` has been supported since this project started.

**Comment by julichan** [comment]
Well i ve been using paperless-ngx since 1.16 and now got 1.17.4 what could be causing this error?

**Comment by stumpylog** [comment]
Indeed, a storage path like `{created_year}/{correspondent}/{created}-{title}-{doc_pk}` works just fine.  As does `{doc_pk}`

**Comment by julichan** [comment]
![image](https://github.com/paperless-ngx/paperless-ngx/assets/27727780/c3294c8d-afc2-4ee0-9847-4771455bf1c6)

**Comment by julichan** [comment]
Could it be related to language ?

**Comment by stumpylog** [comment]
There's no translation

**Comment by shamoon** [comment]
This is a bug we already fixed, hasn't been released yet. Please do try searching first in the future

https://github.com/paperless-ngx/paperless-ngx/pull/4179

**Comment by julichan** [comment]
Ha sorry, i only took a look at open bugs, my bad.
