### ISSUE TITLE
Login to demo not working (changed credentials)

### ISSUE THREAD

**Issue by tooomm** [paperless-ngx/paperless-ngx#4551]
### Description

The default credentials that are named there and even prefilled do not work:
<img width="322" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/9874850/156fe41b-adf7-4063-8687-91f611022246">

Probably somebody changed them.

Can this be prevented somehow? This happend before and is a bit annoying :)

### Steps to reproduce

1. Go to demo page
2. Try to login

### Webserver logs

```bash
None
```

### Paperless-ngx version

Demo

### Host OS

Demo

### Installation method

Docker - official image

### Browser

Edge, Firefox

**Comment by shamoon** [comment]
I agree thats annoying, people do stuff.

The demo data is automatically purged every once-in-a-while, it will fix itself if not already.
