### ISSUE TITLE
default login pass

### ISSUE THREAD

**Issue by daniel-lo** [paperless-ngx/paperless-ngx#456]
Hi .. I just installed this docker from docker hub:
sudo docker pull lippertsweb/paperless-ngx
and I see the login page .. but I cannot find information about the default login.
For paperless-ng it was admin, admin .. but here it seems different.
Could anyone get me started please.

If there is  a different docker I should use please let me know.

**Comment by shamoon** [comment]
Please see https://paperless-ngx.readthedocs.io/en/latest/setup.html#install-paperless-from-docker-hub, specifically item 7, you need to create a superuser . Alternatively https://paperless-ngx.readthedocs.io/en/latest/configuration.html#hosting-security `PAPERLESS_ADMIN_USER`

**Comment by tribut** [comment]
Also note that our official image is ghcr.io/paperless-ngx/paperless-ngx:latest, but this is also in the docs, of course.

**Comment by daniel-lo** [comment]
Thanks guys .. I am using the proper image now but when I enter the command from intem 7 mentioned above I get this error:

       Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?
        Supported filenames: docker-compose.yml, docker-compose.yaml

I work by recipies .. so no linux expertise on this side of the keyboard.
