### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by Kunsi** [paperless-ngx/paperless-ngx#4562]
### Description

In https://docs.paperless-ngx.com/setup/#bare_metal Step 8, you mention installing the dependencies from `requirements.txt`, but that file is not present in the repository:

```
[home.paperless][root@/opt/paperless/src] > find -name requirements.txt
[home.paperless][root@/opt/paperless/src] >
```

I'm running git d3b5de3fadd575a7af60aac71c7ab691feea1dd3, aka v1.17.4

### Steps to reproduce

1. Clone git repository
2. Try to install `requirements.txt`
3. `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

### Paperless-ngx version

1.17.4

### Host OS

debian bookworm

### Installation method

Bare metal

**Comment by shamoon** [comment]
The file is generated and included in our release packages, step 5

**Comment by Kunsi** [comment]
Can you provide instructions on how to generate the `requirements.txt` then?

Step 5 explicitely lists cloning the git repository as an option:

> Optional: If you cloned the git repo, you will have to compile the frontend yourself, see [here](https://docs.paperless-ngx.com/development#front-end-development) and use the build step, not serve.

**Comment by shamoon** [comment]
`pipenv requirements > requirements.txt`
or just download the archive
or install the dependencies with pipenv
