### ISSUE TITLE
Push to official docker hub

### ISSUE THREAD

**Issue by shamoon** [paperless-ngx/paperless-ngx#457]
### Discussed in https://github.com/paperless-ngx/paperless-ngx/discussions/290

<div type='discussions-op-text'>

<sup>Originally posted by **lippoliv** March 12, 2022</sup>
Hi all,
today I switched my NAS from [linuxserver/paperless-ng](https://hub.docker.com/r/linuxserver/paperless-ng) to paperless-ngx. Because my Synology (currently) just supports official docker hub (or I did not research enough), I now [pushed paperless-ngx myself](https://hub.docker.com/r/lippertsweb/paperless-ngx).

Is there some plan to push images to official docker hub in the future?</div>

Schnuffle has kindly offered to work on this when he can, if others have time please chime in.

**Comment by marcogiorgio** [comment]
Hi,
I have a Synology as well and I installed without issues Paperless-ngx.  If you manage your containers by using docker-compose and .yml files you can install Paperless without issues... I strongly recommend you to not using the GUI because you incur in these limitations.

**Comment by TheDarthFather** [comment]
> ### Discussed in #290
> Originally posted by **lippoliv** March 12, 2022 Hi all, today I switched my NAS from [linuxserver/paperless-ng](https://hub.docker.com/r/linuxserver/paperless-ng) to paperless-ngx. Because my Synology (currently) just supports official docker hub (or I did not research enough), I now [pushed paperless-ngx myself](https://hub.docker.com/r/lippertsweb/paperless-ngx).
> 
> Is there some plan to push images to official docker hub in the future?
> 
> Schnuffle has kindly offered to work on this when he can, if others have time please chime in.

You can go to your Synology DSM in the Docker -> Registry - Settings and add additional sources

**Comment by Mirio** [comment]
Hi,
Do you need help with this? I'm available if you want.
Probably we need to implement a GitHub action to avoid the docker hub account limitation for open source projects.
Regards,

**Comment by shamoon** [comment]
I would defer to @schnuffle on that question, especially now that our ci process has changed significantly, hopefully this is easier. But not sure how available he is at the moment.

We do have a hub account setup already btw.

**Comment by lippoliv** [comment]
> You can go to your Synology DSM in the Docker -> Registry - Settings and add additional sources

This did not work for me, for whatever reason.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/8b798013c170267a56d9b797f9ff9db61936c2bc
