### ISSUE TITLE
[BUG] Missing small translation string - v2.0.0 BETA-RC1 Bug

### ISSUE THREAD

**Issue by darkobg79** [paperless-ngx/paperless-ngx#4594]
### Description

Translation string is missing for word "Expires:" for feature: Share links.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/16548358/57fc3fdb-4d03-4cc7-81d5-b5e31d20e782)

### Steps to reproduce

See picture...

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.00 beta rc1

### Host OS

Docker

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Thanks
