### ISSUE TITLE
[BUG] Custom Field is missing on new

### ISSUE THREAD

**Issue by slydlake** [paperless-ngx/paperless-ngx#4600]
### Description

So maybe I did not understand the custom fields correctly. But I intend that, when I created a custom field, that all new documents have this field.

Is it really necessary to add this field to every document? Is there a possibility to add this to templates or something else?

Thank you very much for your great work!

### Steps to reproduce

1. created a custom field
2. imported a new document
3. only default fields are there

### Webserver logs

```bash
no
```

### Paperless-ngx version

2.0.0-beta.rc1

### Host OS

raspberry pi arm64

### Installation method

Docker - official image

### Browser

safari

**Comment by shamoon** [comment]
No that’s not possible yet
