### ISSUE TITLE
[BUG] The display issue in French in settings

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4609]
### Description

With beta-rc1, In settings, access rights

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/63ab9b9b-a7bf-4912-b009-dfa16b6b8c02)

### Steps to reproduce

1. Settings
2. Users rights

### Webserver logs

```bash
nothing
```

### Paperless-ngx version

beta-rc1

### Host OS

Fedora

### Installation method

Docker - official image

### Browser

Firefox 119.0.1

**Comment by shamoon** [comment]
Thanks

Closed in branch by #4612
