### ISSUE TITLE
[BUG] PAPERLESS_FILENAME_DATE_ORDER=YMD not detecting YYYY-MM-DD

### ISSUE THREAD

**Issue by lejando** [paperless-ngx/paperless-ngx#461]
**Describe the bug**
I have lots of Documents with filenames following the pattern "YYYY-MM-DD Title[Tag1 Tag2].pdf" like "2012-11-25 Rechnung Firma[Haus Küche].pdf".  After setting `PAPERLESS_FILENAME_DATE_ORDER=YMD` no document has the right date.

**To Reproduce**
1. Set `PAPERLESS_FILENAME_DATE_ORDER=YMD`
2. Upload document named "2012-11-25 Rechnung Firma[Haus Küche].pdf"
3. Expect to see a "Date created" from somewhere inside the document at best, but date added most of the time, not the one from the filename. 

**Expected behavior**
Acc. to the [Documentation of paperless-ngx](https://paperless-ngx.readthedocs.io/en/latest/configuration.html#software-tweaks) and of [DateParser](https://dateparser.readthedocs.io/en/latest/settings.html#date-order) i would expect a "Date created" of 25th of November 2012.

**Relevant information**
 - Host OS of the machine running paperless: Debian 11 amd64 on Proxmox LXC
 - Browser : Safari
 - Version 1.6.0
 - Installation method: docker-compose using [this guide](https://paperless-ngx.readthedocs.io/en/latest/setup.html#install-paperless-from-docker-hub-using-the-installation-script)
 - docker-compose.env (YMD in filenames, DMY inside documents):
 
 ```
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_SECRET_KEY=******
PAPERLESS_OCR_LANGUAGES=deu+eng
PAPERLESS_FILENAME_DATE_ORDER=YMD
PAPERLESS_DATE_ORDER=DMY
```

**Comment by Tooa** [comment]
Hi,

I tried to reproduce your issue with the configuration below. I created a file named `2012-11-25 Rechnung Firma[Haus Küche].pdf` and copied it to the consume directory. The result looks fine to me?

![image](https://user-images.githubusercontent.com/5375334/160230714-b7c38d51-ac35-4bec-b951-17096fa580a7.png)

I assume there is a problem with your docker setup. Can you please verify your container has the correct environment variables applied?

```
$ docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED         STATUS                   PORTS                                       NAMES
af49a9251fd8   ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   paperless_webserver_1
$ docker exec -it af49a9251fd8 bash
> echo $PAPERLESS_FILENAME_DATE_ORDER
YMD
> echo $PAPERLESS_DATE_ORDER
DMY
```

One thing that is odd though is a warning in the logs. We may have to look into this. However, it shouldn't cause any issues.
```
webserver_1  | [2022-03-26 08:02:56,353] [INFO] [paperless.consumer] Consuming 2012-11-25 Rechnung Firma[Haus Küche].pdf
webserver_1  | /usr/local/lib/python3.9/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
webserver_1  |   date_obj = stz.localize(date_obj)
```

docker-compose.yml
```bash
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379

volumes:
  data:
  media:
  redisdata:
```

docker-compose.env
```
PAPERLESS_OCR_LANGUAGES=deu+eng
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_FILENAME_DATE_ORDER=YMD
PAPERLESS_DATE_ORDER=DMY
```

**Comment by Tooa** [comment]
Hi,

I could not reproduce the issue with the configuration below. I created a document named `2012-11-25 Rechnung Firma[Haus Küche].pdf` and copied it to the consume directory. The result looks fine to  me?

![image](https://user-images.githubusercontent.com/5375334/160231375-13db40d8-25cb-4cf4-a3d3-8f5a477e1110.png)

I guess there is a problem with your docker setup. Can you please verify that your container has the correct environment variables applied?

```bash
$ docker ps

➜  compose git:(doc-unraid-template) ✗ docker ps
CONTAINER ID   IMAGE                                        COMMAND                  CREATED         STATUS                   PORTS                                       NAMES
af49a9251fd8   ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp   paperless_webserver_1
022e63465197   redis:6.0                                    "docker-entrypoint.s…"   2 minutes ago   Up 2 minutes             6379/tcp                                    paperless_broker_1
$ docker exec -it af49a9251fd8 bash
> echo $PAPERLESS_FILENAME_DATE_ORDER
YMD
> echo $PAPERLESS_DATE_ORDER
DMY
```

Apart from that we have to look into the following warning:
```bash
webserver_1  | [2022-03-26 09:14:35,179] [INFO] [paperless.consumer] Consuming 2012-11-25 Rechnung Firma[Haus Küche].pdf
webserver_1  | /usr/local/lib/python3.9/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
webserver_1  |   date_obj = stz.localize(date_obj)
```

However, it seems that this is a problem with `dateparser` (https://github.com/scrapinghub/dateparser/issues/1013)

docker-compose.yml
```bash
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379


volumes:
  data:
  media:
  redisdata:
```

docker-compose.env
```bash
PAPERLESS_OCR_LANGUAGES=deu+eng
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_FILENAME_DATE_ORDER=YMD
PAPERLESS_DATE_ORDER=DMY

```

**Comment by Tooa** [comment]
The warning found will be resolved with https://github.com/paperless-ngx/paperless-ngx/pull/497

**Comment by lejando** [comment]
Hello,
thank you for that extensive reply!

The problem were the evironment variables. They were not set. I expect i issued `docker-compose restart` and not the required `docker-compose down` and  `docker-compose up -d` after altering the docker-compose.env file.

Thank you again for the hint to check the environment variables from inside the container.

Keep up that great work!
