### ISSUE TITLE
[BUG] Erroneous translation

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4610]
### Description

"In the 'File Processing' section, under the 'Successful' tab. The translation of the 'Effacer la sélection' button is not appropriate. The action corresponds to deselecting the entire list, while the translation implies the action is deleting the files from the list."

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/a7a5be6e-9acf-4454-86eb-9e41c5d12a5e)

### Steps to reproduce

1. go to File Processing'
2. tab successful

### Webserver logs

```bash
nothing
```

### Paperless-ngx version

beta-rc1

### Host OS

Fedora

### Installation method

Docker - official image

### Browser

Firefox 119.0.1

**Comment by shamoon** [comment]
Thanks, translations are handled at Crowdin https://crwd.in/paperless-ngx
