### ISSUE TITLE
[BUG] Erroneous translation

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4611]
### Description

"In the 'File Processing' section, under the 'Successful' tab, the translation of the 'Ignorer la sélection' button is not suitable. The action actually corresponds to deleting the selected lines. The button should be translated as 'Supprimer la sélection'."

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/2733900f-c819-4657-b087-1c541af47d96)

### Steps to reproduce

1.  go to File Processing'
2. tab successful

### Webserver logs

```bash
nothing
```

### Paperless-ngx version

beta-rc1

### Host OS

Fedora

### Installation method

Docker - official image

### Browser

Firefox 119.0.1

**Comment by shamoon** [comment]
Thanks, translations are handled at crowdin https://crwd.in/paperless-ngx
