### ISSUE TITLE
[BUG] Action buttons spanning across two lines

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4613]
### Description

"On the 'Documents' page, when a document is selected, the list of action buttons spans across two lines."

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/5ff27b78-9b3c-4759-933d-cf49c9120825)

### Steps to reproduce

1. go to "Documents" pages

### Webserver logs

```bash
nothing
```

### Paperless-ngx version

beta-rc1

### Host OS

Fedora

### Installation method

Docker - official image

### Browser

Firefox 119.0.1

**Comment by shamoon** [comment]
Some languages have words longer than others, not much we can do about this one according to screen width. The buttons flow
