### ISSUE TITLE
[BUG] The display issue in French Models

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4615]
### Description

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/4f2c1904-259e-47fc-b628-2e37c1900c47)

### Steps to reproduce

1. Go to Models page
2. Create a new model

### Webserver logs

```bash
nothing
```

### Paperless-ngx version

beta-rc1

### Host OS

Fedora

### Installation method

Docker - official image

### Browser

Firefox 119.0.1

**Comment by shamoon** [comment]
#4616
