### ISSUE TITLE
[BUG] New view not visible in sidebar in v2.0.0-beta.rc1

### ISSUE THREAD

**Issue by Philippe-M** [paperless-ngx/paperless-ngx#4618]
### Description

Hello,

I created a new view that combines two labels, and when saving the view, I selected 'Show in sidebar.' After clicking the 'Save' button, I see the sidebar move, but the view name does not get saved. To see the view in the sidebar, it is necessary to refresh the page.

Create view
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/3fcdbb41-77f4-458a-98a9-32f18f5a08ce)

Before reload
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/89e03a6b-d81e-403d-8c08-b86d9f88f915)

After reload
![image](https://github.com/paperless-ngx/paperless-ngx/assets/4558101/2032b052-5da2-4938-9f6e-e6764973a50d)

### Steps to reproduce

1. create view
2. reload page

### Webserver logs

```bash
nothing
```

### Paperless-ngx version

beta-rc1

### Host OS

Fedora

### Installation method

Docker - official image

### Browser

Firefox 119.0.1

**Comment by shamoon** [comment]
Closed in branch by #4619

Thanks, a good catch
