### ISSUE TITLE
PDF wird nicht eingelesen

### ISSUE THREAD

**Issue by nektar86** [paperless-ngx/paperless-ngx#4638]
### Description

Bei einigen PDFs bekomme ich immer folgende Fehlermeldung.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 4624.`

Woran kann das liegen?

### Steps to reproduce

1. Datei in den Browser ziehen

### Webserver logs

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 4624.
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 

### Installation method

Docker - official image

### Browser

Opera, Safari

### Configuration changes

docker-compose.yml

**Comment by shamoon** [comment]
This repository is in English, if possible please use that. This is a resource issue, not a paperless bug
