### ISSUE TITLE
[BUG] docker-compose v1 issues

### ISSUE THREAD

**Issue by colfes** [paperless-ngx/paperless-ngx#4649]
### Description

When running the install script as specified in https://paperless.readthedocs.io/en/latest/setup.html via docker-compose run --rm webserver createsuperuser, the script fails iff PAPERLESS_OCR_ROTATE_PAGES is set to true in the docker-compose.yml.

### Steps to reproduce

1. Create fresh installation via docker compose file, Don't specify admin username or password in the compose file. Specify PAPERLESS_OCR_ROTATE_PAGES: true, as described in https://docs.paperless-ngx.com/configuration/. (I did PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD 8)
2. pull and up -d, wait. Start will be successful and web page will be responding.
3. try to create the user via docker-compose run --rm webserver createsuperuser
4. ERROR: The Compose file './docker-compose.yml' is invalid because:
services.webserver.environment.PAPERLESS_OCR_ROTATE_PAGES contains true, which is an invalid type, it should be a string, number, or a null

### Webserver logs

```bash
no relevant entry.
```

### Paperless-ngx version

1.17.4

### Host OS

Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux

### Installation method

Docker - official image

### Configuration changes

described above

**Comment by stumpylog** [comment]
`docker-compose` is quite old at this point.  `docker compose` is the only method they support at this point.

**Comment by colfes** [comment]
I guess the paperless.readthedocs.io is not your responsibility, but https://docs.paperless-ngx.com/setup/#docker_hub also lists docker-compose.

**Comment by stumpylog** [comment]
Correct, we don't use read the docs.  I think that's the original project.  Definitely some changes since then
