### ISSUE TITLE
PDF range request not working with default file loader

### ISSUE THREAD

**Issue by redrubytech** [paperless-ngx/paperless-ngx#4672]
### Description

Hi
Am trying to integrate ngx-extended-pdf-viewer to have a book mode view within paperless-ngx and it is working fine too.
Am able to load the documents in book mode.
The problem is the document is viewable only after the whole file is downloaded. To avoid this and to have a better user experience am trying to implement "range based" pdf content request in paperless-ngx.
I have tested ngx-extended-pdf-viewer sperately and verified that it supports range based pdf content request.

But when i try to implement the same within paperless-ngx , it is not allowing the range request.
Is there any specific settings / modifier / class blocking this range request feature.
I tried troubleshooting, but couldnt find why it is not working only when served from the integrated django application.

I am modifying the class responsible for default preview option.

### Steps to reproduce

Integration of ngx-extended-pdf viewer.

### Webserver logs

request.header print: 
-------------------------------------
{'Content-Length': '', 'Content-Type': 'text/plain', 'Host': '172.16.16.113:5000', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36', 'Accept': '*/*', 'Referer': 'http://172.16.16.113:5000/documents?sort=created&reverse=1&page=1', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,en;q=0.9', 'Cookie': 'csrftoken=NwOXCMVp73N95RH6sUVEqQ9K0MPisVEe; sessionid=03asfgn57xkk6rj8f0tsfmr4hnh6xups'}

### Browser logs

response headers
-------------------------------------------
HTTP/1.1 200 OK
Date: Fri, 24 Nov 2023 05:10:35 GMT
Server: WSGIServer/0.2 CPython/3.10.12
Content-Type: application/pdf
Content-Disposition: inline; filename="0000092.pdf"
Access-Control-Expose-Headers: Accept-Ranges
Access-Control-Allow-Headers: Accept-Ranges,range
Accept-Ranges: bytes
Access-Control-Allow-Origin: http://localhost:4200
X-Frame-Options: ALLOW-FROM HTTP://172.16.16.113:5000/
X-Api-Version: 3
X-Version: 1.17.4
Vary: Accept-Language, origin, Cookie, Accept-Encoding
Content-Language: en-gb
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Cross-Origin-Opener-Policy: same-origin
Content-Encoding: gzip
Connection: close

request headers
-----------------------------------
GET /preview-document/94/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en;q=0.9
Connection: keep-alive
Cookie: csrftoken=NwOXCMVp73N95RH6sUVEqQ9K0MPisVEe; sessionid=03asfgn57xkk6rj8f0tsfmr4hnh6xups
Host: 172.16.16.113:5000
Referer: http://172.16.16.113:5000/documents?sort=created&reverse=1&page=1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
### Paperless-ngx version

1.17.4

### Host OS

ubuntu 22.04

### Installation method

Bare metal

**Comment by shamoon** [comment]
Mate, from the template:

> Please remember: issues are for bugs
> That is, something you believe affects every single user of Paperless-ngx, not just you. If you're not sure, start with one of the other options below.
