### ISSUE TITLE
[BUG] Web Server not starting after 2.0.0 upgrade

### ISSUE THREAD

**Issue by xinput** [paperless-ngx/paperless-ngx#4694]
### Description

After updating to new paperless version 2.0.0 websever seems not to come up, while all other containers work fine an.
In the logs I can see that paperless is also starting consuming documents, just the webserver seems to have an issue.
![Screenshot 2023-11-29 065404](https://github.com/paperless-ngx/paperless-ngx/assets/11652924/d46f02c5-0ed2-4021-b1d7-f916df3aaa0d)

### Steps to reproduce

1. pull new image via docker compose
2. bring up stack
3. wait a few seconds
4. check logs

### Webserver logs

```bash
/usr/local/lib/python3.11/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.

  warnings.warn(
```

### Paperless-ngx version

2.0.0

### Host OS

Debian 11 

### Installation method

Docker - official image

**Comment by shamoon** [comment]
I cant reproduce this and the release was tested in the beta version for a couple of weeks. Have you tried basics like removing the container and re-creating it, etc.?

**Comment by xinput** [comment]
Yes tried this indeed several times without success.. but nevermind. Don't know what exactly happened but i fixed it by just creating a new directory, copy over my docker compose and env files, bringing up the stack with no data in it, then shutting it down and bringig up my usual stack including my files again which then worked.

sorry about that. Didn't came up with that idea before.

**Comment by flecmart** [comment]
Hi,

I had the exact same problem after upgrading from 1.7.4 and I solved it by resetting brower cache. Just a hint for others that might run into the problem.

**Comment by lotharsm** [comment]
Same here when upgrading from 1.7.4 to 2.0.0, but clearing the browser cache fixed it. No issues from 2.0.0 to 2.0.1 though.

Maybe this could be pointed out in the GitHub release notes for 2.0.1?
