### ISSUE TITLE
[BUG] Archive serial number seems to be mandatory after upgrade to 2.0.0

### ISSUE THREAD

**Issue by atemp** [paperless-ngx/paperless-ngx#4721]
### Description

After upgrading to 2.0.0 (docker based) the "SAVE" button is not clickable anymore unless an archive serial number is set. In the previous version this was not the case. Since documents that e.g. came in via email might not be archived as real paper, it would be nice if the serial number field would be optional like before.

### Steps to reproduce

1. log into paperless instance after upgrade to 2.0.0
2. access a random document that got no ASN
3. try to modify something and keep ASN empty
4. save button is not clickable

### Webserver logs

```bash
probably unrelevant?
```

### Paperless-ngx version

2.0.0

### Host OS

docker container on NixOS 23.11 host

### Installation method

Docker - official image

### Browser

Firefox 120.0 (64-bit)

**Comment by atemp** [comment]
went away magically after restarting the host, it works now as it should. sorry.

**Comment by shamoon** [comment]
I can’t reproduce this and it wasn’t changed (at least not intentionally). Can you provide the actual error response?

**Comment by shamoon** [comment]
Ah, ok
