### ISSUE TITLE
[BUG] PDF files with existing text layers are still sent to OCRmyPDF

### ISSUE THREAD

**Issue by noseshimself** [paperless-ngx/paperless-ngx#4724]
### Description

Input files document containing a working text layer (as in pdftotext and a number of GUI tools can access it) are nevertheless sent to ocrmypdf (and failing due to other circumstances which have to worked on by ocrmypdf maintainers).

This is the environment inside the docker container:

root@dms-zner:/usr/src/paperless/src# env | grep OCR
PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=10
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_OCR_DESKEW=true
PAPERLESS_OCR_ROTATE_PAGES=true
PAPERLESS_OCR_OUTPUT_TYPE=pdfa-3
PAPERLESS_OCR_CLEAN=clean-final
PAPERLESS_OCR_MODE=skip

### Steps to reproduce

1. Throw a file into the consumption directory.
2. Wait.
3. See logs.

### Webserver logs

```bash
[2023-11-30 03:28:30,976] [INFO] [paperless.consumer] Consuming 20170509 Pelikan M1000 Raden Royal Gold.pdf
[2023-11-30 03:28:30,980] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-11-30 03:28:30,982] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-11-30 03:28:31,019] [DEBUG] [paperless.consumer] Parsing 20170509 Pelikan M1000 Raden Royal Gold.pdf...
[2023-11-30 03:28:31,345] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxwbyv40sf/2017050
[2023-11-30 03:28:32,125] [ERROR] [paperless.consumer] Error occurred while consuming document 20170509 Pelikan M1000 Raden Royal Gold.pdf: ColorConversionNeededE
--color-conversion-strategy to convert to a common color space
```

### Paperless-ngx version

2.0.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

any

**Comment by shamoon** [comment]
Please search before opening an issue. https://github.com/paperless-ngx/paperless-ngx/issues/4702

**Comment by noseshimself** [comment]
I have the feeling that we're still not talking about the same thing unless I'm fundamentally misunderstanding you:

- I put a (new and never seen before!) file into the input funnel.
- The file already has a valid text layer.
- I specified PAPERLESS_OCR_MODE=skip
- Paperless is sending it to OCRmyPDF

I don't want the text layer to be replaced on the DMS-provided version (because it can only get worse  and in the worst case it is destroying information that is not part of the visible document like embedded XML/EDIFACT data).

I actually do want to keep a completely untouched version of any file put into the DMS so I also specified PAPERLESS_OCR_SKIP_ARCHIVE_FILE=never in the latest iteration (just to be safe).

Did I misunderstand "skip", did I misspell it? I don't really see a good reason to not have "skip" as default option there.

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/blob/04feeaefabf3c475d689101519ea7d2a32ab2d17/src/paperless_tesseract/parsers.py#L196-L197 --> https://ocrmypdf.readthedocs.io/en/latest/advanced.html#when-ocr-is-skipped

**Comment by noseshimself** [comment]
So this *should* work as expected. I'll dig around in OCRmyPDF to see where my XRechnung is being eaten...

**Comment by noseshimself** [comment]
While we are already discussing questions regarding OCRmyPDF:

After throwing about 13000 assorted documents at Paperless I found a number of these messages in the log

```
Error occurred while consuming document 20201210 2020-12-10_Antrag_15-40 (Kfz-Versicherung).pdf: DigitalSignatureError: Input PDF has a digital signature. OCR would alter the document, invalidating the signature.
```

Could we agree on not treating this as an error as long as the next processing step is finding a valid text layer inside the file? pdftotext clearly shows a valid text in all the files I tested.

**Comment by noseshimself** [comment]
> No signatures were harmed in my case but I assume that this is not a proper solution for all situations.

That's the most important part as removing them would be "a substantial modification of the original document" and you know... Taxes. Germany.
