### ISSUE TITLE
[BUG] docker-compose pull not working on raspberry pi 3

### ISSUE THREAD

**Issue by CalyPhornia** [paperless-ngx/paperless-ngx#4730]
### Description

Hello,
i want to update my paperless-ngx to 2.0.1 and become an error "no matching manifest for linux/arm/v7 in the manifest list entries".
Can anyone help me or is the new version incompatible with raspberry pi 3?
Greets

### Steps to reproduce

docker-compose down
docker-compose pull

### Webserver logs

```bash
no matching manifest for linux/arm/v7 in the manifest list entries
```

### Paperless-ngx version

1.17.4

### Host OS

Raspberry Pi 3 Model B

### Installation method

Docker - official image

**Comment by shamoon** [comment]
Please review the release notes https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.0.0

> Breaking: Remove ARMv7 building of the Docker image @stumpylog (https://github.com/paperless-ngx/paperless-ngx/pull/3973)

Also: https://github.com/paperless-ngx/paperless-ngx/discussions/3940

**Comment by stumpylog** [comment]
And/Or #4726.  They really did a weird thing there.
