### ISSUE TITLE
[BUG] Drag and Drop Text leads to Drag Info gets stuck

### ISSUE THREAD

**Issue by sandmann91** [paperless-ngx/paperless-ngx#4766]
### Description

If you mark text and drag it around, it:

1. Shows the overlay for Drag & Drop. In my opinion, this should not happen because you can't drop text. I looked it up, and there seems to be a way to determine whether you're dragging a file or not ([Link](https://stackoverflow.com/questions/6848043/how-do-i-detect-a-file-is-being-dragged-rather-than-a-draggable-element-on-my-pa)).
2. Sometimes the message gets stuck, and you need to reload the page.

### Steps to reproduce

This can be done by marking any text on the website, not only with text from a document.
I know the behavior to reproduce is not quite normal, but this happened to me while doing normal stuff like marking text and copying it to the inputs. To clarify: I do not drag & drop text into the input boxes. I would do it with Ctrl+C and Ctrl+V. If you work quickly, it sometimes happens that you still hold your mouse down while moving. This can lead to this issue in 'normal work'.

1. Open a document (or mark any text on the page).
2. Quickly drag and drop the text to random places.

Sometimes it takes a bit.

https://github.com/paperless-ngx/paperless-ngx/assets/14318498/d59843ab-853a-4075-af30-32357c7d01ef

Sometime on first try

https://github.com/paperless-ngx/paperless-ngx/assets/14318498/53ce8075-c35c-4350-8ca8-4b260540622c

### Webserver logs

```bash
I dont think browser logs will help as this seems to be a front end issue
```

### Browser logs

```bash
no resource to load, early way out
main.js:3 no resource to load, early way out
2pdf.worker.min.js:22 Warning: TT: undefined function: 21
main.js:3 Deprecated API usage: The `enhanceTextSelection` functionality will be removed in the future.
```

### Paperless-ngx version

2.0.1

### Host OS

Ubuntu 23.10

### Installation method

Docker - official image

### Browser

Chrome 119.0.6045.200, Windows 11

**Comment by shamoon** [comment]
I cant really tell what youre dragging there. Nothing in that PDF should be draggable so I dont know why the browser is triggering that. I, for example, cant reproduce it on chromium (not windows)

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/1245c906-de55-405e-9bb4-be94103a4d0b

But I think the idea of filtering out non file-drops is a good one, though I am a little worried about consistency across browsers.

It's currently building ( https://github.com/paperless-ngx/paperless-ngx/actions/runs/7069131512 ) but if you want to try out the image `feature-fix-4766` that would be helpful. NOTE: that is based on our `dev` branch so it does have some other changes in it, I wouldn't use that over your production data.

**Comment by shamoon** [comment]
Ah, I see its a 'long press' on Mac, yea I think that should fix it
