### ISSUE TITLE
[BUG] /api/remote_version/ returns version 0.0.0

### ISSUE THREAD

**Issue by astubenbord** [paperless-ngx/paperless-ngx#4769]
### Description

After upgrading to v2.0.1, the endpoint /api/remote_version/ does not return the expected version code (2.0.1). 

The issue has also been reported by other users (see https://github.com/astubenbord/paperless-mobile/issues/314).

### Steps to reproduce

1. Go to <your-host>/api/remote_version/
2. Observe response

### Webserver logs

```bash
No notable logs (just startup script stuff)
```

### Paperless-ngx version

2.0.1

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

**Comment by astubenbord** [comment]
Addition: The ` X-Version` header seems to be set correctly.

**Comment by shamoon** [comment]
Darn, looks like just a typo https://github.com/paperless-ngx/paperless-ngx/blob/6a78dde3e3b2302cb8e9cac26996561dc07476d4/src/documents/views.py#L1161

should be easy to fix
