### ISSUE TITLE
[BUG] Images with alpha layer not recognized as duplicates

### ISSUE THREAD

**Issue by akumiszcza** [paperless-ngx/paperless-ngx#4775]
### Description

If I upload the same PDF twice to paperless-ngx (either via consume folder, or via drag & drop), the file is processed only once and for the second file the message appears in File Tasks saying it's a duplicate. But if it's a PNG file (screen shot for instance), the same file can be uploaded multiple times and is not discovered as duplicate.

### Steps to reproduce

1. Upload PNG file to consume folder.
2. Wait a moment for the file to be processed and deleted from the folder.
3. Upload the same file again.
4. It is processed and deleted again. Two identical documents appear.

### Webserver logs

```bash
not checked
```

### Paperless-ngx version

2.0.1

### Host OS

Unraid (Linux)

### Installation method

Docker - official image

### Browser

Brave (Chrome)

**Comment by stumpylog** [comment]
Seems highly unlikely, as the duplicate checking is hash based.  The more likely thing is that the files are not bit for bit the same.

**Comment by shamoon** [comment]
It’s not a duplicate if it’s a different file type

**Comment by shamoon** [comment]
Sorry I misunderstood. But as noted, I think the files are hashed to check duplicate

**Comment by stumpylog** [comment]
Can't reproduce it:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/394c3308-d8d2-4729-ae04-13af906bbbc9)

Again, it's bit for bit checking using MD5

**Comment by shamoon** [comment]
Funny enough, I can
<img width="414" alt="Screenshot 2023-12-02 at 7 53 54 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/3c1d92b0-a331-4a45-b410-6c43c092cbe6">

used
<img width="264" alt="Screenshot 2023-12-01 at 10 34 16 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/e78b4ab4-c613-4557-b5a2-c4ea50311221">

**Comment by shamoon** [comment]
Different checksums =/
<img width="666" alt="Screenshot 2023-12-02 at 8 03 05 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/9c920672-1fe9-4d25-82c0-af73cc30060c">
(and archive_checksum)
<img width="977" alt="Screenshot 2023-12-02 at 8 01 37 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/ec8706c0-3a1b-4cd3-a3d2-a5c918609a5a">

**Comment by stumpylog** [comment]
Ok, that's weird.  Can you put up a sample to play around with?

**Comment by shamoon** [comment]
I used the one from this https://github.com/paperless-ngx/paperless-ngx/issues/4775#issuecomment-1837188591 but I can repro with most it seems, yea surprising

**Comment by shamoon** [comment]
I think stumpylog figured it out already =)
