### ISSUE TITLE
[BUG] Default permissions are not applied when creating a tag, storage path or correspondent from the edit page

### ISSUE THREAD

**Issue by salabaz** [paperless-ngx/paperless-ngx#4777]
### Description

The new default permissions setting works when creating new tags, storage paths or correspondents from their respective pages. But when creating news tags, storage paths or correspondents from the "edit" page of a document by typing in the name of the new item and then hitting enter, the permissions settings are empty.
I would expect the default permissions to apply here to.

### Steps to reproduce

* Go to Setting/Permissions and set default permissions - save
* Open any document in edit mode
* Select the tag, storage path or correspondend field and type in the name of a new item - hit enter
* in de following dialog no default permissions are shown

### Webserver logs

```bash
No related logs from the webserver.
```

### Paperless-ngx version

2.0.1

### Host OS

Debian

### Installation method

Docker - official image

### Configuration changes

added syncthing container for file sync

**Comment by shamoon** [comment]
Thanks, FYI the '+' button next to the dropdown still works for now, fix should be in soon.
