### ISSUE TITLE
[BUG] Short URLs in custom field

### ISSUE THREAD

**Issue by florie1706** [paperless-ngx/paperless-ngx#4789]
### Description

I am on paperless-nix 2.0.1 and have one custom filed as URL. I want to stay flexible and want to "link" corresponding documents. So I would like to put something in the filed like this "/documents/213". It would work when I click on the icon next to the custom filed but it throws an error with "no valid URL" and I cannot save it.

### Steps to reproduce

Try to put in /documents/213 instead of a full link within your paperless installation

### Webserver logs

```bash
No logs
```

### Paperless-ngx version

2.0.1

### Host OS

Ubuntu 23.10

### Installation method

Docker - official image

### Browser

Safari

**Comment by shamoon** [comment]
If you'd like to make a FR to support relative URIs that'd be fine
