### ISSUE TITLE
[BUG] Consumption templates based on path do not trigger correctly

### ISSUE THREAD

**Issue by iph0nege3k** [paperless-ngx/paperless-ngx#4812]
### Description

Hi shamoon,

by now I am pretty sure that I am not just using it wrongly, but rather that this is a bug.

What I'm trying to accomplish is having seperate document structures for my girlfriend and I. I created a consumption template that looks like this:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/944111/1a835008-03ae-4cba-ac42-784e5c28554b)

My consume folder:
`./consume:/usr/src/paperless/consume`
is empty except for the girlfriend folder
I added PAPERLESS_CONSUMER_RECURSIVE=true to my environment file and recursive consumption per se works.
When I drop a document in there the owner is not properly set. I set up a template that triggers after her template and assigns a document to my user if her template did not work. This one has no filter and just takes any document and assigns it to me owner-wise.

### Steps to reproduce

1. Setup consumption template using wildcards
2. Drop document in consume subfolder

### Webserver logs

```bash
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,432] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/girlfriend/New Issue · paperless-ngx_paperless-ngx.pdf to the task queue.
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,452] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[1be2ded1-b0cb-410c-a0e1-9e9aaff6b956] received
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,524] [INFO] [paperless.matching] Document did not match template girlfriend
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,525] [INFO] [paperless.matching] Document matched template My Documents
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,546] [INFO] [paperless.consumer] Consuming New Issue · paperless-ngx_paperless-ngx.pdf
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,919] [WARNING] [ocrmypdf._pipeline] This PDF is marked as a Tagged PDF. This often indicates that the PDF was generated from an office document and does not need OCR. PDF pages processed by OCRmyPDF may not be tagged correctly.
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,920] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
paperless-ngx-webserver-1  | [2023-12-04 19:57:43,930] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
paperless-ngx-webserver-1  | [2023-12-04 19:57:44,147] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.27 savings: 21.2%
paperless-ngx-webserver-1  | [2023-12-04 19:57:44,147] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.81 savings: 44.9%
paperless-ngx-webserver-1  | [2023-12-04 19:57:44,150] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
paperless-ngx-webserver-1  | [2023-12-04 19:57:46,813] [INFO] [paperless.consumer] Document 2022-03-21 New Issue · paperless-ngx_paperless-ngx consumption finished
paperless-ngx-webserver-1  | [2023-12-04 19:57:46,820] [INFO] [celery.app.trace] Task documents.tasks.consume_file[1be2ded1-b0cb-410c-a0e1-9e9aaff6b956] succeeded in 3.3651259718462825s: 'Success. New document id 2204 created'
```

### Paperless-ngx version

2.0.1

### Host OS

Debian GNU/Linux 11 (bullseye)

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Didn’t you ask this in chat? Use `*/girlfriend/*`

we may need to make this easier but it’s not broken, I don’t think

**Comment by stumpylog** [comment]
It's not broken.  You need to include the ending path separator.  `*girlfriend/*`

**Comment by stumpylog** [comment]
And/or `*girlfriend/**` if you want deeper folders under that one.
