### ISSUE TITLE
[WARNING] [paperless.sanity_checker] Orphaned file in media dir: /usr/src/paperless/media/documents/originals/.../@eaDir/file.jpg/SYNOINDEX_MEDIA_INFO

### ISSUE THREAD

**Issue by familie-braun** [paperless-ngx/paperless-ngx#4818]
### Description

After upgrading to 2.0.1, I called the command docker exec paperlessngx document_sanity_checker on the synology and received a lot of error messages, such as this one [2023-12-04 21:13:25,362] [WARNING] [paperless.sanity_checker] Orphaned file in media dir: /usr/src/paperless/media/documents/originals/Dominik/Schule-Uni-Weiterbildung/EU-FH/Studium 29.05.2022/4. Semester - attended lectures/marketing planning and market research/@eaDir/file.jpg/SYNOINDEX_MEDIA_INFO

### Steps to reproduce

per ssh on Synology
docker exec paperlessngx document_sanity_checker

### Webserver logs

```bash
[2023-12-04 21:13:25,362] [WARNING] [paperless.sanity_checker] Orphaned file in media dir: /usr/src/paperless/media/documents/originals/Dominik/Schule-Uni-Weiterbildung/EU-FH/Studium 29.05.2022/4. Semester - besuchte Vorlesungen/Marketingplanung und Marktforschung/@eaDir/file.jpg/SYNOINDEX_MEDIA_INFO
```

### Paperless-ngx version

2.0.1

### Host OS

DSM 7.2.1-69057 Update 3

### Installation method

Docker - official image

**Comment by stumpylog** [comment]
Not seeing how this is a bug.  The sanity check has always and will always report files in the media directory which are not tied to a specific document.  

In this case, it appears to be a Synology specific file.  If you can disable whatever makes that, you can resolve the issue.  But it paperless isn't doing anything wrong here.
