### ISSUE TITLE
[BUG] Saving settings fails with TypeError: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by ginkel** [paperless-ngx/paperless-ngx#4820]
### Description

I am running paperless-ngx 2.0.1 deployed via Docker. When editing the Settings at `/settings` and hitting "Save" (actually "Speichern" as the installation is configured to be displayed in German - that's actually what I want to change) I am greeted with the following error:

```
ERROR TypeError: Cannot read properties of null (reading 'toString')
    at n.saveLocalSettings (main.js:3:1148711)
    at n.saveSettings (main.js:3:1151458)
    at main.js:3:1159570
    at iN (main.js:3:89748)
    at Object.o [as next] (main.js:3:89915)
    at X.next (main.js:3:3460)
    at $._next (main.js:3:3144)
    at $.next (main.js:3:2837)
    at main.js:3:5972
    at I (main.js:3:2593)
```

I am logged in as superser.

### Steps to reproduce

1. Open "Settings"
2. Change language
3. Hit "Save"

### Webserver logs

```bash
nothing is logged
```

### Paperless-ngx version

2.0.1

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Chromium Version 119.0.6045.159 (Official Build) Arch Linux (64-bit)

### Configuration changes

```
PAPERLESS_CONSUMPTION_DIR=/usr/src/paperless/consume
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
PAPERLESS_CONSUMER_ENABLE_BARCODES=false
PAPERLESS_CONSUMER_POLLING_DELAY=10
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_DBHOST=postgres
PAPERLESS_DBNAME=paperless
PAPERLESS_DBPASS=*redacted*
PAPERLESS_DBUSER=paperless
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_REDIS=redis://redis:6379
PAPERLESS_TASK_WORKERS=6
PAPERLESS_THREADS_PER_WORKER=2
PAPERLESS_TIKA_ENABLED=1
PAPERLESS_TIKA_ENDPOINT=https://tika.*redacted*
PAPERLESS_TIKA_GOTENBERG_ENDPOINT=https://gotenberg.*redacted*
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_SECRET_KEY=*redacted*
PAPERLESS_URL=https://paperless.*redacted*
```

**Comment by stumpylog** [comment]
Is it a particular language?  I just tried a couple and didn't see any errors.

**Comment by ginkel** [comment]
No, the selected language does not make any difference. Is there a way to figure out which setting is causing trouble? The JS is minified, which makes debugging somewhat cumbersome.

**Comment by ginkel** [comment]
I do have a second Paperless deployment, which is already configured to en_US, where the issue is not reproducible either. So this is probably related to configuration data.

**Comment by stumpylog** [comment]
I don't know the frontend, so I'm not sure.  Our frontend developer will be around when he can and can perhaps shed more light

**Comment by ginkel** [comment]
Thanks! Just managed to also break the second deployment by changing and saving settings. So the issue is probably more universal.

**Comment by ginkel** [comment]
The exception happens on this line:

```
          this.settings.set(ct.THEME_COLOR, this.settingsForm.value.themeColor.toString()),
```

`this.settingsForm.value.themeColor` is `null`

**Comment by ginkel** [comment]
I can work around the issue by manually populating the value of the color picker, which is empty by default:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/174129/fbf4cc2f-33ec-4be7-95ae-75e154b84997)

**Comment by shamoon** [comment]
Hmm, I cant reproduce this either. It's also not something that has changed at all recently. The value is initialized to an empty string, so it shouldn't really be null:

https://github.com/paperless-ngx/paperless-ngx/blob/69e63a87d99ab38e0400756a90ca3027d922613f/src-ui/src/app/data/paperless-uisettings.ts#L97-L101

This is with the db settings totally removed, nothing in the browser local storage:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/06448c78-dd15-46e3-8993-53ddeb717be6

I also tried with e.g. setting the color and then resetting it.

So I dunno, changing that 1 line to handle `null` is easy but it wouldn't make sense, a lot of the code around that behaves the same.

I'd try clearing the browser cache and local storage. Perhaps theres some other step(s) to recreate it, but again, nothing changed here (intentionally anyway)

**Comment by ginkel** [comment]
Clearing cookies and local storage fixed the issue, so I am closing this.
