### ISSUE TITLE
[BUG] No accented characters after OCR

### ISSUE THREAD

**Issue by MilesTEG1** [paperless-ngx/paperless-ngx#4833]
### Description

Hello,
I'm french and in French we use a lot of accented characters like é è à ç ù ë ...
On many documents I put into Paperless NGX, all of those accented characters are missing after the OCR (in the content tab I see that they're missing).
So all filter to tag, add correspondent... using words with accented letters aren't working.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/29298312/20a5f177-7d05-4245-a502-9be4b89649ad)

### Steps to reproduce

1. Import a document with accented letters
2. See that in the content tabs, none of the accented letters are present, but worse, instead of accented letters, there is a space that is not a space (it is bigger)

### Webserver logs

```bash
[2023-12-05 10:29:35,184] [INFO] [paperless.consumer] Consuming 2023-12-04 - Avis d'Échéance 2024.pdf
[2023-12-05 10:29:35,193] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-12-05 10:29:35,196] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-12-05 10:29:35,201] [DEBUG] [paperless.consumer] Parsing 2023-12-04 - Avis d'Échéance 2024.pdf...
[2023-12-05 10:29:35,721] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath("/tmp/paperless/paperless-ngxo9o7tj1k/2023-12-04 - Avis d'Échéance 2024.pdf"), 'output_file': PosixPath('/tmp/paperless/paperless-8bqkjksv/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'fra', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-8bqkjksv/sidecar.txt')}
[2023-12-05 10:29:37,591] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.
[2023-12-05 10:29:37,767] [DEBUG] [paperless.consumer] Generating thumbnail for 2023-12-04 - Avis d'Échéance 2024.pdf...
[2023-12-05 10:29:37,772] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-8bqkjksv/archive.pdf[0] /tmp/paperless/paperless-8bqkjksv/convert.webp
[2023-12-05 10:29:45,547] [DEBUG] [paperless.consumer] Saving record to database
[2023-12-05 10:29:45,548] [DEBUG] [paperless.consumer] Creation date from post_documents parameter: 2023-11-17 00:00:00+01:00
[2023-12-05 10:29:46,418] [DEBUG] [paperless.matching] Tag Assurance habitation matched on document 2023-11-17 MAIF 2023-12-04 - Avis d'Échéance 2024 because it contains this word: MAIF
[2023-12-05 10:29:46,863] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxo9o7tj1k/2023-12-04 - Avis d'Échéance 2024.pdf
[2023-12-05 10:29:46,872] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-8bqkjksv
[2023-12-05 10:29:46,873] [INFO] [paperless.consumer] Document 2023-11-17 MAIF 2023-12-04 - Avis d'Échéance 2024 consumption finished
[2023-12-05 10:38:10,447] [DEBUG] [paperless.api] An error occurred checking for available updates
```

### Paperless-ngx version

2.0.1

### Host OS

x86_64 (Docker is running on a Synology DS920+ with DSM  7.2.1-69057 - Update 3)

### Installation method

Docker - official image

### Browser

Brave

### Configuration changes

PAPERLESS_OCR_LANGUAGE: fra

**Comment by shamoon** [comment]
This came up in #3718 and it came down to the dependencies we use (as it often does), though I think we were under the impression that upgrading them would solve this. Is the text correct if you copy and paste it from the pdf? if you try running the ocrmypdf command as shown in the logs and it has the issue then, as noted in the template this should be reported upstream

Also a sample pdf is always helpful

**Comment by stumpylog** [comment]
> if you try running the ocrmypdf command as shown

` ocrmypdf --language fra --output-type pdfa --color-conversion-strategy RGB --skip-text --clean --deskew --rotate-pages --rotate-pages-threshold 12.0 --sidecar sidecar.txt inputfile.pdf outputfile.pdf`

Running that against a problem file and examine the output will help.  if you can provide a sample, that's almost better.

**Comment by MilesTEG1** [comment]
Hello @shamoon 
Here a sample of the file with accented letters which doesn't 
[sample_with_accented_letters_not_working.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13562258/sample_with_accented_letters_not_working.pdf)

And here the copy/paste form it:

> MAIF CS 90000 - 79038 NIORT cedex 9 Société d'assurance mutuelle à cotisations variables Ent. Régie par le Code des Assurances SIREN : 775 709 702 N° intracommunautaire : FR81775709702 TVA non applicable : article 261 C 2e du CGI N° d'ICS : FR70ZZZ000884
> 
> Votre numéro de sociétaire
> 
> Téléchargez vos attestations, déclarez et suivez vos sinistres sur votre espacepersonnel.maif.fr ou sur l'application MAIF
> 
> Chère Sociétaire, Cher Sociétaire,
> 
> Nous vous adressons votre avis d'échéance pour la période du 1 er janvier au 31 décembre 2024, établi sur votre situation contractuelle au 17/11/2023. Toute modification enregistrée après cette date n'apparaîtra donc pas sur ce document. Nous vous invitons à relire avec soin vos informations et à nous contacter pour signaler tout changement.
> 
> Nous vous remercions de la confiance que vous nous accordez au quotidien.
> 
> HT
> 
> TTC
> 
> Besoin d'informations complémentaires ?
> 
> Nous appeler
> 
> 02 35 58 85 60
> 
> Appel non surtaxé.
> 
> Du lundi au vendredi de 8h à 19h15 et samedi de 8h à 17h15.
> 
> Nous rendre visite
> 
> Votre délégation conseil
> 
> 129 boulevard de l'Europe ROUEN
> 
> Accueil avec ou sans rendez-vous.
> 
> Nous écrire
> 
> gestionsocietaire@maif.fr
> 
> Merci de nous indiquer votre numéro de sociétaire en objet.
> 
> MAIF
> 
> Gestion Courrier Sociétaire 79018 Niort cedex 9
>

**Comment by shamoon** [comment]
Running the command would be done from a shell inside the container. No worries if you don’t know what I mean, we can try it with the sample.

The archive just means the pdf that paperless generates as opposed to the “original”. Eg in your first screenshot, it’s the pdf displayed on the right

**Comment by MilesTEG1** [comment]
Found it!
But the copy/paste is... a bit gibberish:

> NBJG DT!:1111!.!8:149!OJPSU!dfefy!: Tpdju!e(bttvsbodf!nvuvfmmf!!dpujtbujpot!wbsjbcmft Fou/!Shjf!qbs!mf!Dpef!eft!Bttvsbodft TJSFO!;!886!81:!813 O¢!jousbdpnnvobvubjsf!;!GS9288681:813 UWB!opo!bqqmjdbcmf!;!bsujdmf!372!D!3f!ev!DHJ O¢!e(JDT!;!GS81[[[111995
> 
> Wpusf!ovnsp!ef!tpdjubjsf
> 
> Umdibshf{!wpt!buuftubujpotedmbsf{!fu!tvjwf{!wpt tjojtusft!tvs!wpusf ftqbdfqfstpoofm/nbjg/gs pv!tvs!m(bqqmjdbujpo!NBJG
> 
> Disf!Tpdjubjsf-!Difs!Tpdjubjsf-
> 
> !
> 
> !
> 
> !
> 
> ! !
> 
> !
> 
> !
> 
> Opvt!wpvt!besfttpot!wpusf!bwjt!e(dibodf!qpvs!mb!qsjpef!ev!2fs !kbowjfs!bv!42!edfncsf!3135-!ubcmj!tvs!wpusf!tjuvbujpo dpousbduvfmmf!bv!2802203134/!Upvuf!npejgjdbujpo!fosfhjtusf!bqst!dfuuf!ebuf!o(bqqbsbusb!epod!qbt!tvs!df!epdvnfou/ Opvt!wpvt!jowjupot!!sfmjsf!bwfd!tpjo!wpt!jogpsnbujpot!fu!!opvt!dpoubdufs!qpvs!tjhobmfs!upvu!dibohfnfou/
> 
> Opvt!wpvt!sfnfsdjpot!ef!mb!dpogjbodf!rvf!wpvt!opvt!bddpsef{!bv!rvpujejfo/
> 
> Cftpjo!e(jogpsnbujpot
> 
> !
> 
> dpnqmnfoubjsft!@
> 
> Opvt!bqqfmfs
> 
> 13!46!69!96!71
> 
> Bqqfm!opo!tvsuby/ Ev!mvoej!bv!wfoesfej!ef!9i!!2:i26 fu!tbnfej!ef!9i!!28i26/
> 
> Opvt!sfoesf!wjtjuf
> 
> Wpusf!emhbujpo!dpotfjm
> 
> 23:!cpvmfwbse!ef!m(Fvspqf SPVFO
> 
> Bddvfjm!bwfd!pv!tbot!sfoef{.wpvt/
> 
> Opvt!dsjsf
> 
> hftujpotpdjfubjsfAnbjg/gs
> 
> Nfsdj!ef!opvt!joejrvfs!wpusf ovnsp!ef!tpdjubjsf!fo!pckfu/
> 
> NBJG
> 
> Hftujpo!Dpvssjfs!Tpdjubjsf 8:129!Ojpsu!dfefy!:


It was opened with PDF Expert. I've got the same with Apercu (macOS).
But with Adobe Reader, I've got this:

> MAIF
> CS 90000 - 79038 NIORT cedex 9
> Socit d'assurance mutuelle  cotisations variables
> Ent. Rgie par le Code des Assurances
> SIREN : 775 709 702
> N¡ intracommunautaire : FR81775709702
> TVA non applicable : article 261 C 2e du CGI
> N¡ d'ICS : FR70ZZZ000884
>  
>  
>      
>    
> Votre numro de socitaire
> Tlchargez vos attestations,
> dclarez et suivez vos
> sinistres sur votre
> espacepersonnel.maif.fr
> ou sur l'application MAIF
> Chre Socitaire, Cher Socitaire,
> Nous vous adressons votre avis d'chance pour la priode du 1er janvier au 31 dcembre 2024, tabli sur votre situation
> contractuelle au 17/11/2023. Toute modification enregistre aprs cette date n'apparatra donc pas sur ce document.
> Nous vous invitons  relire avec soin vos informations et  nous contacter pour signaler tout changement.
> Nous vous remercions de la confiance que vous nous accordez au quotidien.
> Besoin d'informations
> complmentaires ?
> Nous appeler
> 02 35 58 85 60
> Appel non surtax.
> Du lundi au vendredi de 8h  19h15
> et samedi de 8h  17h15.
> Nous rendre visite
> Votre dlgation conseil
> 129 boulevard de l'Europe
> ROUEN
> Accueil avec ou sans rendez-vous.
> Nous crire
> gestionsocietaire@maif.fr
> Merci de nous indiquer votre
> numro de socitaire en objet.
> MAIF
> Gestion Courrier Socitaire
> 79018 Niort cedex 9

So, no accented letters...

PS: that's very strange that the copy/paste from Aperçu, or PDF Expert, are gibberish...

**Comment by stumpylog** [comment]
It feels like something about the output PDF is what is off here.  I'll look more into it later today, but either ocrmypdf isn't outputting proper utf-8 to the text layer or tesseract is off the rails or something.

**Comment by stumpylog** [comment]
Ok, I've had a little time to look at this now and it appears to be a problem with the layer ocrmypdf is putting into the archive.  That's then the text we extract and use as the document content.

So, given something that looks like this (in the archive):
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/c9a08e5f-0638-4fa1-858e-c177f9721090)
It copies out as:
`Votre numro de socitaire`

That's also what `pdftotext` will extract.

If I run `pdftotext` against the original, it extracts no problem.  But a long time ago the decision was to extract from an OCRd version, which I'm not sure we can change without breaking what people expect.

So I think this should be raised upstream to https://github.com/ocrmypdf/OCRmyPDF/issues.  Even if Tesseract isn't extracting the text correctly, I would expect it to be printable characters.

**Comment by shamoon** [comment]
Thanks stumpy. @MilesTEG1 we’ll close this here for now, you can post any linked upstream issue(s) that are relevant. If there is presumably a fix upstream in the future we will integrate that back into pngx

**Comment by stumpylog** [comment]
I am a little concerned as ocrmypdf is apparently gearing up for a v16 which drops support for Python 3.9, meaning it may be difficult to include a fix.

@MilesTEG1 unless you need the archive, you could skip the generation using `PAPERLESS_OCR_SKIP_ARCHIVE_FILE=with_text`.  That will bypass the problem (ocrmypdf) at the cost of no PDF/A file generated

**Comment by MilesTEG1** [comment]
Hello,
Thank you for looking into this problem, and for your answers.

> So I think this should be raised upstream to https://github.com/ocrmypdf/OCRmyPDF/issues. Even if Tesseract isn't extracting the text correctly, I would expect it to be printable characters.

Do I have to do it myself?



> @MilesTEG1 unless you need the archive, you could skip the generation using `PAPERLESS_OCR_SKIP_ARCHIVE_FILE=with_text`. That will bypass the problem (ocrmypdf) at the cost of no PDF/A file generated

Ok, I'll do this, as I don't really need the archives.
You confirm me that I still get the orginal PDFs?

**Comment by MilesTEG1** [comment]
With adding this environment variable, I now have all my accented letters in the content tab:

> MAIF
> CS 90000 - 79038 NIORT cedex 9
> Société d'assurance mutuelle à cotisations variables
> Ent. Régie par le Code des Assurances
> SIREN : 775 709 702
> N° intracommunautaire : FR81775709702
> TVA non applicable : article 261 C 2e du CGI
> N° d'ICS : FR70ZZZ000884
> 
> 
> 
> 
> Votre numéro de sociétaire
> 
> 
> Téléchargez vos attestations,
> déclarez et suivez vos
> sinistres sur votre
> espacepersonnel.maif.fr
> ou sur l'application MAIF
> 
> 
> Chère Sociétaire, Cher Sociétaire,
> Nous vous adressons votre avis d'échéance pour la période du 1er janvier au 31 décembre 2024, établi sur votre situation
> contractuelle au 17/11/2023. Toute modification enregistrée après cette date n'apparaîtra donc pas sur ce document.
> Nous vous invitons à relire avec soin vos informations et à nous contacter pour signaler tout changement.
> Nous vous remercions de la confiance que vous nous accordez au quotidien.
> 
> Besoin d'informations
> complémentaires ?
> Nous appeler
> 02 35 58 85 60
> Appel non surtaxé.
> Du lundi au vendredi de 8h à 19h15
> et samedi de 8h à 17h15.
> 
> 
> Nous rendre visite
> Votre délégation conseil
> 129 boulevard de l'Europe
> ROUEN
> Accueil avec ou sans rendez-vous.
> 
> 
> Nous écrire
> gestionsocietaire@maif.fr
> Merci de nous indiquer votre
> numéro de sociétaire en objet.
> 
> MAIF
> Gestion Courrier Sociétaire
> 79018 Niort cedex 9


I hope the filters for tag and co will grab correctly the value now ^^

**Comment by shamoon** [comment]
Thanks stumpy

**Comment by stumpylog** [comment]
The issue has been reported further upstream to Ghostscript: https://bugs.ghostscript.com/show_bug.cgi?id=707369
