### ISSUE TITLE
[BUG] Issue with checking for new versions

### ISSUE THREAD

**Issue by jdlail** [paperless-ngx/paperless-ngx#4837]
### Description

Not a big issue, but beginning with version 2.0.0 and continuing with 2.0.1, I see an error in the log files about its ability to check for new versions.

### Steps to reproduce

Check Paperless log screen after Docker update.

### Webserver logs

```bash
From the log screen in Paperless ...

[2023-12-05 09:08:13,161] [DEBUG] [paperless.api] An error occurred checking for available updates
```

### Paperless-ngx version

2.0.1

### Host OS

 QNAP x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
See #4769
