### ISSUE TITLE
[BUG] /assets/js/pdf.worker.min.js 404 Not Found when using reverse proxy with custom subpath

### ISSUE THREAD

**Issue by paradox00** [paperless-ngx/paperless-ngx#4848]
### Description

when hosting paperless-ngx 2.1.0 using custom subpath:
```
PAPERLESS_FORCE_SCRIPT_NAME=/paperless
PAPERLESS_STATIC_URL=/paperless/static/
```

paperless still try to fetch the pdf worker's js from the root path: `https://domain.example.com/assets/js/pdf.worker.min.js` instead of `https://domain.example.com/paperless/assets/js/pdf.worker.min.js`

### Steps to reproduce

set in `docker-compose.env`:
```
PAPERLESS_FORCE_SCRIPT_NAME=/paperless
PAPERLESS_STATIC_URL=/paperless/static/
```

access the web frontend with the path `/paperless/` and try to view one of the PDFs.

### Webserver logs

```bash
None
```

### Browser logs

```bash
GET https://domain.example.com/assets/js/pdf.worker.min.js 404 (Not Found)

GET https://domain.example.com/assets/js/pdf.worker.min.js net::ERR_ABORTED 404 (Not Found)
```

### Paperless-ngx version

2.1.0

### Host OS

Ubuntu 23.10

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment]
Ah ok thanks, I will sort this out when I have a minute. In the meantime you can use the browser viewer

**Comment by shamoon** [comment]
Hey @paradox00 if you have a moment to test out an image for this `feature-fix-pdf-worker-url` would appreciate it, testing subpath deployment is a bit of a pain, I think its straightforward but want to be sure.

That image is based on `dev` but currently doesnt contain anything that should affect an install (e.g. no db migrations etc) but I'd always say you may want to have a backup or try on a test install just in case.

Thanks

**Comment by shamoon** [comment]
Great, thanks for testing

**Comment by shamoon** [comment]
@paradox00 sorry to be a total pain, can you check the image (being sure to re-pull the same tag `feature-fix-pdf-worker-url`)? Trying a different even simpler fix and want to make sure again.

Thank you!

**Comment by paradox00** [comment]
@shamoon  - This one also looks good with my setup :)

**Comment by shamoon** [comment]
Great thanks!
