### ISSUE TITLE
[BUG] If a date in PDF is in ISO-8601 format (YYYY-MM-DD), paperless-ngx suggests wrong date

### ISSUE THREAD

**Issue by akumiszcza** [paperless-ngx/paperless-ngx#4850]
### Description

For each PDF I have with a date in the format YYYY-MM-DD (ISO 8601), paperless-ngx suggests "Date created" in the format YYYY-DD-MM, which is not even a format used in the USA. I have over a hundred of these files and all are corrected manually by me, so I don't think it is a neural network issue. I include one example.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/52917795/cf3ed973-9d06-4154-afa0-ff8bea7fe3b4)

[PA 87541_12_2023_0i74.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13581192/PA.87541_12_2023_0i74.pdf)

The dates in metadata are correct:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/52917795/39c1cec0-f971-4a51-9041-1a55adaf2735)

### Steps to reproduce

1. Upload a PDF with a date in the format YYYY-MM-DD
2. Open the document in paperless-ngx
3. See that suggested date is not in this format.

### Webserver logs

```bash
Nothing of use.
```

### Paperless-ngx version

2.1.0

### Host OS

Unraid 6.12.6 (Linux)

### Installation method

Docker - official image

### Browser

Brave

**Comment by shamoon** [comment]
Did you set `PAPERLESS_DATE_ORDER`?

**Comment by stumpylog** [comment]
You can suggest the date ordering via https://docs.paperless-ngx.com/configuration/#PAPERLESS_DATE_ORDER

Otherwise, all date parsing is at best a guess from thing that look date like.  This is not a bug.

**Comment by akumiszcza** [comment]
Setting PAPERLESS_DATE_ORDER to YMD helped with these documents, thank you.
