### ISSUE TITLE
[BUG] `document_consumer`, `qcluster` processes overconsuming CPU

### ISSUE THREAD

**Issue by kavemang** [paperless-ngx/paperless-ngx#489]
Hi folks, recently switched from -ng to -ngx using the method recommended on r/selfhosted (switching image) 

I'm finding that two python processes from paperless are now consuming most of my cores 24/7, once is called "qcluster" the other is "document_consumer", I would expect this to be possible If I were processing new documents but it seems to be constant without the webfront even being used 

For now im going to spin down the container until I get advice here

**Relevant information**
 - Docker on Ubuntu 20.04]

 - Version latest
 - Installation method: docker
 - switched container from -ng image to -ngx image

**Comment by kavemang** [comment]
hi these log messages are looping when i unpause it, as far as I can recall I don't have any special changes or configuration I just had a standard paperless-ng setup which i changed over to -ngx 

```
?: PAPERLESS_MEDIA_ROOT is not writeable
	HINT: Set the permissions of 
drwxr-xr-x /data/media
 to be writeable by the user running the Paperless services
2022-03-25 16:18:52,266 INFO spawned: 'consumer' with pid 126
2022-03-25 16:18:52,705 INFO exited: scheduler (exit status 1; not expected)
2022-03-25 16:18:53,707 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-25 16:18:53,711 INFO spawned: 'scheduler' with pid 127
2022-03-25 16:18:54,713 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
SystemCheckError: System check identified some issues:
ERRORS:
?: PAPERLESS_CONSUMPTION_DIR is not writeable
	HINT: Set the permissions of 
drwxr-xr-x /data/consume
 to be writeable by the user running the Paperless services
?: PAPERLESS_DATA_DIR is not writeable
	HINT: Set the permissions of 
drwxr-xr-x /config
 to be writeable by the user running the Paperless services
?: PAPERLESS_MEDIA_ROOT is not writeable
	HINT: Set the permissions of 
drwxr-xr-x /data/media
 to be writeable by the user running the Paperless services
```

**Comment by stumpylog** [comment]
Did you by any change migrate to -ngx from the LinuxServer.io provided image?  If yes, #260 and #261 was the same logs and problem.

It's a permissions issue in either case.  Please ensure the `PAPERLESS_CONSUMPTION_DIR` on the host is writeable by the user ID you are running the container as.  By default, that would be uid/gid 1000

**Comment by kavemang** [comment]
> Did you by any change migrate to -ngx from the LinuxServer.io provided image? If yes, #260 and #261 was the same logs and problem.
> 
> It's a permissions issue in either case. Please ensure the `PAPERLESS_CONSUMPTION_DIR` on the host is writeable by the user ID you are running the container as. By default, that would be uid/gid 1000

I tried using chown but no luck so far

**Comment by stumpylog** [comment]
From inside the container:

- What does `ls -ahl /data` show?
- What does `ls -ahl /config` show?
- What does `id -u paperless` output?

From outside the container:
- What is the output of `ls -ahl` for the locations where /data/consume, /data/media, /config are mounted from show?

**Comment by shamoon** [comment]
Thanks for the update!

**Comment by kavemang** [comment]
unfortunately the threads being put up said to switch images, I still don't know how to fix my setup and havent been able to get the container to run with the old -ng image now either, can you advise me how to go back to -ng and get my paperless working again? 

@shamoon

**Comment by shamoon** [comment]
TBH Im not sure clear what went wrong so hard to say.
Perhaps restore your -ng from backup, setup -ngx new and export your docs and import into the new install.

**Comment by stumpylog** [comment]
The original logs pointed to a permission issue.  You should probably look into the USERMAP_UID and USERMAP_GID settings, making sure those values match to the user on the host owning the folders the container is mapped to.  The commands mentioned above can help determine what user owners the various folders.
