### ISSUE TITLE
[BUG] User with edit permissions on document cannot add custom fields or create share links

### ISSUE THREAD

**Issue by lagset** [paperless-ngx/paperless-ngx#4901]
### Description

When user A owns a document and gives user B permissions to edit the document, user B is still not able to add custom fields to the document or generate a share link for the document. Both dropdown buttons are greyed out until the owner is either changed to user B or removed completely.

### Steps to reproduce

1. Edit a document and set the owner to your current user and give another user edit permissions on the document
2. Login as the other user
3. Edit the document -> editing default inputs works and saving the changes is successful 
4. However the buttons "Share Link" and "Custom Field" are both greyed out

Just for context: In my setup the permission matrix of the user group which has edit rights on documents but cannot create share links / add custom fields to editable but unowned documents looks like this:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/15156011/d7c94f7d-a896-46c6-8fdd-bfc318921eb2)

### Webserver logs

```bash
nothing logged while reproducing the issue
```

### Paperless-ngx version

2.1.0

### Host OS

Synology DSM 7.2

### Installation method

Docker - official image

### Browser

Firefox, Edge

**Comment by lagset** [comment]
Thanks for the quick response. I was wondering if it is intentional but doing a quick research I couldn't find anything explicit about what a user with editing rights is capable of doing/not doing. Thus, I decided to go with the bug report.

If you think it's viable, we can move this into a discussion and see how it resonates. Take the following as a discussion starter:

For me, personally (and obviously), the expected privileges of an editor (or better: someone with the maximum of permissions granted) would be more extensive.

 **Regarding custom fields**
From a user view, the questions comes to mind "Why can I edit (custom) fields, but not add/remove them?" It feels like the same scope of responsibility, if you know what I mean.

**Regarding share link**
I can see that sharing (potentially sensitive) documents is another, more critical, scope of responsibility than simply editing metadata of the document. 

However, as a counter-argument on this: The "sharing" of the document is currently possible for editors by downloading it first and then doing what they want with it, hence, there is imho no practical data safety benefit for blocking share link for editors - for now.

___
The cleanest solution to this, I agree, is a finer role system, e.g. a "Manager" role who can act like the owner, with the only exception that the manager cannot change the owner, so the owner can't lose access.

For my use case (partner and me, sharing documents, for now only us), it would be helpful to have the "manager" role, however I could achieve a similar outcome by just removing the owner, for now. This may become a problem if other users join us later on, but not now.

**Comment by shamoon** [comment]
Sounds good, why dont you just open a discussion with the above, biggest thing is use a good title so that people will find it with searching and hopefully we can get some more opinions on it. I'd recommend splitting the FR i.e. "finer control for edit" vs "allow editors to use share links / add custom fields", basically the first thing is a huge change that I dont expect to happen any time soon (if ever), the other one is a very simple change to make, I just dont want to do that without a better sense of what others think.
