### ISSUE TITLE
[Other] Name of downloaded File contains (escaping?) character '+'

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#491]
I am currently experiencing the following behaviour after migrating to ng-x 1.6.0.

When downloaded, a file contains the following special charater (i reckon as a safe-escaping char?) 

> 2019-07-30+Allianz+Ihre+betriebliche+Krankenversicherung+(bKV)+AK-9874071796.pdf

Until 1.5.0 it was the following
> 2019-07-30 Allianz Ihre betriebliche Krankenversicherung (bKV) AK-9874071796.pdf

The naming of the document is as follows

> Ihre betriebliche Krankenversicherung (bKV) AK-9874071796

Following settings was provided before and after the migration:

> PAPERLESS_FILENAME_FORMAT={created_year}/{correspondent}/{document_type}-{title}-{created_year}-{created_month}

I am not sure if this is a bug, or desired behaviour. Can anyone provide further information or is experiencing the same issue?

**Comment by stumpylog** [comment]
When we create a sanitized filename for download, `-` is actually used to replace any invalid characters.  However, that filename doesn't appear to have anything invalid in it.  And it shouldn't be `+` that I know of either.

If you view the document from the admin site (Admin -> Documents -> this document), what is the filename it says there?

**Comment by sukisoft** [comment]
Here the current Values. The sanitized name was working in 1.5.0 pretty sure about that. 

![image](https://user-images.githubusercontent.com/88422038/159551326-1bf65055-cf87-4519-86cb-97083fc48fe5.png)

![image](https://user-images.githubusercontent.com/88422038/159551521-b193aa10-01da-40a6-af41-f6bdf328b5bd.png)

**Comment by stumpylog** [comment]
Thank you.  I haven't actually downloaded files except through the exporter.  Is this through the API (`/api/documents/<pk>/download/`) or is there a location in the UI where you're downloading from?

**Comment by sukisoft** [comment]
I used this button in the document-details

![image](https://user-images.githubusercontent.com/88422038/159629374-88cd3ffd-1a03-44f8-8f45-e3e3f4f86755.png)

Havent tried the exporter or api yet.

**Comment by qcasey** [comment]
> The sanitized name was working in 1.5.0 pretty sure about that.

This may have been introduced in #57, which was included in 1.6.0

**Comment by tribut** [comment]
We probably should be using `quote`, not `quote_plus`.

https://docs.python.org/3/library/urllib.parse.html#url-quoting

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/47dae716ae9db1ebb6a28cfc836236a2a69422a2
