### ISSUE TITLE
STRG+C is not working inside the pdf view

### ISSUE THREAD

**Issue by lindma2** [paperless-ngx/paperless-ngx#4936]
### Description

Since i have upgrade von 1.7.13 to 2.1.1 it's not longer possible to copy text from the pdf view. (STRG+C or right click and copy, both its not working) I have also tested the browser pdf view and here is the same failure.

### Steps to reproduce

Marking Text in the PDF and STRG+C it's not working

### Webserver logs

```bash
n/a
```

### Browser logs

```bash
n/a
```

### Paperless-ngx version

2.1.1

### Host OS

Ubuntu 23

### Installation method

Docker - official image

### Browser

Chrome, Edge

**Comment by shamoon** [comment]
I dont think this would make sense with the browser PDF viewer, can you double-check that?

**Comment by lindma2** [comment]
I have checken it with both viewers (standard and browser) and its always the same. 
When i take pdf24 and open the pdf i can copy the text inside… Also it has worked with the old version 1.7.13

**Comment by shamoon** [comment]
To clarify, Im saying I think this is true only of the "paperless" pdf viewer which changed in 2.1, the browser PDF viewer shouldn't be affected. I have a fix available already if you are able to test out the docker image tagged `feature-fix-4936`. Its building currently but should be done in about 10-15 minutes, see https://github.com/paperless-ngx/paperless-ngx/actions/runs/7172861328

Thanks

**Comment by shamoon** [comment]
Once you've visited a document detail page with the "paperless" viewer enabled it would have the same effect on the browser viewer until you completely reload (empty cache to be certain) paperless with the browser viewer enabled. If that makes sense?

**Comment by akumiszcza** [comment]
I can confirm copying text does not work in paperless-ngx default PDF viewer, it works for me if I select browser PDF viewer (I use Brave for Windows with Acrobat plugin).

**Comment by shamoon** [comment]
Great thanks for confirming, there’s already a PR linked here that will fix this and it should be in our next release
