### ISSUE TITLE
[BUG] Preview on Dashboard

### ISSUE THREAD

**Issue by think-techDE** [paperless-ngx/paperless-ngx#4941]
### Description

In MS Edge is no preview on the dashboard working. I think it uses the webbrowser plugin for pdf's, the reason why it craches. 

![image](https://github.com/paperless-ngx/paperless-ngx/assets/124507707/4f0d17dc-2acf-4271-ad51-a0eb865db02c)
![image](https://github.com/paperless-ngx/paperless-ngx/assets/124507707/a285b53c-3429-4f19-a292-28285eca3fc6)

  

### Steps to reproduce

let you show new items on the dashboard

### Webserver logs

```bash
no available
```

### Paperless-ngx version

2.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Edge

**Comment by shamoon** [comment]
I don’t understand, the preview thing always uses the browser viewer. Do those documents look fine with the browser viewer when you open to ‘edit’?

**Comment by think-techDE** [comment]
with the browser viewer disabled is the preview on the dashboard broken. with activated browser viewer in Edge every preview is broken

**Comment by shamoon** [comment]
Yea there’s an open FR to make the popup previews use the same setting as edit mode, but currently it does not. And we don’t have a way to detect when the users browser pdf viewer is broken or disabled or whatever.

Out of curiosity why is the browser viewer not working in edge for you, is it disabled somehow?

Again, there’s a FR out there for this, I can look into it some time

**Comment by think-techDE** [comment]
Im using the adobe add-on in Edge, perhaps that's reason. Using the add-on because of an licence for acrobat

**Comment by shamoon** [comment]
Do you have a link or something like that for whatever tool you’re referring to?

**Comment by shamoon** [comment]
This FR: https://github.com/paperless-ngx/paperless-ngx/discussions/4524

I will see about implementing that, basically mimicking what we do in 'edit' mode
