### ISSUE TITLE
[BUG] Document metadata (and thus e.g. consumption template information) is lost on barcode split

### ISSUE THREAD

**Issue by guahki** [paperless-ngx/paperless-ngx#4959]
### Description

Documents created by splitting other documents on barcodes loose all their metadata (e.g. when the original file is read from mail, the splitted documents don't know that). I belief it was always like this, but the effect was getting worse with paperless-ngx 2, as using consumption templates does not "really" work with these documents.

### Steps to reproduce

1. have barcode splitting activated
2. create a mail account and mail rule
3. create a consumption template for the created mail rule and let it set some metadata on the document (after reviewing the code, I assume, metadata set in the mail rule directly is similary affected, but this was not tested)
4. consume two documents: one without splitting (metadata is set on this one) and a second document which is split into multiple documents by the barcodes. See, that no metadata is set on these documents.

### Webserver logs

Logs are not important here, but I dug into the code.

* During the file consumtion task, the splitting is called: https://github.com/paperless-ngx/paperless-ngx/blob/ff31558252e731b6ccbf9d7f7fa221fc54a7c141/src/documents/tasks.py#L141
* However, this does not get the full ``input_doc: ConsumableDocument``, nor the ``overrides: Optional[DocumentMetadataOverrides]``
* The splitting function thus just copies the newly split files into the consumtion directory: https://github.com/paperless-ngx/paperless-ngx/blob/ff31558252e731b6ccbf9d7f7fa221fc54a7c141/src/documents/barcodes.py#L341
* These files are read as "new" files without any metadata/metainformation from the consumption folder

### Paperless-ngx version

2.1.1

### Host OS

Linux server 6.1.63-current-meson64 aarch64 GNU/Linux

### Installation method

Docker - official image

### Other

I'm happy to try and provide a fix PR, if somebody can outline the idea of fixing this. Just copy the files in tempdirs and "manually" activate the consume task with correct metadata (similar to mail consumption)?

**Comment by shamoon** [comment]
I think we're still discussing if this is really a bug or maybe just unsupported. Funny enough, Ive never seen anyone using barcode splitting via email. And any change to support this wouldn't be trivial, though it may be possible by reworking some things.

**Comment by guahki** [comment]
Fair enough. If you say, it‘s unsupported, I would be a little sad, but eventually get over it for sure ;)

Actually due to some specialties in my setup it‘s currently hard to use the consumption folder. I drop files from my computer or mobile phone just on the webapp (API-upload) and my scanner just sends mails. Thus, I would like to have this feature working.

About changes to support this: for sure, these changes would be non-trivial, but I would assume a similar structure as with mail-downloads in general might be possible: copy the file to a temp-folder and „manually“ create the consume task. Then you can easily pass the original ConsumableDocument and overrides, preserving all (at least I think it’s all?) the metadata. As said, if you guys would be open for this, I might try to give it a go if this helps you.

**Comment by guahki** [comment]
Thank you very much for the quick fix and release, @stumpylog!
