### ISSUE TITLE
[BUG] Increase PAPERLESS_WORKER_TIMEOUT results in a django warning

### ISSUE THREAD

**Issue by oxi0** [paperless-ngx/paperless-ngx#496]
**Describe the bug**
When I increase PAPERLESS_WORKER_TIMEOUT and change the value from 1800 to 3600, I will get Warnings on Docker-Log.
Occurs since the following PR https://github.com/paperless-ngx/paperless-ngx/pull/37

**To Reproduce**
1. Change Config PAPERLESS_WORKER_TIMEOUT  to 3600
2. See warning messages in docker-logs

**Expected behavior**
No warnings from django

**Webserver logs**
 ```
paperless_1          |         /usr/local/lib/python3.9/site-packages/django_q/conf.py:139: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout,
paperless_1          |         failure to do so will cause the tasks to be retriggered before completion.
paperless_1          |         See https://django-q.readthedocs.io/en/latest/configure.html#retry for details.
```

**Relevant information**
 - Host OS of the machine running paperless: Debian 11.2
 - Docker Image: ghcr.io/paperless-ngx/paperless-ngx:latest
 - Version: 1.6.0
 - Installation method: docker

**Comment by stumpylog** [comment]
I see.  It should be simple enough to include configuration of the retry value for cases like this.  That will silence the warning.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/eb5e0e0b9bb5647da73c784644104be14c51298b
