### ISSUE TITLE
[BUG] Datev PDFs are missing many characters in paperless-ngx viewer 

### ISSUE THREAD

**Issue by Atemu** [paperless-ngx/paperless-ngx#5004]
### Description

When I upload my payroll documents (PDF files generated by Datev), the fields with data are missing most of their characters when viewed inside the Paperless view window.

Since this is very personal information, I cannot share the PDF and getting a screenshot wasn't easy either but it does print a generic text here:  

![image](https://github.com/paperless-ngx/paperless-ngx/assets/18599032/946edb02-00d4-4dd0-9723-b4fbd0d81dc0)

If it wasn't obvious, this says `www.datev.de/lohn-id`. The actual fields with numbers also look like this. The structural elements and field descriptions themselves are all fine; it's just the data of the fields (in monospaced font).

The PDFs themselves are fine; downloading the original or archive and viewing them inside the same browser works as expected. This only happens inside the Paperless viewer.

### Steps to reproduce

1. Take payroll document generated by Datev ("Arbeitnehmer online")
2. Upload to Paperless
3. Open the document such that it's open inside the viewer

### Webserver logs

Nothing interesting in the logs:

```
Dec 13 21:28:26 SOTERIA systemd[1]: Started Paperless web server.
Dec 13 21:28:31 SOTERIA gunicorn[1795]: [2023-12-13 21:28:31 +0100] [1795] [INFO] Starting gunicorn 20.1.0
Dec 13 21:28:31 SOTERIA gunicorn[1795]: [2023-12-13 21:28:31 +0100] [1795] [INFO] Listening at: http://0.0.0.0:28981 (1795)
Dec 13 21:28:31 SOTERIA gunicorn[1795]: [2023-12-13 21:28:31 +0100] [1795] [INFO] Using worker: paperless.workers.ConfigurableWorker
Dec 13 21:28:31 SOTERIA gunicorn[1795]: [2023-12-13 21:28:31 +0100] [1795] [INFO] Server is ready. Spawning workers
Dec 13 21:29:14 SOTERIA gunicorn[1995]: /nix/store/xsah5009wzh6wcqfva01w5dnxfknxsnh-python3.10-Django-4.2.7/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
Dec 13 21:29:14 SOTERIA gunicorn[1995]:   warnings.warn(
```

### Browser logs

```
downloadable font: CFF : Failed validating CharStrings INDEX (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f3" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
Warning: Failed to load font 'g_d0_f3': 'SyntaxError: An invalid or illegal string was specified'. main.js:3:1196338
Warning: Out of bounds subrIndex for callgsubr 13 pdf.worker.min.js:22:21471
downloadable font: CFF : Failed validating CharStrings INDEX (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: CFF : Failed to parse table (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: rejected by sanitizer (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
downloadable font: font load failed (font-family: "g_d0_f4" style:normal weight:400 stretch:100 src index:0) source: (invalid URI)
Warning: Failed to load font 'g_d0_f4': 'SyntaxError: An invalid or illegal string was specified'. main.js:3:1196338
Warning: Out of bounds subrIndex for callgsubr 37 pdf.worker.min.js:22:21471
```

### Paperless-ngx version

1.17.2

### Host OS

NixOS, macOS

### Installation method

Bare metal

### Browser

Firefox

### Configuration changes

https://github.com/Atemu/nixos-config/blob/b1e3e3fca125364dd5ed877fdc5ecf0fa5119271/modules/paperless/module.nix#L20-L41

**Comment by shamoon** [comment]
As is noted in the template if this is an issue with OCR the issue should be raised upstream. If you’re saying both the archive and original files are ok you’ll want to switch the app to use the browser PDF viewer under settings

**Comment by Atemu** [comment]
As mentioned, this is not related to OCR. There is no OCR to be done here as this is a digitally created PDF. You can copy the text out of the "original". 

Switching the app to use the browser PDF viewer does indeed resolve the issue.

**Comment by shamoon** [comment]
The paperless viewer uses pdfjs (though unfortunately not the most recent version yet). You said you can't, but if you can somehow supply a sample I can check it out to see if there's a know pdfjs issue
