### ISSUE TITLE
[BUG] The annual selection is truncated

### ISSUE THREAD

**Issue by Vertux** [paperless-ngx/paperless-ngx#5019]
### Description

When I try to change the creation date (e.g. 04.11.2000) of a document by clicking on the calendar and opening the year selection list, the list is truncated. In my example, the list ends at 2010. It was therefore impossible for me to select a date in 2023, for example. See screenshot:

<img width="515" alt="Bildschirmfoto 2023-12-17 um 17 01 18" src="https://github.com/paperless-ngx/paperless-ngx/assets/10457918/d470cf9b-624b-4504-afd5-820ac9c0924a">

### Steps to reproduce

As described above.

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.1.3 

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Firefox 120.0.1 (64-Bit)

### Configuration changes

PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}/{document_type}/{created}-{title}

**Comment by shamoon** [comment]
Yes, the current limit is 10 years, I suppose it could be increased but it's not unintentional (not a bug).

**Comment by shamoon** [comment]
Note: theres no perfect value, if we made it 100 years that dropdown would, of course, be unusable

**Comment by Vertux** [comment]
> Yes, the current limit is 10 years, I suppose it could be increased but it's not unintentional (not a bug).
> Note: theres no perfect value, if we made it 100 years that dropdown would, of course, be unusable

10 years is definitely not enough, especially if the "base date" for the 10 years is not the current year, but the (wrong) creation date of the document, which could be 1980, then the drop-down list is even more useless. It is simply a bad user experience when you want to use a convenience feature that suddenly does not work the way you expect it to. 
I actually see no problem with making it 100 years because the drop-down list is scrollable.

**Comment by shamoon** [comment]
Im really not trying to be argumentative here, but:

- You are stating things as if they are fact ("definitely", "bad") when they are clearly subjective.
- UX is tricky, very much 'you cant make all the people happy all the time'. More often than this situation, the date is close-enough that 10y is fine, or the correct date is suggested.
- In your example of making the dropdown 100 years, I would argue scrolling that huge list would be horribly-annoying, and what most people would in fact do would be to type the year they want. In that case, it would be simpler to just type that year into the field itself... so nothing gained.

**Comment by Vertux** [comment]
> * You are stating things as if they are fact ("definitely", "bad") when they are clearly subjective.

Please forgive my probably poor choice of words, but I am not a native English speaker. I have only described my personal experience, which I assume other users feel the same way about - this is subjective, of course. I am not judging, just pointing out an unpleasant and unexpected behaviour of the user interface. I can't quite understand why you're reacting so negatively. I think I have explained my opinion to you in an understandable and solid way. To be clear, I am interested in constructive criticism. 

I am quite surprised and disappointed that you are obviously not even willing to think about my suggestion.

> * UX is tricky, very much 'you cant make all the people happy all the time'. 

I agree with you, I don't blame you either.

> More often than this situation, the date is close-enough that 10y is fine, or the correct date is suggested.

That is a very weak, unproven thesis. Just for comparison, the retention period for important documents is 10 years.

> * In your example of making the dropdown 100 years, I would argue scrolling that huge list would be horribly-annoying, and what most people would in fact do would be to type the year they want. In that case, it would be simpler to just type that year into the field itself... so nothing gained.

Don't you think it should be up to the user to decide whether or not to scroll through a list of 100 items? Everyone has the alternative of typing it in, but at least you don't stumble over what I consider to be a very hard limit. When you're a user of a calendar widget, you don't expect an arbitrarily limited choice, which is unexpected and unpleasant. Let's put it another way: For me, it's a small unsightly detail in the user interface that I wanted to point out nicely - no more, no less.

I would like to take this opportunity to thank all the developers for the great software and wish everyone a Merry Christmas 🎄
