### ISSUE TITLE
[BUG] App log-in getting stuck in authentification on Google Pixel 7

### ISSUE THREAD

**Issue by HighTac** [paperless-ngx/paperless-ngx#5024]
### Description

I'm running Paperless on a DS224+ and it has worked flawlessly for multiple months. It still does via browser, but the Android App has stopped working (on my Google Pixel 7). Whenever I try to log into my account, it gets stuck, the authentification circle is still circling, but that's it. I tried to reinstall, but the issue remains.

### Steps to reproduce

1. Go to Android App
2. Try to log in to Paperless Acc

### Webserver logs

```bash
2023-12-17 20:11:36.501	DEBUG   --- [      AuthenticationCubit] - login                    : Trying to log in Mox@19***03...
2023-12-17 20:11:36.502	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Adding new user Mox@19***03..
2023-12-17 20:11:36.502	DEBUG   --- [      AuthenticationCubit] - _addUser                 : Fetching bearer token from the server...
```

### Paperless-ngx version

1.17.4

### Host OS

Synology on DS224+

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
We do not make the android app
