### ISSUE TITLE
[BUG] Changing your name with "Edit Profile" logs you out

### ISSUE THREAD

**Issue by novahahn** [paperless-ngx/paperless-ngx#5027]
### Description

If you change your name using the new "Edit Profile" view, you are logged out. Paperless-ngx displays the message "Password has been changed, you will be logged out momentarily." This does not happen when using `/usersgroups`.

### Steps to reproduce

1. Click on your name on the top right
2. Click "My profile"
3. Edit your first or last name.[^1] Do not change anything else.
4. Click "save"

[^1]: adding a space in the end is sufficient and doesn't cause any actual changes

### Webserver logs

```bash
No output from `docker-compose logs --follow webserver` while reproducing the issue
```

### Paperless-ngx version

2.1.3

### Host OS

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-89-generic aarch64)

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Yea, this is a regression
