### ISSUE TITLE
[BUG] OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by Carsten3110** [paperless-ngx/paperless-ngx#5036]
### Description

Since update to version 2.1.2 paperless reports "OSError: [Errno 28] No space left on device" at the log. This repeats continuesly. Also a complete new installation did not help. Continuing with this problem the consumer is repeating to handle files more than once (no end).

[docker-compose-env.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13703309/docker-compose-env.pdf)
[docker-compose-yml.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13703310/docker-compose-yml.pdf)
[paperless-ngx-webserver-1.pdf](https://github.com/paperless-ngx/paperless-ngx/files/13703353/paperless-ngx-webserver-1.pdf)

paperless-ngx image provided by ghcr.io for synology 

### Steps to reproduce

Superuser has been created during first installation via ssh login

1. login to dsm as an administor to DSM
2. start container manager
3. create the necessary folders (data, pgdata, media, export) underneath the paperless-ngx folder.
4. create a project with the provided docker-compose.yaml by "https://www.digitalisierung-mit-kopf.de"
6. start the project.

### Webserver logs

```bash
see attached files
```

### Paperless-ngx version

>2.1.2

### Host OS

Synology DSM 7.2.1-69057 Update 3

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The error seems quite clear and is not an issue with paperless.  I would trust that Python is correct and there is no space left or a quota has been reached.
