### ISSUE TITLE
[BUG] Mail Import broken

### ISSUE THREAD

**Issue by t0mcat1337** [paperless-ngx/paperless-ngx#511]
**Describe the bug**
Found multiple bugs when trying to consume Mails via IMAP:

When creating an EMail Rule which should work at an IMAP (Sub)Folder, the GUI sais subfolders should be seperated by "." . This is wrong - in my case - as SubFolders are seperated by "/". Listing my IMAP Folders with a little Python Script using imap_tools gives this for example:

`FolderInfo(name='INBOX/2DMS', delim='/', flags=('\\HasChildren',))`
(note the "/" as delimiter)

When entering this Folder seperated by "." as the GUI sais:

![image](https://user-images.githubusercontent.com/3826246/159741159-b920929d-58d2-48b1-a144-79106b47c8de.png)

No Mail is imported by the Job "Check all e-mail accounts" (process_mail_accounts) and this can be found in the logs:

```
16:50:41 [Q] INFO Enqueued 1
16:50:41 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
16:50:41 [Q] INFO Process-1:1582 processing [winter-oregon-sodium-asparagus]
[2022-03-23 16:50:41,611] [ERROR] [paperless_mail] Rule ***.GetMails: Error while processing rule: Rule ***.GetMails: Folder INBOX.2DMS does not exist in account ***
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 192, in handle_mail_rule
    M.folder.set(rule.folder)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/folder.py", line 44, in set
    check_command_status(result, MailboxFolderSelectError)
  File "/usr/local/lib/python3.9/site-packages/imap_tools/utils.py", line 45, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxFolderSelectError: Response status "OK" expected, but "NO" received. Data: [b'SELECT error getting mails in folder']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 177, in handle_mail_account
    total_processed_files += self.handle_mail_rule(M, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 194, in handle_mail_rule
    raise MailError(
paperless_mail.mail.MailError: Rule ***.GetMails: Folder INBOX.2DMS does not exist in account ***
```
"Folder INBOX.2DMS does not exist in account" is quit correct as the Folder is "INBOX/2DMS".

Sidenote:
In the GUI the obviously failed job can be found under "Successful tasks", not under "Failed Tasks" which for me is a bug, either:
![image](https://user-images.githubusercontent.com/3826246/159742553-76836da9-e45c-46e1-9bb9-0003f675c511.png)

When correcting the Folder delimiter to "/" for matching the SubFolder Name:

![image](https://user-images.githubusercontent.com/3826246/159743047-324ffe96-b3c8-48b7-8871-801c954d6445.png)

another error is in the logs:

```
17:02:43 [Q] INFO Enqueued 1
17:02:43 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
17:02:43 [Q] INFO Process-1:1584 processing [monkey-blue-maine-network]
[2022-03-23 17:02:45,251] [ERROR] [paperless_mail] Rule ***.GetMails: Error while processing mail 668684: argument of type 'EmailAddress' is not iterable
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule
    processed_files = self.handle_message(message, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 266, in handle_message
    correspondent = self.get_correspondent(message, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 138, in get_correspondent
    and "name" in message.from_values
TypeError: argument of type 'EmailAddress' is not iterable
[2022-03-23 17:02:45,309] [ERROR] [paperless_mail] Rule ***.GetMails: Error while processing mail 670533: argument of type 'EmailAddress' is not iterable
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 222, in handle_mail_rule
    processed_files = self.handle_message(message, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 266, in handle_message
    correspondent = self.get_correspondent(message, rule)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 138, in get_correspondent
    and "name" in message.from_values
TypeError: argument of type 'EmailAddress' is not iterable
```

So the folder is found now but sth. is wrong when working on the contained mails.

And as described in the sidenote above, this job is found under "Successful tasks" too:
![image](https://user-images.githubusercontent.com/3826246/159743815-01ff90ed-98ba-443a-8258-fb03f9a52575.png)

**Relevant information**
 - Host OS of the machine running paperless: Debian
 - Browser Chrome
 - Version 1.6.0
 - Installation method: docker

**Comment by stumpylog** [comment]
> TypeError: argument of type 'EmailAddress' is not iterable

This error was fixed in #393

However, I do agree the documentation for email consumption and settings could use further details.  In particular, I'm not sure the folder delimiter of `.` is always valid.  As in your case, it appears a `/` is used.  This seems to vary by the server.

**Comment by shamoon** [comment]
So Im guessing we dont have an easy way to know ahead of time when the user is setting up rules (I know he said 'imap_tools' reports the delimiter but we're not going to ping the server a priori) but perhaps changing the instructions under the field as well as reporting a more helpful error?

**Comment by t0mcat1337** [comment]
> So Im guessing we dont have an easy way to know ahead of time when the user is setting up rules (I know he said 'imap_tools' reports the delimiter but we're not going to ping the server a priori) but perhaps changing the instructions under the field as well as reporting a more helpful error?

Changing the instructions has to be done, IMHO, as the current one could be misleading.
Could it be worth thinking about some sort of Select Box / Drop Down, which let the user select the folder instead of a plain text field? This would 1. be more user friendly and 2. eliminates the need of knowing the delimiter ahead of time? Could imagine, not technically interested users even know which delimiter will be the correct one...

Concerning the error handling:
It would absolutly make sense, that the errored task should not appear under "Successful Tasks" but in "Failed Tasks" with a - more or less - speaking error message.
For tracking down, why mails aren't imported, I had to use "docker logs....", which shouldn't be the standard in case of failing jobs.  
 

 
Concerning error reporting

**Comment by shamoon** [comment]
> So when will the fix be merged to main and so enters a new version (1.6.1. for example?) As this bug competely breaks mail import functionality.....

As soon as we release it. Please remember we are all volunteers, everyone who is fixing bugs has all of the other things in their life going on. We havent discussed timeline of a next release, there are a bunch of things still in progress but are hopefully approaching one soon.

**Comment by balanceofcowards** [comment]
For those interested: I just stumbled across the `'EmailAddress' is not iterable` bug, as well. There is a quick work-around until the bug fix lands: Modify the respective rule(s) to not assigning a correspondent. Then assign correspondents manually, in the meanwhile. A slight nuisance, but better than a broken e-mail import, I guess.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/8f98cb486011c3253c2d067bde308b6582bc9b5a & https://github.com/paperless-ngx/paperless-ngx/commit/f74e15840d9e239fb29876eee7e0c50b91d7b2d2
