### ISSUE TITLE
[BUG] Bulk-editing one permission overwrites all permissions

### ISSUE THREAD

**Issue by flemmingss** [paperless-ngx/paperless-ngx#5118]
### Description

I found out this when I tried to bulk-add all my 500+ documents, I set my "Husholding" group to view and edit all documents. When that was done I see that no documents has any ownership anymore.

I tested a little more, looks like if you change something with the "Permissions" button in document view, all parameters under Permissions is updated, including "Owner", "View:Users", "View:Groups", "Edit:Users" or "Edit:Groups".
Even if you don't apply a new value, it just update to "empty".
In other words: You can't edit just one/some of these parameter and leave the others alone. 

In the three pictures before you see I add a owner, then the other permission parameters gets removed.
![1](https://github.com/paperless-ngx/paperless-ngx/assets/25674067/6b8e7165-16e9-4013-afb9-e3e88705e883)
![2](https://github.com/paperless-ngx/paperless-ngx/assets/25674067/0bcffb46-4590-404e-8542-8f7ee4416289)
![3](https://github.com/paperless-ngx/paperless-ngx/assets/25674067/2fab187d-4484-4363-9b7a-41f1c9a2bf45)

### Steps to reproduce

1. mark document(s) in "documents"
2. Select "Permissions"
3. Write a new value just for "Owner", "View:Users", "View:Groups", "Edit:Users" or "Edit:Groups"
4. Open the document(s), see that the other parameters values has been removed

### Webserver logs

```bash
nothing relevant
```

### Paperless-ngx version

2.1.3

### Host OS

UnRAID

### Installation method

Docker - official image

### Browser

Google Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
That is expected, at least for now. See the note at the top of that dialog:
<img width="590" alt="Screenshot 2023-12-27 at 9 57 07 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/29533c54-042e-4329-aa51-f4fdd1d8a308">

**Comment by tooomm** [comment]
Hmm. Reading this issue, it sounds to me like the hint you are pointing at is not giving the full story, shamoon. And users will run into issues with this and be puzzled what is happening, and why.

I think the confusing part here is, that something they don't set (never touching a specific field in the dialog), still leads to values being overridden and deleted in this case. Only the ones that are actually changed/updated should populate though.
That is not expected, and the note is not telling that either.

If it's not fixed, it should be a better describing hint - probably even a warning in red!

Or am I misunderstanding this?

**Comment by shamoon** [comment]
I mean, I guess we can debate the wording and the noticeability of the color, etc. but Im saying what is happening is not unintentional. Yes I agree there could be improvement, maybe a kind of checkbox or something to choose "overwrite everything" but there does need to be a way to _remove_ permissions in bulk edit (that was an initial change request), and thats what this currently allows. Im happy to look at this at some point if someone wants to open a FR or there may be one already, I dont remember

**Comment by flemmingss** [comment]
When I read "permissions set here" I assume permissions I don't set (empty) is not changed, so it can be ambiguous and misleading how it is now.

I think some check boxes like this can be a good solution.
- Not checked by default
- If checked delete value
- If checked disable the dropdown
![image](https://github.com/paperless-ngx/paperless-ngx/assets/25674067/94334e9f-223c-4978-9620-2977b63fd2d4)
