### ISSUE TITLE
[BUG] Rootless container does not work if `PAPERLESS_OCR_LANGUAGES` are set

### ISSUE THREAD

**Issue by beatbrot** [paperless-ngx/paperless-ngx#5119]
### Description

The paperless docker container does not start, when running as regular user (UID 1000) and PAPERLERSS_ORCR_LANGUAGES are specified.

The reason for that is that the entrypoint script tries to install the additional languages via apt at startup. This obviously does not work without root permissions.

On a sidenote: The installation of languages via apt also prevents us from running the container with a read-only root FS. This is especially popular in kubernetes environments (see https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).t

### Steps to reproduce

Use the sample [docker-compose.sqlite.yaml](https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/compose/docker-compose.sqlite.yml) and specify the following variables in the matching .env file:

```env
USERMAP_UID=1000
USERMAP_GID=1000
PAPERLESS_OCR_LANGUAGES=deu eng
```

### Webserver logs

```bash
Paperless-ngx docker container starting...
Installing languages...
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

### Paperless-ngx version

2.1.3

### Host OS

Docker Desktop (Windows 11)

### Installation method

Docker - official image

### Configuration changes

USERMAP_UID=1000, USERMAP_GID=1000, PAPERLESS_OCR_LANGUAGES=deu eng

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
If you have only set UID/GID via the environment, that works fine.  If you have added `user:` or other root-less settings, this is very expected and not something we're going to even attempt to support.  

You need to be root to install packages.  That's just a fact.  If you simply must run as non-root, the only solution is to build your own image with the extra tesseract packages installed.

**Comment by beatbrot** [comment]
@stumpylog Wow, thanks for the very fast response! What would you think about a PR that mentions this fact in the documentation? I am thinking about adding a sentence or warning to the rootless section of this page: https://docs.paperless-ngx.com/setup/#docker_hub

**Comment by stumpylog** [comment]
Sure, there probably needs to be a caveats or warnings section

**Comment by beatbrot** [comment]
@stumpylog Sorry to bother again :) 
I think I got a solution on how we could support this setting in non-root scenarios. Maintenance would be low. Would you mind me opening a PR to show my suggestion?

**Comment by stumpylog** [comment]
How about point me to a branch and give any explanations here.

**Comment by beatbrot** [comment]
@stumpylog Sure thing! So the branch is right here: https://github.com/beatbrot/paperless-ngx/tree/rootless_experiments

As you can see, the idea is that we extract all operations that require root permissions to separate scripts. These scripts are added to the sudo-configuration and are allowed to be executed. Executables not listed in the sudoers configuration can not be executed. This gives us a little "escape-hatch" in cases where we need root for a bit. After the scripts are done, they remove their entry from the sudoers configuration so that noone can later execute them and poke for privilege escalation bugs.

Of course, the simpler version would be to set the suid bit, but unfortunately most kernel do not respect the suid bit for scripts and setting it on bash itself would be completely overkill.

I tried this draft solution on my machine and it worked just fine. Of course, we gain a dependency to sudo, but to be honest it seems like a drop in the ocean compared to all other dependencies we need.

What do you think? :)
