### ISSUE TITLE
[BUG] compiled qpdf missing in amd64 docker image

### ISSUE THREAD

**Issue by Latschenharry** [paperless-ngx/paperless-ngx#513]
**Describe the bug**

**To Reproduce**
pre consmption script with qpdf gives error command not found

**Expected behavior**
script being able to run qpdf to process pdf files

**Screenshots**

**Relevant information**
 - Synology Intel 
 - Browser [Edge]
 - Version [e.g. 1.6.0]
 - Installation method: [docker]
 - qpdf still present in arm builds
 - qpdf was present in paperless-ng

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/9737e4a24d9bd2378204fd67e3458e543fe3ed1c
