### ISSUE TITLE
[BUG] Dropdown for Document owner broken after v2.2.0 update

### ISSUE THREAD

**Issue by BWibo** [paperless-ngx/paperless-ngx#5131]
### Description

After updating to v2.2.0, the dropdown menu for setting the document owner seems to be broken.
Instead of the entries, gray lines appear. When I click on the menu entires, the correct values is used. Seems to be just a display error. The other dropdowns on this page work fine.

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/7643434/e95e8603-a6b8-4727-bddd-8c099188b109)

### Steps to reproduce

1. Select a document and try to change its owner

### Webserver logs

```bash
no errors shown
```

### Paperless-ngx version

2.2.0

### Host OS

Raspberry Pi 4, Ubuntu 22.04 x64 server

### Installation method

Docker - official image

### Browser

Tested with Firefox, Brave (chromium)

### Configuration changes

https://github.com/BWibo/paperless-ngx-compose

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by SchwarzBunt** [comment]
Same Problem here on a Raspberry Pi 4 4GB aarch64 debian 12 and Lenovo m93p x64 8GB debian 12
![Paperless_v2 2_bug](https://github.com/paperless-ngx/paperless-ngx/assets/155079413/8039c12a-2624-4c73-86ec-e070e041c942)
