### ISSUE TITLE
[BUG] Non-http/https URLs erroneously considered invalid

### ISSUE THREAD

**Issue by pm64** [paperless-ngx/paperless-ngx#5151]
### Description

When entering the value for a custom field of type "link", URLs using a protocol other than http or https do not pass validation. Any URL that conforms to RFC 3986 should be considered valid, whether or not Paperless-ngx recognizes the protocol.

Examples:

      ftp://ftp.is.co.za/rfc/rfc1808.txt
      http://www.ietf.org/rfc/rfc2396.txt
      obsidian://open?vault=Vault&file=fields%2Fai%2Fai
      ldap://[2001:db8::7]/c=GB?objectClass?one
      mailto:John.Doe@example.com
      news:comp.infosystems.www.servers.unix
      tel:+1-816-555-1212
      telnet://192.0.2.16:80/
      urn:oasis:names:specification:docbook:dtd:xml:4.1.2

See https://datatracker.ietf.org/doc/html/rfc3986

### Steps to reproduce

1. Log into the Web UI of a Paperless-ngx instance containing a custom field of type "link" and at least one document.
2. Add the link custom field to the document.
3. In the custom field input, enter any URL using a protocol other than http or https.
4. Observe the entry is rejected with the error "Enter a valid URL"

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.2.1

### Host OS

macOS

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
We use [Django's URLValidator](https://docs.djangoproject.com/en/5.0/ref/validators/#urlvalidator):

https://github.com/paperless-ngx/paperless-ngx/blob/f355e3011a7db6c9dd951c3667a08b98993132c7/src/documents/serialisers.py#L502

If theres a bug in their implementation perhaps you should raise an issue at that project. Also, I think some of those URLs work fine, e.g.

<img width="1521" alt="Screenshot 2023-12-29 at 12 52 51 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/93766c73-dd21-450c-8b9c-1a1e2b29db15">

**Comment by pm64** [comment]
@shamoon I appreciate your quick read of this issue -- but after reviewing [Django's URLValidator](https://docs.djangoproject.com/en/5.0/ref/validators/#urlvalidator), it seems that Paperless-ngx has simply chosen to not use the full set of features provided by Django that would permit Paperless-ngx to validate the "full list of valid URI schemes".

```
class URLValidator(schemes=None, regex=None, message=None, code=None)
```
```
schemes:
    URL/URI scheme list to validate against. If not provided, the default list is ['http', 'https', 'ftp', 'ftps']. As a reference, the IANA website provides a full list of [valid URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).
```

According to Django's docs, by ignoring the `schemes` parameter, Paperless-ngx is not respecting the "full list of VALID URI schemes".

To address your suggestion -- there doesn't appear to be any bug in Django's implementation, so it wouldn't make sense to engage that team. However, Paperless-ngx is misusing Django's URLValidator by representing to the user that any valid URL will be accepted, then explicitly telling URLValidator to ignore the majority of valid URLs.

If you're opposed to considering the above a bug, then the bug would be the validation message displayed to the user, misidentifying valid URLs as "invalid". In that case, the message should read "Enter a valid http, https, ftp, or ftps URL" to make it clear that other protocols will be rejected.

So, which is the defect -- rejection of valid URLs, or claiming to respect valid URLs? I suppose either one could qualify.

I would just comment that it seems like an odd choice to intentionally use Django URLValidator in a way that deprives your users of useful functionality, fully supported by Django, with the IANA website providing a full list of [valid URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml).

Opening up these additional protocols does not affect the document management workflow at all, it only empowers your users with added flexibility for free. Shouldn't the user be in charge of which protocols they want their links to use? I guess that's the question.

**Comment by shamoon** [comment]
Ah, I didn't realize the default settings for URLValidaator limit the protocol, thanks for pointing that out. I guess maybe it’s sort of a feature request but let’s not quibble, I’ll be happy to change it

**Comment by pm64** [comment]
Thank you @shamoon for your openness to examining this further, and for all of your amazing efforts on this project.

I'm not 100% sure how to advise on expanding the set of accepted protocols, though. Maybe you have some thoughts.

A common use case for additional protocols will be linkage of documents in Paperless-ngx to entries in knowledge management systems.

For example, you can see that IANA lists "onenote://" as a valid URI scheme.

But I use Obsidian, which uses the "obsidian://" URI scheme, which is not listed by IANA. So if you simply use IANA's list, many users will benefit, but my specific requirement won't be satisfied.

Likewise, I'm not seeing a way to make URLValidator accept "any" URI scheme.

So maybe the answer is a new optional setting, where the user may specify the comma-separated list of protocols (beyond http/https/ftp/ftps) they wish to use?

Also - would never dream of quibbling :) Just want to make sure you have all the info. But as a noob in an extremely important and respected project, I will concede anything at the drop of a hat :)
