### ISSUE TITLE
[BUG] Paperless-ngx 2.2.1 +  Gotenberg 7.10.0 / 7.10.1 / 7.10.2

### ISSUE THREAD

**Issue by ctout76** [paperless-ngx/paperless-ngx#5197]
### Description

Happy New Year!

Hello, I am encountering a problem from Gotenberg version 7.10.0  (same problem with versions 7.10.0 - 7.10.1 - 7.10.2)
For example, when converting .xlsx or .pptx files, I often get the following error message:

file.xlsx: Error occurred while consuming document file.xlsx: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'

As soon as I force install Gotenberg 7.9.2, I don't encounter any problems !

### Steps to reproduce

Paperless-ngx 2.2.1 +  Gotenberg 7.10.0, 7.10.1 or 7.10.2 -> NOK

Paperless-ngx 2.2.1 +  Gotenberg 7.9.2 -> OK

### Webserver logs

```bash
file.xlsx: Error occurred while consuming document file.xlsx: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
```

### Paperless-ngx version

2.2.1

### Host OS

Zorin OS 17 (Ubuntu 22.04)

### Installation method

Docker - official image

### Browser

Mozilla Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
HTTP 503 is a server error.  That means Gotenberg's error.  You can examine Gotenberg's logs to find out more information and report this (or search their issues for further information).
