### ISSUE TITLE
[Other] Update name to paperless-ngx in docs

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#52]
https://github.com/paperless-ngx/paperless-ngx/issues/4#issuecomment-1039890021

> I would go through the places where the project name is mentioned and add the x to it. Only actually code (variable names) could remain unchanged for backwards compatibility.

**Comment by filcuk** [comment]
`vars/paperless-ng.yml` and similar will have to stay as they are for backwards compatibility.
Some links can't be changed yet, for example `https://github.com/jonaswinkler/paperless-ng.git.master` doesn't exist on ngx.
We don't have a release at the moment; `image: jonaswinkler/paperless-ng:0.9.x`.

I can go through whatever can be updated though, then update the rest gradually.

**Comment by qcasey** [comment]
Done in #195
