### ISSUE TITLE
[BUG] Delete option of document_exporter not working

### ISSUE THREAD

**Issue by Inervo** [paperless-ngx/paperless-ngx#5232]
### Description

I'm using paperless-ngx in a docker container on a synology (last version).

I've set a cron task to export my paperless data daily, and specified the option -d to delete the existing files in the target directory.
Unfortunately, the existing files never gets removed.
I've tried with -d, --delete, from the docker image itself as well as from outside the docker, the export always work, but the existings files remains.
The rights are correctly configured, i've even tried with 777. 
Nothing appears in the log.

If anyone have an idea, 

### Steps to reproduce

1. Have existing files in the export folder (for exemple, old_export.zip)
2. Execute the command `docker exec paperless-webserver document_exporter ../export -d -na -nt  -z`
3. Check the files in the export folder. The previously existing files still remains. I now have the new export-XX-XX.zip as well as old_export.zip

### Webserver logs

```bash
(nothing there)
```

### Paperless-ngx version

2.2.1

### Host OS

Synology DSM 7.2.1-69057 Update 3

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
If you're using the zip export, delete is not going to do anything. It's just outputting a zip of everything to the given directory.

**Comment by Inervo** [comment]
This explains it. Thanks for the info :)

**Comment by stumpylog** [comment]
After thinking about it some more, it is inconsistent.  It's a little odd I think to request `--delete` with `--zip`, but we can still clear everything out of the destination folder.  So it will be a use with caution option

**Comment by Inervo** [comment]
Thanks a lot for giving a thought to this.

The idea to combine `--delete` with `--zip` is: I make a daily backup of paperless to a private dropbox. The objective is to keep this archive in case my synology crash completly. But i don't want 1 zip  for each day (because 340Mo x 30 days for each month, i'll reach my dropbox quota really quickly). That's why I just want the last one, the more up-to-date :)
