### ISSUE TITLE
[BUG] Password is shown instead of username

### ISSUE THREAD

**Issue by lukabeli** [paperless-ngx/paperless-ngx#5233]
### Description

I created a second user. 

After logging in with this user a welcome screen appears: "Hello **password**, welcome to paperless-nix".

The welcome message containes the readable password instead of the username!

### Steps to reproduce

see Description

### Webserver logs

```bash
.
```

### Paperless-ngx version

2.2.1

### Host OS

Synology / Container

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

no

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by ignoreigor** [comment]
Hi,

can't reproduce this behaviour. Creating a new user the greeting is: "Hello forename, welcome ..." using paperless-ngx 2.2.1. 
Maybe a localization-issue? I am using german language for ui.

**Comment by ignoreigor** [comment]
if it's a bug at all, it must be in your locales:

src-ui/src/locale/messages.de_DE.xlf

```
      <trans-unit id="1865646076514070962" datatype="html" approved="yes">
        <source>Hello <x id="PH" equiv-text="this.settingsService.displayName"/>, welcome to Paperless-ngx</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/components/dashboard/dashboard.component.ts</context>
          <context context-type="linenumber">38</context>
        </context-group>
        <target state="final">Hallo <x id="PH" equiv-text="this.settingsService.displayName"/>, willkommen bei Paperless-ngx</target>
      </trans-unit>
```


paperless-ngx/src-ui/src/app/services/settings.service.ts
```
  get displayName(): string {
    return (
      this.currentUser.first_name ??
      this.currentUser.username ??
      ''
    ).trim()
  }
```

this fits to my observation

**Comment by lukabeli** [comment]
You were right, issue no longer exists...
