### ISSUE TITLE
[BUG] npm ERR! The Cypress App could not be installed. Your machine does not meet the operating system requirements.

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#524]
**Describe the bug**

Looks to be during the `compile-frontend` step of the armv7 build: 

```
#36 1261.5 npm ERR! The Cypress App could not be installed. Your machine does not meet the operating system requirements.
```

https://github.com/paperless-ngx/paperless-ngx/runs/5684745310?check_suite_focus=true

**Relevant information**
GitHub actions

**Comment by shamoon** [comment]
Cypress is for the new e2e testing #503  introduced by @FrankStrieter 

I’m not sure how to interpret all of https://github.com/cypress-io/cypress/issues/4478 but unless we have a quick solution I suppose we can just modify ci to skip e2e tests on armv7. Obviously there’s some risk that the tests would actually be failing on armv7 and we wouldnt know but that doesn’t seem super likely given our stack and what the e2e tests are actually checking. Anyone have concerns about that potential solution? Other ideas?

**Comment by qcasey** [comment]
Ok, thanks. I'm good with that solution, it's still better than the 0 e2e tests we had a week ago! I'll leave it up to you all though.

**Comment by FrankStrieter** [comment]
I'll take care of it.

**Comment by FrankStrieter** [comment]
@shamoon not the tests are failing, it is the build. We do not need cypress anymore at the build step, so we can skip the installation of it.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/00eff651e62f6aea4b528800b0f18456d68b2e58
