### ISSUE TITLE
[BUG] Date order did not change after modifying PAPERLESS_DATE_ORDER

### ISSUE THREAD

**Issue by errolsancaktar** [paperless-ngx/paperless-ngx#5240]
### Description

Did not realize that paperless was default set to EU date format.  imported several hundred documents and they read the dates on the document in the wrong order.  Tried changing the format by adding PAPERLESS_DATE_ORDER however it does not seem to have done anything.  Is there any way to force paperless to rescan all the documents based on the new format?

### Steps to reproduce

- upload doc without changing anything
- date wrong
- change date format
- date still wrong.

### Webserver logs

```bash
No relevant logs were generated
```

### Paperless-ngx version

2.2.1

### Host OS

kubernetes

### Installation method

Docker - official image

### Browser

any

### Configuration changes

PAPERLESS_DATE_ORDER=MDY

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
There is no way to rescan existing documents using the new format.

**Comment by shamoon** [comment]
Unfortunately yes you’d have to re-add them. But I will tell you date guessing (it really is basically a best guess) isn’t perfect. It’s up to you of course, but I’d perhaps try it with a few before redoing with all of them (since it sounds like a lot of docs).

I’m not sure what you meant about the tags question

**Comment by errolsancaktar** [comment]
> Unfortunately yes you’d have to re-add them. But I will tell you date guessing (it really is basically a best guess) isn’t perfect. It’s up to you of course, but I’d perhaps try it with a few before redoing with all of them (since it sounds like a lot of docs).
> 
> I’m not sure what you meant about the tags question

sorry this should be a discussion not a bug but i mean if i add a new tag with a matching algorithm does it go back and look at existing docs or just docs going forward?  mainly do i have to have the whole model done before docs get uploaded or does it happen on a cadence?

**Comment by shamoon** [comment]
Ah, that ones easy: https://docs.paperless-ngx.com/administration/#retagger
