### ISSUE TITLE
[BUG] Unsupported mime type inode/x-empty

### ISSUE THREAD

**Issue by t-lie** [paperless-ngx/paperless-ngx#5252]
### Description

I am using Paperless-ngx within Docker in latest version.
All running fine so far.

Most times I use a EPSON ES-580W Scanner for getting documents into webdav share.
On this share (on same VM from paperless Docker) there is a fswatch job, which copies new files to the paperless consume path.

Most times its working fine!
But sometimes, it wont work and I get following error within File Task:
Unsupported mime type inode/x-empty

This is curious, because its also same type of PDF/A like every time it comes from that scanner. It seems that its caused of the document content, because even if I scan this document several times... its always the same error.

The log shows these entries:
[2024-01-05 13:39:43,437] [INFO] [paperless.consumer] Consuming 20240105_133835.pdf
[2024-01-05 13:39:43,440] [DEBUG] [paperless.consumer] Detected mime type: inode/x-empty
[2024-01-05 13:39:43,448] [ERROR] [paperless.consumer] Unsupported mime type inode/x-empty

Can anyone understand what is going on here?
If any further logs or other information is needed, just tell me.

Thanks

### Steps to reproduce

import from consume path

### Webserver logs

```bash
[2024-01-05 13:39:43,437] [INFO] [paperless.consumer] Consuming 20240105_133835.pdf
[2024-01-05 13:39:43,440] [DEBUG] [paperless.consumer] Detected mime type: inode/x-empty
[2024-01-05 13:39:43,448] [ERROR] [paperless.consumer] Unsupported mime type inode/x-empty
```

### Paperless-ngx version

2.2.1

### Host OS

Debian bookworm

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Now that I am at a computer, you can configure [PAPERLESS_CONSUMER_INOTIFY_DELAY](https://docs.paperless-ngx.com/configuration/#PAPERLESS_CONSUMER_INOTIFY_DELAY) to something larger.  Exactly what depends on your scanner and how it acts.

**Comment by shamoon** [comment]
Also please search in the future, there are multiple similar threads that I think would’ve answered your question
