### ISSUE TITLE
[BUG] Document details reachable in 1 of 3 view modes only

### ISSUE THREAD

**Issue by florianschroen** [paperless-ngx/paperless-ngx#5259]
### Description

Assuming the current user has only read permissions on the documents.

Documents view has 3 Display Modes.

- Detail (left button)
- Small (middle button) [default]
- Large (right button)

In Detail Mode, the document title links to /documents/<id> which gives us all the details for the document, including notes, metadata, ...

In Small and Large Mode, there is no linking of the title. Normally with write permissions, we can click on the pencil (edit).

But with a readonly user, there is no way to see the document details.

### Steps to reproduce

1. Login as User with readonly access to documents
2. Goto documents
3. select Detail View Mode
4. click on the title of you document
5. details of document open (like in edit mode, but without save buttons)
6. go back to documents 
7. select Small View Mode
8. no option for opening the document details
9. select Large View Mode
8. no option for opening the document details

### Webserver logs

```bash
not related
```

### Paperless-ngx version

2.1.3 + 2.2.1

### Host OS

x86_64

### Installation method

Docker - official image

### Browser

ff, chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Double-click the document.

**Comment by florianschroen** [comment]
Thx, this works for me for the small view mode.

**Comment by shamoon** [comment]
The same works if you double-click the thumbnail in the large documents view
