### ISSUE TITLE
[BUG] Workflow Content matching not saving

### ISSUE THREAD

**Issue by ritschi86** [paperless-ngx/paperless-ngx#5274]
### Description

If you set a trigger with content match in the new "Workflow" feature, this setting is not saved.

### Steps to reproduce

Go to Workflow -> Add Trigger Add/Update and use Content Match. Setting and Value will not saved

### Webserver logs

```bash
...
```

### Paperless-ngx version

2.3.0

### Host OS

Debian

### Installation method

Docker - official image

### Browser

Chrome, Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Not sure what happened there, I'll track it down, thanks

**Comment by shamoon** [comment]
The good news is this is purely a display issue, it is saving it FWIW. Will be fixed in our next release

**Comment by stumpylog** [comment]
Fixed via #5276
