### ISSUE TITLE
Show found dates as suggestions underneath the date field

### ISSUE THREAD

**Issue by hacker-h** [paperless-ngx/paperless-ngx#529]
### Discussed in https://github.com/paperless-ngx/paperless-ngx/discussions/384

<div type='discussions-op-text'>

<sup>Originally posted by **mptr8956** March 15, 2022</sup>
I think it would be nice to show all dates that were found in a document as suggested dates right below the date field in the document detail page. It appears very often that there is more than one date on a page. E.g. for an invoice there is usually a date the invoice was created, a date the letter was sent and a date the invoiced service has been performed. There are even documents (car-related, payroll-related, contracts) where a lot more dates can be found on one page.

It would be very helpful to show all dates as suggestions below the date filed (comparable to the suggestions with the correspondents / document types & tags). With a single click on the right date, it would overwrite the first suggestion.</div>

definition of done:
If a document contains more than one date, a list of suggestions is shown below the date field (similar to tag suggestions).
Clicking on one of the suggested dates will apply it to the date field.
The maximum number of suggestions is limited by default to 4 entries yet overrideable via a config variable.
Dates are collected equally from the top and the bottom of a document (e.g. 2 first and 2 last).

**Comment by shamoon** [comment]
As you noted this FR already exists. Until anyone picks it up to work on it should stay as a FR. Issues are for bugs, thanks.
