### ISSUE TITLE
[BUG] Using latin characters in ASN search displays object reference 

### ISSUE THREAD

**Issue by Tooa** [paperless-ngx/paperless-ngx#530]
**Describe the bug**

When using latin characters in the ASN search a `[object Object]` reference shows in the error message

**To Reproduce**

1. Start paperless
2. Go to documents
3. Select ASN in the drop-down
4. Search with non number characters

**Expected behavior**

Non-technical error message displayed. Maybe even telling the user that only latin numbers allowed for the ASN search

**Screenshots**

![image](https://user-images.githubusercontent.com/5375334/160233084-83cdc42b-2508-415f-95c3-42608ea3c85c.png)

**Webserver logs**

```bash
webserver_1  | [2022-03-26 10:21:34,232] [WARNING] [django.request] Bad Request: /api/documents/
```

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 21.04
 - Browser [e.g. chrome, safari]: firefox
 - Version [e.g. 1.0.0]: 1.6.0
 - Installation method: docker

**Comment by similicious** [comment]
The backend is returning an appropriate validation error,
```
{
   "archive_serial_number":[
      "Bitte eine Zahl eingeben."
   ]
}
```
which the frontend is not handling correctly.
https://github.com/paperless-ngx/paperless-ngx/blob/ed2524cbbb59207b514c71f4434d501ad31bee09/src-ui/src/app/components/document-list/document-list.component.html#L99

Could we just loop over the keys in the keys of the error object and then over the items in the array in display those?

On another note, the text in the alert is not localized.

**Comment by shamoon** [comment]
Funny enough I would guess this is the same issue as https://github.com/paperless-ngx/paperless-ngx/pull/616 e.g. https://github.com/paperless-ngx/paperless-ngx/pull/612#issuecomment-1086421771

Hmm, we should probably abstract the logic for these errors into something more general. I will do that when I have some time.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/bf7002d0ae3c1c1d3edef44fef027e9cde81f9e5
