### ISSUE TITLE
[BUG] Workflow creation throws bad request error

### ISSUE THREAD

**Issue by OverDodo** [paperless-ngx/paperless-ngx#5311]
### Description

When trying to create a workflow, no matter which trigger I choose, I get an error message stating that the trigger cannot be null. 

<img width="228" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/36535726/dd571f6b-9bce-4634-b6e6-10ec8a6ea59d">

This is the error shown in the UI, the container logs only show a Bad Request:
<img width="177" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/36535726/70b5cdfe-ee60-48f9-95e0-70675c9829be">

I cant include a screenshot under Browser Logs, so here is a screenshot of the request data.
<img width="464" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/36535726/d1a456a8-1d89-4e04-a7de-41961285c0ce">

### Steps to reproduce

1. Go to Workflows
2. Create a new Workflow with Name and Order
3. Add any trigger
4. Try to save it

### Webserver logs

```bash
[2024-01-08 09:25:15,077] [WARNING] [django.request] Bad Request: /api/workflows/
```

### Paperless-ngx version

2.3.1

### Host OS

Synology DS723+, DSM 7.2, 'x86_64'

### Installation method

Docker - official image

### Configuration changes

PAPERLESS_CSRF_TRUSTED_ORIGINS to my domain, PAPERLESS_URL to my domain

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This was fixed in 2.3.2
