### ISSUE TITLE
Configuration: User-Arguments are mandatory

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#5313]
### Description

See the following Screenshot. 

![image](https://github.com/paperless-ngx/paperless-ngx/assets/88422038/b2bc5f45-b45d-43c5-99f7-076ae4c6764d)

I don't think, user args should be mandatory, since the documentation says "additionally specify arguments".

### Steps to reproduce

1. Click on "Configuration"
2. Fill in some Values
3. Click "Save"
4. User-Args are mandatory

In order to save a Configuration, the user now has to enter an empty json which is not very user-friendly.

### Webserver logs

```bash
not applicable
```

### Paperless-ngx version

2.3.2

### Host OS

Synology DSM 6.2.X

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

none of interest

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Looks like we'll need the `null=True`, since that isn't being picked up from the model.  @shamoon looks like you're getting this?

**Comment by shamoon** [comment]
Actually please feel free stumpy my virtualenv exploded last night 😥
