### ISSUE TITLE
[BUG] Custom Fields not working on Group Permission

### ISSUE THREAD

**Issue by R1NEJ0** [paperless-ngx/paperless-ngx#5325]
### Description

Hi! I'm not pretty sure if it's a bug o just a feature.

Just owner of a document has permission to add custom field to documents despite of that document has group permission to edit .

### Steps to reproduce

1. Create a workflow that change group permission of the document uploaded to be accesible for group user and editable.
2. Just owner can add / remove custom fields.
3. If you delete the owner, every user of the group can add / remove custom fields on it if the document has owner no one, except owner can add / remove custom fields.

### Webserver logs

```bash
I don't have any logs
```

### Paperless-ngx version

2.3.2

### Host OS

unRaid

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
You are correct, currently only owners can add / remove custom fields. There’s a feature request somewhere to change that.

(At least I think that’s what you’re asking about, let me know if I misunderstood)

**Comment by R1NEJ0** [comment]
That's exactly what I'm telling.

Thanks!
