### ISSUE TITLE
[BUG] UI doesn't reflect changed document type if current user isn't allowed to view type

### ISSUE THREAD

**Issue by zkulbeda** [paperless-ngx/paperless-ngx#5338]
### Description

DocumentType form select in document's edit page is getting old data when another user change the document's type that current user isn't allowed to view.

### Steps to reproduce

1. Create two users (A, B), include permission DocumentType All to both
2. Open two browsers and log in
4. Create a document with owner A, allow editing to user B
5. Create document type with owner A and assign it to new document
6. Open document in user B, UI will display _Private_ document type.
7. Create new document type (or assign different that user A can't view), assign it to shared document.
8. Refresh document edit page in user A browser. Nothing changed. Check the api response for document, see that `document_type` was changed, but ui still somehow show old data.

I reproduced this steps with opened devtools that disables network cache

### Webserver logs

```bash
Does not contain any useful information
```

### Browser logs

```bash
Does not contain any useful information
```

### Paperless-ngx version

2.2.1

### Host OS

Ubuntu 20

### Installation method

Docker - official image

### Browser

Microsoft Edge

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Close the document and re-open it.
