### ISSUE TITLE
Different sortings in views between saved view and on home page

### ISSUE THREAD

**Issue by myssv** [paperless-ngx/paperless-ngx#5362]
### Description

I have a saved report with this sorting order

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/65643813/1d7954c9-fb3d-4f74-9170-dc1703e09d5d)

And the sorting is ok

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/65643813/ce642032-8974-4cfb-8d76-70becbce7a5f)

But when I added this view to the home page, th sorting is different

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/65643813/1e62d021-88fa-4e6f-87ba-6dcb3af3f8a9)

### Steps to reproduce

Save a view with a sorting and put it on the home page

### Webserver logs

```bash
not needed
```

### Paperless-ngx version

2.3.3

### Host OS

Debian 12

### Installation method

Bare metal

### Browser

FirFox 121.0.1

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I can't reproduce this. The sort is saved. If you look at the API call for the view it'll be e.g.

http://localhost:8000/api/documents/?page=1&page_size=25&ordering=-correspondent__name&truncate_content=true&tags__id__all=9
same on the dashboard
http://localhost:8000/api/documents/?page=1&page_size=10&ordering=-correspondent__name&truncate_content=true&tags__id__all=9

Make sure you saved the view again after changing the sort...

**Comment by myssv** [comment]
I looked at the view and it was still changed the correct way.

Then I got to the home page and now it is sorted also correct there ?!?!?

Do I have to close the browser before the change is visible?

Thanks for the hint!
