### ISSUE TITLE
[BUG] User can get higher privileges if user edit permissions are granted

### ISSUE THREAD

**Issue by lordgurke** [paperless-ngx/paperless-ngx#5368]
### Description

This is either an implementation or documentation issue:  
If a user has the permission to add or modify users, the user can grant himself superuser permissions, thus granting unrestricted privileges.  
At least to me it's counter-intuitive that a user can grant more privileges to user accounts than he already has himself.  
Also, having the ability to modify superuser accounts by non-superusers is a problem, as simply setting a new password or changing the e-mail address can also be misused for account takeovers.  
I would've expected that a user account can only grant permissions to new accounts that were already granted to the user that creates the new account.

### Steps to reproduce

* Create a user account on the UI which is not a superuser and has only privileges to show and add user accounts.
* Log in as the newly created user.
* Edit your own user account and grant superuser privileges.
* You now have superuser privileges

### Webserver logs

```bash
(no logs available)
```

### Paperless-ngx version

2.3.2

### Host OS

Debian 11 x86_64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Hmm, I guess the part about not being able to make someone a superuser seems like a fair request but:

- permissions come from Django, so in some ways we're not determining this.
- it has been like this since permissions were added many many months ago...

So I see this as more of a change request, even if I do potentially 'agree' with it.

Feel free to open a FR discussion, can discuss the details

**Comment by stumpylog** [comment]
To a certain extent, if you are giving them permission to add/edit users, isn't it expected they can do this?  If you checked a box to allow a user to edit users, then they can edit users?

**Comment by shamoon** [comment]
Yea exactly my thought. But the one specific point about being able to grant superuser privileges is worth considering
