### ISSUE TITLE
File Tasks "Dismiss selected" is dismissing more than (seen) checked

### ISSUE THREAD

**Issue by pappou99** [paperless-ngx/paperless-ngx#5375]
### Description

Dismissing a lot of duplicated documents includes also documents on further pages.

### Steps to reproduce

1. Import a lot of  Documents, which are already in the system - "File Tasks Failed" shows them in a list.
2. List is too short to show all. More pages are displayed at the right bottom sceen.
3. Select showed items in list at once via checkbox over the list (next to "Name")
4. Click "Dismiss selected"
5. All items in List (also the not showed on pages 2 to eg 7) are dismissed.

I'd love to have a "Dismiss duplicate failed" button so I can clear these out and see the other errors.

### Webserver logs

```bash
None
```

### Paperless-ngx version

2.3.3

### Host OS

Debian bullseye

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thats what the button is supposed to do.

https://github.com/paperless-ngx/paperless-ngx/blob/ab31f1f109eddf177a2d8dce40bdd76ee549b2bf/src-ui/src/app/components/admin/tasks/tasks.component.html#L31
