### ISSUE TITLE
[BUG] Installation script fails after "Apply database migrations..." on Ubuntu 24.04

### ISSUE THREAD

**Issue by s-geissler** [paperless-ngx/paperless-ngx#5380]
### Description

Running the installation script `bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"` fails after the log says `Apply database migration...` with the following error

`django.db.utils.OperationalError: connection to server at "db" (172.18.0.5), port 5432 failed: FATAL:  no pg_hba.conf entry for host "172.18.0.6", user "paperless", database "paperless", no encryption`

### Steps to reproduce

Run `bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"` on a freshly installed Ubuntu 24.04 host.

### Webserver logs

```bash
NA
```

### Paperless-ngx version

v2.3.3

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Sounds like an error you need to Google, but I don’t see how it’s a paperless problem, it’s not even a problem in the paperless container. Certainly not widespread so I’m gonna guess something specific to your machine/setup

**Comment by shamoon** [comment]
Eg https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host

is there something weird or specific about your ipv6 setup?
