### ISSUE TITLE
[BUG] HTTP Remote User authentication broken on unsafe API endpoints

### ISSUE THREAD

**Issue by awahlig** [paperless-ngx/paperless-ngx#5384]
### Description

I am running Paperless on Tailscale and use it to automatically authenticate the Paperless users using this config:
```yaml
environment:
  PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
  PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_TAILSCALE_USER_LOGIN
```

This works for web-ui and safe API calls (GET) but does not work for unsafe API calls (POST), which are returning CSRF errors (see below).

### Steps to reproduce

1. Configure Remote User auth with a custom user header.
2. Try to upload a document using the `/api/documents/post_document/` endpoint while providing the appropriate user header.

I’ve been testing using curl.
```
$ curl -v -X POST 'https://paperless.my-tailnet.ts.net/api/documents/post_document/'
```

It’s ok to not provide the document because the type of error tells if it worked or not.

Expected:
```
< HTTP/1.1 400 Bad Request
…
{"document":["No file was submitted."]}
```

Observed:
```
< HTTP/1.1 403 Forbidden
…
{"detail":"CSRF Failed: CSRF cookie not set."}
```

### Webserver logs

```bash
webserver_1  | [yyyy-mm-dd hh:mm:ss,mmm] [WARNING] [django.request] Forbidden: /api/documents/post_document/
```

### Paperless-ngx version

2.3.3

### Host OS

Ubuntu 22.04.3 LTS jammy (x86_64)

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

- Added a reverse proxy container with embedded Tailscale.
- Disabled port forwarding on webserver service.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

### How to fix

I believe I know how to fix this and can provide a PR if needed.

I had to make two changes:

1. `RemoteUserAuthentication` needs to be before `SessionAuthentication` in `paperless.settings.REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"]` to handle the auth before Session can throw the CSRF errors.
2. `rest_framework.authentication.RemoteUserAuthentication` needs to know about the custom header name (right now it’s always using the default).

**Comment by shamoon** [comment]
I dont think most people use REMOTE_USER with the API directly, they use the webUI, which does set CSRF. Can you explain your use case / how are you providing the REMOTE_USER header in your curl session?

**Comment by awahlig** [comment]
Yes, I understand this is not a common case.

Basically, all my services are available only on my own private VPN created using Tailscale that is shared between several users. Instead of them having to authenticate to access the VPN and then again for the services running on it, whenever possible, I’m trying to remove this second step.

As I said, this works very well for the webUI but as I found out, the API is using a slightly different codepath.

The use case for the API is a shortcut on a phone to easily add new documents from apps. With the Remote User auth working, I wouldn’t have to have any passwords or tokens inside it and could share it without worrying about abuse.

Btw, I was able to reproduce this without involving Tailscale.

### How to reproduce

docker-compose.yml
```yaml
webserver:
  ports:
    - 8000:8000
  environment:
    PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true" 
```

docker-compose.env
```
PAPERLESS_URL=http://localhost:8000
```

And then:
```
$ curl -X POST \
    -H 'Remote-User: <username>' \
    'http://localhost:8000/api/documents/post_document/'
{"detail":"CSRF Failed: CSRF cookie not set."}
```

This should work as “Remote-User” is the default header name (as can be seen in the [documentation](https://docs.paperless-ngx.com/configuration/#PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME)).

It fails because `rest_framework.authentication.RemoteUserAuthentication` is looking in this case at `REMOTE_USER` instead of `HTTP_REMOTE_USER`.

**Comment by shamoon** [comment]
I mean, we've never explicitly supported remote user for direct API requests, API requires token auth, so really I dont know that this is unexpected in our project, aka, I dont see this as a 'bug'.

But without being pedantic about it, you can try the image tag `feature-drf-remote-user`. **Please note** thats based on `dev` and so may contain other changes, i.e. I wouldn't test it with your production install

**Comment by shamoon** [comment]
Sorry there's a silly bug in that one, its re-building: https://github.com/paperless-ngx/paperless-ngx/actions/runs/7517171295

**Comment by awahlig** [comment]
You’re completely right, I must’ve assumed that it should work because the webUI does. Not a bug then.

The `feature-drf-remote-user` tag contains exactly the changes that I made. Thanks for implementing so fast!

**Comment by shamoon** [comment]
Cool. Im fine with opening that PR as I dont really see it having any negative impact

**Comment by awahlig** [comment]
Thanks for letting me know. It's a bummer but I understand the reasoning.

Putting it behind a setting (off by default) would fix the security issue but I understand if that's not something you want. I can just patch my instance instead.

**Comment by shamoon** [comment]
Yea I think the problem is this change would have the potential to silently punch a big hole in people’s setups. It’s hard to know that ‘cause we don’t have actual data but given the popularity of tools like traefik and authelia and ‘typical’ instructions for setting those up it seems too big of a risk.

Perhaps theres a solution that doesn’t cause this by making it opt-in or something like that.

Appreciate your understanding

**Comment by hansmi** [comment]
@awahlig, in case you're interested I opened discussion #5558 to document how I'm remote-user headers for OAuth.
