### ISSUE TITLE
[BUG] Log contains InconsistentVersionWarning for sklearn using docker-compose with latest paperless docker image

### ISSUE THREAD

**Issue by coderph0x** [paperless-ngx/paperless-ngx#5394]
### Description

I have a log entry in root_webserver_1 which reads
```
/usr/local/lib/python3.11/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator MLPClassifier from version 1.3.0 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
```

### Steps to reproduce

1. `podman-compose up -d`
2. `podman logs root_webserver_1`

### Webserver logs

```bash
/usr/local/lib/python3.11/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator MLPClassifier from version 1.3.0 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
```

### Paperless-ngx version

2.3.3

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

PAPERLESS_TRUSTED_PROXIES=172.16.x.y PAPERLESS_USE_X_FORWARD_HOST=true PAPERLESS_ENABLE_COMPRESSION=false  PAPERLESS_OCR_MODE=redo PAPERLESS_OCR_SKIP_ARCHIVE_FILE=with_text  PAPERLESS_CONSUMER_DELETE_DUPLICATES=true PAPERLESS_CONSUMER_RECURSIVE=true PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true  PAPERLESS_OCR_ROTATE_PAGES=true PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=10  PAPERLESS_CONSUMER_ENABLE_BARCODES=true PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXING

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by coderph0x** [comment]
Ran into this log entry after upgrading to 2.3.3.
Doesn't hinder paperless to run, but I can't tell how it affect user experience.

**Comment by stumpylog** [comment]
It doesn't really affect anything.  It appears they changed the warning text we used to capture to something else.

**Comment by stumpylog** [comment]
What version did you update from?  sklearn hasn't changed in 2 months at this point, so I'm having trouble reproducing it

**Comment by stumpylog** [comment]
As soon as the classifier runs again, which is every hour (?) by default, the saved file is updated and the version warning will go away.  So it is only something ever going to be seen in some particular circumstances

**Comment by coderph0x** [comment]
Okay, so my impatient ass stroke again. 😂
Thanks for checking up so fast! 👍🏻

Can be closed, I guess.
