### ISSUE TITLE
[Other] Allow access to webhooks for readthedocs

### ISSUE THREAD

**Issue by gador** [paperless-ngx/paperless-ngx#54]
I recently set up the [readthedocs site](https://paperless-ngx.readthedocs.io/en/latest/). Unfortunately, I don't have access to the webhooks settings of the project. 
I requested access to it from the project owner. When granted, the docs will automatically update.
Also we should change some items in https://github.com/paperless-ngx/paperless-ngx/blob/master/docs/conf.py 
(namely `project = u'Paperless-ng'` and `copyright = u'2021, Daniel Quinn, Jonas Winkler'`)

Should we just add `paperless-ngx team` to it?

**Comment by qcasey** [comment]
Great, thanks! I just approved access to readthedocs.

> Also we should change some items in https://github.com/paperless-ngx/paperless-ngx/blob/master/docs/conf.py
(namely project = u'Paperless-ng' and copyright = u'2021, Daniel Quinn, Jonas Winkler')

We can create a PR if it's just those two lines. What should the copyright change to?

**Comment by gador** [comment]
maybe `paperless-ngx team`?

**Comment by yschroeder** [comment]
The project sidebar still points to the old readthedocs.

**Comment by qcasey** [comment]
> The project sidebar still points to the old readthedocs.

Thanks, updated.

**Comment by qcasey** [comment]
Closed in #55
