### ISSUE TITLE
[BUG] UI: Log keeps scrolling to bottom

### ISSUE THREAD

**Issue by schroeer** [paperless-ngx/paperless-ngx#5415]
### Description

Using the web application with the Chrome browser, on the _Logs_ page, it is impossible to scroll up, because the log keeps jumping back to the bottom immediately. This is independent of the setting of the _Auto refresh_ toggle. With the Edge browser, it seems to work a bit better.

### Steps to reproduce

1. In the web application, go to the _Logs_ page
2. Try to scroll one of the logs backwards to older entries

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.3.3

### Host OS

Linux 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

### Installation method

Docker - official image

### Browser

Chrome (and Edge)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Turn off auto refresh

**Comment by schroeer** [comment]
Turning off auto refresh does not help.

**Comment by schroeer** [comment]
I feel a bit stupid at the moment, because I am having problems to reproduce it myself now. The scroll-to-bottom still occurs at times with "auto refresh" off, but much less frequently. On previous occasions, an attempt to scroll up resulted in heavy flickering from immediately scrolling back down.

I will now wait until I have a better understanding of the conditions under which the issue occurs. Or someone else chimes in to save my reputation by confirming the problem.

**Comment by kirscheGIT** [comment]
Same behavior on MacOS with Safari and Brave. Seems to happen when the tab with paperless is running for quite a while. When you then switch to the Log page and turn off auto refresh and scroll the log up, the log jumps back to the bottom, even when no new log entry has been created.

**Comment by shamoon** [comment]
This will work differently in the next release and I think won’t be an issue any longer
