### ISSUE TITLE
[BUG] OcrConfig Migration is not applied

### ISSUE THREAD

**Issue by agemuend** [paperless-ngx/paperless-ngx#5425]
### Description

After upgrading an instancen to v2.3.3, paperless-ngx does not work anymore. Metadata Operations fail with the following error: 

```
Jan 16 12:25:35 paperless gunicorn[773054]: [2024-01-16 12:25:35,555] [ERROR] [django.request] Internal Server Error: /api/documents/338/metadata/
Jan 16 12:25:35 paperless gunicorn[773054]: Traceback (most recent call last):
Jan 16 12:25:35 paperless gunicorn[773054]:   File "/opt/paperless/venv/lib64/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
Jan 16 12:25:35 paperless gunicorn[773054]:     return self.cursor.execute(sql, params)
Jan 16 12:25:35 paperless gunicorn[773054]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 16 12:25:35 paperless gunicorn[773054]: psycopg2.errors.UndefinedTable: FEHLER:  Relation »paperless_applicationconfiguration« existiert nicht
```

(Sorry for the German, says that the relation does not exist.)

It seems to be the OcrConfig from https://github.com/paperless-ngx/paperless-ngx/pull/5126/ which does not exist in my install. 

And indeed, when checking my logs, I see that the migration in question was never run, only two unrelated migrations: 

```
(venv) [paperless@paperless src]$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions
Running migrations:
  Applying documents.1043_alter_savedviewfilterrule_rule_type... OK
  Applying documents.1044_workflow_workflowaction_workflowtrigger_and_more... OK
(venv) [paperless@paperless src]$
```

### Steps to reproduce

Upgrade existing Installation to 2.3.3 and check if migration is applied correctly.

### Webserver logs

```bash
Jan 16 12:25:35 paperless gunicorn[773054]: [2024-01-16 12:25:35,555] [ERROR] [django.request] Internal Server Error: /api/documents/338/metadata/
Jan 16 12:25:35 paperless gunicorn[773054]: Traceback (most recent call last):
Jan 16 12:25:35 paperless gunicorn[773054]:   File "/opt/paperless/venv/lib64/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
Jan 16 12:25:35 paperless gunicorn[773054]:     return self.cursor.execute(sql, params)
Jan 16 12:25:35 paperless gunicorn[773054]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 16 12:25:35 paperless gunicorn[773054]: psycopg2.errors.UndefinedTable: FEHLER:  Relation »paperless_applicationconfiguration« existiert nicht
```

### Paperless-ngx version

2.3.3

### Host OS

Rocky Linux release 9.3 (Blue Onyx)

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
If you run a bare metal install you are responsible for making sure migrations are run

**Comment by agemuend** [comment]
@shamoon Yes, I have manually executed `python manage.py migrate` but this specific migration will not be run in that case, see above.

**Comment by shamoon** [comment]
Ah. That would imply your paperless install thinks that migration was already run but I can’t see why that would be. No one else has reported this, not yet anyway

**Comment by agemuend** [comment]
Yeah I was wondering the same, showmigrations even listed it with a checkmark: 

```
(venv) [paperless@paperless src]$ python manage.py showmigrations
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
[...]
paperless
 [X] 0001_initial
[...]
```

It executed the other migrations though. Is it because of the initial = True possibly?

**Comment by blackerking** [comment]
sorry for reopening this issue.
But what can I do exactly when I am using Docker(-Compose)?

Best Regards.
