### ISSUE TITLE
[BUG] document_exporter seems to have trouble with special chars like ä,ö and ü

### ISSUE THREAD

**Issue by IntelliNik** [paperless-ngx/paperless-ngx#5449]
### Description

Hi,
I've just used the `document_exporter` in Paperless NGX, where the German word "Bestätigung" got exported as "Best則igung". This way now the `document_importer` is unable to find the file when importing. 

### Steps to reproduce

Use the document_exporter with a document named "Bestätigung"

### Webserver logs

```bash
[2024-01-18 14:02:34,686] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2024-01-18 14:02:46,229] [INFO] [paperless.auth] Login failed for user `niklas` from private IP `192.168.178.20`.
[2024-01-18 14:02:54,431] [INFO] [paperless.auth] Login failed for user `niklas` from private IP `192.168.178.20`.
[2024-01-18 14:03:44,561] [INFO] [paperless.auth] Login failed for user `admin` from private IP `192.168.178.20`.
[2024-01-18 14:04:46,655] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify
[2024-01-18 14:04:46,656] [DEBUG] [paperless.management.consumer] Consumer exiting.
[2024-01-18 14:05:00,744] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2024-01-18 14:05:01,405] [INFO] [paperless.tasks] No automatic matching items, not training
[2024-01-18 14:40:00,279] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify
[2024-01-18 14:40:00,297] [DEBUG] [paperless.management.consumer] Consumer exiting.
[2024-01-18 14:49:08,260] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
[2024-01-18 15:05:00,089] [INFO] [paperless.tasks] No automatic matching items, not training
```

### Paperless-ngx version

2.3.3

### Host OS

Debian

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
- "Seems to have trouble" is not a very viable error report
- I cannot reproduce this.  A file titled Bestätigung exports and import without any issue.  The name in the JSON and the filesystem looks idenctial.

**Comment by shamoon** [comment]
Yea, and there are a lot of German users around here, so Id be surprised. =)

I think there are specific tests for this. Also, those logs aren't very helpful...

**Comment by alexmaret** [comment]
Are you using a CIFS share, that has been mounted into the Docker container, as export folder?

**Comment by OverDodo** [comment]
I can reproduce this on a Synology DS723+ with the official docker image using compose, with the export folder mounted into the docker container. This is the output of the document_importer:
`root@testpaperless-ngx:/usr/src/paperless/src# document_importer /usr/src/paperless/export/export
Found existing user(s), this might indicate a non-empty installation
Checking the manifest
CommandError: The manifest file refers to "Aktivitätendiagramm Beispiellösung" which does not appear to be in the source directory.`

This is how the file names appear in the export directory, while it should be "Aktivitätendiagramm Beispiellösung":
<img width="579" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/36535726/396b58a5-1858-4714-a863-8ce529f67987">

**Comment by alexmaret** [comment]
Same question to you: Did you mount a network share as export folder?

Other than that, can you provide the output of:
```
export | grep LANG
export | grep LC
```

**Comment by OverDodo** [comment]
> Same question to you: Did you mount a network share as export folder?
> 
> Other than that, can you provide the output of:
> ```
> export | grep LANG
> export | grep LC
> ```
> 

Yes, all of the mapped volumes are in a share. Heres the output:

![Screenshot_20240119_184040_Edge.png](https://github.com/paperless-ngx/paperless-ngx/assets/36535726/d6215034-18ce-461d-9167-46e4b0bd074c)

**Comment by alexmaret** [comment]
If it's a CIFS share, you need to set the character set: https://github.com/paperless-ngx/paperless-ngx/issues/5289

You clearly have some character set issues. Either because your system locale is not set correctly or because your volume does no proper conversion. 

Paperless writes filename as UTF-8, as you can see from the locale (C.UTF-8). So you will see this garbled output if your system either has a non-UTF8 locale and tries to read UTF-8 filenames, or if the underlying volume does not support/convert the character set properly and you are trying to read it as UTF-8.

**Comment by OverDodo** [comment]
> If it's a CIFS share, you need to set the character set: https://github.com/paperless-ngx/paperless-ngx/issues/5289
> 
> You clearly have some character set issues. Either because your system locale is not set correctly or because your volume does no proper conversion. 
> 
> Paperless writes filename as UTF-8, as you can see from the locale (C.UTF-8). So you will see this garbled output if your system either has a non-UTF8 locale and tries to read UTF-8 filenames, or if the underlying volume does not support/convert the character set properly and you are trying to read it as UTF-8.
> 

Shouldnt that also mean weird file names in the archive and originals folders/volumes? Because they are correct there. Its just when exporting them. And they are all mapped to the same share.

**Comment by alexmaret** [comment]
Yes, you would also see these issues elsewhere, but Paperless would not notice it.

On Linux, a filename is just a byte array, the character set does not matter. A vanilla paperless should read/write these bytes as UTF-8, but at the end of the day it's just bytes - the character set makes no difference if you reader and writer. So the problem only arises if two parties (reader & writer) have a character set mismatch and interpret the filename bytes differently.

**Comment by shamoon** [comment]
Awesome, appreciate the context and link alexmaret

**Comment by auer1329** [comment]
I can reproduce this:
- when exporting to a .zip file and opening or unzipping the file on my Synology DS920+ via DSM, the filenames get messed up
- when exporting to a directory without zipping, the filenames are fine
