### ISSUE TITLE
[BUG]? Document Renamer Not Working

### ISSUE THREAD

**Issue by mochoandre** [paperless-ngx/paperless-ngx#5454]
### Description

I installed Paperless-ngx in Docker using the Installation Script in Ubuntu 22.04 amd tryed for several hours of documentation and google read to get peperless to rename documents and not the 0000XXX.pdf. 
Changed several ways PAPERLESS_FILENAME_FORMAT in docker-compose.env and .yml, restarted container and nothing happened with new documents or invoquing document_renamer inside container.

I could only make it respect the file name format when in the installation directory of the host I invoqued "docker compose down" and after "docker compose up".

I do not know if this is a bug or by design, but in case it is by design it should be clear in documentation. I could not find it.

Best regards and thank you very much for this very usefull tool wich I'm just starting to learn.

### Steps to reproduce

Change env file 

### Webserver logs

```bash
No Relevant information was given in logs
```

### Paperless-ngx version

2.3.3

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Changing environment variables requires recreating a container. That’s not a paperless-ngx thing it’s a docker thing

**Comment by mochoandre** [comment]
Ok. So maybe it should be clear in documentation, wich is really good, for guys like me wich are not so experienced in docker compose

**Comment by shamoon** [comment]
Sure but that literally applies to every single environment variable it’s possible to set. Or to using bind mounts or docker networking etc... I guess I just mean we have to assume some baseline knowledge of docker, there’s no perfect line for that imho.
