### ISSUE TITLE
[BUG] Max Image Pixels setting in Application Configuration falls back to invalid value

### ISSUE THREAD

**Issue by pm64** [paperless-ngx/paperless-ngx#5456]
### Description

The validation for the Max Image Pixels input appears to require a minimum value of 1000000. There is also a maximum permitted value.

If a value that exceeds the maximum permitted value is entered (for example, 999999999999999), the system falls back to a value of 1, and saves it.

1 is out of range (since the minimum is 1000000), so subsequent changes to Application Configuration raise this validation error.

That covers the actual defect. But I'll quickly add that I hope the resolution contemplates the ability to disable the Max Image Pixels limit completely. The [Pillow docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open) indicate that a value of "None" can be used for this purpose, but Paperless-ngx's Application Configuration UI requires a number for this field. And because a minimum value of 1000000 is required, "None" can't be indicated by a value like 0 or -1.

### Steps to reproduce

1. Go to Application Configuration
2. For Max Image Pixels, enter 999999999999999
3. Click save
4. Observe the field now carries a fallback value of 1.
5. Update another value and observe the validation error.

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.4.0

### Host OS

macOS

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Cant reproduce. Tried with SQLite and Postgres


https://github.com/paperless-ngx/paperless-ngx/assets/4887959/1c0316e7-e1ae-4d5c-93be-7e7eae0d1f9f

**Comment by shamoon** [comment]
Oh, I guess if you just make it even bigger.

Sp it's saving the number as e.g. `1.0e+30`, I guess the frontend isnt displaying that correctly. TBH this feels a bit silly...

Emptying the field is equivalent to using the default for OCRMyPDF which I think is 256M pixels

**Comment by pm64** [comment]
@shamoon good catch, I should have checked the backend to verify the stored value.

I'm actually running up against the default limit while adding some large archival scans:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/10715458/d887519c-38a8-423f-8a03-67e09380db4a)

In addressing this display issue, would you consider allowing a value that removes the max image pixels limit?

**Comment by stumpylog** [comment]
Ocrmypdf doesn't provide a way to remove the limit entirely.  It's either set to a value or not set and left to some default, defined either by ocrmypdf or pillow

**Comment by pm64** [comment]
@stumpylog I think you're mistaken about this:

https://github.com/ocrmypdf/OCRmyPDF/blob/75bf8e4ba2d4d7e437d6cb208e981a2407c963a7/src/ocrmypdf/api.py#L403

![image](https://github.com/paperless-ngx/paperless-ngx/assets/10715458/46c434a4-138a-4ec7-bc10-d7cf4e00abcb)

Also, OCRmyPDF appears to interpret the value "0" as "None", which Paperless-ngx won't do because of the 1000000 minimum:

https://github.com/ocrmypdf/OCRmyPDF/blob/75bf8e4ba2d4d7e437d6cb208e981a2407c963a7/src/ocrmypdf/_validation.py#L213

![image](https://github.com/paperless-ngx/paperless-ngx/assets/10715458/ec1d229b-b601-4ca5-b505-2ce6efdecc50)

@shamoon, would you consider removing the 1000000 minimum and making 0 a valid value?

**Comment by stumpylog** [comment]
You can use https://docs.paperless-ngx.com/configuration/#PAPERLESS_OCR_USER_ARGS

**Comment by pm64** [comment]
Excellent @stumpylog! So I can just add `PAPERLESS_OCR_MAX_IMAGE_PIXELS=None` or `PAPERLESS_OCR_MAX_IMAGE_PIXELS=0` to my docker-compose.env, restart the containers, and the limit will go away?

**Comment by pm64** [comment]
@stumpylog I'll take that as a yes.

@shamoon I'll take that as a no.

Appreciate you guys, very grateful for all your hard work.

**Comment by shamoon** [comment]
No he's saying to use a different variable, double check his post. Also you can set these via the frontend too fyi

Yes sorry were rude. In our defense, we get **a lot** of  discussions / issues every day 😅

Appreciate the appreciation

**Comment by pm64** [comment]
Sorry guys, yes I did completely misread that.

@shamoon no defense or apology necessary, I know you have way bigger fish to fry. I hope my gratitude didn't seem sarcastic.

I'm just new here and am evidently going blind. But I do want to be a productive member of this community. I may file bug reports for minor defects in the future, but won't take it personally if you need to blow me off.

**Comment by shamoon** [comment]
Oh no, I didnt think you were being sarcastic at all, no worries (and neither was I). Tone is easily misconstrued online—I was just noticing that we kinda ghosted you.
