### ISSUE TITLE
[BUG] Error while converting email to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/chromium/convert/html

### ISSUE THREAD

**Issue by schnitzi99** [paperless-ngx/paperless-ngx#5468]
### Description

Since gotenberg 7.10: When importing mails the consumer / gotenberg fails with the above message.
[ERROR] [paperless.consumer] Error occurred while consuming document mymail.eml: Error while converting email to PDF: Server error '500 Internal Server Error' for url 'http://gotenberg:3000/forms/chromium/convert/html

Problem didn't exist with gotenberg 7.8.

Setting 
      - "--chromium-auto-start=true"
      - "--api-timeout=600s"
in docker-compose.yml solved this.

Smaller api-timeouts might solve this problem as well.
Might be that chromium-auto-start alone solves this as well. 
The api-timeout was necessary already at earlier version to avoid the already elsewhere documented 503 error.

--> I suggest including these lines (perhaps with a smaller api-timeout) commented out in the docker-compose.yml with a comment something like 
"uncomment these lines when the protocol shows 503 or 500 error on low-ressource devices like NAS-systems or raspberry pi.

### Steps to reproduce

install paperless ngx via docker with gotenberg and sqllite on rpi4 (I'm using an old 120GB external ssd as storage) and import an .eml file.

### Webserver logs

```bash
seems not necessary as I described the solution above. If you need this anyway let me know.
```

### Paperless-ngx version

2.4.0

### Host OS

dietpi 8.25.1 based on bookworm

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

      - "--chromium-auto-start=true"       - "--api-timeout=600s"       - "--uno-listener-start-timeout=30s"

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please search, there are many similar threads and this is a Gotenberg setup issue, not a bug
