### ISSUE TITLE
[BUG] Cannot save mail rule

### ISSUE THREAD

**Issue by maltokyo** [paperless-ngx/paperless-ngx#5471]
### Description

When I try to save ANY mail rule, for example this one:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/1388507/2e624ca4-04e3-4172-9c9e-6d2175d60da6)

Then the save button greys out, and then just does nothing (like this):
![image](https://github.com/paperless-ngx/paperless-ngx/assets/1388507/e1201451-d838-4109-b7b1-ec66d0dd990d)

Further changes to the rule cannot be saved either, the only option is pressing the X at the top right of the rule and closing it.  Nothing appears in the saved rules list.

The error that pops up in the page after waiting about a minute is pasted below.

### Steps to reproduce

1. Go to Mail
2. Click add rule
3. Try to save it

### Webserver logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":504,"statusText":"OK","url":"https://mydomain-masked.com/api/mail_rules/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://mydomain-masked.com/api/mail_rules/: 504 OK","error":"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n"}
```

### Paperless-ngx version

2.4.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Those are not actual server logs.  Please provide those.

**Comment by maltokyo** [comment]
I just did it again, and nothing at all is generated in `docker compose log`s or in the logs section at the bottom right of the UI - please share if there is any other logs?

**Comment by stumpylog** [comment]
If the server is actually crashing, there will be logs.  There's the log files, there's `docker logs --follow <my container name>`.  Without actual logs, there is little anyone can do.

I cannot reproduce any error with mail rules.  And no one else has reported anything.

**Comment by maltokyo** [comment]
I restarted the container, and now I could save the rule.  I apologize for wasting time, no idea what it was.. closing

**Comment by wezzynl** [comment]
I'm having the exact same issue, though restarting the container does not work for me ;) Steps to reproduce are exactly the same as OP mentioned.

There are no entries in the logs as it seems that the XHR simply does not fire. This is what the network tab in the inspector shows:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/5656741/3ac728a5-9add-405a-ab26-7ad2bdcfd89f)
