### ISSUE TITLE
[Demo-Website] Demo Website is not working.

### ISSUE THREAD

**Issue by Tharun-Techie** [paperless-ngx/paperless-ngx#5476]
### Description

Demo Website : https://demo.paperless-ngx.com/  is not working 
![image](https://github.com/paperless-ngx/paperless-ngx/assets/93753661/894690ad-20d0-4528-b603-fa8236adb9b3)

### Steps to reproduce

1. Go to  https://demo.paperless-ngx.com/
![image](https://github.com/paperless-ngx/paperless-ngx/assets/93753661/21db0c8f-026c-4baf-9658-b3ddb4988cae)

### Webserver logs

```bash
Failed to load resource: the server responded with a status of 523 ()
```

### Paperless-ngx version

1.0

### Host OS

Windows

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thanks, it usually fixes itself eventually
