### ISSUE TITLE
[BUG] Configuration file not read in

### ISSUE THREAD

**Issue by fritzchentastig** [paperless-ngx/paperless-ngx#5477]
### Description

When I set up my paperless to be reverse proxied I got a CSRF Auth Error. After checking everything for two days I got to the conclusion that everything that is in the conf file is not read in. As a first step to troubleshoot I set debug to true and so I got to that conclusion that the conf file is ignored.
So I tested different stuff and it seems no settings regarding everything except the DB setup are read in.
I pointed the settings.py directly to the conf file 

### Steps to reproduce

1. Setup paperless on bare metal
2. Setup apache2 as a reverse proxy 
3. Access the site
4. Log In 
5. Error 

### Webserver logs

```bash
● paperless-webserver.service - Paperless webserver
     Loaded: loaded (/etc/systemd/system/paperless-webserver.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-01-20 09:13:07 UTC; 22min ago
   Main PID: 44820 (gunicorn: maste)
      Tasks: 20 (limit: 18073)
     Memory: 253.4M
        CPU: 13.263s
     CGroup: /system.slice/paperless-webserver.service
             ├─44820 "gunicorn: master [paperless.asgi:application]" 
             └─44872 "gunicorn: worker [paperless.asgi:application]" 

Jan 20 09:13:07 fritzchensserver systemd[1]: Started Paperless webserver.
Jan 20 09:13:08 fritzchensserver gunicorn[44820]: [2024-01-20 09:13:08 +0000] [44820] [INFO] Starting gunicorn 21.2.0
Jan 20 09:13:08 fritzchensserver gunicorn[44820]: [2024-01-20 09:13:08 +0000] [44820] [INFO] Listening at: http://[::]:8001 (44820)
Jan 20 09:13:08 fritzchensserver gunicorn[44820]: [2024-01-20 09:13:08 +0000] [44820] [INFO] Using worker: paperless.workers.ConfigurableWorker
Jan 20 09:13:08 fritzchensserver gunicorn[44820]: [2024-01-20 09:13:08 +0000] [44820] [INFO] Server is ready. Spawning workers
Jan 20 09:13:19 fritzchensserver gunicorn[44872]: [2024-01-20 09:13:19,489] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless.redacted.de does not match any trusted origins.): /accounts/login/
Jan 20 09:15:14 fritzchensserver gunicorn[44872]: /opt/paperless/.local/lib/python3.10/site-packages/django/http/response.py:517: Warning: StreamingHttpResponse must consume synchronous iterators in order to serve them asynchronously. Use an asynchronous iterator instead.
Jan 20 09:15:14 fritzchensserver gunicorn[44872]:   warnings.warn(
~
```

### Paperless-ngx version

2.3.3

### Host OS

Ubuntu 22.04 Server

### Installation method

Bare metal

### Browser

Orion (Based on Safari)

### Other

Paperless is set to port 8001 cause crafty already uses port 8000

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by alexmaret** [comment]
Well, what is the contents of your configuration file, what are the filesystem permissions and where is it located?

Also, what happens if you set a configuration as environment variable in your systemd service definition?

**Comment by fritzchentastig** [comment]
It is located at /opt/paperless/paperless-ngx
The permissions are 775
And at the consume folder 777
`# Have a look at the docs for documentation.
# https://docs.paperless-ngx.com/configuration/

# Debug. Only enable this for development.

#PAPERLESS_DEBUG=true

# Required services

#PAPERLESS_REDIS=redis://localhost:6379
#PAPERLESS_DBHOST=localhost
#PAPERLESS_DBPORT=3306
#PAPERLESS_DBNAME=paperless
#PAPERLESS_DBUSER=paperless
#PAPERLESS_DBPASS=[Redacted]
#PAPERLESS_DBSSLMODE=prefer

# Paths and folders

#PAPERLESS_CONSUMPTION_DIR=../consume
#PAPERLESS_DATA_DIR=../data
#PAPERLESS_TRASH_DIR=
#PAPERLESS_MEDIA_ROOT=../media
#PAPERLESS_STATICDIR=../static
#PAPERLESS_FILENAME_FORMAT=
#PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=

# Security and hosting

#PAPERLESS_SECRET_KEY=[Redacted]
#PAPERLESS_URL=https://paperless.[Redacted].de
#PAPERLESS_CSRF_TRUSTED_ORIGINS=https://paperless.[Redacted].de # can be set using PAPERLESS_URL
#PAPERLESS_ALLOWED_HOSTS=fritzchensserver,paperless.[Redacted].de,www.paperless.[Redacted].de # can be set using PAPERLESS_URL
#PAPERLESS_CORS_ALLOWED_HOSTS=https://localhost:8080,https://paperless.[Redacted].de # can be set using PAPERLESS_URL
#PAPERLESS_FORCE_SCRIPT_NAME=
#PAPERLESS_STATIC_URL=/static/
#PAPERLESS_AUTO_LOGIN_USERNAME=
#PAPERLESS_COOKIE_PREFIX=
#PAPERLESS_ENABLE_HTTP_REMOTE_USER=false

# OCR settings

#PAPERLESS_OCR_LANGUAGE=de
#PAPERLESS_OCR_MODE=skip
#PAPERLESS_OCR_SKIP_ARCHIVE_FILE=never
#PAPERLESS_OCR_OUTPUT_TYPE=pdfa
#PAPERLESS_OCR_PAGES=1
#PAPERLESS_OCR_IMAGE_DPI=300
#PAPERLESS_OCR_CLEAN=clean
#PAPERLESS_OCR_DESKEW=true
#PAPERLESS_OCR_ROTATE_PAGES=true
#PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD=12.0
#PAPERLESS_OCR_USER_ARGS={}
#PAPERLESS_CONVERT_MEMORY_LIMIT=0
#PAPERLESS_CONVERT_TMPDIR=/var/tmp/paperless

# Software tweaks

#PAPERLESS_TASK_WORKERS=1
#PAPERLESS_THREADS_PER_WORKER=1
#PAPERLESS_TIME_ZONE=EST
#PAPERLESS_CONSUMER_POLLING=10
#PAPERLESS_CONSUMER_DELETE_DUPLICATES=false
#PAPERLESS_CONSUMER_RECURSIVE=false
#PAPERLESS_CONSUMER_IGNORE_PATTERNS=[".DS_STORE/*", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini"]
#PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=false
#PAPERLESS_CONSUMER_ENABLE_BARCODES=false
#PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT
#PAPERLESS_CONSUMER_BARCODE_UPSCALE=0.0
#PAPERLESS_CONSUMER_BARCODE_DPI=300
#PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED=false
#PAPERLESS_CONSUMER_COLLATE_DOUBLE_SIDED_SUBDIR_NAME=double-sided
#PAPERLESS_CONSUMER_COLLATE_DOUBLE_SIDED_TIFF_SUPPORT=false
#PAPERLESS_FILENAME_DATE_ORDER=YMD
#PAPERLESS_FILENAME_PARSE_TRANSFORMS=[]
#PAPERLESS_NUMBER_OF_SUGGESTED_DATES=5
#PAPERLESS_THUMBNAIL_FONT_NAME=
#PAPERLESS_IGNORE_DATES=
#PAPERLESS_ENABLE_UPDATE_CHECK=

# Tika settings

#PAPERLESS_TIKA_ENABLED=false
#PAPERLESS_TIKA_ENDPOINT=http://localhost:9998
#PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://localhost:3000
`
I didn't try the last part

**Comment by fritzchentastig** [comment]
I have tried it with the environmental variable and it didn't work
I can't even activate Debug

**Comment by alexmaret** [comment]
All these options are commented out. Any line that starts with '#' is ignored.

If you remove the '#' from those options which you want to set, it should work. To fix your CSRF issue, it should be enough to set:
```
PAPERLESS_URL=https://paperless.[Redacted].de
```

**Comment by fritzchentastig** [comment]
Well that was it
May I suggest a small hint to that behavior in the docs and the sample conf. Cause as someone new to the software and FOSS in general it is not allways obvious how conf files are supposed to be read and I thought they should be read this way.

**Comment by fritzchentastig** [comment]
Anyway that solved it
