### ISSUE TITLE
[BUG] PAPERLESS_CONSUMER_* parameters in docker-compose.env are ignored

### ISSUE THREAD

**Issue by bscx** [paperless-ngx/paperless-ngx#5493]
### Description

Summary: It looks like all PAPERLESS_CONSUMER_* parameters are ignored although explicitly specified in my docker-compose.env. Other parameters (PAPERLESS_PCR_DESKEW, PAPERLESS_TIME_ZONE, PAPERLESS_SECRET_KEY, ...) would be used  though.

My `docker-compose.env`:
```
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true
PAPERLESS_FILENAME_FORMAT={created_year}/{created_year}-{created_month}-{created_day} {document_type} {correspondent} {title}
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_OCR_DESKEW=false
PAPERLESS_SECRET_KEY=xxx
```

Container details (after having started the instance):
```
PAPERLESS_FILENAME_FORMAT	{created_year}/{created_year}-{created_month}-{created_day} {document_type} {correspondent} {title}
PAPERLESS_OCR_DESKEW	false
PAPERLESS_OCR_LANGUAGE	deu+eng
...
```

```
$ docker compose version
Docker Compose version v2.24.1
```

I'm using Paperless-ngx 2.4.0 and inotify, PAPERLESS_CONSUMER_POLLING wouldn't work either.

### Steps to reproduce

1. Stop the paperless-ngx instance
2. Specify PAPERLESS_CONSUMER_RECURSIVE=true in docker-compose.env
3. Start the paperless-ngx instance
4. Check container details, PAPERLESS_CONSUMER_* won't be there
5. Create a file in subfolder of consume folder which wouldn't be consumed

### Webserver logs

```bash
[2024-01-21 19:11:01,966] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
```

### Paperless-ngx version

2.4.0

### Host OS

Debian 11.8

### Installation method

Docker - official image

### Browser

Safari, Chrome

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You must recreate a container for environment changes to be applied.  Restarting is not sufficient.

**Comment by bscx** [comment]
Oh my word. You're absolutely right, this is not a bug. Thank you so much!
