### ISSUE TITLE
[BUG] paperless-ngx subpath intallation broken with uvicorn 0.26

### ISSUE THREAD

**Issue by gringus** [paperless-ngx/paperless-ngx#5494]
### Description

paperless-ngx fails to properly redirect in subpath setup (eg. https://example.com/paperless) when running with uvicorn 0.26. This is likely due to https://github.com/encode/uvicorn/commit/4af46c931c64a4e32c37faec9ce531cca57e4cf7
uvicorn 0.25 works just fine.

### Steps to reproduce

1. install paperless-ngx with uvicorn 0.26 and configure it with subpath (eg. https://example.com/paperless)
2. Go to the landing page (https://example.com/paperless)
3. The landing page won't be shown.

### Webserver logs

```
2a02:a466:ff0:1::4 - - [21/Jan/2024:09:39:03 +0100] "GET /papeless/accounts/login/?next=/papeless/papeless/accounts/login/%3Fnext%3D/papeless/papeless/accounts/login/%253Fnext%253D/papeless/papeless/accounts/login/%25253Fnext%25253D/papeless/papeless/accounts/login/%2525253Fnext%2525253D/papeless/papeless/accounts/login/%252525253Fnext%252525253D/papeless/papeless/accounts/login/%25252525253Fnext%25252525253D/papeless/papeless/accounts/login/%2525252525253Fnext%2525252525253D/papeless/papeless/accounts/login/%252525252525253Fnext%252525252525253D/papeless/papeless/accounts/login/%25252525252525253Fnext%25252525252525253D/papeless/papeless/accounts/login/%2525252525252525253Fnext%2525252525252525253D/papeless/papeless/accounts/login/%252525252525252525253Fnext%252525252525252525253D/papeless/papeless/accounts/login/%25252525252525252525253Fnext%25252525252525252525253D/papeless/papeless/accounts/login/%2525252525252525252525253Fnext%2525252525252525252525253D/papeless/papeless/accounts/login/%252525252525252525252525253Fnext%252525252525252525252525253D/papeless/papeless/accounts/login/%25252525252525252525252525253Fnext%25252525252525252525252525253D/papeless/papeless/accounts/login/%2525252525252525252525252525253Fnext%2525252525252525252525252525253D/papeless/papeless/accounts/login/%252525252525252525252525252525253Fnext%252525252525252525252525252525253D/papeless/papeless/ HTTP/3.0" 302 1330 0.004/0.004 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0" "-|-"
```

### Paperless-ngx version

2.4.0

### Host OS

Gentoo x86_64

### Installation method

Other (please describe above)

### Browser

Firefox, Chromium

### Configuration changes

PAPERLESS_FORCE_SCRIPT_NAME=/docs PAPERLESS_STATIC_URL=/docs/static/

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Are you suggesting we lock unicorn to 0.25? I don’t even see us directly using root-path so seems like that’s the solution, unfortunately. I can’t tell if they meant for 0.26 to be a breaking change, surprising if so.

Since you presumably have a ‘bare metal’ install seems like the answer is “don’t install 0.26” in the meantime.

Perhaps some else has a better solution, but…

**Comment by shamoon** [comment]
Ah

https://github.com/paperless-ngx/paperless-ngx/blob/3d11b9c8ecebb61415e59284dd57c9e2afa155ea/src/paperless/workers.py#L11

**Comment by shamoon** [comment]
Did you notice your logs say “papeless/accounts”?

**Comment by gringus** [comment]
Unfortunately not.

**Comment by gringus** [comment]
I would say that currently using `uvicorn 0.26` will cause problems in certain scenarios. In my case, I install `paperless-ngx` from sources on my home server (no docker).

**Comment by stumpylog** [comment]
We still provide the versions we know work, and if you are choosing to install something else, that really is at your own risk.

This doesn't feel like a big, but just heads up for some future maybe bug.

**Comment by stumpylog** [comment]
And frankly, this seems like a user action is needed.  As pointed out above, there is already a setting to configure that uvicorn setting, so this seems not like a bug.  If/when we update to 0.26, we can flag that for users to know they need to take action

**Comment by gringus** [comment]
1 comment and 1 question:
* In `Pipfile` you do not restrict `uvicorn` version, so likely some people will run into trouble (non-docker folks). I have my workaround, so it's up to you to decide what you are going to do with this piece of information.
* So what should be the new configuration with `uvicorn 0.26` if you want to provide `paperless-ngx` under `https://example.com/paperless` URL? I tried multiple combinations, but none of them worked..

**Comment by shamoon** [comment]
- Yea, I think locking it for now will be an immediate solution for bare-metal installs like yourself.
- This is a great question and I definitely dont know the answer, I find this rather confusing. You mean you tried different options for `PAPERLESS_FORCE_SCRIPT_NAME`, correct? Did you also try adjusting the settings at your reverse proxy. Thats the part that I find confusing / unclear how to easily test.

**Comment by gringus** [comment]
Yes, I tried to tweak `PAPERLESS_URL` along with `PAPERLESS_FORCE_SCRIPT_NAME` and `PAPERLESS_STATIC_URL`. None of the combinations gave me a landing page :-( I can try experimenting a bit more, but likely we will need a patch or something..

**Comment by stumpylog** [comment]
If a user is following the bare metal installation instructions, they will end up with 0.25 right now anyway, so this seems pretty low priority.  We can't really help users who decide not to use the versions we're specifying.  

We'll just lock it for now and if anyone every actually understands the new requirement, can unlock and add documentation.

**Comment by shamoon** [comment]
> If a user is following the bare metal installation instructions, they will end up with 0.25 right now anyway

Thanks for clarifying that stumpy, I misunderstood that

**Comment by gringus** [comment]
Sounds fair..

**Comment by shamoon** [comment]
Thanks for the report, I think this is resolved as above.
