### ISSUE TITLE
[BUG] App Config does not enforce permissions

### ISSUE THREAD

**Issue by hansmi** [paperless-ngx/paperless-ngx#5515]
### Description

Since Paperless 2.3 or 2.4 there's a new menu item named "Configuration" where it's possible to override the logo and a few OCR settings. I'm using a group named `humans` for everyday operations. The group has mere "view" permissions for type "admin":

![image](https://github.com/paperless-ngx/paperless-ngx/assets/3238454/d500df7f-f95b-4d31-b91c-5df23acf6bd0)

And yet the users in that group can modify application configurations. I believe this is caused by the `/api/config/` endpoint not having authorization beyond `IsAuthenticated`:

https://github.com/paperless-ngx/paperless-ngx/blob/6d6650d5f6952f3129e9f4632cd149914b344767/src/paperless/views.py#L169

Removing the "view" permission bit, leaving the group without any for the "admin" type, only hides the UI elements. The underlying API is unaffected.

### Steps to reproduce

1. Authenticate with a user with no permissions for type "admin" other than "view" (the latter being optional if using the API directly).
1. Navigate to `/config` (Application Configuration).
1. Change values.
1. Save.

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.4.0

### Host OS

Debian Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
The permissions for app config just aren't being shown, easy to fix

<img width="751" alt="Screenshot 2024-01-23 at 11 29 29 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/54ecc178-791b-4992-a810-abc6d0cc2d30">

**Comment by shamoon** [comment]
Edit: good point, they're also not being enforced at all, will fix that too
