### ISSUE TITLE
[BUG] Crop gets not respected correctly when creating previews

### ISSUE THREAD

**Issue by henningBunk** [paperless-ngx/paperless-ngx#5517]
### Description

I often crop pages with PDF XChange Editor when they are not Din A4. This results in smaller page formats. 

![Screenshot 2024-01-23 205452](https://github.com/paperless-ngx/paperless-ngx/assets/14870695/a82d2dcb-038c-4da7-80ef-3d36a85c1717)

Usually this works fine. Paperless displays the documents correctly when opened. But the previews are faulty. 

It creates a preview for the whole page (cropped area and uncropped area) but sets all content outside of the cropping boundaries to white.

![Screenshot 2024-01-23 205854](https://github.com/paperless-ngx/paperless-ngx/assets/14870695/b43fbb41-996e-41f4-bc67-36259f0c5769)

Paperless should respect the set page boundaries when creating previews.

### Steps to reproduce

1. Create a pdf file which uses a crop box
2. Upload to paperless

### Webserver logs

```bash
convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-tewn1kwk/archive.pdf[0] /tmp/paperless/paperless-tewn1kwk/convert.webp
```

### Paperless-ngx version

2.4.0

### Host OS

Unraid

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thumbnail generation uses https://linux.die.net/man/1/convert so if that is not respecting the crop box thats where you'd raise an issue. But frankly, I dont think its doing something wrong, cropbox seems to only have to do with PDF viewers see https://wiki.scribus.net/canvas/PDF_Boxes_:_mediabox,_cropbox,_bleedbox,_trimbox,_artbox

**Comment by henningBunk** [comment]
@shamoon i looked into it and convert is able to respect the cropbox with the argument `-define pdf:use-cropbox=true`. Tested it succesfully with my file.

> cropbox seems to only have to do with PDF viewers

I think this is more a point pro supporting it. The preview windows arent anything but a small pdf viewer.
