### ISSUE TITLE
[BUG] Documents no longer open

### ISSUE THREAD

**Issue by ClamsyHub** [paperless-ngx/paperless-ngx#5541]
### Description

When I open a document, assign a tag and click Save and Next, it doesn't always happen, but very often, that the next document doesn't open. It just says “loading” on the right. All links on Paperless are not clickable and the page cannot be reloaded. The only solution is to close and reopen the Safari browser or open a new tab.

### Steps to reproduce

I have a filter with TAG "INBOX" where I currently have around 1,000 documents. The documents are sorted alphabetically in ascending order.
1.) I open the 1st document
2.) I assign an existing TAG
3.) Click on Save and Continue

Next document opens, or not.
Sometimes it works for a few documents, sometimes it happens immediately with the next document.

When evaluating the logs, I saw that the emails were being checked at the same time. Is there perhaps a connection?

### Webserver logs

```bash
[2024-01-25 08:50:01,744] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[9aa475a7-3857-4f5b-925c-87f1033b12cf] succeeded in 1.6577134882099926s: 'No new documents were added.'
[2024-01-25 09:00:00,096] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
[2024-01-25 09:00:00,100] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[78650b55-82f9-441e-8918-0781d5b669e9] received
[2024-01-25 09:00:01,280] [ERROR] [paperless_mail] Rule Filearchiv.Fileablage: Error while processing rule: date value out of range
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 514, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 561, in _handle_mail_rule
    criterias = make_criterias(rule, supports_gmail_labels)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 372, in make_criterias
    maximum_age = date.today() - timedelta(days=rule.maximum_age)
                  ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: date value out of range
[2024-01-25 09:00:01,903] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[78650b55-82f9-441e-8918-0781d5b669e9] succeeded in 1.7995521272532642s: 'No new documents were added.'
```

### Paperless-ngx version

2.4.1

### Host OS

linux x86_64 Synology NAS

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

No

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by ClamsyHub** [comment]
It works on the iPad

**Comment by stumpylog** [comment]
What does the network tools tab show?

**Comment by ClamsyHub** [comment]
I don't see any problems there.
What do you need exactly? I'm not a programmer, hence the question.

I found that with the change from 2.4.0 to 2.4.1 it only occurs on the iMac and Safari. With 2.4.0 everything worked fine.

I have now installed Firefox on the iMac, so it works without any errors. iPhone and iPad also work. This problem only occurs on the iMac and Safari when switching from 2.4.0 to 2.4.1.

**Comment by saadmajeed01** [comment]
Can I get Paperless White-label version because I want to change Paperless-ngx icons.
It is a simple question, if someone can reply me about this.
Thank You

**Comment by shamoon** [comment]
I cant reproduce this on Safari 17.1 (19616.2.9.11.7). Im not clear that the mail error is related but I doubt it. In general, we would need more information if this is actually reproducible / fixable. At the moment there isnt much actionable unfortunately

I also tested going back a few versions

<img width="1973" alt="Screenshot 2024-01-25 at 7 05 46 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/4a0078f8-3363-4a8a-8489-9be2cb26412d">

**Comment by shamoon** [comment]
Perhaps try switching to the browser pdf viewer

**Comment by shamoon** [comment]
And the other place to look is the js console error in the browser

**Comment by ClamsyHub** [comment]
> Perhaps try switching to the browser pdf viewer

already tried, without success.

**Comment by shamoon** [comment]
Can you send the metadata of the doc, eg look at the metadata api endpoint in your browser

**Comment by ClamsyHub** [comment]
That was now a document where it was hung again.

If I close the tab and open a new tab, the document works. If I go to the next document, it may or may not work.


Geändert am | 25. Januar 2024
-- | --
Hinzugefügt am | 25. Januar 2024
Media-Dateiname | 2016/Continentale Versicherung/Anforderung Beitragsnachweis-1-1.pdf
Ursprünglicher Dateiname | Anforderung Beitragsnachweis-1-1.pdf
MD5-Prüfsumme Original | 7b30c8765258718f002b3d857b0eb8f1
Dateigröße Original | 143 KB
MIME-Typ Original | application/pdf

I have already stopped and restarted the Docker Stack. Cleared the browser cache. Logged out of Paperless and logged back in.

**Comment by shamoon** [comment]
Yea I dunno.

As stumpylog asked, anything under the network tab (make sure to open it before you load the page), like 'stuck' network calls etc

**Comment by ClamsyHub** [comment]
My English is not really good. I also use Google Translate.

What do you think? I don't know what I should or can deliver to you?

Portainer --> Networks --> paperless_default --> and then?

I don't see any logs or anything like that. We could do a web session. Zoom, Teams, Webex or something like that.

**Comment by stumpylog** [comment]
The network tab we're talking about is in the browser.  For Firefox at least, it is opened with F12, then has a tab named Network

**Comment by ClamsyHub** [comment]
Ah I understand.

The developer tools ;-) I found it.

An error has occurred. And it depends on suggestions and metadata.

**Comment by ClamsyHub** [comment]
metadata Header:

3
234
12,4 MB
12,5 MB
0
397 ms
Übersicht
URL: https://paperless.aumillers.eu/api/documents/8947/metadata/
Status: 200
Quelle: Netzwerk
Initiator: 
polyfills.js:1:32060

Anfrage
Accept: application/json; version=4
Referer: https://paperless.aumillers.eu/documents/8947/details
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
X-CSRFToken: wdutzKiUW8nUjwWaPYQYeK2SMrJmEwki

Antwort
allow: GET, HEAD, OPTIONS
Content-Language: de-de
Content-Length: 399
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Thu, 25 Jan 2024 16:35:25 GMT
ETag: "115a5d414cc7685349b87b997ca82021"
Last-Modified: Thu, 25 Jan 2024 16:32:04 GMT
Referrer-Policy: same-origin
Server: nginx
Vary: Accept, Accept-Language, origin, Cookie
x-api-version: 4
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
x-version: 2.4.1

**Comment by shamoon** [comment]
So just to clarify, since I cant tell from the above. Are metadata and suggestions both "stuck"? Is either one returning any data successfully?

If you are willing, would you be able to try out two different docker images:
- fix-5541
- fix-5541-2

Let us know if they make any difference (both should be safe to use on a 2.4.1 installation)

**Comment by ClamsyHub** [comment]
Yes, they both hang. And they're still hanging, I haven't closed the window at the moment. The document may or may not be shown after 15 minutes or more.

I would like to test the fixes. Only now I'm probably at the end of my layman's knowledge of programming.

I have a "stack" in Portainer. How do I get the image with the fixes in there now? What do I have to change or add to the stack so that the image with the fixes is pulled? I learn quickly and with pleasure, but I don't know what to do next.

**Comment by ClamsyHub** [comment]
Suggestions:

3
29
3,08 MB
1,49 MB
0
433 ms
Übersicht
URL: https://URL/api/documents/8947/suggestions/
Status: 304
Quelle: Netzwerk
Initiator: 
polyfills.js:1:32060

Anfrage
Accept: application/json; version=4
Referer: https://URL/documents/8947/details
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
X-CSRFToken: wdutzKiUW8nUjwWaPYQYeK2SMrJmEwki

Antwort
allow: GET, HEAD, OPTIONS
Content-Language: de-de
Content-Length: 0
Cross-Origin-Opener-Policy: same-origin
Date: Thu, 25 Jan 2024 16:46:37 GMT
ETag: "b'#\x8b\xca\x8d\x9c7\xb2T2\ts\x83\xf1\xe9\xa1$7\xf8-\xdf\x0e\x85Ch\xc4\x15\x95$$Ed\xa2':3"
Last-Modified: Thu, 25 Jan 2024 16:01:13 GMT
Referrer-Policy: same-origin
Server: nginx
Vary: Accept, Accept-Language, origin, Cookie
x-api-version: 4
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
x-version: 2.4.1


Metadata:

3
29
3,08 MB
1,49 MB
0
433 ms
Übersicht
URL: https://URL/api/documents/8947/metadata/
Status: 304
Quelle: Netzwerk
Initiator: 
polyfills.js:1:32060

Anfrage
Accept: application/json; version=4
Referer: https://URL/documents/8947/details
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
X-CSRFToken: wdutzKiUW8nUjwWaPYQYeK2SMrJmEwki

Antwort
allow: GET, HEAD, OPTIONS
Content-Language: de-de
Content-Length: 0
Cross-Origin-Opener-Policy: same-origin
Date: Thu, 25 Jan 2024 16:46:37 GMT
ETag: "115a5d414cc7685349b87b997ca82021"
Last-Modified: Thu, 25 Jan 2024 16:32:04 GMT
Referrer-Policy: same-origin
Server: nginx
Vary: Accept, Accept-Language, origin, Cookie
x-api-version: 4
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
x-version: 2.4.1

**Comment by shamoon** [comment]
Yea, my guess is the `/suggestions/` endpoint is the real problem and the changes in 2.4.1 have unmasked that.

Is your server CPU / memory very high too? Perhaps its just running out of resources as `/suggestions/` can be resource-intensive.

To change the image in portainer, see https://docs.portainer.io/user/docker/containers/edit you'll want to edit the "Image" field

**Comment by ClamsyHub** [comment]
I got the Synology DS423+ and expanded the memory from 2GB to 18GB.
This morning it was still working when I was working on 2.4.0, but then I read about this "important" update and switched to 2.4.1, and I've had the problem ever since. But strangely enough, only on the iMac with Safari. iMac and Firefox work as expected without errors, and Paperless also runs without errors on iPhone and iPad.

I know that about the image - i.e. how I can choose the main versions:
     image: paperlessngx/paperless-ngx:latest
or
     image: paperlessngx/paperless-ngx:2.4.0
Is it enough if I change this as follows?
     image: paperlessngx/paperless-ngx:fix-5541-2
does it work?

**Comment by shamoon** [comment]
Yea I cant explain the difference between the browsers on desktop or in general why the suggestions endpoint is hanging.

Yes, to try those images you would change `image: ghcr.io/paperless-ngx/paperless-ngx:latest` to e.g. `image: ghcr.io/paperless-ngx/paperless-ngx:fix-5541`

**Comment by ClamsyHub** [comment]
It looks good.
I've been adding tags to documents for 5 minutes now and the error hasn't recurred yet. I will now work for about 1 hour. There are still enough changes going on that I will make today.
I will get back to you later and give feedback.

I have now installed the image fix-5541.

**Comment by shamoon** [comment]
Gotcha, so just making sure, youre saying `fix-5541` is working better? Thanks, that one is pretty simple

**Comment by ClamsyHub** [comment]
Yes, Fix-5541 works better. I have now processed about 100 documents without the error occurring again. Now it's back to what I expect.

Thanks so much. And thank you very much for this super fast support! And thank you for being patient with me, who can't program, and maybe having to explain a little more here and there ;-) You're doing a good job!
