### ISSUE TITLE
[BUG] Demo is offline

### ISSUE THREAD

**Issue by Pudda** [paperless-ngx/paperless-ngx#5556]
### Description

https://demo.paperless-ngx.com

Cloudflare > connection is secure, proceeding.  Then
Timeout. 404 host.

### Steps to reproduce

1. go to https://demo.paperless-ngx.com
2. wait.

### Webserver logs

```bash
NA
```

### Paperless-ngx version

unknown

### Host OS

Mac

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
The demo has been having major issues lately. We may have to remove it or figure something else out thanks
