### ISSUE TITLE
[BUG] Preview fails with Factur-X / EN 16931

### ISSUE THREAD

**Issue by CapoD** [paperless-ngx/paperless-ngx#5564]
### Description

I received an invoice that seems to be formatted in [Factur-X](http://fnfe-mpe.org/factur-x/factur-x_en/). As far as I can tell the document content is extracted properly and tags, document type, etc. are also matched properly. 
However, if I open the document in Details-Mode, the PDF Preview keeps on loading and never finishes, since the `api/documents/<id>/metadata/` request never completes. (Actually, the `/api/documents/<id>/preview/` request completes)

The corresponding logs are reporting the following:
```
[...] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#}ConformanceLevel: EN 16931. Error: 'urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#'
```

Unfortunately, I may not share the document, but [this document](https://www.pdflib.com/fileadmin/pdf-knowledge-base/zugferd/zugferd1_invoice_pdfa3b.pdf) will produce a similar error (ConformanceLevel is different):
```
[...] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {urn:ferd:pdfa:CrossIndustryDocument:invoice:1p0#}ConformanceLevel: BASIC. Error: 'urn:ferd:pdfa:CrossIndustryDocument:invoice:1p0#'
```

### Steps to reproduce

1. Consume a Factur-X document (See sample document)
2. Open Details-View for this document

### Webserver logs

```bash
[...] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#}ConformanceLevel: EN 16931. Error: 'urn:factur-x:pdfa:CrossIndustryDocument:invoice:1p0#'
```

### Browser logs

```bash
GET Request /api/documents/<id>/metadata/ will eventually time-out
```

### Paperless-ngx version

2.4.2

### Host OS

Ubuntu 20.04.6 LTS / RaspberryPi / arm64

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

no

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Can't reproduce this with Firefox or Chrome.  The warning isn't relevant, all errors during getting metadata are handled and a response is always returned.  Perhaps related to #5541, which was also Safari, but also couldn't be reproduced.

**Comment by shamoon** [comment]
Nor with safari

<img width="1898" alt="Screenshot 2024-01-27 at 8 24 45 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/2ddae65a-fc2a-4863-9974-459fbef85978">

**Comment by alexmaret** [comment]
What you can try is always pre-convert your documents. That fixes many issues with invalid or "special" PDFs. If you do it with a pre-consumption script, then paperless will still have the original document, but the one that is displayed, will have been cleaned up.

I had a similar problem and I'm doing pre-consumption as described here: https://github.com/paperless-ngx/paperless-ngx/discussions/5387

**Comment by CapoD** [comment]
Thank you very much for your effort. On my side, I can reproduce the issue also with Chrome and even with cURL. However, if nobody else may reproduce the issue, I will have to look into it on my site.

<img width="1158" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/7033315/373bff5a-5ebe-4732-ab0c-ccc3ed262b7e">
