### ISSUE TITLE
[BUG/ISSUE] Import procedure fails with "The manifest file refers to...which does not appear to be in the source directory", similar to #4485

### ISSUE THREAD

**Issue by HorstyS** [paperless-ngx/paperless-ngx#5588]
### Description

This is an issue which is maybe similar to #4485 , but it doesn't seem to be related with Umlaute in my case. 
The situation is, that I want to replace my old Ubuntu server with a new machine. So I set up the new machine  with the same Ubuntu version 22.04.3 LTS, some docker versions ect....pulled the latest NGX version 2.4.3 (same as on the old machine) and started.
What I did:

1. Export from my "old" Ubuntu machine with `sudo docker-compose exec -T webserver document_exporter ../export`
![export_01](https://github.com/paperless-ngx/paperless-ngx/assets/101665247/1ba3ac69-2d2b-4f50-a73a-8c8f266e76f1)
Export was obviously successful

2. Copied the whole folder to the new machine and started the import
![import_01](https://github.com/paperless-ngx/paperless-ngx/assets/101665247/e4957b1e-b5fa-44a1-98b2-d85cc1e3b9ce)
The import fails with `CommandError: The manifest file refers to "2000-03-13 2000-03-13 DAK Ablehnung HH.pdf" which does not appear to be in the source directory.
Found existing user(s), this might indicate a non-empty installation`

I checked the manifest file information: 
```
file -i ./export/manifest.json
./export/manifest.json: text/plain; charset=utf-8
```
The file 2000-03-13 2000-03-13 DAK Ablehnung HH.pdf is in the folder (for whatever reason several times with different file extensions) and has no Umlaut.

Any ideas what the reason might be?

### Steps to reproduce

See above

### Webserver logs

```bash
None
```

### Paperless-ngx version

2.4.3

### Host OS

Ubuntu 22.04.03 LTS

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
If the basic Python call for a file's existence says it's not there, I'm highly inclined to believe it.  Perhaps it has invalid characters which appear normal but are not.

**Comment by HorstyS** [comment]
i do understand your impression, but as you can see in the second picture the file(s) are in the export folder, with the exact naming it is complaining about.
is there a debug mode which traces all import steps I can activate?

**Comment by stumpylog** [comment]
There is nothing to trace.  The code asks the filesystem if the file exists, it says not:

https://github.com/paperless-ngx/paperless-ngx/blob/2c8fddb554c79fdf80cb3574ac5cb7894e801140/src/documents/management/commands/document_importer.py#L216-L220

It's very simple code

**Comment by shamoon** [comment]
Does the import start and just fail on this doc or is that the first one?

the importer hasn’t been changed much in a long time and we’re not aware of any current issues.

**Comment by HorstyS** [comment]
I now somehow managed to import the data.
No idea what was now different, but I have got a feeling that it is somehow realted with the start of the docker container that (re)created the export folder at the same place I used for my previously pasted export folder.

**Comment by Freika** [comment]
Well, it is actually a bug. A file with `ä` (and probably other similar symbols) in the name is being written into manifest as `a\u0308` (example: `"title": "Besta\u0308tigung der Vertragsbeendigung",`) and couldn't be found during the import process even though it is present in the directory.
