### ISSUE TITLE
[BUG] Unicode characters are not formatted properly in Content-Disposition field, causes issues in firefox

### ISSUE THREAD

**Issue by Nicarim** [paperless-ngx/paperless-ngx#56]
**Describe the bug**
When the filename of the file that you try to download from paperless contains UTF-8 characters after formatting, firefox will not able to properly format the resulting filename, causing issues when saving and trying to preview it. 

Related issue in original repository https://github.com/jonaswinkler/paperless-ng/issues/838

**To Reproduce**
0. Use Firefox
1. Create a new document in paperless
2. Create correspondent with UTF-8 characters like "Urząd Gorzów Document"
3. Assign the correspondent to the newly created document
4. Attempt to download the file
5. File will be saved as `.pdf` instead of proper name

**Expected behavior**
File should save as `Urząd Gorzów Document.pd`

**Screenshots**
![image](https://user-images.githubusercontent.com/655590/154153312-5dca96e6-5ea6-4c40-a971-5165f1a7fce2.png)

**Webserver logs**
There is no error in logs.

**Relevant information**
 - Linux - Manjaro
 - Firefox
 - 96.0.3 (64-bit)
 - Installation method: docker
 - Default configuration

**Comment by qcasey** [comment]
Fixed in #57
