### ISSUE TITLE
[BUG] Cyrillic character recognition doesn't work

### ISSUE THREAD

**Issue by Prominence** [paperless-ngx/paperless-ngx#560]
**Describe the bug**
Cyrillic character recognition doesn't work. Instead, it show a latin similar characters.

**To Reproduce**
1. Load a document with cyrillic symbols.
2. Click `Edit` on document.
3. Open `Content` tab.
4. See something like that: 
```
Hanpapnenue
Ha maTouoro-rMucTouorMyeckoe UccuIeHOBaHHe
```

**Expected behavior**
Cyrillic symbols are there, like it is in an original PDF document.

**Screenshots**
![image](https://user-images.githubusercontent.com/6312697/160596049-90b31c40-1c83-4542-addf-518146c53ec3.png)
![image](https://user-images.githubusercontent.com/6312697/160596138-ea262d84-07ff-44ac-9839-809d5f477b45.png)

**Relevant information**
 - Host OS of the machine running paperless: openmediavault
 - Version: Paperless-ngx 1.6.0 
 - Installation method: docker

**Comment by shamoon** [comment]
Did you set the language for OCR? https://paperless-ngx.readthedocs.io/en/latest/configuration.html#ocr-settings

**Comment by Prominence** [comment]
> Did you set the language for OCR? https://paperless-ngx.readthedocs.io/en/latest/configuration.html#ocr-settings

Wow, I missed that configuration property. I'm going to check it soon. If it works - I'll close the issue.

**Comment by Prominence** [comment]
FYI: It also required to install appropriate tesseract packages inside docker container: `apt install tesseract-ocr-rus tesseract-ocr-bel`.
Probably it could help someone.

@shamoon, shouldn't it be noted in the documentation? :)

Another important question: could I somehow manually trigger to rescan(OCR) already processed documents? Some button on UI or a CLI command at least?

**Comment by shamoon** [comment]
Maybe take a look at https://github.com/jonaswinkler/paperless-ng/issues/1474

Perhaps this issue can be closed?

**Comment by Prominence** [comment]
> Maybe take a look at [jonaswinkler/paperless-ng#1474](https://github.com/jonaswinkler/paperless-ng/issues/1474)
> 
> Perhaps this issue can be closed?

Thanks, it works.
Yes, I'll close it.
