### ISSUE TITLE
[BUG] Adding a custom field with the same name of an existing field leads to internal server error

### ISSUE THREAD

**Issue by pustekuchen91** [paperless-ngx/paperless-ngx#5643]
### Description

If you try to add a custom field with the name of an already existing custom field name, an internal error occours.

### Steps to reproduce

1. Create custom field "ABC" with type integer
1. Create another custom field "ABC" with type string

### Webserver logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"Internal Server Error","url":"http://paperless.local/api/custom_fields/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://paperless.local/api/custom_fields/: 500 Internal Server Error","error":"\n<!doctype html>\n<html lang=\"en\">\n<head>\n  <title>Server Error (500)</title>\n</head>\n<body>\n  <h1>Server Error (500)</h1><p></p>\n</body>\n</html>\n"}
```

### Paperless-ngx version

2.4.2

### Host OS

GNU/Linux synology_braswell_216

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I get an IntegrityError including the files name. Seems clear enough?

```
IntegrityError at /api/custom_fields/ UNIQUE
constraint failed:
documents_customfield.name
```

![IMG_2706](https://github.com/paperless-ngx/paperless-ngx/assets/4887959/bb96466c-290a-4466-9061-8dc35e85d0eb)

**Comment by stumpylog** [comment]
We could probably check and return a bad request instead.  Slightly nicer.

**Comment by shamoon** [comment]
Sure

**Comment by stumpylog** [comment]
It's this issue, again: https://github.com/encode/django-rest-framework/issues/7173

Maybe someday they will release again

**Comment by shamoon** [comment]
Oh right, forgot about that. Insane to me its been 2y since a DRF release.

You want to take care of that? Im happy to if not!
