### ISSUE TITLE
[BUG] Error loop after entering invalid formated value for a custom field

### ISSUE THREAD

**Issue by pustekuchen91** [paperless-ngx/paperless-ngx#5644]
### Description

If a custom field is added to a document (e.g. number) and entered value is not in the excepted format an error will be shown. The value will then be fixed automatically, but saving the document still leads to the error (although the value entered is in the correct format)

### Steps to reproduce

1. Create Custom field of type integer
2. Add this CF to a document
3. set the value to `123,00`
4. Error appear (which is fine)
5. Value is corrected to `123`
6. Save -> Still leads to an error

Same is like if you use a floating point field and enter a value with "," instead of "."

### Webserver logs

```bash
.
```

### Browser logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://paperless.local/api/documents/719/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://paperless.local/api/documents/719/: 400 Bad Request","error":{"custom_fields":[{"field":["Dieses Feld darf nicht null sein."]},{},{}]}}
```

### Paperless-ngx version

2.4.2

### Host OS

GNU/Linux synology_braswell_216

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
I cannot reproduce.  I can't even add a non-numerical character to the field box

**Comment by shamoon** [comment]
I had the same confusion at first but 123,00 is European for 123.00 😂 which will be allowed in the form and I see the issue. Already have a fix, just double-checking it

**Comment by pustekuchen91** [comment]
I think one more issue is, that the validation only starts after the field looses the focus. 

I was adding the value to the field and immediately clicked the save button, without leaving the field first to trigger the validation.

This seems to lead to some strange problems

**Comment by pustekuchen91** [comment]
or here the validation changes the value, but saving fails

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/7147324/13218d9a-1a1d-4e53-b416-7a265cf86fa5)
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/7147324/b84dfcbd-1ec2-4b0e-8143-b345023a158d)

**Comment by shamoon** [comment]
The second thing is not a bug, thats expected, but I think you'll find the PR also makes that less "strange" too
