### ISSUE TITLE
[BUG] Document action buttons do not respect group permissions - only owner can change, even if group permissions allow this 

### ISSUE THREAD

**Issue by frankprimarily** [paperless-ngx/paperless-ngx#5678]
### Description

A document with with edit permissions to a group can only be deleted by the owner, but not by other uses in the same group, even if group permission are allowing deletion.

I believe the PR #5194 missed the use case other people then the owner needs to delete the document.

### Steps to reproduce

- Create group
- create 2 users
- add document, set owner to user 1, group has edit permission
- login as user 2, delete / share etc buttons are disabled

Enabling the buttons (via web debugger) will allow to delete the document. (API does accept the request)

### Webserver logs

```bash
no logs - button just grayed out
```

### Paperless-ngx version

2.4.3

### Host OS

raspi arm

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I realize this can be confusing, youre not the first. But what you are referring to are 'global' permissions, i.e. the ability to delete in general.

Deleting documents has only ever been granted to the owner. This be non-trivial to change (though definitely not impossible) and would have to be "opt-in" to prevent breaking the current system.

There may be an open FR, youre welcome to open one if not.
