### ISSUE TITLE
[BUG] Workflow with empty "filter sources" never matches anything

### ISSUE THREAD

**Issue by denilsonsa** [paperless-ngx/paperless-ngx#5695]
### Description

If the workflow has an empty list of Filter Sources, it will never match.

### Steps to reproduce

1. Create a new Workflow.
2. Add a new Trigger.
3. Set the type to *Consumption Started* (the default type).
4. Set *Filter filename* to something like `Foobar*.pdf`.
5. Click on *Filter Sources*. Add one. Add another. Then change your mind and remove all filter sources.
6. Add an action. Whatever action.
7. Save.
8. Now upload a `Foobar-xyz.pdf` document.
9. BUG! Observe how the action was NOT performed.

### Webserver logs

```
[DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin
[INFO] [paperless.matching] Document did not match Workflow: FoobarWorkflow1
[DEBUG] [paperless.matching] ('Document source ApiUpload not in []',)
[INFO] [paperless.tasks] WorkflowTriggerPlugin completed with no message
[INFO] [paperless.consumer] Consuming Foobar-xyz.pdf
```

Observe `Document source ApiUpload not in []`. This means this workflow will never match anything, as no string will ever be found inside an empty list.

`<guesswork>`I'm not sure if the "step 5" above was enough to trigger this bug. I'm not sure if there is a difference between "never touched that form field, and then it's null" versus "removed everything and it's now empty but not null".`</guesswork>`

In any way, the UI is letting the user create a broken workflow, while happily showing to the user it would work fine. It's also inconsistent, as some form fields will be ignored if empty, while this specific form field is not ignored. There is no way users would have this intuition upon creating their first workflow.

![Screenshot of the workflow form](https://github.com/paperless-ngx/paperless-ngx/assets/121676/d9665bf6-c58c-4ad8-a47d-7db7822e2653)

### Paperless-ngx version

2.4.3

### Host OS

Debian

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by saadmajeed01** [comment]
Hi everyone, I need help resolving an issue. I'm in the process of building a Docker image for myself using the method 'Build the Docker image yourself' from the main source 'https://docs.paperless-ngx.com/setup/#docker_build.' However, when I run the 'docker-compose build' command, I encounter the following issue:

C:\Users\Saad\paperless-ngx>docker compose build
[+] Building 0.0s (0/0)  docker:default
2024/02/09 16:24:45 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 11.6s (12/29)                                                                               docker:default
 => [webserver internal] load build definition from Dockerfile                                                     0.0s
 => => transferring dockerfile: 2.87kB                                                                             0.0s
 => [webserver] resolve image config for docker.io/docker/dockerfile:1                                             3.7s
 => [webserver auth] docker/dockerfile:pull token for registry-1.docker.io                                         0.0s
 => CACHED [webserver] docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752ba  0.1s
 => => resolve docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf31be0  0.1s
 => [webserver internal] load metadata for docker.io/library/python:3.11-slim-bookworm                             5.7s
 => [webserver internal] load metadata for docker.io/library/node:20-bookworm-slim                                 6.9s
 => [webserver auth] library/python:pull token for registry-1.docker.io                                            0.0s
 => [webserver auth] library/node:pull token for registry-1.docker.io                                              0.0s
 => [webserver internal] load .dockerignore                                                                        0.0s
 => => transferring context: 425B                                                                                  0.0s
 => CANCELED [webserver pipenv-base 1/3] FROM docker.io/library/python:3.11-slim-bookworm@sha256:2a746e2b9dfd9c15  0.2s
 => => resolve docker.io/library/python:3.11-slim-bookworm@sha256:2a746e2b9dfd9c155e1218ee5bcaad64c3c8816258c0ee7  0.1s
 => ERROR [webserver internal] load build context                                                                  0.1s
 => => transferring context: 34B                                                                                   0.0s
 => CANCELED [webserver compile-frontend 1/4] FROM docker.io/library/node:20-bookworm-slim@sha256:b54988ddece70ca  0.2s
 => => resolve docker.io/library/node:20-bookworm-slim@sha256:b54988ddece70caaeb64f8952212bbbb3026ed58e5308f421fb  0.1s
------
 > [webserver internal] load build context:
------
failed to solve: changes out of order: "docker/compose" ""

**Comment by stumpylog** [comment]
To a certain extent, this is user error. It seems clear enough that no sources will match nothing.  We can probably add some validation to prevent empty sources though

**Comment by denilsonsa** [comment]
In my humble opinion, it's not "clear enough".

Following the logic of "no sources will match nothing", we would expect that no filter path will match nothing as well. It's inconsistent among the form fields.

I believe the best option is to make "no sources" simply disable the source-checking, just like empty path also disables the path-checking.

If that is not possible, I agree with you regarding adding some validation to warn the user about invalid trigger conditions.
