### ISSUE TITLE
[BUG] Installation "error: externally-managed-environment"

### ISSUE THREAD

**Issue by gck303** [paperless-ngx/paperless-ngx#5725]
### Description

I am following the baremetal installation instructions on a fresh install of Debian12. 

### Steps to reproduce

Using the installation of: https://github.com/paperless-ngx/paperless-ngx/releases/download/v2.5.0/paperless-ngx-v2.5.0.tar.xz

gck@paperless:/opt/paperless/src$ sudo -Hu paperless pip3 install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

### Webserver logs

```bash
I am happy to provide any logs you want.
```

### Paperless-ngx version

2.5.0

### Host OS

Debian 12

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
If you are planning to deploy 'bare-metal' you should be comfortable with the process. If you Google the error you will see the potential solutions, which have nothing to do with Paperless-ngx and do not constitute a bug in our software.

https://stackoverflow.com/a/75722775

**Comment by gck303** [comment]
Hmmm. Yeah, I had googled it first.  

Before I start changing the parameters and setting as outside of the instructions. I filled the instructions carefully and a step then started reporting errors. 

It seems like me that there might be an error in the installation instructions.
