### ISSUE TITLE
consecutive archive numbering

### ISSUE THREAD

**Issue by ZoXx** [paperless-ngx/paperless-ngx#573]
Hello everyone and first of all thank you for the continuation of paperless! 

Paperless has the archive numbers (when you click on a document). Is it possible to show it on the start page?

It is also possible that paperless automatically assigns a consecutive archive number to each archived document?
We have our invoices in paperless and then we don't always have to number them beforehand.

Thanks!

**Comment by shamoon** [comment]
As noted in the template that you used, Issues are for bugs only please.
