### ISSUE TITLE
[BUG] Save & Close brings up a message/question as to whether the unsaved document should be closed.

### ISSUE THREAD

**Issue by ClamsyHub** [paperless-ngx/paperless-ngx#5834]
### Description

For example, if you have a single document in your inbox and edit any data here, then you have the “Save & Close” button. Here the document should be saved and closed. However, the message pops up: You have unsaved changes to this document "MyDocumentName". Are you sure you want to close this document?

However, this only happens when saving & closing. If you are in batch processing and click on "Save & continue" then this message does not appear (or has not yet occurred).

### Steps to reproduce

1. Process the document (only document - e.g. only document in the inbox, or select the last document in the list --> to get to the "Save & Close" button)
2. Make changes in the document, e.g. tags, names, date
3. Click Save & Close

### Webserver logs

```bash
there is nothing
```

### Paperless-ngx version

2.5.3

### Host OS

Synology NAS 423+ - linux x86_64 Synology NAS

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
There is already a discussion for this and in fact already a potential fix but since I cant reproduce it I would appreciate someone testing it out to confirm

https://github.com/paperless-ngx/paperless-ngx/discussions/5782
