### ISSUE TITLE
Persistent Color Conversion Issue with a Specific PDF in Paperless-ngx v2.5.3

### ISSUE THREAD

**Issue by nascherer** [paperless-ngx/paperless-ngx#5836]
### Description

Hello,

I've encountered a color conversion issue with a specific PDF document using Paperless-ngx v2.5.3 on a Synology DS720+ with DSM 7.2. The issue has persisted before and after updating from v2.1.7 to v2.5.3. I've reviewed relevant discussions, including Issue #4702 , and attempted various recommended solutions without success. Here's a summary of my efforts and a request for further guidance, taking into account the settings and configurations mentioned in settings.py and config.py of Paperless-ngx.

Issue Description:

Encountering a color conversion error when processing a particular PDF document, with an error message suggesting the use of a color conversion strategy for an unusual color space.

### Steps to reproduce

1. Updated to Paperless-ngx v2.5.3: To see if newer versions address the issue.

2. Modified docker-compose.yml: Added PAPERLESS_OCR_COLOR_CONVERSION_STRATEGY: "RGB" to the environment section for the webserver service, setting the color conversion strategy explicitly to RGB, as suggested in the settings.py and config.py.

3. Tried PAPERLESS_OCR_USER_ARGS: Attempted to pass specific OCRmyPDF arguments with:

`
PAPERLESS_OCR_USER_ARGS: '{"color_conversion_strategy": "RGB"}'`
--> failed with the above posted error
Correct consumption worked with:
`PAPERLESS_OCR_USER_ARGS: '{"color_conversion_strategy": "Gray"}'
`
For obvious reasons i don't want to scan all documents gray couloured.

### Webserver logs

```bash
Error Text:
documents.consumer.ConsumerError: SPECIFICPDFFILE.pdf: Error occurred while consuming document SPECIFICPDFFILE.pdf: ColorConversionNeededError: The input PDF has an unusual color space. Use

--color-conversion-strategy to convert to a common color space

such as RGB, or use --output-type pdf to skip PDF/A conversion

and retain the original color space.

###
didn't post more, because the problem is know from other posts (e.g. see above)
```

### Paperless-ngx version

2.5.3

### Host OS

Synology DSM 7.2

### Installation method

Docker - official image

### Browser

firefox 122.0.1

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
As noted  in the issue template we dont handle specific PDF issues that happen during OCR. The above comes from OCRmyPDF and you can raise an issue there if you feel it is in error. The linked issue above is our best effort at a sane fallback for this.
