### ISSUE TITLE
No tool `pg_isready` in the docker image

### ISSUE THREAD

**Issue by jovandeginste** [paperless-ngx/paperless-ngx#590]
When running a Docker container based on the dev branch, the pg_isready check fails because there is no such command

https://github.com/paperless-ngx/paperless-ngx/blob/d18eebf97d7325fcbd4df6fd1a04d476217f4c82/docker/docker-prepare.sh#L13

**Comment by jovandeginste** [comment]
This can be fixed by installing `postgresql-client-common`

**Comment by shamoon** [comment]
Thanks, this is a known issue that will be fixed by #238

**Comment by stumpylog** [comment]
Eh, whoops, that's not actually in the base image yet.  I'll have to add that

**Comment by shamoon** [comment]
> Eh, whoops, that's not actually in the base image yet. I'll have to add that

Oh I thought we chatted about this! Thanks

**Comment by jovandeginste** [comment]
Good thing there are plenty 👀! Go team

**Comment by shamoon** [comment]
Yes, thanks again for raising the issue. Its a reminder always better to have stuff written down here than in a chat somewhere =)
