### ISSUE TITLE
[BUG] install-paperless-ngx.sh fails to detect lack of "docker compose" on target system

### ISSUE THREAD

**Issue by ShanSanear** [paperless-ngx/paperless-ngx#5904]
### Description

I tried installing paperless with recommended installation script (i.e. [this](https://docs.paperless-ngx.com/setup/#docker_script)). After providing all necessary information and proceeding with prompt `Press any key to install.` the last lines of the output were:
```
.env                               100%[==============================================================>]      31  --.-KB/s    in 0s

2024-02-26 12:35:40 (567 KB/s) - ‘.env’ saved [31/31]

docker: 'compose' is not a docker command.
See 'docker --help'
```

At first glance, this shouldn't happen, because it is being checked against at the start of the script:
```
if ! command -v docker compose &> /dev/null ; then
        echo "docker compose executable not found. Is docker compose installed?"
        exit 1
fi
```
But this seems to not work, since with that line both `docker` and `compose` binaries are searched and found instead:
```
$ command -v docker compose
/usr/bin/docker
/usr/bin/compose
```
Worth of noting here is doing `command -v "docker compose"` will not work too:
```
$ command -v "docker compose"
$ echo $?
1
```
So probably something similar to [this](https://stackoverflow.com/a/77727722) would be needed

### Steps to reproduce

1. Have system with docker installed but with no docker compose plugin
2. Run installation script
3. It will fail when starting to proceed with provided settings, with first call to `docker compose`

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.5.4

### Host OS

Debian 11 on Raspberry Pi 4 arm64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Well that's annoying.  If you can make a PR, that would be great, otherwise I may get to a fix this week sometime
