### ISSUE TITLE
[BUG] OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by sjau** [paperless-ngx/paperless-ngx#5943]
### Description

I set as scratch dir to use the folder ``/paperless`.

### Steps to reproduce

However task queue complains about it being read only:

```
Feb 28 18:20:20 paperless celery[1479]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 18:20:20 paperless celery[1479]:   File "/nix/store/ldrd0kjm858wgpwg5cry35p4rhhbfwjc-paperless-ngx-2.5.3/lib/paperless-ngx/src/documents/tasks.py", line 122, in consume_file
Feb 28 18:20:20 paperless celery[1479]:     ) as status_mgr, TemporaryDirectory(dir=settings.SCRATCH_DIR) as tmp_dir:
Feb 28 18:20:20 paperless celery[1479]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 18:20:20 paperless celery[1479]:   File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/tempfile.py", line 871, in __init__
Feb 28 18:20:20 paperless celery[1479]:     self.name = mkdtemp(suffix, prefix, dir)
Feb 28 18:20:20 paperless celery[1479]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 18:20:20 paperless celery[1479]:   File "/nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/python3.11/tempfile.py", line 385, in mkdtemp
Feb 28 18:20:20 paperless celery[1479]:     _os.mkdir(file, 0o700)
Feb 28 18:20:20 paperless celery[1479]: OSError: [Errno 30] Read-only file system: '/paperless/tmpo4fa91oe'
```

The error does not make sense, as the folder exists, it's writable by everyone (tried various permissions and currently it's set to 0777).

```
[root@paperless:/]# ls -al
total 76
drwxr-xr-x  21 root      root        21 Feb 28 13:12 .
drwxr-xr-x  21 root      root        21 Feb 28 13:12 ..
drwxr-xr-x   2 root      root         3 Feb 28 18:20 bin
drwxr-xr-x   5 root      root      4096 Feb 28 11:38 boot
drwxr-xr-x   4 root      root         4 Feb 28 11:40 data
drwxr-xr-x  19 root      root      3380 Feb 28 18:20 dev
drwxr-xr-x  22 root      root        72 Feb 28 18:20 etc
drwxr-xr-x   2 root      root         2 Feb 28 11:26 home
drwxr-xr-x   2 root      root         3 Feb 28 11:49 lib
drwxr-xr-x   2 root      root         3 Feb 28 11:49 lib64
drwxr-xr-x   4 root      root         4 Feb 28 11:32 nix
drwx--x--x   3 root      root         3 Feb 28 12:00 opt
drwxrwxrwx   2 paperless paperless    2 Feb 28 13:12 paperless
dr-xr-xr-x 266 root      root         0 Feb 28 18:19 proc
drwx------   5 root      root        10 Feb 28 18:21 root
drwxr-xr-x  21 root      root       600 Feb 28 18:20 run
drwxr-xr-x   2 root      root         2 Feb 28 11:38 srv
dr-xr-xr-x  13 root      root         0 Feb 28 18:19 sys
drwxrwxrwt  15 root      root        15 Feb 28 18:20 tmp
drwxr-xr-x   3 root      root         3 Feb 28 11:38 usr
drwxr-xr-x   9 root      root        12 Feb 28 11:40 var
```

And it can be written to:

```
[root@paperless:/]# cat /paperless/test.txt; echo "test" > /paperless/test.txt && cat /paperless/test.txt
cat: /paperless/test.txt: No such file or directory
test
```

### Webserver logs

```bash
Not applicable
```

### Paperless-ngx version

2.5.2

### Host OS

NixOS

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by sjau** [comment]
If you see the command issued, there's first a `cat` of the non-existing file, that's why you get first that error. Afterwards `echo` is run to create that file and then again `cat` where it outputs the just created file.

And from the `ls -al` you can see that it's permissions are 0777 - everybody can read, write, execute to that directory.

**Comment by stumpylog** [comment]
Python says that it cannot write there, because it is read only.  We can't do anything about that, it's pretty a pretty cut and dried error message.  I would suspect this some Nix security hardening thing.

**Comment by sjau** [comment]
the problem is it all worked on older paperless-ngx release but now it doesn't work anymore. And as said: Everybody and everything can write to that directory. No idea what kind of nix security hardening thing that would be.

**Comment by stumpylog** [comment]
Seeing as the error comes from the tasks, you are probably encountering something related to #5606 which has a pending fix for Nix packages to include.
