### ISSUE TITLE
[BUG] IMAP Importer crashes if filter for subject contains german special characters like "äöü" and so on

### ISSUE THREAD

**Issue by oe4ewa** [paperless-ngx/paperless-ngx#5953]
### Description

[2024-02-29 12:30:01,760] [ERROR] [paperless_mail] Rule xxx.Dummy: Error while processing rule: UID command error: BAD [b'Could not parse command']
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 514, in handle_mail_account
    total_processed_files += self._handle_mail_rule(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 582, in _handle_mail_rule
    for message in messages:
  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 160, in fetch
    uids = tuple((reversed if reverse else iter)(self.uids(criteria, charset)))[limit_range]
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 119, in uids
    uid_result = self.client.uid('SEARCH', 'CHARSET', charset, encoded_criteria)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imaplib.py", line 890, in uid
    typ, dat = self._simple_command(name, command, *args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b'Could not parse command']

### Steps to reproduce

Add an Email-rule and filter the subject with an item containing a german special character like for instance 'Rückmeldung". Maybe it's necessary to escape such special character, but how?

### Webserver logs

```bash
Not available
```

### Paperless-ngx version

2.5.4

### Host OS

Linux vm-paperless 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The error is being reported from the server, which cannot handle the request.  There's nothing we are able to do able servers not supporting special characters.

**Comment by stumpylog** [comment]
You could ensure the accounts charset is properly set to utf8, not ASCII.  Or try to work with the upstream imap-tools on finding out if it needs to escape special characters.

**Comment by stumpylog** [comment]
See also https://github.com/ikvk/imap_tools/issues/88

As mentioned, I would try the charset, but as then, some servers just aren't going to support searching with accented characters.
