### ISSUE TITLE
[BUG] Install script doesn't support docker-compose v2

### ISSUE THREAD

**Issue by stumpylog** [paperless-ngx/paperless-ngx#598]
**Describe the bug**

The install script assumes the user has docker-compose v1 installed or docker-compose v2 with compose-switch installed.

**To Reproduce**
1. Install `docker-compose` v2 (https://github.com/docker/compose#linux)
2. Ensure compose-switch is NOT installed
3. Run install script
4. Script warns docker-compose is not installed
5. Script attempts to run docker-compose commands

**Expected behavior**
We should support compose v1 and v2 if possible

I don't think `which` (as is currently used) or `command -v` (which we should probably use) will support figuring out if we should use `docker-compose` or `docker compose`.  If there is no `docker-compose` command, the only way to check for v2 *might* be to check if the file `docker-compose` exists in any of the installation locations.

**Comment by shamoon** [comment]
I leave the bash stuff to y'all, but wonder if we can somehow use:
`docker compose version` --> `Docker Compose version v2.2.3`
vs
`docker-compose version` --> `Command 'docker-compose' not found, but can be installed with...`
vs
`docker-compose version` --> `docker-compose version 1.29.2`

**Comment by stumpylog** [comment]
I mostly made this since I wasn't sure if I'd have time and didn't want to forget.  Turns out, I had the time and it wasn't so bad.
