### ISSUE TITLE
[Other] Bump Angular from 11 to 13

### ISSUE THREAD

**Issue by FrankStrieter** [paperless-ngx/paperless-ngx#60]
There are a bunch of improvements and changes from the Angular team. https://github.com/angular/angular/blob/master/CHANGELOG.md

We should keep it up to date. Otherwise, it will be hard in some point of time to update.

**Comment by yschroeder** [comment]
I can take a first look and create a branch for that. I'll report back if there are any show stoppers.

**Comment by shamoon** [comment]
Closed by #65
