### ISSUE TITLE
[BUG] Wrong document title was assigned by the mail rule (from attachment name, not from the subject)

### ISSUE THREAD

**Issue by lipinskyy** [paperless-ngx/paperless-ngx#6017]
### Description

The mail rule has assigned the wrong document title (from the attachment name, not from the subject).
Form Mail/Mail Rules/Edit field "Assign title from" is set to "Use subject as title". This problem started over a month ago - before it was working correctly.

<img width="1153" alt="Zrzut ekranu 2024-03-5 o 23 15 53" src="https://github.com/paperless-ngx/paperless-ngx/assets/162379161/9350ced3-b304-4097-90ab-c6d43ca51bd7">
<img width="466" alt="Zrzut ekranu 2024-03-5 o 23 16 41" src="https://github.com/paperless-ngx/paperless-ngx/assets/162379161/2b1c3aa4-fd4d-430b-9bf2-2d00d554f361">

### Steps to reproduce

1. Go to Mail/Mail Rules/Edit and set the 'Assign title from' field to 'Use subject as title'.
2. Import the document from the mail.
3. Check the title for the imported document, it should be taken from the subject of the mail.

### Webserver logs

```bash
2024-03-05 21:40:00,022] [DEBUG] [paperless_mail] Processing mail account iCloud
[2024-03-05 21:40:00,617] [DEBUG] [paperless_mail] GMAIL Label Support: False
[2024-03-05 21:40:00,618] [DEBUG] [paperless_mail] AUTH=PLAIN Support: True
[2024-03-05 21:40:01,046] [DEBUG] [paperless_mail] Account iCloud: Processing 1 rule(s)
[2024-03-05 21:40:01,049] [DEBUG] [paperless_mail] Rule iCloud.Orange.faktura: Selecting folder Folders/Orange
[2024-03-05 21:40:01,217] [DEBUG] [paperless_mail] Rule iCloud.Orange.faktura: Searching folder with criteria (SINCE 4-Feb-2024 FROM "e-faktura@pl.orange.com" UNSEEN SUBJECT "e-faktura Orange")
[2024-03-05 21:40:02,308] [DEBUG] [paperless_mail] Rule iCloud.Orange.faktura: Processing mail e-faktura Orange 03.2024 from e-faktura@pl.orange.com with 2 attachment(s)
[2024-03-05 21:40:02,315] [INFO] [paperless_mail] Rule iCloud.Orange.faktura: Consuming attachment M2403_Faktura_indywidualna_000-060-4354.pdf from mail e-faktura Orange 03.2024 from e-faktura@pl.orange.com
[2024-03-05 21:40:02,318] [DEBUG] [paperless_mail] Rule iCloud.Orange.faktura: Skipping attachment Wykaz polaczen 01.02.2024.xlsx does not match pattern *Faktura*.pdf
[2024-03-05 21:40:02,337] [DEBUG] [paperless_mail] Rule iCloud.Orange.faktura: Processed 1 matching mail(s)
```

### Paperless-ngx version

2.6.1

### Host OS

docker/ubuntu

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
I don't see how this could be wrong:
https://github.com/paperless-ngx/paperless-ngx/blob/0a634883a70f0631bb26c725ce8fb1f54acf9a4d/src/paperless_mail/mail.py#L441-L448

It is also unchanged for 2+ years

Possibilities:
- The change to title assignment wasn't actually saved
- A workflow is also changing the title

**Comment by stumpylog** [comment]
@shamoon 
Just guessing without a full log, but this looks suspicious:
https://github.com/paperless-ngx/paperless-ngx/blob/0a634883a70f0631bb26c725ce8fb1f54acf9a4d/src/documents/consumer.py#L843-L849

The mail code will set the override title to the correct value (there's no place holders there), but this doesn't know/check/care. I think the title is doing too much duty perhaps.  Or update should only override the title, if the title hasn't already been set.

**Comment by lipinskyy** [comment]
I replicated this case again by disabling all Workflows. And in that case the document title was set correctly. Workflow overwrites the title given by the mail rule (when the conditions in Workflow are too general).

**Comment by shamoon** [comment]
I think this is currently doing what is expected, as noted regarding the subsequent workflow actions. The problem is a subsequent workflow which overwrites the title.

From the [docs](https://docs.paperless-ngx.com/usage/#workflows):

> For "assignment" actions, subsequent workflow actions will override previous assignments, except for assignments that accept multiple items e.g. tags, custom fields and permissions, which will be merged.

Of course, someone correct me if Im wrong.

**Comment by stumpylog** [comment]
Well, in the rule editor it does day:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/797416/e9a5fce0-adc4-4de8-b59c-07512f70d9b8)

**Comment by shamoon** [comment]
> Well, in the rule editor it does say

Oh, interesting. I think that should be removed (as opposed to changing this). What do you think?

**Comment by stumpylog** [comment]
I guess that is in line with the documented affects of workflows.  Workflows are powerful and it's easy to end up with something like this.

**Comment by shamoon** [comment]
Yea agree. As you can guess that’s a remnant from the change from consumption templates to workflows. Great catch thanks, I’ll take care of it
