### ISSUE TITLE
[BUG] Storage Path not updated

### ISSUE THREAD

**Issue by Nymax77** [paperless-ngx/paperless-ngx#6031]
### Description

Problem a) Currently the file location (/media/documents/archive) in the storage is not updated when a storage path is deleted in paperless-ngx Web-Gui.

Problem b) Also all the storage paths in the filesystem (/media/documents/archive) are not updated, after PAPERLESS_FILENAME_FORMAT was changed in the docker compose file. Even after a restart with "docker compose up -d --build". It works with docker-compose exec webserver document_renamer. But I believe it should be automatically checked after a storage path is deleted in the web gui.

Problem c) If a different storage path system is chosen, old unused folders in the file system are not deleted. This applies for PAPERLESS_FILENAME_FORMAT and for storage paths from the Web-GUI

### Steps to reproduce

Problem a)
1. Choose a general rule for the storage (https://docs.paperless-ngx.com/advanced_usage/#file-name-handling). This should be PAPERLESS_FILENAME_FORMAT=other-Documents/{correspondent}/{created_year}-{created_month}-{created_day}, Title_{title}, Tags_{tag_list}
2. Create a file in the Web Gui.
3. Create a storage path in the Web Gui. Name: test_storage_path, Rule: test/{correspondent}/{created_year}-{created_month}-{created_day}, Title_{title}, Tags_{tag_list}
4. Connect the file to the storage path.
5. Check if the file is stored in /media/documents/archive/test_storage_path/...
6. delete the file storage in the web-Gui (http://localhost:8000/storagepaths)
7. Check if the file is stored in /media/documents/archive/other-Documents/...
8. This doesnt work for me. The document is still at the path from 5. and not from 8.

Problem b)
1. Choose a general rule for the storage (https://docs.paperless-ngx.com/advanced_usage/#file-name-handling). This should be PAPERLESS_FILENAME_FORMAT=other-Documents/{correspondent}/{created_year}-{created_month}-{created_day}, Title_{title}, Tags_{tag_list}
2. add a file
3. Check if the file is stored in /media/documents/archive/other-Documents/...
4. change PAPERLESS_FILENAME_FORMAT to the new value =other-Documents/{original_name}
5. execute: docker compose down && docker compose up -d --build
6. this was not sufficient for me, location wasn't updated.
7. execute: docker-compose exec webserver document_renamer
8. Check if the file is stored in /media/documents/archive/other-Documents/{original_name}
9. this worked for me

Problem c)
1. Steps 1. - 8. from Problem b)
2. old folder {correspondent} still exists but should be deleted

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.6.1

### Host OS

macOS Intel, Docker Desktop

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

USERMAP_UID=501 USERMAP_GID=20 PAPERLESS_TIME_ZONE=Europe/Berlin PAPERLESS_OCR_LANGUAGE=deu PAPERLESS_OCR_LANGUAGES=eng PAPERLESS_OCR_OUTPUT_TYPE=pdfa PAPERLESS_SECRET_KEY=… PAPERLESS_CONSUMER_POLLING=10 PAPERLESS_OCR_MODE=redo PAPERLESS_OCR_CLEAN=clean-final PAPERLESS_OCR_PAGES=1 PAPERLESS_CONSUMER_DELETE_DUPLICATES=true PAPERLESS_CONSUMER_RECURSIVE=true PAPERLESS_FILENAME_DATE_ORDER=YMD PAPERLESS_FILENAME_FORMAT=andere-Dokumente/{correspondent}/{created_year}-{created_month}-{created_day}, Title_{title}, Tags_{tag_list}    webserver:     volumes:       - data:/usr/src/paperless/data       - ./media:/usr/src/paperless/media       - ./export:/usr/src/paperless/export       - ./consume:/usr/src/paperless/consume

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
a. I think sounds like a feature request when a SP is deleted, but I agree it makes sense.
b. is known and specifically mentioned at https://docs.paperless-ngx.com/advanced_usage/#file-name-handling
c. also a FR

**Comment by stumpylog** [comment]
I agree, you can always run the renamer to ensure files are moved where expected and empty folders are removed.

**Comment by shamoon** [comment]
Feel free to create FR(s) as above.
