### ISSUE TITLE
[BUG] Title placeholder {created_month_name} not in local language (german)

### ISSUE THREAD

**Issue by S-E-B-123** [paperless-ngx/paperless-ngx#6051]
### Description

I use the {created_month_name} title placeholder within my workflows, but the name is still english and not in my local language.
See the attached screenshot, the name of month should be the german **Februar**.
 
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/70915123/fb917317-a3da-4cd5-807f-33ddcf9e10e8)

### Steps to reproduce

Use title placeholder **{created_month_name}**  within a workflow action.

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.6.2

### Host OS

Debian x86_64

### Installation method

Docker - official image

### Other

Set all language related settings in paperless to german

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
There is an existing feature request for locale based naming
