### ISSUE TITLE
[BUG] Paperless + Tika + Gotenberg does not support "LibreOffice Draw" /  "odg" documents

### ISSUE THREAD

**Issue by aki-ks** [paperless-ngx/paperless-ngx#6114]
### Description

Paperless deployed with Tika and Gotenberg reports that ".odg" Documents (mime `application/vnd.oasis.opendocument.graphics`) as e.g. generated by LibreOffice Draw are not supported even tough Gotenberg does support them.

I'm expecting that I can upload such documents since, Gotenberg is able to render those into PDF using LibreOffice.

### Steps to reproduce

- Create a file using LibreOffice Draw or open an existing PDF file for edit using LibreOffice Draw and save it to produce some ".odg" file
- Draw the file into the web-ui of a paperless-ngx instance, deployed together with Tika and Gotenberg
- Paperless will show a hint that the filetype (`application/vnd.oasis.opendocument.graphics`) is not supported

### Webserver logs

```bash
[2024-03-16 16:55:39,805] [WARNING] [django.request] Bad Request: /api/documents/post_document/
```

### Paperless-ngx version

2.6.2

### Host OS

Debian 12 (x86_64)

### Installation method

Docker - official image

### Browser

Firefox 123.0

### Configuration changes

Gotenberg and Tika integration are enabled and properly working (e.g. processing docx documents)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
https://docs.paperless-ngx.com/faq/#what-file-types-does-paperless-ngx-support
