### ISSUE TITLE
[BUG] 2.6.3 stil shows as 2.6.2 (but no upgrade available info).

### ISSUE THREAD

**Issue by gramels** [paperless-ngx/paperless-ngx#6128]
### Description

2.6.3 stil shows as 2.6.2 (but no upgrade available info).

### Steps to reproduce

upgrade to 2.6.3
observe version info lower left
<img width="264" alt="Screenshot 2024-03-18 at 14 40 34" src="https://github.com/paperless-ngx/paperless-ngx/assets/2668342/54e7173f-4fdd-4b84-ad6e-9d44f3b69f8a">

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.6.3

### Host OS

debian

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Empty your browser cache etc

**Comment by gramels** [comment]
ok, close it...
