### ISSUE TITLE
[BUG] PDF cannot be printed under firefox with integrated pdfjs

### ISSUE THREAD

**Issue by telkamp** [paperless-ngx/paperless-ngx#6130]
### Description

I'm using Paperlss-ngx 2.6.2 with Firefox 123.0.1 under Windows 10 (64-Bit).

When I open a PDF with double-click, the PDF is opened with PDF.js:
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/13854808/d33c32da-e8c4-4bfe-9cfd-6378259b2dee)

The following message is printed in the Firefox console:
```
PDF cfe849ba278895aede0eab384631eb92 [1.7 pikepdf 8.13.0 / ocrmypdf 15.4.4 / Tesseract OCR-PDF 5.3.0] (PDF.js: 4.1.30 [a22b5a4f0])
```
When I now try to print the PDF using the PDF.js toolbar, nothing happens. Instead the following message appears in the Firefox console:
```
Uncaught NS_ERROR_FAILURE: 
    triggerPrinting resource://pdf.js/web/viewer.mjs:10807
    webViewerPrint resource://pdf.js/web/viewer.mjs:11146
    dispatch resource://pdf.js/web/viewer.mjs:916
    bindListeners resource://pdf.js/web/viewer.mjs:9440
    #bindListeners resource://pdf.js/web/viewer.mjs:9438
    Toolbar resource://pdf.js/web/viewer.mjs:9377
    _initializeViewerComponents resource://pdf.js/web/viewer.mjs:9939
    initialize resource://pdf.js/web/viewer.mjs:9755
    run resource://pdf.js/web/viewer.mjs:9997
    webViewerLoad resource://pdf.js/web/viewer.mjs:12459
    <anonymous> resource://pdf.js/web/viewer.mjs:12463
```
Using Microsoft Edge I can print the PDF.
Furthermore, I can print a PDF from Firefox with the example https://mozilla.github.io/pdf.js/web/viewer.html
(in this example PDF.js version 4.1.296 is used)

### Steps to reproduce

1. Double Click on the PDF to open the PDF.js editor
2. Print the PDF using the Printer Button

### Webserver logs

```bash
Not relevant
```

### Browser logs

```bash
Uncaught NS_ERROR_FAILURE: 
    triggerPrinting resource://pdf.js/web/viewer.mjs:10807
    webViewerPrint resource://pdf.js/web/viewer.mjs:11146
    dispatch resource://pdf.js/web/viewer.mjs:916
    bindListeners resource://pdf.js/web/viewer.mjs:9440
    #bindListeners resource://pdf.js/web/viewer.mjs:9438
    Toolbar resource://pdf.js/web/viewer.mjs:9377
    _initializeViewerComponents resource://pdf.js/web/viewer.mjs:9939
    initialize resource://pdf.js/web/viewer.mjs:9755
    run resource://pdf.js/web/viewer.mjs:9997
    webViewerLoad resource://pdf.js/web/viewer.mjs:12459
    <anonymous> resource://pdf.js/web/viewer.mjs:12463
```

### Paperless-ngx version

2.6.2

### Host OS

Flatcar

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I dont think this has anything to do with paperless, youre opening the pdf in your browser
