### ISSUE TITLE
[BUG] Less Paper iOS app causes high memory usage

### ISSUE THREAD

**Issue by neok0** [paperless-ngx/paperless-ngx#6133]
### Description

from time to time I experienced a high memory usage >8gb in idle state, very similar to this issue https://github.com/paperless-ngx/paperless-ngx/issues/3616, also causing the same gunicorn process `gunicorn: worker [paperless.asgi:application` consuming large amount of memory. 

While I could not make the connection at first, I figured anytime I opened any document via the Less Paper iOS app (https://apps.apple.com/de/app/less-paper/id6464425056) the gunicorn process soon after spikes in memory usage. I can see the memory increased with any document I opened on the phone.

Not sure what causes this behavior but since there are discussions about a memory leak I wanted to share this, maybe this helps you to reproduce the issue. Let me know if there is anything I can test or share in addition. 

### Steps to reproduce

1. open any document on paper less app
2. watch the memory usage increasing

### Webserver logs

```bash
Unfortunately, there is absolut nothing relevant on the logs on this issue :(
```

### Paperless-ngx version

2.6.2

### Host OS

Debian 12 / x86_64 / Proxmox LXC

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This does not sound like an issue with paperless, but with the iOS application and should be reported to its developer.

**Comment by neok0** [comment]
hmm, not sure I necessarily agree with that statement. If an app what simply uses the Paperless API can trigger a memory leak is an simple app issue...but ok. Maybe I will have another look if I can figure out some more details what call causes this issue, seems like I would need some more debug logs though..
