### ISSUE TITLE
[BUG] 404 on "Open document" right after import

### ISSUE THREAD

**Issue by amo13** [paperless-ngx/paperless-ngx#6144]
### Description

Here a screencast:
[Screencast from 2024-03-20 09-08-52.webm](https://github.com/paperless-ngx/paperless-ngx/assets/6617661/6a0f8b3f-9c7b-43ac-9b1f-68b5a1ca331a)

Network tab in browser dev tools
![Screenshot from 2024-03-20 09-38-27](https://github.com/paperless-ngx/paperless-ngx/assets/6617661/a8062dac-d122-4613-94a7-6d59478d4046)

and the sample document:
[7mb.pdf](https://github.com/paperless-ngx/paperless-ngx/files/14663554/7mb.pdf)

### Steps to reproduce

Import attached sample PDF by drag-and-drop, wait for paperless to digest it and then click on "Open document" in the alert box on the dashboard.
Briefly, the edit page is displayed with a loading spinner where the PDF itself would be shown.
Then, I get redirected to /404.
Clicking "Go to dashboard" does bring me back to the dashboard and on the left under "open documents" I can click on the newly imported document and everything works. I do have to wait a bit for the PDF to display though, since it is big.

### Webserver logs

```bash
[info][2024-03-20 08:21:55,598] [INFO] [paperless.consumer] Consuming 7mb.pdf
[info][2024-03-20 08:22:08,399] [WARNING] [ocrmypdf._pipeline] This PDF is marked as a Tagged PDF. This often indicates that the PDF was generated from an office document and does not need OCR. PDF pages processed by OCRmyPDF may not be tagged correctly.
[info][2024-03-20 08:22:08,672] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:08,685] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:08,685] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
...
[info][2024-03-20 08:22:09,474] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,474] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,475] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,475] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,476] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:09,476] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[info][2024-03-20 08:22:10,246] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[info][2024-03-20 08:22:23,114] [INFO] [ocrmypdf.optimize] Image optimization did not improve the file - optimizations will not be used
[info][2024-03-20 08:22:26,533] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 0.95 savings: -5.1%
[info][2024-03-20 08:22:26,534] [INFO] [ocrmypdf._pipeline] Total file size ratio: 1.36 savings: 26.5%
[info][2024-03-20 08:22:26,715] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
[info][2024-03-20 08:23:20,661] [INFO] [paperless.consumer] Document 2024-03-20 7mb consumption finished
[info][2024-03-20 08:23:21,044] [INFO] [celery.app.trace] Task documents.tasks.consume_file[31376673-49c2-431b-acec-d270c892337d] succeeded in 85.8514666430001s: 'Success. New document id 6 created'
```

### Browser logs

```bash
nothing in the console
```

### Paperless-ngx version

2.6.2

### Host OS

Archlinux

### Installation method

Docker - official image

### Browser

Firefox

### Other

"Use PDF viewer provided by the browser" not checked.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by amo13** [comment]
Also happens when clicking on the pen icon in the document overview.

**Comment by shamoon** [comment]
I think a 1700 page 7.7mb (fake) document is going to be taxing on most systems, but just as you noted above, it does work. Im not really sure what exactly is meant to be actionable here, maybe be more patient next time?

<img width="1892" alt="Screenshot 2024-03-20 at 7 15 01 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/3c25c73d-d32b-46f6-9fd5-7e93938caf91">

**Comment by shamoon** [comment]
Oh I see what youre saying about the 404, I'll look into it when I can

**Comment by amo13** [comment]
Yes, it's the 404 that is odd. Thanks for looking into it and let me know if I can help with something.

**Comment by shamoon** [comment]
It's because of the absurdly long text content which doesn't fit in the browser storage. I'll fix it later.
