### ISSUE TITLE
[BUG] searching for false boolean values not possible

### ISSUE THREAD

**Issue by TimetravelerDD** [paperless-ngx/paperless-ngx#6145]
### Description

I noticed some inconsistencies when searching for custom boolean fields, particularly when the values are false

For this I have created 3 example documents

![image](https://github.com/paperless-ngx/paperless-ngx/assets/14355674/4ebff992-2913-4591-9792-903c728e6156)
let's call them $1, $2 and $3

## here is an overview of what works correctly and what not:
✅ when searching `archived` finds $1,$2,$3 - it searches all fields correctly (including tags)
✅ when searching `archived:` finds $2,$3 - it only finds docs that have the field assigned (doesn't match tags with the same name) 
✅ when searching `archived:true` finds $2 - it finds the one document which has the field checked
❌ when searching `archived:false` no search results - **it doesn't finds the one document which has the field unchecked**
✅ when searching `NOT archived` it finds none of the three docs
✅ when searching `NOT archived:` finds $1 - it finds the doc without the field
✅ when searching `NOT archived:true` finds $1,$2 - the doc without the field and the doc with the field unchecked
❌ when searching `NOT archived:false` it finds all docs. However it should not display $3 (with the field unchecked)
 

# summary
":" correctly works to indicate searching for a custom field. Searching for "true" also works correctly, but searching for "false" yields no result even if it should

### Steps to reproduce

1. create a boolean custom field "customfield" 
2. add customfield to a document and leave it unchecked
3. search for customfield:false
4. no search results displayed (wrongly)

### Webserver logs

```bash
no relevant logs observed
```

### Paperless-ngx version

2.6.3

### Host OS

unraid (x86_64)

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
There's an existing feature request for better custom field searching. It's not easy given our existing technology though.

This is probably just because the index needs time to update.  Changes won't reflect instantly.

**Comment by shamoon** [comment]
Closing as noted above. #4647
