### ISSUE TITLE
[BUG] No ability to scroll in the list of uploaded files

### ISSUE THREAD

**Issue by solarssk** [paperless-ngx/paperless-ngx#6182]
### Description

when I add a large number of files to be uploaded - I have no way to scroll in the status of uploading these files. 
I also have no way to minimize it (the dismiss completed button is invisible).

![Screenshot 2024-03-18 at 16 13 54](https://github.com/paperless-ngx/paperless-ngx/assets/83293863/5e3988b1-64bf-4d60-abee-3be4dfd1fbce)

In addition, in a situation where we have a large number of files in the queue - the information about the file queue covers the information about the number of documents in the system and the place to upload files - it looks unaesthetic.

### Steps to reproduce

1. add more than 20 files to the system upload queue

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.6.1

### Host OS

x86_64

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not entirely accurate, I assume youre talking about uploading > 5 documents and then clicking "show all", in which case covering the other elements is fine and that won't change, but being able to scroll that seems like a reasonable change.

**Comment by solarssk** [comment]
Hey,
Iit is possible to know why it will not change? in the case of an expanded list, there will be an option to collapse it? 
how the scrolling behavior will affect the length of the page? the whole page will move?

**Comment by shamoon** [comment]
There’s a video https://github.com/paperless-ngx/paperless-ngx/pull/6184 , as I said being able to scroll seems like the usability “fix” part of this
