### ISSUE TITLE
[BUG] start download of multiple documents has no visual feedback

### ISSUE THREAD

**Issue by crazychatting** [paperless-ngx/paperless-ngx#621]
**Prolog:**
I am not sure if this is really a bug or a feature request.

**Describe the bug**
A user searches for documents and needs a small subset of them (>400) to be downloaded as a zip-file. The user marks all of the needed dosuments and clicks on "download". Visually nothing happens and the user thinks the process hasn´t started yet and clicks again "download". [repeat the previous sentence 10 times].
Result:
the system gets more and more load and in the end the user gets a couple times the same zip-file offered to download.

**To Reproduce**
1. Go to documents
2. filter the documents for a desired subset
3. Click on 'mark all'
4. Click on 'download'
5. See nothing

**Expected behavior**
Give some visual signal in any way that the action has been triggered and is ongoing - for example fill the download-button with a loading icon or if possible addding a loading bar showing the progress (maybe some type of #415 ?)

**Screenshots**
*screenshot of "nothing happens"*

**Relevant information**
 - Host OS of the machine running paperless: Synology NAS running docker-compose
 - Browser *
 - Version 1.6.0
 - Installation method: docker-compose

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/2f8d263c9cb1fc97e26767e0d3735ce9d4a8a79d
