### ISSUE TITLE
[BUG] qpdf_11.6.4-1_arm.deb not a Debian format archive

### ISSUE THREAD

**Issue by simon-eller** [paperless-ngx/paperless-ngx#6229]
### Description

I tried to setup Paperless NGX via the method "Build the Docker image yourself" on my Raspberry Pi 4 32-bit Bookworm System.
The building process firstly fails because of deprecated urls -> therefore I created a [pull request with a fix](https://github.com/paperless-ngx/paperless-ngx/pull/6228#issuecomment-2028447917).

Then I tried it again and now the building process fails while fetching qpdf with the info that the file is not a Debian format archive.

### Steps to reproduce

1. Follow the steps on [Build the Docker image yourself](https://docs.paperless-ngx.com/setup/#docker_hub) until step 6.
2. Enter the command `docker compose build`

### Webserver logs

```bash
205.2 Installing pre-built updates
205.2 Installing qpdf 11.6.4
205.8 + curl --fail --silent --show-error --location --output qpdf_11.6.4-1_arm.deb https://github.com/paperless-ngx/builder/releases/tag/qpdf-11.6.4/qpdf_11.6.4-1_arm.deb
206.5 + dpkg --install ./libqpdf29_11.6.4-1_arm.deb
206.5 dpkg-deb: error: './libqpdf29_11.6.4-1_arm.deb' is not a Debian format archive
206.5 dpkg: error processing archive ./libqpdf29_11.6.4-1_arm.deb (--install):
206.5  dpkg-deb --control subprocess returned error exit status 2
206.6 Errors were encountered while processing:
206.6  ./libqpdf29_11.6.4-1_arm.deb
```

### Paperless-ngx version

2.6.3

### Host OS

Raspberry Pi 4 aarch64

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
As per the PR.
