### ISSUE TITLE
[BUG] Clear selection does not remove all selection tick

### ISSUE THREAD

**Issue by pustekuchen91** [paperless-ngx/paperless-ngx#6238]
### Description

In different table views (Correspodents, Tags, Document Types) the "all selection tick" is not removed if you use the clear selection button.

### Steps to reproduce

1. Go to /correspondents
2. click the checkbox in the table header to select all entries
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/7147324/d9863203-0e7e-4883-a557-3811a690f2c3)
3. use the "Clear Selection Button"
4. The tick in the table header remains
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/7147324/c54a206a-18cb-47f9-82f4-46e5618ba39e)

### Webserver logs

```bash
not relevant
```

### Browser logs

```bash
not relevant
```

### Paperless-ngx version

2.6.3

### Host OS

any

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by pustekuchen91** [comment]
just for completion: in `tasks` this is still an issue

**Comment by shamoon** [comment]
I'll fix that.
