### ISSUE TITLE
[Other] [WARNING] [ocrmypdf._validation] The output file size is 2.18× larger than the input file.

### ISSUE THREAD

**Issue by t3kg33k** [paperless-ngx/paperless-ngx#626]
I wasn't sure if this was a bug or not so I chose this option.
I attempted to add a car manual .pdf file that's 48M in size with about 600+ pages. When I added it to the 'consume' directory it attempted to process it but eventually gave a warning and it appears to have quit processing. Here is the message I see in the webserver Docker log:

```
[2022-04-02 08:39:54,566] [WARNING] [ocrmypdf._validation] The output file size is 2.18× larger than the input file.
Possible reasons for this include:
The argument --deskew was issued, causing transcoding.
PDF/A conversion was enabled. (Try `--output-type pdf`.)
```
In my Docker compose I made sure to add the following:

```
PAPERLESS_WORKER_TIMEOUT: 3600
PAPERLESS_CONSUMER_POLLING: 1800
```
My system hardware is as follows:

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               69
Model name:          Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
Stepping:            1
CPU MHz:             2600.000
CPU max MHz:         2600.0000
CPU min MHz:         800.0000
BogoMIPS:            3791.19
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
```
I have 8GB of memory. 
With these resources, I would think there would be no issue with processing an 48M .pdf file.

**Comment by stumpylog** [comment]
This looks like an issue from OCRmyPDF:
- ocrmypdf/OCRmyPDF/issues/601
- ocrmypdf/OCRmyPDF/issues/396
- ocrmypdf/OCRmyPDF/issues/614

From our end, you could temporarily set the following values.  This will change the output type to PDF and won't attempt to deskew pages.  Given this is probably not a scanned document (?), deskew is likely not needed :

- PAPERLESS_OCR_DESKEW=false

**Comment by t3kg33k** [comment]
I'll try that out. Thanks.
