### ISSUE TITLE
 [BUG] document_exporter seems to have trouble with special chars like ä,ö and ü

### ISSUE THREAD

**Issue by heliomedia-de** [paperless-ngx/paperless-ngx#6261]
Re-opening issue: https://github.com/paperless-ngx/paperless-ngx/issues/5449

The issue reported by "auer1329" still exists in the current version 2.6.3

Exporting a single file is not affected by this issue, but when exporting several files filenames with umlauts (in the ZIP archive) are messed up.

I mapped the folders "data", "media", "export" and "consume" to local windows folders for easy access in my case.

**Comment by stumpylog** [comment]
You have very helpfully linked to at least one of the duplicates.  As before, this has not been something reproducible and comes down to the individual setup and system.  There isn't anything else paperless is going to be doing here.  We use UTF-8 correctly and cannot assist if your filesystem does not handle UTF-8 correctly.
