### ISSUE TITLE
[BUG] Build of the ngx-1.6.0 tag fails for docker

### ISSUE THREAD

**Issue by gador** [paperless-ngx/paperless-ngx#627]
**Describe the bug**

Build of the `ngx-1.6.0` tag fails.

**To Reproduce**
1. `docker build` with local Dockerfile

**Expected behavior**
The docker image should build.

**Screenshots**
```
Sending build context to Docker daemon   48.1MB
Step 1/33 : FROM node:16 AS compile-frontend
 ---> 054bccad10b0
Step 2/33 : COPY . /src
 ---> 6e5419222895
Step 3/33 : WORKDIR /src/src-ui
 ---> Running in 5a2b17aa78e7
Removing intermediate container 5a2b17aa78e7
 ---> 1f1f8980a3d6
Step 4/33 : RUN npm update npm -g && npm install
 ---> Running in cdc491812cff

removed 20 packages, changed 63 packages, and audited 202 packages in 3s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.5.0 -> 8.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
npm notice Run `npm install -g npm@8.6.0` to update!
npm notice
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @ngneat/dirty-check-forms@1.1.0
npm ERR! Found: tslib@2.3.1
npm ERR! node_modules/tslib
npm ERR!   tslib@"^2.3.1" from the root project
npm ERR!   tslib@"2.3.1" from @angular-devkit/build-angular@13.2.5
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~13.2.5" from the root project
npm ERR!   18 more (@angular/animations, @angular/common, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"^1.10.0" from @ngneat/dirty-check-forms@1.1.0
npm ERR! node_modules/@ngneat/dirty-check-forms
npm ERR!   @ngneat/dirty-check-forms@"^1.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: tslib@1.14.1
npm ERR! node_modules/tslib
npm ERR!   peer tslib@"^1.10.0" from @ngneat/dirty-check-forms@1.1.0
npm ERR!   node_modules/@ngneat/dirty-check-forms
npm ERR!     @ngneat/dirty-check-forms@"^1.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-02T17_41_24_634Z-debug-0.log
The command '/bin/sh -c npm update npm -g && npm install' returned a non-zero code: 1
```

@paperless-ngx/ci-cd 
@paperless-ngx/frontend 

**Relevant information**
 - Host OS of the machine running paperless: NixOS
 - Browser: Brave
 - Version: NGX-1.6.0
 - Installation method: Dockerr
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

Applying the commit https://github.com/paperless-ngx/paperless-ngx/commit/1d3300fb34e01600850c1b1c2b31012570ee80de to `ngx-1.6.0` does not solve the issue

**Comment by shamoon** [comment]
Does it work if you change the npm call https://github.com/paperless-ngx/paperless-ngx/blob/ed2524cbbb59207b514c71f4434d501ad31bee09/Dockerfile#L6 to `npm ci` instead of `install`?

See https://github.com/paperless-ngx/paperless-ngx/blob/65ffaaa67cb0c1ba3dd6cf73579db2d0775641db/Dockerfile#L6

**Comment by yschroeder** [comment]
Slightly off topic: how do ci and install differ? I was able to fix many npm issues using ci before where install messed up.

**Comment by shamoon** [comment]
> Slightly off topic: how do ci and install differ? I was able to fix many npm issues using ci before where install messed up.

`ci` does a clean install and installs exactly and only whats in the package-lock.json file, whereas `install` tries to resolve things itself. We should definitely have been using `ci` (and we do in `dev` thus going forward).

https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci

I think this issue boils down to the dependencies got a little twisted and we didnt notice, since our automations use `ci` the container built fine etc. but the Dockerfile in 1.6.0 has `install`.

I think? And again, hopefully we've corrected this going forward.

**Comment by yschroeder** [comment]
Ok, so is there any use case for install at all or should one use ci by default? Because I'm trained to type in npm install whenever I clone a git repo with some node.js project 😅

**Comment by shamoon** [comment]
Good question, Im not 100% sure about the nuances of this but most of the time install is fine and in fact in the current dev branch it is too (after that recent merge to clean things up). Theoretically ci could install things that aren't strictly necessary to resolve all packages but were for whatever reason still included in the lock file. Also some repos dont include a lock file, in which case `ci` doesnt work =)

Generally if a package-lock.json file is included, `ci` makes more sense, hence the 'lock' part.

Again, I think, def not an expert.

**Comment by yschroeder** [comment]
Maybe we can summon @FrankStrieter here. He seems to be an expert on angular and I believe you need to know your way around npm in that case 😏

**Comment by gador** [comment]
@shamoon 
>Does it work if you change the npm call

No, it doesn't. This is the output:
```
docker build .
Sending build context to Docker daemon   48.1MB
Step 1/33 : FROM node:16 AS compile-frontend
 ---> 054bccad10b0
Step 2/33 : COPY . /src
 ---> 780c95192cd5
Step 3/33 : WORKDIR /src/src-ui
 ---> Running in e795fd6854c1
Removing intermediate container e795fd6854c1
 ---> 09f72067548a
Step 4/33 : RUN npm update npm -g && npm ci --no-optional
 ---> Running in e9192639b08b

removed 20 packages, changed 63 packages, and audited 202 packages in 7s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.5.0 -> 8.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
npm notice Run `npm install -g npm@8.6.0` to update!
npm notice
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @ngneat/dirty-check-forms@1.1.0
npm ERR! Found: tslib@2.3.1
npm ERR! node_modules/tslib
npm ERR!   tslib@"^2.3.1" from the root project
npm ERR!   tslib@"2.3.1" from @angular-devkit/build-angular@13.2.5
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~13.2.5" from the root project
npm ERR!   18 more (@angular/animations, @angular/common, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"^1.10.0" from @ngneat/dirty-check-forms@1.1.0
npm ERR! node_modules/@ngneat/dirty-check-forms
npm ERR!   @ngneat/dirty-check-forms@"^1.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: tslib@1.14.1
npm ERR! node_modules/tslib
npm ERR!   peer tslib@"^1.10.0" from @ngneat/dirty-check-forms@1.1.0
npm ERR!   node_modules/@ngneat/dirty-check-forms
npm ERR!     @ngneat/dirty-check-forms@"^1.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-03T10_06_20_197Z-debug-0.log
The command '/bin/sh -c npm update npm -g && npm ci --no-optional' returned a non-zero code: 1
```

This is after checking out `ngx-1.6.0` and changing the Dockerfile accordingly.

**Comment by shamoon** [comment]
Yea. So it will work if you change it to `npm install --legacy-peer-deps`

But again, the tag 1.6.0 cant be fixed, I think we just have to chalk this up to a mistake we learn from.

**Comment by gador** [comment]
So, the already built images will continue to work, but re-building them, won't work, correct?
Maybe we should "release" a `1.6.1`, so that it at least rebuilds?

**Comment by shamoon** [comment]
Yes, this problem will not be present in the next release. But I mean we cant change the 1.6.0 git tag i.e. the release, it will always be like that.

**Comment by gador** [comment]
yeah, I know. What I ment to say was: Shouldn't we release a version (or git tag) 1.6.1, which just your change to the Dockerfile? So version 1.6 builds at least?

**Comment by shamoon** [comment]
Oh sorry if I was the only one who didn’t get what you meant!

I don’t know, not sure what the convention is from a software standpoint? I of course see the reasoning and it feels “correct” to do so but also sorta feels silly because it will potentially make a lot of people upgrade for a bug that doesn’t affect them at all. For example, you’re the first person to reach out about it. Alternatively we could update the release notes with a “known issue”? Also I think we’re getting close to the next actual release.

What do others think?

**Comment by yschroeder** [comment]
I would add a known issue with the workaround to the release notes. It's a single line in a config file to change, not a breaking bug in the depths of our code.

**Comment by shamoon** [comment]
Closed by https://github.com/paperless-ngx/paperless-ngx/commit/5432700b0d70435f6364478a47c981d4d9348e40
