### ISSUE TITLE
[BUG] Split feature is disabled when using browser pdf viewer

### ISSUE THREAD

**Issue by nhulsch** [paperless-ngx/paperless-ngx#6300]
### Description

If PDF viewer of browser is enabled the split feature is disabled, I think it cannot calculate the number of pages

### Steps to reproduce

1. Goto Settings and enable browsers PDF viewer feature
2. Open document
3. Try to split it

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.7.0

### Host OS

Synology DSM 6.2.4 x86_64

### Installation method

Docker - official image

### Browser

Chrome, Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by cgraefe** [comment]
I just updated to release version 2.7.1, but with the browser PDF view enabled in Firefox, the "Split" action is still disabled. Or did I miss something?

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/2463102/a05c789c-d8c6-48ef-a2e0-e9c49659a7d8)

**Comment by github-Jan** [comment]
Same here in Vivaldi (Chrome based) with internal viewer:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/161719066/71948187-a29c-4589-8872-5d1e89adefc8)

**Comment by shamoon** [comment]
Yea, my bad, a silly error, already fixed.
