### ISSUE TITLE
[BUG] After Splittting a document into 4 documents nothing happens and an error occurs in logfiles.

### ISSUE THREAD

**Issue by NetRat88** [paperless-ngx/paperless-ngx#6310]
### Description

After Splittting a document into 4 documents nothing happens and an error occurs in logfiles.

### Steps to reproduce

1. Go to Ducuments
2. Select Action Split
3. Splitting into 4 separate documents
4. Message that split will start as background task appears
5. Nothing happens but the Error message appears in the event log

<img width="506" alt="screenshot_181" src="https://github.com/paperless-ngx/paperless-ngx/assets/6528507/5fba2d66-0e67-4612-bb9a-0f38c9cba880">

<img width="383" alt="screenshot_182" src="https://github.com/paperless-ngx/paperless-ngx/assets/6528507/4c4d6242-34e9-40dc-abcf-793f91ae4a31">

### Webserver logs

```bash
`[2024-04-07 00:08:42,982] [ERROR] [paperless.bulk_edit] Error splitting document 815: cannot unpack non-iterable Group object
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/bulk_edit.py", line 279, in split
    overrides = DocumentMetadataOverrides().from_document(doc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/data_models.py", line 122, in from_document
    overrides.view_groups = [
                            ^
  File "/usr/src/paperless/src/documents/data_models.py", line 123, in <listcomp>
    group.id for group, perms in groups_with_perms if "view_document" in perms
                 ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable Group object`
```

### Paperless-ngx version

2.7.0

### Host OS

Raspberry Pi 64bit

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
#6302
