### ISSUE TITLE
[BUG] Not marking selection in Drop-Down-List

### ISSUE THREAD

**Issue by ppcutter** [paperless-ngx/paperless-ngx#6322]
### Description

When editing a document and you are typiong for example in the "correspondent" Textbox, the Drop-Down-List with the known correspondents open but when you use the cursor keys to select on of them you don´t see which one is marked as selected. When you count how often you use, for example, the Cursor-Down-Key, the right position is selected into the textbox.

### Steps to reproduce

1.) Got to "edit Document"
2.) Put cursor into one of the textboxes
3.) start typing
4.) try with the Cursor Keys to selsct one of the listed entries in the dropping down list
5.) the selection is not marked, though it is selected

### Webserver logs

```bash
no log
```

### Paperless-ngx version

2.6.3

### Host OS

Unraid Docker Container

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
If youre going to open a bug about a visual issue perhaps it would be helpful to include a screenshot. But frankly, this seems like a change request, not a bug.

**Comment by ppcutter** [comment]
thanks for the fast reaction. Though it was there in former versions, i thought it was a bug. I switched from version 1.17.x
![Bildschirmfoto vom 2024-04-07 20-28-21](https://github.com/paperless-ngx/paperless-ngx/assets/62708410/c3917005-c007-408f-9dc4-50905866d88f)
![Bildschirmfoto vom 2024-04-07 20-27-28](https://github.com/paperless-ngx/paperless-ngx/assets/62708410/fca0c6cb-c130-4543-b8f2-3fe9448d41c8)
 to the recent version when i changed my server hardware. In the version 1.x it was there.
See screenshots attached

**Comment by shamoon** [comment]
Ah, screenshots helpful, yes I'll fix that

**Comment by ppcutter** [comment]
Great, thanks. Have a nice week 

(and sorry for editing my comment repeatly, but i mentioned, that there was still private data that could be seen)
