### ISSUE TITLE
 [BUG] No visibility of the entire title of the related document

### ISSUE THREAD

**Issue by solarssk** [paperless-ngx/paperless-ngx#6334]
### Description

When trying to link a document that has a long title - I am unable to verify which document I can link to an existing other document.

Let's assume a hypothetical situation as in the picture - two documents, one of which is the original, the other was a copy sent to another government.

<img width="505" alt="Screenshot 2024-04-08 at 17 42 45" src="https://github.com/paperless-ngx/paperless-ngx/assets/83293863/397b74c5-6579-4660-a7cd-e7ecc823177c">
<img width="491" alt="Screenshot 2024-04-08 at 17 42 53" src="https://github.com/paperless-ngx/paperless-ngx/assets/83293863/8d5c34f1-13cb-4a0f-bc0b-6d3882fa6ec4">

The solution that comes to mind is to show the document title from the back (that is, with insufficient window space - the end of the title would be shown). But this will not work in all situations.

You can also try to do it in such a way that in the case of an already added related document - when you move the mouse, you see the data of this document with the full title (kind of like a tooltip above the document title). 
The problem arises with a large number of documents associated with a given document and then it is already a mess.

### Steps to reproduce

n/a

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.7.0

### Host OS

x86_64

### Installation method

Docker - official image

### Browser

Safari

### Configuration changes

screen size: 1792x1120 px

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
You can open a feature request.
