### ISSUE TITLE
[BUG] No possibility to show next document from a filtered list (where in paperless-ng, *save and next* was a thing)

### ISSUE THREAD

**Issue by darkmattercoder** [paperless-ngx/paperless-ngx#636]
**Describe the bug**

I noticed that in contrary to paperless-ng, the document editing process in paperless-ngx came up with a new UX design decision which does slow down my regular workflow.

Formerly, you could hit *save* or *save and next* to leave the editing view, either being forwarded to the list of documents you started from, or the next document in that list was shown.

With ngx though, it seems that those buttons do only work when you actually altered something in the edit view. 

How am I supposed to tag my documents now with the lowest possible effort? I frequently leave certain documents unchanged and simply want to have the possibility to say *leave it as is for now, just show me the next document in the list*

Why has this been altered? It feels really counter-intuitive. 

Clearly we do not want users to frequently *close* the edit view, look into the next document, decide whether to actually edit it or not, and repeat, do we?

**Expected behavior**
A one-click possibility to switch to the next document in the list. 

**Relevant information**
 - Host OS of the machine running paperless: [Debian Buster]
 - Browser [chromium]
 - Version [e.g. 1.6.0]
 - Installation method: [docker]
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`:
 
 ``` 
PAPERLESS_OCR_LANGUAGE=deu+eng
PAPERLESS_FILENAME_FORMAT={correspondent}-{created_year}{created_month}{created_day}-{document_type}-{tag_list}
PAPERLESS_TIME_ZONE=Europe/Berlin
```

**Comment by darkmattercoder** [comment]
In the meantime I see that all this originated in https://github.com/jonaswinkler/paperless-ng/issues/57 and lead to the corresponding pull request. 

However, how can it be, that no one complained about this new behaviour? Am I so odd in the way I edit my documents, that I find it weird to be forced to do an edit in order to get the next document in a row displayed?

**Comment by darkmattercoder** [comment]
Proposal:

Add an additional button *Next* which can be disabled as soon as the logic which enables the *Save* and the *Save & Next* buttons enables them. That way you have both, saving only happens when actual changes are being made and still keep the possibility to get the next document presented.

**Comment by shamoon** [comment]
Closed by https://github.com/paperless-ngx/paperless-ngx/pull/273
Next release :)
