### ISSUE TITLE
[Other] Crowdin: New account and app access required

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#64]
We likely need a new account for Crowdin to continue translation.

**Comment by shamoon** [comment]
I’m gonna try and set something up for this

**Comment by shamoon** [comment]
I think this is working though its obviously new to me, I setup a separate account for it too so things dont look so crazy.

We will invite people to help out at: https://crwd.in/paperless-ngx

(someone please tell me if I messed anything up 😅)
