### ISSUE TITLE
[BUG] Orphaned documents / missing original + archived due to different unicode encoding of special chars

### ISSUE THREAD

**Issue by tlwt** [paperless-ngx/paperless-ngx#6400]
### Description

**Summary:** Intermittent errors are occurring in a Paperless setup using an SQLite database, specifically with files containing German umlauts (ä, ö, ü). The root of the issue lies in the differing encodings of umlauts between the file system and the SQLite database. While the file system encodes umlauts one way (e.g., ä as 00E4), the database encodes them differently (e.g., 0061 + 0308).

**Details:** 
The following has happend now twice, but I cannot reproduce when. I run paperless with a sqlite database and yesterday I realized that paperless was having ~100 files with

```
[2024-04-14 00:31:49,625] [ERROR] [paperless.sanity_checker] Original of document does not exist.
[2024-04-14 00:31:49,626] [ERROR] [paperless.sanity_checker] Archived version of document does not exist.
```

and further on in the log

`"[2024-04-14 00:31:50,436] [WARNING] [paperless.sanity_checker] Orphaned file in media dir ..."`

The problematic files all contain German umlaut (äöü). 

* On the file system the the encoding is e.g ä is encoded as `00E4`
* while in the SQLITE database it is encoded as `0061 + 0308`

![Bildschirmfoto 2024-04-15 um 08 37 31](https://github.com/paperless-ngx/paperless-ngx/assets/8267086/9409a01a-0317-4cfd-8bc3-8fe0fae56681)

**Manual fix:**
To fix this issue I am running the following SQLITE command:

```sql
UPDATE documents_document
SET filename = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(filename, 'ä', 'ä'), 'ö', 'ö'), 'ü', 'ü'),'Ä','Ä'), 'Ö','Ö'),'Ü','Ü'),
    archive_filename = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(archive_filename, 'ä', 'ä'), 'ö', 'ö'), 'ü', 'ü'),'Ä','Ä'), 'Ö','Ö'),'Ü','Ü')
WHERE filename LIKE '%ä%' OR archive_filename LIKE '%ä%' OR
	  filename LIKE '%ö%' OR archive_filename LIKE '%ö%' OR
	  filename LIKE '%ü%' OR archive_filename LIKE '%ü%';
```

### Steps to reproduce

I cannot reproduce this behavior but it happened twice.

### Webserver logs

```bash
(removed file names for confidentiality)

[2024-04-14 00:31:49,625] [ERROR] [paperless.sanity_checker] Original of document does not exist.
[2024-04-14 00:31:49,626] [ERROR] [paperless.sanity_checker] Archived version of document does not exist.
...
[2024-04-14 00:31:50,436] [WARNING] [paperless.sanity_checker] Orphaned file in media dir ...
```

### Paperless-ngx version

2.7.2

### Host OS

UBUNTU x86_64 x86_64 x86_64 GNU/Linux

### Installation method

Docker - official image

### Browser

not relevant

### Configuration changes

mapped folders instead of volumes

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
That's what I would do.  Strings in Python are utf8 and we're not doing anything odd with encoding.  Values copied from a PDF might not be UTF-8, I guess  an OCR program wouldn't know what encoding, though I would assume everything at this point is UTF-8
