### ISSUE TITLE
[BUG] Document merge breaks on existing ASN

### ISSUE THREAD

**Issue by mightyjens** [paperless-ngx/paperless-ngx#6440]
### Description

I just used the wonderful new functionality to merge a couple of documents. If one (or more) of these documents contain an ASN barcode, the merge will be split at this position instead of continue merging. The split-part containing the ASN is then rejected with "Given ASN # already exists".

I think the system is absolutely doing its correct job splitting and checking the ASN, but shouldn't this be supressed on merging?
// I don't think that the merge process should care about the ASN functionality at all.

**My config:**
PAPERLESS_CONSUMER_ENABLE_BARCODES=true 
PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=true 
PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXING 

### Steps to reproduce

1. Upload a couple of documents where one (or more) have an assigned ASN barcode 
2. Use the new merge functionality to merge these documents

### Webserver logs

```bash
[2024-04-19 09:09:43,897] [ERROR] [paperless.consumer] Not consuming 209_556_228_229_230_231_232_233_234_235_236_238_239_240_307_310_311_312_313_323_325_341_364_365_369__merged_document_1.pdf: Given ASN 3 already exists!
```

### Paperless-ngx version

2.7.2

### Host OS

Debian

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
A merged document is a new document. It goes through the same process as every new document.  If it includes a barcode and barcode processing is enabled, this seems like expected behavior to me.

**Comment by mightyjens** [comment]
Absolutely, paperless is exactly acting as expected, but this would mean that it would never be possible to merge several documents into a single document as soon as an ASN barcode is present on one of the documents. Paperless will split it and throw an error on the existing ASN.

**Comment by shamoon** [comment]
As noted, it’s doing what you set it to, you can open a FR to somehow handle this differently
