### ISSUE TITLE
[BUG] Document title are not visible in merge window

### ISSUE THREAD

**Issue by pustekuchen91** [paperless-ngx/paperless-ngx#6442]
### Description

When try to merge two documents via the merge actions, in many cases the document titles are not visible
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/7147324/77de6b21-d5c3-4a56-bcf0-a0882f438b99)

it needs 2-3 times open the merge window, to show the titles.

After a longer time `Error: Promised response from onMessage listener went out of scope` appears. But this maybe is another issue, because this show after a merge window with document titles

### Steps to reproduce

1. Go to Documents
2. Choose two documents to merge
3. Actions
4. Merge

### Webserver logs

```bash
no logs to mention
```

### Paperless-ngx version

2.7.2

### Host OS

any

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I can’t reproduce this and those instructions certainly aren’t enough. If you’re seeing an actual error please paste the entire output

**Comment by pustekuchen91** [comment]
Hi @shamoon ,

i've done some further testing. It seems that the request of the document titles just need some time. I've recorded a gif.

![paperless_bug_merge](https://github.com/paperless-ngx/paperless-ngx/assets/7147324/0246be4c-d58b-4d0c-a3b1-1a48e1e15971)

In my paperless instance are about 1050 documents.

**Comment by shamoon** [comment]
Thats not that many documents, your system seems oddly slow to respond. The next version speeds up how the documents are retrieved here anyway.

**Comment by pustekuchen91** [comment]
Okay thanks, i will check back with the next release. 

If my system would react so slowly, why is the normal document list displayed immediately and why does it take so long to query the titles of two documents then?

**Comment by shamoon** [comment]
Because in the current release its retrieving more documents than it needs at once.
