### ISSUE TITLE
[BUG] Mail rule filter attachment filename is case sensitive

### ISSUE THREAD

**Issue by dpaulat** [paperless-ngx/paperless-ngx#645]
### Description

The "Mail rules" interface says the Filter attachment filename should be case insensitive:

> Only consume documents which entirely match this filename if specified. Wildcards such as *.pdf or \*invoice\* are allowed. Case insensitive.

The latest revision of mail.py uses fnmatch, which follows the operating system's rules for case sensitivity:

https://github.com/paperless-ngx/paperless-ngx/blob/a728502988fe26da9aa2844916dcfcc2455d0be2/src/paperless_mail/mail.py#L286-L288

Issue ported from https://github.com/jonaswinkler/paperless-ng/issues/1394

### Expected behavior

Mail attachments should be matched case insensitive to the Filter attachment filename.

### Steps to reproduce

1. Set up paperless to consume from a mailbox
2. Set up a mail rule with a filter attachment filename of *.pdf
3. Send an attachment ending in *.PDF

### Paperless-ngx version

1.6.0

### Host OS

Oracle Linux 8

### Installation method

Docker

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/00287b27ab163d1f86a233803c021bb7412d3195
