### ISSUE TITLE
system is unusable with a lot of correspondents

### ISSUE THREAD

**Issue by shoogland-etn** [paperless-ngx/paperless-ngx#6452]
### Description

you hav more than a few hundret correspondents

### Steps to reproduce

import correspondents and go to documents. in the searchbar click on correspondendents

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.7.2

### Host OS

Docker

### Installation method

Docker - official image

### Browser

all

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not an actionable bug report. Every system on which paperless can be deployed will have some upper limit of performance, you didn’t correctly list your OS above but it would seem you’ve hit the limit of your setup. Other things like db type can also affect this.
