### ISSUE TITLE
[BUG] Images do not rotate

### ISSUE THREAD

**Issue by Slyke** [paperless-ngx/paperless-ngx#6454]
### Description

I uploaded an image of a receit from my phone, but it was taken in the wrong orientation. I tried to rotate the image, but it doesn't apply. I did try empty cache and hard reload.
![image](https://github.com/paperless-ngx/paperless-ngx/assets/6442613/c5a989ae-df83-4d3f-b47b-4e361c2559b2)
![image](https://github.com/paperless-ngx/paperless-ngx/assets/6442613/f22e9d49-f2a5-458e-a438-7b5e6b86eb68)

I did find this recent discussion: https://github.com/paperless-ngx/paperless-ngx/discussions/6309

But I don't see the warning about it only working on PDFs (like in the discussion), so I'm assuming that images should be rotatable since nothing in the UI prevents or mentions otherwise. Please close if this is incorrect!

### Steps to reproduce

1. Upload an image (mine is a jpg).
2. Open the image
3. Actions -> Rotate
4. Click either the left or right rotate buttons, then click proceed.
5. Close and reopen the image.
6. Nothing happens

### Webserver logs

```bash
Not sure why it doesn't detect that it is an image. I can see it being rotated in the browser.

[2024-04-20 08:30:40,169] [INFO] [paperless.bulk_edit] Attempting to rotate 1 documents by 270 degrees.
[2024-04-20 08:30:40,175] [WARNING] [paperless.bulk_edit] Document 89 is not a PDF, skipping rotation.
```
```


### Browser logs

```bash
No logs in the developer console. I can see the bulk_edit api call returning "Ok"
```

### Paperless-ngx version

2.7.2

### Host OS

Kubernetes

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

Running exposed on the internet, behind nginx and Authelia

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
> ```shell
> Document 89 is not a PDF, skipping rotation.
> ```

Also https://docs.paperless-ngx.com/usage/#pdf-actions

you can open a FR to disable the rotate option for non PDFs
