### ISSUE TITLE
[BUG] (dev - Audit Log) Document history not loading

### ISSUE THREAD

**Issue by auer1329** [paperless-ngx/paperless-ngx#6482]
### Description

I just tried to take a look at the Audit Log UI in the current dev version for context of the new translation strings, but it seems like it's loading forever.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/50010167/54fabbe7-0da8-48e8-8589-b87e65575850)

In the Django admin panel there are log entries for this document:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/50010167/37042768-d303-4aa4-ba1e-f6d853116e39)

### Steps to reproduce

1. Go to Document
2. Click on "History"
3. Wait

### Webserver logs

```bash
Paperless-ngx docker container starting...
Installing languages...
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [155 kB]
Fetched 9209 kB in 3s (2958 kB/s)
Reading package lists...
Package tesseract-ocr-eng already installed!
Package tesseract-ocr-deu already installed!
Mapping UID and GID for paperless:paperless to 1031:65537
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
Running Django checks
System check identified no issues (0 silenced).
Did not create superuser, a user dev already exists
Executing /usr/local/bin/paperless_cmd.sh
2024-04-24 06:25:59,033 INFO Set uid to user 0 succeeded
2024-04-24 06:25:59,037 INFO supervisord started with pid 1
2024-04-24 06:26:00,040 INFO spawned: 'gunicorn' with pid 227
2024-04-24 06:26:00,042 INFO spawned: 'celery' with pid 228
2024-04-24 06:26:00,045 INFO spawned: 'celery-beat' with pid 229
2024-04-24 06:26:00,047 INFO spawned: 'consumer' with pid 230
```

### Paperless-ngx version

2.7.2-dev (sha256:f682906ac39595ec530f54ececf903826605dbba36c64fdcd3d7f74feb91760d)

### Host OS

Synology DSM x86_64

### Installation method

Docker - official image

### Browser

Edge, Chrome, Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Well, not seeing this. Did you see the migrations run on startup?

```
  Applying auditlog.0013_alter_logentry_timestamp... OK
  Applying auditlog.0014_logentry_cid... OK
  Applying auditlog.0015_alter_logentry_changes... OK
```

**Comment by shamoon** [comment]
If you can actually provide logs with some kind of error or the api response etc that could be helpful. Otherwise theres nothing really actionable here.

**Comment by auer1329** [comment]
No, I didn't see any migrations at startup. I updated the log in my post.

Also I don't see an error message anywhere, so I guess I'll try to wipe my dev instance and try again.

**Comment by shamoon** [comment]
Ah, its a database thing
