### ISSUE TITLE
[BUG]  Multiple MIME Types not detected - "Unsupported mime type application/octet-stream"

### ISSUE THREAD

**Issue by grunwalski** [paperless-ngx/paperless-ngx#6499]
### Description

Given a PDF that is both `octet-stream` and `pdf` the error message is `Unsupported mime type application/octet-stream`
 
There is an closed issue for this bug [here](https://github.com/jonaswinkler/paperless-ng/issues/906). 
But there might be a fix:

With `--keep-going` you can check for all MIME types assigned:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/2621952/afcc7a51-d17c-4668-88b1-d2c75f393403)

A friend of mine guessed this. I am merely delivering it as possible way to work around it by checking for multiple MIME types - since I'm already in way over my head.

In my case the problem was solved over time. The vendor eventually started outputting _proper_ PDF files.
If I understand correctly,  `octet-stream` could be the [fallback MIME type](https://stackoverflow.com/questions/12061030/why-am-i-getting-mime-type-of-csv-file-as-application-octet-stream) when the [non-standard](https://stackoverflow.com/questions/312230/proper-mime-media-type-for-pdf-files) `application/x-pdf` was used. 

And just in case, the PDFs I had the problem with were - according to Adobe Acrobat - created with:

> Antenna House PDF Output Library 2.6.0 (Windows (x64))
> AH Formatter VS. 1 MRI (5, 1,20Cß, 1209) for Windows (xE4)

 
 
 
 OT: Thanks for your time. I am 3 days into paperless-ngx and I love it. ❤

### Steps to reproduce

Upload a PDF file with not only pdf as MIME type.

### Webserver logs

```bash
[2024-04-25 18:02:42,622] [ERROR] [paperless.consumer] Unsupported mime type application/octet-stream
```

### Paperless-ngx version

2.7.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Mime detection is not using `file`, but `libmagic` through [`python-magic`](https://pypi.org/project/python-magic/) which doesn't provide the option you mentioned.

Frankly though, an improperly created PDF which has junk at the start isn't something we're going to be looking to fix.  I would suggest you "clean" such files through `qpdf` instead.

**Comment by grunwalski** [comment]
I agree. If there is no quick fix, its just not big enough and not your fault in the first place. Thanks for checking.

I went the qpdf route and it worked. `qpdf [FILENAME] [OUTPUT_FILENAME]`

**Comment by hayander** [comment]
> Mime detection is not using `file`, but `libmagic` through [`python-magic`](https://pypi.org/project/python-magic/) which doesn't provide the option you mentioned.
> 
> Frankly though, an improperly created PDF which has junk at the start isn't something we're going to be looking to fix. I would suggest you "clean" such files through `qpdf` instead.

Is there a way to do this automatically? I tried putting a call to qpdf in a pre-consume script but this script is triggered after the checks for mime type (And is thus rejected before it can be cleaned).

**Comment by grunwalski** [comment]
I don't think automatic via paperless-ngx. If I am correct, "non-processed" files via mail-fetch aren't stored. So you would have to download them manually anyway.

But in case the team istouching this issue for any other reason in the future, I found the `keep_going` command in [python-magic](https://github.com/ahupp/python-magic/blob/master/magic/__init__.py#L53)
