### ISSUE TITLE
[BUG] "Automatically remove inbox tag(s) on save" should enable "Save" Button even when no changes have been made

### ISSUE THREAD

**Issue by tom-anders** [paperless-ngx/paperless-ngx#6519]
### Description

When paperless gets all the metadata right on a new document, and I have the "Automatically remove inbox tag(s) on save" option enabled, I want to click the "Save" button without actually editing anything. Currently, the button is disabled (which of course made sense before this new option was a thing).

I suspect this would be a rather trivial fix, so I'd be happy to contribute (but I'd need some guidance on finding the right files in the codebase to change)

### Steps to reproduce

1. "Automatically remove inbox tag(s) on save" settings is enabled
2. Consume a new document
3. Edit the document
4. "Save" and "Save & Next" buttons are disabled

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.7.2

### Host OS

Synology NAS

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This isnt a bug, it's just how it works currently. If you'd like to open a FR that'd be fine but I actually think that would be potentially confusing behavior.
