### ISSUE TITLE
py3.11 is wrongly marked as not supported...

### ISSUE THREAD

**Issue by nerdoc** [paperless-ngx/paperless-ngx#6538]
### Description

When installing on bare metal, during pip install -r requirements.txt i get the warning:
```
pip install --break-system-packages -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.python.org/simple
Ignoring exceptiongroup: markers 'python_version < "3.11"' don't match your environment
Ignoring typing-extensions: markers 'python_version < "3.11"' don't match your environment
```

This is not breaking paperless, but the warning should be removed  as py3.11 **is** supported.

### Steps to reproduce

pip install --break-system-packages -r requirements.txt in /opt/paperless as "paperless" user, as in the setup docs.

### Webserver logs

```bash
not related
```

### Paperless-ngx version

2.7.2

### Host OS

Debian 12.5

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Yeah, that's just pip informing you it isn't installing something that isn't needed

**Comment by nerdoc** [comment]
I know, it's just that you write in your docs that a `pip install` does the trick. It should be better stated that a venv should be used, even when using an own `paperless` user for running it (which should be mandatory).

  >8.  Install python requirements from the requirements.txt file. It is up to you if you wish to use a virtual environment or not.

The docs could be improved here. If you play through the bare metal install, you don't get a working system. When not using a venv, you'd have to use `--break-system-packages` due to PEP 668.

So IMHO in the docs it should be at least recommended to use a venv. I would add the instructions too there.

**Comment by shamoon** [comment]
I’m not an expert here, but that PEP is 3y old. Id guess more likely is that it varies by arch / os etc. Also, to be honest, we assume a certain level of comfort with package management, virtual environments and those sorts of things for folks who want to do a ‘bare metal’ install. Anyway, you can always PR the docs but again I’m not the best person to assess

**Comment by nerdoc** [comment]
@shamoon This could be true - as it is a Debian 12 install. Couldn't reproduce it on Ubuntu 22.04 LTS.
So  maybe this is distro specific.
But the other thing is: even if you are not "comfortable" with pip,venvs etc. - especially if you are **not** - you should be able to follow "dumb" instructions and get a working system. I think this is the difference of good and excellent documentation.
I am comfortable with those tools, and I write and package python software myself, so I think this does matter to newcomers which want to adapt or try out paperless-ngx. Not everyone is capable of handling docker neither. And I for myself would like to use "bare metal", as I use a dedicated proxmox container for paperless - so "bare metal" makes definitely sense in favor of docker here...
There are other glitches in the docker install docs too, and if it's ok and I find time, I'll really make a PR for them.

For now, this issue here is ok to be kept closed, as it has nothing to do with the other issues, I'd open new ones for them if that's ok.

Thanks for your feedback.
