### ISSUE TITLE
[BUG] Misleading error message when email credentials are read-only

### ISSUE THREAD

**Issue by nirvdrum** [paperless-ngx/paperless-ngx#6545]
### Description

I attempted to set up email integration with Fastmail. Fastmail uses app-specific passwords with configurable capabilities. Thinking that Paperless-ngx only needed to read my email, I gave it read-only IMAP support. When I click the "Test" button, I see:

> Unable to connect to the mail server

This led me to believe there was a connectivity error. I double-checked my SSL settings and credentials, but still couldn't connect. I verified I could resolve the host. Eventually, I realized there's now a _mail.log_ file under the "Logs" view. Looking in there, I see:

> [paperless_mail] Error while authenticating account 2024-05-02T00:31:04.446897: b'"INBOX"' is not writable

That message was considerably more helpful. It was clear that the read-only access was problematic (although, I'm unsure why on that). I recreated the app password with read/write access and now can successfully connect.

I think the generic "Unable to connect to the mail server" message was misleading. Best would be something like "Able to connect, but unable to write" or some variant of that. If the message needs to be generic, then a message that doesn't mention connectivity would be more helpful, perhaps redirecting the user to the log for more details.

### Steps to reproduce

Reproducing the issue may be difficult if your email provider doesn't allow setting up read-only access. In that case, it might be best to simulate a write failure.

1. Set up a new mail account
2. Use read-only credentials
3. Click the "Test" button

### Webserver logs

```bash
[paperless_mail] Error while authenticating account 2024-05-02T00:31:04.446897: b'"INBOX"' is not writable
```

### Paperless-ngx version

2.7.2

### Host OS

Debian Bookworm x86_64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
> I think the generic "Unable to connect to the mail server" message was misleading.

This is a change ("feature" for simplicity) request, not a bug, feel free to open one. The message is accurate, it couldn't connect.

**Comment by nirvdrum** [comment]
> The message is accurate, it couldn't connect.

Maybe we're working with different definitions of "connect"? Since the client managed to connect the IMAP server and initiate a login, I would have considered to have established a connection. Authentication happens after a connection is established and that's evidently where the problem stems from. Saying it couldn't connect suggests a DNS problem, SSL misconfiguration, firewall interference, or some other network failure.

In the code you quoted, the exception message from `MailError` is ignored and replaced with a generic "Unable to connect to server". The exception was raised after the connection was established.

I appreciate the guidance on navigating the issue tracker. Some projects treat usability problems as improvements, others as bugs. Here, it sounds like it may be more a case of being ambiguous rather than inaccurate, so I'll turn it into a feature request. Thank you.

**Comment by shamoon** [comment]
> Some projects treat usability problems as improvements, others as bugs.

Thanks for your understanding. Perhaps just pointing to the logs would be helpful.
