### ISSUE TITLE
[BUG] decodingFailed(<APIRequest: PATCH path("/api/documents/1161/")> Error

### ISSUE THREAD

**Issue by derbrowser** [paperless-ngx/paperless-ngx#6552]
### Description

When editing a document (e.g. changing Tags or editing the type) I always receive the following error message

"decodingFailed(<APIRequest: PATCH path("/api/documents/1161/")>, Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "userCanChange", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"userCanChange\", intValue: nil) (\"userCanChange\"), converted to user_can_change.", underlyingError: nil)))"

<img width="310" alt="Pasted Graphic 9" src="https://github.com/paperless-ngx/paperless-ngx/assets/100370217/e3ea8fd3-2b00-49f4-a679-b88d6f691242">

### Steps to reproduce

edit a documents preferences

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.7.2

### Host OS

Synology

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I suspect this error is from one of the paperless apps, none of which we develop. In general, the API for basic things like changing document properties is not broken.
