### ISSUE TITLE
[BUG] Document history not readable

### ISSUE THREAD

**Issue by th3noname** [paperless-ngx/paperless-ngx#6598]
### Description

Some text elements in the document history ui are currently not readable:
![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/1923981/fd99ba7f-4f5f-45c6-9bf5-6bd77bd26af4)

### Steps to reproduce

Open document history

### Webserver logs

```bash
Not relevant
```

### Paperless-ngx version

2.8.1

### Host OS

raspberry pi arm64

### Installation method

Docker - official image

### Browser

Firefox 125

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Shows you how much I use non-dark mode...

**Comment by th3noname** [comment]
@shamoon The global searchbar seems to have a similar issue:

![grafik](https://github.com/paperless-ngx/paperless-ngx/assets/1923981/6a59f4a5-ae40-446a-a9b6-5b1ecf078758)

**Comment by shamoon** [comment]
Gotcha
