### ISSUE TITLE
Dockercontainer not started - 164 Illegal instruction python3 manage.py check

### ISSUE THREAD

**Issue by dimmenhau** [paperless-ngx/paperless-ngx#6617]
### Description

I have just updated my Docker containers to version 2.8.x. For version 2.8.0 and 2.8.1, the error message `/sbin/docker-prepare.sh: line 75: 164 Illegal instruction python3 manage.py check` is displayed.

### Steps to reproduce

docker-compose down
docker-compose pull
docker-compose up -d

### Webserver logs

```bash
Paperless-ngx docker container starting...
Installing languages...
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8786 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [13.8 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [156 kB]
Fetched 9211 kB in 4s (2269 kB/s)
Reading package lists...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
Mapping UID and GID for paperless:paperless to 1000:100
usermod: no changes
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
Running Django checks
/sbin/docker-prepare.sh: line 75:   164 Illegal instruction     python3 manage.py check
```

### Paperless-ngx version

2.8.x

### Host OS

Ubuntu

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please see https://github.com/paperless-ngx/paperless-ngx/discussions/6610#discussioncomment-9342624. The docker container isnt known to be broken and Im not aware of anything that would cause this, but it is indeed curious that youre the second person to report this. Please let us know in that thread
