### ISSUE TITLE
The version is displayed incorrectly

### ISSUE THREAD

**Issue by pafade89** [paperless-ngx/paperless-ngx#6618]
### Description

Version in the Dashboard ist correct:

![IMG_20240507_184714](https://github.com/paperless-ngx/paperless-ngx/assets/113902279/7fd4a13e-9fe2-46c9-91b0-650d8c13bf8e)

But Not in side menu:

![IMG_20240507_184632](https://github.com/paperless-ngx/paperless-ngx/assets/113902279/bc69e49b-29a2-4b31-8c2d-ecf09a79df77)

### Steps to reproduce

Compare Version in system overview and in side menu

### Webserver logs

```bash
.
```

### Paperless-ngx version

2.8.1

### Host OS

Debian

### Installation method

Other (please describe above)

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Either you need to clear your browser cache or you did not correctly re-deploy.

From the demo:

<img width="349" alt="Screenshot 2024-05-07 at 10 09 36 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/a279ca57-6abb-4093-9312-e6a04f11fc6d">

**Comment by tbnobody** [comment]
> Either you need to clear your browser cache or you did not correctly re-deploy.

Having the same issue... Migrations are all done:
```
sudo -Hu paperless python3 manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
```

Browser cache cleared or even used a complete different browser.

The remote_version API shows the correct one:
![image](https://github.com/paperless-ngx/paperless-ngx/assets/1753222/8cfec1e8-7ee0-4fc3-9614-469870ac236f)

But the frontend shows 2.7.1
![image](https://github.com/paperless-ngx/paperless-ngx/assets/1753222/bcd5ca1d-b203-428f-9037-0fb104820343)

**Comment by tbnobody** [comment]
And due to the fact that I was running 2.7.1 I rolled back the VM snapshot and migrated from 2.7.1 to 2.7.2 first --> worked without issues. But when upgrading from 2.7.2 to 2.8.0 the version number does not change.

**Comment by shamoon** [comment]
The version number is embedded in the javascript and nothing about how it is parsed has changed between these versions. Also, as noted above, it works fine in our docker image on the demo and running locally. Perhaps this has to do with the tool you guys are using to install the software, but I dont think theres a bug here.

https://github.com/paperless-ngx/paperless-ngx/blob/ce08400f4e1274d11250df0c4cd0a5d6ac499bc7/src-ui/src/app/components/app-frame/app-frame.component.ts#L49

**Comment by tbnobody** [comment]
The tool is quite simple:
```bash
#!/bin/bash

VERSION_NEW=2.8.1

wget https://github.com/paperless-ngx/paperless-ngx/releases/download/v$VERSION_NEW/paperless-ngx-v$VERSION_NEW.tar.xz
tar -xf paperless-ngx-v$VERSION_NEW.tar.xz

sudo -Hu paperless rsync -av --exclude 'paperless.conf' paperless-ngx/ paperless/

cd paperless
sudo -u paperless pip install -r requirements.txt  --break-system-packages

cd src
sudo -Hu paperless python3 manage.py migrate

cd ../..

systemctl restart paperless-*.service
rm -R paperless-ngx
```

The version in the `/opt/paperless/static/frontend/de-DE/main.js` file is also correct 
BUT not the version main.js.gz!
So I assume there is some kind of server side generation of files?

**Comment by tbnobody** [comment]
Based on the volumes in the docker image the following should do the job:
```bash
sudo -Hu paperless rsync -av --delete --exclude='paperless.conf' --exclude='media/' --exclude='data/' --exclude='consume/' --exclude='export/' paperless-ngx/ paperless/
```
