### ISSUE TITLE
[BUG] Currency input parsing issue with point and/or comma

### ISSUE THREAD

**Issue by petarmarj** [paperless-ngx/paperless-ngx#6621]
### Description

In Switzerland, currency amounts are written with the decimal point. Since the update to 2.8.1, I cannot use a point as a decimal separator for a Swiss franc amount. The input parser deletes the input `444.50` after the point. However, if I enter the amount of money with a comma like `444,50`, the API refuses to save it. 

![Bildschirmaufnahme2024-05-07um20 02 51-ezgif com-video-to-gif-converter](https://github.com/paperless-ngx/paperless-ngx/assets/2379437/b6b0580b-21fe-4740-8d69-69ad8837d1e3)

### Steps to reproduce

1. Use browser locale de-CH and write `444.50` as Swiss francs `CHF` amount.
2. Write `444,50` and save it.

### Webserver logs

```bash
No errors in log.
```

### Browser logs

```bash
{"headers":{"normalisedNames":{}, "lazyUpdate":null}, "status":400, "statusText": "Bad Request", "url": "http://****/api/documents/2752/", "ok":false, "name": "HttpErrorResponse", "message": "Http failure response for http://****/api/documents/2752/: 400 Bad Request", "error":{"custom_fields":[{},{},{},{},{"non_field_errors":["Must be a two-decimal number with optional currency code e.g. GBP123.45"]}]}}
```

### Paperless-ngx version

2.8.1

### Host OS

x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

docker-compose.yml

### Other

window.navigator.language is 'de-CH'

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by petarmarj** [comment]
Looks like the last zero in `444,50` is not being registred by an event handler; PUT request sends `{field: 14, value: "CHF444.5"}` which does not match `^[A-Z]{3}-?\d+(\.\d{2,2})$`.

**Comment by shamoon** [comment]
Testing this kinda stuff is pretty challenging, but I cant reproduce. Using the `,` saves OK as the value is parsed to a float. See video:


https://github.com/paperless-ngx/paperless-ngx/assets/4887959/815cbbbf-e91e-43fd-98f9-ea8fe136b4d1

**Comment by petarmarj** [comment]
Looks like `input[type=number]` causes the issue: I tracked in Chrome's console the keyups (aka: the real changes) for the currency field.

```
document.querySelector("[step='.01']").addEventListener("keyup", (event) => {
  console.log(event.target.value)
});
```

My input was `123,45` and then `123.45`. Console output is:

```
# with comma
> 1
> 12
> 123
> 123.4
> 123.45

# with point
> 1
> 12
> 123
> 
> 4
> 45 
```

With `input[type=text]` there is no such behaviour.

**Comment by shamoon** [comment]
But it is a number and there are pros to it being a number so as opposed to just changing it to text. The browser controls what decimal separator is allowed based on locale, because we dont.

**Comment by petarmarj** [comment]
You say that you cannot reproduce the problem. What does your console say when you enter 123.45 and 123,45 here? You can see my output after the code.

```
    <input type="number" inputmode="numeric" step=".01"
        class="form-control text-muted ng-valid ng-dirty ng-touched" pattern="[-+]?[0-9]*[.,]?[0-9]+">

    <script>
        document.querySelector("[step='.01']").addEventListener("keyup", (event) => {
            console.log(`Key pressed /
 e.target.value / e.target.valueAsNumber`);
            console.log([event.key, event.target.value , event.target.valueAsNumber])
        });
    </script>
```

![Bildschirmfoto 2024-05-07 um 23 48 17](https://github.com/paperless-ngx/paperless-ngx/assets/2379437/8f5733ce-923e-4cd6-b503-21d76c7053ab)

`input[type=number]` is notoriously known as an unreliable element. [Gov.uk](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/) has provided a blog on this. I'm not an experienced front-end developer, but I've known for months that input elements like this are exciting and semantic – but a pain in cases of localisation and decimal numbers. 

It's up to you how you deal with UX problems when they are caused by browsers. Personally, I think it's still a bug in a project when development expects a certain behaviour from frontend renderers, browsers don't meet those expectations, and this leads to UX problems. We may not be in the days of Internet Explorer, but we can't expect browsers to simply deliver the behaviour developers expect. So it saddens me to see the bug report so casually dismissed.

I hope you keep this in mind the next time someone participates empathetically, gratefully, collaboratively and constructively.

**Comment by shamoon** [comment]
I’m not all that clear why you seem to have taken an oppositional tone, the PR that closed this does [change the decimal part too](https://github.com/paperless-ngx/paperless-ngx/pull/6626/commits/0ba5ed85b7ff49f3a86f8898548f1b3556eb3c26). I was saying I am not certain if that is a browser issue or the Angular framework or who knows what causing decimal values to be parsed as null when the locale is expecting numbers with commas and not seeing the thing with the frontend sending un-padded values.

So anyway, this was unpleasant! I think I’ll step away now.
