### ISSUE TITLE
[BUG] Email processing fails because of non-ascii character in email account password

### ISSUE THREAD

**Issue by nomad-999** [paperless-ngx/paperless-ngx#663]
### Description

The email processing fails if the email account password contains a non-ascii character.

### Expected behavior

Non-ascii characters should be acceptable in passwords anywhere.

### Steps to reproduce

1. Set up an email account with a password containing the letter ž
2. Connect the email account to paperless-ngx
3. Review the logs.

### Webserver logs

```bash
`[2022-04-07 09:02:15,780] [ERROR] [paperless.mail.tasks] Error while processing mail account XXXXXX

Traceback (most recent call last):

  File "/opt/paperless/src/paperless_mail/mail.py", line 166, in handle_mail_account

    M.login(account.username, account.password)

  File "/opt/paperless/.local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 60, in login

    login_result = self.box._simple_command('LOGIN', username, self.box._quote(password))  # noqa

  File "/usr/lib/python3.9/imaplib.py", line 1230, in _simple_command

    return self._command_complete(name, self._command(name, *args))

  File "/usr/lib/python3.9/imaplib.py", line 987, in _command

    arg = bytes(arg, self._encoding)

UnicodeEncodeError: 'ascii' codec can't encode character '\u017e' in position 16: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/paperless/src/paperless_mail/tasks.py", line 14, in process_mail_accounts

    total_new_documents += MailAccountHandler().handle_mail_account(account)

  File "/opt/paperless/src/paperless_mail/mail.py", line 168, in handle_mail_account

    raise MailError(f"Error while authenticating account {account}")

paperless_mail.mail.MailError: Error while authenticating account XXXXXX`
```

### Paperless-ngx version

1.6.0

### Host OS

Linux

### Installation method

Bare metal

**Comment by crazychatting** [comment]
maybe the same with https://github.com/paperless-ngx/paperless-ngx/issues/643#issuecomment-1088211707 ?

**Comment by nomad-999** [comment]
![image](https://user-images.githubusercontent.com/103181380/162260708-ac746dbc-bb25-49e8-ac10-f228e2d856b9.png)
This is the character set for the email account.

**Comment by stumpylog** [comment]
In my testing, this looks to be an issue in imap_tools.
```
>>> from imap_tools import MailBox
>>> m_box = MailBox("imap.gmx.com", 993)
>>> m_box.login("dev-testing-paperless@gmx.com", "réception")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tank/users/trenton/projects/paperless/paperless-ngx/.venv/lib/python3.8/site-packages/imap_tools/mailbox.py", line 63, in login
    login_result = self.client._simple_command('LOGIN', username, self.client._quote(password))  # noqa
  File "/usr/lib/python3.8/imaplib.py", line 1205, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.8/imaplib.py", line 962, in _command
    arg = bytes(arg, self._encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 2: ordinal not in range(128)
```

(obviously spoofed values in the log here)

**Comment by stumpylog** [comment]
Well, it's actually more down in IMAP I think.  I don't think the basic LOGIN command only supports non US-ASCII charsets and doesn't have an optional CHARSET which can be provided.  In fact, per [the RFC](https://datatracker.ietf.org/doc/html/rfc3501#section-6.2.3) we shouldn't be using login except as a last resort.  The better command I guess is [authenticate](https://datatracker.ietf.org/doc/html/rfc3501#section-6.2.2).

I wonder if the solution is to update mail fetching to support a user name and token (I think that's OAuth2?)

**Comment by stumpylog** [comment]
Unfortunately, as suspected, this isn't a bug with imap_tools or the Python IMAP client.  The IMAP specification only supports ASCII for a login with username and password.  The encoding being set for an account is for *messages* (which I agree is not clear).

Does your email server provide application specific passwords?  Does it support some form of OAUTH 2 or other authentication method?  If it does, how long do those tokens last?

**Comment by nomad-999** [comment]
Thanks for the comment, I am afraid it goes beyond my limited knowledge: I run Postfix 3.4.14  and Dovecot 2.3.4.1 and use non-ascii letters in passwords without problems in desktop, mobile and web mail clients. I looked around and found this [RFC](https://bugs.python.org/issue21800) and this [Python bug report](https://bugs.python.org/issue21800) related to it and they confirm the need for using **authenticate**.

**Comment by stumpylog** [comment]
Yeah, that's about what I found as well.  That RFC [specifically tells us](https://datatracker.ietf.org/doc/html/rfc6855#section-5) to use `authenticate`.

So the solution is to use that, but I'm afraid it's beyond my understanding of IMAP currently.
