### ISSUE TITLE
[BUG] Set the names of subdirectories as tags for consumed files

### ISSUE THREAD

**Issue by Nautilus34** [paperless-ngx/paperless-ngx#6659]
### Description

Hello, 

I have modified the configuration to allow the creation of a tag per folder or subfolder. 
When I drag and drop a folder containing subfolders and PDF files into Paperless, no tag is created.

Thank you for your help

### Steps to reproduce

1. nano /opt/paperless/paperless.conf 

PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=true

2. Drag and drop a folder containing subfolders and PDF files into Paperless

### Webserver logs

```bash
NA
```

### Paperless-ngx version

Paperless-ngx 2.8.2

### Host OS

Debian 12

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You have to restart the consumer, at a minimum, to apply such a change.

**Comment by Nautilus34** [comment]
Hello @stumpylog 

I already tried and even restarted the system.

**Comment by stumpylog** [comment]
Nothing has changed about recursive tagging in quite some time.  Either you are not using the correct configuration file or the environment is otherwise not correctly set
