### ISSUE TITLE
[BUG] "Error migrating update checking settings" upon login for non-admin users

### ISSUE THREAD

**Issue by nebulade** [paperless-ngx/paperless-ngx#6720]
### Description

When a non-admin user logs in, the following notification is shown. Not just once but with every login:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/646768/e869d2d0-107e-4568-bd6e-a7e18a3f5391)

This does not happen for admin users.
I tried to find the actual error string in the code to debug this code path further, but had no luck, but python/django is also not my strength. Any pointers where to get started with debugging is greatly appreciated.

Original report was at https://forum.cloudron.io/topic/11731/someone-else-with-non-admin-users-and-an-annoying-error-migrating-update-checking-setting

### Steps to reproduce

1. Log in with non-admin user
2. Error notification is shown

### Webserver logs

```bash
Maybe some clue as upon login the server logs:

13:50:15 - [2024-05-14 11:50:15,017] [WARNING] [django.request] Forbidden: /api/ui_settings/
13:50:15 - [2024-05-14 11:50:15,111] [WARNING] [django.request] Forbidden: /api/saved_views/
```

### Browser logs

```bash
The browser terminal shows the corresponding requests:

XHR POST https://paper.nebulon.space/api/ui_settings/ [HTTP/2 403  56ms]

XHR GET https://paper.nebulon.space/api/saved_views/?page=1&page_size=100000 [HTTP/2 403  67ms]
```
Those work fine for admins.

### Paperless-ngx version

2.8.4

### Host OS

Cloudron

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I think the user doesn’t have permissions to the Ui settings, which you probably don’t really want. The error is accurate, they can’t save their own settings.

**Comment by nebulade** [comment]
That makes sense, however in this case the user has not performed any action as such, this happens automatically upon login. It seems some code in the UI should be skipped for non-admins?

**Comment by nebulade** [comment]
Thanks for the hint. After manually adding the `UISettings` permission, things work as expected. I guess now we have to find a way how to do this automatically for new users to avoid the error and the extra step for the admin to grant anyway required permissions.
