### ISSUE TITLE
Global Search: default sorting gone and filter for another Tag does not work

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#6736]
### Description

After using the new Global Search for a Tag the document list is not ordered for "created document date" (as it should be default) anymore. No sorting method is highlighted in the sort drop down menu.

When you then try to filter for another Tag by clicking on a Tag on a document thumbnail nothing happens.

### Steps to reproduce

- Search for a Tag in the upper new Global Search.
- Click there on the found Tag name.
- Now results are shown unsorted.
- Click on another Tag on a Thumbnail. Nothing happens.

### Webserver logs

```bash
/usr/local/lib/python3.11/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'documents.models.Document'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
/usr/local/lib/python3.11/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'documents.models.Document'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
```

### Browser logs

```bash
nothing relevant there
```

### Paperless-ngx version

2.8.5

### Host OS

gentoo x86_64

### Installation method

Docker - official image

### Browser

Chrome latest for macOS ARM

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Sigh. I know what the issue is, will have to figure out a workaround.

**Comment by shamoon** [comment]
Actually, looking at this, clicking another tag does work, its just that its using "Any" instead of "All", which could probably be changed, I'll think about that. The losing sorting thing should be corrected

**Comment by r2ixuz** [comment]
Hmm, I think "All" is much more useful. And this is/was the normal behaviour when not using the global search.

Would appreciate it if we could get a consistent search result no matter if using Global Search or just the normal search via the Tags drop down menu.
