### ISSUE TITLE
paperless-ngx prevents hdd from spin down

### ISSUE THREAD

**Issue by RalfJahns** [paperless-ngx/paperless-ngx#6785]
### Description

According to blktrace logs, processes "postgres" and "celery beat" access the disk regulary.

Usually I don't access my NAS for days or even weeks, because of this spin down is important for me. 
Issue was reported before for paperless-ng (without x) but there was no real answer, if this is intended behaviour.
https://github.com/jonaswinkler/paperless-ng/issues/1589

### Steps to reproduce

Configure hd-idle to spin down disk, watch hd-idle logs or blktrace

### Webserver logs

```bash
not relevant
```

### Paperless-ngx version

2.7.2

### Host OS

Debian Bookworm

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Respectfully, this is not a bug. If you'd like to make absolute certain that paperless-ngx does not use the hard drive for anything then you can shut it down (and / or the database and task queue containers which are what you referenced above).
