### ISSUE TITLE
[BUG] Traceback in logs on every found duplicate

### ISSUE THREAD

**Issue by wduda** [paperless-ngx/paperless-ngx#6787]
### Description

I am currently reimporting about 1600 files to see if I have missed any during first import. On every duplicate found I see a traceback in file logs.

### Steps to reproduce

1. Add a pdf that is a duplicate of archived pdf to ingestion dir.
2. Wait for ingestion to start.
3. Observe file logs.

### Webserver logs

```bash
[2024-05-20 19:15:59,603] [ERROR] [paperless.consumer] Not consuming SWD_HV_Gew_UES_153.pdf: It is a duplicate of SWD_HV_Gew_UES_153 (#1976)

[2024-05-20 19:15:59,603] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: SWD_HV_Gew_UES_153.pdf: Not consuming SWD_HV_Gew_UES_153.pdf: It is a duplicate of SWD_HV_Gew_UES_153 (#1976)

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 144, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 499, in run

    self.pre_check_duplicate()

  File "/usr/src/paperless/src/documents/consumer.py", line 326, in pre_check_duplicate

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 302, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: SWD_HV_Gew_UES_153.pdf: Not consuming SWD_HV_Gew_UES_153.pdf: It is a duplicate of SWD_HV_Gew_UES_153 (#1976)
```

### Paperless-ngx version

2.8.6

### Host OS

Qnap NAS

### Installation method

Docker - official image

### Configuration changes

      PAPERLESS_OCR_LANGUAGES: eng deu pol       PAPERLESS_OCR_LANGUAGE: eng+deu+pol       PAPERLESS_OCR_MODE: redo       PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'       PAPERLESS_CONSUMER_INOTIFY_DELAY: 1       PAPERLESS_CONSUMER_DELETE_DUPLICATES: true       PAPERLESS_CONSUMER_RECURSIVE: true       PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true       PAPERLESS_DATE_ORDER: DMY       PAPERLESS_IGNORE_DATES: "14-03-1981,05-03-1985"       PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true # enable setting ASN by ASN barcodes       PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING # switch from pyzbar to zxing for small code recognition       PAPERLESS_TIME_ZONE: Europe/Berlin       PAPERLESS_FILENAME_FORMAT: "{created_year}/{document_type}/{title}"       PAPERLESS_TIKA_ENABLED: 1       PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000       PAPERLESS_TIKA_ENDPOINT: http://tika:9998

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Its doing exactly what its intended to do, telling your its a duplicate.

**Comment by wduda** [comment]
Thanks, understood. I was just thinking that a duplicate would be logged as a normal operation and not an error that also logs the traceback. But if that is WAI then all good :-)
