### ISSUE TITLE
[Other] Adjustment of the Helm chart

### ISSUE THREAD

**Issue by alexander-bauer** [paperless-ngx/paperless-ngx#68]
There is a Kubernetes Helm chart in the k8s-at-home project [here](https://artifacthub.io/packages/helm/k8s-at-home/paperless). I don't know who maintains this, but we should try and get it adjusted to use the new `ghcr.io` container line.

**Comment by strayer** [comment]
> There is a Kubernetes Helm chart in the k8s-at-home project [here](https://artifacthub.io/packages/helm/k8s-at-home/paperless). I don't know who maintains this, but we should try and get it adjusted to use the new `ghcr.io` container line.

You can see the maintainer when clicking the info button. Won’t post it here since it links directly to an email address for privacy reasons.

**Comment by morremeyer** [comment]
As a user of the chart, I can take care of this. Feel free to assign me here.

However, it might be sensible to deprecate the paperless-ng chart in k8s-at-home for a new -ngx chart to make users aware of the transition.

I'll check with the k8s-at-home maintainers

**Comment by morremeyer** [comment]
I've started with a PR to k8s-at-home to see how the project reacts. Will check out the truecharts one afterwards.

If they're both successful, I'll look into pinging others that have charts for paperless, but I won't submit a PR to every single one, there's too many projects. for that

**Comment by morremeyer** [comment]
k8s-at-home was pleased that the project is being picked up by the community. I'm opening a PR to the truecharts repository now, once that is done we can close this issue.

I will keep maintaining the k8s-at-home chart afterwards so that we get timely updates for it.

**Comment by qcasey** [comment]
This appears to be done, thank you for putting that PR together. 

https://github.com/truecharts/apps/commit/2cbd3a10350e616fb13918668e6b8b277e2a6183
