### ISSUE TITLE
[BUG] OIDC name retrieval problem

### ISSUE THREAD

**Issue by rqi14** [paperless-ngx/paperless-ngx#6807]
### Description

Hi. I connected my paperless instance with Microsoft Entra ID. I found the the system got the surname and forename in the wrong order. For example, I can see that in the django management bit the information paperless got from Entra ID is something like this
`{"sub": "WG4boqoDkhwWRbM_9VPulm00cnzx5INdM2lH2TGIyYI", "name": "Zhang San", "email": "zhangsan@example.com", "picture": "https://microsoftgraph.chinacloudapi.cn/v1.0/me/photo/$value", "given_name": "San", "family_name": "Zhang"}`

But it set the surname of the user to "San" and the forename to "Zhang".

It does not seem correct to me

### Steps to reproduce

1. Set up Entra ID
2. As a new user, go to paperless and login using Entra ID
3. As an admin, check the new user's profile and you can see the user's surname is set to its given name in Entra ID, and the user's given name in paperless is set to its surname in Entra ID
4. In Django admin bit, you can see paperless got the correct JWAT but the name is set incorrectly.

### Webserver logs

```bash
Nothing relevent is available in the log.
```

### Paperless-ngx version

2.8.6

### Host OS

ubuntu 23.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This seems like an allauth question.  It handles all oidc for paperless.

**Comment by shamoon** [comment]
This functionality comes from a package we use called [django-allauth](https://github.com/pennersr/django-allauth) and is be pretty surprised if there was a basic bug like that in it but you can look in their issues. In general, paperless itself doesn’t do anything with the profile data from oidc in any way:

https://github.com/paperless-ngx/paperless-ngx/blob/f7ce32f4717d10a0e4cefdb6b589abed96ba66d9/src/paperless/adapter.py#L89
