### ISSUE TITLE
[BUG] Filename in notifications should be unescaped

### ISSUE THREAD

**Issue by madduck** [paperless-ngx/paperless-ngx#6830]
### Description

When uploading a document, the UI shows me a notification. But if the filename contains e.g. spaces, these are displayed as `%20`, and Unicode characters are similarly encoded:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/195073/747bf33e-d85f-41c4-956a-7aee1b5b2349)

### Steps to reproduce

1. Upload a file containing a space in its name, and/or a Unicode character
2. Observe the percent escape sequence in the notification

### Webserver logs

```bash
n/a
```

### Browser logs

```bash
n/a
```

### Paperless-ngx version

2.8.6-dev

### Host OS

Debian

### Installation method

Bare metal

### System status

```json
{
    "pngx_version": "2.8.6",
    "server_os": "Linux-6.1.0-21-amd64-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 1081101176832,
        "available": 1023055286272
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "account.0009_emailaddress_unique_primary_email",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-05-25T13:54:58.664000+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-05-25T11:08:16.182649Z",
        "classifier_error": null
    }
}
```

### Browser

n/a

### Configuration changes

n/a

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I cant reproduce this, maybe its a filesystem thing, this also isnt something thats changed for many years

<img width="373" alt="Screenshot 2024-05-25 at 9 01 41 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/62af5d7a-9635-4d31-8e44-513f4d7a6a58">
<img width="371" alt="Screenshot 2024-05-25 at 9 04 37 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/80b4c65d-001e-4197-a04b-252b8fba40e9">

**Comment by madduck** [comment]
Hey @shamoon, thanks for your quick response. I am sorry I filed an incomplete issue report, because I failed to mention that I was using the API directly from `aiohttp`, and `aiohttp.form` (incorrectly) encodes the filename of a MIME Multipart form: https://github.com/aio-libs/aiohttp/pull/6826.

So PNGX is doing exactly as it should, and the bug is in `aiohttp`.
