### ISSUE TITLE
[BUG] Split function not working on .eml files

### ISSUE THREAD

**Issue by LordDragonus** [paperless-ngx/paperless-ngx#6831]
### Description

I have imported an e-mail using the e-mail function. I have forwarded it to an address without attachments. A document with 6 pages was generated. 3 pages contain the e-mail in text form, 3 pages as an HTML version. Now I would like to split the document, discard the text and keep the HTML part. When splitting, I receive the information that the process has been started in the background. But nothing else happens. When I then look at the log files, I see an error.

The mentioned file "0000007.eml" also exists in the file system and is an e-mail. Could it be that the split function here is trying to open the file as a PDF file instead of converting it again first and then splitting it?

### Steps to reproduce

1. Import an e-mail with the e-mail import function
2. Try to split the file using the UI

### Webserver logs

```bash
[2024-05-25 15:49:45,161] [INFO] [paperless.bulk_edit] Attempting to split document 7 into 2 documents

[2024-05-25 15:49:45,166] [ERROR] [paperless.bulk_edit] Error splitting document 7: /usr/src/paperless/media/documents/originals/0000007.eml: unable to find trailer dictionary while recovering damaged file

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/bulk_edit.py", line 302, in split

    with pikepdf.open(doc.source_path) as pdf:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pikepdf/_methods.py", line 398, in open

    pdf = Pdf._open(

          ^^^^^^^^^^

pikepdf._core.PdfError: /usr/src/paperless/media/documents/originals/0000007.eml: unable to find trailer dictionary while recovering damaged file
```

### Paperless-ngx version

2.8.6

### Host OS

Debian GNU/Linux 11

### Installation method

Docker - official image

### System status

```json
{"pngx_version":"2.8.6","server_os":"Linux-5.10.0-29-amd64-x86_64-with-glibc2.36","install_type":"docker","storage":{"total":1080090406912,"available":1009992605696},"database":{"type":"postgresql","url":"paperless","status":"OK","error":null,"migration_status":{"latest_migration":"socialaccount.0006_alter_socialaccount_extra_data","unapplied_migrations":[]}},"tasks":{"redis_url":"redis://broker:6379","redis_status":"OK","redis_error":null,"celery_status":"OK","index_status":"OK","index_last_modified":"2024-05-25T15:20:07.953010+02:00","index_error":null,"classifier_status":"OK","classifier_last_trained":"2024-05-25T14:05:00.412680Z","classifier_error":null}}
```

### Browser

Firefox 126.0

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
<img width="984" alt="Screenshot 2024-05-25 at 9 20 23 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/2f911351-c200-4449-a92d-9bb39068ebde">

https://docs.paperless-ngx.com/usage/#pdf-actions

As stated in the documentation, you can only split PDFs

**Comment by LordDragonus** [comment]
Thanks for your quick reply! This is quite confusing as when I download the file, it downloads as a PDF file. If I then upload it again, it also works. Why is it then not possible to keep the file internally as a PDF file or the new files after splitting so that it works? Or, if this is not so easy, is it possible to hide the option?

**Comment by shamoon** [comment]
Yes, the button should be disabled, I'll fix that.

For now, we dont try to split the archive files, only the original, that would be a reasonable feature request.
