### ISSUE TITLE
[BUG] file with umlaut in name unlink during sanity check

### ISSUE THREAD

**Issue by anqi970301** [paperless-ngx/paperless-ngx#6839]
### Description

I have problem similar to #2161 . A pile of files with umlaut (ä, ö, ü) in filename suddenly detached from the database with error "document does not exist" and warning "orphaned file" at the same time. 

I have been using the same database on macOS for 1 year without problem. Starting from 2024-04-21, every week paperless conducts a sanity check and output the warning "orphaned file" but no error and I can preview/download the files. (orphaning the same files again and again every week, not sure if it gets linked back in between).

Last week I moved to ubuntu by copying the full database. Starting from this week's sanity check, it returns both error and warning and I cannot preview/download file anymore. I'm sure the path still exists, and the files are not broken, just not detected.

### Steps to reproduce

1. Upload file with ä, ö, ü in file name
2. Wait until the next sanity check

### Webserver logs

```bash
[2024-05-26 00:30:04,871] [ERROR] [paperless.sanity_checker] Original of document does not exist.

[2024-05-26 00:30:04,871] [ERROR] [paperless.sanity_checker] Archived version of document does not exist.

[2024-05-26 00:30:04,938] [WARNING] [paperless.sanity_checker] Orphaned file in media dir: /usr/src/paperless/media/documents/originals/Rückrechnung.pdf
```

### Paperless-ngx version

1.16.5

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
If you review the linked issue and other similar ones you should see these issues have to do with encoding of the file system and in the end are not something paperless can control.

**Comment by anqi970301** [comment]
> If you review the linked issue and other similar ones you should see these issues have to do with encoding of the file system and in the end are not something paperless can control.
> 
> See #6501

Thanks for the reply! I reset the storage path to default to avoid further problem.
