### ISSUE TITLE
[BUG] Warning on invalid metadata is not limited in size.

### ISSUE THREAD

**Issue by ordnungswidrig** [paperless-ngx/paperless-ngx#6856]
### Description

As described, e.g. in #1093, a warning is logged if tesseract cannot read specific metadata from a document. However the warning message is not limited in size and can lead to a multi-megabyte log line.

```
[2024-05-10 11:34:10,053] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.canto.com/XML/ns/XMPMetadata/1.0}CantoMetadata: 7265636F000000090000013C504C4E4B6C69737400000003000000605543687200630075006D0075006C00750073003A002F...
```

The message above was cropped, for obvious reasones.

### Steps to reproduce

Upload file with very long invalid metadata

### Webserver logs

```bash
[2024-05-10 11:34:10,053] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.canto.com/XML/ns/XMPMetadata/1.0}CantoMetadata: 7265636F000000090000013C504C4E4B6C69737400000003000000605543687200630075006D0075006C00750073003A002F
```

### Paperless-ngx version

2.8.2

### Host OS

Debian / GNU Linux (Linux XXXX 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux)

### Installation method

Docker - official image

### System status

```json
{"pngx_version":"2.8.2","server_os":"Linux-4.19.0-25-amd64-x86_64-with-glibc2.36","install_type":"docker","storage":{"total":84224425984,"available":22299648000},"database":{"type":"postgresql","url":"paperless","status":"OK","error":null,"migration_status":{"latest_migration":"socialaccount.0006_alter_socialaccount_extra_data","unapplied_migrations":[]}},"tasks":{"redis_url":"redis://broker:6379","redis_status":"OK","redis_error":null,"celery_status":"OK","index_status":"OK","index_last_modified":"2024-05-29T00:00:12.383288+02:00","index_error":null,"classifier_status":"OK","classifier_last_trained":"2024-05-29T06:05:01.260390Z","classifier_error":null}}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Seems kinda esoteric and really like the pdf is the problem not handling what is a bit of an edge case, and not really a bug anyway

**Comment by phmeier-nubank** [comment]
I value your assessment, but with PDFs potentially automatically imported from external sources like Mail folder, this could be a way to DOS a paperless instance. I agreed this is potentially low priority but limiting the output of log statements in a good advice in general.

**Comment by shamoon** [comment]
You’re welcome to open a feature (change) request and if this is an issue for lots of other folks we can look into it, I’m not aware of anyone reporting this in the past. And I’m not sure this actually constitutes a DOS vector as uploading documents is a privileged endpoint.
