### ISSUE TITLE
[BUG] websockets broken with channels 4.1.0+

### ISSUE THREAD

**Issue by gringus** [paperless-ngx/paperless-ngx#6862]
### Description

websockets fail (I have `paperless-ngx` configured on subpath) with `HTTP 500` when `paperless-ngx-2.8.6` runs with `channels-4.1.0`. The problem does not manifest with the very same setup and `channels-4.0.0`. I was able to narrow it to the [following commit](https://github.com/django/channels/commit/82c26f2585bca8b76d8f72f4a971095c8f899606).

### Steps to reproduce

1. Build `paperless-ngx-2.8.6` with `channels-4.1.0`
2. Login to `paperless-ngx` portal. In the browser console (Network tab) you should be able to see failed websocket request (`HTTP 500`)
3. Upload document - progress bar is not updating

### Webserver logs

```bash
127.0.0.1 - - [29/May/2024:21:32:03 +0200] "GET /paperless/ws/status/ HTTP/1.1" 500 526 0.010/0.010 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0" "-|-"
```

### Paperless-ngx version

2.8.6

### Host OS

Gentoo Linux x86_64

### Installation method

Bare metal

### System status

```json
{"pngx_version":"2.8.6","server_os":"Linux-6.9.2-hardened-x86_64-Intel-R-_Core-TM-_i5-8259U_CPU_@_2.30GHz-with-glibc2.39","install_type":"bare-metal","storage":{"total":125348462592,"available":71823257600},"database":{"type":"sqlite","url":"/var/lib/paperless/data/db.sqlite3","status":"OK","error":null,"migration_status":{"latest_migration":"documents.1048_alter_savedviewfilterrule_rule_type","unapplied_migrations":[]}},"tasks":{"redis_url":"unix:///run/redis/redis.sock","redis_status":"OK","redis_error":null,"celery_status":"OK","index_status":"OK","index_last_modified":"2024-05-29T18:03:20.851959Z","index_error":null,"classifier_status":"OK","classifier_last_trained":"2024-05-29T19:05:00.289647Z","classifier_error":null}}
```

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Not really sure why you're reporting the issue here then?  That's not a commit in our code

**Comment by gringus** [comment]
Because of https://github.com/paperless-ngx/paperless-ngx/blob/dev/Pipfile#L25
Also, this should help other users having similar problems.

**Comment by stumpylog** [comment]
Yes and ?  I'm failing to see an issue here.  If django-channels made a commit that broke something, then the issue should be reported there.

**Comment by gringus** [comment]
Ok, so do you want me to stop carrying next time? That's easy.. I can do that.
The question is: is this change manifesting a problem with `paperless-ngx` or `channels`? I don't know the answer, so that's why I opened a bug report here.

**Comment by stumpylog** [comment]
I would report it upstream.  As I've said, if they made a change which breaks something which has worked fine for quite a while, that seems like something they would be best suited to fix.

It's clear from the snipped above, we set the URL correctly: `/paperless/ws/status/`.  Everything else is from `WebsocketConsumer` from django-channels.

**Comment by gringus** [comment]
[My take on the problem](https://slonko.net/git/portage/plain/www-apps/paperless-ngx/files/channels-4.1.patch)

**Comment by shamoon** [comment]
Did you have a chance to report upstream?

**Comment by gringus** [comment]
Not at all.
