### ISSUE TITLE
[BUG] Labeling of the button with “Redo OCR” is misleading

### ISSUE THREAD

**Issue by dolorosus** [paperless-ngx/paperless-ngx#6864]
### Description

Labeling of the button with “Redo OCR” is misleading.

as we learned form https://github.com/paperless-ngx/paperless-ngx/discussions/6291#discussioncomment-9023197 this button does not trigger a "Redo OCR" if PAPERLESS_OCR_MODE is set to skip. 

The label "Redo OCR" implies that OCR is redone in every case, which misleads the user and makes him believe that there is an error in the OCR

### Steps to reproduce

open an Document

### Webserver logs

```bash
Not a webserver error
```

### Paperless-ngx version

2.8.6

### Host OS

Linux-6.5.0-35-generic-x86_64-with-glibc2.36

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Feel free to make a request to change it, where this can be discussed.  But it's not a bug.
