### ISSUE TITLE
[BUG] Docker paperless-ngx_webserver_1 is using %25 of CPU constantly

### ISSUE THREAD

**Issue by gerroon** [paperless-ngx/paperless-ngx#688]
### Description

The paperless-ngx_webserver_1 component of the Docker setup is using %25 cpu constantly according to Docker stats, when nobody is accessing it.

I am the only user of the setup and I am not accessing it, the page is not open anywhere, not uploading documents, and all the documents were already processed, but it is still using constant cpu like that for days. 

The issue can be resolved temporarily with restarting the docker setup, but the cpu usage issue eventually comes back.

### Expected behavior

It should not be using cpu when it is not in use.

### Steps to reproduce

docker-compose up
wait for a while to see the usage

### Webserver logs

```bash
0:45:47 [Q] INFO recycled worker Process-1:690
10:45:47 [Q] INFO Process-1:692 ready for work at 73967
10:46:11 [Q] INFO Processed [summer-video-happy-carpet]
10:55:45 [Q] INFO Enqueued 1
10:55:45 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
10:55:45 [Q] INFO Process-1:691 processing [cardinal-vegan-lamp-one]
10:55:46 [Q] INFO Process-1:691 stopped doing work
10:55:47 [Q] INFO recycled worker Process-1:691
10:55:47 [Q] INFO Process-1:693 ready for work at 74077
10:55:53 [Q] INFO Processed [cardinal-vegan-lamp-one]
11:05:48 [Q] INFO Enqueued 1
11:05:48 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
11:05:48 [Q] INFO Process-1:692 processing [seventeen-william-robert-princess]
11:05:49 [Q] INFO Process-1:692 stopped doing work
11:05:49 [Q] INFO recycled worker Process-1:692
11:05:49 [Q] INFO Process-1:694 ready for work at 74183
11:05:52 [Q] INFO Processed [seventeen-william-robert-princess]
11:15:20 [Q] INFO Enqueued 1
11:15:20 [Q] INFO Process-1 created a task from schedule [Train the classifier]
11:15:20 [Q] INFO Process-1:693 processing [blossom-emma-emma-cola]
11:15:36 [Q] INFO Process-1:693 stopped doing work
11:15:37 [Q] INFO recycled worker Process-1:693
11:15:37 [Q] INFO Process-1:695 ready for work at 74313
11:15:38 [Q] INFO Processed [blossom-emma-emma-cola]
11:15:50 [Q] INFO Enqueued 1
11:15:50 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
11:15:50 [Q] INFO Process-1:694 processing [hamper-cardinal-bacon-gee]
11:15:51 [Q] INFO Process-1:694 stopped doing work
11:15:51 [Q] INFO recycled worker Process-1:694
11:15:51 [Q] INFO Process-1:696 ready for work at 74315
11:15:51 [Q] INFO Processed [hamper-cardinal-bacon-gee]
11:25:52 [Q] INFO Enqueued 1
11:25:52 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
11:25:52 [Q] INFO Process-1:695 processing [oxygen-four-timing-saturn]
11:25:53 [Q] INFO Process-1:695 stopped doing work
11:25:53 [Q] INFO recycled worker Process-1:695
11:25:53 [Q] INFO Process-1:697 ready for work at 74430
11:25:56 [Q] INFO Processed [oxygen-four-timing-saturn]
11:35:24 [Q] INFO Enqueued 1
11:35:24 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
11:35:24 [Q] INFO Process-1:696 processing [mike-magnesium-fifteen-lima]
11:35:25 [Q] INFO Process-1:696 stopped doing work
11:35:25 [Q] INFO recycled worker Process-1:696
11:35:25 [Q] INFO Process-1:698 ready for work at 74532
11:35:25 [Q] INFO Processed [mike-magnesium-fifteen-lima]
11:45:26 [Q] INFO Enqueued 1
11:45:26 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
11:45:26 [Q] INFO Process-1:697 processing [london-timing-october-enemy]
11:45:27 [Q] INFO Process-1:697 stopped doing work
11:45:27 [Q] INFO recycled worker Process-1:697
11:45:27 [Q] INFO Process-1:699 ready for work at 74641
11:45:27 [Q] INFO Processed [london-timing-october-enemy]
11:55:28 [Q] INFO Enqueued 1
11:55:28 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
11:55:28 [Q] INFO Process-1:698 processing [hawaii-finch-summer-indigo]
11:55:29 [Q] INFO Process-1:698 stopped doing work
11:55:29 [Q] INFO recycled worker Process-1:698
11:55:29 [Q] INFO Process-1:700 ready for work at 74750
11:55:30 [Q] INFO Processed [hawaii-finch-summer-indigo]
12:05:32 [Q] INFO Enqueued 1
12:05:32 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
12:05:32 [Q] INFO Process-1:699 processing [echo-beryllium-hydrogen-failed]
12:05:33 [Q] INFO Process-1:699 stopped doing work
12:05:34 [Q] INFO recycled worker Process-1:699
12:05:34 [Q] INFO Process-1:701 ready for work at 74857
12:05:40 [Q] INFO Processed [echo-beryllium-hydrogen-failed]


```
```


### Screenshots

`paperless-ngx_webserver_1         25.99%    551.4MiB / 11.68GiB   4.61%     127MB / 601MB     27.9GB / 5.49GB   2063`

### Paperless-ngx version

1.6.0

### Host OS

Debian Testing

### Installation method

Docker

### Browser

Chrome

### Configuration changes

_No response_

### Other

_No response_

**Comment by qcasey** [comment]
Hello, thank you for the report. Possibly related: #318  #489 

A couple questions for you, if you're comfortable helping us debug (free free to do some/none/all of these):

Could you run from inside the container (`docker exec -it paperless-ngx_webserver_1 /bin/bash`)

* `ls -ahl /usr/src/paperless/data`
* `ls -ahl /usr/src/paperless/media`
* `id -u paperless`

From outside the container:

* `ls -ahl` for the locations where /usr/src/paperless/consume, /usr/src/paperless/data, /usr/src/paperless/media are mounted from

**Comment by qcasey** [comment]
Also if there is a particular process shown in `top` overconsuming CPU, that'd be useful too.

**Comment by gerroon** [comment]
Hi

I restarted the containers, so the issue is not there atm , but I will report back when those go up again. I know the cpu  goes up eventually because I have been regularly restarting the containers to keep the cpu usage low.

**Comment by shamoon** [comment]
Yea assuming that is `docker stats` something is clearly up, your block io is super high (though could be accurate if you have a ton of data) and that shows 2000 PIDs?? I wonder if permissions or something not obvious is preventing threads from getting killed or something like that. The `ls` and `id` commands dont need to wait until the issue comes up, fyi, `top` does of course. Thanks

**Comment by gerroon** [comment]
@qcasey 

After a day it has gone up to %12, and I am pretty sure it will hit up to %25 in less than a day, as you can see it has high pid


```
4b0019363420   paperless-ngx_webserver_1         12.29%    504.5MiB / 11.68GiB   4.22%     30.9MB / 139MB    7.66GB / 1.81GB   809
```


```
root@4b0019363420:/usr/src/paperless/src# ls -ahl /usr/src/paperless/data
total 13M
drwxrwxrwx 1 paperless paperless  146 Apr 12 18:05 .
drwxr-xr-x 1 paperless paperless   64 Apr  5 04:27 ..
-rwxrwxrwx 1 paperless paperless    2 Mar 21 17:16 .index_version
-rwxrwxrwx 1 paperless paperless  12M Apr  1 22:16 classification_model.pickle
-rwxrwxrwx 1 paperless paperless 1.3M Apr 12 18:05 db.sqlite3
drwxrwxrwx 1 paperless paperless  104 Apr 12 17:15 index
drwxrwxrwx 1 paperless paperless   60 Mar 21 17:16 log
-rwxrwxrwx 1 paperless paperless    0 Apr 11 17:12 migration_lock
root@4b0019363420:/usr/src/paperless/src# ls -ahl /usr/src/paperless/media
total 0
drwxrwxrwx 1 paperless paperless 38 Apr 11 17:12 .
drwxr-xr-x 1 paperless paperless 64 Apr  5 04:27 ..
drwxrwxrwx 1 paperless paperless 52 Mar 21 17:42 documents
-rwxrwxrwx 1 paperless paperless  0 Apr  1 21:54 media.lock
root@4b0019363420:/usr/src/paperless/src# id -u paperless
1000
root@4b0019363420:/usr/src/paperless/src# 
```

**Comment by qcasey** [comment]
That's very interesting, what is the status of the webserver container when you run `docker ps`? If it's been running for a while it should be `healthy`.

After checking that, yes removing that curls from the `docker-compose.yml` is fine, it's just a health check.

**Comment by gerroon** [comment]
It says healthy but there are hundreds of curl processes, and the cpu usage is up to %15

**Comment by qcasey** [comment]
Thanks. If you end up removing the healthcheck, please let us know if that solves this problem.

**Comment by shamoon** [comment]
am I correct in thinking that running that `curl` command directly works fine for you?

**Comment by gerroon** [comment]
@shamoon I do not know how it is supposed to work, but I ran the command in the container and I do not  see it finishing up the command, never quits it seems

```
root@4b0019363420:/usr/src/paperless/src# time  curl -f http://localhost:8000

```

**Comment by qcasey** [comment]
I'm thinking it's related to #700

**Comment by shamoon** [comment]
> I'm thinking it's related to #700 

But he's having this issue on 1.6.0 which doesn't have that issue no?

The command shouldn't show anything unless there's an error ie the webserver isn't running. If you add -L for example it'll follow redirects and should show the login page. As in, you try localhost:xxxx (ie something that doesn't exist) you'll see an error.

**Comment by shamoon** [comment]
Also, either way it should at least timeout eventually, assuming you still have something like `timeout: 10s` https://github.com/paperless-ngx/paperless-ngx/blob/0bd67a54abad7be86c073bc7dbc154c51befce9d/docker/compose/docker-compose.sqlite.yml#L44

**Comment by stumpylog** [comment]
I'm not sure that would kill the curl process though.  The timeout is used to determine if the healthcheck failed, but it's not clear to me if the CMD is killed after the timeout.  If curl is still trying to connect and not exiting, you could get something like this.  Maybe there should be a `--max-time` added?

Of course, not sure why curl would keep running if there was some webserver error...

**Comment by gerroon** [comment]
As far as I can tell the curl processes were not timing  out. I have removed the health curl stuff from the docker compose and so far the cpu usage is very minimal, I will keep watching and follow up here.

**Comment by shamoon** [comment]
Thanks for following up and appreciate clarification stumpy. Yea I was looking at this before, funny enough `--max-time` [doesnt seem to have a default](https://unix.stackexchange.com/a/94612).

Obviously theres the question of _why_ youre `curl` call is failing at all but the other issue is whether the healthcheck should be amended to prevent this. @gerroon if you are willing, it would be helpful to know if adding `--max-time` helps, e.g. changing the command to `curl --max-time 2 -f http://localhost:8000`. Looking around I found some healthchecks do include that option

Also, found this, maybe overcomplicating things... https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/

**Comment by gerroon** [comment]
My Paperless Docker (without health checks)  has been up for more than a day and the CPU usage is super minimal. So the original issue seemed to be generated by the health check related processes.

**Comment by shamoon** [comment]
@gerroon would you be willing to try this and see if it helps? Change the test line in the .yml to
`test: curl -fs -S --max-time 2 http://localhost:8000`

Either way, @stumpylog @qcasey should we consider changing that? Again, it does seem to come up https://github.com/thirdgen88/ignition-docker/issues/20 https://gitlab.com/gitlab-org/omnibus-gitlab/-/merge_requests/2620 etc.

**Comment by qcasey** [comment]
Something like this? https://github.com/paperless-ngx/paperless-ngx/commit/bb831be19ecc7d6037d9591b25dbc2df09e67c56

**Comment by shamoon** [comment]
In my testing that didnt quite work, I just get the curl progress bar thing as output, so even though it'll report "healthy" its kinda not, like if you run `inspect` with that command, at least I get (note the output):
```
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2022-04-16T08:46:01.509536443-07:00",
                        "End": "2022-04-16T08:46:01.638625845-07:00",
                        "ExitCode": 0,
                        "Output": "  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n"
                    }
                ]
            }
```

That was how I arrived at the above, like https://github.com/paperless-ngx/paperless-ngx/commit/258f5b3e0f443ca9892c451a7d436523e825476a . But Im def not the expert here!

**Comment by shamoon** [comment]
@gerroon can you confirm that this change fixes the issue? I know you removed your healthcheck but it would be good to implement a fix for all and since I dont have this issue in my environment I cant confirm. Thanks

```
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
```

**Comment by gerroon** [comment]
> @gerroon can you confirm that this change fixes the issue? I know you removed your healthcheck but it would be good to implement a fix for all and since I dont have this issue in my environment I cant confirm. Thanks
> 
> ```
>     healthcheck:
>       test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
>       interval: 30s
>       timeout: 10s
>       retries: 5
> ```

That seems to work fine as far as I can tell.

**Comment by shamoon** [comment]
Sweet thanks for the follow-up! Will draft a PR so we can close this one at least =)
