### ISSUE TITLE
[BUG] Tag remains selected in the dropdown after it has been deselected

### ISSUE THREAD

**Issue by granulos** [paperless-ngx/paperless-ngx#6906]
### Description

If a tag is selected in the document overview, it has to be deselected twice. After the first deselection the tag is still displayed as selected.

### Steps to reproduce

1. Open the document view
2. Select a tag -> Only corresponding documents are displayed / The tag is shown as selected
3. Deselect the tag -> The tag is no longer part of the filtering, but the tag is still shown as selected
4. Deselect the tag -> Now the dropdown and the overview show the correct state

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.9.0

### Host OS

Proxmox

### Installation method

Docker - official image

### Browser

Chrome 125.0.6422.142

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Perhaps its not clear what you mean here, but I certainly cant reproduce this (and nothing really shouldve changed here). See video:

https://github.com/paperless-ngx/paperless-ngx/assets/4887959/edbd5351-5220-40ce-a31a-34a4ccb7f252

**Comment by shamoon** [comment]
I think youre referring to the fact that a second click excludes the tag, see the little 'x'. Please let me know if Ive misunderstood

**Comment by granulos** [comment]
I am sorry. I completely overlooked this feature
