### ISSUE TITLE
[BUG] When restarting docker container, if there are items still in queue they are re-added to the queue on startup

### ISSUE THREAD

**Issue by paradizelost** [paperless-ngx/paperless-ngx#6915]
### Description

I have roughly 3000 files in the consume folder, i needed to change the number of workers/threads to work through it faster, and when restarting the containers, it re-added all of the items to the consumer queue.

### Steps to reproduce

Have x number of documents in consume folder in queue, stop and then start container. documents are all duplicated in the queue. 

### Webserver logs

```bash
web server logs would contain sensitive info
```

### Paperless-ngx version

2.8.6

### Host OS

Debian Bookworm

### Installation method

Docker - official image

### System status

```json
{"pngx_version":"2.8.6","server_os":"Linux-6.8.4-3-pve-x86_64-with-glibc2.36","install_type":"docker","storage":{"total":12460864700416,"available":10456169971712},"database":{"type":"mysql","url":"paperless","status":"OK","error":null,"migration_status":{"latest_migration":"socialaccount.0006_alter_socialaccount_extra_data","unapplied_migrations":[]}},"tasks":{"redis_url":"redis://broker:6379","redis_status":"OK","redis_error":null,"celery_status":"OK","index_status":"OK","index_last_modified":"2024-06-04T14:20:08.347048-05:00","index_error":null,"classifier_status":"OK","classifier_last_trained":"2024-06-04T17:05:02.310573Z","classifier_error":null}}
```

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by B5JohnSheridan** [comment]
I also observed this even without a restart of the container. Sometimes, files get added multiple times to the queue. This results in lots of "file not found" errors, as the files are removed from the consume folders when the first jobs consumes then. Later, when the second jobs runs, it will of course no longer find the file.

Wouldn't it be better, to check if the same file is already in the queue, e.g. making sure no duplicate queue entries exist in the consume queue?

**Comment by paradizelost** [comment]
That would be my thought when i opened the issue. I've seen the same when a mail item takes too long to process, it gets re-added to the queue multiple times and then causes failed because of duplicate errors.

**Comment by shamoon** [comment]
That sounds like a reasonable feature request which you are welcome to open (or try to implement of course). Keep in mind checking the names are the same doesnt guarantee the files are in fact the same, you'd need to use e.g. md5 checksum (which is what paperless uses to check for duplicates of existing files)

**Comment by paradizelost** [comment]
The issue isn't that the same name is there, its that the same file path is queued for ingestion more than once. if there's 3 items in queue with the same literal file path ( because it didn't move it to a different location for the queue) you're not going to get a different checksum for each, its the same literal file. thats why i'd consider this a bug not a feature request. 

i.e.  File /consume/xyz.pdf was in queue, container restarted, another instance of /consume/file.xyz.pdf gets added to the queue.  it should be able to say, is that path in queue, if so, skip it as already queued. checksum doesn't matter yet at that point.
