### ISSUE TITLE
[BUG] Content field is tracked incompletly in auditlog

### ISSUE THREAD

**Issue by tribut** [paperless-ngx/paperless-ngx#6960]
### Description

As part of https://github.com/paperless-ngx/paperless-ngx/pull/6388 the content field was declared as `mask_field` (https://github.com/paperless-ngx/paperless-ngx/pull/6388/commits/42eef35988fa262a1ff5085bb95e1341e1111b4f).

The result is that only the second half of the changed field is recorded (for example, when the original content is `None` during create, the auditlog records `**ne`). This seems to serve no purpose, because there is no reason why the first half of the contents of a document are somehow sensitive, while storing the second half is ok. It is also a regression because changes in the first half of the content field can no longer be reconstructed from the log.

Are you ok with reverting? Is there some reason why this is a good change?

### Steps to reproduce

1. Change content field of a document
2. Observe incomplete record in change history

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.9.0

### Host OS

Debian

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
tribut I don’t think this is a bug… it’s masked to keep it short. Happy to discuss the merits of changing it.
