### ISSUE TITLE
[BUG] Logo replacement from v2.9.0 not displaying on dashboard when not adding a Logo

### ISSUE THREAD

**Issue by Houbsi** [paperless-ngx/paperless-ngx#6965]
### Description

With the release of https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.9.0

The new awesome enhancement `Enhancement: support custom logo / title on login page @shamoon `  https://github.com/paperless-ngx/paperless-ngx/pull/6775

I just changed the name of the application without adding a Logo, and on the dashboard it didn't "create" the Logo version with the name. Like on the Login Page.
![image](https://github.com/paperless-ngx/paperless-ngx/assets/70960/e028d2a2-f446-46e6-86b6-6c33769e8c98)

When an image is added the Logo is shown, without "by paperless-ngx" on the dashboard. 
![image](https://github.com/paperless-ngx/paperless-ngx/assets/70960/867aa38f-9d58-4617-bf3d-bb415e3a1a79)

On the Login page, "by paperless-ngx" is added.
![image](https://github.com/paperless-ngx/paperless-ngx/assets/70960/60220330-184b-49b5-87f1-b70479b45bfc)

![image](https://github.com/paperless-ngx/paperless-ngx/assets/70960/3d693457-f4ea-4037-a24d-d665d6c7f97b)
![image](https://github.com/paperless-ngx/paperless-ngx/assets/70960/ab211bd3-d5ad-42f9-9265-80eca6898aed)

### Steps to reproduce

1. Change in Configuration > General Settings the Image / Description
2. Go to dashboard
![image](https://github.com/paperless-ngx/paperless-ngx/assets/70960/e028d2a2-f446-46e6-86b6-6c33769e8c98)

### Webserver logs

```bash
I suppose no logs needed for this
```

### Paperless-ngx version

1.9.0

### Host OS

x86_64 Synology Nas with Docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is intentional, feel free to open a FR.

**Comment by Houbsi** [comment]
Couldn't find something if it was intended or not.

You mean a PR? I will look into it :)

**Comment by shamoon** [comment]
FR meaning a feature request. This is intentional because the app displays the name on the left and the logo on the right, which isnt the case for the login page.

**Comment by Houbsi** [comment]
Oh my bad for FR/PR, did not come to mind.

Thanks for the clarification. I'll think about it and if my thoughts make sense, I'll create a Feature Request.
