### ISSUE TITLE
[BUG] Since 1.7.0-rc1 access via reverse proxy not working

### ISSUE THREAD

**Issue by WAdama** [paperless-ngx/paperless-ngx#698]
### Description

Got 1.7.0-rc1 today via Watchtower update.

Since then my access via reverse proxy (nginx) is not working anymore.

Error message I got is after activating debug for Django is:

`Verboten (403)

CSRF-Verifizierung fehlgeschlagen. Anfrage abgebrochen.
Help

Reason given for failure:

    Origin checking failed - https://paperless.service.mydomain.de:50015 does not match any trusted origins.
    

In general, this can occur when there is a genuine Cross Site Request Forgery, or when Django’s CSRF mechanism has not been used correctly. For POST forms, you need to ensure:

    Your browser is accepting cookies.
    The view function passes a request to the template’s render method.
    In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
    If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
    The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.

You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.

You can customize this page using the CSRF_FAILURE_VIEW setting.`

PAPERLESS_ALLOWED_HOSTS is set to "paperless.service.mydomain.de" but makes no difference, as does setting to "*"

Message from container log:
`[2022-04-12 11:54:41,500] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless.service.mydomain.de:50015 does not match any trusted origins.): /accounts/login/`

### Expected behavior

Successful logon and showing start page of Paperless-ngx

### Steps to reproduce

1. Open page via reverse proxy address
2. Enter user and password
3. Error message appears

### Paperless-ngx version

1.7.0-rc1

### Host OS

Synology DSM

### Installation method

Docker

### Browser

Firefox & Edge

**Comment by cornettonuss** [comment]
I use HAProxy to terminate SSL in front of paperless and this is still working without any problem.

**Comment by gador** [comment]
Did you set PAPERLESS_URL?

What is your nginx config?

**Comment by WAdama** [comment]
@cornettonuss: You mean to get SSL? Not terminate, right?

@gador: PAPERLESS_URL was not necessary until now, with 1.6.0 all worked like a charme.

nginx config for paperless:
`    location ^~ / {
        proxy_pass http://<ip_of_nas>:8100/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        access_log /var/log/nginx/paperless.access.log;
        error_log /var/log/nginx/paperless.error.log;
        proxy_cache assets_zone;
        add_header X-Proxy-Cache $upstream_cache_status;
    }
`

**Comment by gador** [comment]
Please see https://github.com/paperless-ngx/paperless-ngx/pull/674

Since the update of Django, it now enforces the cross site origin.

Try setting PAPERLESS_URL to your domain

**Comment by WAdama** [comment]
@gador Your hint did it, setting just PAPERLESS_URL to my reverse proxy address cuts the knot and it works again.

Is this option missing in documentation? I at least couldn't find it...

**Comment by gador** [comment]
@WAdama :+1: 

I just had a look at our documentation. You are right. Since this feature is part of the `beta` and our documentation is refereed to `main` it wasn't updated yet. 

I have updated the docs to include `beta`.
If anyone wants to have a look, [here](https://paperless-ngx.readthedocs.io/en/beta/configuration.html) is the link.

**Comment by shamoon** [comment]
Thanks @gador 

Though I wonder if we should include a note about this at the top of the release notes as a lot of people are going to wonder if something broke. What does everyone think?

**Comment by gador** [comment]
@shamoon : absolutely :+1: Thanks!
