### ISSUE TITLE
[BUG] Websocket connection does not work when using PAPERLESS_FORCE_SCRIPT_NAME

### ISSUE THREAD

**Issue by mrichtarsky** [paperless-ngx/paperless-ngx#6980]
### Description

When PAPERLESS_FORCE_SCRIPT_NAME is set and paperless is accessed at `http://host/path` instead of `http://host`, websocket connections fail with `NS_ERROR_WEBSOCKET_CONNECTION_REFUSED` / `500 Internal server error` in Firefox

![websocket_failure](https://github.com/paperless-ngx/paperless-ngx/assets/15377781/d13cee5c-d9ce-42f1-89bd-f6d3c7deb206)

Without the subpath it works fine:

![websocket_success](https://github.com/paperless-ngx/paperless-ngx/assets/15377781/5630d9ed-1842-4692-a2c2-5db49bc885a3)

### Steps to reproduce

1. Set PAPERLESS_FORCE_SCRIPT_NAME=/paperless
2. Restart
3. Turn on Developer Tools
4. Go to http://host/paperless
5. Login
6. Observe failed request in Network tab of DevTools

### Webserver logs

```bash
No logs shown, did not find a way to enable higher debug levels
```

### Browser logs

```bash
See screenshots
```

### Paperless-ngx version

2.9.0

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### Browser

Firefox 126.0.1 (64-bit) Windows

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is a duplicate and just as before should be reported upstream.
