### ISSUE TITLE
[BUG] PDF cannot be printed under firefox (reopened)

### ISSUE THREAD

**Issue by homberger** [paperless-ngx/paperless-ngx#6985]
### Description

It is not possible to directly print pdf documents from the details page using Firefox.

This was reported before: https://github.com/paperless-ngx/paperless-ngx/issues/6130

**Using pdfjs provided by the browser (Firefox)**
The toolbar of the pdf viewer is visible, but the button to print the pdf document throws an error (NS_ERROR_FAILURE).
This seems to be a known bug of Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=941146
Maybe this workaround works for paperless: https://pdfjs.community/t/pdfjs-express-not-working-in-firefox/661/3

**Using pdfjs provided by paperless-ngx**
The toolbar of the pdf viewer is disabled. Paperless-ngx does not provide a button to print the pdf document.
 
Please consider 
a) enabling the toolbar of the pdfviewer provided by paperless-ngx or 
b) adding a button to print the document if the setting "Use PDF viewer provided by the browser" is disabled

@shamoon:
> I dont think this has anything to do with paperless, youre essentially opening the pdf in your browser

It's mostly a bug in Firefox or pdfjs, I guess. But it is possible to use a workaround in paperless-ngx to prevent it. 

### Steps to reproduce

Use Mozilla Firefox to open a pdf document in paperless-ngx (`/documents/<id>/details`).
Try to print the document opened in the pdf viewer without downloading it before.

### Webserver logs

```bash
-
```

### Browser logs

```bash
16:58:52.542 Uncaught NS_ERROR_FAILURE: 
    triggerPrinting resource://pdf.js/web/viewer.mjs:11635
    webViewerPrint resource://pdf.js/web/viewer.mjs:12041
    dispatch resource://pdf.js/web/viewer.mjs:1333
    bindListeners resource://pdf.js/web/viewer.mjs:10313
4 viewer.mjs:11635
    triggerPrinting resource://pdf.js/web/viewer.mjs:11635
    webViewerPrint resource://pdf.js/web/viewer.mjs:12041
    dispatch resource://pdf.js/web/viewer.mjs:1333
    bindListeners resource://pdf.js/web/viewer.mjs:10313
```

### Paperless-ngx version

2.9.0

### Host OS

-

### Installation method

Docker - official image

### Browser

Mozilla Firefox 126.0.1 

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Nothing about the above changes the previous assertion that this is not a paperless bug

**Comment by homberger** [comment]
> Nothing about the above changes the previous assertion that this is not a paperless bug

Debatable.

**Comment by stumpylog** [comment]
As before, the built in PDF viewer doesn't provide a print button, only the browser provided viewer would provide controls like that.  And given we're not the browser. failures in that viewer are not a paperless bug.

**Comment by homberger** [comment]
> And given we're not the browser. failures in that viewer are not a paperless bug.

Please do not reject this issue too fast. It might be a bug in paperless-lngx nonetheless. I am trying to help here - you know?

It is generally possible to print from embedded pdf documents with Firefox using the viewer provided by the browser. Do you agree?

But it fails in paperless-ngx. Propably because of the way the object tag (viewer container) is created. I consider this a bug.

**Comment by shamoon** [comment]
I see nothing unusual about how we embed use the <object> tag `<object [data]="previewUrl | safeUrl" type="application/pdf" class="preview-sticky" width="100%"></object>` and the error is thrown by the pdfjs that is bundled in Firefox, and as noted it works fine in other browsers. To me, this sounds like something that should be reported to Mozilla https://bugzilla.mozilla.org/home
