### ISSUE TITLE
[BUG] PDF preview require external Javascript

### ISSUE THREAD

**Issue by KiwiActinidia** [paperless-ngx/paperless-ngx#6988]
### Description

I'm using Paperless 2.9.0 and for  PDF preview it's requested to download a Javascript file from a CDN.
These are the 2 files in question pdf.worker.min  and js,pdf.min.js (angular UI)
Without internet access, from internal LAN network preview not available.

### Steps to reproduce

Use DevTools Console and Network Monitor
This is the link traced:
(https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/legacy/build/pdf.worker.min.js)

### Webserver logs

```bash
(https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/legacy/build/pdf.worker.min.js)
```

### Paperless-ngx version

2.9.0

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Firefox, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Strange, I do see thing.  Something must have changed in that dependency.  I'll our frontend dev sort it out.
