### ISSUE TITLE
[BUG] Paperless OpenID Connect redirect issue (wrong port used by paperless-ngx)

### ISSUE THREAD

**Issue by xy8000** [paperless-ngx/paperless-ngx#7003]
### Description

Hello together, 

i am facing issues with my paperless-instance after upgrading to the latest version today. For many months now i am using the OpenID-Feature successfully. After upgrading to the latest version i am facing some issues while getting redirected to my OpenID-Server (Keycloak). It seems, that paperless is using the wrong port to redirect me to Keycloak. 

**Current** Redirect-URL after clicking SSO-Button: `https://keycloak.[SUBDOMAIN].[DOMAIN].de:8080/[PATH]`
**Wanted** Redirect-URL after clicking SSO-Button: `https://keycloak.[SUBDOMAIN].[DOMAIN].de/[PATH]`

Paperless is redirecting me to port `8080`. This port is not mentioned in my openid-configuration provided by Keycloak. It seems, that paperless is extracting the port from the `PAPERLESS_SOCIALACCOUNT_PROVIDERS` in my dockerfile. Within that dockerfile i configured the `server_url` to `http://keycloak:8080/realms/master/.well-known/openid-configuration`. I need to configure it this way, because i am running docker and keycloak in different containers behind a traefik proxy. In my opinion paperless should use the openid-configuration in order to get the redirect-url to keycloak. The openid-configuration is not containing the port `8080`. Instead, the value `authorization_endpoint` is properly set to `https://keycloak.[SUBDOMAIN].[DOMAIN].de/realms/master/protocol/openid-connect/auth`. 

In order to reproduce the issue i appended the openid-configuration and the docker-compose-file: 

- [openid-configuration.txt](https://github.com/user-attachments/files/15847654/openid-configuration.txt)
- [docker-compose.txt](https://github.com/user-attachments/files/15847669/docker-compose.txt)

Setup:

1. paperless (docker) version [v2.9.0](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.9.0)
2. keycloak (docker) version [25.0](https://hub.docker.com/layers/keycloak/keycloak/25.0/images/sha256-750ef04254aa65df3a900e0ff1d064e6e85400c4b6ca71d2d4b9727cca306d7b?context=explore)

_(Both instances are running behind a traefik-proxy (docker) version v2.11)_

Hardware:

- RaspberryPi 5 'arm 64'

I am enjoying the paperless openid-feature. Unfortunately it cannot be used with this behavior. I couldn't identify any issue in my setup. Maybe there's anyone out there that can proof me wrong or reproduce it locally.

### Steps to reproduce

1. Configure Paperless with Keycloak using OpenID in Docker as described in the BUG
2. Klock SSO-Button in order login

### Webserver logs

```bash
Nothing problem-related detected.
```

### Browser logs

```bash
HTTP/2 302 
access-control-allow-origin: https://paperless.[SUBDOMAIN].[DOMAIN].de
content-language: en-us
content-type: text/html; charset=utf-8
cross-origin-opener-policy: same-origin
date: Sat, 15 Jun 2024 12:16:32 GMT
location: http://keycloak.[SUBDOMAIN].[DOMAIN].de:8080/realms/master/protocol/openid-connect/auth?client_id=paperless&redirect_uri=https%3A%2F%2Fpaperless.[SUBDOMAIN].[DOMAIN].de%2Faccounts%2Foidc%2Fkeycloak%2Flogin%2Fcallback%2F&scope=email+openid+profile&response_type=code&state=[STATE]
referrer-policy: same-origin
server: uvicorn
set-cookie: sessionid=[SESSION_ID]; expires=Sat, 29 Jun 2024 12:16:32 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax
vary: Accept-Language, origin, Cookie
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
content-length: 0
X-Firefox-Spdy: h2
```

### Paperless-ngx version

v2.9.0

### Host OS

RaspberryPi 5 'arm64'

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.9.0",
    "server_os": "Linux-6.6.28+rpt-rpi-2712-aarch64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 527162417152,
        "available": 275435302912
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "account.0009_emailaddress_unique_primary_email",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-15T00:00:38.057073+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-15T12:05:06.886692Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox, Crhome

### Configuration changes

Upgrading to the latest version

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Oidc is fully handled by Django allauth.  I suggest creating a discussion or issue on their repository for help configuring.

**Comment by stumpylog** [comment]
https://github.com/pennersr/django-allauth/discussions

**Comment by xy8000** [comment]
Wasn't aware of that. Thank you for mentioning @stumpylog

Posted a discussion as proposed: https://github.com/pennersr/django-allauth/discussions/3900
