### ISSUE TITLE
[BUG] Unable to parse ICU expression for lang no-NO.

### ISSUE THREAD

**Issue by Frikk** [paperless-ngx/paperless-ngx#7030]
### Description

When display language is set to Norwegian, there seems to be an error parsing a localized text in the File Tasks panel.

### Steps to reproduce

1. Set Display Language to Norwegian.
![displaylang_norwegian](https://github.com/paperless-ngx/paperless-ngx/assets/10959605/15adb737-5665-4874-b3d0-0d133398074e)
3. Navigate to File Tasks
4. Click on "Complete" tab
5. Observe error from main.js in browser log.
![error](https://github.com/paperless-ngx/paperless-ngx/assets/10959605/9e07acd5-e991-4a59-aec3-db3caf7cbbbe)

### Webserver logs

```bash
See Browser logs.
```

### Browser logs

```bash
ERROR Error: Unable to parse ICU expression in "{�0�, plural, =1 {En �1� oppgave} other {�2� totalt�1� oppgaver}}}"/>" message.
```

### Paperless-ngx version

2.10.1

### Host OS

Linux-6.1.79-Unraid-x86_64-with-glibc2.36

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
The fix for this will be at crowdin: https://crowdin.com/editor/paperless-ngx/16/en-no?view=comfortable&filter=basic&value=0#q=plural
