### ISSUE TITLE
[BUG] When adding a pdf document, not all embedded fonts are preserved.

### ISSUE THREAD

**Issue by goebeler** [paperless-ngx/paperless-ngx#7031]
### Description

I just noticed that some of my documents are unreadable after downloading. The problem only exists with documents which were not scanned but added as a pdf document. The archived version does not contain all of the embedded fonts the original contained and is not readable if the font is missing on a viewer's computer.

I notived this when downloading some banking documents which used a "Frutiger" font that's not freely available. In the original document, two variants of said font are embedded in the document. In the archived version, only one variant is still embedded.

Here some screenshots from evince's font tab, left side is the archived pdf, right side is the original:

![image](https://github.com/paperless-ngx/paperless-ngx/assets/8701639/d4cac440-2fb1-47eb-ba09-b3e3b7119e53)

### Steps to reproduce

1. Upload a document wih multiple embedded fonts.
2. Download the archived pdf of the document.
3. Open in pdf viewer.

### Webserver logs

```bash
I dont have the logs anymore, the relevant files were uploaded months ago.
```

### Paperless-ngx version

v2.2.1

### Host OS

Docker image on Archlinux host

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
From the report template you just filled out:

> Paperless-ngx does not perform OCR itself, that is handled by other tools. Problems with OCR of specific files should likely be raised 'upstream', see https://github.com/ocrmypdf/OCRmyPDF/issues or https://github.com/tesseract-ocr/tesseract/issues

Also, fyi, the original file is unchanged, the archive version is what we’re talking about above

**Comment by goebeler** [comment]
There should be no OCR involved here, so I don't see the point in reporting this with either tesseract or myocr?

**Comment by shamoon** [comment]
The pdf/a archive file gets created by ocrmypdf. You can look through their docs / issues about font embedding
