### ISSUE TITLE
[BUG] Error occurred while consuming document

### ISSUE THREAD

**Issue by portalninja2** [paperless-ngx/paperless-ngx#7035]
### Description

After an Upload of a PDF i get this error: 
Error occurred while consuming document SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.

Every Single TIME. But only with a few Documents. 
I dont knwo whats wrong..

Paperless Version: [Paperless-ngx 2.10.1]

Because of privacy, i cant upload a Document. All of them are papers by my Doctor.

### Steps to reproduce

Upload one of the Documents

### Webserver logs

```bash
Error occurred while consuming document SubprocessOutputError: Ghostscript rasterizing failed. See logs for more information.
```

### Paperless-ngx version

2.10.1

### Host OS

Ubuntu

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Problems with particular PDFs happen and are not something we are able to assist with, particularly without a sample file and complete logs.

This generally indicates a malformed PDF from the source.  If you search other issues, there are suggestions for resolution, but this is not a bug.
