### ISSUE TITLE
[BUG] version.json not being produced by document_exporter anymore

### ISSUE THREAD

**Issue by esticle** [paperless-ngx/paperless-ngx#7044]
### Description

When Upgrading from 2.9.0 to 2.10.1 I noticed that document_exporter is no longer producing a version.json file.
If this is intentional I did not pick this up as a change in the release log.

### Steps to reproduce

Run version 2.10.1:
```
root@061ddfe73f7c:/usr/src/paperless/src# document_exporter ../export
You have configured mail accounts, but no passphrase was given. Passwords will be in plaintext
100%|███████████████████████████████████████████████████████████████████████████████| 2616/2616 [00:06<00:00, 434.18it/s]
root@061ddfe73f7c:/usr/src/paperless/src# date
Thu Jun 20 11:03:14 UTC 2024
root@061ddfe73f7c:/usr/src/paperless/src# ls -al ../export/version.json 
-rw-r--r-- 1 paperless paperless 24 Jun 19 05:05 ../export/version.json
root@061ddfe73f7c:/usr/src/paperless/src# cat ../export/version.json 
{
  "version": "2.9.0"
}
```

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.10.1

### Host OS

Unraid/slackware

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is intentional and not a nug
