### ISSUE TITLE
[BUG] Filtering ONLY with a year results in object error

### ISSUE THREAD

**Issue by github-cli** [paperless-ngx/paperless-ngx#706]
### Description

trying to filter by date and only manually entering part of the date results in an error during the search which doesnt explain that the date was entered incorrectly.
This seems to only happen if only the year is given without other search criteria, if I also enter a keyword, it works fine

### Expected behavior

If I enter to search documents before "2020", I expect it to search for anything before 2020-01-01
If I enter to search for documents after "2020", I expect it to search for anything after 2020-12-31

### Steps to reproduce

1.) search only for the year 2.) =errorè
1.) search for only the year AND a common keyword 2.) no error, works fine

### Paperless-ngx version

1.6.0

### Host OS

Ubuntu 20.04

### Installation method

Docker

### Browser

Chrome

**Comment by shamoon** [comment]
Thanks, happily I can confirm this is fixed by #616 in v1.7.0, see below:
<img width="530" alt="Screen Shot 2022-04-12 at 12 17 17 PM" src="https://user-images.githubusercontent.com/4887959/163037094-2ab378f2-d1d3-4984-87b8-e47777ca7dbc.png">

**Comment by github-cli** [comment]
just wondering but why not let us enter just a year? in 1.6.0 it works as long as you provide another keyword as well... which is nicer!!

**Comment by shamoon** [comment]
Ah, so I see what you’re saying about how it works with a keyword, it’s not just the error display issue. I’ll look when I can

**Comment by shamoon** [comment]
I dont think this is any different in 1.7.0 vs 1.6.0 (which would make sense), in either case this only works with "advanced search" (see below). Either way its something deep in the API that would have to be looked into. I agree its a bit odd but Im not sure its fair to call this a "bug" (the error display is but again thats fixed) so I would rather call this a feature request (basically, allow just the year). If thats something you'd like to see please feel free to open a FR for it, in this case Im gonna close this for now, thanks.

<img width="1002" alt="Screen Shot 2022-04-12 at 3 07 00 PM" src="https://user-images.githubusercontent.com/4887959/163062689-f77224c1-b559-413a-b179-aab557915ba5.png">
