### ISSUE TITLE
[BUG] text in Tags should be white in dark mode.

### ISSUE THREAD

**Issue by miku323** [paperless-ngx/paperless-ngx#707]
### Description

Tags text is dark in dark mode when adding or selecting tags in open documents

### Expected behavior

Text should be white.

### Steps to reproduce

1. edit document
2. add tags or esel tags
3. tag text is black

### Screenshots

![image](https://user-images.githubusercontent.com/5058121/163038628-77a7e3fc-c413-434b-a9a9-965ee1d01f2e.png)

### Paperless-ngx version

1.7.-rc1

### Host OS

Linux/Unraid

### Installation method

Docker

### Browser

Chrome

### Configuration changes

/

### Other

/

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/64e1a6ec7ec348304cbf4aa7cc9458578c66770c
