### ISSUE TITLE
[BUG] Bulk updating documents does not update "modified" attribute

### ISSUE THREAD

**Issue by LeoKlaus** [paperless-ngx/paperless-ngx#7070]
### Description

When removing tags (I haven't checked other operations) in bulk, i.e. selecting multiple documents in the list and removing a tag, the "modified" attribute of these documents is not updated.

### Steps to reproduce

1. Go to Documents
2. Select at least one document
3. Edit any of its attributes using the top bar and click "Apply"
4. Check the "modified" date for that document in the API

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.10.1

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.1",
    "server_os": "Linux-5.15.0-1046-oracle-aarch64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 48277495808,
        "available": 2828447744
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-23T11:56:07.718703+02:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thanks for reporting
