### ISSUE TITLE
[BUG] Bad visibility of logo and other icons when using lighter colors in dark mode

### ISSUE THREAD

**Issue by miku323** [paperless-ngx/paperless-ngx#708]
### Description

Bad visibility of logo and other icons when using lighter colors in dark mode. Color in picture is #e39296. Similar to #c9b3e6.
Text is in gray so the visibility is not so good. Same goes for Save button in settings. 

### Expected behavior

Text should maybe be a little darker for logo or some kind of background. Or maybe apply same rule for those items as for tags?

### Steps to reproduce

1. select lighter color in theme color

### Webserver logs

```bash
/
```

### Screenshots

![image](https://user-images.githubusercontent.com/5058121/163039637-4026ad39-6c29-4f74-8ea4-e59de823a586.png)
![image](https://user-images.githubusercontent.com/5058121/163040103-340960a9-488e-40f1-a07c-1e7509fcf072.png)

### Paperless-ngx version

1.7.0-rc1

### Host OS

Linux/Unraid

### Installation method

Docker

### Browser

Chrome

### Configuration changes

/

### Other

/

**Comment by miku323** [comment]
Would like to add that even some checkmarks are not visible
![image](https://user-images.githubusercontent.com/5058121/163040627-0e70e5d0-e361-40bf-a9a4-9bece1fd22cb.png)
![image](https://user-images.githubusercontent.com/5058121/163040642-39947cd0-4e91-4503-8431-436813e05813.png)

**Comment by miku323** [comment]
Oh and notifications
![image](https://user-images.githubusercontent.com/5058121/163041617-d69420e4-3dc4-4a3a-bd87-a9f29400966c.png)

**Comment by shamoon** [comment]
Sorry but you’re saying when you set your own theme color? Hmm, I’m not sure how much we can deal with this, like if the users wants to choose a light color perhaps they should just set the app to light mode, and vice versa. Based on how this works I’m concerned about how much it would take to “correct” for what is essentially a user choice.

**Comment by miku323** [comment]
Yeah, that is true, I guess. Maybe a disclaimer, just? That there might be bad visibility with some colors?

**Comment by qcasey** [comment]
Here on GitHub the color of the label's text changes based on the label's color, to increase contrast. I think it's done something like this:

https://github.com/dwyl/tudo/issues/202

I'm not saying it's worth doing or not, just that if we wanted we could compute the optimal \#000 / \#fff for contrast.

**Comment by shamoon** [comment]
Challenge accepted 👊

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/b4570545ef2184bb03be946bf9fd9c8797bebd8c
