### ISSUE TITLE
[BUG] Android home screen shortcut wrong background color 

### ISSUE THREAD

**Issue by ThisIsCyreX** [paperless-ngx/paperless-ngx#7093]
### Description

The "app" icon on my android homescreen has the wrong background color.
LineageOS, Mozilla Firefox, add Paperless-Web as Homescreen-Shortcut adds this icon:
![green-on-green](https://github.com/paperless-ngx/paperless-ngx/assets/13767589/784e3c8e-de4a-492a-9f0e-5d78da8e694b)
(green leaf on green background).

### Steps to reproduce

1. Open Paperless web in Mozilla Firefox on Android (Lineage OS, in my case).
2. Three dots -> Add to Home Screen
3. Any name. Press add (here is the favicon correct)
![add-home](https://github.com/paperless-ngx/paperless-ngx/assets/13767589/ecfbb435-8ea4-41a5-94ca-5a73f3a0928e)
4. Now I can drag the icon to the home screen or press the button:
![green-on-green](https://github.com/paperless-ngx/paperless-ngx/assets/13767589/784e3c8e-de4a-492a-9f0e-5d78da8e694b)
5. Icon on home screen:
![homescreen](https://github.com/paperless-ngx/paperless-ngx/assets/13767589/a576cad6-7027-43e3-bb7b-40861eb97844)

### Webserver logs

```bash
no issues here
```

### Paperless-ngx version

2.10.2

### Host OS

Linux Mint 21.3

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.2",
    "server_os": "Linux-5.15.0-112-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 431755706368,
        "available": 68686262272
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-25T00:00:48.420397+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-24T23:05:04.696517Z",
        "classifier_error": null
    }
}
```

### Browser

Android, Mozilla Firefox 127.0.1

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Sure does seem like a Lineage OS or FF bug.

All we provide, which has been the case for quite some time now, is 

```
  <meta name="theme-color" content="#17541f" />
...
  <link rel="apple-touch-icon" href="apple-touch-icon.png">
```

https://github.com/paperless-ngx/paperless-ngx/blob/dev/src-ui/src/apple-touch-icon.png

You can ask them why the icon comes up as a green circle in a white box with a green overlay, it's not the icon we provide as you can see. Also note that there is very limited support for control over what happens with `theme-color`.

This is Android on a Galaxy using FF:
<img width="675" alt="Screenshot 2024-06-24 at 5 08 54 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/840753bd-f088-4df1-a78c-0bd83a460632">

Or a Google Pixel:
<img width="578" alt="Screenshot 2024-06-24 at 5 10 06 PM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/d5c907f0-0879-4305-a30f-822cbb48efef">

So as you can see, they handle it differently but at least they use our actual icon.

**Comment by shamoon** [comment]
If you do get an answer from eg the Lineage devs feel free to let us know
