### ISSUE TITLE
[BUG] Paperless doesn’t detect day number in case of accented month name in french language

### ISSUE THREAD

**Issue by fdubuy** [paperless-ngx/paperless-ngx#7099]
### Description

When french language is set, some dates are not detected correctly in uploaded documents. They are detected as the first of the month, regardless of the day number written in the document.
I notice this happens when dates are in "j F Y" format, like "13 décembre 2023" or "15 août 1967", and only with dates in February, August an December, which are the only months with accented characters in french language.

### Steps to reproduce

1. Install paperless-ngx via docker compose
2. Set language to french in parameters
3. Upload a pdf that contains a date with accented month name in , e.g. "13 décembre 2023"
4. Observe that the suggested date is "01/12/2023" instead of "13/12/2023". 

### Webserver logs

```bash
I don’t know where to find them. I have a local installation on my computer, not a remote server.
```

### Paperless-ngx version

2.10.1

### Host OS

Solus OS x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.1",
    "server_os": "Linux-6.8.12-293.current-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 983358451712,
        "available": 110041489408
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-06-25T17:14:39.434258+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-06-25T15:07:53.686776Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is at best a feature request.  All date suggestions are just that, suggestions, with a best effort attempt to locate "date like" things in the content.  Not locating something one thinks is a date is not a bug, it just didn't look like a date or couldn't be parsed by [dateparser](https://dateparser.readthedocs.io/en/latest/) to a date.

You're welcome to examine the regular expressions and make suggestions:
https://github.com/paperless-ngx/paperless-ngx/blob/f3b7ae93f0efa7e78c986162a964f3feb4e30aa2/src/documents/parsers.py#L39-L47
