### ISSUE TITLE
Can't log in due to CSRF verification failed.

### ISSUE THREAD

**Issue by reese2310** [paperless-ngx/paperless-ngx#710]
### Description

I can get to log in screen but when logging in, I get the "Forbidden 403, CSRF verification failed. Request aborted." error.

I have tried clearing cookies, cache, chrome and firefox with same issue.  I am able to sign in via the Android app and using the IP address on a network machine. 

I use nginx proxy manager and my own domain.  It worked this morning, then suddenly stopped.  I have been using the current setup for a month or so with no issues.

Any help would be appreciated.

### Expected behavior

Typical behavior is being able to log in.

### Steps to reproduce

Go to paperless.xxxxxxx.com
Enter log in information
get error

### Webserver logs

```bash
[2022-04-12 12:42:56,708] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless.xxxx.com does not match any trusted origins.): /accounts/login/
```

### Paperless-ngx version

released unraid version, no beta version

### Host OS

Unraid

### Installation method

Docker

### Browser

Chrome, Firefox

### Configuration changes

zero changes

**Comment by reese2310** [comment]
I searched Open issues and didn't see anything.  I just searched the closed items and did find some similar issues.  I will report back if can't get it fixed.

**Comment by miku323** [comment]
Which unraid package are you using linuxserver or any other?

**Comment by qcasey** [comment]
See #674, `PAPERLESS_URL` conf variable must be set when using a reverse proxy. 

You're likely using the current beta version that was accidentally tagged as `latest` this morning. Is there somewhere on the web describing unraid's release strategy? It's completely foreign to me.

**Comment by reese2310** [comment]
This is the package I have been using.

![Capture](https://user-images.githubusercontent.com/97763200/163048100-afffc672-7d8e-47b6-b4c6-c2b4e2b01b7c.PNG)

**Comment by miku323** [comment]
You can add variable mentioned above `PAPERLESS_URL` or try to force update with `ghcr.io/paperless-ngx/paperless-ngx:latest` just so you go back to version 1.6.0
If you add variable, here is a picture for help
![image](https://user-images.githubusercontent.com/5058121/163048496-11570da5-cb5c-40ea-9b35-1dcee7b9ba23.png)

**Comment by miku323** [comment]
Without last / in url

**Comment by reese2310** [comment]
I added the new variable and everything is back up and running.  I appreciate the promptness of replies!

**Comment by qcasey** [comment]
This is a pretty big breaking change, we may need to make an announcement post on release. @miku323 I'd like to use your screenshot to help guide unraid users if that's OK?

**Comment by miku323** [comment]
> This is a pretty big breaking change, we may need to make an announcement post on release. @miku323 I'd like to use your screenshot to help guide unraid users if that's OK?

Sure. Here use this one:
![image](https://user-images.githubusercontent.com/5058121/163049546-c0c083d5-f20e-4240-8df6-d339bce90129.png)

**Comment by qcasey** [comment]
Thank you!

**Comment by qcasey** [comment]
Closing for visibility in #712
