### ISSUE TITLE
[v1.7] Your `CSRF verification failed`, reverse proxy not working?

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#712]
# 1.7.0 Breaking Change: `PAPERLESS_URL`

If you're behind a reverse proxy, the configuration variable `PAPERLESS_URL` needs to be set. See the [Documentation](https://paperless-ngx.readthedocs.io/en/beta/configuration.html#hosting-security) about this variable to determine the correct value, typically it will just be your domain (i.e. `https://paperless.xxxx.com`).

Please remember to **not add** the trailing slash (`https://paperless.xxxx.com/`).

#674 explains why we needed to make this change. 

## Docker

Edit your `docker-compose.env` and add this variable.

```env
PAPERLESS_URL=https://paperless.xxxx.com
```

Then force recreate your container (`docker compose up -d --force-recreate`).

## Unraid

Add this variable similarly to the screenshot below.

- **Name/Key:** `PAPERLESS_URL`
- **Value:** `https://paperless.xxxx.com`

![unraid](https://user-images.githubusercontent.com/1429672/163052410-184821cd-d049-4eed-a329-d0f009150955.png)

## Bare Metal

Add/Edit this variable in your `paperless.conf`:

```env
PAPERLESS_URL=https://paperless.xxxx.com
```

Then restart paperless-ngx.

**Comment by qcasey** [comment]
I think we should leave this for several days after the 1.7.0 release.

**Comment by auanasgheps** [comment]
Thankfully was an easy fix, my legs started to shake when I saw the CSRF error. 

I had a similar problem with TandoorRecipes https://github.com/TandoorRecipes/recipes/issues/959 which took a lot of investigation to fix, but thankfully Paperless-ngx happily accepted the new variable.

Please add it to the .env / docs! I searched and is not yet there!

**Comment by qcasey** [comment]
> Please add it to the .env / docs! I searched and is not yet there!

The variable is [in the beta-branch of the docs](https://paperless-ngx.readthedocs.io/en/beta/configuration.html#hosting-security), although we should add this note to the [nginx config docs](https://paperless-ngx.readthedocs.io/en/beta/setup.html#using-nginx-as-a-reverse-proxy) as well. I'll do that now.

It was also added to the install script and example `.env` for any new installs in https://github.com/paperless-ngx/paperless-ngx/commit/ca0e86757b965dee26ba9b5d62328f3b9326cfbe

**Comment by cl445** [comment]
Do any of you have a working configuration for Traefik as a reverse proxy? The documentation does only contain a configuration for Nginx.

**Comment by cl445** [comment]
@shamoon Thanks, but this is not the problem. I had a working installation with traefik for v1.6, but the CSRF-verification breaks it in v1.7 .  
I was hoping that someone else has already done the necessary adjustments for traefik and is willing to share his configuration.

**Comment by zemsten** [comment]
> 

I'm running into the exact same issue. CSRF fail despite the new environment variable.

**Comment by zemsten** [comment]
> > @shamoon Thanks, but this is not the problem. I had a working installation with traefik for v1.6, but the CSRF-verification breaks it in v1.7 .
> > I was hoping that someone else has already done the necessary adjustments for traefik and is willing to share his configuration.
> 
> ~I'm running into the exact same issue. CSRF fail despite the new environment variable.~

Nevermind. I made a stupid error. The environment variable does work properly with my Traefik setup. @cl445 not sure what you're running into here.

**Comment by morremeyer** [comment]
Thanks for the good documentation! 

As this has been noted as a breaking change, but the major version number has not been bumped, I’m curious as to what we regard as the public API that the versioning is based on?

If we see „the software can be used to archive and retrieve documents“ as the public API (which I think is what we should do and what this being noted as breaking changes suggests), this version bump should have been to `2.0.0`, not to `1.7.0` as per semver specification.

I can also make this a separate issue if we want to discuss this at more length.

**Comment by qcasey** [comment]
> Is there a specific reason for deciding against that?

Paperless' backend API, which serveral apps and scripts depend upon, is unaffected by this change. Personally that's what I have in mind when versioning, although we work as a team and our group semver strategy has not been explicitly defined. We can discuss in a new issue if that should be changed.

**Comment by llexaxell** [comment]
I use synology reverse proxy and I get the same error :
[2022-05-02 00:29:53,093] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://xxxxx/ does not match any trusted origins.): /accounts/login/

I already added PAPERLESS_URL env variable and I didn't add the trailing slash.

**Comment by shamoon** [comment]
> I already added PAPERLESS_URL env variable and I didn't add the trailing slash.

`PAPERLESS_URL` is pretty much just an alias for `CSRF_TRUSTED_ORIGINS` (And a couple others), if neither of those settings work then I would guess there is a reason that is not a “bug”, like either your setup is stripping the header, it’s set incorrectly etc. `CSRF_TRUSTED_ORIGINS` is a core Django setting so I imagine it is working various environments but likely some need tweaking. It’s hard to know how to diagnose these issues when it works for others and there’s not a clear cause, of course we can’t test every possible deployment setup. We would welcome any further detail.

**Comment by schlaggi** [comment]
In `CSRF_TRUSTED_ORIGINS` I'd be able to have multiple Domains with `['first.domain.com','second.domain.com']`, but that seems to not be possible with `PAPERLESS_URL`. Has anybody else tried this?

**Comment by shamoon** [comment]
> In `CSRF_TRUSTED_ORIGINS` I'd be able to have multiple Domains with `['first.domain.com','second.domain.com']`, but that seems to not be possible with `PAPERLESS_URL`.

You are correct, thats why the [documentation ](https://paperless-ngx.readthedocs.io/en/latest/configuration.html#hosting-security) notes that `PAPERLESS_CSRF_TRUSTED_ORIGINS`, `PAPERLESS_ALLOWED_HOSTS` `PAPERLESS_CORS_ALLOWED_HOSTS` are all still available if you need more advanced settings

**Comment by Romanicus** [comment]
Setting the PAPERLESS_URL works for me, but instead of simply restart the docker-compose as it is told in the documentation (docker compose up -d) I had to start the containers again with recreation (docker compose up -d --force-recreate). This does the trick at my installation.

**Comment by qcasey** [comment]
> I had to start the containers again with recreation (docker compose up -d --force-recreate). This does the trick at my installation.

Thank you, I've edited that into the OP

**Comment by llexaxell** [comment]
> I use synology reverse proxy and I get the same error : [2022-05-02 00:29:53,093] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://xxxxx/ does not match any trusted origins.): /accounts/login/
> 
> I already added PAPERLESS_URL env variable and I didn't add the trailing slash.

I change the reverse proxy configuration and it works !

**Comment by 10of12** [comment]
What did you changed on the Synology reverse proxy configuration?
I tired the settings from the Docs -> https://paperless-ngx.readthedocs.io/en/beta/setup.html#using-nginx-as-a-reverse-proxy
But it is not working. The PAPERLESS_URL variable is already set

**Comment by 10of12** [comment]
Try changing the PAPERLESS_URL to https://cloud.xxx-xxx.de:8770 
This is what worked for me. Also Synology with the internal reverse proxy

**Comment by simonkurka** [comment]
@stfnx I think this is more related to #817 

I compared the response headers when removing a tag with the login page. The login page doesn't set the `access-control-allow-origin` header. I didn't figure out yet, why this leads to `Origin: null`, but at least Google Chrome behaves in this way. When the `access-control-allow-origin` is set in the response headers the `Origin` ist also set in the request.

@shamoon I feel like this better fits in #817, but it's closed. What is your suggestion? New issue? Reopen #817?

**Comment by simonkurka** [comment]
I removed `add_header Referrer-Policy "no-referrer" always;` which solved the issue, but I think the `access-control-allow-origin` header should still be set on the login page.

**Comment by diesl** [comment]
> Then force recreate your container (docker compose up -d --force-recreate).

This has cost me 2 hours of searching why my settings did not work.
IMHO, this is missing in the documentation?

**Comment by egodigitus** [comment]
Was running paperless on proxmox within a LXC container.  
Setting PAPERLESS_URL=https://paperless.sub.domain.tld within /opt/paperless/paperless.conf worked for me.  
Important: Restart the LXC container!

**Comment by onjour** [comment]
> > I use synology reverse proxy and I get the same error : [2022-05-02 00:29:53,093] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://xxxxx/ does not match any trusted origins.): /accounts/login/
> > I already added PAPERLESS_URL env variable and I didn't add the trailing slash.
> 
> I change the reverse proxy configuration and it works !

Would you mind telling what did you change in the reverse proxy configuration exactly?

**Comment by flemmingss** [comment]
I have this problem also, I can't get it to work. (Using HAProxy on pfSense as reverse proxy)
I can access the login page, but after that I get `Forbidden (403) CSRF verification failed. Request aborted`

Log:

`
[2023-03-11 21:29:22,678] [WARNING] [django.security.csrf] Forbidden (Origin checking failed - https://paperless-ngx.mydomain.top does not match any trusted origins.): /accounts/login/
`

with:  `-e 'CSRF_TRUSTED_ORIGINS'='10.0.24.10,paperless-ngx.mydomain.top,https://paperless-ngx.mydomain.top'`
