### ISSUE TITLE
Nutzer Anmeldung funktioniert nicht mehr

### ISSUE THREAD

**Issue by totocotonio** [paperless-ngx/paperless-ngx#7131]
### Description

Hi,
ich habe gerade festgestellt, dass sich User nicht mehr anmelden können.
Leider kann ich nicht genau sagen, seit wann das ist.

Ich habe die Version 2.10.2

Der Superuser funktioniert.

### Steps to reproduce

Nicht reproduzierbar

### Webserver logs

```bash
Keine sichtbar
```

### Browser logs

```bash
Keine
```

### Paperless-ngx version

2.10.2

### Host OS

Docker Container unter Nas

### Installation method

Docker - official image

### Browser

Firefox, chrome usw.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by OverDodo** [comment]
Es fehlt wahrscheinlich die ui_settings Berechtigung
