### ISSUE TITLE
[BUG] Document importer not recognizing existing files

### ISSUE THREAD

**Issue by p3l1** [paperless-ngx/paperless-ngx#7137]
### Description

Hello,

when importing an existing backup with the document importer, the importer fails and complains that one of my documents is missing. My plan was to import using 2.4.1 first and then performing an upgrade to the latest version.

<img width="1489" alt="Bildschirmfoto 2024-06-30 um 19 49 42" src="https://github.com/paperless-ngx/paperless-ngx/assets/66635816/f1f4d5da-9c4e-4b06-81b4-ea13e7b2fc59">

As you can see in the screenshot, the file is available and I am gussing it has something todo with the chosen filename, maybe? The backup was created with document_exporter default settings and the filenames match the current pattern like its described in the docs.

I also tried importing the backup using the newest version 2.10.2, since the importer behaviour has been changed a bit, but wasn't successful, resulting in the same error messages.

The container is running within my kubernetes cluster, but the error occurs within paperless itself and should not be affected by the current installation method. I am using [this](https://github.com/CrystalNET-org/helm-paperless-ngx/blob/main/chart/values.yaml) helm chart which uses the official docker image.

### Steps to reproduce

1. Create an export using the document_exporter in 2.4.1
2. Try importing the backup directory in 2.4.1 or 2.10.2

It fails with the default export filename pattern.

### Webserver logs

```bash
None.
```

### Browser logs

```bash
None.
```

```
{
    "pngx_version": "2.10.2",
    "server_os": "Linux-6.1.0-21-amd64-x86_64-with-glibc2.36",
    "install_type": "kubernetes",
    "storage": {
        "total": 492146208768,
        "available": 445392547840
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "socialaccount.0006_alter_socialaccount_extra_data",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://paperless-redis-headless:6379",
        "redis_status": "ERROR",
        "redis_error": "Error connecting to redis, check logs for more detail.",
        "celery_status": "ERROR",
        "index_status": "OK",
        "index_last_modified": "2024-06-30T17:44:40.612498Z",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": null,
        "classifier_error": null
    }
}
```
I am still working things out with redis. From what I've seen, it should not affect the import, should it?

### Configuration changes

Only common options for db connection etc. used so far.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please have a search, there are existing issues and discussions about this. It’s related to the umlaut and the file system encoding, there doesn’t seem to be much we can do on the paperless side
