### ISSUE TITLE
[BUG] Deleting a document doesn't work properly

### ISSUE THREAD

**Issue by hgschehl** [paperless-ngx/paperless-ngx#7163]
### Description

When I upload a new document and delete it immediately afterwards it is only "deleted" in the frontend. The file remains in the "media/originals" directory and is not moved to the configured trash dir.
I also think this is the cause of #7071 (I added a comment there before I saw that this was already closed): If the file is neither removed from the media directory nor the database itself it seems logic to be marked as duplicate because its cheksum remains in the database....

It worked in several versions before 2.10.2, but I cannot say in which version it started not to work.

### Steps to reproduce

[1. Upload a file via the consumer directory (for me it's then tagged normally and also with an INBOX-Tag)]-->seems to affect also older files! 
2. view details of the file in web frontend
3. click the delete-button and confirm

### Webserver logs

```bash
no relevant entries regarding the deletion, neither error message nor confirmation at all
```

### Paperless-ngx version

2.10.2

### Host OS

Ubuntu, x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.2",
    "server_os": "Linux-5.4.0-150-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 5952756088832,
        "available": 392332460032
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-04T23:07:18.084704+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-04T21:05:03.696418Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Configuration changes

no change since former working version...

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please read the release notes, that’s precisely how the trash works
