### ISSUE TITLE
[BUG] CSRF failed with PAPERLESS_AUTO_LOGIN_USERNAME

### ISSUE THREAD

**Issue by odelseth** [paperless-ngx/paperless-ngx#7173]
### Description

When using the PAPERLESS_AUTO_LOGIN_USERNAME feature to log in with a non-staff user, I receive a "CSRF Failed: CSRF cookie not set." 403 error, when doing a POST to the API.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/4722139/8e648452-e055-4758-96c4-9ff793dbbca1)

I've experienced this bug on my local machine, using the standard development environment on http://localhost:4200, and CSRF_USE_SESSIONS=False (so that CSRF token is stored in cookies).

PAPERLESS_CSRF_TRUSTED_ORIGINS contains http://localhost:4200, so it's not an origin issue.

When uploading a new document, a POST request is sent to /api/documents/post_document/. The X-Csrftoken is posted in the headers, but no cookie is received in the backend.

Then, Django's CsrfViewMiddleware checks that a value exists in the cookie, and raises RejectRequest(REASON_NO_CSRF_COOKIE) because the csrftoken key does not exist.

This is done in [_get_secret() function](https://github.com/django/django/blob/446cdab13485e99939f06b74c563d5bb992330b2/django/middleware/csrf.py#L245) of CsrfViewMiddleware. Additionnally, it also double check that the cookie token matches the header token, prevent csrf validation and reject the POST request.

There is a simple workaround to solve this issue by adding:

    if not settings.CSRF_USE_SESSIONS and (request_csrf_token := request.META.get(settings.CSRF_HEADER_NAME)):
        request.COOKIES[settings.CSRF_COOKIE_NAME] = request_csrf_token

in [paperless.auth.AutoLoginMiddleware](https://github.com/paperless-ngx/paperless-ngx/blob/0deb8a11d6f3c08a5cb37ad282450093a480913e/src/paperless/auth.py#L20)

### Steps to reproduce

1. In paperless.conf, set PAPERLESS_AUTO_LOGIN_USERNAME to a user that is not a staff user, nor an admin.
2. Remove all staff users from the DB, so that AngularApiAuthenticationOverride does not auto logs with that user.
3. set CSRF_USE_SESSIONS to False (this is the default)
4. Go to the dashboard and upload a new document

### Webserver logs

```bash
N/A
```

### Browser logs

```bash
"CSRF Failed: CSRF cookie not set."
```

### Paperless-ngx version

2.10.2

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

### Browser

Chrome, Firefox

### Configuration changes

PAPERLESS_AUTO_LOGIN_USERNAME

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This hasn't changed for a very long time and PAPERLESS_AUTO_LOGIN_USERNAME is not really meant to be used in any production scenario, so Im not sure what the goal is here. And http://localhost:4200/ is the angular dev frontend which is why AngularApiAuthenticationOverride is involved at all.

Im not clear that it needs to change, but I would leave the verdict on the changes above to the backend team.

**Comment by odelseth** [comment]
It's certainly not a much-used feature, but it can gave some headache the first time one try to connect locally with a non-staff user.

Indeed, it's only useful during local development/testing in a multi-user scenario.
