### ISSUE TITLE
[BUG] document_exporter no configuration file provided: not found

### ISSUE THREAD

**Issue by bmsleight** [paperless-ngx/paperless-ngx#7180]
### Description

As per #6027 

$ docker compose exec -T paperless-webserver-1 document_exporter ../export
no configuration file provided: not found

Solution is to be in the paperless-ngx directory
bms@percy:~$ cd paperless-ngx/
bms@percy:~/paperless-ngx$ docker compose exec -T webserver document_exporter ../export
100%|██████████| 80/80 [00:00<00:00, 939.58it/s]
bms@percy:~/paperless-ngx$ 

Document patch to follow. 

### Steps to reproduce

Follow https://docs.paperless-ngx.com/administration/#exporter

### Webserver logs

```bash
N/a
```

### Browser logs

```bash
n/
```

### Paperless-ngx version

Paperless-ngx 2.8.6

### Host OS

debian bookworm

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
- Those steps are clearly not enough to reproduce anything
- We don't support older versions
- This is clearly something about your configuration, as the Docker image is always left with the correct working directory for the commands to function normally
- you may also be confused about how Docker Compose works. It needs the compose file either present or provided via flags

In short, not a bug.

**Comment by bmsleight** [comment]
At least consider the document update.

**Comment by shamoon** [comment]
i.e. https://stackoverflow.com/a/70257438/5331804

**Comment by stumpylog** [comment]
Our documentation is not an introduction to Docker.  Some level of knowledge is required
