### ISSUE TITLE
[BUG] Advanced Search for ASN number range does not work correctly

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#7186]
### Description

Using advaced search with this search string: asn:[1 to 14] outputs wrongly every document with an ASN. 

My total ASN document amount is currently 97.

This behaviour was reported in #3139 .

### Steps to reproduce

1. Using advanced search with this search string: asn:[1 to 14] outputs every document with an ASN. 
2. A search string: asn:[1 to 15] results in only the first 15 documents with an ASN like it should be...

### Webserver logs

```bash
no errors
```

### Paperless-ngx version

2.10.2

### Host OS

gentoo x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.2",
    "server_os": "Linux-6.6.32-gentoo-dist-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 1829027639296,
        "available": 544476778496
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://pl-redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-08T00:00:33.074450+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-08T10:05:02.860002Z",
        "classifier_error": null
    }
}
```
```


### Browser

Chrome latest for macOS ARM

### Configuration changes

_No response_

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is a feature request, at most, feel to open one.

**Comment by r2ixuz** [comment]
Ok but why is this a feature request? I mean the search ends with inconsistent results.

Or do you mean it is a feature request because at https://docs.paperless-ngx.com/usage/#document-searches ASN search is not mentioned?

**Comment by shamoon** [comment]
The second. In general, these queries come from whoosh.

You can also run this filter directly against database easily with `archive_serial_number__gt=X&archive_serial_number__lt=Y`
