### ISSUE TITLE
[BUG] Visual: Split document, split button becomes active again when no splits are possible

### ISSUE THREAD

**Issue by felldo** [paperless-ngx/paperless-ngx#7214]
### Description

When you have a new document and want to split it, the "Add split" button (or what it is called in english) is not disabled at the splitted position.

### Steps to reproduce

1. Split all pages of the document
When you get to the last page, the behaviour is correct and the split button is disabled
![image](https://github.com/paperless-ngx/paperless-ngx/assets/31566807/2b83639c-377f-4373-80a2-5884bb0c64f1)

If you now scroll up to any previous page, the split button will become active again, although you won't be able to split any more pages.
![image](https://github.com/paperless-ngx/paperless-ngx/assets/31566807/cd7cc55b-710f-42a2-bcc1-e187184923b6)

### Webserver logs

```bash
Not needed
```

### Paperless-ngx version

2.10.2

### Host OS

Ubuntu

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I think calling this a bug is a bit of an exaggeration. The button is disabled on the first and last pages because a split isn’t possible, clicking add when one already exists doesn’t do anything “bad” nor throw an error. I suppose you can open a FR if you’d like. Thanks for your interest in the project
