### ISSUE TITLE
[BUG] Docker Update breaks Gotenberg

### ISSUE THREAD

**Issue by ralfi** [paperless-ngx/paperless-ngx#7227]
### Description

Today's update to v2.11 breaks Gotenberg, for log entry see here:

![image](https://github.com/user-attachments/assets/a86f7a70-d655-401d-ad37-0db124f8ec80)

### Steps to reproduce

1. git pull
2. docker-compose pull
3. docker-compose down
4. docker-compose up -d

### Webserver logs

```bash
No, see Docker log entry
```

### Paperless-ngx version

2.11

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

Nothing since last update to 2.10

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by ralfi** [comment]
Solution from Matrix Chat
Change gotenberg Docker Image in docker-compose.yml to version 6.8

**Comment by diesl** [comment]
@shamoon I know I am a bit late to the party, but considering you are following _semver_ and this is a breaking change, I think the current release `2.11.0` should better have been `3.0.0` ?

**Comment by shamoon** [comment]
Gotenberg is an optional, external third party tool that is 'updated' by changing the docker tag. Semantics of semver aside, this hardly seems worthy of 3.x
