### ISSUE TITLE
[BUG] Demo site returns a 404

### ISSUE THREAD

**Issue by slnc** [paperless-ngx/paperless-ngx#7233]
### Description

The [Paperless demo site](https://demo.paperless-ngx.com/) linked on the README.md gives me a 404.

<img width="825" alt="image" src="https://github.com/user-attachments/assets/73421cb8-335b-452b-ba41-598f8f773cd1">

### Steps to reproduce

1. Go to https://demo.paperless-ngx.com/

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

N/A

### Host OS

N/A

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Works fine for me.  This isn't a bug with paperless either, contrary to the checkmarks you hit above.

**Comment by slnc** [comment]
> Works fine for me. This isn't a bug with paperless either, contrary to the checkmarks you hit above.

I'm not sure how this report goes against any of the checkboxes: the demo site wasn't working when I reported the issue which affected every user of Paperless-ngx at the time I reported the issue, you can see the cloudflare IP returning a 404, I had searched for relevant issues, and I had updated the title with a concise description.

Anyways, you're welcome.

**Comment by shamoon** [comment]
The demo recreates itself frequently, I did add a more helpful 404 page but I’ll have to see if I can tweak it

**Comment by slnc** [comment]
@shamoon thanks, perhaps it was bad timing on my part.

**Comment by shamoon** [comment]
Yea it’s actually a small window when there’s a barebones 404 but that’s what I meant by tweak it, try to make it always show the better 404
