### ISSUE TITLE
[BUG] Google invoice PDFs cannot be imported with "File type application/octet-stream not supported"

### ISSUE THREAD

**Issue by ginkel** [paperless-ngx/paperless-ngx#7239]
### Description

Hi there,

Google seems to create odd PDF invoices that fail being imported into paperless-ngx. Looking at the file with a hex viewer shows that there is extra data before the PDF header:

![image](https://github.com/user-attachments/assets/05eae72e-9bd1-49b7-9ca9-f6a7fadaf8cc)

Paperless-ngx complains about this with: `File type application/octet-stream not supported`

Most likely this is a duplicate of https://github.com/paperless-ngx/paperless-ngx/issues/2419. Your answer was to re-generate the PDF file. Google being Google certainly won't do this.

As I am using paperless-ngx as a long-term archiving solution I'd be interested in a way to archive such documents. Modifying invoice PDFs before archival is not permitted by German law.

Thanks,
Thilo

### Steps to reproduce

1. Try to import a Google workplace invoice PDF

### Webserver logs

```bash
Noerror is logged
```

### Paperless-ngx version

2.11.0

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I’m not sure how exactly is this a bug on our end, as you correctly point out, the file is malformed. You can fix the file yourself before importing into paperless
