### ISSUE TITLE
[BUG] Table view columns are messed up on smaller screen sizes

### ISSUE THREAD

**Issue by umtauscher** [paperless-ngx/paperless-ngx#7253]
### Description

I Updated today to 2.11
I don‘t now if thsi was previously working.

In the table view on the ipad safari columns are missing and column titles are not positioned correctly
![IMG_2224](https://github.com/user-attachments/assets/43f63366-c543-47e7-b719-7b969d960ec0)

### Steps to reproduce

Got to a view
Select table view
Select the columns to show

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.11

### Host OS

Proxmox, Intel

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Is there an error in the browser console?

I certainly can’t reproduce this with just those instructions

**Comment by umtauscher** [comment]
Well, how can I show a browser console on an iPad?
I really don‘t know if that‘s possible at all.

**Comment by umtauscher** [comment]
Oh, I can reprocude it on any browser now.
Just reduce the window width a bit.  About half of the screesize does it on 1920:1080
On the iPad I naturally have no control of the size.

**Comment by shamoon** [comment]
Yes something must have changed within the bootstrap framework, I'll sort it out
