### ISSUE TITLE
Error using Installation Script from Paperless SETUP-Page

### ISSUE THREAD

**Issue by Evil-Error** [paperless-ngx/paperless-ngx#7288]
### Description

Its not about Paperless itself but regarding the setup documentation

https://docs.paperless-ngx.com/setup/#docker_script

at point two which points to the automatic install script I guess there is a problem within the script using the command 
"docker compose" several times, which cause in a failure because the command should be
 "docker-compose" I guess ? 

first:

`if ! docker compose &> /dev/null ; then
        echo "docker compose plugin not found. Is docker compose installed?"
        exit 1
fi`

and also at:

`docker compose pull

if [ "$DATABASE_BACKEND" == "postgres" ] || [ "$DATABASE_BACKEND" == "mariadb" ] ; then
        echo "Starting DB first for initialization"
        docker compose up --detach db
        # hopefully enough time for even the slower systems
        sleep 15
        docker compose stop
fi

docker compose run --rm -e DJANGO_SUPERUSER_PASSWORD="$PASSWORD" webserver createsuperuser --noinput --username "$USERNAME" --email "$EMAIL"

docker compose up --detach` 

I changed the .sh-script  and could run it after that whitout issues.

pleas excuse if this should be the wrong place to inform you about it. 

### Steps to reproduce

execute:

`$ bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`
"

### Webserver logs

```bash
root@PAPERLESS:/home/admin# docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
root@PAPERLESS:/home/admin#
```

### Paperless-ngx version

none

### Host OS

Ubuntu 22.04 LTS

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by hfrSchmidt** [comment]
You are most likely using a deprecated version of docker compose (v1). I would suggest to update to version 2.
More info also here: https://docs.docker.com/compose/migrate/

**Comment by stumpylog** [comment]
That's correct. We dropped support for V1 quite some time ago, as Docker themselves no longer support it.  You will need to update your install.

**Comment by Evil-Error** [comment]
Damn!

Thanks very much - my fault! I installed Docker, using an old script and didn't notice -_-
