### ISSUE TITLE
Export Split Manifest not Working

### ISSUE THREAD

**Issue by alst-ovh** [paperless-ngx/paperless-ngx#7293]
### Description

If i run document_exporter with -sm or --split-manifest, it does not split the manifest

### Steps to reproduce

document_exporter ../export -d -p -f -sm

### Webserver logs

```bash
Nothing
```

### Paperless-ngx version

2.11

### Host OS

Debian 12

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You haven't provided any logs, or examples of what the output is vs expected.

**Comment by stumpylog** [comment]
That's not an example of the output you get

**Comment by alst-ovh** [comment]
I get the full manifest.json and not splittet !
it generates only the full manifest.json !!!

The parameter -sm  does not work, the output is always the full manifest.json !!!

Try it then you see it !

**Comment by stumpylog** [comment]
I have tried it, hence why this has been flagged as "can't reproduce".  

What I want from you is the listing of files in the `json` directory, since you are using the `-f` option.  And have you tried putting the options first?  That's the typical ordering for any command, options, then positional.

**Comment by alst-ovh** [comment]
OK, thanks for the tip, I misunderstood the split function, now I see it, please close
