### ISSUE TITLE
[BUG] Cannot upload files in UI

### ISSUE THREAD

**Issue by praetorianer777** [paperless-ngx/paperless-ngx#730]
### Description

Hello,

I installed paperless on bare metal, I got no errors or anything else, but when I try to upload a file wit hthe webui, it looks like described here: [https://github.com/paperless-ngx/paperless-ngx/issues/220](url), but I have no uploaded file.

I run it also behind an apache reverse proxy.

### Expected behavior

The file should be uploaded and processed, also the progress bar should update correctly.

### Steps to reproduce

Nothing special, just installed it.

### Webserver logs

```bash
only entries are like this:

docs.domain.de:443 192.168.1.15 - - [14/Apr/2022:15:13:23 +0200] "GET /sw.js HTTP/1.1" 200 3907 "https://docs.domain.de/sw.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
```

### Screenshots

![image](https://user-images.githubusercontent.com/6584303/163480955-19a82b3a-cb91-4c0b-ab1c-55c44b0e4c1b.png)

### Paperless-ngx version

1.7.0-rc1

### Host OS

Ubuntu 20.04

### Installation method

Bare metal

### Browser

Chrome

**Comment by praetorianer777** [comment]
Also when I add a file to the consume directory I get the following log:

[2022-04-14 15:19:27,957] [INFO] [paperless.management.consumer] Adding ../consume/003448.pdf to the task queue.

[2022-04-14 15:19:27,959] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: ../consume

but nothing happens...

**Comment by shamoon** [comment]
Im going to guess these are both install-related. 

The first one I bet is related to your reverse-proxy, which was the issue in the thread you linked to. Have you tried from localhost and / or tweaking the reverse proxy settings? https://paperless-ngx.readthedocs.io/en/latest/setup.html#using-nginx-as-a-reverse-proxy I dont use apache so cant give specifics. This isnt a known issue in 1.7.0-rc1.

**Comment by shamoon** [comment]
Also, did you have 1.6.0 working previously?

**Comment by praetorianer777** [comment]
No I didn't use 1.6 before, it is a fresh install.
And I can't test it with localhost because it is a headless machine :(

I try a fresh install in the evening, maybe something went wrong there... I will give some feedback when it's done!

**Comment by shamoon** [comment]
Appreciate your patience. Yea you might want to try 1.6.0 which has been pretty throughly tested and in the wild for a bit.

That said, if there are real issues in 1.7.0-rc1 obviously we would love to know. There aren’t huge changes to this functionality between the two versions but of course it’s possible something broke :)

**Comment by shamoon** [comment]
btw specifically you need websockets enabled on your reverse proxy for webui upload

**Comment by praetorianer777** [comment]
Hehe no problem, finally this is opensource...
Websockets are enabled, I also don't geht Errors related to this in the web console

**Comment by praetorianer777** [comment]
Ok, still the same issue...
And with version 1.6 I get a CSRF-Token error

**Comment by praetorianer777** [comment]
I run the server in the console and this is the output when I upload the file:

```
20:28:36 [Q] INFO Enqueued 4
[14/Apr/2022 20:28:36] "POST /api/documents/post_document/ HTTP/1.1" 200 4
[14/Apr/2022 20:28:36] "GET /ws/status/ HTTP/1.1" 200 8489
[14/Apr/2022 20:28:47] "GET /sw.js HTTP/1.1" 200 8489
[14/Apr/2022 20:29:05] "GET /assets/bootstrap-icons.svg HTTP/1.1" 302 0
[14/Apr/2022 20:29:08] "GET /api/correspondents/?page=1&page_size=100000 HTTP/1.1" 200 52
[14/Apr/2022 20:29:08] "GET /api/documents/?page=1&page_size=50&ordering=-created HTTP/1.1" 200 52
[14/Apr/2022 20:29:08] "GET /api/tags/?page=1&page_size=100000 HTTP/1.1" 200 52
[14/Apr/2022 20:29:08] "GET /api/document_types/?page=1&page_size=100000 HTTP/1.1" 200 52
[14/Apr/2022 20:29:08] "GET /api/documents/?page=1&page_size=50&ordering=-created HTTP/1.1" 200 52
[14/Apr/2022 20:29:08] "GET /api/statistics/ HTTP/1.1" 200 44
[14/Apr/2022 20:29:11] "GET /api/logs/ HTTP/1.1" 200 20
[14/Apr/2022 20:29:11] "GET /api/logs/paperless/ HTTP/1.1" 200 1709
[14/Apr/2022 20:29:27] "GET /api/statistics/ HTTP/1.1" 200 44
```

Looks like it is enqued, but nothing happens... are there other logs I can inspect?

The protocol on the webpage only shows this:

```
[2022-04-14 20:00:39,872] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: ../consume

[2022-04-14 20:00:39,953] [DEBUG] [paperless.management.consumer] Not consuming file ../consume/__paperless_write_test_26568__: File has moved.

[2022-04-14 20:05:52,499] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: ../consume

[2022-04-14 20:05:53,514] [DEBUG] [paperless.management.consumer] Not consuming file ../consume/__paperless_write_test_26715__: File has moved.

[2022-04-14 20:06:15,290] [DEBUG] [paperless.management.consumer] Not consuming file ../consume/__paperless_write_test_26787__: File has moved.

[2022-04-14 20:06:47,879] [INFO] [paperless.management.consumer] Adding ../consume/sample.pdf to the task queue.

[2022-04-14 20:11:07,781] [DEBUG] [paperless.management.consumer] Not consuming file ../consume/__paperless_write_test_26914__: File has moved.
```

**Comment by praetorianer777** [comment]
Ah I found something in the service status:

```
Apr 14 21:39:30 paperless python3[708]:     self._target(*self._args, **self._kwargs)
Apr 14 21:39:30 paperless python3[708]:   File "/opt/paperless/.local/lib/python3.8/site-packages/django_q/cluster.py", line 424, in worker
Apr 14 21:39:30 paperless python3[708]:     f = pydoc.locate(f)
Apr 14 21:39:30 paperless python3[708]:   File "/usr/lib/python3.8/pydoc.py", line 1632, in locate
Apr 14 21:39:30 paperless python3[708]:     nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
Apr 14 21:39:30 paperless python3[708]:   File "/usr/lib/python3.8/pydoc.py", line 362, in safeimport
Apr 14 21:39:30 paperless python3[708]:     raise ErrorDuringImport(path, sys.exc_info())
Apr 14 21:39:30 paperless python3[708]: pydoc.ErrorDuringImport: problem in documents.tasks - ImportError: Unable to find zbar shared library
```

but zbar is installed via pip

**Comment by praetorianer777** [comment]
Upload and processing of the uploaded file works after installing

`apt install libzbar0`

**Comment by shamoon** [comment]
Thanks for the update, glad it’s working. Is that on v1.6.0 or 1.7.0-rc1?

@stumpylog isnt `libzbar0` a new requirement from the barcode feature and thus shouldn’t be in 1.6? And is it included in 1.7? I don’t see it there tho I’m on my phone so a little hobbled atm.

**Comment by praetorianer777** [comment]
I didn't get Version 1.6 to work and tried again with 1.7, there I found the solution, don't know what was wrong with 1.6 :/

**Comment by stumpylog** [comment]
If I'm following the history here, that log was from trying with 1.7.0-rc1?  So it's expected to see things about zbar there.

You're correct though, the requirements for installing `libzbar0 poppler-utils` are missing from the bare metal documentation, at least in dev.

**Comment by shamoon** [comment]
Yes correct on 1.7.0, ok thanks I can an add that to the docs if that’s all that’s missing

**Comment by stumpylog** [comment]
It looks that way.  Install the pyzbar library won't install the required system libraries.    So they're missing from step 1

**Comment by praetorianer777** [comment]
seems like poppler is also missing:

```
Apr 15 11:33:53 paperless python3[61181]:   File "/opt/paperless/src/documents/tasks.py", line 198, in consume_file
Apr 15 11:33:53 paperless python3[61181]:     separators = scan_file_for_separating_barcodes(path)
Apr 15 11:33:53 paperless python3[61181]:   File "/opt/paperless/src/documents/tasks.py", line 105, in scan_file_for_separating_barcodes
Apr 15 11:33:53 paperless python3[61181]:     pages_from_path = convert_from_path(filepath, output_folder=path)
Apr 15 11:33:53 paperless python3[61181]:   File "/opt/paperless/.local/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
Apr 15 11:33:53 paperless python3[61181]:     page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
Apr 15 11:33:53 paperless python3[61181]:   File "/opt/paperless/.local/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 484, in pdfinfo_from_path
Apr 15 11:33:53 paperless python3[61181]:     raise PDFInfoNotInstalledError(
Apr 15 11:33:53 paperless python3[61181]: pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

**Comment by gador** [comment]
as @stumpylog has said:
> You're correct though, the requirements for installing `libzbar0 poppler-utils` are missing from the bare metal documentation, at least in dev.

So installing both packages is required. The documentation has been updated in #737
