### ISSUE TITLE
[BUG] Drop does not work anywhere

### ISSUE THREAD

**Issue by mrichtarsky** [paperless-ngx/paperless-ngx#7318]
### Description

On the Dashboard (likely other pages supporting drag&drop as well) it says "Drop documents anywhere" but when dropping at the end of the page (not part of any container, `body` element) drop does not work, instead the document is opened in both Firefox and Chrome, and you have to use the back button to get back to paperless.

Would be nice if the drop action could be bound to the `body` element, not sure that's possible.

### Steps to reproduce

1. Go to Dashboard
2. Drag document to the bottom right of the page, where no container is displayed

### Webserver logs

```bash
Frontend issue
```

### Browser logs

```bash
t
```

### Paperless-ngx version

2.11.0

### Host OS

Linux amd64

### Installation method

Docker - official image

### Browser

Firefox, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by mrichtarsky** [comment]
P.S.: At least Chrome opens in a separate tab. Firefox uses the current tab and then it's possible to lose state. Example: In the document view when you have selected some documents, that drop outside by mistake, use the back button, the original selection will be lost.

**Comment by shamoon** [comment]
I do not think we broke drag-and-drop suddenly, see below. Perhaps a browser extension or some other issue.


https://github.com/user-attachments/assets/8a925a51-04e7-4631-836d-56e1a44af664

**Comment by shamoon** [comment]
I cant reproduce that, and its nothing to do with the drag not covering that area, it looks like your browser is triggering a drag out event, thats why the green shows up and then goes away. What browser is that and are you running in some kind of frame?

See:

https://github.com/user-attachments/assets/f06a8016-7dd1-47ee-8684-7933520fdf25

https://github.com/user-attachments/assets/38b72d50-8375-4acd-bed0-6d7104033129

**Comment by mrichtarsky** [comment]
My screencap is from Edge, which I just installed from scratch for the occasion. I can reproduce it also in Firefox and Chrome. In your first video, you are still in a container below `body` (check with the inspector). I can reproduce the behavior from your second video as well with the large vertical size of 3000 in the mobile emulation, but not with some smaller size, there it's broken again:

![7318_2](https://github.com/user-attachments/assets/2878856f-e341-4601-aab7-02d9adb62218)

Anyway, it's no big issue, so if you don't see an easy way to somehow attach the drop listener to the whole `body` then let's just keep it as is.

**Comment by shamoon** [comment]
Yea I still cant reproduce this but if you want to try out the docker image tagged `fix-7318`, let me know if that changes things. That image is based on 2.11.1 so should be safe to test (the changes between 11.0 and 11.1 dont make any e.g. database migrations) but then again, always safest to test on non-production data

**Comment by shamoon** [comment]
Another approach you can try: `fix-7318-2`

**Comment by mrichtarsky** [comment]
Both approaches work fine, I tested in Firefox and Chrome. Thank you very much!
