### ISSUE TITLE
[BUG] Filter documents by more than one owner

### ISSUE THREAD

**Issue by bjoernpoettker** [paperless-ngx/paperless-ngx#7322]
### Description

When I want to add more than on owner to the filter the added owner is not listed but is recognized by the filter.

If I change e.g. the tag-filter, the owners only filter by the first on.

![Permissions Owner](https://github.com/user-attachments/assets/cdfe8086-89bd-4dc3-a9a9-1db5fb0f86a4)

### Steps to reproduce

Go to documents
Open the permissions filter
Add more than on owner
Change e.g. the tag filter

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.11.0

### Host OS

unraid / docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I don’t understand what you’re saying and I can’t reproduce any issue. In other words, filtering for multiple owners isnt working unless you add a tag filter? Or the opposite, that the tag filter makes the multiple owner filter not work?

Again, either way I can’t reproduce this but perhaps I’m misunderstanding

Also please post the system status as requested

**Comment by shamoon** [comment]
This can be re-opened if you can add more context, but again, I cant reproduce anything here, see attached.

https://github.com/user-attachments/assets/8bf3f9f6-84ff-475d-9c15-2f0ed4d18779

**Comment by bjoernpoettker** [comment]
Hello,
Thanks for your answer.
I restarted my system and now it works for me too. Yesterday only one owner was displayed in the selection field even if I had selected more than one.
