### ISSUE TITLE
[BUG] Cannot login if NOT superuser

### ISSUE THREAD

**Issue by jacobburrell** [paperless-ngx/paperless-ngx#7326]
### Description

<img width="586" alt="image" src="https://github.com/user-attachments/assets/49bda00d-ad38-4fde-ba09-b5dbd8359dc1">

Getting a 403 https://paper.revoluciones.mx/api/ui_settings/ 
`    "detail": "You do not have permission to perform this action."`

when logging in with a test user without superuser permissions.

<img width="384" alt="image" src="https://github.com/user-attachments/assets/18ff5d6a-6e90-4853-87f0-52b563f48ea3">

Giving superuser permissions DOES allow the test user to login

### Steps to reproduce

1. Create user test
2. try to login incognito
3. 403 and login hands forevver

### Webserver logs

```bash
webserver-1  | [2024-07-26 01:20:13,628] [WARNING] [django.request] Forbidden: /api/ui_settings/
```

### Paperless-ngx version

2.11.1

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by jacobburrell** [comment]
Saw that it is a specific permission: `View permission for UISettings`

<img width="743" alt="image" src="https://github.com/user-attachments/assets/a367b1c8-80bf-4596-87ed-3b814101dacd">

Seems like there is a disconnect here. Either the setting shouldn't be required to _just_ login, or should be toggled when the user is made active or not.

Additionally, the login page shouldn't just hang with an error message. User should be told what permission is missing or that their account isn't active.

**Comment by jacobburrell** [comment]
@shamoon this is expected behaviour?

**Comment by shamoon** [comment]
https://docs.paperless-ngx.com/usage/#global-permissions

> **Users that will access the web UI must be granted at least View permissions.**

![IMG_3676](https://github.com/user-attachments/assets/3c7d8742-127d-4e6d-90d1-5274526f007f)
