### ISSUE TITLE
[BUG] Delete Document is not working correct

### ISSUE THREAD

**Issue by chriswhaas** [paperless-ngx/paperless-ngx#7344]
### Description

I updated to paperless-ngx 2.11.2, but maybe I just didn´t noticed before: Deleting a document is done inside the web Gui, document is visualy gone. But in my docker folders it stays in the archive and original folder and is not moved. And it stays in the database, uploading the same file again is not working becuase an error message:  It is a duplicate of ...Document (#726).

### Steps to reproduce

Delete a document
Check file in browser, is still in the folders
Upload the same file again= error message, because not really deleted.
[docker-compose.zip](https://github.com/user-attachments/files/16417914/docker-compose.zip)

### Webserver logs

```bash
ther is no delete in the log, just notifications for creating the file, creating ID´s
```

### Paperless-ngx version

2.11.2

### Host OS

Synology

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please read the release notes, it is in the trash

**Comment by chriswhaas** [comment]
no, the document is still in the original folder. And I can´t add the same document again, because it is still in the database

**Comment by shamoon** [comment]
Until the trash is emptied it's not actually deleted. Again, previous release notes describe the feature, so do the docs.

**Comment by chriswhaas** [comment]
Ok, Thank you, I can confirm this behaviour, you are right. But for me it is confusing that a new upload of the same document do not tell me that there is a copy in the trash. It says the document is already there in the account. 
Worst Case: I delete it and forget about it, still in Trash. A few weeks later I want to add this document and paperless say to me: already there. I think everything is all right and I delete it from my computer. A few days later I empty the trash and NOW it´s 
 really gone and I have no chance to recover the document or even notice the missing at that moment. Does that make sense?
