### ISSUE TITLE
[BUG] Default currency for monetary custom fields is acting weird

### ISSUE THREAD

**Issue by Blizzke** [paperless-ngx/paperless-ngx#7356]
### Description

I have a couple monetary fields in my paperless install and they've always defaulted to `USD`. I have (literally) typed EUR 500 times the last month. Yesterday I've added 1 document where I used `GBP` as currency and now it defaults to `GBP` every time I add that field to a document.

I've been looking for "default currency" here and found #6020 - a PR that seems merged where it uses the `LOCALE_ID` to determine the default currency. I've added the environment variable to the docker service container with value '`en_BE` ' (English, Belgium) and have confirmed it is set in the container for the service user, but it keeps showing up with `GBP`.

### Steps to reproduce

Add a custom monetary field
Add the field to document, it wiil default to USD
Type GBP in the currency, fill amount, save document
Afterwards the default is "GBP"

### Webserver logs

```bash
This is a frontend issue I think, so unfortunately no logs.
```

### Paperless-ngx version

2.11.2

### Host OS

Linux-6.10.0-3-MANJARO-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-6.10.0-3-MANJARO-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 235382026240,
        "available": 78629376000
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-31T11:33:16.692407+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-31T09:05:09.140271Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome / Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
There is quite literally no mechanism by which it will change from the locale default. Only changing the locale of the browser or system would affect it
