### ISSUE TITLE
[BUG] wrong documents filtered, when searching with created for an exact date

### ISSUE THREAD

**Issue by IeP4nieF** [paperless-ngx/paperless-ngx#7378]
### Description

Searching for documents created at a specific date leads to documents created on the next day. For example searching with

`https://paperless.domain/documents?query=created:2024-02-06`

leads to documents created on 2024-02-07.

Timezone is set to `Europe/Berlin`.

### Steps to reproduce

Search again with

`https://paperless.domain/documents?query=created:<date>`.

### Webserver logs

```bash
no logs returned on this query
```

### Browser logs

```bash
no issues in browser
```

### Paperless-ngx version

2.11.2

### Host OS

Debian 12 Linux-6.1.0-23-amd64-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-6.1.0-23-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 937926811648,
        "available": 388935409664
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-03T00:00:04.233752+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-03T00:05:00.527504Z",
        "classifier_error": null
    }
}
```

### Configuration changes

using an external postgresql-host, so no db-section in docker-compose.yml

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
You can try reindexing and checking for timezone issues, I do not suspect that this is suddenly broken. If you want to use an exact date better to use the date queries against the database

I’ll move this to a discussion for now
