### ISSUE TITLE
[BUG] Same as already closed bug report

### ISSUE THREAD

**Issue by Stephan-4711** [paperless-ngx/paperless-ngx#7406]
### Description

As in https://github.com/paperless-ngx/paperless-ngx/issues/776

I have exactly the same problem, but it's a monthly recuring PDF I get, which should be automatically proccesed.
It's a credit card bill from barclay card germany.
My installation is installed on proxmox with ttecks lxc paperless script.

Is there a way to automatically get that files imported, it would be very sad, if I need to manipulate every month this pdfs?

### Steps to reproduce

Import Barclay card credit card bill

### Webserver logs

```bash
Rule ScanInput.Scaninput Standard: Skipping attachment Kontoauszug_15412014_2024-02-05.pdf since guessed mime type application/octet-stream is not supported by paperless
```

### Paperless-ngx version

2.11.2

### Host OS

Debian 12

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please read that thread, its really not a bug, its a malformed PDF

**Comment by Stephan-4711** [comment]
And now I have to deal with the credit card company instead of fixing the problem in the DMS?
