### ISSUE TITLE
[BUG] Calendar weekdays are off

### ISSUE THREAD

**Issue by CF-FHB-X** [paperless-ngx/paperless-ngx#7410]
### Description

It seems as if the calendar week days are off? Here's a screenshot of August 7th, 2024 which should be a Wednesday, but is showing up as Tuesday instead:

<img width="453" alt="Screenshot 2024-08-07 at 12 33 15 PM" src="https://github.com/user-attachments/assets/10229a63-2dde-482d-805f-d518e541f57f">

### Steps to reproduce

This happens when editing a file (in this case, it was a merged document from 2 input PDFs, but not sure that matters).

### Webserver logs

```bash
n/a? If you need them, I can provide them.
```

### Paperless-ngx version

2.11.2

### Host OS

Raspberry Pi arm 64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-6.6.28+rpt-rpi-2712-aarch64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 244926529536,
        "available": 198067867648
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-07T12:39:26.466870-04:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-07T16:05:02.289030Z",
        "classifier_error": null
    }
}
```

### Browser

Safari and Vivaldi are both showing the same incorrect weekdays

### Configuration changes

n/a

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not our big. We’ll update when they fix it.

https://github.com/paperless-ngx/paperless-ngx/discussions

https://github.com/ng-bootstrap/ng-bootstrap/issues/4729

**Comment by gdh2024-gdh** [comment]
As of 26 Aug 2024, looking at https://ng-bootstrap.github.io/#/components/datepicker/overview the issue seems to be fixed.  In paperless-ngx 2.11.6 it is not fixed.

**Comment by shamoon** [comment]
The correct bug report is linked above and no, it is not resolved yet.

**Comment by JiCiT** [comment]
FYI, looks the upstream bug was squashed in latest upstream release about two weeks ago.

**Comment by shamoon** [comment]
And it was already merged here
