### ISSUE TITLE
[BUG] Wrong index when deleting papes from document

### ISSUE THREAD

**Issue by felixfkrull** [paperless-ngx/paperless-ngx#7413]
### Description

Deleting the last page of a 13 pages long document leads to an error:
`[INFO] [paperless.bulk_edit] Attempting to delete pages [13] from 1 documents`
`[ERROR] [paperless.bulk_edit] Error deleting pages from document <nnn>: Accessing nonexistent PDF page number`

### Steps to reproduce

Try to delete the last page of any pdf document.

### Webserver logs

```bash
[2024-08-08 00:02:20,885] [INFO] [paperless.bulk_edit] Attempting to delete pages [13] from 1 documents
[2024-08-08 00:02:20,939] [ERROR] [paperless.bulk_edit] Error deleting pages from document 575: Accessing nonexistent PDF page number
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/bulk_edit.py", line 385, in delete_pages
    pdf.pages.remove(pdf.pages[page_num - offset])
                     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: Accessing nonexistent PDF page number
```

### Paperless-ngx version

2.11.2

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Someone else reported something similar #7335 but this seems like an error with the PDF and ultimately an error with the software that does the deleting. As I mentioned there, if you can provide a sample PDF you may want to create an issue in that project.

**Comment by shamoon** [comment]
Or if you can provide the file here I can play with it too
