### ISSUE TITLE
[BUG] Selection is not cleared after deleting objects

### ISSUE THREAD

**Issue by Finkman** [paperless-ngx/paperless-ngx#7417]
### Description

I was editing the correspondents and tried to delete multiple correspondents and delete them.

What I did:

![Bildschirmaufzeichnungvom01 08 2024122959-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/f6895529-532e-422e-874f-e08e72938abb)

I used a - never used before - FireFox for my latest test.

Error Details:

```json
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"OK","url":"https://paperless.hauswg.diskstation.me/api/bulk_edit_objects/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://paperless.hauswg.diskstation.me/api/bulk_edit_objects/: 400 OK","error":{"non_field_errors":["Some ids in objects don't exist or were specified twice."]}}
```

The permissions of that user:

![image](https://github.com/user-attachments/assets/4c14ea0d-c7af-4986-9b49-223424457cbb)

### Steps to reproduce

1. Login as a User with given rights see picture below.
2. Take paperless 2.11.2
3. Select a correspondent
4. Press delete at the trash bin icon top right

### Webserver logs

```bash
-- currently no access to the server logs --
```

### Paperless-ngx version

2.11.2

### Host OS

Synology OS

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-3.10.108-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 8915941834752,
        "available": 2135326994432
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-01T08:54:24.644162+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-01T06:05:04.194939Z",
        "classifier_error": null
    }
}
```

### Browser

Edge, Safari, Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
The actual issue is the selection isn't getting cleared after you delete objects, I think that's the actual issue. I suppose it can be changed so you don't have to hit clear selection

**Comment by Finkman** [comment]
Wired to change the title in a complete different meaning.

what ever issue is related to the selection…

It is simply not deleting! That is my point.

After simply closing #7360, it seams you don’t want to face the problem here. If it is like that, I can live with that but will stop reporting bugs.

**Comment by shamoon** [comment]
1. The title was changed to be accurate, I’m happy to change it back to your incorrect one. It’s the second time you’ve filed a report that didn’t really describe the issue correctly.
2. This was closed because I fixed it.

**Comment by Finkman** [comment]
The title describes exactly what is (not) happening and which is visible in the gif, btw.

Don’t get it, why this is going to be so rude.

**Comment by shamoon** [comment]
Because your response sounded snarky as well as complained that this was closed without being addressed, which is false.

Yes, feel free to stop posting to this project.

**Comment by Finkman** [comment]
Apologies, I didn't want to sound snarky.
Simply, I found that bug and wanted to give a helpful feedback to it as a kind of contribution.
I really love this project and appreciate the time and effort you invest to it.
Hopefully, we can cool this down and get along with it.

Thanks for the fix and sorry for the noise.

**Comment by shamoon** [comment]
Thanks for saying that. Apologies if I was too quick to assume the worst.
