### ISSUE TITLE
[BUG] No GMAIL login possible (no 2FA) V2.11.0

### ISSUE THREAD

**Issue by VerbraucherX** [paperless-ngx/paperless-ngx#7441]
### Description

In V2.11.0 it seems that configuring the email login funktion with a Gmail account doesn't work (only user and password, not testet with 2FA). It constantly refuses to login to a Gmail account:

![Screenshot_20240810_154653_Brave](https://github.com/user-attachments/assets/1c769409-5796-458b-9a32-28663bd8c7d1)

Other email provider work flawlessly (tested mailbox.org).

### Steps to reproduce

1. Go to email accounts
2. Add a Gmail account
3. Test login
4. It will fail

### Webserver logs

```bash
[2024-08-10 17:50:00,477] [ERROR] [paperless.mail.tasks] Error while processing mail account xxxxx

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 220, in mailbox_login

    mailbox.login(account.username, account.password)

  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 63, in login

    check_command_status(login_result, MailboxLoginError)

  File "/usr/local/lib/python3.11/site-packages/imap_tools/utils.py", line 46, in check_command_status

    raise exception(command_result=command_result, expected=expected)

imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/tasks.py", line 17, in process_mail_accounts

    total_new_documents += MailAccountHandler().handle_mail_account(account)

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 510, in handle_mail_account

    mailbox_login(M, account)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 230, in mailbox_login

    raise MailError(

paperless_mail.mail.MailError: Error while authenticating account xxxxx
```

### Paperless-ngx version

V2.11.0

### Host OS

Docker

### Installation method

Docker - official image

### Browser

Brave, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not a bug, Oauth is not supported.

**Comment by VerbraucherX** [comment]
> This is not a bug, Oauth is not supported.

Sorry? It works with other mail accounts, but not with Gmail. So Oauth generally works, but not in this case or did I misunderstood something?

**Comment by shamoon** [comment]
No, Oauth does not work. It’s not supported and never has been.

Google is discontinuing support for ‘app passwords’ which is the only way this has ever worked with 2FA in the past. If you still have access to app passwords you can use them, otherwise you can’t use Gmail.

Try googling it.

**Comment by r2ixuz** [comment]
That is not true. App passwords with activated 2FA will continue to work. At least if you want to trust these sources:

https://www.googlecloudcommunity.com/gc/Workspace-Q-A/Will-App-Passwords-work-for-IMAP-after-Sept-30-2024/m-p/715290
https://support.google.com/a/answer/14114704?hl=en
