### ISSUE TITLE
[BUG] User cannot login after upgrade

### ISSUE THREAD

**Issue by manuelkamp** [paperless-ngx/paperless-ngx#7470]
### Description

User cannot login after Upgrade from 2.11.0 to 2.11.4
However, Admin can login.

### Steps to reproduce

Load Login page.
login as regular user.

### Webserver logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"OK","url":"https://docs.my.domain/api/ui_settings/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://docs.my.domain/api/ui_settings/: 403 OK","error":{"detail":"Sie sind nicht berechtigt diese Aktion durchzuführen."}}
```

### Paperless-ngx version

2.11.4

### Host OS

Ubuntu 22.04

### Installation method

Bare metal

### System status

```json
{
    "pngx_version": "2.11.4",
    "server_os": "Linux-6.8.12-1-pve-x86_64-with-glibc2.31",
    "install_type": "bare-metal",
    "storage": {
        "total": 21474836480,
        "available": 21346254848
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-04T00:00:01.886143+02:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Browser

Edge

### Configuration changes

none

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Users must be granted at least permissions for ui_settings to be able to log in.  This has been the case since 2.10.x, for example as mentioned [here](https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.10.1).

**Comment by shamoon** [comment]
And with all due respect, please search before opening up a bug report, I think it’s a fair ask for volunteer-maintained projects (we’re regular people like you)
