### ISSUE TITLE
[BUG] Enabling permission Sharelink for new user emits message: Object with codename=add_sharelink does not exist.

### ISSUE THREAD

**Issue by deddc23efb** [paperless-ngx/paperless-ngx#7491]
### Description

Setting up a new install and manually adding users.   For standard non-admin user I'm enabling Document, Tag, Correspondent and Sharelink.  Hitting save results in the rather unhelpful error message: Object with codename=add_sharelink does not exist.
Disabling sharelink allows the save.  

If there is a linkage between the permissions, it should be clearly set out in the documentation or the error message. If there is some aspect of the software that needs to be enabled, it should be described in the documentation or mentioned in the error message.  I can't tell if something is broken or I'm simply doing something incorrect.

### Steps to reproduce

Install docker latest for paperless-ngx with standard settings
Add an admin user during install script process.
In my case I've imported data from a V1 install of Paperless-ngx including documents tags etc via the export/import process
Login as admin user. Add a new user.  Select the Document, Tag, Correspondent and Sharelink. Press Save on the web ui  .. notice error.

### Webserver logs

```bash
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://belegost.rusmont.net:8000/api/users/4/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://belegost.rusmont.net:8000/api/users/4/: 400 Bad Request","error":{"user_permissions":["Object with codename=add_sharelink does not exist."]}}
```

### Paperless-ngx version

2.11.4

### Host OS

Ubuntu 22.04.4 LTS

### Installation method

Docker - official image

### Browser

Brave

### Configuration changes

Added a PAPERLESS_FILENAME_FORMAT to docker-compose.env

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Please provide full logs.

**Comment by deddc23efb** [comment]
I can recreate it at will. No logs appear in the webui paperless.log

**Comment by deddc23efb** [comment]
Additional information.  It appears to be related to having imported from paperless-ngx v1 .  I wiped my install and followed the same procedure but SKIPPED the import of old data.  Creating a new user with the limited set of permissions + Sharelink saves correctly with no error.   
I can recreate the issue by importing the data again from a clean install.

**Comment by shamoon** [comment]
Im going to close this because:

1. You have resolved the issue.
2. Unless you intend to provide us with the data export no one can re-create this or do anything about it.
3. Sharelinks have been around for a year with no known issues or recent changes.

Of course, feel free to add more context, if theres a real bug here we'd be happy to address.
