### ISSUE TITLE
[BUG] user require "view users" permission to view its info in API

### ISSUE THREAD

**Issue by landure** [paperless-ngx/paperless-ngx#7504]
### Description

I'm connecting to Paperless NGX using Paperless Mobile Android app.

The connection fails with a unauthorized error. My user isn't allowed to view users. It can't view his own information from API

I've allowed the user to view the users list. It fix the unauthorized error issue, but allow the user to view all paperless users.

### Steps to reproduce

1. Create a user without "View user" permission.
2. Authenticate to the API using the User login and Password (or Paperless Mobile).
3. Query the user own info from the API

### Webserver logs

```bash
[WARNING] [django.request] Forbidden: /api/users/4/
```

### Paperless-ngx version

2.11.4

### Host OS

Debian GNU/Linux 12 (bookworm) x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.4",
    "server_os": "Linux-6.1.0-18-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 1081099079680,
        "available": 592133406720
    },
    "database": {
        "type": "postgresql",
        "url": "paperless_paperless-domain-fr",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis:///0:None",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-20T11:02:08.758102+02:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
You are correctly describing how this permission works, “view_users” is required to… view users

**Comment by landure** [comment]
Yes, the issue is that a given user doesn't have automatic view permission on its own User object.

**Comment by shamoon** [comment]
There is an API endpoint for editing ones own profile.

Also, "should" generally implies a change request, i.e. it works one way but you want it to work another way, not a bug.
