### ISSUE TITLE
[BUG] Email Rule ignores subfolders

### ISSUE THREAD

**Issue by MegamikeMUC** [paperless-ngx/paperless-ngx#753]
### Description

Mail Rules are all working fine - except if I use a subfolder.
i.e. "INBOX.Archiv" for one of my Email accounts end in
`[2022-04-18 16:08:51,911] [ERROR] [paperless_mail] Rule CMRU.cmru paperless ordner: Error while processing rule: Rule CMRU.cmru paperless ordner: Folder INBOX.Archiv does not exist in account CMRU`

Of cource I tried different spellings and different folders and different Email-Accounts. For all account only the main folder is working

### Expected behavior

Mail rule should process only email in defined subfolder

### Steps to reproduce

see above

### Webserver logs

```bash
[2022-04-18 16:08:51,862] [DEBUG] [paperless_mail] Account CMRU: Processing 1 rule(s)

[2022-04-18 16:08:51,867] [DEBUG] [paperless_mail] Rule CMRU.cmru paperless ordner: Selecting folder INBOX.Archiv

[2022-04-18 16:08:51,911] [ERROR] [paperless_mail] Rule CMRU.cmru paperless ordner: Error while processing rule: Rule CMRU.cmru paperless ordner: Folder INBOX.Archiv does not exist in account CMRU

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 192, in handle_mail_rule

    M.folder.set(rule.folder)

  File "/usr/local/lib/python3.9/site-packages/imap_tools/folder.py", line 44, in set

    check_command_status(result, MailboxFolderSelectError)

  File "/usr/local/lib/python3.9/site-packages/imap_tools/utils.py", line 45, in check_command_status

    raise exception(command_result=command_result, expected=expected)

imap_tools.errors.MailboxFolderSelectError: Response status "OK" expected, but "NO" received. Data: [b"INBOX.Archiv doesn't exist."]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 177, in handle_mail_account

    total_processed_files += self.handle_mail_rule(M, rule)

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 194, in handle_mail_rule

    raise MailError(

paperless_mail.mail.MailError: Rule CMRU.cmru paperless ordner: Folder INBOX.Archiv does not exist in account CMRU
```

### Paperless-ngx version

1.6.0

### Host OS

Synology/ Docker

### Installation method

Docker

**Comment by shamoon** [comment]
Did you try different separators? Eg #550

**Comment by MegamikeMUC** [comment]
"I tried ". , | / \"

**Comment by stumpylog** [comment]
Just to be sure, the expected folder is named `INBOX.Archiv` not `INBOX.Archive` (the extra e there)?

**Comment by MegamikeMUC** [comment]
> Just to be sure, the expected folder is named `INBOX.Archiv` not `INBOX.Archive` (the extra e there)?

Good question, but yes, it`s German :-) - so "ARCHIV" is correct.

Meanwhile I found the following:

- If I choose only "Archiv" (wihout INBOX) it works. 
- This works only for folders on "top level", 
- this might be specific for MS exchange, because "posteingang" (German for INBOX) seems is NOT top level of  INBOX =:-\ - my "Archiv" is in the list of folders at the same level as "INBOX/Posteingang"
- but for each subfolder, no seperator seems to work, neither the subfolder is in "Archiv" nor in "Posteingang"

**Comment by stumpylog** [comment]
Despite IMAP being a standard, things really aren't standardized so much.  We can't really account for every variance in how mail servers decide folder structure is, but I think we could try to surface more information to the user in this error case.

I'm thinking in this case, where folder selection fails, we try to list out the account folders visible, before raising up the error.  Then a user can hopefully locate the folder they wanted in the listing.

**Comment by stumpylog** [comment]
With 1.7.0, there is now some additional checking and waiting around file consumption for both inotify and polling based setups.  These changes should resolve the issue.
