### ISSUE TITLE
[BUG] "File type text/html not supported" when importing .eml file

### ISSUE THREAD

**Issue by Lx** [paperless-ngx/paperless-ngx#7537]
### Description

I am attempting to import a .eml file into Paperless that I know to be well-formed.

Paperless is refusing to import this particular .eml file, stating that "File type text/html not supported".

It seems that something is erroneously identifying it as an HTML file.  (Granted, it is an email with HTML content.)

### Steps to reproduce

1.  Drag a particular .eml file, which I would be happy to provide privately, into the Paperless web interface.
2.  Observe that Paperless refuses to process the file.

### Webserver logs

```bash
[2024-08-25 02:06:13,075] [WARNING] [django.request] Bad Request: /api/documents/post_document/
```

### Paperless-ngx version

2.11.6

### Host OS

Synology NAS, `arm64`

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.6",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 7659800371200,
        "available": 3357810401280
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-25T01:49:57.450351+10:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-24T15:06:10.270886Z",
        "classifier_error": null
    }
}
```

### Browser

Brave

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
That means the file is malformed. Paperless relies on standardized libraries for identifying file types, so it’s not something we directly control anyway

**Comment by Lx** [comment]
Respectfully, this issue has been closed a little too hastily.  I examined the .eml file before creating this issue and it is not malformed.  Would you be willing to look at it to satisfy yourself of this?

**Comment by stumpylog** [comment]
As mentioned, if it is not detected by the standard libmagic, it's probably malformed at best and that's not an issue we can fix

**Comment by shamoon** [comment]
Indeed, no disrespect meant from this direction either.

It's not hasty, its just that I know how we determine mime_type:

https://github.com/paperless-ngx/paperless-ngx/blob/982eeb0d2431f08ee92e3599e3be50fa712da4d2/src/documents/serialisers.py#L1327
https://github.com/paperless-ngx/paperless-ngx/blob/982eeb0d2431f08ee92e3599e3be50fa712da4d2/src/documents/consumer.py#L538

So again, not something we control, and I suspect it has to do with the specific file, since in general .eml files work fine (with tika/gotenberg)

**Comment by Lx** [comment]
Thank you @shamoon for your further response—the two code references are very useful for me.

The .eml file in question is 100% compliant with RFC 5322, but I accept that the underlying `libmagic` library is falsely identifying it and causing the problem here.

At least I’m not alone: https://github.com/alephdata/ingest-file/issues/622 shows that at least one other person has had this exact problem (in another project).  I enjoyed this comment:

> Please note that the root cause of this problem is using libmagic, which actually _is_ a sort of we-don't-know-how-it-works-but-it-seems-to-work type of file type / mime-type detection. It can do wonders but it can also get things horribly wrong.

It’s also not the first time this issue has impacted a Paperless user: https://github.com/paperless-ngx/paperless-ngx/discussions/2374 documents a case where an email is mistakenly detected as `text/plain`.

### Workaround

My immediate options from here are:
- Manually convert emails to PDF before attempting import into Paperless
- Work out how to report this issue (if not already done) to the developers of `libmagic`.

### Possible fix (in Paperless)

Given that this is a known, ongoing `libmagic` deficiency though, would the Paperless team potentially consider a modification to the `validate_document` function along the lines of:

```py
def validate_document(self, document):
    document_data = document.file.read()
    mime_type = magic.from_buffer(document_data, mime=True)

    # Handle likely libmagic false negatives for .eml files
    if mime_type in ["text/html", "text/plain"]:
        # TODO: run document_data through eml-parser and if no errors, return success
        ...

    if not is_mime_type_supported(mime_type):
        raise serializers.ValidationError(
            _("File type %(type)s not supported") % {"type": mime_type},
        )

    return document.name, document_data
```

**Comment by shamoon** [comment]
No, we wouldn’t accept that unfortunately. And that linked issue isn’t exactly the same, but still, two cases a widespread problem does not make.

Unfortunately I do think the only real path is converting the files or yes, certainly we’d be happy to integrate any updates to libmagic if they were to address the issue.

**Comment by Lx** [comment]
Understood and accepted.  Thank you for engaging nonetheless.

**Comment by Lx** [comment]
For the benefit of anyone else chancing upon this issue in future:

- Current-day `libmagic` (and by extension, Paperless) is misidentifying any `.eml` file whose first header is `Subject:`.
  - This is **not** a non-conformance or malformation per RFC 822 or RFC 5322 as far as I can tell—just poor identification on `libmagic`'s part.
  - `libmagic` will currently only correctly identify emails with first headers of `Date:` or `From:`.
  - This means that in the meantime, one can at least manually reorder the headers in a `.eml` file before uploading and the file will be accepted by Paperless.

- I've raised this as a bug against `libmagic`:
  - [0000554: .eml file identified as text/html (should be message/rfc822) when "Subject:" header is first](https://bugs.astron.com/view.php?id=554)
  - I guess if/when it is resolved, I'll ask the Paperless maintainers to consider requiring a minimum `libmagic` version in their official Docker image/s.

**Comment by shamoon** [comment]
Appreciate you taking the time to raise an issue there. We’ll see

**Comment by vsessink** [comment]
> As mentioned, if it is not detected by the standard libmagic, it's probably malformed at best and that's not an issue we can fix

May I kindly suggest that libmagic is "a file type _guesser_"? Libmagic can do wonders - it can detect everything from Applixware Graphics to the Commodore 64 tape storage format - but there's no guarantee. And as paperless-ngx probably doesn't do, say, Applixware or Algol68, you may want to ponder a bit if your document type detection has just a bit too much hidden magic. Because no, a file doesn't have to be "malformed" to be misdetected by libmagic - at all.

**Comment by shamoon** [comment]
Looks like the issue was resolved, cool. Now just need it to trickle back to paperless :)

https://bugs.astron.com/view.php?id=554#c4097
