### ISSUE TITLE
[BUG] Too long texts break input fields

### ISSUE THREAD

**Issue by jonastaedcke** [paperless-ngx/paperless-ngx#7568]
### Description

When I use long text for the input fields I get to long input widths.

<img alt="grafik" src="https://github.com/user-attachments/assets/37a5da92-48e6-4e6e-bf0a-c55c36a9e083">

Thank you for your support and your great job! 

### Steps to reproduce

1. Open https://demo.paperless-ngx.com/dashboard
2. Open a [document](https://demo.paperless-ngx.com/documents/4/details)
3. Add a new correspondent, Document type or Storage path

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.11.6

### Host OS

x86_64

### Installation method

Docker - official image

### Browser

Firefox 129.0.2, Chrome 128.0.6613.85 (newest versions)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Not sure this qualifies as a bug.  Correspondents, document types, etc aren't meant to be novels, they are already limited in length in the backend.

**Comment by jonastaedcke** [comment]
One of my document types is `Rechnung, Bon, Kostenvoranschlag, Gewährleistung, Zahlungserinnerung, Mahnung` (is's German for `Invoice, receipt, cost estimate, warranty, payment reminder, overdue notice`. I group some types to one.

This is not a bug in the backend. The input fields should behave differently.

My real world example:
<img width="596" alt="grafik" src="https://github.com/user-attachments/assets/de0f0687-5c41-4606-905f-03a280c5fed6">
