### ISSUE TITLE
[BUG] sed: 1: "docker-compose.yml": extra characters at the end of d command

### ISSUE THREAD

**Issue by kshitijzutshi** [paperless-ngx/paperless-ngx#7576]
### Description

Screenshot of issue as run on MacOS Sonoma 14.6.1 (23G93) M2 MacBook Pro

![image](https://github.com/user-attachments/assets/7e7e5e8f-b1c6-42a0-bcfc-7ea120a270fd)

### Steps to reproduce

Error encountered when using docker compose to install paperless-ngx

`bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`

### Webserver logs

```bash
Screenshot attached in description
```

### Paperless-ngx version

2.11.6

### Host OS

MacOS Sonoma 14.6.1 (23G93)

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

No changes made

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
What does the secret key generation command output?  Macos is weird and not really compliant to normal posix things

**Comment by shamoon** [comment]
There is a note in the docs for this specifically. I run the script on macOS frequently.

![image](https://github.com/user-attachments/assets/3f18e637-ee40-4cbf-b2b4-cd2def7239b4)

**Comment by kshitijzutshi** [comment]
> There is a note in the docs for this specifically. I run the script on macOS frequently.
> 
> ![image](https://private-user-images.githubusercontent.com/4887959/362866121-3f18e637-ee40-4cbf-b2b4-cd2def7239b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NjUzNDUsIm5iZiI6MTcyNDk2NTA0NSwicGF0aCI6Ii80ODg3OTU5LzM2Mjg2NjEyMS0zZjE4ZTYzNy1lZTQwLTRjYmYtYjJiNC1jZDJkZWY3MjM5YjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMjA1NzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGFlYTc1NTQ4NGM0OWZlMmQ3NDdmOTQ5NTI5OWYwNjkzYzJmYjZlM2RhM2MzZWZiZTZlNzEyZDdiYTc4MTdkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.06ooAxWyNr4fxq-QW649WMxJUlPwd38ExoMUOrlTDN4)

I did see it and have installed gnu-sed using homebrew, yet I get same error.

**Comment by shamoon** [comment]
And did you install it into your PATH like the install instructions (for gnu-sed) say?

If you dont, this is the exact error you get, so I'm still very suspicious thats all this is.
