### ISSUE TITLE
[BUG] filename has wrong scheme when document gets downloaded

### ISSUE THREAD

**Issue by naishweb** [paperless-ngx/paperless-ngx#7597]
### Description

If i download a stored document, the filename (suggestion if your browser asks) is different to the scheme it was saved in paperless.

i.e.:
store path scheme is: file/path/{correspondent}/{created_year}/{created_year}{created_month}{created_day} - {correspondent} - {title}

results in

YYYY-MM-DD Correspondent - Title.pdf
 

### Steps to reproduce

assuming you already have a correspondent with an customized file name as written above and a document which is assigned to

1. pick the document
2. click download
3. check filename in local file structure

### Webserver logs

```bash
If i can assist with any logs it would be very kind to tell me which
```

### Paperless-ngx version

2.11.6

### Host OS

Linux x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.6",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 11503316021248,
        "available": 565406183424
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-01T18:05:29.284618+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-01T16:07:45.382906Z",
        "classifier_error": null
    }
}
```

### Browser

behaviour appears in all actual versions of safari, edge, chrome, firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The downloaded filename is not controllable by any setting.

**Comment by stumpylog** [comment]
#5153

**Comment by shamoon** [comment]
This is not a bug, that’s expected. If you download in bulk from the documents page there’s an option for this.
