### ISSUE TITLE
[Other] The image should be pushed to Docker hub

### ISSUE THREAD

**Issue by sbrunner** [paperless-ngx/paperless-ngx#76]
All is in the title, if nobody is working on that I can work on that next week :-)

**Comment by sbrunner** [comment]
Or specify and use the github.io in the Readme and in the Docker compose files

**Comment by yschroeder** [comment]
I think we decided to push the images to ghcr.io. Not sure if that is finished yet.

**Comment by qcasey** [comment]
GHCR is easier to manage, one fewer account. I updated the build script in #62 to push to the [registry](https://github.com/orgs/paperless-ngx/packages?repo_name=paperless-ngx). 

Updating the readme and docs with GHCR.io still needs to be done, however

**Comment by yschroeder** [comment]
Can this be closed? Or is there still something missing?

**Comment by isigmund** [comment]
I believe this can be closed, since the change to ghcr.io in the compose*.yml files has been merged by now

**Comment by lukeIam** [comment]
> Can this be closed? Or is there still something missing?

I guess here are two urls missing:
https://github.com/paperless-ngx/paperless-ngx/blob/main/install-paperless-ng.sh#L280

**Comment by shamoon** [comment]
dev: https://github.com/paperless-ngx/paperless-ngx/blob/2f7c351039e6359c5e1a69d912768e9ef782d7a2/install-paperless-ngx.sh#L281
