### ISSUE TITLE
[BUG] High memory usage when indexing large installation

### ISSUE THREAD

**Issue by slundell** [paperless-ngx/paperless-ngx#7615]
### Description

In our current installation we store 70k+ documents and we do experience a few problems with building the index. Often it cannot be completed within the given timeout, but that has been extended. As the index is not committed to disk until after it is complete, one have to restart the entire build if it fails. The most limiting factor is however the amount of memory required to rebuild the index. It currently use above 32 Gb, and, depending on what other processes are running, might be OOM-killed.

In my limited understanding, it seems that the reindexing process starts by loading _all_ documents, and then indexes them one at the time, and then commits the entire index to disk. One way to reduce memory usage might be to read in the documents in smaller chunks, of a few hundred at the time. 

A `refresh`-option would be a godsend.  It will then only reindex documents which is not already in the index. That would allow for a restart if the refresh fails.

### Steps to reproduce

1. import 70000 documents
2. observe that you do not have a index because it once failed for some reason.
3. try to rebuild the index with `document_index reindex`
4. observe memory usage

### Webserver logs

```bash
From host

CPU%   MEM%  VIRT  RES       PID USER          TIME+ THR  NI S  R/s W/s  Command ('e' to pin | 'k' to kill)
 >91.0  52.3  34.7G 32.9G 1665906 wpu            4:46 34    0 R    0 33K  python3 manage.py document_index -v3 --traceback --force-color reindex
```
```


### Browser logs

_No response_

### Paperless-ngx version

2.11.6

### Host OS

 Ubuntu 20.04 64bit AMD Ryzen 5 3600 6-Core

### Installation method

Docker - official image

### System status

```json
System Status

Environment
Paperless-ngx Version
2.11.6
Install Type
docker
Server OS
Linux-5.4.0-107-generic-x86_64-with-glibc2.36

Media Storage
3.02 TB available (5.41 TB total)

Database
Type
postgresql

Status
OK

Migration Status
Up to date

Tasks
Redis Status
OK

Celery Status
OK

Search Index
OK

Classifier
OK
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
- documents are updated in the index as actions are taken already
- documents are not all loaded into memory by paperless, we iterate through one at a time
- the actual index creation, building and saving to disk is fully implemented by whoosh.  

You're welcome to investigate and find out more, but this is almost entirely out of Paperless code
