### ISSUE TITLE
[BUG] Sort order with special character

### ISSUE THREAD

**Issue by datenwort** [paperless-ngx/paperless-ngx#7622]
### Description

I stored documents in paperless by naming `text month/year`. After sorting them by title I got a strange view. The sorting stops at the `/`

It looks like

`xxx 01/2021
xxx 01/2022
xxx 01/2023
xxx 02/2021
xxx 02/2022
xxx 03/2022`

### Steps to reproduce

The steps to this behaviour are

`Select by title xxx`
`sort by title desc`

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.11.6

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

-

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Not sure what you're expecting but this seems like normal sort to me. feel free to provide more context if I’m missing something

![asc](https://github.com/user-attachments/assets/6457af6e-96e1-41e1-b73b-630eb1b45dcd)
![desc](https://github.com/user-attachments/assets/135ce30b-a923-47a7-b7a6-06c39388dfd9)

**Comment by datenwort** [comment]
Please add 02/2021 and 02/2022

I expect the following sort order

xxx 01/2021 
xxx 02/2021 
xxx 01/2022 
xxx 02/2022 
xxx 03/2022
xxx 01/2023

**Comment by datenwort** [comment]
Thank you for clarifying. I had a mistake in thinking. Can be closed
