### ISSUE TITLE
[BUG] v1.7.0 RC1 Bug: Mail Actions are mixed up

### ISSUE THREAD

**Issue by p-h-a-i-l** [paperless-ngx/paperless-ngx#763]
### Description

Mail Actions are completely mixed up, instead of marking Mails as read, they are being deleted.

https://github.com/paperless-ngx/paperless-ngx/blob/09d62d76b27cc769b289d3f419a1455785c08161/src/paperless_mail/models.py#L63-L67

### Expected behavior

Actions on Mails are performed as selected and described.

### Steps to reproduce

1. Add new Mail rule: http://localhost:8000/admin/paperless_mail/mailrule/add/ 
2. Set Action to mark as read
3. observe Mail being deleted

### Paperless-ngx version

v1.7.0 RC1

### Host OS

Archlinux

### Installation method

Bare metal

**Comment by shamoon** [comment]
Great catch, thank you

@stumpylog I think this is from https://github.com/paperless-ngx/paperless-ngx/commit/f358eda5c5045bd6859f17062e1afcb865d7426e but Im happy to make a PR later, looks like literally just lines need to be moved?

**Comment by stumpylog** [comment]
Whoops, I swear I tried to be careful.  Yes, the help text or whatever it is called needs to be moved around to match, then a migration created probably.

**Comment by p-h-a-i-l** [comment]
already working on a PR. Should this be against beta?

**Comment by shamoon** [comment]
Thank you! Yes to `beta`

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/68e3612d36502a9531946b2280a527dcf24ffdc8
