### ISSUE TITLE
[BUG] Google invoice throws with "File type application/octet-stream not supported"

### ISSUE THREAD

**Issue by draptik** [paperless-ngx/paperless-ngx#7634]
### Description

Google Invoice is not parsed.
Direct upload and automatic mail scan both fail.

Error message:

File type application/octet-stream not supported

Importing Google Invoices in the past was never a problem. So either Google Invoice changed something in their PDF, or there is a regression bug in paperless. I don't know.

### Steps to reproduce

Upload a google invoice newer than 2024-08.

### Webserver logs

```bash
[2024-09-06 00:13:42,434] [ERROR] [paperless.consumer] Unsupported mime type application/octet-stream

[2024-09-06 00:13:42,435] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: 5052774727.pdf: Unsupported mime type application/octet-stream

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 149, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 550, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 304, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: 5052774727.pdf: Unsupported mime type application/octet-stream
```

### Paperless-ngx version

2.11.6

### Host OS

Archlinux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Its hard to believe that you searched first.

https://github.com/paperless-ngx/paperless-ngx/issues/7239
https://github.com/paperless-ngx/paperless-ngx/issues/6499
https://github.com/paperless-ngx/paperless-ngx/issues/776

**Comment by draptik** [comment]
@shamoon thanks for the pointers to the other issues.
Sadly, they don't provide a solution.

As Google is a global player, it would be nice if they conform to standards. They don't. And I doubt we can change that fact.
So we have to manipulate the input from Google - invoice -> convert to valid pdf -> upload
Correct?

**Comment by shamoon** [comment]
Yes, unfortunately. And in general it seems the more global the player the less they care about other peoples standards 😕

It might be interesting to see if we could somehow recover these for the user (but that’s obviously a feature request kinda thing)

**Comment by draptik** [comment]
My "bug report" might not be a "bug".
Maybe my "problem" is something for a FAQ?

**Comment by stumpylog** [comment]
If you can share one of these, I'm curious about something with them. You can do it privately in matrix as well

**Comment by shamoon** [comment]
stumpylog take a look at feature-autoclean-pdfs (and https://github.com/paperless-ngx/paperless-ngx/blob/b26901ee82ade174294f0c93ab70b9d3568c8009/src/documents/tests/samples/invalid_pdf.pdf )
