### ISSUE TITLE
[BUG] nltk error when uploading certain pdf

### ISSUE THREAD

**Issue by Tropaion** [paperless-ngx/paperless-ngx#7666]
### Description

Cannot upload a specific pdf file:
![image](https://github.com/user-attachments/assets/646189ce-a194-4be1-8b01-ae816ff4a6ec)

### Steps to reproduce

Upload file via file browser or dropping it into paperless.

### Webserver logs

```bash
Sep 09 22:47:14 Paperless celery[593]:   Resource punkt_tab not found.
Sep 09 22:47:14 Paperless celery[593]:   Please use the NLTK Downloader to obtain the resource:
Sep 09 22:47:14 Paperless celery[593]:   >>> import nltk
Sep 09 22:47:14 Paperless celery[593]:   >>> nltk.download('punkt_tab')
Sep 09 22:47:14 Paperless celery[593]:   
Sep 09 22:47:14 Paperless celery[593]:   For more information see: https://www.nltk.org/data.html
Sep 09 22:47:14 Paperless celery[593]:   Attempted to load tokenizers/punkt_tab/english/
Sep 09 22:47:14 Paperless celery[593]:   Searched in:
Sep 09 22:47:14 Paperless celery[593]:     - PosixPath('/usr/share/nltk_data')
Sep 09 22:47:14 Paperless celery[593]: **********************************************************************
```

### Paperless-ngx version

2.12.0

### Host OS

Debian12

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please search
