### ISSUE TITLE
[BUG] mime-support has no installation candidate in 24.04

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/paperless-ngx#7684]
### Description

Hi there, this is for the bare metal route. If one uses Ubuntu >22.xx then there is an issue with the package mime-support that did not make it to the package list.
![image](https://github.com/user-attachments/assets/a314761d-ef2d-4e4d-9304-9784391812c5)

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package mime-support is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  media-types mailcap

E: Package 'mime-support' has no installation candidate
```

linked to 
* https://github.com/paperless-ngx/ansible/issues/186
* https://github.com/paperless-ngx/ansible/pull/179

Is there a chance for substitution?

### Steps to reproduce

install mime-support on Ubuntu 24.xx

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

n/a

### Host OS

n/a

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
It is included in our setup guide https://github.com/paperless-ngx/paperless-ngx/blob/66a8057e315dbc1888fabff91005d07b4f66df25/docs/setup.md#L272 / https://github.com/paperless-ngx/paperless-ngx/blob/66a8057e315dbc1888fabff91005d07b4f66df25/docs/setup.md#L279 so I guess id its not needed it can just be removed from there

**Comment by stumpylog** [comment]
I can't really test it easily, but for the op, does anything appear to not work without it?

**Comment by shamoon** [comment]
I think I can confirm works fine in 24.04: #7689 so I suppose question is whether older ones might need it?

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/pull/7689
