### ISSUE TITLE
[Documentation] PAPERLESS_GPG_DECRYPTOR in Docs but not in Code

### ISSUE THREAD

**Issue by stevenengland** [paperless-ngx/paperless-ngx#7686]
### Description

`PAPERLESS_GPG_DECRYPTOR` appears in docs but not in code. I think `PAPERLESS_ENABLE_GPG_DECRYPTOR` is meant.

### Steps to reproduce

n/a

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

n/a

### Host OS

n/a

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
#7688
