### ISSUE TITLE
[BUG] Filtering of tags does not work with "true" or "false"

### ISSUE THREAD

**Issue by systemmonkey42** [paperless-ngx/paperless-ngx#7698]
### Description

When viewing documents and trying to either Filter by tags or select tags to apply, the tag filter ignores the words
"true" and "false", and any substring thereof, in any capitalization.

UPDATE:
I quickly realized the response from '/api/tags' includes the JSON structure:
```json
        {
            "id": 98,
            "slug": "sometag",
            "name": "sometag",
            "color": "#7f4ad1",
            "text_color": "#ffffff",
            "match": "",
            "matching_algorithm": 6,
            "is_insensitive": true,
            "is_inbox_tag": false,
            "document_count": 1,
            "owner": 4,
            "user_can_change": true
        },
```
This includes the text "true" and "false" as field.  As a test, I filtered on "7f4" (the tag color) and quickly found the tag.

So I think the error is more along the lines of: TAGS should be filtered  on the tag name, not the entire JSON string.

Regards

### Steps to reproduce

1. Go to documents view
2. Select the "Tags" dropdown.
3. Start typing "true" or "false" into the filter string.
4. Note that the "unassigned" option disappears, however the list is not filtered.

Note that substrings of "true" and "false", such as "lse", will also not filter. 

### Webserver logs

```bash
no logs generated
```

### Browser logs

```bash
no logs generated
```

### Paperless-ngx version

2.12.0

### Host OS

Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Cute little bug, thanks
