### ISSUE TITLE
[BUG] Docker scripts sets incorrect value for PAPERLESS_OCR_LANGUAGES

### ISSUE THREAD

**Issue by MateoPeri** [paperless-ngx/paperless-ngx#770]
### Description

When running the startup script the user is prompted for a list of languages, separated by `+` (eg. `eng+nld+spa`).

This sets the `PAPERLESS_OCR_LANGUAGE` variable in `docker-compose.env` to `eng+nld+spa` (expected), for paperless to use as OCR. 

However, it also sets the list of languages to install (`PAPERLESS_OCR_LANGUAGES`, note the final "S") to the same value. When trying to install the script will fail with error `Package tesseract-ocr-eng+nld+spa not found! :(`. I had to manually change `PAPERLESS_OCR_LANGUAGES` to `eng nld spa` (spaces instead of `+`).

### Expected behavior

The scripts sets the correct variables separately, with their respective formats.

### Steps to reproduce

1. Run the script from the docs: `bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/master/install-paperless-ngx.sh)"`
2. Add a list of `+`-separated languages when prompted.

### Paperless-ngx version

1.6.0

### Host OS

Synology

### Installation method

Docker

### Other

I will try to open a PR later this week.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/d98bfa5bede015055b03f47956d9d2b09954b20f
