### ISSUE TITLE
[BUG] Beta: Delayed Button Progress Not Visible

### ISSUE THREAD

**Issue by stumpylog** [paperless-ngx/paperless-ngx#771]
### Description

When performing an operation which opens a delayed button, the delayed progress bar isn't visibly counting down/decreasing.

### Expected behavior

Expect the line to decrease as from #415

### Steps to reproduce

1. Select multiple docs
2. Press delete
3. Observe button

### Webserver logs

```bash
Nothing applicable in webserver.

In the developer console, a warning about `Cross-Origin-Opener-Policy`
```

### Screenshots

Button looks like this until enabled:
![image](https://user-images.githubusercontent.com/797416/164120710-2e864ed8-d056-4202-ac35-55f98fff0c90.png)

### Paperless-ngx version

1.7.0 (beta image)

### Host OS

Ubuntu 20.01

### Installation method

Docker

### Browser

Google Chrome, Version 101.0.4951.34 (Official Build) beta (64-bit)

**Comment by stumpylog** [comment]
Looks related to my using dark mode.  If I disable that, either through the browser or settings page, the bar is visible again

**Comment by shamoon** [comment]
Thanks stumpy!

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/44d6db8c47f4332cac716fafe816539798d649da
