### ISSUE TITLE
[BUG] User is able to delete pages even with read-only permissions

### ISSUE THREAD

**Issue by marzlberger** [paperless-ngx/paperless-ngx#7713]
### Description

I have a user who basically only has view permissions. This user can open and view a page. The delete button is not visible, which is correct.

**But!

It is possible to remove individual pages from the original PDF document using the Actions menu.
The correct behavior should be that even file manipulations are not possible.

### Steps to reproduce

- Assign view-only rights to a user
- Login with this user
- use the action to delete pages from an existing document

### Webserver logs

```bash
none
```

### Paperless-ngx version

2.12.0

### Host OS

Alpine Linux

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.0",
    "server_os": "Linux-6.6.51-0-virt-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 2274262908928,
        "available": 2270932762624
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-15T17:11:24.354256+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-15T22:05:05.321619Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I think your setup is incorrect somehow. If the user viewing the document is not the owner the delete pages is disabled:

<img width="194" alt="Screenshot 2024-09-15 at 3 41 47 PM" src="https://github.com/user-attachments/assets/b0f33b0c-4464-4f08-8382-367e1f126d8b">

https://github.com/paperless-ngx/paperless-ngx/blob/36df6fd3e5c62db164d8f4578da636ddcc3fdf39/src-ui/src/app/components/document-detail/document-detail.component.html#L64

And indeed trying anyway (by editing the html) will fail:
<img width="363" alt="Screenshot 2024-09-15 at 3 42 47 PM" src="https://github.com/user-attachments/assets/c93f1586-1400-4612-ba2d-dddb33d0074f">

If theres more context feel free to provide

**Comment by marzlberger** [comment]
ok, that is globally good and thankfully not bug. But anyhow i wonder what is the case for my read only user.
This user is even not the owner of the file and is still able to delete pages. This user comes from the past and was created long time/versions ago.

I have added another fresh user and the problem is still there.

![grafik](https://github.com/user-attachments/assets/6305c7e4-0eb2-4fd3-a28b-db65c746b951)
![grafik](https://github.com/user-attachments/assets/f8e9b120-a7d0-4794-8e37-bfbd731215ff)
![grafik](https://github.com/user-attachments/assets/34455285-584c-42dc-9fc0-4e692b95c618)

Strangely another document, with exactly the same permissions is correct
![grafik](https://github.com/user-attachments/assets/3a7862b7-6b3b-499f-8564-b61f7bd2179d)

What is your advice?

**Comment by marzlberger** [comment]
I have seen that you have pushed this request:
Ist that related? https://github.com/paperless-ngx/paperless-ngx/pull/7714

**Comment by marzlberger** [comment]
I have upgraded to the latest Version with docker-compose and 2.12.1 is installed
There are still documents available, which are allowing to delete pages een though they do not have any owner:

![grafik](https://github.com/user-attachments/assets/6a726eb7-ae12-41aa-a938-93e9614cb859)

**Comment by shamoon** [comment]
See https://github.com/paperless-ngx/paperless-ngx/issues/7713#issuecomment-2351818923

There are three cases where the delete pages option is disabled:

1. user is not owner. If there is no owner then everyone effectively is
2. if the file is not a pdf
3. if the file is detected to have only 1 page.

**Comment by marzlberger** [comment]
ok, i have assigned alle documents to user A.
Group A has read rights on those documents.
User B is assigned to a group A
User B is not able to delete pages any longer.

Case closed, thanks for the help.
