### ISSUE TITLE
[BUG] PAPERLESS_ACCOUNT_SESSION_REMEMBER not being recognized

### ISSUE THREAD

**Issue by oeiber** [paperless-ngx/paperless-ngx#7733]
### Description

I'm using latest stable (2.12.1). Setting Environmet variable PAPERLESS_ACCOUNT_SESSION_REMEMBER as implementet in #6105 makes no difference: Regardles if the value is set to "true", "false" or left unset, the session cookie's expiry is always set to 14 days.

### Steps to reproduce

1. Clearing session cookie
2. Setting PAPERLESS_ACCOUNT_SESSION_REMEMBER to true --> cookie sessionid expiry: 14 days
3. Clearing session cookie
4. Setting PAPERLESS_ACCOUNT_SESSION_REMEMBER to false --> cookie sessionid expiry: 14 days

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.12.1

### Host OS

Debian 12 aarch64

### Installation method

Docker - official image

### Browser

Edge, Chrome, Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
The setting is directly passed to all-auth, which makes no mention of time for the setting in its documentation. What makes you think it should change the time?

And basics, you have cleared the cookies after changing it right?

**Comment by shamoon** [comment]
I get the feeling the allauth setting has been deprecated or something. I think I see the problem, I cant look into it more until later but essentially I think its:

https://github.com/pennersr/django-allauth/blob/c031add73ccac4d2f8517037a99d56d2598377f9/allauth/account/forms.py#L199-L205

**Comment by shamoon** [comment]
Yea, I take it back. This works fine:

<img width="1094" alt="Screenshot 2024-09-18 at 4 19 58 PM" src="https://github.com/user-attachments/assets/c3d19e31-27a6-4523-8287-fe19f0d2ff7a">

In fact the snippet above sorta confirms it. `remember` will be the value of this setting, if its false expiry will be set to 0 which will expire after the browser session.

Make sure youre re-creating the container after changing environment variables.

If false:
<img width="1118" alt="Screenshot 2024-09-18 at 4 22 58 PM" src="https://github.com/user-attachments/assets/520c3d8a-70bb-426b-8960-cce6cc3f45cc">

**Comment by oeiber** [comment]
Thank you for investigating. But for me it's not working:
- Set environment varialbe PAPERLESS_ACCOUNT_SESSION_REMEMBER=false
- Recreate container
- Clear Browser's cache

![image](https://github.com/user-attachments/assets/a1d62ed0-fb34-4f06-9bfc-839824a5ca56)

I'm using oidc with goauthentik. Regular login is disabled entirely. Maybe the problem is related to the oidc provider?

**Comment by shamoon** [comment]
Yea that would have been relevant information to include.

I believe it doesnt work with oidc, https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/sessions.py . You can always ask over at the allauth project

**Comment by oeiber** [comment]
I think you're right. It covers "regular logins" only. Maybe it is suitable to implement django's configuration option for session expiration (SESSION_COOKIE_AGE: [(https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-age]) as well? For my opinion this option would cover both, regular logins and social accounts as well. What do you think?

**Comment by shamoon** [comment]
Yes that was [my plan](https://github.com/paperless-ngx/paperless-ngx/tree/feature-7733)

**Comment by oeiber** [comment]
Thank you!
I tried it, but it don't work as aspected: Setting the value greater 0 sets the cookie to the expected value. But setting it to 0, which usually means "Session", breaks oidc authentication entirely.

**Comment by oeiber** [comment]
Maybe this is the right option to expire session on browser close: [SESSION_EXPIRE_AT_BROWSER_CLOSE(https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-SESSION_EXPIRE_AT_BROWSER_CLOSE)

**Comment by shamoon** [comment]
This sounds like something you should report to allauth

**Comment by shamoon** [comment]
Ok #7748 should put an end to this and avoid making things more confusing by adding a third setting, essentially it makes `PAPERLESS_ACCOUNT_SESSION_REMEMBER` work the same for SSO and non-SSO.

**Comment by oeiber** [comment]
Thank you for your help! Now it's working as expected. 👍
