### ISSUE TITLE
[BUG] "UISettings" "Add" Permissions and permanent dialog box "Start the tour" on Dashboard

### ISSUE THREAD

**Issue by ctout76** [paperless-ngx/paperless-ngx#7736]
### Description

When the "Add" permission of "UISettings" is not enabled on a user, the dialog box "Start the tour" is displayed on the Dashboard each time you reconnect or refresh the page, even if all steps are completed or the dialog box is closed.

Once "Add" of "UISettings" is enabled, the Dashboard is displayed normally, the dialog box "Start the tour" no longer appears.

![Start the tour](https://github.com/user-attachments/assets/a9483aa8-98b9-41fa-8231-75946ad8045f)

User permissions causing problems

![user](https://github.com/user-attachments/assets/503f5493-313c-43c5-b217-30fcd287dbca)

### Steps to reproduce

Uncheck    "Add"   "UISettings" permissions on a user

### Webserver logs

```bash
No Logs
```

### Paperless-ngx version

2.12.1

### Host OS

Linux

### Installation method

Docker - official image

### Browser

Mozilla Firefox - Brave

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
If you disallow UI settings permissions then it cant record completion of the tour.
