### ISSUE TITLE
[BUG] Missing Repo for Helm-Chart

### ISSUE THREAD

**Issue by genofire** [paperless-ngx/paperless-ngx#7737]
### Description

In this PR @alexander-bauer wanted to create a dedicated Repo for Helm:

https://github.com/paperless-ngx/paperless-ngx/pull/2119#issuecomment-1374932540

### Steps to reproduce

1. create repo
2. put there the data

### Webserver logs

```bash
*
```

### Paperless-ngx version

*

### Host OS

*

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not a bug

**Comment by genofire** [comment]
okay a removed function instatt of called a migration ... ;(
