### ISSUE TITLE
[BUG] Missing scroll bar

### ISSUE THREAD

**Issue by joergmahn** [paperless-ngx/paperless-ngx#7785]
### Description

The scroll bar on the left sidebar is missing. Neither when folded nor when unfolded.

![2024-09-27 08_04_54-Startseite - Paperless-ngx und 10 weitere Seiten - Persönlich – Microsoft​ Edge](https://github.com/user-attachments/assets/c168decf-3b1c-43c2-938e-fa161bb58c4f)
Browser: Microsoft Edge

### Steps to reproduce

1. Open Paperless-ngx
2. Try to open the items under Administration e.g. Users and Groups or File Tasks

### Webserver logs

```bash
Protocols cannot be opened either because they are not accessible without the scroll bar.
```

### Paperless-ngx version

2.12.1

### Host OS

Linux-5.15.0-122-generic-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-5.15.0-122-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 21766418194432,
        "available": 10963792224256
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-27T08:01:16.187740+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-27T06:05:11.657837Z",
        "classifier_error": null
    }
}
```

### Browser

Microsoft Edge, Version 129.0.2792.52 (Offizielles Build) (64-Bit)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is already fixed in our next release.
