### ISSUE TITLE
[BUG]  Comma is deleted and cursor jumps to Pos1 when deleting the first number after the comma in a Custom Field "Currency"

### ISSUE THREAD

**Issue by MrMoep** [paperless-ngx/paperless-ngx#7790]
### Describe the bug

I tried to write an amount of money in the custom currency field and made a typo directly after the comma. (16,7 instead of 16,8). I deleted the last number and the comma is automatically erased and the cursor jumps to the beginning. So if I try to change 16,7 to 16,8 it changes to 816).

![2024-09-26 17_18_23](https://github.com/user-attachments/assets/a15bbd58-83d2-4b1a-a94b-6ae34b36e92d)
![2024-09-26 17_18_32](https://github.com/user-attachments/assets/3a3ea420-1237-4f52-8293-23a193111be5)
![2024-09-26 17_18_43](https://github.com/user-attachments/assets/546d789d-a6f8-4e81-aee2-8c6328a9a54b)

### Expected behavior

The already typed comma shouldn't be deleted and the cursor shouldn't change position.

### Steps to reproduce

1. Use chrome as a browser (it seems to work with Firefox)
2. Go to a document with a custom field "currency"
3. Type a number with at least one number after the comma
4. Delete the numbers after the comma

### Webserver logs

```bash
### Relevant log output

_No response_
```

### Paperless-ngx version

2.12.0

### Host OS

Unraid 

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.0",
    "server_os": "Linux-6.1.99-Unraid-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 4998549946368,
        "available": 4912330072064
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://192.168.188.24:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-27T00:01:07.720667+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-27T09:05:06.032976Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome (it works with firefox)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
There is a debounce on the field after which it’s going to try and interpret the value which does stuff like this. Feel free to submit a PR otherwise honestly, I think it’s fine.
