### ISSUE TITLE
[BUG] Documents with separator pages all get the same "date created"

### ISSUE THREAD

**Issue by Gauss23** [paperless-ngx/paperless-ngx#7794]
### Description

I have a document with 50 pages (invoices). Those are separated with the PATCH-T barcode pages. Splitting works fine but all separated documents get the "date created" from the first page. When downloading one of the documents, deleting the file from Paperless and reuploading the single downloaded invoice, the date is calculated correctly. I thought maybe it's an option to reprocess the splitted documents, but this doesn't change the "date created". I assume because the field holds already data.

I would assume that each splitted document gets its own "date created" from a date found in the document.

### Steps to reproduce

- Create a document with multiple pages with different "date created" dates
- put PATCH-T pages after each document
- Upload the document to Paperless
- check the splitted documents
- they have all the same "date created" as the first document in the batch 

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.12.1

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-6.8.12-1-pve-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 21474836480,
        "available": 17689608192
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-27T00:00:01.028465+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-27T13:05:00.301643Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome, Opera, Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
If configured https://docs.paperless-ngx.com/configuration/#PAPERLESS_FILENAME_DATE_ORDER
