### ISSUE TITLE
[BUG] Error when fetching mails with IMAP (amount of mails might be too large to fetch at once)

### ISSUE THREAD

**Issue by tobi1449** [paperless-ngx/paperless-ngx#7799]
### Description

Currently, when paperless tries to fetch new mail from my account, it always results in "Error while processing rule: UID command error: BAD [b'Error in IMAP command UID FETCH: Too long argument". 
[This post on stackoverflow](https://stackoverflow.com/questions/70456990/imap-command-uid-fetch-too-long-argument) points to the problem being that the amount of mails paperless tries to fetch is too large to fetch at once.
Per [the documentation of imap_tools](https://pypi.org/project/imap-tools/#basic) it might be a good idea to set `bulk=<number>` to load mails in <number> batches instead of `bulk=true` which tries to load all mails at once.

### Steps to reproduce

1. Add a mail account to paperless
2. Fill the mail account with a large number of mails
3. Let paperless try to fetch them all at once

### Webserver logs

```bash
[ERROR] [paperless_mail] Rule Mailbox.org.Default: Error while processing rule: UID command error: BAD [b'Error in IMAP command UID FETCH: Too long argument (0.001 + 0.298 + 0.297 secs).']

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 518, in handle_mail_account

    total_processed_files += self._handle_mail_rule(

                             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 586, in _handle_mail_rule

    for message in messages:

  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 187, in fetch

    for fetch_item in message_generator:

  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 151, in _fetch_in_bulk

    fetch_result = self.client.uid('fetch', ','.join(uid_list_i), message_parts)

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/imaplib.py", line 890, in uid

    typ, dat = self._simple_command(name, command, *args)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/imaplib.py", line 1230, in _simple_command

    return self._command_complete(name, self._command(name, *args))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/imaplib.py", line 1055, in _command_complete

    raise self.error('%s command error: %s %s' % (name, typ, data))

imaplib.IMAP4.error: UID command error: BAD [b'Error in IMAP command UID FETCH: Too long argument (0.001 + 0.298 + 0.297 secs).']
```

### Paperless-ngx version

2.9.0

### Host OS

Debian

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.9.0",
    "server_os": "Linux-6.1.0-25-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 267887210496,
        "available": 76680679424
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "socialaccount.0006_alter_socialaccount_extra_data",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-09-28T00:00:06.756716+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-09-28T15:05:00.658098Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This doesn’t seem like a bug, it seems like you have too many emails like you said.

If you’d like to open a change / feature request for that change that would be fine, but clearly this is not an issue for the vast vast majority of users.

feel free to add more context of course, but I’ll close this for now.

**Comment by stumpylog** [comment]
Or consider adding some filters. Most of those are server side and will reduce the amount fetched

**Comment by tobi1449** [comment]
I've had a look at this again, is there any way to see what query paperless sends for the fetch command?
Because I've already imported most of my mails earlier, the import simply stopped working about a month ago. 
Therefore, most of my mails are already tagged and should be ignored by paperless.
A quick search showed ~600 mails in my inbox that have an attachment, but were not tagged yet. 
However when I quickly edited the bulk parameter I've mentioned above, the paperless log said it has imported 16k mails ...

**Comment by shamoon** [comment]
I'm on my phone at the moment so a bit limited but my googling doesn't yield the same suggestion as what you're saying that this has to do with too many emails vs a problem with a specific message but I'm not sure

No I don't believe our logs don't currently output the imap commands but if you're editing the source shouldn't be too hard to add
