### ISSUE TITLE
[BUG] Destination folder existence not checked / no log for failure to move message

### ISSUE THREAD

**Issue by mrichtarsky** [paperless-ngx/paperless-ngx#7807]
### Description

Please see https://github.com/paperless-ngx/paperless-ngx/discussions/7272

### Steps to reproduce

Please see https://github.com/paperless-ngx/paperless-ngx/discussions/7272

### Webserver logs

```bash
Please see https://github.com/paperless-ngx/paperless-ngx/discussions/7272
```

### Paperless-ngx version

2.12.1

### Host OS

Ubuntu Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Im going to leave the PR for now, but this really is not a bug, its a change that you'd like to see (which I see the value of, of course).

**Comment by stumpylog** [comment]
It seems to me like something which should be raised upstream.  If a user of imap-tools asks to move a message somewhere that doesn't exist, that should raise an error.  The IMAP standard requires this already: https://datatracker.ietf.org/doc/html/rfc3501#section-6.4.7

**Comment by shamoon** [comment]
I think it does, see: https://github.com/paperless-ngx/paperless-ngx/discussions/7272#discussioncomment-10117292
