### ISSUE TITLE
[BUG] menu block is not completely visible anymore

### ISSUE THREAD

**Issue by datenwort** [paperless-ngx/paperless-ngx#7811]
### Description

After updating to version 2.12.1 I do not see the menue bar on the left with all necessary entries. I have so zoom out see "User & groups" and log information. There is no scrollbar visible

If I zoom out there will be a very large space between the last two menue blocks.

### Steps to reproduce

I logged myself into paperless
(Add some items in stored views part (8+))
and see that the last items are hidden

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.12.1

### Host OS

Ubuntu 20.4.6

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
#7785 #7735 #7809

All closed by https://github.com/paperless-ngx/paperless-ngx/pull/7738
