### ISSUE TITLE
[BUG] <tr> element is missing in the header from document list view

### ISSUE THREAD

**Issue by lemmi** [paperless-ngx/paperless-ngx#7831]
### Description

The list view does not include `<tr>` tags around the `<th>` tags, which I think is not correct html.

I think it's this part here that needs to be surrounded in `<tr>...</tr>`: https://github.com/paperless-ngx/paperless-ngx/blob/374a1ceb05ec4def098572355edadcbecdbb5b11/src-ui/src/app/components/document-list/document-list.component.html#L163-L267

I noticed the error since I wanted to convert the table into something else, but most tools just did not want to work correctly without the tags.

### Steps to reproduce

1. Go to documents
2. Enable list view
3. Inspect html

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.11.3 

### Host OS

VoidLinux x86_64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is a bit silly, but ok.
