### ISSUE TITLE
[BUG] Scrolling Bar at Google Chrome Version 129.0.6668.90 

### ISSUE THREAD

**Issue by jjmwiwi** [paperless-ngx/paperless-ngx#7845]
### Description

Unforunately, there is no scrolling bar any more for the menue on the left side in Google Chrome Browser. At Firefox it works
<img width="176" alt="Screenshot 2024-10-03 202123" src="https://github.com/user-attachments/assets/6ff95e2c-dba1-4549-beba-91301dcebba1">

### Steps to reproduce

Start page of Paperless-NGX
Move Mouse over the side bar
no scrolling bar appears

### Webserver logs

```bash
no logas available
```

### Paperless-ngx version

2.12.1

### Host OS

RaspberryPi4

### Installation method

Docker - official image

### Browser

Chrome Version 129.0.6668.90 

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Even a cursory search would reveal this has already been reported and resolved
