### ISSUE TITLE
Tag share with another account always shows a count of 0 on other account

### ISSUE THREAD

**Issue by maxime1992** [paperless-ngx/paperless-ngx#7857]
### Description

Hello,

I've got a certain tag that I wish to share with someone, to give access to read all the documents with that tag.

I did that and gave the permission on the tag for the other person to read documents.

Logging into the account of the other person, I always have a count of `0` for that tag and I'm not sure why.

### Steps to reproduce

Tried to repro on the demo env but couldn't as there's an error when creating another user.

Essentially the setup I've got is basic:
- Create one new tag, lets call it "A"
- Create a new user and share the "A" tag with them
- Open an incognito window and connect as the new user
- See that if you filter for the tag "A" you'll have a count of 0

It's weird though, I do have a few shared documents that have been working just fine. Not sure how relevant that is but I did rename that tag in between :thinking: 

### Webserver logs

```bash
Nothing relevant unfortunately
```

### Paperless-ngx version

2.12.1

### Host OS

Ubuntu 22.04

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Sharing a tag does not share documents with that tag.

**Comment by maxime1992** [comment]
Is there an easy way to share all documents with a certain tag? For example, if there's a tag family, I'd like my wife to have access to all those documents

**Comment by maxime1992** [comment]
Brilliant, never used those but I just did now, it's fantastic. Paperless-ngx never cease to amaze me
