### ISSUE TITLE
[BUG] Changing displayed custom fields in a SavedView does not always show the warning about "unsaved changes"

### ISSUE THREAD

**Issue by chefkoch** [paperless-ngx/paperless-ngx#7863]
### Description

I have the setting enabled to show a warning when unsaved changes were made to a saved view.
.../settings/savedviews

### first test
✅ The popup is being raised as expected nicely for modifications of **filter**, **layout** and even **sorting**.
⚡ However when **adding custom fields to be displayed**, this popup is not being shown when switching to another view.

### second test
✅ After some more testing and investigation I noticed for recently added views or  views that have been modified recently, the popup is shown in all cases tested. (see green highlighted views)
⚡So I digged a bit deeper and can confirm now that only in my legacy (older views) the popup is not shown when adding fields to be displayed.  (see yellow highlighted view) --> the fields to be displayed is set to "Standard" and within this view, the popup is not shown when adding new fields.

![grafik](https://github.com/user-attachments/assets/98dbd361-452f-4971-a0ae-f9a3b7bc7917)

### Steps to reproduce

1. enable warning about unsaved changes
2. use a saved view from previous versions (I guess pre merged #6439 )
3. open the saved view
4. add custom fields to be displayed
5. change the view again --> popup warning expected but not displayed

### Webserver logs

```bash
not relevant? did not find anything view related
```

### Paperless-ngx version

2.12.1

### Host OS

Linux-6.1.106-Unraid-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-6.1.106-Unraid-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 12998205411328,
        "available": <more>
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://<IPaddress>:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-06T21:00:33.686670+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-06T20:05:03.164320Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Can't reproduce this, also doesn't make much sense. Saved views with the default fields have "NULL" for that value in the db and will definitely register as changed when changing them. See video. Feel free to add more context, of course.


https://github.com/user-attachments/assets/62c96c87-55b5-4a54-8591-109b2cf942a3

**Comment by shamoon** [comment]
Oh I see, you're talking about modifying the saved view itself. Lemme check that.

**Comment by chefkoch** [comment]
@shamoon  man... you  are on fire. 👍 
thanks for testing and sorry for confusion.... 
With my screenshot I just wanted to highlight my findings, but the descriped behaviour is not within the settings/savedviews screen, but within the actual view so....

1. open a view
![grafik](https://github.com/user-attachments/assets/866acc0a-81ff-4ff8-9302-61dfa9c02082)
2. modify it there 
![grafik](https://github.com/user-attachments/assets/17cfd66e-ce62-48eb-9fc9-20fa0f49f0c2)
