### ISSUE TITLE
[BUG] Certain pdfs won't get importet ('File type application/octet-stream')

### ISSUE THREAD

**Issue by veeroohre** [paperless-ngx/paperless-ngx#7888]
### Description

Importing certain pdf's via mail rules doesn't work since the mime type is not supported by paperless (see log below). Also importing it manually gives a similar error message ("File type application/octet-stream not supported").

Opening the files with external programs like Adobe Reader gives no error message. Since it's a sensitive file I don't want to upload it here.

The beginning of the file looks like this (partially redacted):
```
TEXTmdos ��%PDF-1.4
%����
10 0 obj
<<
/Creator (Omnis Studio v10.2)
/Producer (Brainy Data PDFDevice v4.0.0.0 for Win64)
/CreationDate (D:20241009122705+02'00')
/ModDate (D:20241009122705+02'00')
>>
endobj
11 0 obj
<<
/Type /Catalog
/Pages 12 0 R
/PageLayout /SinglePage
/PageMode /UseNone
/OutputIntents [ ]
>>
endobj
12 0 obj
<<
/Type /Pages
/Kids [ 13 0 R 14 0 R 15 0 R 16 0 R 17 0 R ]
/Count 5
>>
endobj
13 0 obj
<<
/Type /Page
/Parent 12 0 R
/MediaBox [0.00 0.00 595.27 841.89]
/Resources << /ProcSet 1 0 R /Font << /F1 4 0 R /F2 5 0 R >> /XObject << /Im1 2 0 R /Im2 3 0 R >> >>
/Contents 18 0 R
/Annots [ 19 0 R ] >>
endobj
18 0 obj
<< /Length 2337 /Filter /FlateDecode >>
stream
[...]
endstream
endobj
2 0 obj
<<
/Type /XObject
/Subtype /Image
/Width 204
/Height 118
/ColorSpace /DeviceRGB
/BitsPerComponent 8
/Length 5842
/Filter /FlateDecode
```

Maybe it's a problem I have to solve upstream or with the creator of the file, but first I think this issue may be important for some other people and second it would be great to get a "filtered log" or an alert in Paperless-ngx to know which files are affected and therefore not imported.
Unfortunately these files don't make it to the file task screens. So unless you check the logs very carefully you don't notice this problem.

Addition: I use Google Workspace to manage my mails.

In the "original message view" the file type seems to be recognized correctly:
```
Content-Type: **application/pdf**; name="RK-4721312.PDF"
Content-Description: RK-4721312.PDF
Content-Disposition: attachment; filename="RK-4721312.PDF"; size=98786; creation-date="Thu, 10 Oct 2024 05:03:21 GMT"; modification-date="Thu, 10 Oct 2024 05:03:21 GMT"
Content-ID: <6DCE65364D5FDB43B5C99079354A6F67@b***n.de>
Content-Transfer-Encoding: base64
```

Addition 2:
After reading [this ](https://medium.com/@jberkenbilt/the-structure-of-a-pdf-file-6f08114a58f6) basic article about the structure of pdf files I now know that the beginning of the file "TEXTmdos ��" is the problem. After deleting this text the import works.

The question is now whether the "importer" of Paperless could ignore all strings before the "%PDF..." part. Meaning being a little bit more error tolerant.

### Steps to reproduce

1. Create mail rule
2. Get email with certain pdf as attachment
3. Attachment won't get imported

### Webserver logs

```bash
[2024-10-10 10:40:02,348] [DEBUG] [paperless_mail] Rule m***@m*****m.de.Alle Nachrichten Martin (7 Tage): Processing mail FW: Ihre Kostenabrechnung vom ***  Nr.  4****2 from M***r@b***n.de with 1 attachment(s)

[2024-10-10 10:40:02,367] [DEBUG] [paperless_mail] Rule m***l@m****m.de.Alle Nachrichten Martin (7 Tage): Skipping attachment RK-4721312.PDF since guessed mime type application/octet-stream is not supported by paperless
```

### Browser logs

```bash
n/a
```

### Paperless-ngx version

2.12.1

### Host OS

Ubuntu 20.04 LTS

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-5.15.0-122-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 3318743040000,
        "available": 667756265472
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-10T10:10:20.117067+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-10T11:05:00.703993Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by veeroohre** [comment]
Addition: I use Google Workspace to manage my mails.

In the "original message view" the file type seems to be recognized correctly:
```
Content-Type: **application/pdf**; name="RK-4721312.PDF"
Content-Description: RK-4721312.PDF
Content-Disposition: attachment; filename="RK-4721312.PDF"; size=98786; creation-date="Thu, 10 Oct 2024 05:03:21 GMT"; modification-date="Thu, 10 Oct 2024 05:03:21 GMT"
Content-ID: <6DCE65364D5FDB43B5C99079354A6F67@bafin.de>
Content-Transfer-Encoding: base64
```

**Comment by shamoon** [comment]
1. The files are messed up, that’s not paperless’ fault.
2. #7651
