### ISSUE TITLE
[BUG] Menue is missing the scroll bar - not all entries visible

### ISSUE THREAD

**Issue by ulbi** [paperless-ngx/paperless-ngx#7891]
### Description

Currently it is not possible to see the menue entry "Protocol" and the version information.
![image](https://github.com/user-attachments/assets/a263033e-25b1-4a84-84b9-26c8bf2c78cc)
Screensize is 1920x1080 and Zoomfactor 125%

But also with 100% and a downsized window, the entries are not visible and no scroll bar comes up.

### Steps to reproduce

1. Open paperless
2. Reduce Window Size until the menue becomes no longer completely visible 
3. Menueentries disappear and no scroll bar gets displayed

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.12.1

### Host OS

Docker Image

### Installation method

Docker - official image

### Browser

Edge, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please search.
