### ISSUE TITLE
[BUG] Newlines fail to render in edit preview for TXT files

### ISSUE THREAD

**Issue by blankdvth** [paperless-ngx/paperless-ngx#7907]
### Description

Paperless-ngx does not properly render the newlines of TXT files on the **Edit** page's preview. Instead, it clumps all the text together into one big blob. This only affects the **Edit** page, and does not affect the [pre]view (including the hover preview), nor the download, only on Edit.

For example, this is the source TXT file:
![](https://s3.blankdvth.com/9593fa86-0697-4b65-8693-e58d6fc60cf6.png)

This is how it renders in the hover preview (note that newlines render fine) -- same goes for direct in-browser [pre]viewing, or downloading:
![](https://s3.blankdvth.com/a2082d29-236e-48a8-974e-0e812da4eccf.png)

While this is how it renders in the edit preview (note the lack of newlines):
![](https://s3.blankdvth.com/4d61f7ef-2355-4450-be2e-a0682c716e7e.png)

I believe this is a bug as it makes understanding the text content while trying to organize the document extremely difficult in some cases.

### Steps to reproduce

1. Create a text file containing newlines, for example a few paragraphs of lorem ipsum
    - I used [lorem_ipsum.txt](https://github.com/user-attachments/files/17356530/lorem_ipsum.txt)
3. Upload this text file to paperless-ngx
4. Go into the **Edit** view for the document that results
5. Notice the rendering of the text in the preview on the side of the document properties

### Webserver logs

```bash
Unrelated
```

### Paperless-ngx version

2.12.1

### Host OS

Debian 12 x86_64

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
#7908
