### ISSUE TITLE
[BUG] Beta 2.13.0 RC1: Microsoft Business OAuth Token too long for database

### ISSUE THREAD

**Issue by stefanlachner** [paperless-ngx/paperless-ngx#7915]
### Description

When connecting a Microsoft 365 business account with the recently added OAuth feature, the token can not be stored in the db due to length constraints of 2048 characters.

### Steps to reproduce

1. Set up OAuth Config variables for Office365
2. Click the OAuth button in mail settings (paperless)
3. Accept the OAuth Sign-In
4. Get error 500

### Webserver logs

```bash
paperless-db-1         | 2024-10-14 13:54:04.157 UTC [184] ERROR:  value too long for type character varying(2048)
paperless-db-1         | 2024-10-14 13:54:04.157 UTC [184] STATEMENT:  INSERT INTO "paperless_mail_mailaccount" ("owner_id", "name", "imap_server", "imap_port", "imap_security", "username", "password", "is_token", "character_set", "account_type", "refresh_token", "expiration") VALUES (NULL, 'Outlook OAuth 2024-10-14 13:54:03.697806+00:00', 'outlook.office365.com', 993, 2, '', '*deleted token for obvious reasons*', true, 'UTF-8', 3, '*deleted token for obvious reasons*', '2024-10-14 15:10:07.154097+00:00'::timestamptz) RETURNING "paperless_mail_mailaccount"."id"
paperless-webserver-1  | [2024-10-14 15:54:04,158] [ERROR] [django.request] Internal Server Error: /api/oauth/callback/
```

### Paperless-ngx version

2.13.0-beta-rc1

### Host OS

Synology DSM 7.2

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Sheesh Microsoft. How long is the token?

**Comment by shamoon** [comment]
Thanks for testing, the fix is already in the beta build

**Comment by stefanlachner** [comment]
Thanks for the fast fix!
However, the error still exists:
```
paperless-db-1         | 2024-10-14 15:30:44.247 UTC [61] ERROR:  value too long for type character varying(2048)
paperless-db-1         | 2024-10-14 15:30:44.247 UTC [61] STATEMENT:  INSERT INTO "paperless_mail_mailaccount" ("owner_id", "name", "imap_server", "imap_port", "imap_security", "username", "password", "is_token", "character_set", "account_type", "refresh_token", "expiration") VALUES (NULL, 'Outlook OAuth 2024-10-14 15:30:43.912968+00:00', 'outlook.office365.com', 993, 2, '', '*token*', true, 'UTF-8', 3, '*refresh token*', '2024-10-14 16:56:48.243413+00:00'::timestamptz) RETURNING "paperless_mail_mailaccount"."id"
```

Thanks to the now also correct version info I can confirm that I used the correct image:
<img width="184" alt="image" src="https://github.com/user-attachments/assets/8ae834ff-0f0d-4058-b518-031365be76f3">

**Comment by shamoon** [comment]
Because it hasn't been released yet I just updated the migration `0027...` so if you're using the same test instance it won't 'see' the new migrations. You'll either need to apply the changes manually or setup a new test instance (I think you can also re-apply Django migrations but that might be more annoying to figure out).
