### ISSUE TITLE
[BUG] Beta 2.13.0 RC1: Version Info incorrect

### ISSUE THREAD

**Issue by stefanlachner** [paperless-ngx/paperless-ngx#7917]
### Description

The version info in Beta 2.13.0 RC1 is still 2.12.

### Steps to reproduce

1. Log in
2. View version
3. Wonder why the version is still 2.12 even though you specified a different image tag ;) 

### Webserver logs

```bash
Not relevant
```

### Paperless-ngx version

Beta 2.13.0 RC1

### Host OS

Synology DSM 7.2

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I don't really see this as a bug, and the version increment just wasn't done yet but anyway, its been changed already, thanks.

<img width="222" alt="Screenshot 2024-10-14 at 8 25 45 AM" src="https://github.com/user-attachments/assets/7f8da230-2349-4028-ad76-b69e2d309780">
