### ISSUE TITLE
Search highlighting

### ISSUE THREAD

**Issue by chwari** [paperless-ngx/paperless-ngx#7928]
### Description

Hello,
first thank you all for this great work!

This seems to be the same Problem as in #6717. I am on 2.12.1.

The search ist very fast. But there ist no highlighting. Not in the preview an not in the document.
And there is no difference between global search, "title and content" or "advanced search".
Btw. in #6717 it is stated that highlighting only works in global search. Has that been confirmed?

I tried chrome, edge and firefox dev. edt. But no luck.

### Steps to reproduce

Fill in search word
Enter

### Webserver logs

```bash
no log
```

### Paperless-ngx version

2.12.1

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Chrome, Edge, FF dev. edt.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
<img width="1005" alt="Screenshot 2024-10-15 at 1 00 54 AM" src="https://github.com/user-attachments/assets/e4897a9a-dbae-4313-b736-0e2ada8d6bc8">

**Comment by chwari** [comment]
hmm
dark mode does not work for me...do you use mac os (safari)?
![lorem_dark](https://github.com/user-attachments/assets/297b13ca-1c90-45e8-b40c-34d863c8d747)

because it works on the app in android. So maybe its a "windows bug". But thank you anyway.
![Screenshot_20241015-103938](https://github.com/user-attachments/assets/4ea0802f-2ed3-4063-8bba-379d0c212fdf)

**Comment by shamoon** [comment]
- We don’t make the android app
- Advanced search with large cards. Not the hover preview
