### ISSUE TITLE
[BUG] Closing a document opened from Dashboard returns to Documents

### ISSUE THREAD

**Issue by luc-ass** [paperless-ngx/paperless-ngx#7939]
### Description

When opening a file from the dashboard and then closing it, you are returned to the Documents section not the Dashboard. I've stumbled across this multiple times when editing files from the _INBOX_-Section on my Dashboard.

### Steps to reproduce

1. Open file from Dashboard
2. Close file via **x** in the top left corner
3. Paperless returns you to the Documents section

### Webserver logs

```bash
no relevant logs
```

### Paperless-ngx version

2.12.1

### Host OS

Synology DSM 7.2.2-72803

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-3.10.108-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 11490240110592,
        "available": 4657426853888
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://paperless-ngx-redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-16T15:49:36.194252+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-16T13:05:05.657511Z",
        "classifier_error": null
    }
}
```

### Browser

Chrome 129.0.6668.100 (arm), Safari 18.0.1 (20619.1.26.31.7)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
You’re just describing the way it works, and has for a long time

**Comment by luc-ass** [comment]
True, but don't you think, that it would be more intuitive, if you would return to the page you came from, when closing a document?

**Comment by luc-ass** [comment]
Thanks for clarifying. I'll make it a feature request.
