### ISSUE TITLE
[BUG] Newly created custom fields do not appear in the "Show" menu until the page is refreshed

### ISSUE THREAD

**Issue by bdr99** [paperless-ngx/paperless-ngx#7968]
### Description

After creating a new custom field, it will not appear in the "Show" menu until after the page is refreshed. Therefore, it's not possible to add a column for it to a document view until the page is refreshed. I think this UX is a bit confusing since I would have expected the custom field to show up right away.

### Steps to reproduce

1. Go to "Custom Fields".
2. Add a new custom field.
3. Go to "Documents".
4. Click the "Show" drop down at the top right corner.
5. Note the new custom field does not appear.
6. Refresh the page and click "Show" again.
7. Note the new custom field now appears.

### Webserver logs

```bash
I think this is not relevant but let me know if this is needed
```

### Paperless-ngx version

2.12.1

### Host OS

Unraid 6.12.11

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.12.1",
    "server_os": "Linux-6.1.99-Unraid-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 1000203837440,
        "available": 127298310144
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "documents.1052_document_transaction_id",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://redis:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-20T13:28:05.964393-04:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-20T17:05:27.657430Z",
        "classifier_error": null
    }
}
```

### Browser

LibreWolf 131.0.3-1

### Configuration changes

n/a

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
You can open a request for this but it’s just not implemented, not really a bug

**Comment by shamoon** [comment]
Forgot to update here, without wanting to quibble about whether this is a bug or not I understand how it is unexpected and the implementation is quite simple so the change will be included in our next release 👍

**Comment by bdr99** [comment]
@shamoon Thank you. Regardless of whether it is considered a bug, I appreciate that you recognized that it was confusing and were able to fix it.
