### ISSUE TITLE
[Other] Code formatting using `black` (and more)

### ISSUE THREAD

**Issue by kpj** [paperless-ngx/paperless-ngx#8]
It does currently not seem like paperless-ng(x) is following any particular coding style.

In order to keep everything uniform and prevent certain kinds of discussion, I'd suggest formatting all Python code with [black](https://github.com/psf/black).
As a next step, one could format the TypeScript code using, e.g. [prettier](https://prettier.io/). And linting with, e.g. [flake8](https://github.com/PyCQA/flake8) might also be a good idea.

What do you guys think? I'd be happy to create a PR and then also add code formatting tests to our GitHub Actions workflows.

**Comment by bauerj** [comment]
Yes, in my experience using black just makes everything so much easier.

However, we should probably wait until the outstanding PRs have been handled. Otherwise merging may be unnecessarily hard.

**Comment by kpj** [comment]
Agreed! I'll wait for those PRs and then create one myself :-)

**Comment by yschroeder** [comment]
There is currently a CI check for PEP8 compatibility. We should adjust that to fail if the PR is not correctly blackened.

**Comment by bauerj** [comment]
Hey @kpj,

did you start working on this yet? I think a 1.6.0 release is not too far away any more so it would be nice to have it ready to be merged :+1:

**Comment by yschroeder** [comment]
It might be a PITA to merge the split and merge feature. Summoning @shamoon to comment.

**Comment by shamoon** [comment]
You mean because black will give me a hard time with that code? I could see that. But tbh I've never used this kinda tool before so I don't know the pain. Is the idea that code that's merged before we implement black is kinda "grandfathered in"?

I guess also part of this question is the urgency of implementing each of these (code formatting tool vs split/merge).

**Comment by yschroeder** [comment]
Black will change a lot of lines, so every merge and rebase that was easy will result in a conflict.

That's why you want to have a mostly clean slate regarding open PRs.

**Comment by yschroeder** [comment]
Code formatting would be a easy thing to get into 1.6. If split and merge is postponed to 1.7 anyway, then we should blacken the code now and of course put a github check into place that all code is always correctly blackened.

**Comment by qcasey** [comment]
I also agree we should blacken now. Split and Merge conflicts can be resolved, the only other PRs I think would be effected is #100 which is under debate anyway and #14 which awaits contributor input/testing.

We're probably at the 'cleanest slate' we'll see for a while.

**Comment by qcasey** [comment]
Can't we also use GH actions to run black against new PRs and commit the formatted code? Enforcement, as well as testing for formatting?

**Comment by yschroeder** [comment]
I would do it as is with the current pep8 check. Just fail the check and let the author fix it. You can't commit to other persons repositories anyway.

**Comment by qcasey** [comment]
I think that's a checkbox when you create a PR...

![image](https://user-images.githubusercontent.com/1429672/155856593-8d6f9fce-2102-407b-955d-46f23edce26e.png)

But no need to complicate things, just an automated check would be great :)

**Comment by kpj** [comment]
Awesome! I'll create a PR later today.

**Comment by qcasey** [comment]
This has been merged in #168. Thank you @kpj!
