### ISSUE TITLE
[BUG] After running export/import process, logins using SSO aren't linked to the user requiring them to be re-setup

### ISSUE THREAD

**Issue by paradizelost** [paperless-ngx/paperless-ngx#8015]
### Description

After running export/import process, when signing in via SSO I could not sign in, and when "registering" it errored stating that the user already exists. To resolve issue i had to re-enable normal sign-in, log into the normal user (thank goodness i had the password saved) and re-link from under the profile.
This must be done for each user in the system.

### Steps to reproduce

Have SSO set up, export, stop service, delete database, import, start system and attempt to log in.

### Webserver logs

```bash
Not finding webserver logs for the SSO user already existing.
```

### Paperless-ngx version

2.13.0

### Host OS

Debian

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.0",
    "server_os": "Linux-6.8.12-1-pve-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 40802189312,
        "available": 19466027008
    },
    "database": {
        "type": "mysql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-25T14:24:09.186544-05:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Browser

Chrome

### Configuration changes

docker-compose.env settings for openid provider using authentik

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I think we can just update the docs, SSO info isn't exported, so you will need to set them up again and disable the "disable regular login" setting

**Comment by paradizelost** [comment]
Is this an intentional thing? with an environment with multiple users this
could be labor intensive.

**Comment by shamoon** [comment]
It's never been that way, the difference is now you can disable the login. I do see the value in adding it to the export / import.

**Comment by shamoon** [comment]
Bug or not #8016 will sort this out in the future
