### ISSUE TITLE
[BUG] Missing german translation for "correspondents" heading and "document types" heading

### ISSUE THREAD

**Issue by Profex** [paperless-ngx/paperless-ngx#802]
### Description

"Correspondents" heading and "document types" heading not translated to german

### Expected behavior

"Correspondents" and "document types" heading translated to german, similar to side menu

### Steps to reproduce

Open correspondents view or open document types view

### Screenshots

![image](https://user-images.githubusercontent.com/1678124/165174348-74f730a8-f6ac-43de-b2d2-3ee25d40d7f4.png)
![image](https://user-images.githubusercontent.com/1678124/165175212-ea99dd38-54e5-40bb-b3b9-d106a0130ce6.png)

### Paperless-ngx version

1.7.0 (final)

### Host OS

Synology DSM

### Installation method

Docker

### Browser

Edge 100

### Other

I checked on crowdin and headings are properly translated there, so issue must be something else

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/99e4a79cb8b755b13b08b1d5596245296a600dcd

**Comment by shamoon** [comment]
We do still need folks to review the translations over at [crowdin](https://crwd.in/paperless-ngx)!
