### ISSUE TITLE
[BUG] Missing page numbers

### ISSUE THREAD

**Issue by leo-022** [paperless-ngx/paperless-ngx#8024]
### Description

The new page count function (#7750) does not enter a page number for documents consumed by Gotenberg (*.docx, *.eml).

### Steps to reproduce

1. Consume docx or eml document
1. Look in the list of documents
1. Pages entry is empty/missing

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.13.0

### Host OS

Synology DSM

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by s0llvan** [comment]
It’s because it was only intended for PDF files, as stated in the feature description.
But it’s not really a bug.

**Comment by stumpylog** [comment]
I agree.  This is a feature request.
