### ISSUE TITLE
[BUG] Inconsistency regarding transaction_id column

### ISSUE THREAD

**Issue by gringus** [paperless-ngx/paperless-ngx#8030]
### Description

It seems like there is an inconsistency between the content of the `migrations` directory and the `models.py` file regarding the `transaction_id` column in `documents_document` table which is causing below warning(?):
```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  No migrations to apply.
  Your models in app(s): 'documents' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
According to `migrations` directory `transaction_id` column is created in `1052_document_transaction_id.py` migrations file and does not get removed afterwards. Unfortunately `models.py` file does not list that column, so the field is unknown and likely this is the reason for the warning.

### Steps to reproduce

1. Presumably start fresh or go back with migrations eg.
```
$ python manage.py migrate documents 1051_alter_correspondent_owner_alter_document_owner_and_more
...no errors...
$ python manage.py migrate documents
...no errors...
$ python manage.py migrate documents
Operations to perform:
  Apply all migrations: documents
Running migrations:
  No migrations to apply.
  Your models in app(s): 'documents' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

### Webserver logs

```bash
No need
```

### Paperless-ngx version

2.13.0

### Host OS

Gentoo Linux x86_64

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
src/documents/migrations/1052_document_transaction_id.py

**Comment by stumpylog** [comment]
There is no reason the field should be removed.  It exists and is used.  Not seeing any sort of bug here, stepping around migrations isn't something that is supported.

**Comment by shamoon** [comment]
It is inherited from `SoftDeleteModel`

https://github.com/paperless-ngx/paperless-ngx/blob/53aa216a4ae57f68d75a15d2762ff91f2d177e4a/src/documents/models.py#L137

**Comment by gringus** [comment]
In such a case, I am sorry for the noise. Thank you for the explanation.
