### ISSUE TITLE
[BUG] Some issues with custom field queries

### ISSUE THREAD

**Issue by B5JohnSheridan** [paperless-ngx/paperless-ngx#8051]
### Description

I've been testing the great new feature of the custom field filtering and stumbled on a few issues.

When creating a complex filter, it is not possible to delete some parts of it, even if they are still empty. This can be reproduced by creating the following outline:

![grafik](https://github.com/user-attachments/assets/d028e596-14fe-4db1-9544-98305a1e7d8f)

It is then not possible to delete the last added area with the red cross delete button (while it is possible to delete the one above it). Even when filling it with real queries, this issue persists. So adding by error another "{ }" block is an issue as it cannot be deleted anymore without deleting other, already configured parts. This also happens in more complex scenarios, e.g. with more sub filters:

![grafik](https://github.com/user-attachments/assets/08f1bf99-f81a-42f0-9e4e-30e4405a9663)

In this scenario, the lower two sections (a total of 5 sections) cannot be deleted. Only the first part can be removed and afterwards also other areas can be deleted. It seems that only the uppermost two areas can be deleted. Everything below cannot be deleted.

The other issue I found might not be a bug, but it seems not logical. It is about the "Not" selection. It is only available for whole subquery blocks, but not for single queries. So for a single query:

![grafik](https://github.com/user-attachments/assets/3fcf142d-9367-49c3-b9f3-30e0ecd0ff1e)

It is not possible to use "Not", but it is when adding a "{ }" block:

![grafik](https://github.com/user-attachments/assets/7cc8f74f-a695-44df-9481-6b9c9c8f3e7c)

it is possible. As there are "Is null" and "Has value", it would sometimes be nice to use "Has not value" rather to use both "Is null" and "Has value". With adding another sub query it is possible, but a little more complicated then it seems necessary.

The last issue is about the "exists" query. This seems not to work as expected:

![grafik](https://github.com/user-attachments/assets/1ee98d74-e091-4040-9cec-a2cb7c5de3e8)

Results in many hits of the form:

![grafik](https://github.com/user-attachments/assets/f0499b9d-b0cf-4125-9e8d-b155ddfbc97a)

So obviously, the fields are existing for the documents. Also some documents without the fields are shown, but it does not seem to be consistent at all. With "true", only documents with the fields seem to appear, but with "false" also lots of documents that have the field, appear in the list...

### Steps to reproduce

See above for examples.

### Webserver logs

```bash
No logs seem helpful here. If they do, please tell me!
```

### Paperless-ngx version

2.13.0

### Host OS

Ubuntu 24.04

### Installation method

Docker - official image

### Browser

Mozilla Firefox 131.0.3

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
The first is certainly a bug, the second was a choice, the third thing I cant really reproduce but I will play with that one some more.

**Comment by B5JohnSheridan** [comment]
> The first is certainly a bug, the second was a choice, the third thing I cant really reproduce but I will play with that one some more.

I can reproduce this with any custom field in my setup. Furthermore:
- Without the filter "custom field exists": all 4806 documents are found
- With filter "custom field exists true": 414 documents are found. On the first glance, all of them do have the custom field
- With filter "custom field exists false": 442 documents are found. First, I would expect, 4806-414 = 4392 documents. Second, all of the documents that were shown for "true" are still shown, with a few more without the field showing. But far from all. I think all of the additional documents have other custom fields.

So looks like a bug ONLY for "false". And "false" seems to show documents that have custom fields, regardless which ones or so? Though the number of documents found for "false" are not always the same, but almost.

**Comment by B5JohnSheridan** [comment]
I looked at the fix #8056 and I am not fully sure I understand it enough to comment it, but together with the header "empty element removal" I'd like to point out, that it also happens for normal elements, e.g. here:

![grafik](https://github.com/user-attachments/assets/47687574-17a0-4382-887d-ce04d214ebd6)

I also cannot remove the individal elements in the lower two "{ }" sections, e.g. "Rechnungs/Lieferscheint", "Vorgangsnummer", .... and also of course not the entire "{ }" sections. If this was fixed as well with your fix, then sorry for my comment.

**Comment by shamoon** [comment]
> If this was fixed as well with your fix, then sorry for my comment.

It is:


https://github.com/user-attachments/assets/25d788f8-da3a-44d3-b4c1-72aee57b5625

I'll see about the exists thing

**Comment by shamoon** [comment]
@yichi-yang I see what he's saying (here: https://github.com/paperless-ngx/paperless-ngx/issues/8051#issuecomment-2440045551 ), any thoughts? The query may be technically correct but it sorta seems like we want something closer to `custom_fields__id__none`

**Comment by shamoon** [comment]
No worries if you dont have the bandwidth.

> Edit: I think it's meant to act similar to `custom_fields__id__none`, so there's something wrong here.

It sorta isnt though, `custom_fields__id__none` will exclude all documents that have the ID(s) listed, whereas this seems to do something different, including documents that do have the field. See below if you're curious.

<img width="2032" alt="Screenshot 2024-10-27 at 8 22 29 PM" src="https://github.com/user-attachments/assets/9e27b959-b460-41ac-937f-5a94f34e8490">
<img width="2032" alt="Screenshot 2024-10-27 at 8 22 33 PM" src="https://github.com/user-attachments/assets/98db7ea8-28f9-4940-9bc9-f031c1451401">

vs

<img width="2032" alt="Screenshot 2024-10-27 at 8 22 37 PM" src="https://github.com/user-attachments/assets/11a78d26-04b6-4dbc-8469-deed67580c6d">

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by yichi-yang** [comment]
I think I've figured out what's wrong with `exists false`. I submitted the fixes as #8158.
