### ISSUE TITLE
[BUG] FILENAME_FORMAT_REMOVE_NONE with empty first path

### ISSUE THREAD

**Issue by Necoro** [paperless-ngx/paperless-ngx#8057]
### Description

I have `PAPERLESS_FILENAME_FORMAT` set to `{{ owner_username }}/{{ created_year }}/{{ correspondent }}/{{ title }}`. I also have `PAPERLESS_FILENAME_FORMAT_REMOVE_NONE` enabled.

With 2.13.0 and the new template handling, whenever `owner_username` is not set (which is the default in our instance), it gets removed from the path -- with the slash intact. That is, the path get rendered as `/{{ created_year }}/...` and paperless is thus trying to write to root, which is disallowed.

Looking at [file_handling.py](https://github.com/paperless-ngx/paperless-ngx/blob/b2e9f3195a38d387f7fabd24744d092e7800964e/src/documents/file_handling.py#L110) this is no surprise, as the slashes are only removed when they occur on both sides. Probably, something like `rendered_filename.removeprefix("-none-/")` needs to be added.

### Steps to reproduce

1. Have `PAPERLESS_FILENAME_FORMAT_REMOVE_NONE` enabled
2. Have a filename format set to a template where the first path resolves to `""`/`"-none"`
3. Add a document and see it fail, because it tries to write to root

### Webserver logs

```bash
[2024-10-27 14:43:58,087] [ERROR] [paperless.consumer] The following error occurred while storing document ADS_1100W_006904.pdf after parsing: [Errno 13] Permission denied: '/2024'

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 565, in run
    create_source_path_directory(document.source_path)
  File "/usr/src/paperless/src/documents/file_handling.py", line 11, in create_source_path_directory
    os.makedirs(os.path.dirname(source_path), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/2024'
```

### Paperless-ngx version

2.13.0

### Host OS

Ubuntu 24.04.1 (aarch64)

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by Necoro** [comment]
Workaround: prefix the filename with `./`
Might also be a mitigation idea: add
```python
if not rendered_filename.startswith("/"):
  rendered_filename = "./" + rendered_filename
```
This omits the problems with iteratively removing the leading directory.

**Comment by stumpylog** [comment]
The much simpler fix is to strip the leading and trailing slashes from the final string.  You're welcome to open a pr
