### ISSUE TITLE
[BUG] After updating to 2.13.0 the feature GMail OAuth is not visible

### ISSUE THREAD

**Issue by v4w5gse65g874** [paperless-ngx/paperless-ngx#8059]
### Description

Using docker image:
ghcr.io/paperless-ngx/paperless-ngx:latest

![Screen Shot 2024-10-27 at 10 38 58](https://github.com/user-attachments/assets/b750c698-58d8-46f9-84a5-1f094a41c562)

### Steps to reproduce

Upgrade to 2.13.0, navigate to the Mail tab, and the OAuth buttons that should be seen in from https://github.com/paperless-ngx/paperless-ngx/pull/7866 are not there.

### Webserver logs

```bash
Not applicable
```

### Paperless-ngx version

2.13.0

### Host OS

Ubuntu 24.04.1 LTS

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by RincewindX** [comment]
Same issue. Why is this duplicate? To what?

![grafik](https://github.com/user-attachments/assets/fcadf974-0c8c-46b1-bd2d-680ff6f5ae43)
