### ISSUE TITLE
[BUG] Paperless down after upgrade 2.12 > 2.13 DB Issue

### ISSUE THREAD

**Issue by Buggyfan** [paperless-ngx/paperless-ngx#8077]
### Description

Website ist down
Error in DB logs

### Steps to reproduce

I use a portainer stack an just update the stack with repull-image

### Webserver logs

```bash
Fehler: Verbindung fehlgeschlagen
```

### Browser logs

```bash
DB log:
PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-10-28 11:57:58.413 UTC [1] FATAL:  database files are incompatible with server

2024-10-28 11:57:58.413 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 16, which is not compatible with this version 17.0 (Debian 17.0-1.pgdg120+1).
```

### Paperless-ngx version

2.13.0

### Host OS

Docker on Synology with Portainer

### Installation method

Docker - official image

### System status

```json
Log from webserver:

django.db.utils.OperationalError: [Errno -2] Name or service not known

Paperless-ngx docker container starting...

Creating directory scratch directory /tmp/paperless

Adjusting permissions of paperless files. This may take a while.

Waiting for PostgreSQL to start...

Connected to PostgreSQL

Waiting for Redis...

Connected to Redis broker.

Apply database migrations...
```

### Configuration changes

version: "3.4" services:   broker:     image: docker.io/library/redis:7     restart: unless-stopped     volumes:       - /volume2/DockerSSD/paperless-ngx/redisdata:/data    db:     image: docker.io/library/postgres:latest     restart: unless-stopped     volumes:       - /volume2/DockerSSD/paperless-ngx/pgdata:/var/lib/postgresql/data     environment:       POSTGRES_DB: paperless       POSTGRES_USER: paperless       POSTGRES_PASSWORD: paperless    webserver:     image: ghcr.io/paperless-ngx/paperless-ngx:latest     restart: unless-stopped     depends_on:       - db       - broker     ports:       - 8010:8000     healthcheck:       test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]       interval: 30s       timeout: 10s       retries: 5     volumes:       - /volume2/DockerSSD/paperless-ngx/data:/usr/src/paperless/data       - /volume2/DockerSSD/paperless-ngx/media:/usr/src/paperless/media       - /volume2/DockerSSD/paperless-ngx/export:/usr/src/paperless/export       - /volume2/DockerSSD/paperless-ngx/consume:/usr/src/paperless/consume     environment:       PAPERLESS_REDIS: redis://broker:6379       PAPERLESS_DBHOST: db       PAPERLESS_SECRET_KEY: ***       PAPERLESS_ADMIN_USER: ***       PAPERLESS_ADMIN_PASSWORD: ***       PAPERLESS_OCR_LANGUAGE: deu+eng       PAPERLESS_CONSUMER_DELETE_DUPLICATES: true       PAPERLESS_TIME_ZONE: Europe/Berlin       USERMAP_UID: 0       USERMAP_GID: 0  volumes:   data:   media:   pgdata:   redisdata:

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This is not a bug.  If you would like to upgrade your database, you will have to take steps to di so.

**Comment by ZzetT** [comment]
In case somebody comes here and still doesn't know what to do, you probably have something like that in your docker compose file:
`image: postgres`
This has the disadvantage that as soon as postgres is updated, you need to upgrade your database.
But I think the easiest solution is to just pin the version and change the line to:
`image: postgres:16`
