### ISSUE TITLE
[BUG] TIF document is not displayed when editing

### ISSUE THREAD

**Issue by OSch24** [paperless-ngx/paperless-ngx#8082]
### Description

Hello,

As you can see, in the overview all TIF documents are displayed like the PDF documents:
![grafik](https://github.com/user-attachments/assets/dc9966a6-63bc-4a52-b436-6452fe715dd9)

However, if I edit a TIF document, it is not displayed on the right.
![grafik](https://github.com/user-attachments/assets/50485f12-2419-4d2d-be24-1251cefd0e54)

### Steps to reproduce

Upload a TIF file to Paperless

### Webserver logs

```bash
Which log is required here?
```

### Paperless-ngx version

2.13.0

### Host OS

Synology 723+ / Container Manager / Docker

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.0",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 5749758619648,
        "available": 2635827060736
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0027_mailaccount_expiration_mailaccount_account_type_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-28T17:38:44.082029+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-28T16:05:37.881750Z",
        "classifier_error": null
    }
}
```

### Browser

FireFox v131.0.3

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Any webserver or browser logs would be helpful

**Comment by stumpylog** [comment]
I cannot reproduce any issue with a TIFF file:
![image](https://github.com/user-attachments/assets/305a20cb-7688-4e76-a70d-141220206bcf)

**Comment by shamoon** [comment]
Browser support for tiff is very limited, not a paperless thing as you can see Safari has no problem:

<img width="1922" alt="Screenshot 2024-10-28 at 10 09 15 AM" src="https://github.com/user-attachments/assets/1c9c7167-9a3a-4240-9b84-42b919afeb15">

You can open a FR, I'll see what the options are for other browsers.

**Comment by OSch24** [comment]
Very strange. But they are TIF files that are already 20 years old... Firefox and Edge don't work. IrfanView or Windows Photo Viewer can display these files without any problems.

I'll convert them to PDF, then I'll have peace of mind.
Thanks.

**Comment by shamoon** [comment]
> Very strange. 

I think its been that way forever.

I also have a PR for displaying TIFFs: #8087 but we haven't decided if we'll merge that, it requires a library just for doing this and is obviously not something many users would use
