### ISSUE TITLE
[BUG] Set-Permissions Dialog: ComboBox should fit Modal-Size

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#8094]
### Description

Shown in the screenshot below the comboboxes used for selecting users / groups to set permissions to are smaller than they probably should be.

![2024-10-29_06-27](https://github.com/user-attachments/assets/e8b29f52-9fe8-4bfe-9b95-ccdfb831d32f)

### Steps to reproduce

1. go to documents
2. select one or more documents
3. open set permissions dialog

### Webserver logs

```bash
not applicable
```

### Paperless-ngx version

2.13.1

### Host OS

Synology DSM 6.X

### Installation method

Docker - official image

### Configuration changes

none of interest for this specific bug

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Thanks for reporting

**Comment by sukisoft** [comment]
Sure. I'm not as active here as a was 2 years ago or so, but sometimes i slide in. thx for the immediate fix!
