### ISSUE TITLE
[BUG] 1.7.0 Docker-Image, armv7: Consumer fails due to to PIL import error

### ISSUE THREAD

**Issue by raisinbear** [paperless-ngx/paperless-ngx#810]
### Description

Hi,
I'm running the armv7 Docker image. Document import via consume folder or web upload fails immediately.
The exact error message in the log is:  

`[paperless.consumer] Error while consuming Document.pdf: ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.9/site-packages/PIL/__init__.py)`  

### Expected behavior

Document import succeeds. No issues in 1.6.0.

### Steps to reproduce

Import document via consume folder or web upload.

### Webserver logs

```bash
No complete log, just the relevant error:

[paperless.consumer] Error while consuming Document.pdf: ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.9/site-packages/PIL/__init__.py)
```

### Paperless-ngx version

1.7.0

### Host OS

Raspbian Buster, 5.10.63-v7+

### Installation method

Docker

### Other

Reading up on this a little, it appears this error signature could point to a python package built on specific platform being copied to incompatible platform.

**Comment by stumpylog** [comment]
I don't have an arm platform I can test on, could you give me the output of `ls -ahl` in `/usr/src` of the container?

**Comment by raisinbear** [comment]
Hi,

sorry, couldn't check any sooner, the outputs are:

`root@01d03e619d01:/usr/src/paperless/src# ls -ahl /usr/src
total 3.5M
drwxr-xr-x 1 root      root      4.0K Apr 25 17:56 .
drwxr-xr-x 1 root      root      4.0K Mar 28 00:00 ..
-rw-r--r-- 1 root      root      453K Apr  4 23:15 Pillow-9.1.0-cp39-cp39-linux_armv7l.whl
-rw-r--r-- 1 root      root      683K Apr  4 21:58 libqpdf28_10.6.3-1_armhf.deb
-rw-r--r-- 1 root      root      1.5M Apr  4 23:15 lxml-4.8.0-cp39-cp39-linux_armv7l.whl
-rw-r--r-- 1 root      root       40K Apr  4 22:29 packaging-21.3-py3-none-any.whl
drwxr-xr-x 1 paperless paperless 4.0K Apr 27 05:46 paperless
-rw-r--r-- 1 root      root      503K Apr  4 23:15 pikepdf-5.1.1-cp39-cp39-linux_armv7l.whl
-rw-r--r-- 1 root      root      132K Apr  4 03:02 psycopg2-2.9.3-cp39-cp39-linux_armv7l.whl
-rw-r--r-- 1 root      root       96K Apr  4 22:29 pyparsing-3.0.7-py3-none-any.whl
-rw-r--r-- 1 root      root      115K Apr  4 21:58 qpdf_10.6.3-1_armhf.deb`

and

`root@01d03e619d01:/usr/src/paperless/src# ls -ahl /usr/local/lib/python3.9/site-packages/PIL/*.so
-rwxr-xr-x 1 root root 257K Apr  7 21:06 /usr/local/lib/python3.9/site-packages/PIL/_imaging.cpython-39-arm-linux-gnueabihf.so
-rwxr-xr-x 1 root root  18K Apr  7 21:06 /usr/local/lib/python3.9/site-packages/PIL/_imagingmath.cpython-39-arm-linux-gnueabihf.so
-rwxr-xr-x 1 root root 5.5K Apr  7 21:06 /usr/local/lib/python3.9/site-packages/PIL/_imagingmorph.cpython-39-arm-linux-gnueabihf.so
-rwxr-xr-x 1 root root 9.5K Apr  7 21:06 /usr/local/lib/python3.9/site-packages/PIL/_imagingtk.cpython-39-arm-linux-gnueabihf.so`

Thanks!

**Comment by raisinbear** [comment]
Ok, thanks a lot! You sent me on the right track with your request.  
Copying `_imagingcms.cpython-39-arm-linux-gnueabihf.so` from the `python3-pil_9.1.0-1_armhf.deb` package to `/usr/local/lib/python3.9/site-packages/PIL/` in the container actually did the trick. At least the document import succeeded.

**Comment by stumpylog** [comment]
That's about what I expected to see.  Your changes will work, at least until the container restarts.  We'll have a fix for this coming soon.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/9325eff6fc59a1640be9d0a1acf028a11cfbbb61

**Comment by dekiesel** [comment]
Please let me know if I should open an issue for this:

Pulling `image: ghcr.io/paperless-ngx/paperless-ngx:latest` gives me version 1.7.0. , pulling `:1.7.1` works.

**Comment by shamoon** [comment]
> Please let me know if I should open an issue for this:
> 
> Pulling `image: ghcr.io/paperless-ngx/paperless-ngx:latest` gives me version 1.7.0. , pulling `:1.7.1` works.

I’m not seeing that (nor are other users since 1.7.1 has been out for a while). If you look at https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx/21804287?tag=latest which includes 1.7.1 tag

**Comment by dekiesel** [comment]
Yes, seems to have been an issue on my end. `docker-compose pull` didn't give me 1.7.1, I maybe should have used `--force-recreate`.
