### ISSUE TITLE
[BUG] Tags applied randomly or indiscriminately to uploaded documents

### ISSUE THREAD

**Issue by jb817566** [paperless-ngx/paperless-ngx#8102]
### Description

Seemingly random tags are applied to documents when uploaded, and I don't see any option to disable this behavior or the root cause.

### Steps to reproduce

1. Upload a document, or any number of documents
2. Observe scanning of documents and import
3. Navigate to documents view
4. Observe random tags applied

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

1.10.2

### Host OS

Ubuntu 24.04.1 LTS

### Installation method

Bare metal

### Browser

Brave

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not an actual bug report and frankly just seems like complaining. There is ample documentation of how automatic tagging is done and how you can control this in our docs. If you'd like to discuss it in a productive way perhaps start a discussion with actual information or observations.
