### ISSUE TITLE
[BUG] Creating a superuser password in docker compose drops all characters after "$"

### ISSUE THREAD

**Issue by DM2602** [paperless-ngx/paperless-ngx#8118]
### Description

Starting up a new paperless-ngx instance with a set admin/superuser password in your environment variables does not respect your password in quotes, all characters after a dollar sign ($) in your password will be disregarded, including the dollar sign. Trying to log in will tell you the password is wrong until you cut off the part from the dollar sign on.

### Steps to reproduce

1. Set up a new paperless-ngx docker-compose with standard values
2. Set `PAPERLESS_ADMIN_PASSWORD` to a password with a dollar sign in it ($), put it in quotes
3. Start the container
4. Try to login with the full password you just put in the variables

### Webserver logs

```bash
[2024-10-30 18:50:20,183] [INFO] [paperless.auth] Login failed for user `admin` from IP `127.0.0.1`.
```

### Paperless-ngx version

2.13.2

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Configuration changes

PAPERLESS_ADMIN_PASSWORD=eohwef0ijd324g$1jgfos

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
You will no doubt see a warning from `docker compose` such as `WARN[0000] The "test" variable is not set. Defaulting to a blank string.` (in this example, the text after $ was "test").  

If you need an actual $, you must escape it with `$$`.  This is well documented: https://docs.docker.com/reference/compose-file/interpolation/
