### ISSUE TITLE
[BUG] Changelog is missing the changes for version 2.13.0

### ISSUE THREAD

**Issue by guahki** [paperless-ngx/paperless-ngx#8134]
### Description

The changelog does not contain the changes mentioned in https://github.com/paperless-ngx/paperless-ngx/releases/tag/v2.13.0.

This is in GitHub (https://github.com/paperless-ngx/paperless-ngx/blob/702ab1b77aa643a508702d180efe3c19aced50ce/docs/changelog.md) as well as the published docs (https://docs.paperless-ngx.com/changelog/).

### Steps to reproduce

Go to the URLs listed above.

### Webserver logs

```bash
No server logs
```

### Paperless-ngx version

-

### Host OS

-

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
#8135

**Comment by guahki** [comment]
@shamoon thanks! That was quickly. 10min solve time is crazy, even for such a "little" change.
