### ISSUE TITLE
[BUG] Miniature views in dark mode faulty

### ISSUE THREAD

**Issue by OSch24** [paperless-ngx/paperless-ngx#8162]
### Description

With the current version 2.13.3, the miniature views in the dark mode are incorrect
Tested with Firefox, Edge and Chrome.
The setting "Intestate miniature pictures in dark mode" cannot help.

### Steps to reproduce

Update to 2.13.3
Activate dark mode
Look at thumbnails

### Webserver logs

```bash
Which log file should I give here?
```

### Paperless-ngx version

2.13.3

### Host OS

Synology 723+ / Container Manager / Docker

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.3",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 5749758619648,
        "available": 2709440200704
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-03T12:24:07.936929+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-03T11:05:02.985431Z",
        "classifier_error": null
    }
}
```

### Browser

Firefox, Edge, Chrome, jeweils akt. Version

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
A screenshot would be more helpful than logs. Are you talking about the thumbnails or the popup preview?

**Comment by shamoon** [comment]
Thanks, I'll release the fix now

**Comment by OSch24** [comment]
Sorry, I should have written more.
The thumbnail images... I didn't even look at the pop-up preview.

Great, thanks for the quick solution.
You guys are really doing a great job, thank you.

But now, after the update to 2.13.4, the thumbnail images are OK again... but the pop-up preview is OK once, and others are inverted...

I even deleted the browser cache and called everything up again, I can't find a pattern as to why some are displayed correctly and others inverted.

The problem is in Firefox (v132.0 64bit), Edge and Chrome always do it correctly.

**Comment by shamoon** [comment]
Again more specifics would be helpful, I’m not 100% sure what you mean. But, Firefox has a bug (I opened a bugzilla report which has been verified) with text documents that we’ve been trying to workaround since it could literally be years till they fix it. The PR #7890 will be the ultimate fix for all of this, but because it’s a “feature” we were waiting to release it. At this point I expect it will be pretty soon.

**Comment by OSch24** [comment]
No problem, here are a few screenshots.
This is what the overview looks like, everything is great.

![grafik](https://github.com/user-attachments/assets/10806a60-807d-4eaf-b682-71a3f48053cc)


Now I display the pop-up view of the first PDF-document. It is displayed inverted:

![grafik](https://github.com/user-attachments/assets/0c413df9-83b2-4f5b-8ed8-391ce3771aad)


And here is the pop-up view of the 2nd PDF document. It is displayed correctly:

![grafik](https://github.com/user-attachments/assets/492e3156-8f50-48be-86e1-39443fe557c4)


Since this is only a Firefox problem, it is not that urgent or has no priority. When the above feature comes, we can see what happens. If you need more information or if you want me to test something, let me know.
