### ISSUE TITLE
New User - non admin - non super user : error when logging in

### ISSUE THREAD

**Issue by doc-huebi** [paperless-ngx/paperless-ngx#8215]
### Description

Hi,
all my documents in the system dont have an owner - nor a single user nor a group. So the documents should be visible for everybody.

I have now created a new user. No Admin, no Super user.

This user has authorization for documents, tags, correspondents and document types: all

When the user is logging in there is an error message:

{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"Forbidden","url":"http://nuc:8010/api/ui_settings/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://nuc:8010/api/ui_settings/: 403 Forbidden","error":{"detail":"Sie sind nicht berechtigt diese Aktion durchzuführen."}}

when i assign UISettinngs: All, the user works fine.

But i dont want him to be able to change the UISettings.

### Steps to reproduce

- Create user
- no admin
- no superuser
- documents, tags, correspondents and document types all
- espacially UISettings: None

### Webserver logs

```bash
Error message in PLNGX

{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":403,"statusText":"Forbidden","url":"http://nuc:8010/api/ui_settings/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://nuc:8010/api/ui_settings/: 403 Forbidden","error":{"detail":"Sie sind nicht berechtigt diese Aktion durchzuführen."}}

Webserverlogs:

[2024-11-07 07:55:48,781] [INFO] [celery.app.trace] Task documents.tasks.bulk_update_documents[a1d98e16-fd0b-43b1-80cc-7e27c9a790e8] succeeded in 0.19741985108703375s: None

[2024-11-07 07:57:51,912] [WARNING] [django.request] Forbidden: /api/ui_settings/

[2024-11-07 07:57:56,736] [WARNING] [django.request] Forbidden: /api/ui_settings/

[2024-11-07 07:59:44,961] [WARNING] [django.request] Forbidden: /api/ui_settings/

[2024-11-07 07:59:59,820] [WARNING] [django.request] Forbidden: /api/ui_settings/

[2024-11-07 08:00:00,001] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
```

### Paperless-ngx version

2.13.4

### Host OS

Win 11

### Installation method

Docker - official image

### Browser

Chrome, FF, Edge

### Configuration changes

Running system, just added a user without UISettings authorization

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please read the documentation 

https://docs.paperless-ngx.com/usage/#global-permissions
