### ISSUE TITLE
[BUG] Document filtering based on documents?created__date__gt or documents?created__date__lt does not work

### ISSUE THREAD

**Issue by lordzeroMS** [paperless-ngx/paperless-ngx#8221]
### Description

Paperless does not work if you want to filter with specific dates on created date. 

Paperless-ngx-Version
2.13.4
Installationstyp
bare-metal
Serverbetriebssystem
Linux-4.9.0-18-amd64-x86_64-with-glibc2.36

### Steps to reproduce

1. go to documents page
2. click on dates
3. select a date in the last two fields

### Webserver logs

```bash
nothing relevant in logs, no new entries after applying the filter

[2024-11-07 15:05:28,364] [ERROR] [paperless.api] System status detected a possible problem while loading the classifier: Classifier file does not exist (yet). Re-training may be pending.
Traceback (most recent call last):
  File "/opt/paperless/src/documents/views.py", line 2074, in get
    raise FileNotFoundError(classifier_error)
FileNotFoundError: Classifier file does not exist (yet). Re-training may be pending.
[2024-11-07 15:06:07,738] [DEBUG] [paperless.classifier] Training tags classifier...
[2024-11-07 15:08:17,501] [DEBUG] [paperless.classifier] Training correspondent classifier...
[2024-11-07 15:08:43,257] [DEBUG] [paperless.classifier] There are no document types. Not training document type classifier.
[2024-11-07 15:08:43,258] [DEBUG] [paperless.classifier] Training storage paths classifier...
[2024-11-07 15:09:00,779] [INFO] [paperless.tasks] Saving updated classifier model to /opt/paperless/data/classification_model.pickle...
```

### Browser logs

```bash
request: 
page=1&page_size=50&ordering=-created&truncate_content=true&created__date__gt=2024-11-01

response is just an empty response like nothing is matching
```

### Paperless-ngx version

2.13.4

### Host OS

Linux-4.9.0-18-amd64-x86_64-with-glibc2.36

### Installation method

Bare metal

### System status

```json
{
    "pngx_version": "2.13.4",
    "server_os": "Linux-4.9.0-18-amd64-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 1469621125120,
        "available": 1034562764800
    },
    "database": {
        "type": "mysql",
        "url": "c1paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-07T00:02:15.560589+01:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
I highly doubt this is broken (see attached) as it comes straight from Django. If there are no results perhaps checking your timezone settings

![Documents - Paperless-ngx jpeg](https://github.com/user-attachments/assets/92a4897b-beaa-4a3b-8de3-7f8728408272)

**Comment by lordzeroMS** [comment]
even if this is a timezone issue, it is a bug. I guess that is correctly translated into a date in the argument. 

![Bildschirmfoto vom 2024-11-07 15-58-29](https://github.com/user-attachments/assets/8398ab61-067a-4315-864b-76a740c77b8a)

**Comment by shamoon** [comment]
I dont understand your last statement but no, it is not likely to be a bug. Again, date filtering comes straight from Django and no one has changed it lately. You haven't really explained what document(s) you think should be in the result but commonly when it's a 1 day difference it's related to timezone settings, either the browser or in the container. But again, Im sorta guessing.

**Comment by lordzeroMS** [comment]
The statement being executed in the background is:

SELECT DISTINCT `documents_document`.`id`, `documents_document`.`created`
FROM `documents_document`
LEFT OUTER JOIN `documents_note` ON (`documents_document`.`id` = `documents_note`.`document_id`)
WHERE (
    (`documents_document`.`deleted_at` IS NULL AND DATE(CONVERT_TZ(`documents_document`.`created`, 'UTC', 'Europe/Berlin')) > '2024-10-31')
    OR (`documents_document`.`deleted_at` IS NULL AND DATE(CONVERT_TZ(`documents_document`.`created`, 'UTC', 'Europe/Berlin')) > '2024-10-31' AND `documents_document`.`owner_id` = 3)
    OR (`documents_document`.`deleted_at` IS NULL AND DATE(CONVERT_TZ(`documents_document`.`created`, 'UTC', 'Europe/Berlin')) > '2024-10-31' AND `documents_document`.`owner_id` IS NULL)
)
GROUP BY `documents_document`.`id`
ORDER BY `documents_document`.`created` DESC;
However, the DATE(CONVERT_TZ(documents_document.created, 'UTC', 'Europe/Berlin')) function is always returning a NULL value.

The issue is likely due to the time zone data not being loaded into MySQL. To resolve this, you need to load the time zone data. Here is the command to do so:

`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql`
This command loads the time zone information into MySQL, allowing the CONVERT_TZ function to work correctly.

Just for reference, this solution ensures that the time zone conversion functions properly and prevents NULL values from being returned.
