### ISSUE TITLE
[BUG] Firstname not parsed correctly from OIDC claim

### ISSUE THREAD

**Issue by madduck** [paperless-ngx/paperless-ngx#8233]
### Description

My OIDC provider offers claims like `name` and `given_name`, which contain my full name (sorry, wrong screenshot ("wikijs"), but the output for the paperless provider is the same…):

![image](https://github.com/user-attachments/assets/2f2bb98d-97b8-4100-83b7-12d2ce3c723c)

When a new user is created after an OIDC login, their first name will contain the full name, whereas their last name will be what I think is just the last word of the claim:

![image](https://github.com/user-attachments/assets/f34c3a1e-b9c0-4ecb-9ca5-bef1278a9b64)

If this is the logic to parse the full name into first and last, then apart from this logic not being fail-proof, it also seems like it just happens for the last name, whereas the first name is not split into parts.

### Steps to reproduce

1. Log in as new user using OIDC
2. Verify that the first name in the profile is actually the full name.

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

2.13.4

### Host OS

Debian

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

{
    "pngx_version": "2.13.4",
    "server_os": "Linux-6.1.0-26-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 160980459520,
        "available": 141058682880
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-08T00:00:00.070103+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-08T09:05:00.068212Z",
        "classifier_error": null
    }
}

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
All this comes from all-auth.  https://codeberg.org/allauth/django-allauth/issues
