### ISSUE TITLE
[BUG] Docker image tag not semver compliant

### ISSUE THREAD

**Issue by bjw-s** [paperless-ngx/paperless-ngx#824]
### Description

The new docker image tag (`ngx-1.7.0`) format is not compatible with semantic versioning, and can therefore break automated updating tools (such as Renovate) that by default rely on a semantic versioning-style tag.

I would have expected the latest versioned tag to be `1.7.0`.

### Steps to reproduce

Open https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx/20580039?tag=ngx-1.7.0

### Paperless-ngx version

1.7.0

### Host OS

n/a

### Installation method

Docker

**Comment by qcasey** [comment]
This is a recent regression, [1.6.0](https://github.com/paperless-ngx/paperless-ngx/pkgs/container/paperless-ngx/16577132?tag=1.6.0) was tagged correctly. Thank you for pointing this out.

**Comment by qcasey** [comment]
That's a great advantage, and yes now would be a good time to do that. How would `beta-` releases fit into this?

**Comment by stumpylog** [comment]
In the workflow, it would be pretty simple, just adding 2 new flavors for `type=semver`.

For a beta, we would do much the same, create a branch `beta-1.7.1`.  The tagging would any of:
- `beta-1.7.1-rc0`
- `v1.7.1-rc0`
- `v1.7.1-beta`

In my testing, none of those updated the `:latest` tag, to avoid updating everyone to the beta.  There is also going to be an image tag created from the branch already, so potentially there is no need to tag the beta branch?

Releasing is creating 1 tag: `v1.7.1`, which made all of the following:
- `paperless-ngx:1.7.1`
- `paperless-ngx:1.7`
- `paperless-ngx:v1.7.1`
- `paperless-ngx:latest`

Other updates I can think of:
- release process docs for the decided rc/beta tag names and the final tag name
- user docs to explain pinning to a major.minor
- small change in the remote version checker

**Comment by qcasey** [comment]
Okay that's easy enough. I'll manually retag 1.7.0 for now

**Comment by qcasey** [comment]
@stumpylog I noticed your branch [feature-semver-tags](https://github.com/paperless-ngx/paperless-ngx/tree/feature-semver-tags) seems to have these changes implemented already. Is that true, and if so do you mind if we draft that PR?

**Comment by qcasey** [comment]
Fixed in #851
