### ISSUE TITLE
[BUG] PDF/A-B "archive" files have inconsistent date display presentation formats

### ISSUE THREAD

**Issue by easyas314** [paperless-ngx/paperless-ngx#8245]
### Description

Just started with paperless-ngx and while reviewing some "consumed" document information, the metadata for the archived PDF/A-2B has:

`xmp:CreateDate	2024-10-19T15:30:50-04:00` 
- which looks like the right date/time when the original pdf was created; and displaying it as my local time with an offset from UTC.

`xmp:ModifyDate	2024-11-10T03:24:01+00:00`
- which looks like the right time (very recent to this post), but it is differently presenting the date/time -- it's UTC showing the +00:00 offset from UTC.

`xmp:MetadataDate	2024-11-10T03:24:01.323978+00:00`
- this is like the ModifyDate; ie, a UTC-like presentation

3 dates and 2 formats --- I was seriously thinking there was a problem with the upstream OCRmyPDF, pikepdf, and the system time zone, but I finally realized all 3 date *values* are very similar and correct. I was thinking the "ModifyDate" and  "MetadataDate" fields were 5 hours in the future!

It's the inconsistency of the formats that completely derailed me.

Are the data values stored as strings and paperless is just displaying those strings? (Possibly a case that the upstream tools are also inconsistent.) Regardless, the paperless GUI should be providing a consistent presentation of date/time because the **values** are correct.

fyi - the host date / time setting:
```# timedatectl status
               Local time: Sat 2024-11-09 22:34:05 EST
           Universal time: Sun 2024-11-10 03:34:05 UTC
                 RTC time: n/a
                Time zone: America/New_York (EST, -0500)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
```

### Steps to reproduce

Go to a Documents.
Double-click on a document.
Go to the Metadata tab for the document.
If needed, expand the "Archived document metadata" section.

Screenshot of same:
![image](https://github.com/user-attachments/assets/74300dac-a641-4d6e-90f5-78469a49faa0)

### Webserver logs

```bash
n.a.
```

### Browser logs

```bash
n.a.
```

### Paperless-ngx version

2.13.4

### Host OS

Proxmox helper-script installed as an LXC (linux container)

### Installation method

Other (please describe above)

### System status

```json
{
    "pngx_version": "2.13.4",
    "server_os": "Linux-6.8.12-3-pve-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 7659816484864,
        "available": 4560667148288
    },
    "database": {
        "type": "postgresql",
        "url": "paperlessdb",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-09T22:24:03.510649-05:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-10T04:05:00.025948Z",
        "classifier_error": null
    }
}

**NICE** even this has inconsistent date/time presentation.  ;-p
```

### Browser

not relevant

### Configuration changes

n.a.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Paperless does not generate the files and does not set the metadata itself
