### ISSUE TITLE
[BUG] Extended search does not work with ASN

### ISSUE THREAD

**Issue by gador** [paperless-ngx/paperless-ngx#825]
### Description

When trying to search for ASN in the extended query, no documents get returned. 
Also I am not sure which field to use here. I tried `asn`, `ASN`, `archive_serial_number`. 

Non of them return the document. 

I know there is the ASN search query, but I am trying to create a saved search with `ASN>0` or something like `ASN not empty` 

Has anyone got this working? 

Unfortunately, the documentation does not include the search terms the user can use in the extended search. Maybe we should add them (once I figure out, what those are..)

### Steps to reproduce

Go to paperless and choose Advanced earch. Then try to filter for ASN:

![image](https://user-images.githubusercontent.com/1883533/165702401-6e0ec28a-ad29-474a-9645-319897b9400a.png)

### Webserver logs

```bash
Non related to search.
```

### Paperless-ngx version

1.7.0

### Host OS

Ubuntu 20.04

### Installation method

Docker

### Browser

Brave

**Comment by qcasey** [comment]
I wonder if this is related to #509

**Comment by shamoon** [comment]
FYI this is doable with the query var `archive_serial_number__isnull` but the PR adds a proper UI to it too. 👍

**Comment by qcasey** [comment]
What about the `ASN>0` case?

**Comment by shamoon** [comment]
Doh, I lied, `archive_serial_number__gt` comes 'built-in' from Django. Adding that would mean complicating the UI a bit (the empty toggle becomes like a dropdown presumably) as well as the logic. Before I do that, though, would it actually be useful to anyone?

**Comment by shamoon** [comment]
Who am I kidding, I'm already working on it 😂

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/f3d6fcb52b11840549980824bfda36816f568511
