### ISSUE TITLE
[BUG] document_exporter: --compare-checksums does not work for manifest json files

### ISSUE THREAD

**Issue by kdoren** [paperless-ngx/paperless-ngx#8260]
### Description

When using document_exporter with --compare-checksums, the json files are always written even if there are no changes.  If --split-manifest is also enabled (1 manifest file per document), then a new manifest file will be written for each document every time document_exporter runs. 

This causes a problem when using a file sync backup method for the export directory, such as "aws s3 sync".  The changed file timestamps cause the json files to be uploaded to s3 every time document_exporter is run, even if nothing has changed. 

I have implemented a fix for this.  I will issue a PR.

### Steps to reproduce

1. run document_exporter. observe the timestamps for manifest.json and metadata.json in the export directory.
2. run document_exporter again using --compare-checksums.  The timestamps will change for the json files, but they will not change for the document files.
3. if --split-manifest is used, there will be a manifest file with a changed timestamp for every document

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.13.2

### Host OS

Raspberry Pi 5 (arm64)

### Installation method

Docker - official image

### Browser

Edge

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
This feels much more like a feature request. Nothing about the documentation implies checksum comparison is for anything except documents.

I'll see about the "fix" you've linked.

**Comment by kdoren** [comment]
For documents, the behavior is already to avoid writing files unless they have changed.  Either by checking timestamps, or --compare-checksums.  And with good reason.

The json files should be treated the same.  There's no source file to check timestamps.  IMO it would be best if the json checksums were always compared.  But certainly when --compare-checksums is used, so I implemented it that way and wrote it up as a bug.

What this enables is something like an incremental backup using "aws s3 sync", especially if --split-manifest is used.  rsync would be similar.  Add 1 document, then only that document's files are written when synched.  Add no documents, the no files are written when synced.

**Comment by stumpylog** [comment]
It's still a feature request, not a bug.  And things like rsync, rclone, etc, can compare by checksums as well, instead of using mtime.
