### ISSUE TITLE
[BUG] Deleting custom field select option causes inconsistent document/custom field instance state

### ISSUE THREAD

**Issue by pschucker** [paperless-ngx/paperless-ngx#8262]
### Description

Deleting an option of a select type custom field does not update custom field instances of documents (see steps to reproduce).
Looking at the data model, it appears that only the index of the list of options is stored in custom field instances. So if an option is removed, the stored index will point to an incorrect value.

Possible solutions:
- on option deletion, reset value_select for all custom field instances that reference the deleted value. Reduce value_select by 1 for all other instances with an index greater than the index of the deleted option.
- Instead of playing with indices, we could switch to a better data model that does not rely on indices. For example instead of a simple list `{"select_options": ["Option 1", "Option 2", "Option 3"]}`, we could use something like  
    ```json
    {
        "select_options": [
            {
                "id": 1,
                "name": "Option 1"
            },
            {
                "id": 2,
                "name": "Option 2",
                "deleted": true
            },
            {
                "id": 3,
                "name": "Option 3"
            }
        ]
    }
    ```
   This way, deleting is no longer an issue, and migration would be easy because we could keep the current values.

### Steps to reproduce

1. Create a custom field of type select with 3 options ("Option 1", "Option 2", "Option 3").
2. Assign "Option 1" to document 1, "Option 2" to document 2, "Option 3" to document 3.
3. Edit the custom field definition and delete "Option 2".
4. Result: Document 1 still correct, Document 2 now has "Option 3" assigned instead of no value, Document 3 has no value instead of "Option 3".

### Webserver logs

```bash
N/A
```

### Paperless-ngx version

2.13.4

### Host OS

Amazon Linux 2023 x86_64

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Ps. I think you will find it’s more complicated than the above, for example, what if the user changes just the order of the options? This is why we’ve just sorta left it up to the user to deal with.

**Comment by shamoon** [comment]
I can add some kind of warning to the dialog, but I think its still useful to be able to do this, for example if you haven't added them to any fields yet, or if you just want to change the text of one option, etc.

If you'd like to open a FR I can look at doing this at some point, just dont really have the time at the moment.

Pros/cons either way of course.
