### ISSUE TITLE
[BUG] Import Error on PDF Filenames with Umlaut (ä, ö, ü, ß)

### ISSUE THREAD

**Issue by carlo17** [paperless-ngx/paperless-ngx#8265]
### Description

I regularly backed up a Paperless NGX Docker Instance into a ZIP file via the "document_exporter" on my Synology NAS.

After a crash of the NAS I decided to move my Docker instance to another base machine with a more modern Hardware. I setup a black Ubuntu and installed Paperless NGX with the installation script provided by the project.

During the import I faced multiple Error because of ä, ö, ü, ß in the exported document names. After renaming all file manually and editing the manifest file accordingly I was able to import the backup after maybe 50 to 60 attempts.

### Steps to reproduce

I specifically fixed the Issue by renaming the files to import in the extracted folder and edited the manifest file accordingly. All other ä, ö, ü, ß have not been changed in the manifest.

### Webserver logs

```bash
(I have no logs of the installation process)
```

### Paperless-ngx version

2.13.4

### Host OS

Ubuntu 24.04.1 LTS

### Installation method

Docker - official image

### Browser

Arc, FireFox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please have a search. This has been reported in the past and is a file system issue.
