### ISSUE TITLE
[BUG] Header bar unexpectedly shifts down, covering content in Paperless-ngx file tasks view

### ISSUE THREAD

**Issue by Friedjof** [paperless-ngx/paperless-ngx#8277]
### Description

Currently, Paperless-ngx has a layout issue where the green header bar is unexpectedly shifted downward in the file tasks view. This behavior causes the header bar to overlap with the list of documents, obscuring parts of the content and limiting usability.

This issue seems to affect the display of file tasks, specifically when viewing the completed or pending tasks. The header bar should remain fixed at the top of the page but instead appears further down, creating a distracting overlay over the content area.

**Expected Behavior**: The header bar should remain at the top, outside the document list, without obscuring any content in the file tasks view.

**Actual Behavior**: The header bar is shifted down and overlays part of the content area.

![Eingefügtes Bild](https://github.com/user-attachments/assets/d2f99482-774c-493c-8134-acceea353256)

### Steps to reproduce

1. Open Paperless-ngx and navigate to the "File Tasks" section.
2. View the list of tasks under "Completed" or "Pending."
3. scrawl down (browser on mobile / desktop)
4. Observe that the header bar is shifted downward, covering part of the list view.

### Webserver logs

```bash
_No specific web server errors were noted in the log for this layout issue._
```

### Browser logs

```bash
_No specific browser errors were noted in the console for this layout issue._
```

### Paperless-ngx version

2.13.5

### Host OS

Synology DS923+

### Installation method

Docker - official image

### Browser

Tested on Chrome, Firefox (Ubuntu 24LTS)

### Configuration changes

_No configuration changes were made to the default setup._

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Are you referring to the little 'bounce' of the header when scrolling? Thats normal. Otherwise, I cant reproduce this and nothing has changed. Certainly the steps above ("scroll") are not enough to reproduce anything...

Feel free to add more context but Im not inclined to think theres a real issue here


Uploading 8277.mov…
