### ISSUE TITLE
[BUG] Finished upload Document not show webUI

### ISSUE THREAD

**Issue by RazorDarkAMG** [paperless-ngx/paperless-ngx#8303]
### Description

Hello,

For some time, when I upload a new document on paperless-ngx I have the progress bar that remains blocked and no longer moves, the document is uploaded well and when I update the page "Document" I see the document that was uploaded, but the progress bar remains frozen and does not tell me that the task is complete.

I thought it was a problem of my browser cache so I empty it but it does not change anything, try with another web browser same, I am not sure that the problem comes from paperless-ngx or from home, have you ever had this problem?

Thank you!

### Steps to reproduce

Drag & Drop new document in webUI.

### Webserver logs

```bash
Document is upload and everything is OK on logs, it is webUI issue.
```

### Paperless-ngx version

2.13.5

### Host OS

OMV 7.4.11-1 amd64

### Installation method

Docker - linuxserver.io image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not a bug, there’s an issue with your websockets setup.

**Comment by RazorDarkAMG** [comment]
I’m stupid, you’re right, I still use the remote version and not in local, I just tried with the local address and indeed I no longer have this problem, I have to fix it at Nginx proxy manager.

Thank you very much and really sorry for the bleeding.
