### ISSUE TITLE
[BUG] Umlauts in filenames in media directory are not correctly recognized by rsync

### ISSUE THREAD

**Issue by Ralf31337** [paperless-ngx/paperless-ngx#8337]
### Description

Paperless just works fine. I have all my media mounted to a volume in paperless docker container. I rsync all files to an attached hard disk.

If one repeatedly starts the rsync, in my case files with an "ö" are copied again every time.

I do an rsync -avu --delete media /mnt/backup/media

The reason for this issue given in rsync discussions is: Normalization Form C (NFC) and Normalization Form D (NFD)

The solution would be that the outside system (in my case en_US.UTF-8) is the same and is installed inside the container. I can't judge about the side-effects for paperless-ngx if I change the locale, so if this is something you haven't thought about, I would appreciate if this issue triggers the discussion.

### Steps to reproduce

1. Put a file with umlaut in paperless
2. rsync to external hard drive with filesystem on source and destination of type ext4
3. run rsync again, nothing happens, except files with umlaut are copied again

### Webserver logs

```bash
there are no logs related
```

### Paperless-ngx version

1.17.4

### Host OS

Raspberry PI 4

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
> Paperless just works fine

I really don’t see why you would open a bug report for this? If you’d like to have a discussion about something, please start a discussion.
