### ISSUE TITLE
[BUG] Thumbnail doesn't get updated after document rotation

### ISSUE THREAD

**Issue by Nevarro** [paperless-ngx/paperless-ngx#8344]
### Description

After rotating a document, the thumbnail doesn't get updated. It remains in the wrong orientation.

### Steps to reproduce

1. Scan a document, 2. Go into edit mode, 3. rotate and save the document, 4. go back to document overview.

### Webserver logs

```bash
-
```

### Paperless-ngx version

2.13.5

### Host OS

Unraid (docker)

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Clear your cache?

it most certainly does, note that the tasks are run asynchronously in the task queue so it’s not immediate.
