### ISSUE TITLE
[BUG] Cannot save monetary custom field value using CTRL+S without focusing

### ISSUE THREAD

**Issue by OverDodo** [paperless-ngx/paperless-ngx#8360]
### Description

When you enter a value in a monetary custom field and press CTRL+S to save, **but without unfocusing the input field** first, an error will occur, stating the input value is not valid. Pretty niche again, but something I will be using alot more once the Save+Next shortcut is released, which I assume would have the same issue.

See the request body missing the decimals, even when i enter them:
<img width="242" alt="image" src="https://github.com/user-attachments/assets/eea39c6c-7a69-4055-a708-e907c8821a3b">

<img width="378" alt="image" src="https://github.com/user-attachments/assets/e79fc823-269b-4925-9a78-304317dc5617">

### Steps to reproduce

1. Add a custom monetary field to a document
2. enter any numeric value (that should be valid, in my example i tried all three: "28", "28.00", "28,00")
3. Press CTRL+S to save without unfocusing the input

### Webserver logs

```bash
stderr	[2024-11-26 20:36:53,311] [WARNING] [django.request] Bad Request: /api/documents/2939/
```

### Paperless-ngx version

2.13.5

### Host OS

Synology DSM 7.2 | x86_64

### Installation method

Docker - official image

### Browser

Edge, Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This is not a bug, its a combination of limitations and frankly the solution is absurdly easy, you have to focus out of the field.

**Comment by shamoon** [comment]
Ps. I suppose you could open a change request

**Comment by OverDodo** [comment]
Thanks a lot, appreciate it 😊
