### ISSUE TITLE
Cant upload any doc or txt file, after Barcode seperation enabled

### ISSUE THREAD

**Issue by aytec** [paperless-ngx/paperless-ngx#837]
### Description

After putting PAPERLESS_CONSUMER_ENABLE_BARCODES=1 in my env, the seperation of pdf files works perfect, but i cant put any office documents to paperless. i if upload it via browser, it just says uploading and nothing else happens. If i put it in my consume folder by hand, nothing happens at all. Even in the protocol there is no entry about that document. 

If i delete the line PAPERLESS_CONSUMER_ENABLE_BARCODES=1 from env, everythings works back again, but of course without barcode seperation.

### Steps to reproduce

After putting PAPERLESS_CONSUMER_ENABLE_BARCODES=1 in my env, the seperation of pdf files works perfect, but i cant put any office documents to paperless. i if upload it via browser, it just says uploading and nothing else happens. If i put it in my consume folder by hand, nothing happens at all. Even in the protocol there is no entry about that document. 

If i delete the line PAPERLESS_CONSUMER_ENABLE_BARCODES=1 from env, everythings works back again, but of course without barcode seperation.

### Paperless-ngx version

1.7

### Host OS

20.04.4 

### Installation method

Docker

### Browser

Chrome

### Configuration changes

PAPERLESS_CONSUMER_ENABLE_BARCODES=1

**Comment by gador** [comment]
Can you please provide the logs?
It would be helpful if you cou enable debugging for the logs.

Thanks 👍

**Comment by aytec** [comment]
Hi, thanks for answering. There is no Barcode at all in the docx. Even a docx containing one single words, stops after uploading. Seems like paperless does not longer know how to use Tinka/Gotenberg.
one of the results:

> 
Unable to get page count.
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
: Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 479, in pdfinfo_from_path
raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/usr/src/paperless/src/documents/tasks.py", line 198, in consume_file
separators = scan_file_for_separating_barcodes(path)
File "/usr/src/paperless/src/documents/tasks.py", line 105, in scan_file_for_separating_barcodes
pages_from_path = convert_from_path(filepath, output_folder=path)
File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 98, in convert_from_path
page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
File "/usr/local/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 488, in pdfinfo_from_path
raise PDFPageCountError(
pdf2image.exceptions.PDFPageCountError: Unable to get page count.
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref `table `

i enabled debugging, but where can i find the logs that you wanted for investigation?
`

**Comment by gador** [comment]
I think this is the same issue as in #746 and was fixed in #766. 
I was able to reproduce the bug in the current (latest) 1.7.0 image. It isn't present in the current `dev` tag. 

@stumpylog @shamoon @qcasey : maybe we should make a 1.7.1 release sometime soon to include this bugfix?

**Comment by shamoon** [comment]
Yea! See https://github.com/paperless-ngx/paperless-ngx/milestone/4

**Comment by stumpylog** [comment]
This should be fixed in 1.7.1, which includes #766
