### ISSUE TITLE
[BUG] Mail import guesses MIME type (incorrectly) rather than considering taking Content-Type header

### ISSUE THREAD

**Issue by madduck** [paperless-ngx/paperless-ngx#8371]
### Description

When a mail containing a `.doc` file is slurped up by the mail importer, the MIME part's content-type is ignored, and instead the content type guess to be `text/html`. Consequently, the import fails:

```
[2024-11-28 13:20:00,467] [DEBUG] [paperless_mail] Rule DMS Upload.Slurp all mail, attachments only: Skipping attachment 2023-01-09-Concept.doc since guessed mime type text/html is not supported by paperless
```

Paperless ignores the MIME tree of the message, which correctly identifies the attachment:

```
  I     1 <no description>                                                    [multipa/mixed, 7bit, 12K]
  I     2 ├─><no description>                                            [text/plain, 7bit, utf-8, 0,1K]
  A     3 └─>paperless.doc                                                 [applica/msword, base64, 12K]
```

No need to guess…

### Steps to reproduce

1. Get Paperless mail importer to read in the [MIME message contained in this ZIP file](https://github.com/user-attachments/files/17948583/paperless-mail-message.zip);
2. Observe the log stating that `text/html` was guessed as the MIME type, which is not supported;
3. Observe the mail/attachment not getting imported.

### Webserver logs

```bash
n/a
```

### Browser logs

```bash
n/a
```

### Paperless-ngx version

2.13.4

### Host OS

Debian stable

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.4",
    "server_os": "Linux-6.1.0-26-amd64-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 160980459520,
        "available": 131432357888
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-28T13:40:24.160534+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-28T13:05:29.721061Z",
        "classifier_error": null
    }
}
```

### Browser

n/a

### Configuration changes

Tika and Gotenberg are enabled (Docker images)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This has been discussed before, please search. Mine type guessing is from other tools and the email likely is malformed in a way that causes this. I actually think there was a change to the library we use that might change this but hasn’t been released yet.

**Comment by madduck** [comment]
@shamooon I searched existing issues and discussions, but I could not find an issue or discussion that describes this problem, or explains any of it. What did I miss?

The email is not malformed, it's perfectly adherent to the MIME standard, I checked that.

My point is that the MIME type should not be guessed by other tools, because it's already known. If you are referencing Tika, then I cannot discern from the code that you are actually including the information of the content-type provided in the mail to Tika, which would enable Tika to not start at 0. Have a look at e.g. https://github.com/paperless-ngx/paperless-ngx/blob/dev/src/paperless_mail/parsers.py#L71 and take note how the `mime_type` function argument of all functions in that file is simply not used, i.e. ignored.

**Comment by madduck** [comment]
If you are suggesting I missed https://github.com/paperless-ngx/paperless-ngx/issues/7537 then that is not accurate. The issue there is that an email per se is misclassified by `libmagic`. In my case, the attachment is extracted and the content-type ignored, thus leaving Tika to do guessing, which it fails to do. But my point is that Tika shouldn't need to guess…

**Comment by madduck** [comment]
> Ah, so you've once again requested to change something and opened it as a bug?

I am sorry this is the impression I caused. No. I do consider this a bug. The bug in Paperless is not that Tika misclassifies a Word Document. That is a Tika issue. The issue with Paperless is that it drops vital information in the pipeline, which would prevent this Tika problem from happening.

Is this not a bug?

**Comment by shamoon** [comment]
I don’t see it that way, hard to believe most would.

Paperless has never done what you are describing, so this “bug report” is (again) just your assertion that something be done a different way. So, squarely a change/feature request.

**Comment by madduck** [comment]
I am sorry that I am not totally on top of the difference between a feature request and a bug, especially in this case. It works, so in that view there is no bug. It could work better because it has the information, but it drops that information. So a change request? Sure, you can see it that way.

When I created the issue, it didn't look like a feature request, because when I saw Paperless unable to handle a doc attachment, I naturally thought about a bug.

What now? Should I create a new discussion?
