### ISSUE TITLE
[BUG] TypeError: 'PDFObjRef' object is not iterable

### ISSUE THREAD

**Issue by MAX5489312654** [paperless-ngx/paperless-ngx#8380]
### Description

I keep getting this error on almost all my PDF that I try to import. Only a few are getting imported without this error. 

"filename.pdf: Error occurred while consuming document filename.pdf: TypeError: 'PDFObjRef' object is not iterable"

### Steps to reproduce

Import File by drag and drop or monitored folder. 

### Webserver logs

```bash
File "/usr/src/paperless/src/documents/consumer.py", line 509, in run
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: filename.pdf: Error occurred while consuming document filename.pdf: TypeError: 'PDFObjRef' object is not iterable
```

### Paperless-ngx version

2.13.4

### Host OS

unRaid

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.4",
    "server_os": "Linux-6.1.118-Unraid-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 3998833471488,
        "available": 2941184978944
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://192.168.0.191:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-29T09:53:14.343013-08:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-29T18:05:11.774817Z",
        "classifier_error": null
    }
}
```

### Browser

Safari, chrome  Any with same result

### Configuration changes

none. 

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
> [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.

I really dont know how to make it clearer

Paperless does not do the OCR / archive file creation itself. Please read the issue template you filled out more carefully for more information.

**Comment by Tschi02** [comment]
I get the same error and was about to raise an issue as well. As a non-contributer it can be hard to tell if the error origins in ocrmypdf or paperless-ngx, unfortunatelly. Thanks for your hard work, @shamoon! ❤️
