### ISSUE TITLE
[BUG] Small typo in german popup when assigning Tags

### ISSUE THREAD

**Issue by github-Jan** [paperless-ngx/paperless-ngx#8405]
### Description

![image](https://github.com/user-attachments/assets/8b3a0eaa-519c-41ea-b20d-d811f814a683)

"Diesr Vorgang"
-> "Dieser Vorgang"
missing an "e"

it is correkt when assigning correspondents

### Steps to reproduce

Switch to german assign tags.

### Webserver logs

```bash
not needed
```

### Paperless-ngx version

2.13.5

### Host OS

Ubuntu 22.04 docker 

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Translation updates are handled over at Crowdin.
