### ISSUE TITLE
[BUG] Email import not running. Celery beat fails. 

### ISSUE THREAD

**Issue by cibernox** [paperless-ngx/paperless-ngx#8429]
### Description

I noticed that my emails haven't imported for weeks, probably since my last restart. Digging a bit, I found that it's the "Paperles Celery beat" that is failing, as shown by the output of `systemctl`:
```
// skipping lines
  paperless-consumer.service                                        loaded active     running         Paperless consumer
* paperless-scheduler.service                                       loaded failed     failed          Paperless Celery beat
  paperless-task-queue.service                                      loaded active     running         Paperless Celery Workers
  paperless-webserver.service                                       loaded active     running         Paperless webserver 
```

The log for the service shows an very (very) lengthy error, but the bottom line seems to be that it can  "add item to the database".
It's so long I decided to put it on a gist: https://gist.github.com/cibernox/77bfebbf603ee056cfd4de0639363d7b

Any idea on what might be going on?

### Steps to reproduce

I don't do anything particularly weird. I've configured paperless to import from my gmail account and it did work for some weeks.

### Webserver logs

```bash
https://gist.github.com/cibernox/77bfebbf603ee056cfd4de0639363d7b
```

### Paperless-ngx version

2.13.5

### Host OS

LxC container on proxmox

### Installation method

Other (please describe above)

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
I'm not going to visit a random link to view logs which can be pasted. 99% sure it will simply be solved by removing the beat schedule and restarting

**Comment by stumpylog** [comment]
Ok, just a gist. But really why?

As expected, it's a common error with the same solution posted many times, just as suspected.

**Comment by cibernox** [comment]
I though I was being helpful not dropping a thousand lines of log into the first message. Pasted.

**Comment by cibernox** [comment]
@stumpylog what file should be removed? I did check the troubleshooting page in https://docs.paperless-ngx.com/troubleshooting/ before opening the issue.

**Comment by stumpylog** [comment]
https://github.com/paperless-ngx/paperless-ngx/issues?q=is%3Aissue+_dbm.error
