### ISSUE TITLE
[BUG] Getting 404 Errors behind Cloudflare Tunnel

### ISSUE THREAD

**Issue by Openhabber** [paperless-ngx/paperless-ngx#845]
### Description

Hello,

locally, paperless is working without any problems. However, accessing it from outside behind a cloudflare argo tunnel and cloudflare access seems not work so well.

Most of it works, but I often get 404 pages at random, and while clicking buttons in the UI. In Chrome, the following messages are present (im not sure what those mean or where they are created):

`Unsafe attempt to load URL https://MYDOMAIN.cloudflareaccess.com/cdn-cgi/access/login/docs.MYDOMAIN.com?kid=<removed>&redirect_url=%2Fassets%2Fbootstrap-icons.svg&meta=<removed>#trash from frame with URL https://docs.MYDOMAIN.com/documents/418. Domains, protocols and ports must match.`

`Access to XMLHttpRequest at 'https://MYDOMAIN.cloudflareaccess.com/cdn-cgi/access/login/docs.MYDOMAIN.com?kid=<removed>&redirect_url=%2Fapi%2Fcorrespondents%2F%3Fpage%3D1%26page_size%3D100000&meta=<removed>' (redirected from 'https://docs.MYDOMAIN.com/api/correspondents/?page=1&page_size=100000') from origin 'https://docs.MYDOMAIN.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have no problems whatsoever with several other self-hosted services.
Im also not sure if the above errors are related whatsoever..

### Steps to reproduce

1. Try to access paperless through a cloudflare-tunnel

### Paperless-ngx version

1.7.0

### Host OS

Synology with Docker

### Installation method

Docker

### Browser

Chrome

**Comment by shamoon** [comment]
I’m not clear this is a bug tbh. Have you tried setting `PAPERLESS_CORS_ALLOWED_HOSTS` as the error is complaining about?

**Comment by Openhabber** [comment]
Additional note:
I cannot login also. I just tried to use auto login, as I have authentication through cloudflare.

I set up PAPERLESS_URL.
 If I dont set it up, I just get a CSRF verification failed error.
Now I don't get any error at all. It just loops back to the login page, and there's nothing in the logs.

Local access works fine.

Please tell me if I can give any additional information.

**Comment by Openhabber** [comment]
I think I fixed it.. I tried several settings of cloud flare and am not sure which one was making problems:

-Changed session duration to 24h from no duration
-disabled bot protection (which injects JavaScript)
-changed some cookie settings to Strict and http only (don't think this has an effect).

Still using auto login.
Very strange...
