### ISSUE TITLE
[BUG] "Cannot load classifier, incompatible versions" after upgrade to 1.7.0

### ISSUE THREAD

**Issue by nepomuc** [paperless-ngx/paperless-ngx#847]
### Description

I upgraded my paperless-ngx using docker with `docker-compose pull && docker-compose up --force-recreate -d && docker image prune -f`.
Then I saw the error in the paerless-ngx-logs.

### Steps to reproduce

1. Pull new docker image of paperless-ngx 1.7.0
2. Upgrade your docker-container

### Webserver logs

```bash
[2022-04-30 15:24:16,533] [ERROR] [paperless.classifier] Unrecoverable error while loading document classification model, deleting model file.

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/classifier.py", line 40, in load_classifier

    classifier.load()

  File "/usr/src/paperless/src/documents/classifier.py", line 81, in load

    raise IncompatibleClassifierVersionError(

documents.classifier.IncompatibleClassifierVersionError: Cannot load classifier, incompatible versions.
```

### Paperless-ngx version

1.7.0

### Host OS

Docker 20.10.14 on Debian 11

### Installation method

Docker

**Comment by gador** [comment]
Interesting. I haven't seen this error on upgrade.
I know `force-recreate` should do that, but can you stop the container, remove it and and `docker-compose pull && docker-compose up` again?
Can you please post you docker-compose.yml and the .env file?

**Comment by nepomuc** [comment]
### What I did just now:

1. Pulled full backup of the entire system just before the paperless-ngx upgrade (=rollback to paperless-ngx 1.6.0)
2. `docker-compose stop`
3. `docker-compose down`
4. Added `PAPERLESS_ENABLE_UPDATE_CHECK=true` to docker-compose.env
5. `docker-compose pull && docker-compose up -d`

Now only the following warning got logged:
`[2022-04-30 15:52:47,041] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/src/../consume

[2022-04-30 15:52:47,204] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/src/../consume/__paperless_write_test_35__: Unknown file extension.`

1. Rebooting entire LXC.
2. No additional errors after reboot 🤨

**So unfortunately I wasn't able to reproduce the error this way.**

### Trying to do the exact same like I did the first time:

1. Pulled full backup of the entire system just before the paperless-ngx upgrade (=rollback to paperless-ngx 1.6.0)
2. `docker-compose pull && docker-compose up --force-recreate -d && docker image prune -f`
3. No classifier errors, yet.
4. Added `PAPERLESS_ENABLE_UPDATE_CHECK=true` to docker-compose.env
5. `docker-compose down && docker-compose up -d`
6. Meh. No errors :/

**That's really weird. I recreated the entire case exactly the same this time.**

### docker-compose.yml

`version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /home/nepomuc/paperless-inbox:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
  redisdata:`

### docker-compose.env

`# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
#PAPERLESS_OCR_LANGUAGES=tur ces

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=_________________________________

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=Europe/Berlin

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=deu+eng

PAPERLESS_ENABLE_UPDATE_CHECK=true`

**Comment by gador** [comment]
alright. maybe it was just a quirk. 
Re-creating containers sometimes help. Its like turning it off-and-on again.
Not really satisfying, though. 

I am closing this. If something like this happens again, feel free to re-open
