### ISSUE TITLE
[BUG] Uploading of documents of the office type is not supported

### ISSUE THREAD

**Issue by benhailong** [paperless-ngx/paperless-ngx#8506]
### Description

<img width="405" alt="image" src="https://github.com/user-attachments/assets/200720e3-09b7-4259-b82d-a181b2ae59c5" />
Upload office type document reported error

### Steps to reproduce

Upload office type document reported error

### Webserver logs

```bash
Upload office type document reported error
```

### Paperless-ngx version

2.13.5

### Host OS

Linux-5.10.55+-x86_64-with-glibc2.36

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.5",
    "server_os": "Linux-5.10.55+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 954489372672,
        "available": 405290618880
    },
    "database": {
        "type": "sqlite",
        "url": "/usr/src/paperless/data/db.sqlite3",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0001_initial_squashed_0009_mailrule_assign_tags",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-12-17T02:53:32.069337Z",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-12-17T03:05:00.589593Z",
        "classifier_error": null
    }
}
```

### Browser

chrome

### Configuration changes

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless/redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8601:8000"
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/docker/paperless/media:/usr/src/paperless/media
      - /volume1/docker/paperless/export:/usr/src/paperless/export
      - /volume1/docker/paperless/consume:/usr/src/paperless/consume
#    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379

volumes:
  data:
  media:
  redisdata:

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
Please "read the manual"
