### ISSUE TITLE
[BUG] OIDC Redirect URI on HTTP force use of HTTPS

### ISSUE THREAD

**Issue by vhaudiquet** [paperless-ngx/paperless-ngx#8550]
### Description

I successfully set up OIDC on Paperless-ngx with Authentik. I'm using paperless only on my local network, which I connect to via VPN, so I don't need HTTPS for paperless.

I set up OIDC with Authentik, but Paperless automatically uses `https://paperless.local/accounts/oidc/authentik/login/callback/` as a redirect URI instead of `http://paperless.local/accounts/oidc/authentik/login/callback/`. It still works fine if i allow this URI in authentik and remove the 's' by hand after redirection.

I already have set: `PAPERLESS_URL=http://paperless.local`. Is there another environment variable I can set to tell it to use http ? Or is this not supported/a bug ?

Thank you.

### Steps to reproduce

Setup paperless OIDC with authentik using http only. Watch the redirection to https.

### Webserver logs

```bash
--
```

### Paperless-ngx version

2.13.5

### Host OS

Debian x86_64

### Installation method

Docker - official image

### Browser

Firefox (zen browser)

### Configuration changes

PAPERLESS_URL=http://paperless.local
      
PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": "<ID>",
                "secret": "<SECRET>",
                "settings": {
                  "server_url": "https://authentik.vhaudiquet.fr/application/o/paperless/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment]
Please read the documentation.  https://docs.paperless-ngx.com/configuration/#PAPERLESS_ACCOUNT_DEFAULT_HTTP_PROTOCOL
