### ISSUE TITLE
[BUG] Dropdown for "Custom Field" value type "Select" not shown when changing Multipe documents

### ISSUE THREAD

**Issue by kagithd** [paperless-ngx/paperless-ngx#8557]
### Description

If you mark several Documents to Add/Remove Custom fields, for  such of type "Select" there is no dropdown shown to specify the Value. 
Instead if you chose the Name of the Select Field, this name is Added to all of the selected Value instead of the Posibility to choose the Value

### Steps to reproduce

1. create a custom field type select 
2. create several Option in that field
3. choose several documents in "Documents" view
4. try to add a single option out of the select field to the document 
5. Dropdown is not shown 

### Webserver logs

```bash
n.a.
```

### Paperless-ngx version

2.13.5 

### Host OS

Ubuntu 24.04 / docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
2.13 does not contain the ability to select a custom filed value of any type, that’s clearly not a bug it just wasn’t implemented at all yet.

Good news is it’s in our next release already.
