### ISSUE TITLE
Demo down?

### ISSUE THREAD

**Issue by lue30499** [paperless-ngx/paperless-ngx#856]
### Description

Hello,

I am trying to access the demo but I am met with a cloudflare error.

![image](https://user-images.githubusercontent.com/63104612/166145043-26a608b6-d188-458b-ac09-f3be0cb8f735.png)

### Steps to reproduce

Go to https://demo.paperless-ngx.com/ 

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

na

### Host OS

na

### Installation method

Other (please describe above)

### Browser

All

**Comment by shamoon** [comment]
Yea, good ol free cloud tier
