### ISSUE TITLE
[BUG] 1.7.0 silently ignores "invalid" dates

### ISSUE THREAD

**Issue by bllngr** [paperless-ngx/paperless-ngx#857]
### Description

1.6.0 showed an error when an entered date could not be parsed, and disabled saving a document until the date was corrected.  
1.7.0 silently ignores the error, discards the invalid date on save, and uses the previously entered value.

### Steps to reproduce

1. Edit a document, remember the value for "Date created"
2. Enter e.g. "31_12_2020" in the date input field
3. Save document and reopen
4. Observe the date having the previous value

Try the same with v1.6.0. Step 3) fails with an error, and the document cannot be saved.

### Paperless-ngx version

1.7.0

### Host OS

Synology Diskstation DSM

### Installation method

Docker

### Browser

Firefox 99.0.1 on Windows 10

### Configuration changes

```
PAPERLESS_DATE_ORDER=DMY
PAPERLESS_FILENAME_DATE_ORDER=DMY
PAPERLESS_IGNORE_DATES=01.01.2020
```

### Other

Probably related to #250 or #253.

**Comment by shamoon** [comment]
Actually you shouldn't be able to enter that date, but youre right it should warn, I'll look at this when I can

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/fe61ca2c97054c678d8108dca50cfa1de58801fb
