### ISSUE TITLE
[BUG] Frontend: Editing date to YYYY-MM-DD is resolved to a day before

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#863]
### Description

I found a weird inconsistency where editing a date using dashes (YYYY-MM-DD) is resolved to a day before. `1999-10-20` is rendered as `10/19/1999`.

### Steps to reproduce

This does not occur when using slashes. `1999/10/20` renders correctly as `10/20/1999`

https://user-images.githubusercontent.com/1429672/166167972-61674295-c26e-4f8c-bae1-5b35da4ec21e.mp4

### Paperless-ngx version

dev

### Host OS

Arch

### Installation method

Bare metal

### Browser

Firefox

### Configuration changes

None, PAPERLESS_DATE_ORDER is default.

**Comment by shamoon** [comment]
I wrote a very long reply but in the end just made a PR 🤪. We should [correctly] accept yyyy*mm*dd, its sort of like the universal format.

Dates, cant live with em, cant live without em, amiright?!

**Comment by qcasey** [comment]
> Dates, cant live with em, cant live without em, amiright?!

lol you could say that again. Thanks for the PR
