### ISSUE TITLE
[BUG] Error on most PDF files

### ISSUE THREAD

**Issue by furchtlos76** [paperless-ngx/paperless-ngx#868]
### Description

Hi, thanks alot for this great tool. I got a really stran ge problem. I Have a brother document scanner and used to use finereader ocr for making my scans ocr readable on synology drive. now i wanted to swap to paperless-ngx. When i move my files, that where ocred by finereader allready i get mostly this error:
PdfError: operation for dictionary attempted on object of type null: returning null for attempted key retrieval
other pdfs work great. Anyone got an idea how to fix this?

### Steps to reproduce

maybe i can send a testfile or something

### Paperless-ngx version

1.7.0

### Host OS

synology docker

### Installation method

Docker

### Browser

chrome

**Comment by qcasey** [comment]
Hello, a test file would be great if that's something you can provide.

**Comment by furchtlos76** [comment]
https://file.io/M75fhFuuV4ll

Here is a little allready ocr made pdf i found that i testet, too. It gives the same error.

Vogelhochzeit.pdf
PdfError: operation for dictionary attempted on object of type null: returning null for attempted key retrieval

Well i could print all those pdfs as pdf again and ocr again, but i wanted to let my setup do the ocr like before and just use paperless-ngx for the rest, should work normaly or?

**Comment by shamoon** [comment]
> https://file.io/M75fhFuuV4ll

file.io
The file you requested has been deleted

**Comment by furchtlos76** [comment]
lol.. another try https://easyupload.io/whxh7v

**Comment by furchtlos76** [comment]
Just found another one https://github.com/pikepdf/pikepdf/files/8282996/empty_pdf_bug.pdf  i dont know if paperless uses pikepdf but the file produces the ssame problem like there. https://github.com/pikepdf/pikepdf/issues/317

**Comment by stumpylog** [comment]
We do utilize pikepdf, so that is likely related.  Loading your provided PDF (thank you) and the one from the upstream report produce an almost exact match to the exception traceback.

However, trying the commands there, I do get an error from QPDF with the document.  So the error is most likely somewhere upstream

**Comment by furchtlos76** [comment]
I could not find out yet, how i could convert my pdf, keeping the OCR layer to import. Tryed alot yesterday, but could not find out whats exactly the difference between some pdfs that work and the majority of my pdfs that dont work :-( if anyone got a idea here please share.

**Comment by furchtlos76** [comment]
I just saw there is a fix (pull request) out that i would try, anyoje here that cna help with "installing" this fix? I am no coder, so maybe i dont understand right, but can this fix be applied with sone commands to my docker so i can start using this great tool? https://github.com/pikepdf/pikepdf/pull/339

**Comment by stumpylog** [comment]
There's not an easy way to apply that kind of fix.  If it is merged, paperless will get the updated version in pretty quickly.

One thing you could try is not allowing finereader to OCR the scans, but allowing paperless to do it.  I'm not sure that would work if finereader is still making the file, but it's an idea.

**Comment by furchtlos76** [comment]
thanks alot, well sure this works with new files but i want to import all my old directory. So i will have to work, no problem

**Comment by furchtlos76** [comment]
Is anyone here that could guide me on how to apply the fix inside my docker container by compiling pikepdf vom source?

**Comment by furchtlos76** [comment]
> There's not an easy way to apply that kind of fix. If it is merged, paperless will get the updated version in pretty quickly.
> 
> One thing you could try is not allowing finereader to OCR the scans, but allowing paperless to do it. I'm not sure that would work if finereader is still making the file, but it's an idea.

I tryed to apply 

*wget "https://patch-diff.githubusercontent.com/raw/pikepdf/pikepdf/pull/339.patch"
git apply "./339.patch"

myself but failed. Is there any way, the developers could include this patch in the next release?

**Comment by stumpylog** [comment]
Our next release will include pikepdf 2.1.3, which fixes this crash.

**Comment by smn57** [comment]
Is there any workaround possible until the new docker image is released? Two months of files piling up and want to be consumed...

**Comment by shamoon** [comment]
You can try to use the `dev` branch in the meantime, of course be careful. We dont have an exact release timeline yet but hoping to release the next version as a beta within the next few weeks. Our team are all a bit scattered/busy at the moment though so hard to be exact at this point.

**Comment by ErrorSource** [comment]
Had the same issue (OCR via FineReader). I have an "bare metal route" installation, not the Docker version:
```
cd /opt/paperless-ngx
vi requirements.txt
```

```
--- requirements.txt.orig	2022-07-08 10:48:46.281186391 +0200
+++ requirements.txt	2022-07-08 10:40:13.334899178 +0200
@@ -62,7 +62,7 @@
 pathvalidate==2.5.0
 pdf2image==1.16.0
 pdfminer.six==20220319
-pikepdf==5.1.2
+pikepdf==5.1.3
 pillow==9.1.0
 pluggy==1.0.0; python_version >= '3.6'
 portalocker==2.4.0; python_version >= '3'
```

```
sudo -Hu paperless pip3 install --upgrade pip
sudo -Hu paperless pip3 install -r requirements.txt
```

This updated pikepdf from 5.1.2 to 5.1.3. As a workaround, of course. Now paperless-ngx can consume my "OCRed" documents.

Unfortunately there's another error:
`Unsupported mime type inode/x-empty : Traceback (most recent call last)`

But this is off topic.

**Comment by smn57** [comment]
@ErrorSource thanks for the hint. I've managed to do the same, but within docker:

`docker exec -it paperless-ng_websever_1 bash` <- replace with your corresponding docker-image name
within the container:
`pip3 install pikepdf==5.1.3`
you'll get a warning you shouldn't do that as root, but I'll take that over an alpha. Thank you, @shamoon, for the suggestion anyway! 

This will probably work as long as I/you don't restart the container. Then just repeat it, after restarting.
