### ISSUE TITLE
[BUG] Tables overflow viewport on mobile devices/small viewports

### ISSUE THREAD

**Issue by ashrude** [paperless-ngx/paperless-ngx#871]
### Description

When viewing a table (eg. the correspondents tab) on a mobile device or small viewport, the table will overflow, and scrolling sideways will reveal the top bar being cut off.

This could be fixed by putting a scrollbar at the bottom of the table.

### Steps to reproduce

1. Go to Correspondents
2. Shrink viewport
3. Observe the correspondents table overflowing the viewport

### Paperless-ngx version

1.7.0

### Host OS

Debian GNU/Linux 11 (bullseye) x86_64

### Installation method

Docker

### Browser

Firefox, Safari, Gnome Web

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/7c2137fcda1638a68fb256723e94929a61bb0dd6
