### ISSUE TITLE
[BUG] Papeless does not work with the latest TIKA and GOTENBERG dockers.

### ISSUE THREAD

**Issue by upuldi** [paperless-ngx/paperless-ngx#876]
### Description

Paperless NGX docker does not work with Tika and Gotenberg dokers. 

### Steps to reproduce

1. Use the latest Gotenberg and Tika images with the latest Paperless NGX docker.
2. Upload a PDF for consumtion.

### Paperless-ngx version

latest

### Host OS

Unraid

### Installation method

Docker

**Comment by qcasey** [comment]
Hello, could you please post your webserver logs when this occurs? I'm pretty sure this will be fixed in the next release, but the logs would confirm that. 

#866

**Comment by gador** [comment]
Not working is a broad description. Without further information this information is rather useless.

**Comment by Profex** [comment]
For me it works perfectly fine using below docker images, running on Synology DSM 

ghcr.io/paperless-ngx/paperless-ngx:latest
gotenberg/gotenberg:7
apache/tika

The only thing I noticed: after watchtower updated apache/tika to latest version yesterday I had to restart gotenberg and tika to get it work again, Before the restart gotenberg was always failing with a 503 service unavailable error when processing a docx file

> {"level":"error","ts":1651645298.3380878,"logger":"api","msg":"convert to PDF: lock long-running LibreOffice listener: start long-running LibreOffice listener: LibreOffice listener socket not available: context deadline exceeded","trace":"1adf0b72-34d4-4917-a9b7-d7231e9847f6","remote_ip":"172.19.0.3","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"python-requests/2.27.1","status":503,"latency":10053228770,"latency_human":"10.05322877s","bytes_in":11903,"bytes_out":19}

**Comment by Spoker** [comment]
I can confirm the findings of @Profex . Now it is working, before I also had the 503 error.
