### ISSUE TITLE
[BUG] Views on dashboard not working

### ISSUE THREAD

**Issue by rsmuc** [paperless-ngx/paperless-ngx#877]
### Description

After clicking on "Show all" button, of a custom view (e.g. Tag: Todo) at the dashboard, the link leads to http://xxxx:8000/documents and not to http://xxxx:8000/view/2.

That only happens, if the view is only shown on the dashboard. If the custom view is also shown at the side panel, everything is working as expected.

![image](https://user-images.githubusercontent.com/6809635/166652037-350ed52e-1993-45d6-a5fa-7581827b86a7.png)

Tag: ToDo --> working
Tag: ToDo2 --> not working

### Steps to reproduce

1. Create a new custom view. (Save as ...)
2. Only add to the dashboard, not to the side panel
3. Click "Show all" at the dashboard. "Show all" does not lead to the correct view.

### Webserver logs

```bash
no relevant logs
```

### Paperless-ngx version

1.7.0

### Host OS

Debian x86_64

### Installation method

Docker

### Browser

Firefox

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/9b8a4900614224ecf62909971321047615cc1855
