### ISSUE TITLE
[BUG] [paperless.parsing] Thumbnail generation with ImageMagick failed

### ISSUE THREAD

**Issue by MrThiemann** [paperless-ngx/paperless-ngx#895]
### Description

when my files consumed, i became the error: 
`[2022-05-07 17:01:07,376] [WARNING] [paperless.parsing] Thumbnail generation with ImageMagick failed, falling back to ghostscript. Check your /etc/ImageMagick-x/policy.xml!`

but not with every document, but felt like every third one... (always different)
<img width="1305" alt="Bildschirmfoto 2022-05-07 um 19 01 42" src="https://user-images.githubusercontent.com/54147030/167264450-96e93f44-a715-40cc-88e4-595975c02b84.png">

### Steps to reproduce

Scan document an uploaded this in `/var/www/uploads`
then i used a script that checked if a new file in "www" and then moved it to `/opt/paperless/consume`

### Webserver logs

```bash
[WARNING] [paperless.parsing] Thumbnail generation with ImageMagick failed, falling back to ghostscript. Check your /etc/ImageMagick-x/policy.xml!
```

### Paperless-ngx version

1.7.0

### Host OS

Proxmox LXC Debian 11

### Installation method

Bare metal

**Comment by qcasey** [comment]
Thank you for reporting. Are you able to share any of these failing documents with us?

**Comment by x4FF3** [comment]
hi, installed my instance today. and also stumbled upon this.

**Comment by StanDaMan0505** [comment]
I also stumbled upon this warning in 1.9.2

**Comment by nsar1907** [comment]
I also stumbled upon this warning in 1.9.2

`[2022-11-28 04:36:32,768] [WARNING] [paperless.parsing] Thumbnail generation with ImageMagick failed, falling back to ghostscript. Check your /etc/ImageMagick-x/policy.xml!`

**Comment by halfbyte** [comment]
I've looked at the file that gets mentioned and I think this might be a hint:

```xml
<!-- disable ghostscript format types -->
  <policy domain="coder" rights="none" pattern="PS" />
  <policy domain="coder" rights="none" pattern="PS2" />
  <policy domain="coder" rights="none" pattern="PS3" />
  <policy domain="coder" rights="none" pattern="EPS" />
  <policy domain="coder" rights="none" pattern="PDF" />
  <policy domain="coder" rights="none" pattern="XPS" />
```

This is from a yunohost paperless-ngx installation. I am no expert in ImageMagick config, but that sounds to me as if it would prevent convert from reading these file types?

**Comment by lordyod** [comment]
Hi, this should probably not be closed. Just did a fresh baremetal install, consumed ~1200 docs, every single one gives this error.

Additionally, when I try to use the admin `document_thumbnails` tool I get the following:

```
root@paperless:/opt/paperless/src# sudo -u paperless ../venv/bin/python3 manage.py document_thumbnails
  0%|                                                                                                                                                                                       | 0/1169 [00:00<?, ?it/s]convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: no images defined `/tmp/paperless/paperless-gkkqedz2/convert.webp' @ error/convert.c/ConvertImageCommand/3342.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: no images defined `/tmp/paperless/paperless-1cd9zbji/convert.webp' @ error/convert.c/ConvertImageCommand/3342.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: no images defined `/tmp/paperless/paperless-rctsafwu/convert.webp' @ error/convert.c/ConvertImageCommand/3342.
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/741.
convert: no images defined `/tmp/paperless/paperless-1cd9zbji/convert_gs.webp' @ error/convert.c/ConvertImageCommand/3342.
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/741.
convert: no images defined `/tmp/paperless/paperless-gkkqedz2/convert_gs.webp' @ error/convert.c/ConvertImageCommand/3342.
```

**Comment by HolgerM1** [comment]
Same her on paperless-ngx 1.13:
 `[WARNING] [paperless.parsing] Thumbnail generation with ImageMagick failed, falling back to ghostscript. Check your /etc/ImageMagick-x/policy.xml!`
This was happening on importing a bunch of PDF I exported from my former DMS.

**Comment by MortRainey** [comment]
https://docs.paperless-ngx.com/setup/

Point 13 did it for me:

> Configure ImageMagick to allow processing of PDF documents. Most distributions have this disabled by default, since PDF documents can contain malware. If you don't do this, paperless will fall back to ghostscript for certain steps such as thumbnail generation.
> 
> Edit /etc/ImageMagick-6/policy.xml and adjust
> 
> <policy domain="coder" rights="none" pattern="PDF" />
> to
> 
> <policy domain="coder" rights="read|write" pattern="PDF" />

**Comment by HolgerM1** [comment]
I'll try that. Thank you!

**Comment by ndom91** [comment]
Just ran into this too on a fresh bare-metal install of `1.14.0-beta.rc1` on a fresh Ubuntu 22.04.

Turns out you have to remove this line from the aforementioned `/etc/ImageMagik-6/policy.xml`. No restart or reload required.

```
<policy domain="coder" rights="none" pattern="PDF" />
```
