### ISSUE TITLE
[BUG] Loading screen disappears even when loading data

### ISSUE THREAD

**Issue by lippoliv** [paperless-ngx/paperless-ngx#896]
### Description

The initial load of paperless-ngx takes quiet some time. This is OK and more transparent since there is the new loading screen (#298).

But especially when my NAS is under high load, the loading screen disappears even if not all data is loaded, which always shoks me for a second because it looks like all data is gone.

![image](https://user-images.githubusercontent.com/2561859/167282170-242b4ee8-587f-44af-ac8e-77588109c52c.png)

I think the loading screen should wait until initial loading is done.

### Steps to reproduce

1. Dump in some documents (in my case ~2400)
2. Give high load to the system
3. Load dashboard

### Paperless-ngx version

1.7.0

### Host OS

Official Docker Image on Synology DSM 7.0

### Installation method

Docker

### Browser

Chrome

### Configuration changes

No

**Comment by shamoon** [comment]
I don’t think this is a bug in the sense that the loading screen shouldnt go away until it loads (as in it’s not set to do that afaik) but my guess is that your system is so slow there’s just a long gap between the handoff to the Angular app. How long are you talking anyway?

**Comment by shamoon** [comment]
Oh you mean the dashboard shows no documents while they’re loading?

**Comment by lippoliv** [comment]
Agreed, whether it's a bug or not is at least discussable. At least if I analyze network traffic I see that multiple requests are fired, containing way more data than needed. I think if this would be improved, the issue I'm facing here would disappear.

> my guess is that your system is so slow there’s just a long gap between the handoff to the Angular app. How long are you talking anyway?

Yes in most cases I just experience this if the system is unter load. Because then it's up to 10 seconds while in normal load it's probably just 1 or 2.

> Oh you mean the dashboard shows no documents while they’re loading?

Exacty. It's not just "empty", but it also looks like a plain installation.

**Comment by lippoliv** [comment]
#899 looks very nice, thanks @shamoon. It'll not fix this issue sill, you agree?.

**Comment by shamoon** [comment]
I think I’m confused about this. Perhaps a video would be helpful if you can. 

If your server is slow to serve the frontend while under load (which is my guess) it’s not something we can fix or even that we can handle, I think. The idea of the PR was to make it obvious when the app is waiting for the backend which is part of what you’re seeing at least.

**Comment by lippoliv** [comment]
Use I can :)

For personal reasons I blured it, but you can follow the sequence I guess.

Now my NAS is not under high load, so things are faster now. For the first ~500ms you see the loading screen. Then for ~1500ms you see the welcome screen asking me to setup the dashbaord and then you see the contents loading.

https://user-images.githubusercontent.com/2561859/167312953-5bb99791-37c3-4eb4-803e-7a0210e8acfa.mp4

I think the loading screen should not just cover the technical laoding of the application, but also the initial loading of the screens content?

**Comment by shamoon** [comment]
Oh I see, thanks for the video. So "best practice" is definitely to load the app asap and load the data into it later asynchronously (its kind of the raison d'être to all these "reactive" javascript frameworks). Yes there needs to be some minimum loading done so that the app looks like itself but yea. Its like the /documents view, initially its empty but you can tell its loading your documents so its "OK"

But I think the same principle applies so I updated the PR to add some more things that should cover the other spots from your video.

BTW, coincidentally I am working on something that will affect the initial loading of the app but in that case the app will really need to wait, I dont think it should in this case while its pulling in things like statistics and saved views, etc.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/2510216f2192712515d1685f2e6ec276e41ff5a5
