### ISSUE TITLE
[BUG] '/api/statistics/' slow

### ISSUE THREAD

**Issue by lippoliv** [paperless-ngx/paperless-ngx#897]
### Description

The statistics endpoint `/api/statistics` should be a very small one. But for me, it takes ~6 seconds to load 47 B. In comparision to `/api/documents/?page=1&page_size=10&ordering=created&tags__id__all=21` which responds in ~700ms with 60 KB, it looks like the statistics endpoint needs to be optimized to be scalable?

### Steps to reproduce

1. Setup (sqlite) docker environment 
2. Dump in some documents (2400 in my case)
3. Call statistics endpoint

### Paperless-ngx version

1.7.0

### Host OS

Official Docker Image on Synology DSM 7.0

### Installation method

Docker

### Browser

Chrome

### Configuration changes

No

**Comment by shamoon** [comment]
As mentioned in your other PR, I think this is more about your setup which sounds like a relatively lower-speed server and is especially slow when under load and so is slow to handle the simultaneous requests that happen upon app startup.

In particular the code for this is incredibly simple, it runs 3 queries on the database (2 if you have no inbox tags) and even though Im not a Django guy, I think this is as "optimized" as this gets...

```python
documents_total = Document.objects.all().count()
        if Tag.objects.filter(is_inbox_tag=True).exists():
            documents_inbox = (
                Document.objects.filter(tags__is_inbox_tag=True).distinct().count()
            )
```

But happy to hear if others think different, it does seem odd that this would ever take 6 seconds...

**Comment by lippoliv** [comment]
> But happy to hear if others think different, it does seem odd that this would ever take 6 seconds...

I personally think it's mainly because of sqlite + 2.400 Documents. But it probably shows a bottleneck in my opinion. It can be improved, if others face the same issue.

There is exactly one situation, where this values do change: Add documents & Delete documents.
So why not pre-calculate those values and cache them in redis? This will speed up the endpoints significantly, I guess.

But I agree, it's complexity which needs to be maintained. So if I'm the only one, you can close this issue down.

**Comment by lippoliv** [comment]
@shamoon some followup:

Today I [moved my data from sqlite to postgresql](https://paperless-ngx.readthedocs.io/en/latest/setup.html#moving-data-from-sqlite-to-postgresql). Now the endpoint is responding within ~200ms while the system is roughly under the same load like yesterday.

Maybe this is an indicator that sqlite is the bottleneck with a higher amount of documents then postgresql?

My system is a DS918+ (INTEL Celeron J3455 with 4x 1.5GHz and 4GB RAM). Plugged in are HDDs, no SSDs.

**Comment by shamoon** [comment]
Yes, definitely. SQLite is not really a particularly performant db but especially as it scales up. I think you'll find a lot of benefit from switching.

Thanks for the follow-up.
