### ISSUE TITLE
[BUG] Importer fails with Umlaut

### ISSUE THREAD

**Issue by HorstyS** [paperless-ngx/paperless-ngx#898]
### Description

Hi,

I had to reinstall my document server (Ubuntu with docker containers). So i first exported everything with the exporter into a dedicated directory, which went fine.
After the reinstall of the server and the docker images via the provided script I started the importer.
I reveive now a lot of errors with e.g.: "The manifest file refers to "Kostenübernahme.pdf" which does not appear to be in the source directory". But the file is there as mentioned in the error message.

What I can see is, that this only happens for files with Umlaute in the filename. All others seem to be okay.

I have to say, I might have had version 1.6 for the export, and now I have 1.7 which was obviously released some days ago. But I also installed 1.6 and tried the import with the same result.

Any idea what might be the issue?

Thanks,
Richard

### Steps to reproduce

1. Export via exporter
2. Import via importer

### Paperless-ngx version

1.7.0

### Host OS

Ubuntu 22.04 LTS

### Installation method

Docker

### Browser

Chrome

**Comment by stumpylog** [comment]
I was able export and import again a file named `Kostenübernahme.pdf`  Could you share the exact error and traceback if any?

**Comment by HorstyS** [comment]
Sure. What exactly would you need?

**Comment by stumpylog** [comment]
Just any output from when you run the command `document_importer somefolder`

**Comment by HorstyS** [comment]
I use:

docker-compose exec webserver document_importer ../export

This results into:

CommandError: The manifest file refers to "2019-12-31 Antrag_auf_Kostenübernahme_einer_Individualbegleitung_für_den_Besuch_e.pdf" which does not appear to be in the source directory.

**Comment by HorstyS** [comment]
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

**Comment by stumpylog** [comment]
You're not going to be able to import from 1.5 anyway.  An in place upgrade should work though.

Unfortunately, as I can't reproduce this at all, it's going to be hard to fix.

1. Start from a clean slate
2. Start the containers
3. Upload a document
4. set the title to something like `Antrag_auf_Kostenübernahme_einer_Individualbegleitung_für_den_Besuch_e.pdf`
5. `docker exec -it paperless-ngx-dev-webserver /bin/bash`
6. `document_exporter ../export`
7. delete document from web ui
8. `document_importer ../export`
9. Document imports and is visible in the web ui

**Comment by tymbu** [comment]
Ah OK, I did the steps as you pointed out and it worked without errors. The deleted file with Umlaut was imported again without errors.

How would I then transfer from 1.5? 1.5 is running in docker on Mac, I want to use 1.7.1 on RaspberryPi. I think I need to move maybe the databases but did not find anything in the documentation.

Would it work to update first to 1.7.1 on Mac, then use the exporter. And importing on RaspberryPi would then be without issues?

Thanks!

**Comment by stumpylog** [comment]
> Would it work to update first to 1.7.1 on Mac, then use the exporter.

Yes, that should work just fine.

How were you running the exporter before?  There must be some difference

**Comment by tymbu** [comment]
Hi stumpylog,
I was running the exporter before on Mac with the normal terminal command as shown in the documentation: 

`docker-compose exec -T webserver document_exporter ../export`

As you recommended, I upgraded to 1.7.1 on Mac which worked fine. Then I exported the documents again using the same terminal command. I then transferred those files to Raspberry Pi, also running 1.7.1. When I started the importer using 

`docker-compose exec -T webserver document_importer ../export`

again, I get the CommandError:

`CommandError: The manifest file refers to "xxxx-xx-xx Übertrag Wertpapiere.pdf" which does not appear to be in the source directory.`

Could it be a problem because the files were generated on Mac but imported on Raspbian?
Do you have any ideas how I could restore my database on the Raspberry?

Thank you!

**Comment by stumpylog** [comment]
Hm, that could be, I've never tried between systems.  The easy test would be trying to import again on the same system (such as a new setup to test with).

**Comment by HorstyS** [comment]
I will set up my Ubuntu server maybe this week and also try some things.
Maybe the issue relates on a code issue while transferring to a new system. I used Filezilla and UTF-8 for the file transfer.

**Comment by HorstyS** [comment]
I just exported and imported the documents to see what happens. I did not move the files or touched them after the export:

![ExpImp](https://user-images.githubusercontent.com/101665247/169229830-bde801ee-636e-4c91-a29f-168723464cca.jpg)

I assume this is not related with the Umlaute issue as it complains about sth different?

**Comment by editwentyone** [comment]
> 

i have the same situation coming form the same hardware, I created on m1 MacBook and exported there. now I want to import it on unraid / linux system and I also think its not working because of the Umlaut problem

**Comment by editwentyone** [comment]
> You're not going to be able to import from 1.5 anyway. An in place upgrade should work though.
> 
> Unfortunately, as I can't reproduce this at all, it's going to be hard to fix.
> 
> 1. Start from a clean slate
> 2. Start the containers
> 3. Upload a document
> 4. set the title to something like `Antrag_auf_Kostenübernahme_einer_Individualbegleitung_für_den_Besuch_e.pdf`
> 5. `docker exec -it paperless-ngx-dev-webserver /bin/bash`
> 6. `document_exporter ../export`
> 7. delete document from web ui
> 8. `document_importer ../export`
> 9. Document imports and is visible in the web ui

I did that as a test with 51 documents on my MacBook m1 where I created the files. the importer imports flawlessly after exporting and deleting by webui

**Comment by cbl789** [comment]
@HorstyS did you get it working now? I have the same problem, migrating from a M1 Mac (Ventura 13.2) to Ubuntu (22.04.1 LTS)
