### ISSUE TITLE
[BUG] Search cannot work with comma sign

### ISSUE THREAD

**Issue by lippoliv** [paperless-ngx/paperless-ngx#922]
### Description

If I use extended search query and I have a comma inside, the query will get cut off.

### Steps to reproduce

1. Open paperless documents view
2. Use extended search and search for "test 12,34 some use" (or use url `/documents?query=test%2012,34%20some%20use`)
3. (If you still see all text in search box, add a space to the end)

![image](https://user-images.githubusercontent.com/2561859/167800531-b7781eba-b7d6-4343-8e80-db76ed1518ea.png)

### Paperless-ngx version

1.7.1

### Host OS

Official Docker Image on Synology DSM 7.0

### Installation method

Docker

### Browser

Chrome

**Comment by stumpylog** [comment]
I can confirm this happens.  Probably a frontend bug?

**Comment by shamoon** [comment]
Yes, I’ll look into it. Though I am curious what the use case is for including commas :)

**Comment by lippoliv** [comment]
@shamoon the stupid Germans which decided to use commas as decimal separation characters xD

And than its me who is about to connect his tax system to paperless API to add invoices documents to outgoing payments...

Sorry for both :P

One thing I found already: the API works fine with the query. It must be an angular thing though...

**Comment by shamoon** [comment]
Haha, oh of course, I didnt think of that! (stupid Americans with no worldly knowledge 😝)

Oh good, Im just glad to know it'll be useful, easy fix

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/d2304312271c9a47bf88d91b2a9fc858e100b0a9
