### ISSUE TITLE
[BUG] Applied tags should be displayed in identical order

### ISSUE THREAD

**Issue by rmayergfx** [paperless-ngx/paperless-ngx#927]
### Description

Installed Paperless-ngx 1.7.1 on Synology DSM 7.1 with docker with this tutorial:
[https://mariushosting.com/how-to-install-paperless-ngx-on-your-synology-nas/](url)
But i got the same problem as already mentioned here in Paperless-ng
[https://github.com/jonaswinkler/paperless-ng/issues/453](https://github.com/jonaswinkler/paperless-ng/issues/453)
when adding tags, also manually they will be viewed in a randomly order.

plz check and confirm. if this is a configuration error from my side plz advice

### Steps to reproduce

just take 2 docs and add 2 identical Tags manually in the same order

### Paperless-ngx version

1.7.1

### Host OS

DSM7

### Installation method

Docker

### Browser

Firefox, Chrome, Edge

### Configuration changes

none

**Comment by rmayergfx** [comment]
Just a short update, After i disabled the dark mode in Chrome, the ordering matches.

**Comment by shamoon** [comment]
The link to the other issue is broken. Can you either explain what you mean more clearly (e.g. all the steps one by one) or upload a video / screenshots?

**Comment by shamoon** [comment]
Oh I see the link now

**Comment by shamoon** [comment]
I cant reproduce this, see video

https://user-images.githubusercontent.com/4887959/167957073-a77ccb9c-b0d8-4e44-9b1c-49b43eb4f949.mov

**Comment by shamoon** [comment]
Sorry if Im not understanding but I still cant reproduce this, regardless of the view style. Again if there are very specific steps needed to recreate this that would be helpful. Or a video. Thanks
