### ISSUE TITLE
[BUG] Filter "Not assigned" is jumpy

### ISSUE THREAD

**Issue by straach** [paperless-ngx/paperless-ngx#929]
### Description

The document filters (document type, correspondent, but not tags) are jumpy. They only select really on a 2nd attempt. First attempt is quickly shown then revoked.

### Steps to reproduce

* Go to documents
* Select a document type
* Wait for filter to apply
* Not click on "not assigned" for the document type
* See that the filter quickly gets set to not assigned but immediately reverts
* Click again "not assigned" and now it works and stays

### Paperless-ngx version

1.7.1

### Host OS

Raspberry Pi arm64

### Installation method

Docker

### Browser

Chrome

### Configuration changes

PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}/{title}

**Comment by straach** [comment]
duplicate of #926

**Comment by shamoon** [comment]
Actually its not working at all, I see the issue, thanks
