### ISSUE TITLE
[BUG] dis-arranged buttons in mobile view

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#931]
### Description

When using paperless-ngx on mobile, at least since version 1.6.0, i am experiencing a not ideal arrangement of the buttons in the documents-view.

is there a way to arrange thos buttons better? or use icons instead of translation text? maybe this distracts the css from properly algining.

![2022-05-12_07-20](https://user-images.githubusercontent.com/88422038/167997809-e472f2f7-d646-409d-914b-e928057cb3b4.png)

### Steps to reproduce

1. go to documents view

### Paperless-ngx version

1.6.0,1.7.1

### Host OS

Android 11

### Installation method

Docker

### Browser

Chrome 101.0.4951.61

**Comment by shamoon** [comment]
German words are long =/ see attached screenshot of English version. Its tough to get the CSS to completely cooperate given the variation in button text length, etc.

<img width="447" alt="Screen Shot 2022-05-11 at 10 27 17 PM" src="https://user-images.githubusercontent.com/4887959/167998492-0b00cce1-a7c5-4c7e-86d8-c864516fc760.png">

**Comment by sukisoft** [comment]
yep, german is never the best option when it comes to languages :D

but i would assume, this problems hits other languages as well, so maybe there is a chance, or an option maybe, to completely use icons instead of buttons when the boundaries are to small?
