### ISSUE TITLE
[BUG] unable to use arrow-keys to naviagte in combo-boxes in document editing

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#932]
### Description

Since 1.7.x it seems, the arrow keys are not working to navigate within the combo-boxes to choose a correspondent or document type. 

I think this is a useful feature since there can be a lot of entries. To type first, and then select out of a smaller entry set is at least to me a pretty known and useful workflow of working withi those elements.

![2022-05-12_07-50](https://user-images.githubusercontent.com/88422038/168001137-a0ae8163-2ea8-4570-8180-84d5610c6799.png)

### Steps to reproduce

1. edit a document
2. select e.g. the correspondent box
3. start typing so that the entries are getting filtered
4. type until u see a subset that matches your needs
5. hit the arrow-down key to select

selection is not working with arrow key.

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04 LTS

### Installation method

Docker

### Browser

Chrome 101.0.4951.64

**Comment by shamoon** [comment]
Its because the text / background color are not visibly different (in other words it is working you just cant see it). I'll sort it out.

**Comment by sukisoft** [comment]
hm. sneaky. thx!

**Comment by shamoon** [comment]
https://github.com/paperless-ngx/paperless-ngx/commit/109b0ea78baa79156a8e1d3e486156fcec77394a
