### ISSUE TITLE
[BUG] Translation error (plural "s" is appended)

### ISSUE THREAD

**Issue by fantasticle** [paperless-ngx/paperless-ngx#937]
### Description

The current version 1.7.1 in German contains multiple erroneous translations.

Korrespondenten => Korrespondent**s**
Dokumenttypen => Dokumenttypen**s**

This looks like a front-end issue appending the English plural "s". I have no clue about JS Frameworks but if you point me in the right direction I will try to figure it out and submit a PR.

### Steps to reproduce

1. Look at the Tab `Korrespondenten`and `Dokumenttypen`

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04 LTS

### Installation method

Docker

### Configuration changes

multiple => irrelevant to this issue

**Comment by shamoon** [comment]
Appreciate the offer but this is not as simple to fix as you might think, but I have a plan, I'll sort it out later.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/38f4bf4e281d100e89c420d6a087c5250ff69562
