### ISSUE TITLE
[BUG] Demo not working

### ISSUE THREAD

**Issue by tooomm** [paperless-ngx/paperless-ngx#940]
### Description

https://demo.paperless-ngx.com/ leads to `Error 521 Web server is down`

### Steps to reproduce

1. Try to open demo instance

### Paperless-ngx version

n/a

### Host OS

n/a

### Installation method

Other (please describe above)

### Browser

Firefox, Chromium

**Comment by tooomm** [comment]
Thanks for the quick fix 👍

**Comment by shamoon** [comment]
Yea, its just under-powered and loves to completely seize up 🙃

**Comment by Vyacheslav-S** [comment]
Today I can't log in with login /pass - demo / demo version!

**Comment by shamoon** [comment]
The demo gets re-created every few hours, looks like someone changed the password (why?) and it wasnt properly being re-created, should be fixed now...

**Comment by Vyacheslav-S** [comment]
> The demo gets re-created every few hours, looks like someone changed the password (why?) and it wasnt properly being re-created, should be fixed now...

Yes, it works now! 
Thanks!
