### ISSUE TITLE
[BUG] Barcode splitting not working with v1.7.1 (file extension detection bug)

### ISSUE THREAD

**Issue by xmd3** [paperless-ngx/paperless-ngx#949]
### Description

After updating to v1.7.1, the new splitting by barcodes feature doesn't work anymore for me.

From what I can tell, the log message `Unsupported file format for barcode reader:` indicates that the file extension calculated in `documents/tasks.py` - [`consume_file` here](https://github.com/paperless-ngx/paperless-ngx/blob/26eb7ecdb50ee8925fa402556a917c562a7b1e8b/src/documents/tasks.py#L237) is empty.

After switching back to v1.7.0, it works again.

### Steps to reproduce

1. Upload multi-page PDF with PATCHT barcode page inbetween (EDIT: via the web ui upload button)
2. After processing, file is not split and shown as one document

### Webserver logs

```bash
2022-05-15 00:00:37,691] [WARNING] [paperless.tasks] Unsupported file format for barcode reader:
[2022-05-15 00:00:37,741] [INFO] [paperless.consumer] Consuming 2022-05-14_02.pdf
[2022-05-15 00:00:37,745] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2022-05-15 00:00:37,751] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2022-05-15 00:00:37,758] [DEBUG] [paperless.consumer] Parsing 2022-05-14_02.pdf...
[2022-05-15 00:00:37,853] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /tmp/paperless/paperless-upload-mmaedjbi
[2022-05-15 00:00:37,915] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/tmp/paperless/paperless-upload-mmaedjbi', 'output_file': '/tmp/paperless/paperless-zycya93h/archive.pdf', 'use_threads': True, 'jobs': '2', 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'sidecar': '/tmp/paperless/paperless-zycya93h/sidecar.txt'}
```

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04

### Installation method

Docker

### Browser

Firefox

### Configuration changes

PAPERLESS_CONSUMER_ENABLE_BARCODES=true  
PAPERLESS_CONSUMER_BARCODE_STRING=PATCHT

**Comment by aytec** [comment]
Yeah, can confirm this, same issue with docker installation and 1.7.1

**Comment by gador** [comment]
Could you post the filename?
The split feature checks for .pdf file extension and it appears that it doesn't find any

**Comment by xmd3** [comment]
> Could you post the filename? The split feature checks for .pdf file extension and it appears that it doesn't find any.
> 
> Also, do you upload per web ui, folder or email?

Good point, I uploaded it via the web ui, I haven't tested the other ways yet.

The filename was `2022-05-14_02.pdf`

**Comment by gador** [comment]
I don't have access to a pc right now, but I suspect the upload through the web ui somehow strips the extension.

I suspect the upload through the folder will work just fine

**Comment by shamoon** [comment]
Well the frontend posts documents to `/api/documents/post_document/` as form-data which gives a random file name like `/tmp/paperless/paperless-upload-n86vou29`, but the file name is of course sent otherwise that data would be lost (this is just how web file uploads work btw, this isnt Paperless per se):
```
------WebKitFormBoundaryATAY199OoXiGIB9r
Content-Disposition: form-data; name="document"; filename="samplefile.pdf"
Content-Type: application/pdf


------WebKitFormBoundaryATAY199OoXiGIB9r--
```

But:
1. That has not changed in a long time, let alone between 1.7.0 and 1.7.1. Im surprised to know it worked in 1.7.0 and not in 1.7.1 since Im not aware of anything that would affect that.
2. I didnt review the original PR but I am surprised to learn it works with file name as opposed to mime-type or something like that, since file naming can be unreliable (not that mime-type doesnt have its problems!).

**Comment by gador** [comment]
The thing that changed is #766

There it checks for file extension and splits if it detects a pdf or Tiff file.

Maybe we should MIME check, or explicitly pass the file name..

**Comment by shamoon** [comment]
Ah yes. Yea I meant no changes on the frontend that would affect that.

I think should use mime IMHO, it’s not perfect but I think still the most reliable method. I suppose could use both mime and file name too

**Comment by aytec** [comment]
right, if i put the same file in the cosume folder, everything works just fine. WebUi doesnt work But good to know, i only tried it via web, to see if splitting works... :)
For me, i`m fine if it works right now, cosume Folder is for me the normal way to scan. :)

**Comment by gador** [comment]
I'll look into it in the coming days. @aytec good to know it works with the folder :+1: 
@shamoon I looked at the code, and maybe we can use it with `override_filename` additionally to the `path` and maybe the MIME detection. That should make it more robust

**Comment by smseidl** [comment]
Fyi I'll agree that this is working in 1.7.1 when processing through file consumption.  I processed many documents last night using this.
