### ISSUE TITLE
[BUG] Pagination can cause loss of in-progress/open document

### ISSUE THREAD

**Issue by seidls** [paperless-ngx/paperless-ngx#955]
### Description

Was editing a document in Paperless-NGX, and needed to go reference some other documents for verification. (By Editing - was adding Tags, adjusting type, correspondent, date, etc). I went to the Documents tab and entered my search criteria, and then started using the "next" arrow to go thru the documents until I found the one I wanted. Once I did, I was unable to find my 'open' document to finish editing/tagging.

**Expected behavior**
Option 1 (**preferred**) - Using the "Next Arrow" should only add the current document into the "Open Documents list". Unless changes were made, the click on "Next Arrow" should close the current document and open the next.

Option 2 - Open/Unsaved Documents should not be bumped off the "Open Documents List" by Pagination. If you try to click the 'X' on an Open & Changed document you get an popup. At minimum pagination should cause this if being bumped.

### Steps to reproduce

1. Open A Document and add a tag - DO NOT HIT SAVE
2. Click on Documents and choose your first document. (You should now have 2 Open Documents like this)![image](https://user-images.githubusercontent.com/27238471/168514739-889b043b-e60a-4a90-b76a-4dd48cf347ed.png)
3.Use the "Next Button" and go forward 5 documents. On the 5th "next" you will loose access to that in progress document
After 4 nexts
![image](https://user-images.githubusercontent.com/27238471/168514731-e7ccc27b-d9de-488a-bac2-ddf51dc34cc3.png)
After 5 nexts (notice the document ending in document_1 is gone:
![image](https://user-images.githubusercontent.com/27238471/168514718-ef2555d1-f9a2-4909-92d3-953cc9531ee6.png)

### Paperless-ngx version

1.7.0 & 1.7.1

### Host OS

Ubuntu 64 bit 20.04 - RPI 4

### Installation method

Docker

### Browser

Edge

**Comment by shamoon** [comment]
Good bug. 

Btw, its not related to #273, its just that opening a doc was never updated to check if the one its going to close had changes.

I'll have it sorted soon

**Comment by smseidl** [comment]
Sounds good.  Looks like you have a PR out there.   I will test that in the next day or two.

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/abc5bd98b4eb4480f9c7a0da7980895cb3185751
