### ISSUE TITLE
[Other] Add prompt to env file for better visibility of pipenv

### ISSUE THREAD

**Issue by Timoms** [paperless-ngx/paperless-ngx#97]
Just a quick QoL change for developing - and an issue to reference a PR.

If we append `export PROMPT="(pipenv-projectname)$P$G"` to the .env file we can get an indicator that we are in the pipenv. 

![image](https://user-images.githubusercontent.com/26655414/154725503-52cfa7a2-cea9-46ee-b061-540464eb37ab.png)

**Comment by qcasey** [comment]
This was implemented in #102, right? I'll close
