### ISSUE TITLE
[BUG] Regular CPU usage spikes

### ISSUE THREAD

**Issue by Pheggas** [paperless-ngx/paperless-ngx#977]
Hello. Today i deployed Paperless-ngx via docker. My setup is: Proxmox -> Ubuntu VM with 6 cores, 12GB RAM, 12 GB Swap -> Docker -> Portainer -> Paperless-ngx. 

After Paperless scanned all my documents, i let it be for like 4 hours now and went to Portainer -> Paperless container -> Graph view and noticed regular CPU spikes each 5 or so seconds.

![image](https://user-images.githubusercontent.com/9994511/168669205-00af8ccb-94b9-444b-ae18-cf2892ed3d92.png)

I'm pretty sure this is not normal behaviour. Do someone have same issue? Is there a fix or it's a bug that need to be fixed by developers?

PS: There are no jobs working (or, i'm assuming). Last logs are from 6 PM (or 18:00 if you're european).

EDIT: Just to see rounded values of CPU usage in Proxmox (one hour interval)
![image](https://user-images.githubusercontent.com/9994511/168675611-bca57943-2bc8-483e-b8c7-2c1f607138c8.png)

_Originally posted by @Pheggas in https://github.com/paperless-ngx/paperless-ngx/discussions/966_

**Comment by qcasey** [comment]
The spike starts about every 10 seconds. What does your configuration look like?

**Comment by Pheggas** [comment]
> What does your configuration look like?

I'm not entirely sure where i could find single file config. Could you please provide default path?

> Could you post what top -o TIME+ shows after a few of these spikes?

Sure. Here you go.
![image](https://user-images.githubusercontent.com/9994511/168886230-938a6472-60c4-43ce-8783-8b80fbaea47d.png)

**Comment by stumpylog** [comment]
The configuration would be anything changed in the `environment` section of your Docker compose or in your `.env` file.  It depends on how paperless was setup.

**Comment by Pheggas** [comment]
>The configuration would be anything changed in the environment section

Right. There are the environment variables

```
PUID=1001
PGID=1001
TZ=Europe/Bratislava
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOME=/root
LANGUAGE=en_US.UTF-8
LANG=en_US.UTF-8
TERM=xterm
PAPERLESS_DATA_DIR=/config
PAPERLESS_MEDIA_ROOT=/data/media
PAPERLESS_CONSUMPTION_DIR=/data/consume
PAPERLESS_OCR_LANGUAGE=slo+eng
```

**Comment by stumpylog** [comment]
I see a regular spike (from about 0.5% to 1%) every 30s.  That's about how often I believe django-q checks for scheduled tasks to be run [here](https://github.com/Koed00/django-q/blob/85baaccd2c3adfe0a414d4237465163e9ff6e5a0/django_q/cluster.py#L284)

I also see these with the LSIO container.  But nothing spiking so large.

**Comment by Pheggas** [comment]
Weird. Is there option to see trace logs? So we can potentially notice unexpected behavior?

**Comment by stumpylog** [comment]
You can enable `PAPERLESS_DEBUG: 1` temporarily and see if anything stands out.

**Comment by lpcvoid** [comment]
I would guess it's the consumer polling too often, this spiked for me too. Try setting `PAPERLESS_CONSUMER_POLLING` to something like 60.
