### ISSUE TITLE
[BUG] When editing multiple files, a pending title change overwrites the title on unrelated open document

### ISSUE THREAD

**Issue by qcasey** [paperless-ngx/paperless-ngx#978]
### Description

A little hard to describe, see video.

When more than one file is open, writing a pending change to a title then clicking to another open document overwrites the title of the second document.

https://user-images.githubusercontent.com/1429672/168848422-67882b85-7036-4817-b71d-277927451f18.mp4

### Steps to reproduce

1. Open 2 documents for editing
2. Change the title of document 1
3. Click the open document 2
4. Change the title of document 2
5. Click the open document 1
6. See title of document 1 has been replaced with the pending change to document 2

### Webserver logs

```bash
n/a
```

### Paperless-ngx version

dev

### Host OS

Arch

### Installation method

Docker

### Browser

Firefox

**Comment by shamoon** [comment]
Ah, funny bug! I get why its happening tho =)
