### ISSUE TITLE
[Other] Dissemination of paperless-ngx (upon first new release)

### ISSUE THREAD

**Issue by shamoon** [paperless-ngx/paperless-ngx#98]
Just wanted to create a list of places to consider announcing this project when the first release is ready.

- [x] Reddit: https://www.reddit.com/r/HomeServer/ & https://www.reddit.com/r/selfhosted/ also suggested  r/datahoarder & r/datacurator ( see [link](https://www.reddit.com/r/selfhosted/comments/tbcuf0/announcing_first_release_of_paperlessngx_the/) )
- [x] Awesome-selfhosted list: https://github.com/awesome-selfhosted/awesome-selfhosted#document-management ( see https://github.com/awesome-selfhosted/awesome-selfhosted/pull/2908 )
- [x] -ng Gitter chat: https://gitter.im/paperless-ng/community
- [x] HA add-on: https://community.home-assistant.io/t/paperless-ng-add-on/269335 (looks like someone already left a comment there)
- [x] linuxserver.io: https://docs.linuxserver.io/images/docker-paperless-ng --> https://github.com/linuxserver/docker-paperless-ngx
- [x] Helm chart [Other] Adjustment of the Helm chart #68
- [x] AUR package https://aur.archlinux.org/packages/paperless-ng ([comment](https://aur.archlinux.org/packages/paperless-ng#comment-855794))
- [x] Perhaps add comments in any PRs / issues we imported (and completed) to let users know the issue / feature has been implemented?
- [x] Potentially blogs: https://mariushosting.com/how-to-install-paperless-on-your-synology-nas/ , https://stadt-bremerhaven.de/dokumentenverwaltung-paperless-ng-mit-docker-auf-einem-synology-nas-installieren/ , https://deployn.de/setup-paperless/

Anywhere else people can think of?

**Comment by Timoms** [comment]
What about a discord server for the community? With a channel for hosting questions and feature request. Binding that with a bot for github would give us awesome community feedback (and maybe even a bigger audience to announce updates etc).

I could make a server and assign groups etc if you want.

**Comment by Timoms** [comment]
> 

Actually, I never hear of Matrix before. 
Discord is widely used (even in topics like homelab and stuff) so most of the "normal" users (especially those coming from reddit) will use discord for chatting. 
Also we could add separate channels / permissions for staff and teams.

**Comment by shamoon** [comment]
Yea this is my first time using matrix, I do already have discord as well. Again I defer to others on this question.

**Comment by yschroeder** [comment]
This guys has a nice manual on how to install paperless on a synology nas which I followed when setting it up myself.

We should notify him to change the URLs.

https://mariushosting.com/how-to-install-paperless-on-your-synology-nas/

**Comment by yschroeder** [comment]
I just noticed that a very popular German tech blog created a similar tutorial two weeks ago. Those people should be notified as well.

https://stadt-bremerhaven.de/dokumentenverwaltung-paperless-ng-mit-docker-auf-einem-synology-nas-installieren/

**Comment by yschroeder** [comment]
And one more German tech blog that I personally don't know but is pretty high up in the Google results:

https://deployn.de/setup-paperless/

**Comment by dblitt** [comment]
Two other subreddits that frequently bring up paperless are r/datahoarder and r/datacurator

**Comment by deployn** [comment]
> And one more German tech blog that I personally don't know but is pretty high up in the Google results:
> 
> https://deployn.de/setup-paperless/

As soon as there is a new container with paperless-ngx, I would happily update
Thanks for mentioning me :)

**Comment by shamoon** [comment]
Oh yea, and as someone mentioned do we try to reach out to @danielquinn and ask about updating the "notice" on the OG homepage? Though I wonder if hes getting tired of that by now... 😑

**Comment by shamoon** [comment]
> As soon as there is a new container with paperless-ngx, I would happily update or make a new post about paperless-ngx Thanks for mentioning me :)

@deployn Update: it's live! Thanks for your support
