### ISSUE TITLE
[Other] Update example config to match the documentation

### ISSUE THREAD

**Issue by Timoms** [paperless-ngx/paperless-ngx#99]
The current example config is just a full fetched config file with every possible configuration. 
We should add some short information to each important part (or even config) so the user doesn't need to open the "big" documentation for each little change.

Especially the upcoming LDAP part should get some line-by-line doc to make each config entry more clearer.

**Comment by qcasey** [comment]
I'm going to close this in favor of #158, it'll be handled in tandem with the rest of the doc updates
