### ISSUE TITLE
[BUG] Newly added tags not showing up for previously added documents

### ISSUE THREAD

**Issue by tylerlucas** [paperless-ngx/paperless-ngx#991]
### Description

I have several documents (OCR working correctly), but newly added tags are not being added for them. If I delete one of the docs and re-upload it the tags show up correctly.

### Steps to reproduce

1. Upload a document and verify OCR is working for a planned tag word
2. Create a new tag using 'any' with the tag word
3. Go to documents section -- the newly added tag does not show up for previously added document

To fix:
1. Delete the previously uploaded doc
2. Re-upload the doc -- the new tag will now appear for the doc

### Paperless-ngx version

1.7.1

### Host OS

Ubuntu 20.04

### Installation method

Docker

**Comment by shamoon** [comment]
See https://paperless-ngx.readthedocs.io/en/latest/administration.html#document-retagger

**Comment by tylerlucas** [comment]
Thanks any idea if there's feature request to add this to GUI? It's unintuitive that a separate command would be required.

Separately, I've tried the document_retagger, but the tags are still not showing up. The output from the retagger doesn't show if tags are being updated.

`tyler@tl-lab-docs:~$ docker exec -it ec8ac32033b2 document_retagger
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 135926.52it/s]`

**Comment by shamoon** [comment]
> Thanks any idea if there's feature request to add this to GUI?

Looks like: https://github.com/paperless-ngx/paperless-ngx/search?q=retagger&type=discussions

I think you need to specify tags, again from the docs:

> Specify any combination of -c, -T and -t to have the retagger perform matching of the specified metadata type. If you don’t specify any of these options, the document retagger won’t do anything.

**Comment by tylerlucas** [comment]
Thanks, that did it
