### ISSUE TITLE
[BUG] minor tooltip-translation issues

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#994]
### Description

I came across some missing tooltip-translations in the documents overview lists (in all 3 modes). See below screenshots.

![2022-05-19_14-58_1](https://user-images.githubusercontent.com/88422038/169463487-aa10e403-6de7-4127-aac2-564150aaf289.png)

![2022-05-19_14-55](https://user-images.githubusercontent.com/88422038/169463517-97aae273-27a1-4321-a2d2-04acbe2540e3.png)

![2022-05-19_14-58](https://user-images.githubusercontent.com/88422038/169463534-e9c813f0-88a5-4c6a-af7e-04bd099212ca.png)

![2022-05-20_06-11](https://user-images.githubusercontent.com/88422038/169463665-3a544042-4655-4ac4-b3df-e4d7ac018bf4.png)

![2022-05-20_06-12_1](https://user-images.githubusercontent.com/88422038/169463682-8e6f86ea-8b0f-4795-bb3b-2a3badbda913.png)

![2022-05-20_08-06](https://user-images.githubusercontent.com/88422038/169463702-8056a00a-fe79-499e-9bc5-c3ba93aa5f60.png)

### Steps to reproduce

1. go to documents-list-view
2. select a document
3. hover on the shown column values

### Paperless-ngx version

1.7.1

### Host OS

synology DSM

### Installation method

Docker

### Browser

Chrome

**Comment by qcasey** [comment]
Thanks for the report. This will be fixed in the next release.  #995
