### ISSUE TITLE
[BUG] Document consumption not following `PAPERLESS_FILENAME_FORMAT`

### ISSUE THREAD

**Issue by tefracky** [paperless-ngx/paperless-ngx#998]
### Description

I use scanimage to scan a document and save it as PDF in the` consumption` directory. The PDF-files are rename by the created date/time. I tried to use `PAPERLESS_FILENAME_FORMAT` to keep the file names, but it is not working or not recognized (or I make something wrong). The files are still renamed to a consecutive number.

### Steps to reproduce

1. Install paperless-ngx via `bash -c "$(curl -L https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"`
2. Add `PAPERLESS_FILENAME_FORMAT={title}` to `docker-compose.env`
3. Run `sudo systemctl restart docker` (I also tried `sudo reboot`)
4. Add a file in the consumption directory

### Paperless-ngx version

1.7.1

### Host OS

Raspberry Pi arm64

### Installation method

Docker

**Comment by stumpylog** [comment]
Did you make the change _after_ the files had already been consumed?  If yes, you should run the [`document_renamer`](https://paperless-ngx.readthedocs.io/en/latest/administration.html#managing-filenames)

If not, try recreating the containers:
1. `docker-compose down`
2. `docker-compose up`

**Comment by tefracky** [comment]
Thanks a lot! I used `docker-compose down` and `docker-compose up` and it works.

Unfortunately, paperless didn't start automatically when booting, so I had to create a corresponding service for it.

But now everything works!
